### PR TITLE
Adding new L2 layout. closes #2426 - Merge into master only after #2422 and #2440 have been merged

### LINKED ISSUE #2426: L2 Template
**Here are the desktop L2s:**

l2 1 desktop db

l2 1 desktop eb

**Here are the mobile L2s:**

l2 1 mobile db

l2 1 mobile eb

### PR DESCRIPTION
**Pull request by webinista**
- Blocked by #2422
- Blocked by #2440
- Merged in changes from master.
- Integrating USWDS grid.
- Changing variable names in grid-settings.scss, grid.scss to avoid collisions with Foundation.
- Adding includes for L2 side bars.
- Updating _disability-benefits/index.md with additional content
- Adding VA Grid overrides, L2 layout styles.

### CODE REVIEW

**Comment by webinista** [comment]
Assigning to you for design review, @angel. When that's done, please assign it to @plusjeff for code review.

**Comment by angel** [comment]
@webinista this is looking good. I had a few tweaks. 

1. Can we have the two paragraphs under the header be the same size as the .primary ps, 1.25em?

2. Can we add more padding to the left of the h3 of the gray bar (20px) and can we have the text and links underneath it to align to that h3 like this?
image

3. Can we add more padding between the in-person assistance block and the phone assistance? Around 40px between them would be good. 

4. Can we add some padding under the map? So there's about 20px from the image to the text. 

5. Can we have the h4 in the sidebar to be 1.2em?

6. Can we have the h4 be the gray dark and the border to be primary darker? <- pending input from @gnakm and @emilyville 

Let me know if any of these don't make sense. Thanks!

**Comment by webinista** [comment]
@angel This is ready for re-review. If you have further changes, re-assign it to me. Otherwise, assign it to Jeff (plusjeff).

**Comment by webinista** [comment]
@angel 

1. How much space should that be between the disclaimer and main content? 
2. Yes, the disclaimer is on a different grid (Foundation). We can target the disclaimers just on the L2 pages until we can fully remove Foundation and integrate USWDS.

**Comment by angel** [comment]
@webinista 

1. 80px: 
image

2. Cool.

**Comment by angel** [comment]
This looks good to me! I think @maryannbrody might have copy changes though.

**Comment by webinista** [comment]
@crwallace Reassigning this to you. I've brought it up to date with master, but you and/or design may want to give it another look in case I've introduced visual regressions with all of this merging.

**Comment by webinista** [comment]
@crwallace I think it makes sense to close this PR and (optionally) delete the branch. There's been a lot of drift between it and `master`. From what I've gathered, our IA and template hierarchy have changed significantly anyway.

**Pull request closed without merging**
