### PR TITLE
Uploads: Verify file extension matches format

### PR DESCRIPTION
**Pull request by Mottie**
## Description

File uploads for Form 526 are being rejected after form submission because the file extension doesn't match the file format (content). Because this rejected happens after the submission, there is no current method in place to inform the Veteran of this problem. Catching the problem prior to upload is the best solution.

This PR checks the extension against the file (mime) type and then searches the file content for a [matching format signature](https://en.wikipedia.org/wiki/List_of_file_signatures). The following file types have been added: pdf, txt, doc, docx, rtf, jpg, jpeg, png, gif, bmp and zip.

The change is applied to the platform FileField, claim status tool uploads and the financial status report upload component (not currently used).

## Original issue(s)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/32402

## Testing done

Added unit tests

## Screenshots

<details><summary>526 Upload file mismatch error</summary>

upload-526-error</details>

<details><summary>Claim Status tool upload file mismatch</summary>

upload-cst-error</details>

## Acceptance criteria
- [x] File extension mismatch error is displayed when the file extension, type and format signature do not match.
- [x] All tests passing

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by CBonade — APPROVED** [review]
Cypress portion of this looks fine to me!

**Review by andresriveratoro — APPROVED** [review]

**Review by LinnJS — APPROVED** [review]
Looks good, and well unit tested 🎉 Thanks for taking the time to update our FileUpload instance 💪🏻

**Comment by Mottie** [comment]
I tried adding some code to check for form elements after the file upload, but I couldn't get it to work properly, so I opt to skip the file checks when running Cypress e2e tests. I didn't check for Cypress specifically, but the Cypress upload test sets the file type to `testing` which is used as a flag.

**Comment by Mottie** [comment]
@CBonade Would you please review the changes. Thanks!

**Review by CBonade — APPROVED** [review]

**Pull request merged**
