### PR TITLE
Updates to pension intro page

### PR DESCRIPTION
**Pull request by jbalboni**
Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3611

There are a few differences from the last comment in the above issue:

- I'm hiding the FDC text that has the TBD links until we get those
- I only listed Work history in the "under 65" section, since that's the only time someone would see that page
- I kept the mention of the VA file number in the first bullet with the SSN, since you can use either of those.

screencapture-localhost-3001-pension-application-527ez-introduction-1499871950070

### CODE REVIEW

**Comment by peggygannon** [comment]
@jbalboni looks good. One minor edit: under Apply, can you add a period after:
 Complete this pension benefits form.

Thank you!

**Review by cehsu — APPROVED** [review]
Looks good to me. Wondering whether it makes more sense to note optional/conditionally required documents, rather than required documents as the section title states "...you'll need your:"

**Comment by jbalboni** [comment]
@cehsu I think the wording means that the military info is required, not the documents, but maybe we can make it clearer? @peggygannon, do you have an opinion on that?

**Comment by peggygannon** [comment]
@jbalboni @cehsu We discussed noting "optional" items, rather than "required" with Alex and Stacy, but the decision was to keep "required" for now, as it follows the style and treatment of the other form intro pages. We will be revisiting this style and how all intro pages are formatted in the next few months.

**Pull request merged**
