### PR TITLE
80690 Update content and layout for CC appointment request detail page

### PR DESCRIPTION
**Pull request by vbahinwillit**
## Summary
This PR updates the content and layout for CC appointment request detail page

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#80690

## Testing done
Unit and e2e testing

## Screenshots
localhost_3001_my-health_appointments_pending_mock5_confirmMsg=true(iPhone 14 Pro Max)
---
localhost_3001_my-health_appointments_pending_mock5_confirmMsg=true(iPhone 14 Pro Max) (1)

## What areas of the site does it impact?
VAOS

## Acceptance criteria
All test must pass

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by jenniemc** [comment]
@vbahinwillit Can you provide the link to the figma design for this PR?

**Comment by vbahinwillit** [comment]
https://www.figma.com/file/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?type=design&node-id=2011-215656&mode=design&t=quNyRczPCM8wsyDi-4

**Comment by vbahinwillit** [comment]
The is the link for the Cancel Confirmation.

https://www.figma.com/file/ColC9ciGHdmp54jXlKuWFM/Redesign-Cancelation-Flow-%7C-Appointments-FE?type=design&node-id=2440-4884&mode=design&t=g2yCwAU3X1q3BFTl-4

**Comment by ryanshaw** [comment]
> @vbahinwillit Can you provide the link to the figma design for this PR?

@jenniemc Just noting that I will take on some of the spacing issues related to the appointment card.

**Comment by jenniemc** [comment]
> Just noting that I will take on some of the spacing issues related to the appointment card.

@ryanshaw , Noted. Just wondering if you're going to handle adding the icon and border around the cancel CC confirmation card?

**Review by jenniemc — COMMENTED** [review]
Since CC requests does not ask for appointment reason, we simply display the booking note if there is any. CC requests does not display reason.

**Comment by ryanshaw** [comment]
> > Just noting that I will take on some of the spacing issues related to the appointment card.
> 
> @ryanshaw , Noted. Just wondering if you're going to handle adding the icon and border around the cancel CC confirmation card?

Yeah, I will add that. This should be for content only.

**Review by ryanshaw — APPROVED** [review]
Looks good. The appointment card and spacing around it will be taken care of via https://github.com/department-of-veterans-affairs/va.gov-team/issues/72652

**Pull request merged**
