### PR TITLE
Pretty print json

### PR DESCRIPTION
**Pull request by kelsonic**
## Description
Pretty prints the JSON for the comparison tool JSON diff.

## Testing done
Locally tested

## Screenshots
image

## Acceptance criteria
- [x] Pretty print json diff for cms export vs graphql

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by mpelzsherman — APPROVED** [review]

**Review by brangi — APPROVED** [review]

**Review by theodur — APPROVED** [review]

**Comment by ncksllvn** [comment]
image

**Comment by micahchiang** [comment]
Screen Shot 2021-02-05 at 1 30 25 PM

**Comment by kelsonic** [comment]
hahaha :trollface: @ncksllvn @micahchiang

**Pull request merged**
