### PR TITLE
July 2018 monthly disability claim average update

### PR DESCRIPTION
**Pull request by jstanek**
Updating the average number of days to complete a disability claim.

### CODE REVIEW

**Review by bethpotts — APPROVED** [review]
Looks good! Thanks, Joe!!!

**Comment by bethpotts** [comment]
@jstanek You can request a review and merge from Sophia.

**Review by 1Copenut — APPROVED** [review]
@jstanek @bethpotts Pulled the branch to my local instance, and verified both updates are correct. Moving to merge now.

**Comment by 1Copenut** [comment]
Two screenshots confirming the changes took on my `localhost` instance:

screen shot 2018-07-02 at 12 34 23 pm

---

screen shot 2018-07-02 at 12 34 46 pm

**Comment by jstanek** [comment]
Merged 7/2/18

**Pull request merged**
