### PR TITLE
Arf 77939 migrate to router v5 compat

### PR DESCRIPTION
**Pull request by williamphelps13**
## Summary

- To align with [Platform React Router Guidelines](https://depo-platform-documentation.scrollhelp.site/developer-docs/react-router-guidelines) we should import router functionality from react-router-dom. This would inherently mean using React Router version 5 instead of what we were currently using (and most of vets-website is using) which is version 3.
- In addition the vets-website package.json has a dependency of react-router-dom-v5-compat@6.3.0 which is a package that allows using the React Router version 6.3 APIs.
- This PR migrates the ARP application to use react-router-dom-v5-compat@6.3.0 and react router 6.3 APIs
- It also updates the corresponding tests to continue work with the changes introduced in 6.3.0
- Benefits Accredited Representative Facing Team

## Related issue(s)

- [#77939 Migrate codebase to react-router-dom-v5-compat](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/77939)

## Testing done

- Navigation from Landing Page to all other pages could occur
- Test all the Links in the ARP application

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.

### CODE REVIEW

**Review by cohnjesse — DISMISSED** [review]
LGTM! Great work Will!

**Review by powellkerry — DISMISSED** [review]

**Review by gabezurita — COMMENTED** [review]
I see [three Code Climate issues](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/pull/29375) we could fix. Would you like us to take care of the following? Up to you!
image

Some suggestions you could try:
### Function Breadcrumbs has 30 lines of code (exceeds 25 allowed). Consider refactoring. 
```
const Breadcrumbs = () => {
  const { pathname } = useLocation();
  const pathSegments = pathname.split('/').filter(Boolean);
  const breadcrumbs = pathSegments.map(buildBreadcrumb);

  return (
    <nav aria-label="Breadcrumb" className="va-nav-breadcrumbs">
      <ul className="row va-nav-breadcrumbs-list">
        <li>
          <Link data-testid="breadcrumbs-home" to="/">
            Home
          </Link>
        </li>
        {breadcrumbs.map(({ link, label }) => (
          <li key={label}>
            <Link data-testid={`breadcrumbs-${kebabCase(label)}`} to={link}>
              {label}
            </Link>
          </li>
        ))}
      </ul>
    </nav>
  );
};

function buildBreadcrumb(segment, index, segments) {
  let pathAccumulator = '';
  segments.slice(0, index + 1).forEach(s => pathAccumulator += `/${s}`);
  return {
    link: pathAccumulator,
    label: formatSegment(segment) // Ensure formatSegment is a defined helper function
  };
}

```

### Similar blocks of code found in 2 locations. Consider refactoring.
```
const RowColumnLayout = ({ leftComponent, rightComponent, leftColClass, rightColClass }) => (
  <div className="vads-l-row vads-u-margin-x--neg2p5">
    <div className={leftColClass}>
      {leftComponent}
    </div>
    <div className={rightColClass}>
      {rightComponent}
    </div>
  </div>
);

// Usage in SignedInViewLayout and other components
<RowColumnLayout
  leftComponent={<Sidenav />}
  rightComponent={content}
  leftColClass="vads-l-col--12 vads-u-padding-x--2p5 medium-screen:vads-l-col--4 large-screen:vads-l-col--3"
  rightColClass="vads-l-col--12 vads-u-padding-x--2p5 medium-screen:vads-l-col--8 large-screen:vads-l-col--9"
/>

```

**Review by gabezurita — DISMISSED** [review]
LGTM!

**Review by gabezurita — APPROVED** [review]
Still LGTM after merge conflict resolution!

**Pull request merged**
