### PR TITLE
Adding Breaks for Link Placement and Formatting 

### PR DESCRIPTION
**Pull request by jstanek**
Adding breaks after links to move links to their own line instead of imbedding within larger blocks of texts

### CODE REVIEW

**Review by peggygannon — APPROVED** [review]
@jstanek Hi, Joe, proofread pass of link placement is complete. I made minor tweaks in some of the files, esp Employment where some word changes were necessary. Overall, the pages look good!

**Comment by peggygannon** [comment]
@DanielleSoCompany Hi, Danielle, here is the link placement PR ready for your review. Joe fixed the in-line links in the Employment section, and some word adjustments were necessary, so those pages should have a more careful review. Thank you!

cc @jstanek

**Review by DanielleSoCompany — APPROVED** [review]

**Comment by DanielleSoCompany** [comment]
Hi @peggygannon. This is ready for you to look into the burials form issue we discussed in slack. Thanks!

**Comment by peggygannon** [comment]
@jbalboni Hi, Jeff. This PR also shows the Pre-need form link in the left nav of the burial/burials-and-memorials/pre-need/ page--"Apply online for pre-need determination of eligibility in a VA National Cemetery." 
I believe this link is showing up b/c it's part of a script or collection? Are you able to take a look at this PR and remove it from the files?

**Comment by jbalboni** [comment]
@peggygannon Should be fixed now, though I don't think it would have shown up in production, because that form is ignored there.

**Comment by peggygannon** [comment]
Thanks, @jbalboni

**Comment by ncksllvn** [comment]
Hi there 👋 Because of the changes involved to meet the requirements of Brand Consolidation, this pull request is unfortunately incompatible with `vets-website` and is being closed as part of a post-launch clean-up effort. However, to make sure the intent of the work is not lost, we're collecting all relevant pull requests into https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15129 and will open a longstanding issue into https://github.com/department-of-veterans-affairs/vagov-content for the visibility of the content and product teams. Thank you and sorry for any inconvenience!

**Pull request closed without merging**
