### PR TITLE
Redo the whole site using metalsmith + webpack; closes #2662

### LINKED ISSUE #2662: Switch from Jekyll to Metalsmith
This will allow a unified frontend build.

### PR DESCRIPTION
**Pull request by awong-dev**
Removes jekyll in favor of a fully node.js solution.

### CODE REVIEW

**Comment by carlmjohnson** [comment]
What is supposed to be in /public/? Is it the directory for files that don't need to be changed for the final version? Normally, the naming convention is something like "assets" for images, fonts, etc. and "public" or "site" for the built files ready to be sent to S3.

**Comment by awong-dev** [comment]
Yeah.. assets might be a better name. This PR is still in heavy flux and is
NOT ready for merging yet. Please keep comments coming!

**Comment by carlmjohnson** [comment]
One thing I don't like about the current project is that the root directory has files that need to go into the final site in it. I think the root directory should have a README and whatever we need to install the project then the rest of the files should be in sub-directories like:

- **content**: Markdown files go here. E.g. homepage is /content/index.md
- **layouts** / **templates**: HTML templates go here
- **src**: Files that need processing like Javascript and Sass go here
- **static** / **assets**: Images, fonts, special files like robots.txt go here. Potentially we may want to add hashes to images and fonts for cache busting purposes
- **public** / **site**: The site generator saves final output here. Probably the process should be something like copy over /static/, process the files in /src/ and save the output into /public/, and finally combine the Markdown and templates.

**Comment by awong-dev** [comment]
@carlmjohnson yup...can you take a look now and see what you think?

The top-level crap was actually because github pages completely barfs on putting the jekyll files in a subdirectory.  Fought that for a week and gave up. :/

**Comment by awong-dev** [comment]
but we don't need to support that anymore so very happily moving things out.

**Comment by carlmjohnson** [comment]
This looks pretty good. I can't get it to build, but I think that's a known issue, right? It might make sense to move sass into src too, but it's probably fine either way.

It's also a little tricky to move to the branch from master because the gitignore is so different, but that's just a one time problem. Once the world has been burnt down, we don't have to worry about it anymore.

**Comment by crwallace** [comment]
closes #2662

**Pull request merged**
