### PR TITLE
Updating Vets.gov to VA.gov 

### PR DESCRIPTION
**Pull request by jstanek**
This ticket includes updates to existing pages that mention Vets.gov. 

All of Sophia's command line search results are here,
https://docs.google.com/spreadsheets/d/1C5CnCWheJsAmpXFmfXB4bS0QKs-tS4gn7a9PVp76BEU/edit#gid=858879292

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by bethpotts** [comment]
@jstanek Four commits were made in the content folder rather than in the va-gov folder. Let's talk about it before you dive in, but these are the commits/files where you'll need to re-enter edits:

Commit 7: Do I need to sign in to VA.gov to apply for a Veteran ID Card?
content/pages/veteran-id-card/how-to-get.md

Commit 8: Frequently Asked Questions about Signing In to VA.gov
content/pages/faq.md

Commit 9: What if I have trouble downloading a VA letter?
content/pages/download-va-letters/index.md

Commit 36: “on our mental health website.”
content/pages/health-care/health-conditions/military-sexual-trauma.md

**Comment by ncksllvn** [comment]
An engineer has to update "Vets.gov" reference in the `src/` directory because those files are shared between Vets.gov and VA.gov, so that value will have to be rendered conditionally. I'm working on it now over at this pull request, https://github.com/department-of-veterans-affairs/vets-website/pull/8747, and will update this pull request once the former is merged. I couldn't do the work here directly because I wanted another engineer to code review my work.

**Comment by ncksllvn** [comment]
Hey @jstanek, hey @bethpotts, while on our call I didn't notice that this branch originated from the now-stale branch `brand-consolidation`, and I couldn't make the changes compatible in this PR. However, I opened a new PR that should capture the work required to the `va-gov` directory here - https://github.com/department-of-veterans-affairs/vets-website/pull/8757.

The pull request for the `src/` directory - https://github.com/department-of-veterans-affairs/vets-website/pull/8747 - has been reviewed and will be merged shortly.

When you're comfortable, I think we can close this PR and pick up at 8757.

**Comment by ncksllvn** [comment]
Hello there 👋 This PR has been migrated to the new content repo and is now located here, https://github.com/department-of-veterans-affairs/vagov-content/pull/27! This was a complicated process, so please check the diff carefully and feel free to reach out if something doesn't look quite right. I'm closing this PR, but the branch will still exist, so your changes will definitely not be lost.

**Pull request closed without merging**
