### PR TITLE
Check in/42028/physical location

### PR DESCRIPTION
**Pull request by brianseek**
## Description
Adds clinicLocation as Location to appointment detail lists.

## Original issue(s)
department-of-veterans-affairs/va.gov-team#42028

## Testing done
Added unit tests for coverage

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by brianseek** [comment]
There is a bot of duplicated code with the AppointmentBlockWithIcons component and the AppointmentConfirmationListItem component. This is caused by the phone appointments feature being dragged out. Once that feature is on and refactored out the AppointmentConfirmationListItem component will be updated and be the sole source of the list code.

**Comment by brdunfield** [comment]
Screen Shot 2022-07-22 at 10 11 23 AM

I am not sure if this was introduced in this PR or the markup changes previously, but this is what the check-in list page looks like in spanish. 😬

**Comment by loripusey** [comment]
Yeah, wrapping seems to be an issue. @brianseek ?

**Review by brdunfield — APPROVED** [review]
LGTM, displays as expected locally! 🦑

**Pull request merged**
