### PR TITLE
Remove rx proxy

### PR DESCRIPTION
**Pull request by alexose**
This is currently not working because the OPTIONS preflight is failing with a 401 error.

The OPTIONS request is not supposed to be authenticated-- Most browsers (chrome included) will automatically strip any Authorization header.  (See: http://stackoverflow.com/questions/15734031/why-does-the-preflight-options-request-of-an-authenticated-cors-request-work-in)

So, in order to get CORS working, we'll need to tweak the server response to allow unauthenticated OPTIONS requests.

### CODE REVIEW

**Comment by alexose** [comment]
@ayaleloehr @saneshark Could I get an update on the unauthenticated OPTIONS part of this?

Wondering if we should just table this...

**Comment by ayaleloehr** [comment]
If the proxy config in build.js is working for people for local development (is it?), then I say we table this. @saneshark will be connecting the API to work require ID.me authentication soon, which will then enable us to remove basic auth from the Rx API, which should resolve this issue on its own?

**Comment by alexose** [comment]
Awesome.  Yeah, once basic auth is gone I think we'll be in business.

**Comment by ayaleloehr** [comment]
Going to closer for now then. Anyone feel free to reopen if the proxy config is causing you heartburn or slowness for any reason.

**Pull request closed without merging**
