### PR TITLE
Have Jenkinsfile use vagov swarm node

### PR DESCRIPTION
**Pull request by njdister**
Ref: department-of-veterans-affairs/vets.gov-team#18570

### CODE REVIEW

**Comment by njdister** [comment]
This is failing pretty early on due to the `checkout scm` stage attempting to use git's SSH transport rather than HTTPS, and I'm not sure where this is coming from as all references in the seed job were updated to use HTTPS transport for github/git.

**Comment by timwright12** [comment]
@njdister Just looking through old PRs for potential clean up, do you know if we still need this or can we close it out?

**Comment by njdister** [comment]
@timwright12 I would guess no, but please check with the current VSP devops team as I haven't been with the project for over a year.

**Comment by timwright12** [comment]
Closing because of age and we're sunsetting Jenkins soon

**Pull request closed without merging**
