### PR TITLE
68991 - SW - [FSR] Back/Cancel A11y fix for Spouse and Employment Records on mini-summary list loops

### PR DESCRIPTION
**Pull request by OptionSelect**
## Summary
Added dynamic text to back cancel buttons based on differing scenarios of entering employment for spouse and vet.
See https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699537353880/d2b2dafa4a375570765ac6d42d27d4ff3d1bc24e?sender=u64758e17a18c4eb2bea93888 for permutations.

ALSO removed unused Component that should've been long gone.

## Related issue(s)

department-of-veterans-affairs/va.gov-team#68991

## Screenshots
Screenshot 2023-12-21 at 1 22 01 PM
Screenshot 2023-12-21 at 1 23 01 PM
Screenshot 2023-12-21 at 1 22 13 PM
Screenshot 2023-12-21 at 1 22 35 PM

## What areas of the site does it impact?

FSR

### Quality Assurance & Testing

- [ X ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ X ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ X ] Linting warnings have been addressed
- [ X ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ X ] Screenshot of the developed feature is added
- [ X ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ X ] Browser console contains no warnings or errors.
- [ X ] Events are being sent to the appropriate logging solution
- [ X ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ X ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by amponce — DISMISSED** [review]
Went through the jobs for `spouse` and `veteran`. Manual testing checks out! 🚀 I'll let Andrew take the final pass

image

image

image

**Comment by Dr-Pongo** [comment]
@OptionSelect 

review won't let me comment on this, but I think the `Cancel` in [EmploymentWorkDates](https://github.com/department-of-veterans-affairs/vets-website/pull/27265/files#diff-bbda558b26a6029d3431fc4def596a181acaafd6259083f45d8a28645590449aR200) needs to be `Back` based on the mural!

**Comment by OptionSelect** [comment]
image

**Review by Dr-Pongo — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
