### PR TITLE
Additional Resources section in GIBCT profile pages

### PR DESCRIPTION
**Pull request by U-DON**
Resolves department-of-veterans-affairs/vets.gov-team#2253.

In addition to the new section in the header, I also tweaked some of the margins between the icon-with-info rows to be more consistent.

### CODE REVIEW

**Review by melwoodard — APPROVED** [review]
LGTM

**Comment by saintsoup52** [comment]
1. Are these additional resources showing up on the GI Bill CT landing page? That was the original intent with this change.

2. In the current version the additional resources disappear on a mobile device. I think we would be OK with that happening here too. Otherwise the additional resources delays users getting to the meat of the tool.

3. Is the video also showing up on the school profile page? I was not there at the Coy meeting but I think I heard that was his request.

**Comment by melwoodard** [comment]
Answers to your questions @saintsoup52:

1. We already show the Apply link on the landing page, and can add the other two there
2. We'll make this change
3. The request to add the video back was only for the landing page. To Stephanie's point from our Tuesday meeting, the main reason for the links to exist on the profile page is to provide next steps for a Veteran is interested in that school, and the video is less critical to that - but I'll point out that it also exists on the page linked to from "Choosing a school". Also, if we were to add the video back it would cause the calculator section to be pushed down and a large amount of empty space between that and the section above it.

@U-DON can you address 1 and 2 above?

**Comment by U-DON** [comment]
Done. No additional resources in mobile, so it will just be the icons with info rows and then the estimate section. Landing page sidebar will look like this:

> screen shot 2017-04-20 at 2 22 47 pm

**Review by melwoodard — APPROVED** [review]
Looks good, thanks!

**Review by bshyong — APPROVED** [review]
LGTM

**Pull request merged**
