### PR TITLE
[Development] HLR updates

### PR DESCRIPTION
**Pull request by Mottie**
## Description

- Updated content per recommendations
  - Included the Additional info dropdown from the contestable issues page inside the alert
  - Changed the title & first sentence of the dropdown (when compared to the component on the contestable issues page - included a screenshot for comparison).
- Switch telephone links to use the Telephone component

Related issues:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/10713
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/11255

## Testing done

Unit tests

## Screenshots

<details><summary>Introduction page - No contestable issues alert (full screen; collapsed)</summary>

</details>

<details><summary>Introduction page - No contestable issues alert (expanded)</summary>

Screen Shot 2020-07-15 at 10 32 35 AM</details>

<details><summary>Introduction page - Network error alert</summary>

<br />
The actual error message (in bold) is included between the two sentences.

Screen Shot 2020-07-15 at 10 36 15 AM</details>

<details><summary>Contestable issues page</summary>

Screen Shot 2020-07-15 at 10 28 54 AM</details>

## Acceptance criteria
- [ ] Content updates are acceptable

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by peggygannon** [comment]
hi, @Mottie I have some additional changes on this messaging. Please see my recommendations below:

**Comment by Mottie** [comment]
cc: @kevinstachura

**Comment by kevinstachura** [comment]
Hey @peggygannon! Great question here:

>I'm not sure we should include a bullet point about requesting an extension without giving users some steps to do so. I would like to give users some information about how to request an extension if they need to. @luke-gcio do you know if this was a SME request to add this bullet point? and if so, do you know how users would request an extension? I can't find anything about this in my research

This absolutely was a SME request, with COVID being a reason for 'good cause' to get an extension. The SMEs did not identify exactly where the user would gain instruction into this process, so I think you are 100% correct on about seeing if we can clarify the process to users. If we do that however, we would likely want to link them to a content page where they could gain more info. Meaning we would need to engage Public Websites into adding that info on a content page. We would also need to find a contextually appropriate page in which to add it.

I think we have a bit of time before this launches (possibly over a month), so we may be able to accomplish this coordination. If for some reason we cannot move all those pieces before launch is imminent, then we can just remove the last bullet point and add it back in later when we have the accompanying content page.

**Comment by peggygannon** [comment]
thank you, @kevinstachura for the background on the SME request to add that bullet about a good cause extension (COVID-related) for Higher-Level Reviews. 

I DID find mention of the good cause extension for claims in our Coronovirus FAQ page and I have updated the last bullet below. 

I do think it's also a good idea for you to reach out to the PW team to see if we need to incorporate content about good cause extensions on the decision review/higher level review static pages. 

Let me know if you have questions or want to discuss in person! 

-------

**You have no issues eligible for a Higher-Level Review**
We don't have any issues on file for you that are eligible for Higher-Level Review. These are called contestable issues. If you think this is an error, please call us at 800-827-1000.

Why isn’t my issue eligible?
Your issue may not be eligible for a Higher-Level Review if:

*We made the decision over a year ago. You have 1 year from the date on your decision letter to request a Higher-Level Review.

*Your issue is for a benefit type other than compensation or pension. To request a Higher-Level Review for another benefit type like health care, insurance, or education, you'll need to fill out Decision Review Request: Higher-Level Review (VA Form 20-0996) and submit it by mail or in person.

*The issue or decision isn’t in our system yet. Please refer to your decision letter about what form you'll need to submit to request a Higher-Level Review.

*You’re unable to request a Higher-Level Review within 1 year from the date on your decision letter due to the COVID-19 pandemic. To request a good cause extension, you'll need to fill out [Decision Review Request: Higher-Level Review (VA Form 20-0996)](https://www.vba.va.gov/pubs/forms/VBA-20-0996-ARE.pdf) and attach a note to your application that you’re requesting an exemption for timely filing due to COVID-19.

To learn more about how COVID-19 affect claims or appeals, please visit our [Coronavirus FAQ page](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#more-benefit-and-claim-questio).

**Comment by Mottie** [comment]
HLR content updates:

I switched the PDF form download links to match the a11y requirements mentioned by @jenstrickland in [this comment](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/152#issuecomment-553127340).

<details><summary>Intro page</summary>


HLR_introduction</details>

<details><summary>Contestable issues page</summary>


HLR_contestable_issues</details>

**Comment by kevinstachura** [comment]
Awesome! Oh just one more question @peggygannon - based on Robin's updated screenshots in his previous comment, how do we want to handle the PDF size in the parenthetical statement? Currently we have it like this:

>_(VA form 20-0996, 1.5MB)_

with a comma separating the size of the form from the form title. Is this how it should look? Would a dash or brackets be a better option? 

**Dash**

>_(VA form 20-0996 - 1.5MB)_

**Brackets**

>_(VA form 20-0996 [1.5MB])_


Just some suggestions for alternatives, but let us know what makes the most sense here. Thanks, Peggy!

**Comment by jenstrickland** [comment]
@kevinstachura @peggygannon Here's the [documentation for handling PDF (and other) links](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/152#issuecomment-553127340).

**Comment by peggygannon** [comment]
Hello, @kevinstachura 

thank you for the updated screenshots @Mottie It looks like a few words got jumbled in these bullet 2 and 4 when download was added. can we fix these two bullets to the below. I've also tightened up the name of the VA form to accommodate the file size. It was getting to be a mouthful for a bullet point. 

- Your issue is for a benefit type other than compensation or pension. To request a Higher-Level Review for another benefit type like health care, insurance, or education, you'll need to [download VA Form 20-0996 (1.5 MB)] and submit a completed application by mail or in person.

- You’re unable to request a Higher-Level Review within 1 year of the date on your decision letter due to the COVID-19 pandemic. To request a good cause extension, you'll need to [download VA Form 20-0996 (1.5 MB)] fill it out and attach a note to your application that you’re requesting an exemption for timely filing due to COVID-19.

**Comment by jenstrickland** [comment]
I would adjust a bit (and include the icon as indicated in the documentation):

<ul>
  <li>Your issue is for a benefit type other than compensation or pension. To request a Higher-Level Review for another benefit type like health care, insurance, or education, you'll need to <a href="#" download>download VA Form 20-0996 <dfn><abbr title="Portable Document Format">PDF</abbr> (1.5 <abbr title="Megabytes">MB</abbr>)</dfn></a> and submit a completed application by mail or in person.</li>

  <li>You’re unable to request a Higher-Level Review within 1 year of the date on your decision letter due to the COVID-19 pandemic. To request a good cause extension, you'll need to <a href="#" download>download VA Form 20-0996 <dfn><abbr title="Portable Document Format">PDF</abbr> (1.5 <abbr title="Megabytes">MB</abbr>)</dfn></a> fill it out and attach a note to your application that you’re requesting an exemption for timely filing due to COVID-19.</li>
</ul>

**Comment by Mottie** [comment]
Updated:

<details><summary>Introduction page</summary>


Intro</details>

<details><summary>Contested issues page</summary>


contested-issues</details>

**Comment by kevinstachura** [comment]
Thanks so much for the support, team! This looks to be in an excellent place based on @Mottie 's updated screenshots, but please let us know if any further changes are necessary.

**Comment by peggygannon** [comment]
@Mottie @kevinstachura @jenstrickland Looks good. thank you, everyone!

**Comment by jenstrickland** [comment]
Once this is in staging, could we show this to @artsymartha68 and @KevinMHoffmanUSDS ? This implementation uses the Download Link pattern that @1Copenut and I worked on, which I believe is being added to the design system (cc @CrystabelReiter). It would be helpful to see if the icon is 👍  or 👎 . It's very clear, certainly. ;)

**Comment by artsymartha68** [comment]
Checking in here, happy to review something if I can access it...? Not sure whether I can or not yet.

**Comment by Mottie** [comment]
> Checking in here, happy to review something if I can access it...? Not sure whether I can or not yet.

It's not accessible on staging yet.

**Review by ndsprinkle — APPROVED** [review]

**Comment by Mottie** [comment]
Sadly, this work can't be tested on staging yet... the backend isn't in sync with the frontend. We're waiting on an update before they work smoothly together.

**Pull request merged**
