### PR TITLE
updating the SSO Info Modal to toggle on the ssoe feature flag

### PR DESCRIPTION
**Pull request by ericbuckley**
Right now its checking to see if the user has a sso session in their local storage.  Because the call to set this only happens if both the `ssoe` and `ssoeInbound` feature flags are set, the info modal won't show for users with `ssoeInbound` disabled.

### CODE REVIEW

**Comment by ericbuckley** [comment]
@hinzed1127 are there any e2e tests that need to be updated to reflect the new changes to the SSO Info Modal?

**Comment by hinzed1127** [comment]
@ericbuckley no, announcements are actually [disabled](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/announcements/README.md#e2e-tests) for e2e tests. updated unit tests should be sufficient

**Review by hinzed1127 — APPROVED** [review]
LGTM to unblock @1Copenut, but we'll need to update this after final changes re inbound sso get finished/merged

**Review by ncksllvn — APPROVED** [review]

**Comment by ericbuckley** [comment]
@ncksllvn do you happen to have any ideas as to why the e2e tests are failing?  http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fvets-website/detail/eb-sso-info-modal-fix/3/pipeline

**Comment by ncksllvn** [comment]
@ericbuckley That particular test just frustratingly fails from time to time...I restarted the build just now

**Review by theodur — APPROVED** [review]

**Pull request merged**
