### PR TITLE
Update and link to caregiver PDF app

### PR DESCRIPTION
**Pull request by melwoodard**
Closes https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3842
- Adds updated version of the 10-10CG application PDF
- Ads link to PDF from health care apply page

image

### CODE REVIEW

**Comment by melwoodard** [comment]
See https://vetsgov-pr-6062.herokuapp.com/health-care/apply

**Comment by J-Quag** [comment]
The PDF has always worked for me, so I want to make sure @amybehrens can access it since I know that her computer was able to recreate the previous issue. 
Otherwise I'm good.

**Review by ghost — APPROVED** [review]

**Comment by amybehrens** [comment]
Hooray!!!! It works! Thanks so much @J-Quag and @melwoodard 

Let me know when it's live and I'll report back to Kelly

**Review by bethpotts — APPROVED** [review]
The text looks good, and the link works! Approved on my end.

**Pull request merged**
