### PR TITLE
Show AlertBox in case of search errors

### PR DESCRIPTION
**Pull request by narin**
## Description

Display an error `AlertBox` if search encounters rate limiting error, or any errors in general.

## Testing done

Mocked redux action using Redux DevTools using the following:

```
{
  type: 'FETCH_SEARCH_RESULTS_FAILURE',
  errors: [
    {
      "title": "Exceeded rate limit",
      "detail": "Exceeded Search.gov rate limit",
      "code": "SEARCH_429",
      "status": "429",
      "source": "Search::Service"
    }
  ]
}
```

## Screenshots

image

## Acceptance criteria
- [x] `AlertBox` shows when `FETCH_SEARCH_RESULTS_FAILURE` action with an array of errors is dispatched.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by bshyong — CHANGES_REQUESTED** [review]
LGTM except for the following:
1. we should also null out `renderResultsFooter()` and `renderResultsCount()` if there are errors
2. Alert Box placement should go above the search bar (results section should remain nulled out in case of error)

**Comment by narin** [comment]
@bshyong Good catch.  Nulled out the footer and results as well.

**Review by bshyong — DISMISSED** [review]
Can we move the alert box on top of the search results box? Just so it’s consistent with the design mock-up

LGTM otherwise! Thanks for grabbing this

**Comment by narin** [comment]
FYI @bshyong, to clarify the dismissal: I believe the build failed due to an unrelated component failing a unit test.  Decided to do some slight refactoring in order to handle layout rearrangement when errors are shown and re-trigger the build.  Please take a look again.  Thanks.

**Review by bshyong — APPROVED** [review]
LGTM. Great refactor

**Pull request merged**
