### PR TITLE
All claims on VA.gov

### PR DESCRIPTION
**Pull request by cvalarida**
## Description
Copies the all claims entry to `va-gov` content directory.

~**Note:** I don't know how to hide this from production off the top of my head, so if this gets merged in as-is, I'm pretty sure it'll make it to preview.va.gov.~

:point_up: Question answered in the comments. Thanks, @ncksllvn!

## Testing done
Checked that it worked with `yarn watch --brand-consolidation-enabled` and `yarn build --brand-consolidation-enabled --buildtype=preview` and serving it from the `build/preview/` directory with `python -m SimpleHTTPServer 3001`.

## Screenshots
image

## Acceptance criteria
- [x] The form is live in staging.va.gov

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by cvalarida** [comment]
@ncksllvn The `production` flag in the markdown file is set to `false`, but it still is accessible when I build with `--buildtype=preview`. How can I make the app available on staging.va.gov but not preview.va.gov?

**Comment by ncksllvn** [comment]
In the markdown file, if you also set `preview: false` then it’ll be removed from that build type too. It works that way for all build types.

**Comment by cvalarida** [comment]
Nifty! Thanks! :raised_hands:

**Review by ncksllvn — APPROVED** [review]
LGTM!

**Review by markgreenburg — APPROVED** [review]
lgtm

**Comment by ncksllvn** [comment]
I hate to say this....but I think since this merged after the `vagov-content` repo was setup, I think we need to copy this change over to that side of town

**Comment by cvalarida** [comment]
Booo. :disappointed:
Thanks for the heads up. :+1:

**Pull request merged**
