### PR TITLE
Health care (WIP content) template updates

### PR DESCRIPTION
**Pull request by melwoodard**
Related: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2155

Updates the WIP health care content with new templates and side navigation.

https://vetsgov-pr-5619.herokuapp.com/healthcare/

Content review should include the following:
- New short names (display_title) for use in breadcrumbs/side nav/previous+next page nav
- Modifications to link sections (previously blue cards + piano keys)
  - Removed links
  - Link sections that need headings for context
- Side nav for different
- Rehomed sidebar content in certain pages

I've written up notes and questions for review and proposed short names for the pages that need them. Updates are highlighted in yellow: https://docs.google.com/spreadsheets/d/1jY8bebVuNmS0Au2KGavtjQYbjQdqTX3TEyqn_X8lYaY/edit#gid=869619117

@rroueche will need to give the SMEs reviewing this content a heads up when this is merged into the main `health-care` branch.

### CODE REVIEW

**Review by peggygannon — COMMENTED** [review]
@melwoodard New Healthcare templates LGTM. I've updated some majorlinks, based on our discussion last week.

**Comment by peggygannon** [comment]
@melwoodard @rroueche Review of WIP Healthcare templates and display titles is complete.  Content changes have been made in the files, and I've created a new issue for incorporating resource links into the healtcare pages' body copy (Issue #3108)

**Comment by melwoodard** [comment]
@peggygannon I reviewed your updates in the spreadsheet, overall looks good! I fixed the After You Apply page so that its related links show up properly now. Can you review whether these links should stay or go? https://vetsgov-pr-5619.herokuapp.com/healthcare/after-you-apply/

**Comment by peggygannon** [comment]
@melwoodard  Thanks. I think the links at on the After You Apply should go. I updated the pages/PR.

**Comment by melwoodard** [comment]
@leannammiller @iantopper can I get a quick look from an engineer to figure out why the build is breaking on this branch? I don't have jenkins configured so I can't look at the errors.

**Comment by iantopper** [comment]
@melwoodard dropped it in Rainbows Slack to see if we can run this down

**Comment by jbalboni** [comment]
There's an e2e test that is failing: `Testing if the page title equals "Refill your prescriptions: Vets.gov".  - expected "Refill your prescriptions: Vets.gov" but got: "Refill Your Prescriptions: Vets.gov"`

**Comment by melwoodard** [comment]
Thanks @jbalboni - I changed the capitalization for those page titles to be consistent with static content pages, so that when they're mixed together in the side nav the capitalization is the same. If I change the capitalization in the test specs will that be ok?

**Comment by jbalboni** [comment]
@melwoodard Yep, that should be fine.

**Pull request merged**
