### PR TITLE
29452 refactor cancel appointment modal

### PR DESCRIPTION
**Pull request by ryanshaw**
## Description
Refactor the CancelAppointmentModal such that:

- It doesn't have the different appointment type conditions (these are not used for homepage refresh)
- Update the component to use connect to Redux directly (using useSelector), rather than needing props to be passed in from the parent component (unless truly necessary).

## Original issue(s)
[department-of-veterans-affairs/va.gov-team/issues/29452](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29452)

## Testing done
- Unit testing
- e2e testing
- Local testing

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by jenniemc — APPROVED** [review]
LGTM!
Nice job refactoring the CancelAppointmentModal and getting rid of the duplicate cancel modals!

**Review by vbahinwillit — CHANGES_REQUESTED** [review]
Should this be behind a feature flag? The different cancel modals are still used for production VAOS.

**Comment by ryanshaw** [comment]
@vbahinwillit Thanks, will take another look.

**Comment by ryanshaw** [comment]
I wanted to document the tested I've done related to the need (or not) for a feature flag. Refactoring led to the removal of the following components:

- `CancelCOVIDVaccineModal.jsx`
- `CancelCernerAppointmentModal.jsx`
- `CancelCommunityCareAppointmentModal.jsx`
- `CancelVideoAppointmentModal.jsx`

I wanted to ensure that these components are not used in production using a user that had **V2 turned off**. I used the `ruben.moreno@id.me` user for the testing.

On staging I looked at Community Care, COVID Vaccine, Video, appointment requests and VA appointments. 

**Community Care prompted the patient to call to make changes**
Wednesday, August 31, 2022 at

**COVID Vaccine promoted the patient to call to make changes**
Thursday, August 25, 2022 at

**Video prompted the patient to call to make changes**
Tuesday, October 11, 2022 at 300

Both VA and appointment requests use the `CancelAppointmentConfirmationModal.jsx` modal. All e2e and unit tests are currently passing too.

**Comment by ryanshaw** [comment]
Also, it is unclear to me currently how to validate the cerner appointment cancel flow.

**Review by vbahinwillit — APPROVED** [review]
LGTM

**Pull request merged**
