### PR TITLE
Electron screenshots

### PR DESCRIPTION
**Pull request by alexose-gov**
Addresses [#1249](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1249).

This is the first and biggest building block in the effort to do visual comparisons across branches.

I’ve hooked into `expectNavigateAwayFrom` in order to trigger screenshots.  This would be fine strategy in the long term except that only the `hca` and `edu-benefits` use this method.  Thus, screenshots only happen for some of the tests at the time of writing.  This will be fixed with [#1251](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1251).

The screenshots don’t run by default.  You’ll want to test them with `npm run test:screenshot`.

Lastly, I ran into some limitations with capturing screenshots of the entire (i.e., full-size) document. I was able to work around this with a library called rasterizeHTML.js.  I wrote some extra functions to inject rasterizeHTML into Electron— This may eventually prove useful for injecting other tools as well.

The next step is to integrate resembleJS to do comparisons.  I expect to have that ready tomorrow (Wednesday) EOD.

### CODE REVIEW

**Comment by alexose-gov** [comment]
The build will start passing once https://github.com/department-of-veterans-affairs/vets-website/pull/4987 is merged...

**Comment by jcmeloni-usds** [comment]
@robbiethegeek-usds My understanding is that this will pass and can be merged after accessibility tests are passing (see #4987) - right?

**Comment by ayaleloehr** [comment]
@robbiethegeek-usds what's the plan here?

**Comment by robbiethegeek-usds** [comment]
This is on hold, and will be closed until there is a front-end engineer that can work on this.

**Pull request closed without merging**
