### PR TITLE
Resolves issue with overly broad .primary p:first-of-type selector

### PR DESCRIPTION
**Pull request by ghost**
**IMPORTANT** Review of this PR should focus on src/sass/modules/_m-alert.scss, and src/sass/base/_va.scss.
 
- Added .va-introtext class. closes department-of-veterans-affairs/vets.gov-team#619
- Make .call-out p, .feature p inherit font, color property values.
- Replaced secondary class with va-alert for alert boxes.
  - Closes department-of-veterans-affairs/vets.gov-team#1470

Affects:

- content/pages/education/apply-for-education-benefits.md
- content/pages/education/apply.md

### CODE REVIEW

**Comment by tiffanybbrown-va** [comment]
Examples of affected content:

screen shot 2017-03-21 at 5 06 39 pm

screen shot 2017-03-21 at 5 20 05 pm

**Comment by jcmeloni-usds** [comment]
LGTM - @melwoodard you ok w/ it?

**Comment by melwoodard** [comment]
@tiffanybbrown-va the intention of https://github.com/department-of-veterans-affairs/vets.gov-team/issues/619 was to remove the `first-of-type` rule entirely and allow the `.va-introtext` class you've created to be manually applied as the content team sees fit, since there are a lot of cases where a page doesn't start out with an intro paragraph. 

It does looks like there's no more weirdness with this style showing up in the first paragraphs of callouts or alerts, but I see other instances where the page doesn't begin with a paragraph, and so `first-of-type` is being applied to the first paragraph that shows up:

https://vetsgov-pr-5145.herokuapp.com/disability-benefits/conditions/ptsd/

posttraumatic_stress_disorder__ptsd___vets_gov

@bethpotts @rroueche can you confirm? You'd rather have to apply this intro paragraph style manually than have it applied automatically, correct? In which case the content team will probably need to help run through all pages and identify where these styles are needed.

**Comment by tiffanybbrown-va** [comment]
@melwoodard I understand the intention of department-of-veterans-affairs/vets.gov-team#619.  This PR is an interim step to resolve this issue for call-out / feature boxes, and give the content team time to update the markup.

Happy to remove the rule entirely, however, since `p:nth-child(1)` should work for first paragraphs without introducing the side effects that `:first-of-type` does.

**Comment by tiffanybbrown-va** [comment]
@melwoodard Please review when you have a chance.

**Review by melwoodard — APPROVED** [review]
LGTM! I've left @bethpotts a list of URLs in the original issue to review that may need some style tweaks, but that doesn't need to block this PR.

**Comment by rroueche** [comment]
Also, confirming -- yes that's correct that we'd like to apply the class manually to text we feel needs the special styling, instead of having the first-of-type rule apply the styles automatically.

**Comment by rroueche** [comment]
although, @melwoodard and @tiffanybbrown-va here's an example where all of the text on the page has the special styling, whereas I'd think w/the rule removed, it would all have the normal p styles:

image

compare:
vets.gov/disability-benefits/claims-process/
https://www.vets.gov/disability-benefits/claims-process/

**Comment by rroueche** [comment]
ah nvm, I see why:
image


so @melwoodard is that an example of a page that you've manually updated w/the class to have that style?

**Comment by melwoodard** [comment]
@rroueche I applied the class to all content pages as part of this PR. I made a list for Beth [here](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/619#issuecomment-288892042) of a few pages that weren't super straightforward on where the intro/body break should happen that we can address separately from this PR.

**Comment by rroueche** [comment]
ok awesome, yeah looks good to me too then!

**Pull request merged**
