### PR TITLE
Updates page title url on appointment detail pages

### PR DESCRIPTION
**Pull request by ryanshaw**
## Summary

This PR changes the URLs and page titles for all of the confirmed appointment detail pages that are rendered as children of `src/applications/vaos/appointment-list/components/ConfirmedAppointmentDetailsPage/index.jsx`

One big change is moving away from using the URL to determine if the `DetailsVA` or `DetailsCC` should be rendered. Instead the appointment object stored in the application state is used.

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/60946
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/61083
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/61084
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/61085

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

- [x] Given the user is on the MHV on VA.gov portal
        When the user clicks on `Upcoming VA appointments`, user will land on the Appointments landing page
        And the user clicks on `Details` link for a booked appointment 
        Then the URL will be updated to: https://va.gov/my-health/appointments/[ID]
        And the page title will be [`VA appointment on [Weekday], [Month] [DD], [YYYY] | Veteran Affairs`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person---upcoming)

- [x] Given the user is on the MHV on VA.gov portal
        When the user clicks on `Upcoming VA appointments`, user will land on the Appointments landing page
        And the user clicks on `Details` link for a canceled booked appointment 
        Then the URL will be updated to: https://va.gov/my-health/appointments/[ID]
        And the page title will be [`VA appointment on [Weekday], [Month] [DD], [YYYY] | Veteran Affairs`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person---upcoming)

- [x] Given the user is on the MHV on VA.gov portal
        When the user clicks on `Upcoming VA appointments`, user will land on the Appointments landing page
        And the user clicks on `Details` link for a Community Care booked appointment 
        Then the URL will be updated to: https://va.gov/my-health/appointments/[ID]
        And the page title will be [`Community care appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#community-care-appointments)

- [x] Given the user is on the MHV on VA.gov portal
        When the user clicks on `Upcoming VA appointments`, user will land on the Appointments landing page
        User will click on the `Pending` link, then clicks on `Details` for a pending appointment
        Then the URL will be updated to: https://va.gov/my-health/appointments/pending/[ID]
        And the page title will be [`[Page Header] | Veterans Affairs`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-request---pending)

- [x] Given the user is on the MHV on VA.gov portal
        When the user clicks on `Upcoming VA appointments`, user will land on the Appointments landing page
        User will click on the `Pending` link, then clicks on `Details` for a canceled pending appointment 
        Then the URL will be updated to: https://va.gov/my-health/appointments/pending/[ID]
        And the page title will be [`[Page Header] | Veterans Affairs`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-request---canceled)

- [x] Given the user is on the MHV on VA.gov portal
        When the user clicks on `Upcoming VA appointments`, user will land on the Appointments landing page
        User will click on the `Past` link, then clicks on `Details`
        Then the URL will be updated to: https://va.gov/my-health/appointments/past/[ID]
        And the page title will be [`VA appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person---past)

- [x] Given the user is on `Upcoming VA appointments` landing page, 
        And the user clicks on `Start Scheduling` button and submits a pending VA appointment
        Then the URL will be updated to: https://va.gov/my-health/appointments/requests/[ID]?confirmMsg=true
        And the page title will be [`[Page Header] | Veterans Affairs`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-request---confirmed)

- [x] Given the user is on `Upcoming VA appointments` landing page, 
        And the user clicks on `Start Scheduling` button and submits a pending Community Care appointment
        Then the URL will be updated to: https://va.gov/my-health/appointments/requests/[ID]?confirmMsg=true
        And the page title will be [`[Page Header] | Veterans Affairs`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#community-care-requests)

## Testing done

- Manual testing on review instance
- e2e testing
- Unit testing
- Local testing

### CODE REVIEW

**Comment by jenniemc** [comment]
@ryanshaw, while past and pending detail pages are displaying correctly, the upcoming detail page are not displaying in the local environment.

**Comment by ryanshaw** [comment]
@jenniemc The routes should be fixed now with an assist from @simiadebowale

**Review by simiadebowale — APPROVED** [review]

**Review by jenniemc — APPROVED** [review]
LGTM!

**Comment by ryanshaw** [comment]
This probably closes [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62826) as well

**Pull request merged**
