### PR TITLE
[WIP] changed gender question on 10-10EZ to what gender is on your dd-214

### PR DESCRIPTION
**Pull request by phiden**
https://app.zenhub.com/workspace/o/department-of-veterans-affairs/vets.gov-team/issues/9028

### CODE REVIEW

**Comment by DanielleSoCompany** [comment]
Hi @peggygannon. This is another one we're looking to resolve or merge. Do you happen to be familiar with this PR in your work on forms? I'm familiar with the gender question issue, but not with this specific PR. Thanks!

**Comment by peggygannon** [comment]
@DanielleSoCompany No, I'm not familiar with this PR.. Maybe Sophia would have more information about this one.

**Comment by phiden** [comment]
This is super old -- months ago, I had a task to change the gender question on a form as an experiment, and that's what this PR is -- but I don't know who the approver would be. Someone on DSVA for sure as it might be a policy question.

**Comment by DanielleSoCompany** [comment]
Thanks, @phiden! I'll try to figure out who might be the best person to look into it. Hope all is going well with your new work!

**Comment by ncksllvn** [comment]
Closed, because I believe this is stale now. Apologies for any inconvenience!

**Pull request closed without merging**
