### PR TITLE
Use webpack for karma tests to enable es6.

### PR DESCRIPTION
**Pull request by awong-dev**
Now both production code AND JS tests are all in es6.

### CODE REVIEW

**Comment by ayaleloehr** [comment]
Don't think I'm the best code reviewer on this, but for my own edification, why did this deploy to Heroku 14 times when it's only 2 commits?

**Comment by awong-dev** [comment]
There were actually probably 14 commits as I was playing with configurations. The final thing you see is the result of me squishing a bunch of stuff and force pushing.

**Comment by awong-dev** [comment]
@ayaleloehr btw, I actually wonder if maybe you are the right code reviewer for this...

I think only Shane has experience with Webpack and Karma. You and Christine are picking up lots of the ops stuff...this is effectively part of ops since it's build infrastructure.

Wanna do the code review to learn it?

**Comment by ayaleloehr** [comment]
Sure. Will look at it tomorrow and come back to you with questions.

**Comment by ayaleloehr** [comment]
LGTM.  Says there are branch conflicts though?  Will leave to you to merge. 

Two things I want to verify for my own edification:
1) You removed `use strict;` in health-care.spec.js. Is this because it's automatically run in strict mode with ES6?
2) I assume npm-shrinkwrap.json is automatically generated from package.json and not that you edited this manually?

Alex's opinion that no one asked for: I don't like that the spec is called ES2015 and that you have to reference it that way. Including '2015' in the spec name seems to imply it is already outdated now that we are in 2016.

**Comment by awong-dev** [comment]
@ayaleloehr Thanks! I will merge.

(1) Yup. `use strict;` is deprecated in ES6.
(2) Yup. I will regenerate on merge. It's `npm-shrinkwrap.json` is basically `Gemfile.lock` for npm.

And yeah...I don't know why they have so many friggin names for this thing.  ES6, ESnext, Harmony, ES2105. Fuuu.

**Comment by awong-dev** [comment]
Rebased and fixed up the npm-shrinkwrap.json conflict by regenerating. Will merge once tests pass.

**Pull request merged**
