### PR TITLE
Content-wip-GIBS-crosslinks

### PR DESCRIPTION
**Pull request by peggygannon**
## Description
Update the crosslinks to the GIBS static page to make them more clear that a GIBS statement of benefits will only be available for a user if they've been rewarded education benefits.

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by ncksllvn — APPROVED** [review]
LGTM!

**Comment by peggygannon** [comment]
@bethpotts PR with updated GIBS crosslinks ready for your review.

**Review by bethpotts — APPROVED** [review]
@ncksllvn I wanted to confirm that Peggy needs to also make these edits in va-gov. Is that right?
@peggygannon For awareness that this work will likely need to be done all over again in va-gov directory.

**Comment by peggygannon** [comment]
Thanks, @bethpotts and @ncksllvn 
A few questions: 
- Do I need to create the new PR on the va-gov directory now (before this PR gets merged to vets.gov)? 
- Or can this PR get merged now onto the current site (vets.gov) and the creation of new PR can happen next week?

**Comment by bethpotts** [comment]
@peggygannon You can work on the second duplicate PR next week. The directories are totally separate.

**Comment by peggygannon** [comment]
@bethpotts Ok, thanks for confirming. 

@ncksllvn if this PR looks OK to you, then this PR can get merged/deployed to vets.gov.

**Review by ncksllvn — APPROVED** [review]

**Comment by ncksllvn** [comment]
@bethpotts @peggygannon Oh no, sorry I missed your question! Feel free to make the changes in both the content and va-gov directories in the same PR if changes need to go into both Vets.gov and VA.gov.

**Pull request merged**
