### PR TITLE
content/wip/add apply by mail to disability apply page

### PR DESCRIPTION
**Pull request by DanielleSoCompany**

### CODE REVIEW

**Comment by kellyskennedy** [comment]
Hiya @bethpotts I added the address change to the pull request Danielle had already created, which was the plan, but then I confused myself...

**Review by bethpotts — APPROVED** [review]
This all looks good to me BUT, please hold off merging until we hear back from Jennifer that the address is correct. Thanks!

**Comment by kellyskennedy** [comment]
Hiya @ncksllvn Could you review and merge, please? Thanks!

**Review by ncksllvn — APPROVED** [review]
LGTM!

**Pull request merged**
