### PR TITLE
Add customMatcher to auto-suggest field

### PR DESCRIPTION
**Pull request by Mottie**
## Description

The provided fast Levenshtein fuzzy matching algorithm does not provide the desired results in Form 526's list of rated disabilities suggestions. This PR adds a `customMatch` ui option that is used instead of the built-in algorithm. We can then optimize the suggested results to match our needs.

I couldn't find any docs to update.

## Original issue(s)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/30061

## Testing done

Added unit test

## Screenshots

N/A

## Acceptance criteria

- [x] Add `customMatcher` ui option to allow customized suggestions
- [x] All tests passing

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by bkjohnson — COMMENTED** [review]
In what ways are the current results not always optimal? In other words, could the existing matching function be improved to be better in all scenarios? Also, if we were to add this as an option to `uiOptions` it would have to be documented somewhere.

**Comment by Mottie** [comment]
> In what ways are the current results not always optimal?

Here is a screenshot from the other PR I have open:



Only the first 3 results should be shown. The remaining suggestions don't make any sense. I at least think that if the suggestion is shorter than the query, it shouldn't be shown.

> could the existing matching function be improved to be better in all scenarios

Yes, there is a ticket regarding this - https://github.com/department-of-veterans-affairs/va.gov-team/issues/6006. I don't know enough about the other usages to make this call.

> if we were to add this as an option to uiOptions it would have to be documented somewhere

I couldn't find any documentation for the auto-suggest component. I'll add it in the global `uiOptions` docs then.

**Comment by Mottie** [comment]
> Based on the screenshot it looks like it should be possible to only show things that actually have that partial match.

Filtering results won't help with misspelling words, I don't have an optimal solution for matching results, but having a custom matcher will allow us to experiment with different methods.
Screen Shot 2021-09-21 at 11 38 57 AM

**Comment by Mottie** [comment]
Also word order is an issue - see https://github.com/department-of-veterans-affairs/va.gov-team/issues/6006

**Comment by bkjohnson** [comment]
We could set a threshold for the score and filter by that, right? I'm not very familiar with the Levenshtein algorithm so I wrote a test script to help give me an idea of what's going on. Here is my output:

image


<details>
    <summary>script/lev.js</summary>

    ```js
    const fastLevenshtein = require('fast-levenshtein');

    function sortListByFuzzyMatch(value, list, prop = 'label') {
      return list
        .map(option => {
          const label = option[prop].toUpperCase().replace(/[^a-zA-Z ]/g, '');
          const val = value.toUpperCase().replace(/[^a-zA-Z ]/g, '');
          let score = label.includes(val) ? 0 : Infinity;

          // if the search term is just one word, split the
          // list into words and find the best match
          if (score > 0 && !val.includes(' ')) {
            score = Math.min.apply(
              null,
              label
                .split(/[ ,]/)
                .map(word => fastLevenshtein.get(word, val))
                .filter(wordScore => wordScore < val.length),
            );
          } else if (score > 0) {
            score = fastLevenshtein.get(label, val);
          }

          console.log(label, score);

          return {
            score,
            original: option,
          };
        })
        .sort((a, b) => {
          const result = a.score - b.score;

          if (result === 0) {
            return a.original[prop].length - b.original[prop].length;
          }

          return result;
        })
        .map(sorted => sorted.original);
    }

    const term = 'nueropathy';
    const options = [
      { label: 'neuropathy' },
      { label: 'muscle atrophy' },
      { label: 'strep throat' },
    ];

    console.log('Matching on', term);
    const suggestions = sortListByFuzzyMatch(term, options);

    console.log(suggestions);
    ```
</details>

With a bit of testing we may be able to decide that the best result is to filter out items with a score greater than X

**Comment by Mottie** [comment]
I'm going to close this PR... we need to improve the core matching algorithm.

**Pull request closed without merging**
