### PR TITLE
Mobile typography

### PR DESCRIPTION
**Pull request by phiden**
See: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/6214

Basically, knock down the text size on mobile devices so that the headers don't take up so much real estate.

### CODE REVIEW

**Comment by melwoodard** [comment]
Fantastic! This looks good to me. Are you ready for PR review from a FE engineer?

Once it's been reviewed, I think the next step should be to keep this PR open and send out a heads up in the vetsdotgov slack w/ links to an example before/after on production and the heroku review instance, and give people a day to give feedback before merging. Does that sound right @suzchap?

**Comment by phiden** [comment]
Yes -- will tag a FE for review, and agree on steps forward. Thanks @melwoodard!

**Comment by suzchap** [comment]
Ohh, that looks so much better!

**Comment by phiden** [comment]
@suzchap do you want to post the preview for buy-in while we wait for PR review?

**Comment by melwoodard** [comment]
@phiden any movement on this? I think we could post the preview for buy-in while we wait for @ncksllvn to review. I'd personally love to see this live sooner rather than later as there's some work coming up in the personalization products that could really benefit from it! :)

**Comment by ncksllvn** [comment]
Oh is this ready for review? Thought it was still a WIP.

**Comment by phiden** [comment]
@ncksllvn please review -- I just don't want to merge it until we have buy-in, which I will try to get now!

**Comment by phiden** [comment]
@ncksllvn it's all yours; feel free to merge too!

**Review by ncksllvn — APPROVED** [review]
LGTM

**Comment by ncksllvn** [comment]
Good work @phiden!

**Pull request merged**
