### PR TITLE
Removed #content.interior a[href^='http://'], .text-capitalize rules

### PR DESCRIPTION
**Pull request by ghost**
Removed #content.interior a[href^='http://'] rule.

- Closes department-of-veterans-affairs/vets.gov-team#1481
- Added [rel=external] selector

### CODE REVIEW

**Comment by tiffanybbrown-va** [comment]
@jkassemi @robbiethegeek-usds Any idea why this may be failing?

**Comment by jkassemi** [comment]
@tiffanybbrown-va - ```
   - Begin application [1;33m(16.941s)[0m
[0;31m   Expected element <.upload-files button.usa-button> text to equal: "Submit Files for Review" [1;37m - expected [0;32m"equal 'Submit Files for Review'"[0m[0m but got: [0;31m"Submit Files For Review"[0m[0m
[0;90m       at /application/test/disability-benefits/e2e/05.claim-additional-evidence.e2e.spec.js:34:15
       at Object.BeginApplication [as Begin application] (/application/test/util/e2e-helpers.js:100:7)[0m

[0;31m ✖ disability-benefits/e2e/05.claim-document-request.e2e.spec[0m

   - Begin application [1;33m(17.073s)[0m
[0;31m   Expected element <.upload-files button.usa-button> text to equal: "Submit Files for Review" [1;37m - expected [0;32m"equal 'Submit Files for Review'"[0m[0m but got: [0;31m"Submit Files For Review"[0m[0m
[0;90m       at /application/test/disability-benefits/e2e/05.claim-document-request.e2e.spec.js:33:15
       at Object.BeginApplication [as Begin application] (/application/test/util/e2e-helpers.js:100:7)[0m
```

I'm going to trigger a re-run now to see if that clears it. Do you ever notice this happening locally? I have a TODO item to build out a quick harness and try to replicate the issue locally, but I haven't prioritized it yet.

**Comment by tiffanybbrown-va** [comment]
Thanks for this @jkassemi Seems moving the "capitalize" declaration to the button changes the _actual_ button text, or at least how it's rendered -- "Submit Files for Review" versus "Submit Files For Review." 

That seems more like a bug with Electron / WebKit or something, but NBD. I can revert that change and create a better fix.

**Review by jcmeloni-usds — APPROVED** [review]
LGTM

**Pull request merged**
