### PR TITLE
Cleanup of Identity feature flags

### LINKED ISSUE #39079: Remove Flipper feature flags
## Issue Description
This ticket tracks the work of removing unneeded Flipper feature flags because of the launch of SSOe and Login.gov that includes but is not limited to:
- `ssoe`
- `ssoe_inbound`
- `ssoe_ebenefits_links`
- `login_gov`
- `login_gov_*`

---
## Tasks
- [x] Removes unnecessary feature flags from the SSOe launch
- [x] Removes unnecessary feature flags from the Login.gov launch

## Acceptance Criteria
- [x] VSP Identity team does not have any unnecessary feature flags in Flipper

### PR DESCRIPTION
**Pull request by asg5704**
## Description
Removes unnecessary feature flags including: `login_gov`, `login_gov_disable`, `login_gov_create_account`, `login_gov_mhv`, `login_gov_myvahealth`, `ssoe`, `ssoe_inbound`, `ssoe_ebenefits_links`

## Original issue(s)
Closes department-of-veterans-affairs/va.gov-team#39079

## Testing done
Unit testing

## Screenshots
n/a

## Acceptance criteria
- [x] All listed feature flags are removed from vets-website
- [x] All listed feature flags are removed from vets-api
- [x] No impact to existing services

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by jgacek — APPROVED** [review]

**Review by it-harrison — APPROVED** [review]

**Review by vbahinwillit — APPROVED** [review]

**Review by adamwhitlock1 — APPROVED** [review]
LGTM as far as the Profile based code changes

**Review by it-harrison — APPROVED** [review]

**Review by lzapson — APPROVED** [review]
caregiver related changes LGTM

**Comment by AGarcia-Clarity** [comment]
👋  Hello may I please get a review from the following teams @department-of-veterans-affairs/vsa-bam-1-frontend @department-of-veterans-affairs/vsa-public-websites-frontend @department-of-veterans-affairs/vsa-ebenefits-frontend @department-of-veterans-affairs/patient-check-in. Thank you 🙏

**Review by acrollet — APPROVED** [review]
health-care-questionnaire changes approved.

**Review by joeniquette — APPROVED** [review]

**Review by ryguyk — APPROVED** [review]

**Pull request merged**
