### PR TITLE
[CI/CD] Update HCA

### PR DESCRIPTION
**Pull request by Mottie**
## Description

- Updated Health Care Application (form 10-10EZ) end-to-end tests; the accordions on the review-and-submit page are now expanded before the axe check.
- Fixed axe errors on the review & submit page
- Cleaned up footer links & content (see screenshots)
- Replaced all telephone links with the Telephone component
- Wrapped all `ET` (eastern time) abbreviations in an `abbr` tag.

I was **not** able to fix the upload issue mentioned in ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/7384. It is an ongoing issue with the combination of Nightwatch & Selenium - see https://github.com/nightwatchjs/nightwatch/issues/890

## Testing done

Updated unit tests; all passing
Updated e2e test; upload test not passing locally, but should pass in CI.

## Screenshots

<details><summary>Footer (before & after)</summary>

### Before
Screen Shot 2020-06-09 at 12 18 36 PM

### After
Screen Shot 2020-06-09 at 3 08 27 PM</details>

## Acceptance criteria
- [x] HCA e2e tests all passing
- [x] HCA review & submit page does a11y testing with all accordions open
- [x] Axe tests passing on all pages
- [ ] Footer content update is acceptable

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by Mottie** [comment]
This PR will be replaced by https://github.com/department-of-veterans-affairs/vets-website/pull/13119, once it's been merged.

**Review by rianfowler — APPROVED** [review]
We may want to update the codeowner for this and remove the FE review group.

**Comment by Mottie** [comment]
> We may want to update the codeowner for this and remove the FE review group.

I don't know who owns this form. I was just asked to take care of the e2e tests. I think I'll hold off on merging this PR either way, since there is already a PR to replace these Nightwatch tests with Cypress tests.

**Comment by Mottie** [comment]
Replaced by https://github.com/department-of-veterans-affairs/vets-website/pull/13119

**Pull request closed without merging**
