### PR TITLE
VFEP-searchvfep-search-url-error Resolve Search Error.

### PR DESCRIPTION
**Pull request by GovNapoleon**
## Summary

-  VFEP-searchvfep-search-url-error Resolve Search Error.

## Problem

MicrosoftTeams-image (2)

### CODE REVIEW

**Comment by randimays** [comment]
I'm not able to see the search results on the review instance. Maybe something weird going on in the CI?

Screenshot 2024-02-29 at 10 51 34 AM

Screenshot 2024-02-29 at 10 51 22 AM

**Comment by GcioNapoleon** [comment]
@randimays just finished pushing a potential solution and I'm waiting for the review instance to update.

**Comment by GcioNapoleon** [comment]
@randimays all tests are passing waiting for the review instance to update.

**Comment by GcioNapoleon** [comment]
@randimays I just finished confirming the solution in stage

Screenshot 2024-02-29 at 12 38 53 PM

**Review by randimays — APPROVED** [review]
LGTM!

**Review by Andrew565 — APPROVED** [review]

**Pull request merged**
