### PR TITLE
Email capture form for VIC

### PR DESCRIPTION
**Pull request by bshyong**
⚠️  Please merge the associated API pull request first https://github.com/department-of-veterans-affairs/vets-api/pull/1575

Screenshots:

### Initial state
screen shot 2017-12-03 at 11 19 22 am

### Error state
screen shot 2017-12-03 at 11 19 28 am

### Success state
screen shot 2017-12-03 at 11 20 44 am

Resolves https://github.com/department-of-veterans-affairs/vets.gov-team/issues/6449

### CODE REVIEW

**Comment by jkassemi** [comment]
Getting a review instance online to pair this with vets-api changes for testing. Looks great!

Will reach out now for content review so we can get confirmation and make any required updates.

**Comment by jkassemi** [comment]
For the record, review instance builds do not trigger the `__VIC_RATE_LIMIT_ENABLED__` feature. SSH into the review instance, run the build with `VIC_RATE_LIMIT_ENABLED=true API_URL=http://b5ee8b0d85b7000cca1eef4d8c25c863-api.review.vetsgov-internal BASE_URL=http://b5ee8b0d85b7000cca1eef4d8c25c863.review.vetsgov-internal npm run build -- --buildtype=development`.

Might be nice to be able to specify additional ENV settings from Jenkins.

**Comment by jkassemi** [comment]
Review instance: http://b5ee8b0d85b7000cca1eef4d8c25c863.review.vetsgov-internal/

**Review by jkassemi — APPROVED** [review]
Tests successful!

**Comment by bshyong** [comment]
@jkassemi feel free to merge this when ready

**Comment by jkassemi** [comment]
Thanks @bshyong - just getting the vets-api deployments out now, then will get a merge and PR out for production release.

**Comment by amybehrens** [comment]
**Landing page**
Yellow box language works as is. 

In the meantime, please enter your email address below and we'll send you an alert when it's available. Note: We will only use your email about the Veterans ID Card. See our [privacy policy](https://staging.vets.gov/privacy/). 

Email box
Submit button

-----
**Success message**
We received your email address. We'll send you an email when the Veterans ID Card system is available. 


^ @kerryilenahan @bethpotts is that ok by you?

**Comment by melwoodard** [comment]
@goldenmeanie and I were wondering if it makes sense to lead the yellow box language with an apology, as well as tweaking the wording to make it clear that the high volume of traffic is causing problems with loading the application:

> We’re sorry, we’re experiencing a high volume of traffic and are unable to submit your request for a Veteran ID card right now. We’re working to fix the problem, but it may take a little while.

@amybehrens @bethpotts thoughts?

**Comment by bethpotts** [comment]
@kerryilenahan @amybehrens @jkassemi @leannamiller

Plain language suggestion:

YELLOW BOX
Thank you for your interest in the Veteran Identification Card. If your application isn't going through, it's because our system is having trouble handling the many requests for cards. We apologize, and we want you to know we're working to fix the problem as quickly as we can.

BELOW YELLOW BOX
If you'd like us to let you know when the application is working again, please enter your email address here. Note: We'll use your email only to contact you about the Veteran Identification Card. See our privacy policy.

Email address (@jkassemi the "A" in "address" should be lowercased)

GREEN EMAIL RECEIVED BOX
Thank you for your email address. We'll let you know when the application is working again.

**Comment by bethpotts** [comment]
@kerryilenahan @amybehrens @jkassemi @leannammiller

REWRITTEN TO LEAD WITH THE APOLOGY

Plain language suggestion:

YELLOW BOX
We're sorry your application isn't going through. Our system is having trouble handling the many requests for cards, and we're working to fix the problem as quickly as we can.

BELOW YELLOW BOX
If you'd like us to let you know when the application is working again, please enter your email address here. Note: We'll use your email only to contact you about the Veteran Identification Card. See our privacy policy.

Email address (@jkassemi the "A" in "address" should be lowercased)

GREEN EMAIL RECEIVED BOX
Thank you for your email address. We'll let you know when the application is working again.

**Comment by jkassemi** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/6903/ has copy updates for review @bethpotts

**Comment by bethpotts** [comment]
@jkassemi Can you send me screen shots?

**Comment by bethpotts** [comment]
@jkassemi Also, in looking at the commit, it seems like you'll need to link "See our privacy policy." I'm sorry I wasn't clear about that. Amy had linked it in her suggestion, but I left out the link! The page is located here: https://www.vets.gov/privacy/

**Comment by jkassemi** [comment]
@bethpotts thanks! Added a link to the privacy policy, and comments in the PR. Let's move further discussion there?

**Pull request merged**
