### PR TITLE
Adding support for og:description

### PR DESCRIPTION
**Pull request by robertfairhead**
Closes https://github.com/department-of-veterans-affairs/vets-website/issues/5889
Closes https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3601
Part of https://github.com/department-of-veterans-affairs/vets.gov-team/issues/612

Adds support for og:description meta tags in our headers
Puts an initial description on the GIBCT landing page

### CODE REVIEW

**Comment by saintsoup52** [comment]
Sorry for not knowing this... But any particular reason why the entryname is just "gi" and not "gi bill"?

Also is there an ideal character limit for the page description? I imagine VA EDU might want to put a little more descriptive explanation of why people should use the comparison tool.

Lastly... since GI Bill is a registered trademark do we need to include the (r) there too?

**Comment by robertfairhead** [comment]
No particular reason on `gi` versus anything else that I'm aware of. The entryname is only really used internally by the front-end build system so it doesn't impact the Veterans, SEO, etc. in any meaningful way. The only restriction on it is that it couldn't have a space.

For the page description, Google (and the other engines) do not publish any specific numbers. That's an internal thing for them. I'm not an SEO specialist, but it's roughly two lines at roughly 75-80 characters per line, so something in the range of 150-160 characters would be reasonable. 

With respect to the registered trademark symbol, the phrase isn't used in the new description and the rest of the page's copy have already been reviewed and approved by the appropriate VA stakeholder, so I wouldn't be in a position to change that here.

**Comment by ayaleloehr** [comment]
pinging @melwoodard , but feel free to redirect if you think there is someone better to review.

**Comment by melwoodard** [comment]
@ayaleloehr makes functional sense to me, though I'd appreciate a look from someone more familiar with meta tags.

**Review by cvalarida — APPROVED** [review]
I poked around for a bit, looking at how to make metatags useful, and this looks great.

It did look funny without the self-closing bit in there, but Google tells me that's right.

🚀

**Pull request merged**
