### PR TITLE
VACMS-18287 Remove new tab behavior per DST guidelines

### PR DESCRIPTION
**Pull request by randimays**
## Summary
Per Design System guidance, links should only open in a new tab if the user will lose some data or progress. This PR includes updates to:

**Find Forms**
- Removes `target` and `rel` attributes from download links as a download link wouldn't open in a new tab anyway
- Removes new tab from "GSA Forms Library" link
- Removes the `deriveLinkPropsFromFormURL` utility and its usage. Previously this utility was used to apply props to an `<a>`, and now that element is a `<button>` that opens a modal so none of these props are applicable anyway.

**Discharge Upgrade Wizard**
- Adds `(opens in a new tab)` and new tab behavior to every link on the results page, as they will all cause a user to lose progress/data if they are clicked

**Events search**
- Removes new tab from "Get directions on Google Maps" links

**Mega menu and footer**
- Removes target attribute from the links. They were previously added as though they would be set coming from Drupal, but there is no way to set a target attribute in Drupal, so these were never used.

Also includes an adjustment to the 404 page as the test started failing in CI. Slack thread for context: https://dsva.slack.com/archives/CBU0KDSB1/p1719341196473059

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18287

## Testing done
Tested the applications locally at:
- `/find-forms`: Search for forms and inspect the results' links and modal triggers
- `/discharge-upgrade-instructions`: Go through several flows for different military branches and view the results page (including the accordions at the bottom). All links should open in a new tab and also have the `(opens in a new tab)` text next to them
- `/outreach-and-events/events`: Search for events and inspect the results' Google links
- `/` (home): Inspect the mega menu and footer links

## Screenshots
<details><summary>Find Forms</summary>
Screenshot 2024-06-24 at 5 21 59 PM
Screenshot 2024-06-24 at 5 22 05 PM

Screenshot 2024-06-24 at 5 24 28 PM
Screenshot 2024-06-24 at 5 22 32 PM
Screenshot 2024-06-24 at 5 25 09 PM

Screenshot 2024-06-24 at 5 26 25 PM
Screenshot 2024-06-24 at 5 26 32 PM

</details>

<details><summary>Discharge Upgrade Wizard</summary>
Screenshot 2024-06-25 at 10 07 00 AM
Screenshot 2024-06-25 at 10 06 51 AM
Screenshot 2024-06-25 at 10 06 48 AM
Screenshot 2024-06-25 at 10 06 43 AM
Screenshot 2024-06-25 at 10 05 04 AM
Screenshot 2024-06-25 at 10 01 50 AM
Screenshot 2024-06-25 at 10 01 47 AM
Screenshot 2024-06-25 at 10 01 41 AM
Screenshot 2024-06-25 at 10 01 35 AM
Screenshot 2024-06-25 at 9 54 49 AM
Screenshot 2024-06-25 at 9 54 46 AM

</details>

<details><summary>Events</summary>
Screenshot 2024-06-24 at 5 19 58 PM
Screenshot 2024-06-24 at 5 20 11 PM

</details>

### CODE REVIEW

**Review by carlosfelix2 — APPROVED** [review]

**Review by rsmithadhoc — APPROVED** [review]

**Comment by randimays** [comment]
@laflannery The review instance won't come back up. This can be tested locally if you wish, but otherwise there are screenshots in the PR description. I would spin up a Tugboat but they don't pick up vets-website branches.

**Review by chriskim2311 — APPROVED** [review]
LGTM! Tested locally great work

**Comment by laflannery** [comment]
@randimays I looked at the screenshots and those all look good. 2 clarifying questions:
1. For reference, does the events update also apply to VAMC events pages, like `/boston-health-care/events/`? I feel like typically events changes apply to both these listing pages but want to be sure
2. For the meganav and footer links, there weren't screen shots so I want to be sure - we aren't opening anything in a new tab there right?

**Comment by randimays** [comment]
@laflannery Whoops, I didn't add screenshots because the target and rel attributes weren't being used and aren't there in prod. In prod today, nothing opens in a new tab in the header and footer, so nothing should have changed.

Mega menu
Screenshot 2024-06-28 at 9 27 09 AM

Footer
Screenshot 2024-06-28 at 9 27 09 AM

**Review by laflannery — APPROVED** [review]

**Pull request merged**
