### PR TITLE
[Messaging] Updated API queries for folders.

### PR DESCRIPTION
**Pull request by U-DON**
API updated the `meta` object for folder messages, so I updated the names for the keys we used to access that data.

Also now fetching both a folder and its messages when loading up a folder, doing away with the need to use the folder id to look it up within the array of folders in state.

### CODE REVIEW

**Comment by U-DON** [comment]
Still updating to get pagination for folders working, actually, now that it's properly paginated on the API side.

**Comment by webinista** [comment]
LGTM

**Comment by U-DON** [comment]
Updated with more changes, particularly navigation through pages of messages in a folder.

**Comment by webinista** [comment]
LGTM.

**Pull request merged**
