### PR TITLE
Update FrontEndTests101.md

### PR DESCRIPTION
**Pull request by annekainicUSDS**
Updated docs to reflect additional conversational during front-end sync up.

### CODE REVIEW

**Comment by jbalboni** [comment]
@annekainicUSDS One thing we could mention is how to run tests with code coverage (`npm run test:coverage`). That is sometimes useful.

I think we're going to turn off code climate, but I think it would be great to have a tool like that focused only on code coverage, so we could see how well we were doing writing tests. Something like Coveralls.

**Comment by annekainicUSDS** [comment]
@jbalboni thanks for the suggestion! added some notes on the code coverage thing

**Comment by ncksllvn** [comment]
Great work @annekainicUSDS! Just an idea, but do you think we should put notes from these meeting in their own directory within `docs/`? Our docs are super useful but kind of hard to navigate at the moment.

**Comment by annekainicUSDS** [comment]
@ncksllvn totally agree about needing to clean up the organization of our docs folder. I think that should be a separate task to review things in total and figure out a new organization, and then also rework the README and create a table of contents linking to things.

**Comment by ncksllvn** [comment]
@annekainicUSDS Perfect, that's a great plan! Thanks!

**Comment by annekainicUSDS** [comment]
@ncksllvn do you mind approving so I can merge? Thanks!

**Review by ncksllvn — APPROVED** [review]

**Comment by ncksllvn** [comment]
@annekainicUSDS whoops sorry, thought I already did!

**Pull request merged**
