### PR TITLE
Add validation error event when review page validation fails

### PR DESCRIPTION
**Pull request by jbalboni**
Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3119

### CODE REVIEW

**Review by cvalarida — APPROVED** [review]

**Comment by cvalarida** [comment]
FYI @robertfairhead per [your request](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3119#issuecomment-306241978).

**Review by cehsu — APPROVED** [review]
LGTM.

**Comment by robertfairhead** [comment]
So all the Edu apps and HCA should be emitting these events soon, right? I'll definitely have to add a handler for HCA. Edu should pick it up automatically, but I'll confirm that.

**Comment by jbalboni** [comment]
@robertfairhead Correct, starting with tomorrow's deploy.

**Comment by robertfairhead** [comment]
Ok, I updated the HCA config to be more generic, similar to the Edu one so that it'll catch any events with its prefix from the form schema config.

I need to give a little thought about how to better handle the event reporting for forms. I'll probably open an issue tomorrow with some initial thoughts.

**Pull request merged**
