### PR TITLE
Make entire VCL banner clickable

### PR DESCRIPTION
**Pull request by jbalboni**
## Description
This makes the entire red VCL banner clickable, instead of the inner button.

## Testing done

Tested locally at different screen sizes, checked IOS 9 iPad on Browserstack

## Screenshots
screen shot 2018-10-19 at 10 43 19 am
screen shot 2018-10-19 at 10 43 08 am
screen shot 2018-10-19 at 10 43 00 am
screen shot 2018-10-19 at 10 44 36 am

## Acceptance criteria
- [x] Entire VCL banner is clickable

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by emilywaggoner — APPROVED** [review]
Wooo looks great! Thanks!

**Review by ncksllvn — APPROVED** [review]
LGTM!

Does this have any impact on https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14298?

**Review by cehsu — APPROVED** [review]
LGTM.

**Review by rianfowler — APPROVED** [review]

**Comment by jbalboni** [comment]
@ncksllvn Not that I know of.

**Pull request merged**
