### PR TITLE
21013 Form Removal Combat Zone

### PR DESCRIPTION
**Pull request by ashagross**
[21013](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21013) 526 Removal of Combat Zone form.

## Description
Removal of combat zone form from 526ez 

## Testing done
visual/manual

## Screenshots

[Previously lived](http://localhost:3001/disability/file-disability-claim-form-21-526ez/review-veteran-details/combat-status)

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by Mottie — CHANGES_REQUESTED** [review]
This looks great! Please update (remove the values in) the mock data in the `src/applications/disability-benefits/all-claims/tests/fixtures/data` folder, but no rush!

Anyway, let's put this on hold on merging this until we verify that the backend is ready for the change and that EVSS won't reject submissions missing this value.

**Comment by annaswims** [comment]
Please remove it from here as well https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/schemas/21-526EZ-allclaims/schema.js

If this is your first time updating vets-json-schema this is useful https://github.com/department-of-veterans-affairs/vets-json-schema#development

**Comment by annaswims** [comment]
I haven't made the corresponding changes to the BE so I made a ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/25173

**Comment by annaswims** [comment]
What happens if someone was on the combat status page and then try to resume their form?

Just checking - If someone answers the question and then resumes later will `servedInCombatZonePost911` be sent to the API?

**Comment by Mottie** [comment]
> What happens if someone was on the combat status page and then try to resume their form?

Ooof, yeah. That would cause a problem where they would be sent back to the intro page until they restart the form 😭 - can this be changed on the backend? I think we might be able to reroute, but I'm not sure if anyone has ever done that from the frontend before.

> will `servedInCombatZonePost911` be sent to the API?

it won't get included in the submit transformer, so it won't be submitted.

**Comment by annaswims** [comment]
yeah, I can update the return URL on the back end.

**Comment by ashagross** [comment]
https://github.com/department-of-veterans-affairs/vets-json-schema/pull/594

Made sure to remove it from the schema.

**Review by Mottie — APPROVED** [review]
ghe-emoji

**Pull request merged**
