### PR TITLE
[WIP] 5255 scheduling

### PR DESCRIPTION
**Pull request by phiden**

### CODE REVIEW

**Comment by phiden** [comment]
Staged! @amybehrens https://vetsgov-pr-6633.herokuapp.com/health-care/about-va-health-care/schedule-an-appointment/

**Comment by phiden** [comment]
Staged with changes: https://vetsgov-pr-6633.herokuapp.com/health-care/about-va-health-care/schedule-an-appointment/

Please take a good look at the IA; I want to be sure I caught everything!

**Comment by amybehrens** [comment]
I'm getting a "sorry we can't find that page message"

For the other related pages:

https://vetsgov-pr-6633.herokuapp.com/health-care/
capitalize "a" in "Schedule a VA Appointment"

https://vetsgov-pr-6633.herokuapp.com/health-care/about-va-health-care/your-care-team/#appointments
need to update content here per word doc

https://vetsgov-pr-6633.herokuapp.com/health-care/about-va-health-care/where-you-get-care/#care-appointment
need to update content here per word doc

**Comment by phiden** [comment]
Ah. Yes. Forgot about the word doc changes. On it!

**Comment by amybehrens** [comment]
This lgtm. Want @lalexanderson-dsva to review as well. 

Note: We're still waiting on confirmation to change "Have had an appointment at that VA medical facility within the last 2 years, and" to "Have had a *primary care* appointment at that VA facility within the last 2 years, and"

**Comment by lalexanderson-dsva** [comment]
On https://vetsgov-pr-6633.herokuapp.com/health-care/schedule-an-appointment/, is it possible to change the link direction for **VA medical facility that accepts online scheduling** to an anchor link w/i MHV? Or a MHV page? I'm not in love with the UX on this new page (read: having a long list of facilities as opposed to a neater dropdown), but per Charles, we're trying to both K.I.S.S. and avoid the app store altogether. Slack me if you want to talk about logistics.

**Comment by amybehrens** [comment]
@lalexanderson-dsva i'm happy for us to link wherever that list is going to live. Do you have the link w/ anchor? We can send that wherever you say to!

**Comment by lalexanderson-dsva** [comment]
Apologies apologies for the late afternoon update. VAR is still being buggy, but @CyberKoz  and Jiten are on it. @chrisj-usds is currently estimating a Tuesday/Wednesday release date. Please don't go live with vets.gov scheduling page til then if at all possible.

**Review by robbiethegeek-usds — APPROVED** [review]
:shipit:

**Pull request merged**
