### PR TITLE
Added benefits note

### PR DESCRIPTION
**Pull request by kellyskennedy**
@peggygannon Let's try this one... Could you review, please?

### CODE REVIEW

**Review by peggygannon — COMMENTED** [review]
@kellyskennedy Looks good. 
The first PR you sent me had some added language after this line "You’ll get 100% of your applicable MHA during the first 6 months of training."   It's missing on this one, so I'm double-checking if it needs to be here?

**Comment by kellyskennedy** [comment]
Hey @peggygannon Nope -- just the note line below the bullets.

**Review by peggygannon — APPROVED** [review]
@kellyskennedy OK, looks good to me. It's ready to send to Beth.

**Review by DanielleSoCompany — APPROVED** [review]
Looks great to me, thanks!

**Comment by kellyskennedy** [comment]
Ready for you to take a look, @bethpotts

**Review by bethpotts — APPROVED** [review]
WAIT! Don't push to the live site until SME approves these edits.

**Comment by kellyskennedy** [comment]
@peggygannon Can you review this? I added a second line under "Who's covered." @bethpotts -- for your awareness...

**Comment by peggygannon** [comment]
@kellyskennedy LGTM. thanks

**Comment by kellyskennedy** [comment]
@bethpotts Want to take a look?

**Comment by kellyskennedy** [comment]
Okay, it's ready for you, @bethpotts

**Comment by kellyskennedy** [comment]
Okay -- ready for you @bethpotts

**Comment by bethpotts** [comment]
@kellyskennedy Looks great! Hopefully this'll be the last back and forth with the SME...

**Comment by kellyskennedy** [comment]
@phiden Could you review and merge this, please? SME-approved. Thanks!

**Review by phiden — APPROVED** [review]

**Pull request merged**
