### PR TITLE
[CST] - Update the css for the FilesNeeded alert 

### PR DESCRIPTION
**Pull request by pmclaren19**
## Summary

Updated the css for the FilesNeeded alert so that it better matches va standards in claims-status.css
- Removed alert-title changes
- Removed the font-size changes to alert-description

In the WhatYouNeedToDo file I did the following:
- added 24px of bottom margin to the h3

In the FilesNeeded file I did the following:
- Moved the header out of the div and added slot="headline" to the alert header so that the component default css was used
- Updated the heading to a h4 for accessibility

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#69450

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Changes  | Screenshot 2024-01-24 at 12 01 50 PM | Screenshot 2024-01-25 at 11 01 12 AM|

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### CODE REVIEW

**Comment by pmclaren19** [comment]
@skylerschain can you please review this pr with the updated design?

**Comment by pmclaren19** [comment]
@davidakennedy Is it okay that the alert has a H3 or should this be a H4?

**Comment by davidakennedy** [comment]
@pmclaren19 Good question. In a perfect world, we would have some paragraph or list text under the "What you need to do" h3, so we don't sandwich headings without text underneath them. Ideally, headings have text with them before other headings.

That said:

- If the "What you need to do" heading, corresponds with the conditions above, the alerts should be h4s. Because they relate to what needs to be done. I think this is the case, but just making sure.
- If the tasks in the alerts aren't related to the conditions listed, you could make the "What you need to do" heading a h2 and leave the headings in the alerts as h3s.

cc: @skylerschain

**Comment by skylerschain** [comment]
Yeah @davidakennedy the alerts pertain to "What you need to do" so making them h4s sounds like the right approach!

**Review by samcoforma — APPROVED** [review]
LGTM

**Pull request merged**
