### PR TITLE
Working ancillary forms wizard summary page

### PR DESCRIPTION
**Pull request by cvalarida**
## Description
The ancillary forms wizard summary page works!

Because it's an information-only page, I decided to make it a "blank" page as far as the schema is concerned, but with a stateful description component. When a checkbox is selected, the appropriate content is displayed in the Wall of Text™ below.

@goldenmeanie Can you take a look at the screenshot and provide feedback for how we can separate each form content?

:thinking: Actually each section maybe should be displayed as expanded under the option itself, now that I think about it. What sayest thou?

@peggygannon I just made up the check box content. It...needs help. What should each option say?

## Testing done
None so far. Waiting on design review to write the tests.

## Screenshots
image

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by peggygannon — CHANGES_REQUESTED** [review]
@cvalarida Please see below for my content tweaks: 

1. please update the checkbox labels to: 
Adapted housing assistance
Automobile allowance
Aid and Attendance (note both capped "a"s)
Individual Unemployability (cap the U, as this is the full name of the benefit)

2. please remove the bullets before the two paragraphs for the Auto allowance.

**Comment by goldenmeanie** [comment]
I wonder if an expanded accordion makes sense here? It would let us fence the content off, form to form, and create a little more visual hierarchy. Alternately, we could do headings and paragraphs. The checkboxes don't seem useful to me until we have live forms to turn on behind them. So maybe only 8940/4192 to start?

**Review by goldenmeanie — CHANGES_REQUESTED** [review]
Agree that the current separation is not ideal. See prior comment for details.

**Comment by cvalarida** [comment]
@peggygannon @goldenmeanie I updated the content and used our design system's collapsible panels instead of the check boxes to reveal the nested content. How does that look?

### All the options
image

### Only the applicable ones show
image

### The content
image
image
image
image

**Review by peggygannon — APPROVED** [review]

**Comment by peggygannon** [comment]
@cvalarida Looks good. Thanks!

**Review by goldenmeanie — APPROVED** [review]

**Comment by cvalarida** [comment]
Perfect, thanks @goldenmeanie & @peggygannon!

@markgreenburg this is ready for technical review.

**Review by markgreenburg — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
