### PR TITLE
Deploy 4142

### PR DESCRIPTION
**Pull request by igreulich**
## Description
Added some prod flags to keep the world from seeing our form before we are ready to show it to them.

## Testing done
Local prod and dev builds, UI compared.

## Screenshots
n/a

## Acceptance criteria
- [x] Configure 4142 for deployment

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by igreulich** [comment]
@JBarbour2 This is the branch you need to test one.

**Comment by igreulich** [comment]
Looks like there is a slew of linting errors that I get to fox tomorrow, but aside from that, @robfelder @aaronjlech @imeecuison can I get a new review please.

**Review by aaronjlech — APPROVED** [review]
@igreulich Looks good!

**Review by robfelder — APPROVED** [review]
LGTM!

**Comment by igreulich** [comment]
Looking at the Jenkins failure, it **LOOKS** like there are some dependencies that need to update their dependencies.

```
+ npm --no-color run test:coverage

> vets-website@1.0.0 test:coverage /application
> NODE_ENV=test nyc --all --reporter=lcov --reporter=text --reporter=html mocha --reporter dot --reporter mocha-junit-reporter --no-color --opts src/platform/testing/unit/mocha.opts --recursive '{src,test}/**/*.unit.spec.js?(x)' src/platform/testing/unit/helper.js

/application/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^
BrowserslistError: Unknown version 60 of Firefox (While processing preset: "/application/node_modules/babel-preset-env/lib/index.js")
    at error (/application/node_modules/browserslist/index.js:37:11)
    at Function.select (/application/node_modules/browserslist/index.js:605:21)
    at /application/node_modules/browserslist/index.js:207:41
    at Array.forEach (<anonymous>)
    at browserslist (/application/node_modules/browserslist/index.js:196:13)
    at getTargets (/application/node_modules/babel-preset-env/lib/index.js:146:70)
    at buildPreset (/application/node_modules/babel-preset-env/lib/index.js:216:17)
    at /application/node_modules/babel-core/lib/transformation/file/options/option-manager.js:317:46
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/application/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/application/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/application/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/application/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/application/node_modules/babel-register/lib/node.js:103:45)
    at loader (/application/node_modules/babel-register/lib/node.js:144:14)
    at require.extensions.(anonymous function) (/application/node_modules/babel-register/lib/node.js:154:7)
    at Object.<anonymous> (/application/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /application/node_modules/mocha/bin/_mocha:366:3
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/application/node_modules/mocha/bin/_mocha:365:10)
    at Module._compile (module.js:653:30)
    at Module.replacementCompile (/application/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/application/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/application/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at runMain (/home/jenkins/.node-spawn-wrap-31-d4961ec8a1af/node:68:10)
    at Function.<anonymous> (/home/jenkins/.node-spawn-wrap-31-d4961ec8a1af/node:171:5)
    at Object.<anonymous> (/application/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at /home/jenkins/.node-spawn-wrap-31-d4961ec8a1af/node:178:8
    at Object.<anonymous> (/home/jenkins/.node-spawn-wrap-31-d4961ec8a1af/node:181:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by igreulich** [comment]
@JBarbour2 Let me know when you have rechecked this.

branch `deploy-4142`

**Pull request merged**
