### PR TITLE
[WIP] content changes for new nav

### PR DESCRIPTION
**Pull request by bethpotts**
Content changes to support the new nav.

### CODE REVIEW

**Comment by bethpotts** [comment]
@rroueche We are ready for you to review and merge this. Thanks! 
@mollyblake FYI

**Comment by rroueche** [comment]
@bethpotts @mollyblake awesome! I think there are just some page title changes left. For example, I thought we were changing the page titles of these to Application Process:

https://www.vets.gov/healthcare/apply/
https://www.vets.gov/education/apply-for-education-benefits/
https://www.vets.gov/healthcare/apply/
https://www.vets.gov/disability-benefits/apply-for-benefits/

And changing the following page to Health Care Benefits:
https://www.vets.gov/healthcare/

**Comment by bethpotts** [comment]
@rroueche @mollyblake  I thought we decided to change only the nav to "Application process" for Disability, and that the titles of the Apply pages themselves would stay with the specific name of the benefit being applied for. I think that's more clear to users, anchors them as far as what page they're on. My thought was that the language is similar enough with "Application" in the nav linking to "Apply" on the page users land on. Apologies if I misunderstood this piece! Let's check in about it in the morning.

I'll have to fix the Disability apply page to be more specific by adding the word "Disability" to "Apply for Benefits" so that it's: Apply for Disability Benefits.

I'll make this change right now. Thank you for noticing:
And changing the following page to Health Care Benefits:
https://www.vets.gov/healthcare/

**Comment by rroueche** [comment]
Awesome! Looks good to me.

@maryannbrody cc'ing you in case you'd like to review before we go live, but I'll plan to merge these updates to master the same day the global nav goes live.

**Review by rroueche — COMMENTED** [review]
👍

**Review by rroueche — APPROVED** [review]

**Comment by rroueche** [comment]
@maryannbrody and @bethpotts merging these now so they can go live this afternoon w/the global nav (woo!!)

**Pull request merged**
