### PR TITLE
[WIP] BAH 4142 Shell page in the 526EZ flow

### PR DESCRIPTION
**Pull request by robfelder**
## Description
This PR creates the initial shell page for the 4142 form and includes the contention name at the top of the screen. This change ensures that the page is accessible in the 526EZ flow and that is will display for each contention with the correct contention displayed.

## Testing done
- Manual testing
- Unit test written and ran

## Testing Plan
- Manual QA testing
- Peer manual testing
- Unit tests ran

## Acceptance Criteria (Definition of Done)
- Upon choosing the no option for PMR's, the user will be taken to a new page that displays the contention name at the top of the screen
- Route reads: `supporting-evidence/:index/private-medical-record-request` where `:index` is a zero based indicator as to what contention you are adding supporting evidence for.

#### Unique to this PR

- If the user does not select no, then the user will not be taken to this screen.

#### Applies to all PRs

- [ ] Appropriate logging
- [ ] Documentation has been updated, if applicable
- [ ] Provide link to originating GitHub issue, or connected to it via ZenHub
- [ ] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [ ] Provide which alerts would indicate a problem with this functionality (if applicable)

ZenHub Issue: https://app.zenhub.com/workspace/o/department-of-veterans-affairs/vets.gov-team/issues/12853

### CODE REVIEW

**Comment by igreulich** [comment]
@robfelder Will Do.

**Comment by igreulich** [comment]
I can't in good conscience approve a PR with any, let alone all, commented-out code in it.

**Review by igreulich — CHANGES_REQUESTED** [review]
See above

**Review by imeecuison — COMMENTED** [review]
If this is a WIP, the commented out code doesn't bother me. It actually will help me orient myself to where I need to add my stuff. Rob, is 582 about where I put in the 4142 integration?

**Comment by igreulich** [comment]
Per @imeecuison's comment, I'll defer to you guys.

**Review by igreulich — APPROVED** [review]

**Comment by robfelder** [comment]
@imeecuison Yep, that's exactly where you would put it

**Pull request merged**
