### PR TITLE
Replace GA Code snippet with GTM code snippet

### PR DESCRIPTION
**Pull request by rickleegit**
This PR replaces the Google Analytics code in the footer include with a Google Tag Manager code snippet. the GTM container has been established and will take over tracking from the old code as soon as this is pushed into production so the interruption to metric continuity will be extremely minimal, if any. The code in the VA Common GEM needs to be replaced to complete the transition to GTM. That will be done in a separate PR. 

cc; @staceylanger @ayaleloehr

### CODE REVIEW

**Comment by rickleegit** [comment]
For more information, please see: https://github.com/department-of-veterans-affairs/vets.gov-team/blob/gtmReadme/Products/analytics_procedure/readme.md

**Comment by rickleegit** [comment]
@webinista; 

@staceylanger Suggested that you might be interested/able to assist with this deployment as well. The code is complete. Just needs a review. Following merge and deployment, I will monitor for a week or so to make sure that everything is functioning as expected. If there is a problem, we might need to make adjustments and redeploy. 

Thanks! 
Rick

**Comment by ayaleloehr** [comment]
This looks good to me, as I'm assuming you just copied this code out of the GTM web interface.

**Comment by rickleegit** [comment]
@webinista: Let's chat about this moving forward. Alex jumped on this deployment early this morning. Thanks @ayaleloehr!

**Comment by ayaleloehr** [comment]
Was assigned to me, so I thought you were looking for a review and merge.  Hope I didn't jump the gun.

**Comment by rickleegit** [comment]
All is good. I had assigned it to you. I jumped the gun out of assignment
habit.

**Pull request merged**
