### PR TITLE
adds LoginNote component

### PR DESCRIPTION
**Pull request by CaitHawk**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

## Summary

Final Content has been determined for the Login Modal. It was requested that we add a note informing users that they will no longer be able to sign in with certain CSPs after December 31st as shown in the screenshot below.

## Testing done
 - unit tests were added to ensure the note is rendering on the page

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  | Screenshot 2024-07-18 at 11 24 00 AM | Screenshot 2024-07-18 at 12 45 41 PM |
| Desktop | Screenshot 2024-07-18 at 11 23 22 AM | Screenshot 2024-07-18 at 12 44 56 PM |

## What areas of the site does it impact?

- VA Sign In Modal

## Acceptance criteria

- Add note to VA Sign In Modal

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Comment by acaruso-oddball** [comment]
lgtm 🚀

**Review by acaruso-oddball — CHANGES_REQUESTED** [review]
lgtm, can you rebase and I'll approve?

**Review by joeniquette — DISMISSED** [review]
Tested with user 150 successfully

**Review by acaruso-oddball — DISMISSED** [review]
lgtm thx!

**Review by joeniquette — APPROVED** [review]

**Pull request merged**
