### PR TITLE
CT 116: Remove production flag from 116 content so that all changes are available in production #19375

### PR DESCRIPTION
**Pull request by zurbergram**
## Description
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19375

As a developer, I need to remove the conditional logic that prevents the 116 Comparison Tool functionality from being displayed in production so that the functionality is released to the public.

## Assumptions:
1. Stories that should be available in production after completion of this story:
    - Landing Page:
      - #19099
    - Search Results Page:
      - #19101
      - #19180
      - #19278
      - #19340
    - Profile Page:
      - #18896
      - #19104
      - #19181

## Testing done
- local testing

## Acceptance criteria
- [ ] On the landing page, the VET TEC institution type and other corresponding changes are available in production.
- [ ] The user is redirected to the VET TEC search results page after having chosen the VET TEC institution type on the landing page.
- [ ] The user is redirect to the VET TEC profile page after clicking on the header/view details of the search results card.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by devin-mccurdy — APPROVED** [review]
LGTM

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Comment by zurbergram** [comment]
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!

**Review by rianfowler — APPROVED** [review]

**Review by delli-gatti-michael — APPROVED** [review]
Approved by QA

**Pull request merged**
