### PR TITLE
Rename compensation claim text

### PR DESCRIPTION
**Pull request by jbalboni**
Closes [131](https://github.com/department-of-veterans-affairs/sunsets-team/issues/131)

screen shot 2016-10-31 at 3 19 50 pm
screen shot 2016-10-31 at 3 19 14 pm
screen shot 2016-10-31 at 3 18 19 pm
screen shot 2016-10-31 at 3 18 13 pm
screen shot 2016-10-31 at 3 18 09 pm

### CODE REVIEW

**Comment by jbalboni** [comment]
@suzchap Does this look like all the instances of that text?

**Review by molindoz — APPROVED** [review]
LGTM

**Comment by suzchap** [comment]
@jbalboni I found another one -- on the details tab. Claim Type = Compensation
should be Claim Type = Disability Compensation

Should I create a new issue?

**Comment by jbalboni** [comment]
@suzchap The values in that field are coming back from EVSS, as far as I know, so we can't change them.

**Comment by suzchap** [comment]
Ok, I'll let it go for now but when we expand to have more types of claims we may need to revisit. Thanks!

**Pull request merged**
