### PR TITLE
Update health services listing to use correct template.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
Health services listing page is using the wrong template.

## Testing done
Visual

## Screenshots
image

## Acceptance criteria
- [ ] Visit `pittsburgh-health-care/health-services/` and verify that page appears, and is unbroken.

### CODE REVIEW

**Comment by kevwalsh** [comment]
Judging only from the screenshot, this is missing the "In the spotlight" stuff from https://www.va.gov/pittsburgh-health-care/health-services/

**Review by jhonny218 — APPROVED** [review]

**Comment by ethanteague** [comment]
> Judging only from the screenshot, this is missing the "In the spotlight" stuff from https://www.va.gov/pittsburgh-health-care/health-services/

Good catch - updated, @kevwalsh

**Comment by kevwalsh** [comment]
@ethanteague can't `health_care_region_health_services_page` be removed altogether now?

**Comment by ethanteague** [comment]
> @ethanteague can't `health_care_region_health_services_page` be removed altogether now?

Yep. Removed, @kevwalsh

**Review by kevwalsh — APPROVED** [review]

**Review by ncksllvn — APPROVED** [review]

**Review by kelsonic — APPROVED** [review]

**Pull request merged**
