### PR TITLE
GIBCT autosuggest styling.

### PR DESCRIPTION
**Pull request by U-DON**
Resolves department-of-veterans-affairs/vets.gov-team#1239.

### CODE REVIEW

**Review by ben-USDS-damman — APPROVED** [review]
LGTM

**Comment by U-DON** [comment]
Jenkins build isn't happening here for some reason. Closing in order to get the build running on a new PR.

**Comment by saintsoup52** [comment]
What happens after the school is selected? 

In the old version the user was redirected to the next page... here what they select will have to stay on the page... will it just be in the box?

**Comment by U-DON** [comment]
@saintsoup52 It should update the search results like a search term. Since the selection is a specific name, it would list just the one result that matches it. This still needs to be implemented, however.

**Pull request closed without merging**
