### PR TITLE
Advanced search form (layout only)

### LINKED ISSUE #3239: Checkbox click area is unnecessarily large
Clickable area is as wide as what you can see in the fuzzy blue outline. (But it's an invisible clickable area.)

screen shot 2016-09-30 at 11 35 51 am

Caused by `input {width: 100%}` declaration that's inherited from USWDS.

Related to:

- 18F/web-design-standards#1490
- 18F/web-design-standards#1491

### PR DESCRIPTION
**Pull request by webinista**
WIP on department-of-veterans-affairs/messaging-fe#4
- Adds react-datepicker component.
- Fixes checkbox sizing bug inherited from USWDS. Resolves #3239

### CODE REVIEW

**Comment by webinista** [comment]
Small functionality issue with the Create New Folder modal: If the user submits the form without first focusing on the input field, error checking will be bypassed, and the form will be submitted. Should either focus on `newFolderName` when the modal is opened, or maybe mark the initial value `dirty`

Aside from that, it looks good. Will let you decide whether to fix the above issue in this PR or another one.

**Comment by U-DON** [comment]
The datepicker pops up now, but selecting a date doesn't populate the input. Despite having a placeholder, I don't see it actually appear either.

The legend issue is probably the same as the one from the compose page, so that can be dealt with separately in a bug fix PR.

**Comment by webinista** [comment]
This is literally just the layout. None of the other functionality -- search toggling, date selection, error checking is in there yet.

**Comment by U-DON** [comment]
LGTM.

**Pull request merged**
