### PR TITLE
Transition off deprecated URLSearchParams polyfill

### PR DESCRIPTION
**Pull request by hinzed1127**
## Description

The existing polyfill for URLSearchParams has a [known bug](https://github.com/WebReflection/url-search-params#ios-10--other-platforms-bug) that the SSO team has encountered, and the package itself is deprecated. This transitions that dependency to a more widely used and up-to-date [polyfill](https://github.com/jerrybendy/url-search-params-polyfill)

## Testing done

- [x] Existing tests don't break
- [ ] Manual testing in IE
- [x] Manual testing in Safari

### CODE REVIEW

**Comment by ericbuckley** [comment]
@hinzed1127 / @patrickvinograd  I used the iOS simulator (version 10.3.1) on my mac, and was able to verify on staging this is what the user sees when the auto login launches (which is inline with the access log value we saw earlier in nginx).

If tests are passing and we can push this branch up to dev, I can run another test.

Screen Shot 2020-07-08 at 14 03 00

**Comment by ericbuckley** [comment]
patrick deployed this branch to dev.va.gov and I ran the following test case on my laptop using the iOS simulator for 10.3.1.

```
- opened a tab to https://int.eauth.va.gov/accessva/
- logged into an app using ID.me testing credentials
- verified that I was logged into SSOe by going to https://int.eauth.va.gov/IAM/
- opened a new tab to https://dev.va.gov/
- within a second I was redirected to int.eauth.va.gov then back to dev.va.gov in the logged in state
```

I think this PR will resolve the issue.

**Review by ericbuckley — APPROVED** [review]
👍

**Comment by ericbuckley** [comment]
@hinzed1127 should we close this in favor of #13451

**Review by ncksllvn — COMMENTED** [review]
Maybe we can delete the import out of each module and instead just import it once at `src/platform/polyfills/index.js`?

**Comment by rianfowler** [comment]
closing- captured in https://github.com/department-of-veterans-affairs/va.gov-team/issues/11457

**Pull request closed without merging**
