### PR TITLE
BUG: includes/footer.html: Add the same links as the /gi-bill-comparison-tool/ footer

### PR DESCRIPTION
**Pull request by westurner**

### CODE REVIEW

**Comment by jcmeloni** [comment]
@crwallace @webinista @melwoodard Heads up on this PR as it relates to other work ongoing re: the footer and blog/vec links which I believe are going away. I think we'll actually end up removing the links from GIBCT?

**Comment by melwoodard** [comment]
@jcmeloni that's correct - removal of those links was intentional, with the next iteration of footer content planned in #4439. Once GIBCT is migrated to vets-website it will use includes/footer.html

**Comment by webinista** [comment]
@jcmeloni Related to #4594. Should we close this PR since the plan is to remove the links from GIBCT, not add them to `/includes/footer.html`?

**Comment by jcmeloni** [comment]
@webinista That makes sense to me, yeah

**Pull request closed without merging**
