### PR TITLE
[AVS] Add redirect from base path

### PR DESCRIPTION
**Pull request by acrollet**
## Summary

- Redirects to `/my-health/medical-records/summaries-and-notes/` when a user visits `/my-health/medical-records/summaries-and-notes/visit-summary/` without an AVS id.

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#78131

## Testing done

- local testing
- added unit tests

## What areas of the site does it impact?

AVS application only

### CODE REVIEW

**Review by stephenBarrs — DISMISSED** [review]
All unit tests pass and I was able to run in codespaces.  There is no mock for the page redirected to when no `id` is present, but the url was correct.  LGTM!

**Review by mdewey — DISMISSED** [review]
Lgtm

**Comment by jamigibbs** [comment]
Platform FE CoP will be able to review once tests are passing.

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Pull request merged**
