### PR TITLE
Updated footer content links. closes vets.gov-team#678

### PR DESCRIPTION
**Pull request by webinista**
- Removed .usa-social-links CSS.
- Renamed va-list-linkgroup* to va-footer-linkgroup.
- Removed footer-logo block. Unnecessary.
- Switched footer to a flexbox layout.
- Moved disclaimer to bottom of footer.

(Opening new branch to get around a [branch naming issue](https://github.com/department-of-veterans-affairs/vets-website/pull/4703#issuecomment-273310276) with Jenkins)

### CODE REVIEW

**Comment by webinista** [comment]
@jkassemi Can you help me out here with a reason why Jenkins is failing?

**Comment by jcmeloni-usds** [comment]
@jkassemi halp us pls. :)

**Comment by webinista** [comment]
Closing this PR. It looks like the content updates made it to production already? IDK.

**Comment by jkassemi** [comment]
sorry for the delay - error was from the broken link checker:

`[production] Error: Link is broken: href: "/2016/11/11/help-us-improve-vets-gov/", text: "Message from the Secretary", in file: 404.html`

**Comment by webinista** [comment]
[Reopening because I looked at the issue again and was wrong about these changes landing in prod]

I am confused about why we're getting that error. 404.html should be built from 404.md, right? And 404.md uses the same header and footer that the rest of the site does.

**Comment by jkassemi** [comment]
@webinista - yes, build will exit after first failure, and the 404 page was the first page in the build that had the issue with the link.

**Comment by webinista** [comment]
@jkassemi We removed that link from the footer though. If 404.html is built from 404.md using the global header and footer, why would we get a broken link error?

**Comment by webinista** [comment]
So here's where I realize that I got two footer-related PRs mixed up in my head, and this is the one didn't remove the link.

**Comment by webinista** [comment]
Is the current Jenkins error anything like:

```
Module build failed: ModuleBuildError: Module build failed:
  ($base-font-size * $input-line-height) +
 ^
      Incompatible units: 'rem' and '%'.
```

**Comment by jcmeloni-usds** [comment]
Please please please let's figure this out and get this pushed out in today's release.  Please.  

cc @emilyville @koconnor719 so they know I wasn't lying when I said the work has been done but we are running into ridiculous problems getting the darn thing deployed. :)

**Comment by jkassemi** [comment]
Looking into a Jenkins specific issue causing the build failure. While changes to the application config may be required, don't let this hold up progress on this ticket. If Travis passes, we're good here.

**Comment by jkassemi** [comment]
Jenkins issue appears to be a problem with running the process all together, possibly related to issues cloning the repo. Doesn't get far enough yet to hit issues with incompatible units.

**Pull request merged**
