### PR TITLE
Changed link to Gulf War Illness/Afghanistan

### PR DESCRIPTION
**Pull request by kellyskennedy**

### CODE REVIEW

**Comment by kellyskennedy** [comment]
@peggygannon can you review this, please? Thanks!

**Review by peggygannon — APPROVED** [review]
@kellyskennedy Copy edit is complete. 
--one thing to note, should the link to the accredited rep page change here or is that change captured in your accredited rep PR from last week?

**Comment by kellyskennedy** [comment]
@peggygannon I got it last week--it just isn't showing up yet on this page. 
@bethpotts ready to take a look?

**Comment by kellyskennedy** [comment]
@bethpotts Mina just asked about this one -- was this the weird jenkins break we were waiting on?

**Review by bethpotts — APPROVED** [review]
This is ready for a code review and merge!

**Review by ncksllvn — APPROVED** [review]

**Pull request merged**
