### PR TITLE
6.29.20 changes to refine symptoms

### PR DESCRIPTION
**Pull request by DanielleThierryUSDSVA**
## Description
Updating symptoms per latest CDC language.

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by batemapf** [comment]
LGTM! I recommend waiting until after the 2pm build/deploy to merge this in which will give me time to send out a short note summarizing the changes to our distro list. @DanielleThierryUSDSVA any chance you have a non-GH redlined version of the changes? No worries if not, I can generate.

**Review by batemapf — APPROVED** [review]
See previous comment re: holding off until after today's deploy.

**Comment by DanielleThierryUSDSVA** [comment]
@batemapf Sure. Here you go! Tracked changes and comments w/ reasons for changes. Do me a favor and just give it a quick double check for typos if you don't mind :) 

[VA.gov_COVID-19 screening tool 6.29.20.docx](https://github.com/department-of-veterans-affairs/vets-website/files/4846926/VA.gov_COVID-19.screening.tool.6.29.20.docx)

**Comment by batemapf** [comment]
@mchelen-gov @stephenBarrs just tidied up some whitespace issues that was causing this to failing linting. wonder if there is a way to disable/reduce to warn prettier (and any other linting steps) for our config files?

**Pull request merged**
