### PR TITLE
4790 MDT confirm address step - edit address

### PR DESCRIPTION
**Pull request by maharielrosario**
## Description
We are creating a confirm address step feature based on our design team's thumbnail workflow.
This is a work in progress so requirements most likely will change. 

The current user story is "As a Veteran, I need to be able to edit my current address so that I can choose where I would like my items sent". 

## URL

http://localhost:3001/disability-benefits/2346/confirmaddress

## Testing done
Since our requirements are not finalized, we have not set up tests yet.

## Screenshots

screenshot-app mural co-2020 01 (1)

screenshot-localhost_3001-2020 01 (1)

## Blockers

- Our design requirements need to be finalized
- We need back end data sent to us

## Acceptance criteria

Given that I am a Veteran logged into va.gov ordering hearing aid batteries and accessories
When I want to confirm my address for where to ship my items
Then I should see the address I typed in, check the box next to it, and click the "confirm address" button

## Definition of done
- [ ] I am able to see the address populated from the API
- [ ] I am able to check the box next to my name
- [ ] I am able to click the "confirm address" button
- [ ] I am able to click the "back" button and go to the previous page

### CODE REVIEW

**Comment by bradl3yC** [comment]
This looks like the same PR as https://github.com/department-of-veterans-affairs/vets-website/pull/11532****  Did you mean for this to be merged into @mojaray2k PR?

**Comment by mr0sari0** [comment]
> This looks like the same PR as #11532**** Did you mean for this to be merged into @mojaray2k PR?

It looks similar but it is a different step in the workflow. #11532 is selecting which items the Veteran wants to order.   #11533 is confirming the address of the veteran.

**Comment by bradl3yC** [comment]
> > This looks like the same PR as #11532**** Did you mean for this to be merged into @mojaray2k PR?
> 
> It looks similar but it is a different step in the workflow. #11532 is selecting which items the Veteran wants to order. #11533 is confirming the address of the veteran.

There is a lot of duplicated work here.  This will lead to quite a few merge conflicts.

**Comment by mr0sari0** [comment]
> > > This looks like the same PR as #11532**** Did you mean for this to be merged into @mojaray2k PR?
> > 
> > 
> > It looks similar but it is a different step in the workflow. #11532 is selecting which items the Veteran wants to order. #11533 is confirming the address of the veteran.
> 
> There is a lot of duplicated work here. This will lead to quite a few merge conflicts.

What do you propose we should do?  Our current plan was to make separate PRs for each new feature and then merge to master.

**Comment by bradl3yC** [comment]
> > > > This looks like the same PR as #11532**** Did you mean for this to be merged into @mojaray2k PR?
> > > 
> > > 
> > > It looks similar but it is a different step in the workflow. #11532 is selecting which items the Veteran wants to order. #11533 is confirming the address of the veteran.
> > 
> > 
> > There is a lot of duplicated work here. This will lead to quite a few merge conflicts.
> 
> What do you propose we should do? Our current plan was to make separate PRs for each new feature and then merge to master.

You could abstract the foundational work into its own PR, merge that once approved and then work on your separate pieces in your own branches.  This should alleviate the potential headache you're headed into having so many changes of the same files.

**Comment by mr0sari0** [comment]
> > > > > This looks like the same PR as #11532**** Did you mean for this to be merged into @mojaray2k PR?
> > > > 
> > > > 
> > > > It looks similar but it is a different step in the workflow. #11532 is selecting which items the Veteran wants to order. #11533 is confirming the address of the veteran.
> > > 
> > > 
> > > There is a lot of duplicated work here. This will lead to quite a few merge conflicts.
> > 
> > 
> > What do you propose we should do? Our current plan was to make separate PRs for each new feature and then merge to master.
> 
> You could abstract the foundational work into its own PR, merge that once approved and then work on your separate pieces in your own branches. This should alleviate the potential headache you're headed into having so many changes of the same files.

#11506 is the foundational branch we have been merging to once these feature branches were approved.  But #11506 itself needs to be approved and merged to master.

**Comment by bradl3yC** [comment]
> > > > > > This looks like the same PR as #11532**** Did you mean for this to be merged into @mojaray2k PR?
> > > > > 
> > > > > 
> > > > > It looks similar but it is a different step in the workflow. #11532 is selecting which items the Veteran wants to order. #11533 is confirming the address of the veteran.
> > > > 
> > > > 
> > > > There is a lot of duplicated work here. This will lead to quite a few merge conflicts.
> > > 
> > > 
> > > What do you propose we should do? Our current plan was to make separate PRs for each new feature and then merge to master.
> > 
> > 
> > You could abstract the foundational work into its own PR, merge that once approved and then work on your separate pieces in your own branches. This should alleviate the potential headache you're headed into having so many changes of the same files.
> 
> #11506 is the foundational branch @mojaray2k and I have been merging to once these feature branches were approved. But #11506 itself needs to be approved and merged to master.

None of that was communicated - there are 3 PRs which have requested review.  All 3 have targets of master.  There are changes that have been requested on Amen's PR I referenced above.  Those changes need to be made on your base branch before it can be merged.  If you're doing work in another PR that will eventually get merged into the base branch, those need to have their branch target set to the appropriate branch as opposed to master.  That way it does not show all of the duplication of work.

**Comment by mr0sari0** [comment]
> > > > > > > This looks like the same PR as #11532**** Did you mean for this to be merged into @mojaray2k PR?
> > > > > > 
> > > > > > 
> > > > > > It looks similar but it is a different step in the workflow. #11532 is selecting which items the Veteran wants to order. #11533 is confirming the address of the veteran.
> > > > > 
> > > > > 
> > > > > There is a lot of duplicated work here. This will lead to quite a few merge conflicts.
> > > > 
> > > > 
> > > > What do you propose we should do? Our current plan was to make separate PRs for each new feature and then merge to master.
> > > 
> > > 
> > > You could abstract the foundational work into its own PR, merge that once approved and then work on your separate pieces in your own branches. This should alleviate the potential headache you're headed into having so many changes of the same files.
> > 
> > 
> > #11506 is the foundational branch @mojaray2k and I have been merging to once these feature branches were approved. But #11506 itself needs to be approved and merged to master.
> 
> None of that was communicated - there are 3 PRs which have requested review. All 3 have targets of master. There are changes that have been requested on Amen's PR I referenced above. Those changes need to be made on your base branch before it can be merged. If you're doing work in another PR that will eventually get merged into the base branch, those need to have their branch target set to the appropriate branch as opposed to master. That way it does not show all of the duplication of work.

I see what you are saying.  Tell me if I'm understanding this correctly:  We will just target our feature branches to our base branch, #11506,  and then once we feel we are ready to ship out, we do a real PR for #11506 .

**Comment by bradl3yC** [comment]
> > > > > > > > This looks like the same PR as #11532**** Did you mean for this to be merged into @mojaray2k PR?
> > > > > > > 
> > > > > > > 
> > > > > > > It looks similar but it is a different step in the workflow. #11532 is selecting which items the Veteran wants to order. #11533 is confirming the address of the veteran.
> > > > > > 
> > > > > > 
> > > > > > There is a lot of duplicated work here. This will lead to quite a few merge conflicts.
> > > > > 
> > > > > 
> > > > > What do you propose we should do? Our current plan was to make separate PRs for each new feature and then merge to master.
> > > > 
> > > > 
> > > > You could abstract the foundational work into its own PR, merge that once approved and then work on your separate pieces in your own branches. This should alleviate the potential headache you're headed into having so many changes of the same files.
> > > 
> > > 
> > > #11506 is the foundational branch @mojaray2k and I have been merging to once these feature branches were approved. But #11506 itself needs to be approved and merged to master.
> > 
> > 
> > None of that was communicated - there are 3 PRs which have requested review. All 3 have targets of master. There are changes that have been requested on Amen's PR I referenced above. Those changes need to be made on your base branch before it can be merged. If you're doing work in another PR that will eventually get merged into the base branch, those need to have their branch target set to the appropriate branch as opposed to master. That way it does not show all of the duplication of work.
> 
> I see what you are saying. Tell me if I'm understanding this correctly: We will just target our feature branches to our base branch, #11506, and then once we feel we are ready to ship out, we do a real PR for #11506 .

100% - that way all the base work does not show up as a change in your feature branch!

**Comment by mr0sari0** [comment]
> > > > > > > > > This looks like the same PR as #11532**** Did you mean for this to be merged into @mojaray2k PR?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > It looks similar but it is a different step in the workflow. #11532 is selecting which items the Veteran wants to order. #11533 is confirming the address of the veteran.
> > > > > > > 
> > > > > > > 
> > > > > > > There is a lot of duplicated work here. This will lead to quite a few merge conflicts.
> > > > > > 
> > > > > > 
> > > > > > What do you propose we should do? Our current plan was to make separate PRs for each new feature and then merge to master.
> > > > > 
> > > > > 
> > > > > You could abstract the foundational work into its own PR, merge that once approved and then work on your separate pieces in your own branches. This should alleviate the potential headache you're headed into having so many changes of the same files.
> > > > 
> > > > 
> > > > #11506 is the foundational branch @mojaray2k and I have been merging to once these feature branches were approved. But #11506 itself needs to be approved and merged to master.
> > > 
> > > 
> > > None of that was communicated - there are 3 PRs which have requested review. All 3 have targets of master. There are changes that have been requested on Amen's PR I referenced above. Those changes need to be made on your base branch before it can be merged. If you're doing work in another PR that will eventually get merged into the base branch, those need to have their branch target set to the appropriate branch as opposed to master. That way it does not show all of the duplication of work.
> > 
> > 
> > I see what you are saying. Tell me if I'm understanding this correctly: We will just target our feature branches to our base branch, #11506, and then once we feel we are ready to ship out, we do a real PR for #11506 .
> 
> 100% - that way all the base work does not show up as a change in your feature branch!

Awesome, thanks for the clarification. I will discuss with @mojaray2k when he gets back online.

**Comment by bradl3yC** [comment]
@mr0sari0 you need to rebase this with the branch you're trying to merge into.  You can rebase THAT branch with master and then rebase this branch from that branch.  But since you're branched off of 3614-discovery-mock-up-of-medical-device-tool - thats what you need to keep this branch up to date with.

**Comment by mr0sari0** [comment]
@kelsonic @bradl3yC  @mojaray2k  closing this PR as it is not needed for this branch.

**Pull request closed without merging**
