### PR TITLE
Upgrade component-library to 3.4.0

### PR DESCRIPTION
**Pull request by erikphansen**
## Original issue(s)
department-of-veterans-affairs/va.gov-team#0000

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by timwright12** [comment]
Bringing in @bkjohnson for this one

**Comment by bkjohnson** [comment]
If we tag a release that includes the changes from https://github.com/department-of-veterans-affairs/component-library/pull/211, I expect that the published version will include what we need.

More info below

---

This bump is to a version that was published based on a release. All the build errors seem to be about `react-bindings` being unavailable. Notice that there isn't a `react-bindings` directory inside of `dist`:

image

And on `master` where we're using a version that I manually published, `react-bindings` is there: 
image

The `prepare` script is [no longer part of `yarn`'s lifecycle scripts](https://yarnpkg.com/advanced/lifecycle-scripts), so it wasn't being run in the automation.

**Comment by k80bowman** [comment]
@erikphansen just letting you know on this one that @bkjohnson fixed the React bindings issue and we released that with version 3.6.0 of the component-library.

**Comment by tmitchellgcio** [comment]
Closing this as we are changing it to 3.6.0

**Pull request closed without merging**
