### PR TITLE
content/wip/stub out new content templates

### PR DESCRIPTION
**Pull request by melwoodard**
Related: https://github.com/department-of-veterans-affairs/vets.gov-content/issues/206

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/938

Add shell templates with placeholder content for the 3 new page templates:

- eligibility
- application-process
- after-you-apply

Templates copied into 3 sections:

- disability-benefits
- education
- healthcare

**Eligibility**
screenshot-localhost-3001-2017-03-07-17-29-21

**Application process**

screenshot-localhost-3001-2017-03-07-17-29-27

**After you apply**

screenshot-localhost-3001-2017-03-07-17-29-31

### CODE REVIEW

**Comment by melwoodard** [comment]
@mollyblake you can use this `content-apply-templates` branch I started to work on the content for these new pages - unless you already have an open branch I should merge this PR into?

Just noting this PR shouldn't be merged into master, so please don't close it :)

**Comment by rroueche** [comment]
Thanks @melwoodard the screenshots look amazinnnnng! I notice a Jenkins error, so I'm just working on that this morning to make sure the staging link can still be accessed. Also, updating the title here to the "WIP" format so that we don't have to worry about it accidentally getting merged in.

**Comment by rroueche** [comment]
@jkassemi would you be able to take a look at this Jenkins error? I fixed the things that were triggering it before, but this error remains and I don't know how to resolve: 
image

**Comment by bethpotts** [comment]
@amybehrens @suzchap (@rroueche FYI) I just added you as reviewers to look over the 9 new pages for Disability, Education, and HC that we'll go live with in the push to production tomorrow. Let me know if you notice anything of concern, otherwise we'll proceed! Thanks very much for your fresh eyes on these pages. Since I know Amy can't do her review until tomorrow morning, we are still making some minor language tweaks this afternoon, but all the components should be in place for Suzanne's design review right now: 
https://vetsgov-pr-5043.herokuapp.com/healthcare/eligibility/
https://vetsgov-pr-5043.herokuapp.com/healthcare/apply/
https://vetsgov-pr-5043.herokuapp.com/healthcare/after-you-apply/

https://vetsgov-pr-5043.herokuapp.com/disability-benefits/eligibility/
https://vetsgov-pr-5043.herokuapp.com/disability-benefits/apply/
https://vetsgov-pr-5043.herokuapp.com/disability-benefits/after-you-apply/

https://vetsgov-pr-5043.herokuapp.com/education/eligibility/
https://vetsgov-pr-5043.herokuapp.com/education/apply/
https://vetsgov-pr-5043.herokuapp.com/education/after-you-apply/

**Comment by suzchap** [comment]
Overall, it looks great. I love the new structure and separation of apply, process, and eligibility. Especially improved around the disability compensation process stuff (yay!).  Just a few minor suggestions:

1) https://vetsgov-pr-5043.herokuapp.com/healthcare/eligibility/

"If you separated under a dishonorable discharge, visit healthcare.gov to find out if you qualify for health insurance. Go to healthcare.gov."--- I'm afraid the healthcare.gov link looks like the main call to action for someone just skimming and clicking the first prominent link they see. Maybe bump it down to the regular type size or move to under the bullet list?

2) Some pages use "Apply for benefits" and some say "Ready to apply?" -- better to be consistent? I like "Ready to apply?" so it isn't redundant with button label

3) https://vetsgov-pr-5043.herokuapp.com/disability-benefits/apply/

Should "Be sure your claim is filled out completely and you’ve included all supporting documents. This will help us process your claim quickly. Learn more about fully developed claims."
go under the "apply" section just below it? That way the blue box stuff will be just under the bullet that's about it. 

4) https://vetsgov-pr-5043.herokuapp.com/education/apply/

Yellow ebenefits box under apply: "eBenefits.va.gov" should just be "eBenefits" or be an actual link.

**Comment by bethpotts** [comment]
@melwoodard Could you take a look above at the status of my last commit. It doesn't indicate that there are errors or failures, but the changes from my last commit aren't showing up in staging. Thanks for any help you can provide so late in the day!

**Comment by bethpotts** [comment]
@suzchap I incorporated your suggestion you gave above here, and responded to each one.

**Review by ghost — CHANGES_REQUESTED** [review]
@rroueche @amybehrens My comments are embedded here in Amy's suggestions.
https://vetsgov-pr-5043.herokuapp.com/healthcare/apply/
1) Once you’ve figured out if you qualify, applying for VA health care benefits is easy. Find out how to apply.
=> link [if you qualify] to eligibility page
**BETH: Our site style is not to have links in this first paragraph generally. And we also don't embed links. We do have a link to eligibility just below, under "Prepare." It will be more prominent once I remove the parenthetical, which is your point No. 2 below!**

2) Under "prepare" delete the comment in parenthesis: 
Find out if you qualify (if you haven’t done that already). **BETH: Done!**

**Comment by rroueche** [comment]
@bethpotts see Amy's comments above, would you be able to get these in within like the next 30 min?

**Review by rroueche — APPROVED** [review]

**Pull request merged**
