### PR TITLE
1926 remove icon react component

### PR DESCRIPTION
**Pull request by harshilmoradia**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

This PR removes the `IconUser` React component and replaces it with a Font Awesome icon.

## Related issue(s)

[department-of-veterans-affairs/vets-design-system-documentation/1926](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1926)

## Testing done

Yes,
Chrome/Edge

## Screenshots
**Before:**
Before

**After:**
After

Content Build:
Screenshot 2023-08-31 at 11 06 58 AM

Screenshot 2023-08-31 at 11 07 25 AM

## What areas of the site does it impact?

This PR would impact the area of the user nav dropdown where the IconUser React component is currently being used, replacing it with a Font Awesome icon.

### CODE REVIEW

**Review by it-harrison — APPROVED** [review]
lgtm!

**Review by Andrew565 — APPROVED** [review]

**Comment by jilladams** [comment]
Flagged that this PR has Public Websites as a reviewer bc of the interaction with the header. Not all assets automatically load / work correctly on injected sites, so it's worth thinking that through / demonstrating you've considered it.  https://dsva.slack.com/archives/C52CL1PKQ/p1693341296969089?thread_ts=1693340277.576989&cid=C52CL1PKQ

**Review by jilladams — DISMISSED** [review]
Blocking on confirmation that the injected header scenario has been considered / verified. Info on testing that scenario: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite

**Review by randimays — APPROVED** [review]

**Comment by powellkerry** [comment]
@jilladams do the screenshots that Harshil added look ok? Wanting to get this PR merged so that we can get the latest version of component-library up on vets-website.

**Review by jilladams — APPROVED** [review]
@harshil1793 apologies! APproving based on Randi's approval.

**Pull request merged**
