### PR TITLE
Improve exit (external link) icon

### PR DESCRIPTION
**Pull request by goldenmeanie**
We’re going to use this exit icon in some buttons, so I redrew it to work better on non-white backgrounds. It's still a png though.

I also renamed the variations to sort together.

### CODE REVIEW

**Review by jbalboni — APPROVED** [review]
This looks ok to me, but might be worth having @bshyong or @crwallace look at it.

**Comment by jbalboni** [comment]
@goldenmeanie Were we not using the gold icon?

**Comment by goldenmeanie** [comment]
I didn't find any evidence of it in the code

**Comment by goldenmeanie** [comment]
And yeah, I should have tagged one of them instead. Been a long day of you answering all my questions!

**Review by crwallace — APPROVED** [review]
LGTM!

**Pull request merged**
