### PR TITLE
VACMS 17781 - Disable VA Benefits Service Type dropdown

### PR DESCRIPTION
**Pull request by eselkin**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

- Made selecting VA Benefits from Facility Type in the Facility Locator disable the Service Type dropdown (since we aren't pushing those to Lighthouse) for now
- Until we push service types to LH from CMS and have the ids available to Vets-website (autosuggest proces) we won't enable this dropdown or a typeahead.
- Sitewide team (we own Facility Locator)

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17781

## Testing done

- Modified cypress and unit tests to support this change
- Follow steps below to test
- Also manually tested

## Screenshots

SCR-20240905-mtaa

## What areas of the site does it impact?

Facility Locator (/find-locations when VA Benefits is selected)

## Acceptance criteria

- [x] Service type dropdown is disabled in facility locator with VBA is selected, to match behavior with Vet Centers

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user (unauthenticated)

## Requested Feedback

Check /find-locations on RI (cannot produce on tugboat)
Select VA benefits from Facility Type, check that search still performs as expected (compare with https://dev.va.gov/find-locations (won't be the same results as va.gov/find-locations)

### CODE REVIEW

**Comment by eselkin** [comment]
@laflannery Unfortunately, you're probably the only person who can review this. In the results list of every Facility Type on the Facility Locator, I've added a tabindex (because we were put on flaky test alert and would not be able to merge without it). I made the tabindex the index in the list that the item is, but this may not be what we want. The items themselves are not "interactive" in a normal sense, so maybe we want to change what becomes the tabindexed item.

**Comment by laflannery** [comment]
@eselkin it was working earlier but now I'm getting an error so I can't test the `tabindex` you wanted me to. Do you know if this will clear up? I don't know why it would have started error all of a sudden:
image

**Comment by laflannery** [comment]
@eselkin I checked this again this morning, I can see the correct `tabindex` in the files changed but I can't see it in the Review Instance and I don't know why.

I'm on [this URL](http://0a1f06b95359003f1a5cd1accdb4caa4.review.vetsgov-internal/find-locations/?page=1&address=02038&facilityType=benefits&serviceType&latitude=42.082423&longitude=-71.396688&radius=10&bounds%5B%5D=-72.796688&bounds%5B%5D=40.682423&bounds%5B%5D=-69.99668799999999&bounds%5B%5D=43.482423&context=Franklin%2C%20Massachusetts%2002038%2C%20United%20States) and this is what I see:

image

**Review by laflannery — DISMISSED** [review]
LGTM!

**Review by laflannery — APPROVED** [review]
Approved!

Tested no results and results listings for all facility types. Also noting that the focus management for Emergency and Urgent care results lists should be improved to be consistent with the other facility types but [a new ticket has been made for this](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19176)

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Comment by jilladams** [comment]
Flaky Axe test is tracked here now: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19189

**Pull request merged**
