### PR TITLE
Remove visit feedback forum link

### PR DESCRIPTION
**Pull request by suzchap**
Removed the "visit the feedback forum link" per https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2049.

Please make sure I did this correctly!

### CODE REVIEW

**Comment by tiffanybbrown-va** [comment]
There's one other thing to do, and that's decide whether the link should be white or bluish. This is what it looks like after your change.

screen shot 2017-04-10 at 4 26 12 pm

If it should be white, then the `opacity: 0.6` line needs to be removed from this block:

    .feedback-widget:last-child {
      opacity: 0.6;
      padding-left: 1em;
    }

Otherwise, LGTM.

**Comment by jcmeloni-usds** [comment]
Thanks @tiffanybbrown-va !  @suzchap up to you if you want to change. You can change it on the same branch and the PR will update, or you can decide not to change it and press the merge button and it'll go in tomorrow. Whoo hoo!  Good job.

**Review by jcmeloni-usds — APPROVED** [review]

**Comment by suzchap** [comment]
@tiffanybbrown-va Good catch! I'd prefer it to be white. Would you mind changing it? I'm trying to be self sufficient but I also know my limitations ;)

**Review by ghost — APPROVED** [review]

**Comment by tiffanybbrown-va** [comment]
Not merging just in case y'all want to double-check my CSS. Otherwise, I think it's okay to merge.

**Pull request merged**
