### PR TITLE
Updated deprecated care expenses fields

### PR DESCRIPTION
**Pull request by danlim715**
## Summary

- On the Unreimbursed care expenses page, update the deprecated fields with the v3 component equivalent.
- Pension benefits team to own this work.

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#76777
- [_Link to epic if not included in ticket_](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/76777)

## Testing done

- On the add new care expenses page, childName, provider, hoursPerWeek, and noCareEndDate used to be the older version component. The hoursPerWeek field used to be a number field, but now it has become a text field with a validation that prevents non-digit numbers from being entered.
- Navigate through the pension application until you reach the add care expenses page. There you should be able to see and confirm the component changes.
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile | image | image |
| Desktop | image | image |

## What areas of the site does it impact?

Pension application

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

### CODE REVIEW

**Review by ToddWebDev — APPROVED** [review]

**Review by ToddWebDev — CHANGES_REQUESTED** [review]
When running this locally I noticed that this changes 'hoursPerWeek' from an integer to a string. We will need to update the test data as well (maximal-test.json, etc) and ensure that the API will not break with 'in progress' forms that have 'hoursPerWeek' saved as an integer.

**Comment by ToddWebDev** [comment]
After additional testing, an 'in progress' form with an integer saved for 'hoursPerWeek' will not be able to be submitted without editing the 'Financial information' > 'Unreimbursed care expenses' section, since the form is invalid. The UI does show the error in the correct chapter and section for the Veteran to update their 'Unreimbursed care expenses' so we just need to make sure the 'string' will not break the API.
Screenshot 2024-03-06 at 8 22 30 AM

**Comment by Andrew565** [comment]
PR has requested changes pending, opting not to review at this time. - Tier 2/FE CoP

**Review by ToddWebDev — APPROVED** [review]

**Comment by danlim715** [comment]
this branch looks to be borked. Closing and reopening new branch.

**Pull request closed without merging**
