### PR TITLE
76700 Burials URL updates

### PR DESCRIPTION
**Pull request by DLarson-Oddball**
## Summary

Updates burials url

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/76700

## Testing done
Ensured form loads as expected  at http://localhost:3001/burials-memorials/veterans-burial-allowance/apply-for-allowance-form-21p-530ez/introduction

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by tblackwe — DISMISSED** [review]

**Comment by IGallupSoCo** [comment]
You will need to pull the latest changes to main in.  CI is breaking here due to a now-absent branch that was triggering stylelint at an unexpected part of the workflow.

**Comment by eselkin** [comment]
I'm confused why one app is changing 570 files? Does it just need to be brought up to date with main or is there something more substantial going on here?

**Comment by DLarson-Oddball** [comment]
> I'm confused why one app is changing 570 files? Does it just need to be brought up to date with main or is there something more substantial going on here?

Hey @eselkin Thanks for taking a look! I cleaned up the PR, so this should be good for another pass. Thanks!

**Review by Midge-dev — APPROVED** [review]
LGTM :shipit:

**Review by eselkin — APPROVED** [review]
LGTM

**Review by tblackwe — APPROVED** [review]

**Review by asiisii — APPROVED** [review]
LGTM

**Review by micahchiang — APPROVED** [review]

**Pull request merged**
