### PR TITLE
Update legacy content on schedule appt page

### PR DESCRIPTION
**Pull request by kelsonic**
## Description
**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/12446

This PR doesn't actually have a related ticket except [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12446#issuecomment-674324572) within the issue mentioned above. This PR updates the legacy content on the schedule appt page.

## Testing done
Updated unit test

## Screenshots
N/A

## Acceptance criteria
- [x] Update legacy content

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by DanielleThierryUSDSVA — COMMENTED** [review]
Hi @kelsonic. This looks great! I saw just 2 things:

1. I don't see the intro paragraph changes. Can you update intro paragraph to read:

With our VA appointments tool, you can schedule some VA health care appointments and request approved community care (non-VA) appointments online. You can also review details about upcoming appointments and organize your health calendar. Find out if you’re eligible, and how to sign up to begin using this tool.

2. In line 308, can we change "these tools" to "this tool" please? So it will read: " provider outside of VA, you can use this tool to submit" This is an added content update that I noticed when reviewing.

**Comment by kelsonic** [comment]
@DanielleThierryUSDSVA 1 actually has to be done in Drupal! I can show you how to do this on that page though if you'd like! 🙂 2 has been incorporated in the PR just now! Thank you!

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @kelsonic! I'll make the change in Drupal this morning. Approving PR now. Thanks!

**Review by DanielleThierryUSDSVA — APPROVED** [review]

**Review by ncksllvn — APPROVED** [review]

**Review by jhonny218 — APPROVED** [review]
LGTM

**Pull request merged**
