### PR TITLE
Add structured markup to eligibiltiy.md

### PR DESCRIPTION
**Pull request by robbiethegeek-usds**

### CODE REVIEW

**Comment by robbiethegeek-usds** [comment]
@phiden can you please take a look and compare this page from production to the heroku instance to confirm the design is not impacted.

@bethpotts can you confirm that the content is the same between production and the heroku instance.

Would like to get this submitted today for deploy today

**Review by phiden — CHANGES_REQUESTED** [review]
Did you mean to remove "-You can check to see if you have Post-9/11 GI Bill benefits. [View and print your statement of benefits](/education/gi-bill/post-9-11/ch-33-benefit)."?

**Comment by robbiethegeek-usds** [comment]
Added back @phiden sorry about that, thanks for catching

**Review by phiden — APPROVED** [review]

**Comment by phiden** [comment]
As soon as @bethpotts validates content, lmk and I will merge!

**Review by bethpotts — APPROVED** [review]
Content looks good now! Approved.

**Pull request merged**
