### PR TITLE
96379 Update alert on choose a VA location page - Part 1

### PR DESCRIPTION
**Pull request by vbahinwillit**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

If the folder you changed contains a `manifest.json`, search for its `entryName` in the content-build [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) (the `entryName` there will match).

If an entry for this folder exists in content-build and you are:
1. **Deleting a folder**:
   1. First search `vets-website` for _all_ instances of the `entryName` in your `manifest.json` and remove them in a separate PR. Look particularly for references in `src/applications/static-pages/static-pages-entry.js` and `src/platform/forms/constants.js`. _**If you do not do this, other applications will break!**_
      - _Add the link to your merged vets-website PR here_
   2. Then, Delete the application entry in [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) and merge that PR **before** this one
      - _Add the link to your merged content-build PR here_

2. **Renaming or moving a folder**: Update the entry in the [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json), but do not merge it until your vets-website changes here are merged. The content-build PR must be merged immediately after your vets-website change is merged in to avoid CI errors with content-build (and Tugboat).

### :warning: TeamSites :warning:
Examples of a TeamSite: https://va.gov/health and https://benefits.va.gov/benefits/. This scenario is also referred to as the "injected" header and footer. You can reach out in the `#sitewide-public-websites` Slack channel for questions.

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary
This PR updates the alert text displayed on the 'Choose a VA location' page.

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#96379

## Testing done
Unit and e2e

## Screenshots

|         | Before | After |
| ------- | ------ | ----- |
| Mobile | localhost_3001_my-health_appointments_schedule_location(iPhone 14 Pro Max) (1)  | localhost_3001_my-health_appointments_schedule_location(iPhone 14 Pro Max)  |
| Desktop | localhost_3001_my-health_appointments_schedule_location (1)  | localhost_3001_my-health_appointments_schedule_location (2) |

## What areas of the site does it impact?
VAOS

## Acceptance criteria
All test pass

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by jenniemc** [comment]
@vbahinwillit , What is your local configuration to get the warning message above? I'm getting something entirely different.

Screenshot 2024-11-18 at 2 23 48 PM

Here are my steps: 

- In "featureFlags.js" both `vaOnlineSchedulingOhDirectSchedule` and `vaOnlineSchedulingOhRequest` =  `true`
- In  "scheduling_configurations.json" 983 has Direct Schedule and request `enabled` = `false` for Amputation care
- Select Start Scheduling > Amputation Care > Cheyenne VA Medical Center

**Comment by vbahinwillit** [comment]
@jenniemc - I have whatever the defaults are for the feature flags. It's strange that a modal is displaying as well.

```
  { name: 'facilityLocatorShowCommunityCares', value: true },
  { name: 'profile_show_profile_2.0', value: false },
  { name: 'vaOnlineScheduling', value: true },
  { name: 'vaOnlineSchedulingCancel', value: true },
  { name: 'vaOnlineSchedulingRequests', value: true },
  { name: 'vaOnlineSchedulingCommunityCare', value: true },
  { name: 'vaOnlineSchedulingDirect', value: true },
  { name: 'vaOnlineSchedulingPast', value: true },
  { name: 'vaOnlineSchedulingExpressCare', value: true },
  { name: 'vaOnlineSchedulingFlatFacilityPage', value: true },
  { name: 'vaOnlineSchedulingVAOSServiceRequests', value: true },
  { name: 'vaOnlineSchedulingVAOSServiceVAAppointments', value: true },
  { name: 'vaOnlineSchedulingFacilitiesServiceV2', value: true },
  { name: 'vaOnlineSchedulingVAOSServiceCCAppointments', value: true },
  { name: 'vaOnlineSchedulingStatusImprovement', value: true },
  { name: 'vaOnlineSchedulingVAOSV2Next', value: true },
  { name: 'vaOnlineSchedulingClinicFilter', value: true },
  { name: 'vaOnlineSchedulingUseDsot', value: true },
  { name: 'vaOnlineSchedulingConvertUtcToLocal', value: false },
  { name: 'vaOnlineSchedulingBreadcrumbUrlUpdate', value: true },
  { name: 'vaOnlineSchedulingBookingExclusion', value: false },
  { name: 'vaOnlineSchedulingStaticLandingPage', value: true },
  { name: 'vaOnlineSchedulingAfterVisitSummary', value: true },
  { name: 'vaOnlineSchedulingStartSchedulingLink', value: true },
  { name: 'vaOnlineSchedulingDatadogRum', value: true },
  { name: 'vaOnlineSchedulingCCDirectScheduling', value: false },
  { name: 'vaOnlineSchedulingRecentLocationsFilter', value: false },
  { name: 'vaOnlineSchedulingOhDirectSchedule', value: false },
  { name: 'vaOnlineSchedulingOhRequest', value: false },
  { name: 'vaOnlineSchedulingRemovePodiatry', value: false },
  { name: 'selectFeaturePocTypeOfCare', value: true },
  { name: 'edu_section_103', value: true },
  { name: 'gibctEybBottomSheet', value: true },
  { name: 'travelPayViewClaimDetails', value: false },
```

**Comment by vbahinwillit** [comment]
@jenniemc - I have scheduling for facility 983 direct and request turned off in scheduling_configruations.json as well.

**Comment by jenniemc** [comment]
@vbahinwillit, So strange. If I use the default in feature flags, it sends me to the "How to schedule" page (ScheduleCernerPage.jsx) after selecting Cheyenne VA Medical Center.

**Review by jenniemc — APPROVED** [review]
LGTM! 
May want to ask Peter what to display if no facility is returned to supply phone number to call.

**Review by harshilmoradia — APPROVED** [review]

**Comment by vbahinwillit** [comment]
@outerpress - Is the following display correct when there are no facilities found? Specifically, should the text. "You'll need to call to schedule." be displayed? Thanks

localhost_3001_my-health_appointments_schedule_location (3)

**Pull request merged**
