### PR TITLE
Moved how to link to its own component and added to confirmation and …

### PR DESCRIPTION
**Pull request by brianseek**
…error. Also turned on local feature for phone.

## Description
More updates for how to link. Adding to error pages and only showing for clinic appointments.

## Original issue(s)
department-of-veterans-affairs/va.gov-team#46347

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by acrollet** [comment]
Testing notes:

* visiting at time of appointment for clinic appointment:
   * see the link
* visiting at time of appointment for phone appointment:
   * do not see the link
* visiting the day before the appointment for phone appointment:
   * do not see the link
* visiting the day before the appointment for clinic appointment:
   * see the link
* visiting the day before the appointment for canceled clinic appointment:
   * see the link
* visiting the day before the appointment for canceled phone appointment:
   * do not see the link

**Comment by acrollet** [comment]
re-tested, new results:

Testing notes:

* visiting at time of appointment for clinic appointment:
   * see the link
* visiting at time of appointment for phone appointment:
   * do not see the link
* visiting the day before the appointment for phone appointment:
   * do not see the link
* visiting the day before the appointment for clinic appointment:
   * see the link
* visiting the day before the appointment for canceled clinic appointment:
   * do not see the link
* visiting the day before the appointment for canceled phone appointment:
   * do not see the link

**Review by acrollet — APPROVED** [review]
🐙

**Comment by loripusey** [comment]
Thanks @acrollet , I think this last testing looks like the correct behavior.

**Pull request merged**
