### PR TITLE
content/wip/Bdd quick start sme updates

### PR DESCRIPTION
**Pull request by DanielleSoCompany**

### CODE REVIEW

**Comment by bethpotts** [comment]
@phiden We're still waiting for SME feedback on this one. In the meantime, would it be a good idea to merge master into this branch to keep it up to date?

**Comment by phiden** [comment]
@bethpotts possibly; it already has conflicts and those are only going to increase the longer this sits open. @leannammiller ok to add to my tasks?

**Comment by leannammiller** [comment]
slay away @phiden - let me know if we need to push something from this sprint!

**Comment by phiden** [comment]
@bethpotts pulled in master -- should be up to date now

**Comment by kellyskennedy** [comment]
@peggygannon Can you review this, please?

**Comment by bethpotts** [comment]
@peggygannon @kellyskennedy I'll do the final review/proofread on this rather than Peggy. I've been ushering this one through. Thanks, Kelly!

**Comment by kellyskennedy** [comment]
Ready for your review, @bethpotts I think I got 'em...

**Comment by kellyskennedy** [comment]
Can you take a look, @peggygannon ? And then I think @bethpotts would like to see it. Thanks!

**Comment by peggygannon** [comment]
@kellyskennedy Hi, Kelly, is there a list or ticket that shows the changes that were to be implemented?

**Comment by kellyskennedy** [comment]
#6095

**Review by peggygannon — COMMENTED** [review]
@kellyskennedy @bethpotts Copy edit is complete for both pages. 
There is one more place where we need to fix "predischarge". It's in a breadcrumb, but I can't find the file that contains that breadcrumb in github. I'm attaching a screenshot
predischarge screenshot

**Comment by bethpotts** [comment]
@phiden (NOT READY TO MERGE, just need you help with a couple things!)
1) Please reference the screenshot above. Can you help us fix the little subhead (Predischarge claims) in the left nav where there's only "File a Claim While Overseas"? This left nav subhead needs to be "claim" singular and have a hyphen in "Pre-discharge." Like this:
Pre-discharge claim
2) Can you help resolve the conflicting file?

**Review by bethpotts — APPROVED** [review]
This is ready for @phiden to review and merge.

**Review by phiden — APPROVED** [review]

**Pull request merged**
