### PR TITLE
Remove Type of Care categories then alphabetize list

### PR DESCRIPTION
**Pull request by jenniemc**
## Description
create an alphabetized list of care for vet to choose from

## Testing done
unit test

## Screenshots
image

## Acceptance criteria
- [ ] displays alphabetized list of care for vet to choose from

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by jbalboni** [comment]
@jenniemc Since we don't have the grouping anymore, we can remove the TypeOfCareField component entirely and update the TypeOfCarePage component to use our regular radio widget. You can see an example of how this would work on TypeOfVisitPage (https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/containers/TypeOfVisitPage.jsx)

**Comment by jenniemc** [comment]
@jbaldoni, all checks have passed. Would you approve the draft PR?

**Review by jbalboni — APPROVED** [review]

**Comment by jbalboni** [comment]
@jenniemc I approved it, but can you remove the TypeOfCareField file and any tests associated with it?

**Review by narin — APPROVED** [review]
LGTM, but looks like you can delete the `TypeOfCareField.jsx` since it's no longer in use.

**Review by rianfowler — APPROVED** [review]

**Comment by jenniemc** [comment]
@jbalboni, do i simply go to the "files changed" tab then select "Delete File" from the more options? Like the screenshot below?



image

**Comment by jbalboni** [comment]
@jenniemc I would delete it on your local machine, then commit the changes and push them up.

**Comment by jenniemc** [comment]
@jbalboni, does that mean i am removing the file from my branch but the file remains unchanged and intact in Master?  Does "TypeOfCareField.jsx" remain unchanged and intact in the Master Repo after I do the Squash and Merge?

**Comment by jbalboni** [comment]
@jenniemc You want to remove it locally while on your branch, push those changes up, and then when you squash and merge, it'll be removed on master.

**Pull request merged**
