### PR TITLE
incorporating updates to avoid dead-ends

### PR DESCRIPTION
**Pull request by DanielleSoCompany**

### CODE REVIEW

**Comment by DanielleSoCompany** [comment]
@peggygannon here's the PR for proofing. Thank you!

**Review by peggygannon — APPROVED** [review]
@DanielleSoCompany Hello. I've proofed and made some minor tweaks to the copy (what we discussed over Slack), as well as updated quote marks and some bold formatting. 
Let me know if you have any questions.

**Comment by DanielleSoCompany** [comment]
@peggygannon this is ready for your final proof of changes. thank you!

**Review by peggygannon — APPROVED** [review]
@DanielleSoCompany Proofread is complete. A few things to note:
1. I'm not sure if updating title of this page was ever discussed, but we might want to think about updating it at some point to make it more descriptive that the FAQs are about sign in and creating an account. 
2. The [Sign in now] links didn't work for me. I'm not sure if this is because I was in a heroku link, but I want to let you know.

**Comment by DanielleSoCompany** [comment]
Thank you, @peggygannon! Proofing changes are great. And that's a very good question about the title. I'll run it by Natalie and see if we might want to update to something like: FAQs About Signing In to Vets.gov. For the links, yes, they won't work in heroku. Thank you!

**Comment by DanielleSoCompany** [comment]
Hi @phiden. Could you please review and merge this PR today? Just let me know if you have any questions or concerns. Thanks!

**Review by phiden — APPROVED** [review]

**Pull request merged**
