### PR TITLE
feature/16544axe-4-bump - Bumping axe to current version 4.1.1 in CI/CD pipeline

### PR DESCRIPTION
**Pull request by 1Copenut**
## Description
The [axe browser plugin](https://deque.com/axe) uses the current version of the axe ruleset, V4.1.1. This PR bumps our axe-core dependency in the package.json file and updates the Cypress `axeCheck()` helper method to allow developers to pass individual rule and ruleset overrides. Documentation will be updated in a fast-follow PR on va.gov-team repo.

## Testing done
All evaluations were run against the Google Analytics test in Facility Locator. This test was modified because the `axeCheck()` was happening before the page was rendered. This was discovered by accident during my axeConfig testing, so if I need to revert this test and exclude it from the PR, I'm happy to do so.

### gaEvents.cypress.spec.js (Facility Locator)

* True negative - no errors in pages under test
  * Run 30 times on Cypress 6.3
    * First page has best-practices ruleset enabled, and color-contrast rule enabled
    * Detail page has color-contrast rule enabled
  * Zero accessibility errors on either page
  * Run additional 20 times on Cypress 6.4 with same outcomes as previous test
* True positive - accessibility errors in pages under test
  * Run 30 times
    * First page has best-practices ruleset enabled, and color-contrast rule enabled
    * First page has no accessibility errors
    * Detail page has two accessibility errors:
      * h1 has a `role="nonsense"` attribute
      * h1 has a **`color #999`** that does not meet 4.5:1 color contrast ratio requirement
  * Detail page has two accessibility errors detected on each run
  * Run additional 20 times on Cypress 6.4 with same outcomes as previous test
* False negative - accessibility errors in pages under test are not detected
  * Run 30 times
    * First page has `{ _13647Exception: true }` enabled AND
    * First page has a **`color #999`** that does not meet 4.5:1 color contrast ratio requirement
    * Detail page has `{ _13647Exception: true }` enabled AND
    * Detail page has a **`color #999`** that does not meet 4.5:1 color contrast ratio requirement
  * Zero accessibility errors on either page
  * Run additional 20 times on Cypress 6.4 with same outcomes as previous test
* Best practice - deliberately skipped a heading level to ensure best practices ruleset is being evaluated
  * Run 30 times with best practices ruleset enabled
    * 1 accessibility error detected on first page
  * Run 30 times with best practices ruleset disabled
    * 0 accessibility errors detected on first page
* WCAG 2.1 deliberately added an `autocomplete="nonsense"` to ensure WCAG 2.1 ruleset is being evaluated
  * Run 30 times with WCAG 2.1 ruleset enabled
    * 1 accessibility error detected on first page
  * Run 30 times with WCAG 2.1 ruleset disabled
    * 0 accessibility errors detected on first page
* Axe-core 4.1.1 ran against all static content
  * Used command `yarn test:accessibility` after pulling latest Drupal content
  * Ran the test twice against 1500+ static pages
  * Zero errors
* All unit tests were run locally, zero failures on 3 passes after fixing a break in `ProgressBar.unit.spec.js`. This was a good sign, it meant the unit tests were picking up the current version of axe-core for their automated scans.
* UPDATE 2/17: Bumped Cypress to 6.5 and retested e2e tests briefly with helper methods

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by mpelzsherman** [comment]
FYI there's a failure in `src/platform/forms-system/test/js/components/ProgressBar.unit.spec.jsx` that is preventing the Cypress tests from running in Jenkins.

**Comment by mpelzsherman** [comment]
I tested the changes to `src/applications/facility-locator/tests/e2e/gaEvents.cypress.spec.js` locally, and the test passes.

I am curious to know whether this tests even needs axe checks though, since the purpose of the test is to check for specific GA events being sent. (?)

**Review by mpelzsherman — APPROVED** [review]

**Review by jhonny218 — APPROVED** [review]
LGTM

**Comment by 1Copenut** [comment]
@mpelzsherman 
> I tested the changes to `src/applications/facility-locator/tests/e2e/gaEvents.cypress.spec.js` locally, and the test passes.
> 
> I am curious to know whether this tests even needs axe checks though, since the purpose of the test is to check for specific GA events being sent. (?)

Good point. I'll revert this to the previous version and make sure it's excluded from the PR.

**Review by ddzz — APPROVED** [review]
LGTM -- ran tests locally, no aXe failures observed.

**Review by billfienberg — APPROVED** [review]

**Review by holdenhinkle — APPROVED** [review]
The following tests failed in headless mode but I reviewed the Cypress videos and none of them failed due to aXe reasons:

```
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  applications/facility-locator/tests      00:21        2        1        1        -        - │
  │    /e2e/mobile.cypress.spec.js                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  applications/personalization/view-r      00:03        1        -        1        -        - │
  │    epresentative/tests/view-representa                                                         │
  │    tive.cypress.spec.js                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  site/layouts/tests/vamc/location_ho      00:17        2        -        2        -        - │
  │    me.cypress.spec.js                                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  site/layouts/tests/vamc/system_home      00:38        2        -        2        -        - │
  │    .cypress.spec.js                                                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  4 of 100 failed (4%)                     27:18      210      171        6       33        -  
```

LGTM

**Review by cvalarida — COMMENTED** [review]
Looks like the progress bar in the forms library is only used in `FileField`. If you're changing that to use the `ProgressBar` from the component library (which I think is great), please also remove `src/platform/forms-system/src/js/fields/FileField.jsx` and the associated test. No use for that to hang around, potentially confusing folks later. :man_shrugging: 

image

**Review by cvalarida — APPROVED** [review]
Looks great from the design system team side. :+1:

**Pull request merged**
