### PR TITLE
WIP/Content/Pension apply updates

### PR DESCRIPTION
**Pull request by peggygannon**
Update Pension Eligibility and Pension Apply apply information to match the Pension FDC page.

### CODE REVIEW

**Comment by peggygannon** [comment]
@bethpotts This PR for refining the apply language on Pension Apply and Pension Eligibility page is ready for your review.

**Review by bethpotts — APPROVED** [review]
Looks perfect! And now all three pages are consistent: elig, apply, and FDC. You can request a code review and merge now.

**Comment by peggygannon** [comment]
@phiden this PR is ready for your review and merge. thank you!

**Review by phiden — APPROVED** [review]

**Comment by phiden** [comment]
@peggygannon reviewed + approved, but there's a save-in-progress test failing. I restarted the run hoping it's just a gremlin, but if it doesn't pass you should ping the front-end team for help!

**Pull request merged**
