### PR TITLE
User notification of Austin SAN issues

### PR DESCRIPTION
**Pull request by jkassemi**
VBMS-backed service outage that may affect VIC, EVSS, and HCA. Provides user notice. Needs copy suggestion and approval.

ref https://github.com/department-of-veterans-affairs/vets.gov-team/issues/7031

### CODE REVIEW

**Comment by jkassemi** [comment]
screen shot 2018-01-02 at 11 11 55 am

**Comment by jkassemi** [comment]
screen shot 2018-01-02 at 11 20 59 am

**Comment by bethpotts** [comment]
@jkassemi I can take a look at this in the next hour. Is it for today's build?

**Comment by jkassemi** [comment]
We may not need this to go out today, since it looks like systems may be running within the next hour. I would like to have an idea for copy in case we run into this or a similar incident in the near future.

**Comment by jkassemi** [comment]
(but also an idea for this copy in case the incident is _not_ resolved soon)

**Comment by DanielleSoCompany** [comment]
Hi @jkassemi. Here's the copy from @bethpotts and I. Just let us know if you have any questions/concerns. Thanks!

**Some Vets.gov tools may not be working**
We’re sorry. We’re working on our data system right now. Some Vets.gov tools—including Veteran ID cards, claims and appeals, and Post-9/11 GI Bill benefits status—may not be working during this time. Please check back soon.

**Comment by jkassemi** [comment]
That's perfect, thank you! We'll keep the copy in our pocket for future outages; we can easily replace the described affected services in an emergency update when necessary.

**Comment by DanielleSoCompany** [comment]
Awesome!

**Comment by jkassemi** [comment]
Expecting another update on the issue at 4PM ET. If we're still unsure of when systems will be back online we'll go ahead with the updated copy.

**Comment by bethpotts** [comment]
@jkassemi @DanielleSoCompany Can we also replace the title "System Maintenance" with the more plain language "Some Vets.gov tools may not be working"?

**Comment by jkassemi** [comment]
No ANR updates. Will get this to production now and revert as soon as service restored for PD#946-949

**Review by jbalboni — APPROVED** [review]

**Comment by jbalboni** [comment]
Ideally, I think we wouldn't have the left hand border on the alert, but I don't think it should hold this up.

**Pull request merged**
