### PR TITLE
Removed link and modal from GIBCT profile line for veterans tuition policy.

### PR DESCRIPTION
**Pull request by U-DON**
Resolves department-of-veterans-affairs/vets.gov-team#4665.

### CODE REVIEW

**Comment by saintsoup52** [comment]
What are we doing here? Is there a problem with the veterans tuition policy links?

**Review by bshyong — APPROVED** [review]
LGTM

**Comment by bshyong** [comment]
@saintsoup52 this is a minor UI level change—removal of a link to a "tooltip" modal that does not provide much relevant information to the user

**Comment by U-DON** [comment]
screen shot 2017-09-07 at 2 25 04 pm

@saintsoup52: The change removes the link to the 'Veterans tuition policy" line. Before, clicking it would pop up a modal that only said, "URL for tuition policies specifically related to veterans and military service members."

**Comment by saintsoup52** [comment]
Thanks for the explanation... I am happy that the link to the school's policy is not going away.

**Pull request merged**
