### PR TITLE
#80476 [10-10 EZR]: Remove TERA Alert

### PR DESCRIPTION
**Pull request by JoshingYou1**
## Summary

- Removed the EZR TERA alert component from the introduction page.
- Removed the `ezr-tera-alert` static page

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80476

## What areas of the site does it impact?

- The 10-10EZR form

### CODE REVIEW

**Review by dellerbie — APPROVED** [review]
LGTM, perhaps clean up the PR description removing the sections that aren't necessary for this

**Review by mkerns1 — APPROVED** [review]
Thanks for jumping on this Josh LGTM!

**Comment by JoshingYou1** [comment]
> LGTM, perhaps clean up the PR description removing the sections that aren't necessary for this

Done! Thanks Derrick!

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Pull request merged**
