### PR TITLE
Add specificity to no icon styling

### PR DESCRIPTION
**Pull request by akainic**
Icons were appearing in some alerts when they weren't supposed to be:

screen shot 2016-09-29 at 3 41 47 pm

Added another class to increase specificity so that the styles to remove the icon take precedence:

screen shot 2016-09-29 at 3 41 13 pm

### CODE REVIEW

**Review by jbalboni — APPROVED** [review]
LGTM. I think the build failure is something I need to fix separately. Might work if you re-run it.

**Comment by webinista** [comment]
That's weird. `.edu-benefits-info-no-icon` should be enough to override the styles in `.usa-alert-info`. Are the edu styles being loaded after USWDS?

**Comment by akainic** [comment]
@webinista edu styles should be loaded after USWDS, but for some reason when I look at the css source file there are some `.usa-alert-info` styles being loaded after `edu-benefits-info-no-icon`. Trying to figure out in vets-website where that's coming from...

**Comment by webinista** [comment]
Ah. Caused by #3057.

**Comment by akainic** [comment]
Ah, thanks for tracking that down @webinista. Do you mind if we merge this for now until we're able to fix that other issue? Just because this is creating a visible bug for us.

**Comment by webinista** [comment]
Not at all. That will take much longer to fix.

**Comment by akainic** [comment]
Sounds good! I'm going to merge then.

**Pull request merged**
