### PR TITLE
add feature flag for use with disability labels

### PR DESCRIPTION
**Pull request by lukey-luke**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- VA Platform Feature toggles guide suggests submitting PR's for feature flags
- this is a follow-up to https://github.com/department-of-veterans-affairs/vets-api/pull/14493

## Related issue(s)

- https://github.com/department-of-veterans-affairs/vagov-claim-classification/issues/299

## Testing done

- n/a
- future unit testing will be done when making use of this feature flag

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
n/a
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
n/a
- [ ] Screenshot of the developed feature is added
n/a
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed
n/a

### Error Handling

- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
n/a
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)
n/a

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by lukey-luke** [comment]
Marked as draft, because still waiting on

_Validate changes to DataDog Service Catalog Files Expected — Waiting for status to be reported
Required_
for https://github.com/department-of-veterans-affairs/vets-api/pull/14493

**Comment by lukey-luke** [comment]
Somehow this totally fell off my radar and I never marked it as ready-for-review. This just contains the code to access the feature flag from https://github.com/department-of-veterans-affairs/vets-api/pull/14493 in `src/platform/utilities/feature-toggles/featureFlagNames.js`

**Review by powellkerry — APPROVED** [review]

**Review by tyler-spangler6 — APPROVED** [review]
Approved

**Comment by lukey-luke** [comment]
closing in favor of https://github.com/department-of-veterans-affairs/vets-website/pull/27077

**Pull request closed without merging**
