### PR TITLE
copy updates

### PR DESCRIPTION
**Pull request by rianfowler**
Removed several of the conditionals that were switching on `production`. 
screen shot 2018-05-29 at 11 14 56

### CODE REVIEW

**Review by peggygannon — APPROVED** [review]
@rianfowler looks good. thanks!

**Comment by jbalboni** [comment]
@rianfowler I don't think we want to remove the conditionals yet. If we do, we can't merge this until the HCA changes go live.

**Comment by rianfowler** [comment]
@jbalboni so this is live and we're adding an email notification. 
screen shot 2018-05-30 at 09 14 02

**Comment by jbalboni** [comment]
Correct, the HCA form is live, but we're making the process async and adding a failure email, which entails some copy changes here, which you're getting the second round of. Unless something changed yesterday that I'm not aware of.

**Comment by rianfowler** [comment]
Nope- I need to ask for more context in the future before making logic changes.

**Review by jbalboni — APPROVED** [review]

**Pull request merged**
