### PR TITLE
15484 ui updates

### PR DESCRIPTION
**Pull request by cohnjesse**
## Description
[Original Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15484)

This PR is to address a few of the UI updates on View Patments that have from the collaboration cycle. This PR is also accompanied by an update I made to the `<Table />` Component in the `formation-react` repo [here](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/503)

## Screenshots

Here are each of the changes along with screenshots of those changes
<details>
  <summary>The breadcrumb should say, "Your VA payments"</summary>
  
Screen Shot 2020-11-12 at 1 10 21 PM

</details>

<details>
  <summary>The intro text below the H1 need to have line-height increased--it's too tight.</summary>
  
Screen Shot 2020-11-12 at 1 14 17 PM

</details>

<details>
  <summary>Change intro text to "Check your payment history for your VA disability compensation, pension, and education benefits."</summary>
  
see the previous screenshot

</details>

<details>
  <summary>Need standard space (padding/margin) below last paragraph</summary>
  
Screen Shot 2020-11-12 at 1 16 10 PM

</details>

<details>
  <summary>The line, "If you have questions about payments made by VA, please call the VA Help Desk at 800-827-1000," is its own paragraph</summary>
  
Screen Shot 2020-11-12 at 1 17 41 PM

</details>

<details>
  <summary>Right sidebar content needs left/right margin in mobile view</summary>
  
Screen Shot 2020-11-12 at 1 19 46 PM

</details>

<details>
  <summary>Link to profile" in sidebar should read, "Go to your profile"</summary>
  
Screen Shot 2020-11-12 at 1 22 17 PM

</details>

<details>
  <summary>Right align numerical columns, e.g. Amount, Account, Check # etc</summary>
  
Screen Shot 2020-11-12 at 1 29 05 PM

</details>

<details>
  <summary>Sentence case these labels: "Issue date" and "Cancel date"</summary>
  
Screen Shot 2020-11-12 at 1 41 24 PM

</details>

<details>
  <summary>There is no padding between the Payments table and the following paragraph when the is no pagination stepper</summary>
  
Screen Shot 2020-11-12 at 1 42 37 PM

</details>

<details>
  <summary>Change content of "Missing check" paragraph, and right side bar content to match mockup</summary>
  
Screen Shot 2020-11-12 at 1 44 12 PM

Screen Shot 2020-11-12 at 1 44 22 PM

</details>

## Testing done
existing unit tests pass

## Acceptance criteria
- [x] All items in the list above are addressed OR
- [x] Items that cannot be addressed are documented with a brief explanation in the comments

### CODE REVIEW

**Review by micahchiang — APPROVED** [review]
lgtm

**Review by Clark-W-Griswold — APPROVED** [review]
Approved, but looks like we have a failing test. 👍

**Comment by cohnjesse** [comment]
@Clark-W-Griswold my understanding is that we are not supposed to be concerned with failing tests in Circle CI yet as they are not what we are going off and are instead going off Jenkins still?

**Comment by cohnjesse** [comment]
@Clark-W-Griswold also that failing test is not related to my work here

**Pull request merged**
