### PR TITLE
10 13 16 bug fixes

### PR DESCRIPTION
**Pull request by akainic**
Addresses the following tickets:
- #3362  
- #3368 
- Some validation issues on the phone field
- Removing "Does not apply" as an option on "Were you involuntarily called for active duty"

### CODE REVIEW

**Comment by goldenmeanie** [comment]
Functionally, this looks good! 

Re: The phone number no longer breaks the form with dashes, but it doesn't clean up formatting yet. I assume that's why it says "**some** validation issues on the phone field"

**Comment by akainic** [comment]
@goldenmeanie yeah I only fixed the validation issues that were preventing the user from continuing onto the next page with dashes. I think we need to think more about how to clean up the formatting; that's a bigger change. Just wanted to get the most essential change in first :)

**Comment by goldenmeanie** [comment]
Well, if my LGTM is enough to merge, go for it!

**Comment by akainic** [comment]
@markolson is this good to merge or is anything else required due to the schema change in vets-json-schema? I wasn't sure if anything else was needed due to the submodule change.

**Pull request merged**
