### PR TITLE
[WIP] Million Veteran Program

### PR DESCRIPTION
**Pull request by dannychapman**
WIP Do not merge yet.

### CODE REVIEW

**Comment by dannychapman** [comment]
mvp-enroll
mvp-index
mvp-privacy

**Comment by dannychapman** [comment]
enroll
mvp

**Comment by rroueche** [comment]
@jkassemi this is a super old PR that has been stale and un-merged due to approval delays. It'll be getting reprioritized again, so I checked in on it and am noticing that there are lots of conflicts, many of which are code-related (not content) so I don't feel comfortable resolving. I could just rebase if you think that would be safe and easy, but wanted to check with you before taking any action.

**Comment by jcmeloni-usds** [comment]
@rroueche +1 to you for being on the same "review old PRs" schedule as I am :)

**Comment by dannychapman** [comment]
@rroueche Let me know if you need any help from me on this one.

**Comment by rroueche** [comment]
@dannychapman @jkassemi yeah I just don't feel comfortable resolving these conflicts myself since they're all react or js. if it were html/css/english i'd be good to go! but alas. advice on how to proceed?

**Comment by jkassemi** [comment]
Most of the issues are related to https://github.com/department-of-veterans-affairs/vets-website/pull/3496/commits/fe06b04c39e60222271a5195007e35c886b664a8, which may have resulted from files copied over from another copy of the repository. Permissions were changed there, and some of these have since files have since been removed in master, so git is unable to figure out what to do with them.

@rroueche - can you piece together what the expected scope of these changes are? I think we're going to want to apply these to a branch fresh off of master. If this is limited to content changes it'll be a little simpler.

**Comment by rroueche** [comment]
@bethpotts @amybehrens I'm going to redo these updates in a new branch and delete this one + the PR bc it's so old that the other commits that have gone live in the meantime are making it super complicated to debug. Should still have a link ready by end of today for ya though!

**Comment by ayaleloehr** [comment]
So can this be closed @rroueche ?

**Comment by rroueche** [comment]
@ayaleloehr oh shoot, my comments above were supposed to be for a different PR (#2991) not this one. I'm reluctant to make any moves on this PR, bc it's not a priority to get up on the site right now, but I also don't want to lose the work in case we do take it live in a few months. is it ok to keep in icebox? or is it negatively affecting other work?

**Comment by ayaleloehr** [comment]
@rroueche Not negatively affecting other work, but given how far behind `master` this PR is, it doesn't seem like this PR will ever be merged, but would be recreated instead. It seems to only be about 3 pages that were actually changed, so my suggestion would be to copy the edits from this PR into an issue and keep track of them there, rather than in this open PR.

**Comment by phiden** [comment]
Closing this PR because I've opened a new one! https://github.com/department-of-veterans-affairs/vets-website/pull/6605

**Pull request closed without merging**
