### PR TITLE
Add 20-10206 max test-data

### PR DESCRIPTION
**Pull request by tlei123**
## Summary

- Add maximal test-data file to facilitate back-end data-mapping
- Team: Veteran Facing Forms
- Flipper not implemented yet

## Context for backend data-mapping

PDF blocks to ignore:
- FOIA &mdash; we're only supporting the PA portion of the PDF
- Third-party preparer-type &mdash; we're only supporting first-party submissions

## Related issue(s)

- n/a

## Testing done

- n/a

## What areas of the site does it impact?

Nothing, just data to support local development.

### CODE REVIEW

**Review by ndsprinkle — DISMISSED** [review]

**Comment by ndsprinkle** [comment]
@Thrillberg From what I can tell from the [sketch](https://www.sketch.com/s/314e6dbf-5b4a-422d-beb1-0ad599fc3af1/p/D2736869-8F0B-4244-AB27-F7EBFDE853EB/canvas), there's only one mailing address right now regardless of flow. I think we're not supporting every possible type of situation for V1, but I don't know the details of that

**Comment by Thrillberg** [comment]
Thanks @ndsprinkle ! It might be easiest if I can view/navigate through the form in my browser. When I go to http://localhost:3001/records/request-personal-records-form-20-10206, I get an error page. Do you know the real local URL?

**Comment by jeana-adhoc** [comment]
Hi @Thrillberg - The URL has been updated. It's now http://localhost:3001/records/request-personal-records-form-20-10206 You can find the current url in the manifest.json file under `rootUrl` for any of the forms.

**Comment by Thrillberg** [comment]
Thanks @jeana-adhoc ! That's the same URL I've been trying while having this running in terminal:
```
yarn watch --env entry=10206-pa
```

And then I get this in the browser:
Screenshot 2023-12-08 at 10 33 41 AM

Is my `yarn watch` command by chance wrong?

**Comment by tlei123** [comment]
> Thanks @jeana-adhoc ! That's the same URL I've been trying while having this running in terminal:
> 
> ```
> yarn watch --env entry=10206-pa
> ```
> 
> And then I get this in the browser: Screenshot 2023-12-08 at 10 33 41 AM
> 
> Is my `yarn watch` command by chance wrong?

@Thrillberg , sorry for the confusion!  Yes, you have the correct final URL.  The error's due to the content-build side not getting this "new" rootUrl just yet.  You just need to refresh the route on the vet-website side with a build:

1. Stop the form-app if it's running
2. Pull main from content-build repo
3. Back in vets-website, run a build with `yarn build --pull-drupal` \[much quicker than building content-build\]
4. Start the form-app.
5. Reload the form-app in browser.

P.S. Sorry I forgot checking all the options in recordSelections.  Will ping you when the next push here's done.

**Comment by tlei123** [comment]
> Is there no second address for "SECTION II: REQUEST FOR INFORMATION ON A PERSON OTHER THAN YOURSELF"?

@Thrillberg , sorry for the confusion here!  We're actually gonna _block_ Continuing beyond preparer-type page IF prepareType is 'third-party'.  Just throw back a 500 \[or whatever response/error you think is appropriate\].

**Comment by tlei123** [comment]
Closing this unmerged.  Will add maximal data-file via another ticker/PR when appropriate.

**Pull request closed without merging**
