### PR TITLE
Migrate code from rx repo into unified frontend build.

### PR DESCRIPTION
**Pull request by awong-dev**
Code is now migrated and building.

There is still some archived files in `src/rx-migrate` left over but those should just be reviewed, any useful info extracted, and then the directory deleted.

### CODE REVIEW

**Comment by alexose** [comment]
Looks like there are a few linting errors causing issues:

`/home/travis/build/department-of-veterans-affairs/vets-website/src/js/rx/containers/Main.jsx
  16:13  error  Handler function for onCloseAlert prop key must begin with 'handle'  react/jsx-handler-names
/home/travis/build/department-of-veterans-affairs/vets-website/src/js/rx/containers/RxRefillsApp.jsx
  20:13  error  Handler function for onCloseModal prop key must begin with 'handle'  react/jsx-handler-names`

also missing a sass file here:

`ERROR in ./src/js/rx/rx-entry.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../../sass/rx.scss in /home/travis/build/department-of-veterans-affairs/vets-website/src/js/rx
 @ ./src/js/rx/rx-entry.jsx 28:0-29`

I'll clean these up.

**Comment by awong-dev** [comment]
Thanks dude. I'm in a meeting.  Feel free to merge if it looks good.

**Comment by alexose** [comment]
The build is passing now, but there are a few issues with the styles (can I request your help on this @webinista?) and with the router now that it's being served out of a subdirectory.

Other than that-- It's looking good.

Were we still planning on doing incremental builds for `healthcare-app` and `rx`?  It's not a problem yet, since the build is still pretty fast, but it's going to be important when we start running lots of tests.

**Comment by alexose** [comment]
Merging this up for now-- Fixes will come in future PRs

**Pull request merged**
