### PR TITLE
Add alt text to VAGOV logo in injected header to remove two accessibility errors

### PR DESCRIPTION
**Pull request by 1Copenut**
## Description
UPDATE: I have also removed the `title` attribute from the VAGOV image's parent `<a>` tag. Having the same text in a title and alt text can cause screen readers to read duplicate content. This makes our markup consistent with that of VA.gov's front page.

The header we're injecting onto sub-domains like https://benefits/va.gov/benefits/ was missing alt text on the VAGOV logo in the `<header>`. This was causing two aXe errors, one for the missing alt text, the other for a link with no discernible text. This PR fixes both of those by adding an alt declaration to match what we're doing on VA.gov.

## Testing done
* Ran `$ test:vrt` after creating feature branch, verified failing tests
* Updated the Jest image snapshots to match `master` branch
* Ran `$ test:vrt` after code was updated. All tests passed.
* Ran the standard e2e and unit tests
* Verified with aXe on `localhost` the error about missing alt text was suppressed. Checked this on the **http://localhost:3001/?target=https://www.va.gov/health/** and **http://localhost:3001/?target=https://benefits.va.gov/benefits/** URLs
* Spot checked **http://localhost:3001/?target=https://www.va.gov/health/** in MacOS + Safari + VoiceOver:
  * Confirmed the link text is not read twice (after removing the `title` attribute from `<a>` tag
  * Confirmed the link text appears in the Links menu

## Related issue
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17853

## Acceptance criteria
- [x] Alt text has been added
- [x] Error no longer appears

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by ncksllvn — APPROVED** [review]

**Comment by 1Copenut** [comment]
@ncksllvn Thank you for the quick review. I noticed there was a `title` attribute on the `<a>` tag that I've had cause issues with screen readers before. I am removing it now, and will re-push code in a few minutes after running tests locally to ensure no regression.

**Comment by ncksllvn** [comment]
Take your time @1Copenut, I can re-review if you'd like but these changes look and sound very safe to me.

**Review by jbalboni — APPROVED** [review]

**Review by ncksllvn — APPROVED** [review]
LGTM! Good catch on the title tag!

**Comment by 1Copenut** [comment]
And merged. Thanks all!

**Comment by rianfowler** [comment]
Once this is built you should be able to verify it with the staging scripts:
https://staging.va.gov/health/?targetEnvironment=vagovstaging
https://www.cem.va.gov/?targetEnvironment=vagovstaging

LMK if you run into issues with this.

**Comment by 1Copenut** [comment]
@rianfowler Thank you for this heads up. I'm checking in multiple browsers now.

**Comment by 1Copenut** [comment]
### TESTING DONE IN STAGING

**Tested the following domains for accuracy:**
* https://www.cem.va.gov/?targetEnvironment=vagovstaging
* https://staging.va.gov/health/?targetEnvironment=vagovstaging
* https://benefits.va.gov/benefits/?targetEnvironment=vagovstaging

**Tested domains in the following browsers at desktop and mobile size:**
* MacOS - Chrome
* MacOS - Safari
* MacOS - Firefox
* Win10 - IE11
* Win10 - Chrome
* Win10 - Firefox
* Win10 - Edge

**Tested readout with following screen reader and browser pairings:**
* MacOS - Safari - VoiceOver
* Win10 - IE11 - JAWS
* Win10 - Chrome - JAWS
* Win10 - Firefox - NVDA
* Win10 - Edge - Narrator

**Pull request merged**
