### PR TITLE
Migrate flex utility breakpoints to USWDS names

### PR DESCRIPTION
**Pull request by jamigibbs**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

This is migrating [flex utilities](https://design.va.gov/foundation/utilities/flexbox) breakpoint names to the USWDS equivalent.

| Current VADS Name | USWDS v3 Name |
| --------------------------- | ------------------------- |
| xsmall-screen (320px)          | mobile (320px) |
| small-screen (480px) | mobile-lg (480px) |
| small-desktop-screen (1008px) | desktop (1024px) 
| large-screen (1200px) | desktop-lg (1200px) |

## Related issue(s)

- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3208

## Testing done

Tested locally with the different breakpoint names on generic markup. Individual teams should please test their applications though too:

Screenshot 2024-09-26 at 1 42 51 PM

Screenshot 2024-09-26 at 1 42 35 PM
**check-in**

Screenshot 2024-09-26 at 2 02 54 PM

Screenshot 2024-09-26 at 2 03 04 PM

Screenshot 2024-09-26 at 2 22 54 PM

Screenshot 2024-09-26 at 2 23 02 PM

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by pjhill — APPROVED** [review]

**Review by pjhill — APPROVED** [review]
Agree, with the statement that additional testing should be done for each application, but the changes look good generally.

**Review by eselkin — APPROVED** [review]
LGTM

**Review by chriskim2311 — APPROVED** [review]
LGTM

**Comment by jamigibbs** [comment]
Hello @department-of-veterans-affairs/patient-check-in! 👋 If someone has some time this morning, can you verify that your app is working as expected with the flex breakpoints? I have checked it locally and added screenshots to the PR description.

**Review by lee-delarm6 — APPROVED** [review]
For the check-in portion, this looks good to go, double check with other teams (vaos etc.) for their portions 👍

**Review by simiadebowale — APPROVED** [review]

**Comment by jamigibbs** [comment]
MVH and other teams discussion here in [Slack](https://dsva.slack.com/archives/CBU0KDSB1/p1727372949849339)

**Pull request merged**
