### PR TITLE
31962 update the choose clinic page description

### PR DESCRIPTION
**Pull request by ptouchton**
## Description
This PR updates the page description on the covid-19 vaccine - choose a clinic page

## Original issue(s)
department-of-veterans-affairs/va.gov-team#31962

## Testing done

Manual and unit

## Screenshots
image

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by vbahinwillit — CHANGES_REQUESTED** [review]
One small comment. There is a change that's missing under the 'Page Content' section.

'Choose where you’d like to get your vaccine. (*Required)'

Also, I would add a screenshot as well.

**Comment by ptouchton** [comment]
@vbahinwillit - changes have been uploaded with screenshot. Sorry it took so long, I had to upgrade my Ubuntu VM to handle cypress tests

**Review by jenniemc — APPROVED** [review]
Looks good to me!

**Review by vbahinwillit — APPROVED** [review]
LGTM!

**Comment by vbahinwillit** [comment]
FYI, don't forget to merge latest changes from master into this branch before squash & merge.

**Pull request merged**
