### PR TITLE
[65692] removes inheritedProofingVerified mock data

### PR DESCRIPTION
**Pull request by bramleyjl**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)

## Summary

- removes inheritedProofingVerified mock data

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/65692
- https://github.com/department-of-veterans-affairs/vets-api/pull/17417

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Review by alex-morgun-1 — APPROVED** [review]

**Review by IGallupSoCo — APPROVED** [review]
LGTM

**Review by IGallupSoCo — APPROVED** [review]
LGTM

**Review by jsimonVA — APPROVED** [review]

**Review by asiisii — APPROVED** [review]
LGTM 🚀

**Review by Thrillberg — APPROVED** [review]

**Review by mmoyer-va — APPROVED** [review]

**Review by aurora-a-k-a-lightning — APPROVED** [review]

**Review by acrollet — APPROVED** [review]
Approved for 2346 + health care supply reordering

**Review by bradbergeron-us — APPROVED** [review]

**Pull request merged**
