### PR TITLE
Remove vetsgov in forms

### PR DESCRIPTION
**Pull request by cehsu**
## Description
These changes replace vetsgov instances in several form apps and shared forms components.

## Testing done
verified locally

## Screenshots
image
image
image
image

## Acceptance criteria
- [x] Help desk messages
- [x] Go back buttons
- [x] Save in progress errors

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by rianfowler — APPROVED** [review]

**Review by peggygannon — CHANGES_REQUESTED** [review]
@cehsu Hi, Claire.  It looks like we have two old error messages. Can we update the two messages to the following?

**We're sorry. We can't submit your form right now.** 

We're working to fix the problem. Please make sure you're connected to the Internet, and then try saving your form again. [Save your form].

If you don't have an account, you'll have to start over. Please try submitting your form again tomorrow. 

If it still doesn't work, please call the VA.gov Help Desk at  at 1-855-574-7286 (TTY: 1-800-877-8339). We’re here Monday-Friday, 8:00 a.m. – 8:00 p.m. (ET).


We're sorry. We're unable to connect to VA.gov right now. Please make sure you're connected to the Internet so we can save your form in progress.

**Comment by cehsu** [comment]
Thanks @peggygannon kindly refer to the updated screenshots below:
image
image

**Review by peggygannon — CHANGES_REQUESTED** [review]
@cehsu Thanks for the updated screenshots.

--For the first message, we still need to change vets.gov to VA.gov >>If it still doesn't work, please call the VA.gov Help Desk at .....
--Can you also add spaces around the dashes to this sentence: We’re here Monday - Friday, 8:00 a.m. – 8:00 p.m. (ET).

**Comment by cehsu** [comment]
Thanks @peggygannon, updated:
image

**Review by peggygannon — APPROVED** [review]

**Comment by peggygannon** [comment]
thanks, @cehsu LGTM.

**Review by erikphansen — APPROVED** [review]

**Pull request merged**
