### PR TITLE
Moving placement of breadcrumbs in templates. closes #2366

### LINKED ISSUE #2321: Change some call-out boxes from HTML to Markdown definition list syntax
Related to #2089 and #2099. 

Many of the call-out boxes in `4-action-page` templates might be better expressed as definition lists. At the very least, it reduces the amount of HTML in our Markdown which would make writing and editing easier.

This task is/would only be for _some_ call-out boxes, such as the one on the [Project 112/SHAD](https://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/project112-SHAD/) page. The decision tree for whether or not a callout box should be migrated to the definition list syntax is: "Does this look like an FAQ?" If yes, change it.

- [Markdown/Kramdown definition list syntax](http://kramdown.gettalong.org/syntax.html#definition-lists)

### LINKED ISSUE #2366: Pull out breadcrumbs and heading from header to main content
Currently:
image

Pull out Education heading to the main content and add the breadcrumb above it for L2 and beyond. This will help to navigate users, remove the yellow that will be specific to the crisis line, for the heading to be clearer against the white background, and for the header to be smaller. The current section should be bolded with no underline in the breadcrumbs. 

image

### PR DESCRIPTION
**Pull request by webinista**
- Ensuring that all Markdown pages have template values.
- Removing markup for most call out boxes in favor of Markdown. (closes #2321)
- Moving questions for registry-health-exam, test-storage to include.
- Changing agent-orange/diseases.md feature list to Markdown
  - Adds va-list--feature pattern
- Adding breadcrumbs to 4-action-page\* templates.
- Restyling .breadcrumbs, .section.one, h1 to accommodate changes.
- Removing breadcrumbs include from page-breadcrumbs.html
- Adding breadcrumbs tag to template-level pages 1-topic-landing.html, L2-section-landing.html, 2-detailed-landing.html,6-info-page.html
- Adding Home link to breadcrumbs include.
- Updating template property for some pages.
- Adding 3-panel-filters template.
- Removed hidden heading from header file.

### CODE REVIEW

**Comment by emilyville** [comment]
Let's bump it in slightly so it lines up with the text below. I think it's the same for mobile as desktop, but it's more noticeable on mobile.

screen shot 2016-05-27 at 1 41 59 pm

**Comment by emilyville** [comment]
It looks like we lost our blue larger leading copy. See here at /employment

screen shot 2016-05-27 at 1 57 27 pm
screen shot 2016-05-27 at 1 57 22 pm

**Comment by emilyville** [comment]
Will need to look at the playbook as it's special self (not sure yet the best way to approach this) Looks a little bit sad as is

screen shot 2016-05-27 at 2 13 28 pm
screen shot 2016-05-27 at 2 13 45 pm

**Comment by emilyville** [comment]
Updating: we should be able to time this with @ayaleloehr to get out tonight or tomorrow.

**Comment by webinista** [comment]
@ayaleloehr Can you update us on the status of this? Is this more that you need to do before we review and merge this PR?

**Comment by ayaleloehr** [comment]
@webinista sorry for the delay.  The plan was for @emilyville to get everything set up in both this repo and the [va_common](https://github.com/department-of-veterans-affairs/va_common) gem, which I believe does the breadcrumbs for GI Bill Comparison Tool and VEC.  She was then going to update the gem version in both GIBCT and VEC to make sure the changes applied properly in each repo and then I was going to deploy.  

Last I heard before Emily went out was on 6/2 saying "I'm going to try to get it out today, but as a backup I also set up time to teach tiffany how to update the gem on Monday. So if we don't get to it this week, there is a backup plan."  By your question here, I'm assuming this didn't happen?

**Comment by webinista** [comment]
@ayaleloehr No, that did not happen :-). Thanks for the update! I guess I can try to figure it out this week so that those tasks no longer hold us up.

**Comment by ayaleloehr** [comment]
@webinista looking quickly at VEC, it actually looks like breadcrumbs aren't defined in va_common but in VEC itself, such as places like [this](https://github.com/department-of-veterans-affairs/veterans-employment-center/blob/c804ce36e03ae6691cf8392019f2b9ce8708efda/app/views/veterans/new.html.erb#L9).  Looks like there are 13 of these. There is also one scss file in [VEC](https://github.com/department-of-veterans-affairs/veterans-employment-center/blob/572367328e75b87bec4c8c17a55ff9071a708bc6/app/assets/stylesheets/_vec.scss#L8) and a couple in [va_common](https://github.com/department-of-veterans-affairs/va_common/search?utf8=%E2%9C%93&q=breadcrumbs) that are probably where the real changes for this will go.  Keep me updated on how it goes and where I can help?!

**Comment by crwallace** [comment]
@webinista IS everything ready to go here? Looks like we were waiting to update the va_common gem before deploying this. Are we all set there?

**Comment by webinista** [comment]
@crwallace Sort of. I'm testing the gem now with the GIBCT and running into some issues. 

The only reason _not_ to merge and deploy this PR is so that we don't have multiple versions of headers floating around; it's strictly a UX issue.

**Comment by webinista** [comment]
So the thing I'm learning is that integrating `va_common` into GIBCT is a problem and a half. I haven't even made it to VEC. Both will likely require significant changes (which, btw, haven't been fully discussed or designed). 

We may want to ask product whether an inconsistent UX is acceptable in the short term while the details of an "application template" (or set of components) are hashed out.

**Comment by crwallace** [comment]
@staceylanger Can you weigh in on this situation? I think this is something that we will try to implement late this week or next week, but I would like to get this conversation started.

**Comment by ayaleloehr** [comment]
@crwallace you good to resolve these conflicts on Wednesday so we can deploy Thursday?

**Pull request merged**
