### PR TITLE
[All Claims] 781/781a Incident Unit Assignment

### PR DESCRIPTION
**Pull request by devin-mccurdy**
## Description
This PR covers PTSD incident unit assignment pages for the 781 and 781a flow

## Testing done
- [x] local testing
- [x] unit tests

## Screenshots
image

## Acceptance criteria
- [x] The content on this screen in the UI matches the content document (linked above)
- [x] This page is accessible within the 526 All Claims flow
- [x] Field validations (if applicable per the linked document for Validations above) are enforced in the UI
- [x] Error messages (if applicable per the linked document for Validations above) are displayed in the UI

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by aaronjlech — CHANGES_REQUESTED** [review]
Just a few syntax things, and some updated things with ptsdTitle!

**Review by aaronjlech — APPROVED** [review]
LGTM!

**Comment by dmccurdybah** [comment]
@department-of-veterans-affairs/code-reviewers-for-external-teams-group - Could I get a code review on this at your earliest convenience? Thanks!

**Review by rianfowler — APPROVED** [review]
LGTM

**Review by markgreenburg — APPROVED** [review]
LGTM

**Pull request merged**
