### PR TITLE
Claims: Update copy for "other claims" text

### PR DESCRIPTION
**Pull request by earthboundkid**
Fixes https://github.com/department-of-veterans-affairs/sunsets-team/issues/297

### CODE REVIEW

**Comment by carlmjohnson** [comment]
The change is pretty simple, but maybe it should be behind a feature flag until we roll out all claims? The feature flag is still pending though, right?

**Comment by carlmjohnson** [comment]
screen shot 2017-01-11 at 6 03 33 pm

**Comment by carlmjohnson** [comment]
screen shot 2017-01-12 at 2 23 44 pm

**Review by austin-martinez — APPROVED** [review]
LGTM :neckbeard:

**Pull request merged**
