### PR TITLE
VACMS-19347: Add need help component to DUW v2 homepage

### PR DESCRIPTION
**Pull request by chriskim2311**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary
This PR adds the need help component to the DUW homepage

## Related issue(s)
[#19347](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19347)

## Testing done
Tested component locally

## Screenshots
Homepage
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs

Results
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs

## What areas of the site does it impact?

DUW v2

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by randimays** [comment]
@chriskim2311 Based on the ACs, I think we're missing adding this to the results screen also:

Screenshot 2024-11-21 at 12 46 25 PM

**Review by randimays — COMMENTED** [review]
Spacing on this is pretty tight on the intro screen. We should add a bit more here. Desktop and mobile screenshots below. @thejordanwood thoughts?

Screenshot 2024-11-26 at 9 52 18 AM
Screenshot 2024-11-26 at 9 52 08 AM

On the results page, we have some spacing but we should make sure it is consistent with the spacing on the intro page.

Screenshot 2024-11-26 at 9 54 30 AM
Screenshot 2024-11-26 at 9 54 21 AM

**Comment by chriskim2311** [comment]
@davidmpickett Hi! This is the PR with a comment about spacing if you can let me know what you would prefer that would be great!

**Comment by davidmpickett** [comment]
Based on a quick review, it looks like the Need Help component typically has a total 64 px of head room. Seems like this is usually encased in an div that's an entirely separate row from the content above it. 

 48 seems to come from the bottom padding/margins of row above. 16 seems to be internal to the row that encases the Needs Help component.
 
Prod examples:
- https://www.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/introduction
- https://www.va.gov/supporting-forms-for-claims/third-party-authorization-form-21-0845/introduction

**Comment by jilladams** [comment]
Dunno why but that first link 404s for me and I can only reach it if I approach via search > results link, top recommendation here: https://www.va.gov/search/?query=processing%20form%2020-10207&t=false

**Comment by chriskim2311** [comment]
Updated with screenshots. @randimays @davidmpickett ready for a re-review thanks!

**Comment by randimays** [comment]
@jilladams The first link 404s because that particular app doesn't have an entry in [this file](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/blob/main/template-rendering/revproxy-vagov/vars/react_routes.yml) to allow client-side redirects. In this case, it would redirect from `/introduction` in that app to `/`, which it is not doing.

@chriskim2311 I kicked off a rerun of the failed jobs and poked the review instance. I'll check back in a little bit to review.

**Review by randimays — APPROVED** [review]
LGTM

**Review by davidmpickett — APPROVED** [review]
Padding is as requested. Approved!

**Comment by laflannery** [comment]
Approved!

**Pull request merged**
