### PR TITLE
[97411]: Display preferred name in authenticated menu when available

### PR DESCRIPTION
**Pull request by dcloud**
Did you change site-wide styles, platform utilities or other infrastructure?
- [ ] No
- [x] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

- Now that preferred name is being parsed from MPI, use preferred name in site-wide nav when available

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97411
- https://jira.devops.va.gov/browse/VI-771, 
per https://github.com/department-of-veterans-affairs/vets-api/pull/19488

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |  Screen Shot 2024-11-25 at 14 23 59   |  Screen Shot 2024-11-25 at 14 22 05   |
| Desktop |  Screen Shot 2024-11-25 at 14 23 55 |  Screen Shot 2024-11-25 at 14 22 10  |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by nichia — DISMISSED** [review]
The changes to use Preferred Name (if available) looks good.
Questions: Is there a need to put this change behind feature flag (eg. mhvLandingPagePersonalization or another flag)?

**Comment by dcloud** [comment]
```
  1) Medical Records Understanding Your Results Pathology Detail Page
       Understanding Your Results Pathology Detail Page:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-testid="record-list-item"]`, but never found it.
```

This is not related to preferred name

**Comment by dcloud** [comment]
Last run was CI errors, e.g `cp: cannot stat 'qa-standards-dashboard-data/src/allow-list/data': No such file or directory` 😢

**Review by IGallupSoCo — APPROVED** [review]
LGTM

**Review by alex-morgun-1 — APPROVED** [review]

**Review by nichia — APPROVED** [review]
LGTM

**Comment by dcloud** [comment]
FWIW, the injected header scenario doesn't apply to auth version of header, but after some finagling, checked it anyway

**Comment by dcloud** [comment]
Will merge on Monday before noon, to [deploy on Monday](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployments)

**Review by radavis — APPROVED** [review]
It's exciting to see this work nearing the finish line!

**Pull request merged**
