### PR TITLE
Rename _education/survivors-dependent-assistance.md to _education/GI-…

### PR DESCRIPTION
**Pull request by rcarthur**
…BIll/ survivors-dependent-assistance.md

### CODE REVIEW

**Comment by ss0ss** [comment]
@rcarthur - Do you still need this. The checks have failed. @dannychapman What do you think?

**Comment by dannychapman** [comment]
@ss0ss Pretty sure this should just be closed out. The IA has changed here I think. @rcarthur Please submit this again if needed as a fresh pull request.

**Comment by rcarthur** [comment]
Yes, this has been resolved.  IA changed since then.

**Comment by dannychapman** [comment]
@rcarthur Thanks! Closing.

**Pull request closed without merging**
