### PR TITLE
School selection review fix

### LINKED ISSUE #4154: Validation on School Selection broken on review page
For some reason the validation on the review page for the school selection chapter is broken (but not on the original page itself). When adding a school, it does not let me update the chapter, even though all of the required fields are complete.

### PR DESCRIPTION
**Pull request by lihanli**
closes #4154

### CODE REVIEW

**Comment by jbalboni** [comment]
@lihanli I don't see how this would fix #4154, though it does fix a bug with what the review page displays.

**Comment by lihanli** [comment]
if you try to add a school in the review page it won't let you update because this section won't render

**Comment by jbalboni** [comment]
Oh, I see. Looks good to me, then.

**Review by jbalboni — APPROVED** [review]
LGTM

**Pull request merged**
