### PR TITLE
MHV-50539-Update-Refill-Content

### PR DESCRIPTION
**Pull request by agravell047**
## Summary

Updated refill page content based on feedback from UCD.

## Related issue(s)

https://jira.devops.va.gov/browse/MHV-55039
>For the If your prescription isn’t ready to refill section:
>- If there are ever meds with 0 prescriptions in this part of the list (see screenshot), don’t show the “Showing 0 prescriptions” element or the line underneath it.
>- Remove the colon from the 'Last filled on' field - For example, “Last filled on January 1, 2024"
>- Can you confirm that we are paginating this list when we reach 20 meds?

>For the Ready to refill section:
>- Change the text styling of the med names to be H4s (Bitter/bold/17px)
>- Can you reduce the margins between the name of the med, and the prescription number? This looks to be about 16-ish px. (The margin under the med name overlaps with the fields below it, and idk what to do with that. But as long as there is less space, I’m happy.)
>- Remove the colon from the 'Last filled on' field - For example, “Last filled on January 1, 2024"

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

Screenshot 2024-02-28 at 2 21 07 PM

## What areas of the site does it impact?

MHV Medications refill page

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by vmenshutin-bylight — DISMISSED** [review]

**Review by dcloud — DISMISSED** [review]
The changes specific to this PR look good. 

Not part of this PR, but the labels don't seem to render with the expected `for=` attributes. 


I'm late to the party here, but wondering if the accessibility of a heading within a label was considered? At a first look, I wonder if a `vads-u-font-size--h4` would have been preferable

**Comment by agravell047** [comment]
> The changes specific to this PR look good.
> 
> Not part of this PR, but the labels don't seem to render with the expected `for=` attributes.
> 
> I'm late to the party here, but wondering if the accessibility of a heading within a label was considered? At a first look, I wonder if a `vads-u-font-size--h4` would have been preferable

@dcloud The `for=` attributes not rendering is actually just because prescrption.id was undefined, I meant to use prescription.prescriptionId. Good catch. 

For the H4, that what asked for by UCD and included in the mocks but I can check with accessibility to make sure.

**Review by dcloud — DISMISSED** [review]
Fixes for label-input association look good too.

Interested in clarification on [a11y of headings inside labels](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#headings), but that shouldn't hold this PR back!

**Comment by agravell047** [comment]
> > The changes specific to this PR look good.
> > Not part of this PR, but the labels don't seem to render with the expected `for=` attributes.
> > I'm late to the party here, but wondering if the accessibility of a heading within a label was considered? At a first look, I wonder if a `vads-u-font-size--h4` would have been preferable
> 
> @dcloud The `for=` attributes not rendering is actually just because prescription.id was undefined, I meant to use prescription.prescriptionId. Good catch.
> 
> For the H4, that what asked for by UCD and included in the mocks but I can check with accessibility to make sure.

Updated H4 as well based on feedback from accessibility.

**Review by vmenshutin-bylight — APPROVED** [review]

**Review by Andrew565 — APPROVED** [review]

**Pull request merged**
