### PR TITLE
Housing content design updates (proposed)

### PR DESCRIPTION
**Pull request by melwoodard**
Related: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2789

This PR proposes some small design changes for the WIP Housing content. Changes include:

~~[Eligibility](https://vetsgov-pr-5574.herokuapp.com/housing-assistance/home-loans/eligibility/), [Purchase Loan](https://vetsgov-pr-5574.herokuapp.com/housing-assistance/home-loans/va-backed-loans/purchase-loan/), [NADL](https://vetsgov-pr-5574.herokuapp.com/housing-assistance/home-loans/va-backed-loans/nadl/), [Cash-Out Refinance Loan](https://vetsgov-pr-5574.herokuapp.com/housing-assistance/home-loans/va-backed-loans/cash-out-refinance/),~~ (EDIT: reverted these back to text links) [Apply for COE](https://vetsgov-pr-5574.herokuapp.com/housing-assistance/home-loans/apply-for-certificate-of-eligibility/)

- changed "Apply" link to the standard green button

[Apply for COE](https://vetsgov-pr-5574.herokuapp.com/housing-assistance/home-loans/apply-for-certificate-of-eligibility/), [Cash-Out Refinance Loan](https://vetsgov-pr-5574.herokuapp.com/housing-assistance/home-loans/va-backed-loans/cash-out-refinance/), [Purchase Loan](https://vetsgov-pr-5574.herokuapp.com/housing-assistance/home-loans/va-backed-loans/purchase-loan/)

- Gave subway map steps H4 headings

[Apply for COE](https://vetsgov-pr-5574.herokuapp.com/housing-assistance/home-loans/apply-for-certificate-of-eligibility/)

- Converted table to plain text for mobile-friendliness

### CODE REVIEW

**Comment by DanielleSoCompany** [comment]
Hi @melwoodard. These updates look good to me with just one question: Should all apply links (including those that go to the Application Process page, and not the actual application) be green buttons? Or _just_ those that go to actual application? Just wondering if the former (like the button now on Eligibility) could feel confusing for some users. Thoughts?

**Comment by melwoodard** [comment]
@DanielleSoCompany that's a good point - I was thinking we did this already in the live sections, but I see now that all of those green buttons do point to the actual application, and never to the process page. I'm good with switching the buttons linked to the process page back to just text links.

**Comment by DanielleSoCompany** [comment]
Ok, great. Thanks, @melwoodard! Just to confirm: are you making that change or would you like me to?

**Comment by melwoodard** [comment]
@DanielleSoCompany I just made the updates, they should be up on  PR shortly.

**Comment by DanielleSoCompany** [comment]
@melwoodard awesome - thanks!

**Pull request merged**
