### PR TITLE
Content/wip/site inconsistency fixes

### PR DESCRIPTION
**Pull request by peggygannon**
Fixes content inconsistencies across site, including:
DOD to DoD
P.O. Box to PO Box
Regional Benefits Office to regional benefit office
"more than 1" to "more than one"
removed accent marks from resume. 
Update a few VR&E links so they no longer link offsite

### CODE REVIEW

**Comment by peggygannon** [comment]
@bethpotts for your review, this PR fixes content inconsistencies across the site (as listed above).

**Review by bethpotts — APPROVED** [review]

**Comment by peggygannon** [comment]
@bethpotts @robertfairhead Hello! I'm checking back to see if this PR is ready to be merged?

**Comment by bethpotts** [comment]
@robertfairhead Is jenkins hanging?

**Comment by robertfairhead** [comment]
@bethpotts all good now!

**Comment by peggygannon** [comment]
@phiden This PR is ready for your review and then merge!

**Review by phiden — APPROVED** [review]

**Pull request merged**
