### PR TITLE
Use VA cards on single page arrays

### PR DESCRIPTION
**Pull request by ToddWebDev**
## Summary
Follow VA Form system guidelines and 'useVaCards' on single page array items on the Pension Benefits form (21P-527EZ)

### Description
This update aligns with our effort to keep our application maintainable and up-to-date with the latest VA Forms Library and VADS standards.

### Reference
[#vfs-frontend](https://dsva.slack.com/archives/C5HP4GN3F/p1711033133945109)

### Form tester utility support
This PR also adds a Cypress form tester utility helper function to help automate e2e testing with single page arrays that use 'useVaCards'

## Issue
[Issue in Github](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78971)

## How to run in local environment
1. Check out this branch locally
2. In your local environment, set the `pension_form_enabled` flipper to 'enabled' at http://localhost:3000/flipper/features/pension_form_enabled
3. Run `vets-website` and `vets-api`

## How to verify
1. Go to `http://localhost:3001/pension/application/527EZ` in your browser
2. Go to the 'Marital status' page in the 'Household information' chapter
3. Select 'Married'
4. Enter at least 2 marriages
5. Verify that a previous marriage is title'd correctly and components are updated
6. Verify that the previous marriage is validated
7. Verify that current marriage is title'd correctly and components are updated
8. Verify that the current marriage is validated
9. Verify that the data is saved to the api and redux
10. Continue to the 'Review application' page
11. Verify that the data is viewable and editable
12. Verify that the application is able to be submitted

## Acceptance criteria
n/a

## Testing done
- [x] Existing unit tests passing

### Single Page Array
| Before | After |
| ------ | ------ |
|localhost_3001_pension_application_527EZ_form-saved (old)|localhost_3001_pension_application_527EZ_form-saved (new)

### Review application
| Before | After |
| ------ | ------ |
|localhost_3001_pension_application_527EZ_introduction|localhost_3001_pension_application_527EZ_form-saved (23)

## What areas of the site does it impact?
Pension Benefits Application

### Quality Assurance & Testing
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling
- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication
- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Review by TaiWilkin — APPROVED** [review]
Looks good!

**Review by TaiWilkin — DISMISSED** [review]

**Review by rhasselle-oddball — DISMISSED** [review]

**Review by rmessina1010 — DISMISSED** [review]
LGTM

**Comment by ToddWebDev** [comment]
Re-requesting reviews due to merge conflict resolution dismissing reviews

**Review by TaiWilkin — DISMISSED** [review]

**Review by TaiWilkin — APPROVED** [review]

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Pull request merged**
