### PR TITLE
CT: Write "keyboard.e2e.spec.js" using Cypress #13371

### PR DESCRIPTION
**Pull request by zurbergram**
## Description
https://github.com/department-of-veterans-affairs/va.gov-team/issues/13371

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by zurbergram** [comment]
@department-of-veterans-affairs/frontend-review-group @department-of-veterans-affairs/bah-code-reviewers You can ignore this PR at the moment, testing if test will pass in jenkins build

**Comment by rianfowler** [comment]
Are you looking from feedback from VSP on this?

**Comment by zurbergram** [comment]
@rianfowler I accidentally made it a PR instead of draft, was able to switch it back,  when i'm done it will need frontend approval for the removal of nightwatch commands that are only used in GI

**Review by devin-mccurdy — APPROVED** [review]
LGTM

**Comment by zurbergram** [comment]
@department-of-veterans-affairs/frontend-review-group this is ready for a review

**Review by sonntag-adam — APPROVED** [review]

**Pull request merged**
