### PR TITLE
VACMS-19786: DUW v2 Medical Records

### PR DESCRIPTION
**Pull request by chriskim2311**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary
Updating the Medical records information on the DUW v2 results screen

## Related issue(s)
[#19786](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19786)

## Testing done
Tested in RI for the updated text to appear dynamically.
Screenshots below for all ACs

## Screenshots
<details>
<summary>Reason PTSD and discharge 1992 to present</summary>
#### Review

How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs

#### Medical Records
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs

</details>

<details>
<summary>Reason PTSD and discharge before 1992 </summary>
#### Review
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs
#### Medical Records
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs
</details>

<details>
<summary>Reason TBI and discharge after 1992 </summary>
#### Review
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs
#### Medical Records
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs
</details>

<details>
<summary>Reason TBI and discharge before 1992 </summary>
#### Review
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs
#### Medical Records
Cursor_and_How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs

</details>

<details>

<summary>Reason Sexual Assault and discharge after 1992 </summary>
#### Review
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs
#### Medical Records
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs

</details>

<details>
<summary>Reason Sexual Assault and discharge before 1992 </summary>
#### Review
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs
#### Medical Records
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs
</details>

## What areas of the site does it impact?
DUW v2

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### CODE REVIEW

**Review by randimays — COMMENTED** [review]
I have some observations about ACs vs. review instance differences.

I don't know where the Sharepoint doc lives, but I'm curious about the formatting. These observations generally apply to other parts of the ACs / flows as well.

- Should the `You'll need to submit copies of your medical records.` be bulleted as in the ACs?
- Should the links be bulleted? I know they are in the ACs like this but they look odd; we usually don't bullet them in other sections.
- In the ACs, the links are in the opposite order from the review instance.

ACs:

Screenshot 2024-11-20 at 6 07 31 AM

Review instance:

Screenshot 2024-11-20 at 6 07 57 AM

**Comment by laflannery** [comment]
@chriskim2311 (and @FranECross) I found a typo - this was probably in the text handed to you but I'm pretty sure it's wrong:

> ...fill out and submit a Request for and Authorization...

"and" should be "an"

Otherwise everything looked good!

**Comment by randimays** [comment]
@laflannery The wording is weird but it does match [the form page](https://www.va.gov/find-forms/about-form-10-5345/) that corresponds to.

Screenshot 2024-11-20 at 11 58 08 AM

**Comment by laflannery** [comment]
I understand now in that context, thanks @randimays!

**Review by laflannery — DISMISSED** [review]

**Comment by chriskim2311** [comment]
@randimays @FranECross This is from the CAIA doc. DischargeUpgradeWizardContent_docx_-_Google_Docs

Fran can you verify if we want to bullet the link or not? I see some discrepancies in the ACs and the doc is pretty confusing on this.

**Comment by FranECross** [comment]
@chriskim2311 Thanks for checking! I see that I had conflicting info in the description of the main ticket, and have corrected it. The form shouldn't have a bullet and should be part of (or just underneath) the "Get VA form...." sentence.

**Review by randimays — APPROVED** [review]
LGTM!

**Review by rsmithadhoc — APPROVED** [review]

**Pull request merged**
