### PR TITLE
Content/WIP/Move health care edits to new branch that lives in va-gov directory

### PR DESCRIPTION
**Pull request by bethpotts**
## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by bethpotts** [comment]
@ncksllvn I need your help resolving these conflicts before we merge this one.

**Comment by ncksllvn** [comment]
Hey @bethpotts, I resolved the conflicts by taking your changes here, but can you double check that these look okay? 

- va-gov/pages/health-care/about-va-health-benefits.md
- va-gov/pages/health-care/after-you-apply.md

**Comment by bethpotts** [comment]
@ncksllvn On this page: va-gov/pages/health-care/about-va-health-benefits.md

These two links don't work:

screen shot 2018-10-17 at 9 31 38 am

AND

screen shot 2018-10-17 at 9 33 28 am

**Comment by ncksllvn** [comment]
@bethpotts I believe those pages are routed through our proxy so that we can enable our VA.gov header/footer/navigation on those pages. That isn't wired up on our review instances though, so we'll have to double check it in dev/staging/preview.

**Comment by bethpotts** [comment]
@ncksllvn So we should go ahead and push this to preview and see if they work there? Is that what you're saying? If so, please merge.

**Comment by ncksllvn** [comment]
@bethpotts exactly! Merging in 3..2...1...

**Review by ncksllvn — APPROVED** [review]

**Pull request merged**
