### PR TITLE
2344 total rated disabilities

### PR DESCRIPTION
**Pull request by cohnjesse**
## Description
Original ticket - [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2344)

This ticket is create the front end component that will display a veteran's total rated disability in a meaningful way. This is only for the front end components, the back end is still being built, although I have included the redux code that will be used to eventually connect the front end to the back end. GA events have not been provided yet by the Analytics team but will be added in a separate branch.

## Testing done
Unit tests are included in this PR. End to end tests will be completed once the back end API endpoint is set up in a separate branch.

## Screenshots
Screen Shot 2019-10-21 at 10 09 58 AM

## Acceptance criteria
- [x] Have a component that displays error states
- [x] Have a component that displays the percentage

## Definition of done
- [ ] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by rianfowler** [comment]
Please tag the @department-of-veterans-affairs/frontend-review-group in a comment when this has a peer review approval. We [recommend](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/code_review_guidelines.md) using [draft PR requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/) to do peer reviews.

**Comment by cohnjesse** [comment]
@department-of-veterans-affairs/frontend-review-group this should be ready for review. Peer review was completed in a draft PR.

**Comment by rianfowler** [comment]
please tag the @department-of-veterans-affairs/frontend-review-group when this is has a peer review approval. 

We recommend using [draft PRs](https://github.blog/2019-02-14-introducing-draft-pull-requests/) for peer reviews and only promoting these into full PRs when they've received a peer approval: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/code_review_guidelines.md

**Comment by cohnjesse** [comment]
These changes have been moved to another branch and a draft PR has been opened there

**Pull request closed without merging**
