### PR TITLE
Add note about discharge upgrade into profile

### PR DESCRIPTION
**Pull request by ncksllvn**
image

### CODE REVIEW

**Comment by DanielleSoCompany** [comment]
Hi Nick. Placement looks perfect. I did notice that the old "burials and memorials" copy looks like it's in there. Could you update to read as follows:

**Note:** If you have a less than honorable discharge, you can apply for an upgrade. If your application goes through and your discharge is upgraded, you'll be eligible for the VA benefits you earned during your period of service. [Find out how to apply for a discharge upgrade].

**Comment by ncksllvn** [comment]
@DanielleSoCompany sorry about that! Fixed now

image

**Comment by DanielleSoCompany** [comment]
@ncksllvn No worries and thanks! @bethpotts want to take a quick look?

**Comment by bethpotts** [comment]
@ncksllvn Text looks good. Since you're the only one who can click on that link, can I ask you to do that to make sure it's working? Other than that, it's good to go!

**Review by bethpotts — APPROVED** [review]

**Review by DanielleSoCompany — APPROVED** [review]

**Comment by ncksllvn** [comment]
@bethpotts will do once Jenkins finishes!

**Comment by ncksllvn** [comment]
@bethpotts link works great!

image

**Comment by DanielleSoCompany** [comment]
@bshyong This is the other PR connected to the discharge links.

**Comment by bshyong** [comment]
@ncksllvn can you merge master/retrigger the Jenkins build for this PR? I will merge as soon as tests pass

**Comment by ncksllvn** [comment]
@bshyong Definitely, thanks for your help. Merged!

**Pull request merged**
