### PR TITLE
Create GitHub comment with broken links on Content PRs

### PR DESCRIPTION
**Pull request by robertfairhead**
Closes: department-of-veterans-affairs/vets.gov-team#6203

### CODE REVIEW

**Comment by robertfairhead** [comment]
Example output in comment above

**Review by wyattwalter — APPROVED** [review]
LGTM.

I think you can probably get the branch's PRs by using `pr.queryPullRequests`. May or may not be cleaner, I haven't traced through the whole thing.

I don't see any function calls that aren't already approved in Jenkins. If you hit any, let us know in #platform-team.

**Comment by robertfairhead** [comment]
I looked at `queryPullRequests` but dismissed it for some reason. Obviously, it'll work.

picard-facepalm

I transitioned over to it and reran the test (after approving all the methods in Jenkins). Once the build passes, I'll merge it in.

Thanks wyatt for approving the devops PR to persist those approvals!

**Comment by wyattwalter** [comment]
Woot!

**Pull request merged**
