### PR TITLE
adds tou content updates

### PR DESCRIPTION
**Pull request by asg5704**
## Summary
This PR encapsulates the body of work from a content request change for Terms of Use. Reference [Slack thread](https://dsva.slack.com/archives/C053QAL4ZNZ/p1719346798382389)

## Related issue(s)

- department-of-veterans-affairs/va.gov-team#86951

## Testing done
Manual

## Screenshots
Screenshot 2024-06-25 at 5 38 20 PM
Screenshot 2024-06-25 at 5 40 16 PM
Screenshot 2024-06-25 at 5 38 16 PM

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by CaitHawk — DISMISSED** [review]

**Review by jhouston0 — DISMISSED** [review]

**Comment by DanielleThierryUSDSVA** [comment]
Note that there's a missing space between 2 words in this screen (highlighted in yellow here).

image

I also noticed that the mobile app name should be:

VA: Health and Benefits mobile app

Instead of:

VA Health and Benefits Mobile App

in this screen:
image

**Comment by DanielleThierryUSDSVA** [comment]
One additional request:

Spoke with Tom and we agree that we should move the **If you have a My HealtheVet user ID and password** section into the **What will happen if you decline** alert. That content only applies if you decline the terms, so while it will make that alert even larger, we'd like to keep all that content together. Thank you!

image

**Comment by asg5704** [comment]
@DanielleThierryUSDSVA 

- [x] I caught the spacing issue as it must have been an old screenshot
- [x] Changed `Mobile App` => `mobile app`
- [x] Moved the MHV h3 + content inside the va-alert

Screenshot 2024-06-26 at 9 59 10 AM
Screenshot 2024-06-26 at 9 53 27 AM

**Comment by DanielleThierryUSDSVA** [comment]
Thank you so much for doing this so quickly, @asg5704! 2 final things:

- Just need to add the : in "VA: Health and Benefits mobile app"
- I can't tell from the screenshot, but just make sure that the "If you have a My HealtheVet user ID and password" heading is the next heading level down in logical order from the "What will happen if you decline" heading.

Really appreciate your work on getting this out so quickly. Thanks again!

**Comment by asg5704** [comment]
> Thank you so much for doing this so quickly, @asg5704! 2 final things:
> 
> * Just need to add the : in "VA: Health and Benefits mobile app"
> * I can't tell from the screenshot, but just make sure that the "If you have a My HealtheVet user ID and password" heading is the next heading level down in logical order from the "What will happen if you decline" heading.
> 
> Really appreciate your work on getting this out so quickly. Thanks again!

Will do

**Review by rileyanderson — APPROVED** [review]

**Comment by asg5704** [comment]
@DanielleThierryUSDSVA I'm going to confirm with my lead + Tom if we're ready to merge this.

**Review by CaitHawk — APPROVED** [review]

**Pull request merged**
