### PR TITLE
Update home page layout to use navigation-links-lists. #5479

### PR DESCRIPTION
**Pull request by ghost**
Closes department-of-veterans-affairs/vets.gov-team#2555
Closes https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2554
Closes https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2553
Closes https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1621

### CODE REVIEW

**Comment by tiffanybbrown-va** [comment]
Replacement PR for #5479 since the Heroku build wasn't working.

**Comment by melwoodard** [comment]
Perfect! Everything looks to be in a good place. Next steps as I mentioned before: keep the PR open so we can share a link with the wider team to preview.

@suzchap @amybehrens preview of the homepage updates here: https://vetsgov-pr-5527.herokuapp.com/

Summary of updates:
- Reduced the size of the hero image 
- Removed extraneous "that" from the tagline "Get the VA services (that) you've earned"
- Changed "Get started" links to a standard button style
- Replaced "Check claim status" button with link to the Veterans Crisis Line
- Change big blue cards to 1-column text links

**Comment by amybehrens** [comment]
I think this looks fab! I can work with the content team on updating the descriptions for the main content areas, but that shouldn't block moving forward with the design.

**Comment by suzchap** [comment]
LGTM!

**Review by melwoodard — APPROVED** [review]

**Pull request merged**
