### PR TITLE
Update reasons for appointment

### PR DESCRIPTION
**Pull request by jenniemc**
## Description
update the copy on the reason for appointment page that matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/reason-for-appointment.md) to the following:

- heading
- description
- radio options
- alert hotline selection

## Testing done
local and unit test

## Screenshots

image

## Acceptance criteria
- [ ] update the copy to match the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/reason-for-appointment.md) 

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by LeKeve — APPROVED** [review]
Looks good to me!

**Review by vbahinwillit — CHANGES_REQUESTED** [review]
One question. Is the following text in the copy doc to be added or changed?

"Please provide any additional details you'd like to share with your provider about this appointment. (*Required)"

**Comment by jenniemc** [comment]
Oh good catch @vbahinwillit. I see there's no change for direct schedule but a change for request appt. Making update now.

**Review by vbahinwillit — APPROVED** [review]
LGTM!

**Pull request merged**
