### PR TITLE
Removed bourbon, bourbon-neat npm packages. Using USWDS dependencies.

### PR DESCRIPTION
**Pull request by ghost**
Closes department-of-veterans-affairs/vets.gov-team#755

### CODE REVIEW

**Comment by jcmeloni-usds** [comment]
@tiffanybbrown-va Do you need help from @jkassemi or @robbiethegeek to see why Jenkins barfed?

**Comment by tiffanybbrown-va** [comment]
@jcmeloni-usds  Yes, please.

**Comment by jkassemi** [comment]
```

Cannot find module 'babel-eslint'
Error: Cannot find module 'babel-eslint'
    at Object.ModuleResolver.resolve (/application/node_modules/eslint/lib/util/module-resolver.js:75:19)
    at Object.load (/application/node_modules/eslint/lib/config/config-file.js:518:42)
    at loadConfig (/application/node_modules/eslint/lib/config.js:64:33)
    at getLocalConfig (/application/node_modules/eslint/lib/config.js:126:23)
    at Config.getConfig (/application/node_modules/eslint/lib/config.js:227:22)
    at processText (/application/node_modules/eslint/lib/cli-engine.js:223:27)
    at processFile (/application/node_modules/eslint/lib/cli-engine.js:298:18)
    at executeOnFile (/application/node_modules/eslint/lib/cli-engine.js:682:23)
    at /application/node_modules/eslint/lib/cli-engine.js:719:13
    at Array.forEach (native)
```

I'm pulling down the latest and doing a lint run locally with a fresh node_modules to see if I can replicate outside of the CI environment.

**Comment by jcmeloni-usds** [comment]
Ok! So, with tests passing and prelim reviews and commits by @raquelromano-gov and @annekainicUSDS and others, I'm good with this but would like one of the following to give another thumbs up before we call it good to merge: @robbiethegeek-usds @annekainicUSDS @raquelromano-gov Please and thanks!

**Review by jcmeloni-usds — APPROVED** [review]

**Review by raquelromano-gov — COMMENTED** [review]
Yay for no more warnings!

My only comment/question is that I don't understand why all of the https URLs are changed to http. And more generally, I don't understand how/when we are pushing changes to npm-shrinkwrap. Seems like whenever someone updates the package.json, we just go ahead and accept all of the other updates. I'm fairly new to node so don't know if that's common practice, or if there are more careful ways to manage it.

**Comment by tiffanybbrown-va** [comment]
> My only comment/question is that I don't understand why all of the https URLs are changed to http. 

That's a weird change, and I'm not sure why that's the case either. Will investigate and hold off on merging until I can figure it out. Happened after I deleted `node_modules` and re-ran `npm install`.

> And more generally, I don't understand how/when we are pushing changes to npm-shrinkwrap. Seems like whenever someone updates the package.json, we just go ahead and accept all of the other updates.

The point of `npm-shrinkwrap` is to freeze dependencies at or above a particular version so that everyone's development environment is consistent. `package.json` is the file that lets you specify what tools you used. `npm-shrinkwrap` is how other people can replicate it.

Otherwise we'd probably end up with a bunch of different, personalized configurations that we'd have to debug.

**Comment by raquelromano-gov** [comment]
@tiffanybbrown-va Yeah, I'm more wondering about our process for updating the shrinkwrap file. I realize (or assume) npm looks at dependencies and figures out what versions are needed to satisfy the package.json requirements, but it's a little disturbing that we'll make a 1-line package.json file change, then run npm-shrinkwrap and, since it's rarely run, get a ton of updates to the shrinkwrap file that git diffs can't properly handle so we just rubberstamp them. If it's rare that anything goes wrong with accepting the changes, then I will stop worrying about it!

**Comment by jcmeloni-usds** [comment]
@tiffanybbrown-va your call -- whenever you're ready to hit the merge, or if you and @raquelromano-gov want to talk more, I'm good w/ it. Do what's right.

**Comment by raquelromano-gov** [comment]
Good to merge from my end! Will ask the above questions at a FE architecture sync

**Review by raquelromano-gov — APPROVED** [review]

**Comment by raquelromano-gov** [comment]
FYI, long discussion in various slack channels on the mysteries of npm --shrinkwrap

**Pull request merged**
