### PR TITLE
Allow html to be displayed for tracked item description

### PR DESCRIPTION
**Pull request by jbalboni**
Closes [144](https://github.com/department-of-veterans-affairs/sunsets-team/issues/144)

(There's a `<br/>` in the text):
screen shot 2016-10-27 at 4 19 16 pm

### CODE REVIEW

**Comment by jbalboni** [comment]
@austin-martinez Can you verify for me that the `description` field is html that comes from EVSS and not users? I'm allowing anything through, which would be bad if it's somehow writable by users elsewhere.

**Review by molindoz — APPROVED** [review]
LGTM 👍

**Comment by carlmjohnson** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/374 would obviate this.

**Comment by jbalboni** [comment]
Will delete this PR if/when the API change gets merged.

**Pull request closed without merging**
