### PR TITLE
Set up confirmation page

### PR DESCRIPTION
**Pull request by cehsu**
These changes set up the Opt Out form confirmation page per issue [11293](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11293).

localhost_3001_education_opt-out_form_confirmation 1

### CODE REVIEW

**Review by emilywaggoner — CHANGES_REQUESTED** [review]
Looks great, @cehsu! There is a typo (which was my fault, it was in the copy I provided) in the 3rd paragraph, an extra "o" in the last phrase: "to o ask VA to start sharing..." Thank you!

**Review by rianfowler — APPROVED** [review]

**Review by peggygannon — COMMENTED** [review]
@cehsu Looks good. 

We just need to fix the typo (extra "o"). Can you upload a new screenshot when that is fixed?

**Comment by cehsu** [comment]
Thanks @peggygannon and @emilywaggoner for your feedback, kindly refer to the updated screenshot below:
localhost_3001_education_opt-out_form_confirmation 2

**Review by emilywaggoner — APPROVED** [review]
Looks great. Thanks, @cehsu!

**Comment by peggygannon** [comment]
@cehsu Looks good. thank you!

**Review by peggygannon — APPROVED** [review]

**Pull request merged**
