### PR TITLE
Modified font sizes and margins in certain GIBCT estimated benefits rows.

### PR DESCRIPTION
**Pull request by U-DON**
Resolves department-of-veterans-affairs/vets.gov-team#2252.

> screen shot 2017-04-18 at 8 42 59 pm

### CODE REVIEW

**Review by melwoodard — APPROVED** [review]
Thanks @U-DON - and yes, the bolding here looks good.

**Comment by saintsoup52** [comment]
This looks a lot better... 

One thing.. we don't want to bold the tuition costs but what the GI Bill will pay in tuition benefits.

**Comment by melwoodard** [comment]
Ok, @U-DON then why don't we (1) flip the order of the tuition lines so that GI Bill pays comes before Tuition and fees; (2) Make GI Bill pays the larger, bold weight, (3) make Tuition and fees the smaller, regular weight.

**Comment by U-DON** [comment]
screen shot 2017-04-19 at 6 32 08 pm

**Review by melwoodard — APPROVED** [review]
Looks good!

**Review by bshyong — APPROVED** [review]
LGTM

**Pull request merged**
