### PR TITLE
Va 11592 remove covid vaccine query flipper

### PR DESCRIPTION
**Pull request by eselkin**
Removes flipper for query to API.

## Summary

- Removes the flipper
- in order to test that flipper was removed, resolved crash on Covid19Result component.

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13331
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11592

Issue's crash prevents testing of other issues - so fixed in this PR:
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14959

## Testing done

- Tested against locally-run locator pointing to [vets-api](http://e5e27dd973a190be415eecadea0c13b0-api.review.vetsgov-internal) on deployed environment from https://github.com/department-of-veterans-affairs/vets-api/pull/13582 -- with query removed
- No adverse events in other pages noted

## Screenshots

N/A

## What areas of the site does it impact?

Facility Locator

## Acceptance criteria

- Flipper is removed

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable - N/A).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary - N/A)
- [x] Screenshot of the developed feature is added N/A
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed - N/A - nothing added and no displayed content changed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user (No, but no authenticated routes are touched)

## Requested Feedback

Check that deployed site does not crash when in facility locator.

## QA (for this to be QA'ed you the API needs to be updated as well)

- [ ] go to `/find-locations`
- [ ] select Facility type: "VA health"
- [ ] see if there is "COVID-19 vaccines" in the dropdown for service type

### CODE REVIEW

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Comment by powellkerry** [comment]
Looks like there is an e2e test that is failing:
```
  1) Facility VA search
       does a simple search and finds a result on the list:

      AssertionError: expected 'Covid19Vaccine' to equal 'DentalServices'
      + expected - actual

      -'Covid19Vaccine'
      +'DentalServices'
      
      at Context.eval (http://localhost:3001/__cypress/tests?p=src/applications/facility-locator/tests/e2e/facilitySearch.cypress.spec.js:1366:7)
```

**Comment by eselkin** [comment]
> Looks like there is an e2e test that is failing:
> 
> ```
>   1) Facility VA search
>        does a simple search and finds a result on the list:
> 
>       AssertionError: expected 'Covid19Vaccine' to equal 'DentalServices'
>       + expected - actual
> 
>       -'Covid19Vaccine'
>       +'DentalServices'
>       
>       at Context.eval (http://localhost:3001/__cypress/tests?p=src/applications/facility-locator/tests/e2e/facilitySearch.cypress.spec.js:1366:7)
> ```

Yep, fixed that and another test that failed. Thanks for catching it.

**Review by maxx1128 — APPROVED** [review]
LGTM 2

**Review by powellkerry — APPROVED** [review]

**Pull request merged**
