### PR TITLE
[Site-wide] Consume Promo-Banner from Formation

### PR DESCRIPTION
**Pull request by ncksllvn**
## Description
This PR begins consuming the new `PromoBanner` component from Formation, which replaces the green banner fixed to the bottom of the page, sometimes referred to as an announcement. See the Design System PR and ticket for more info.

Design System PR - https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/137
Ticket - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18175

## Testing done
- Tested using different screen sizes, text, promo-types

### Large
image

### Small
image

## Acceptance criteria
- [x] Promo-banner has been implemented

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by rtwell** [comment]
hey @ncksllvn this is looking great—thanks again for all of your hard work on this! My last tweak would be to align the same left margin as the cards (in the desktop view)—i dropped in a cyan rule for clarity:
image

**Comment by ncksllvn** [comment]
@rtwell patched over at https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/138 and updated in this PR -

image

**Comment by ncksllvn** [comment]
The [Heroku review instance](https://vetsgov-pr-10269.herokuapp.com/) works for seeing this in action, FYI

**Review by jbalboni — APPROVED** [review]

**Comment by ncksllvn** [comment]
@jaredcunha-usds had a concern about the close button touching the edge on some screen sizes. Addressing that here, https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/139, then planning to merge this.

**Pull request merged**
