### PR TITLE
More end to end tests for Secure Messaging

### PR DESCRIPTION
**Pull request by bshyong**
Resolves https://github.com/department-of-veterans-affairs/vets-website/issues/4563

Adds test for Desktop view
Adds test for Thread view for both Mobile and Desktop

### CODE REVIEW

**Review by U-DON — APPROVED** [review]
LGTM. There are some merge conflicts, though?

**Comment by bshyong** [comment]
Hmm will take a look and fix

**Comment by bshyong** [comment]
merge conflicts fixed

**Comment by U-DON** [comment]
Parts of the E2E tests aren't passing.

```
test/messaging/01-required-desktop.e2e.spec ✖ TypeError: client.url is not a function
```

```
test/messaging/00-required.e2e.spec ✖ Expected element <.messaging-thread-messages .messaging-thread-message:last-of-type .messaging-message-body> text to equal: "Reply 3" - element was not found - expected "present" but got: "not present"
```

**Comment by bshyong** [comment]
Found the bug—due to the use of auth token in mock requests. Should be working now

**Comment by U-DON** [comment]
Still LGTM, but should the commented out blocks be removed, since we're using `mock` now instead of just `request`?

**Comment by bshyong** [comment]
oof—forgot to remove that after debugging. Removed.

**Pull request merged**
