### PR TITLE
updates client_id for sis options w/ fallback

### LINKED ISSUE #51673: Add new client IDs on the FE
## Description
Mobile requires new Client IDs: `vaweb` and `vamobile`.  These parameter values should be added and continue to work as expected with their fallbacks `web` and `mobile`.  This is the FE work for #50585

## Tasks
- [ ] Add `vamobile` and `vaweb` as Client IDs parameter options

### PR DESCRIPTION
**Pull request by asg5704**
## Summary

- *(Summarize the changes that have been made to the platform)*
> This PR updates the client IDs to add the new ones needed for the Sign in Service
- *(What is the solution, why is this the solution)*
> The solution is to add `vaweb` and `vamobile` to the client IDs lookups, ensure the `createOAuthRequest` completes an equality check using the `.includes` method to check for either `vaweb` or `web` for Web-based client IDs and `vamobile` and `mobile` for Mobile-based client IDs
- *(Which team do you work for, does your team own the maintainence of this component?)*
> Identity. Yes

## Related issue(s)
- *Link to ticket created in va.gov-team repo*
Closes department-of-veterans-affairs/va.gov-team#51673
- *Link to epic if not included in ticket*
https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/42469

## Testing done

- *Describe what the old behavior was prior to the change*
> When using Sign in Service (OAuth) the `client_id` parameter would be generated as either `web` or `mobile` based on the application
- *Describe the steps required to verify your changes are working as expected*
> 1. Unit tests are passing as expected
> 2. Manually verifying the new client IDs
>   2a. `/sign-in/?application=vamobile&oauth=true` yields `client_id=vamobile`
>   2b. `/sign-in/?application=vamobile&oauth=true&client_id=mobile` yields `client_id=mobile`
>   2c. `/sign-in/?oauth=true` yields `client_id=vaweb`
>   2d. `/sign-in/?oauth=true&client_id=web` yields `client_id=web`
- *Describe the tests completed and the results*
> The expected client ID parameter options are now the newly created client IDs by default `vaweb` and `vamobile` with fallbacks for manually specified `client_id=<web|mobile>`

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*
This should only modify the Unified Sign in Page (`/sign-in`) on VA.gov for users utilizing the Sign in Service (OAuth) in staging and below.

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [x]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Review by it-harrison — APPROVED** [review]

**Comment by AGarcia-Clarity** [comment]
@department-of-veterans-affairs/vsp-identity Can I get a review on this?

**Comment by asg5704** [comment]
This will have to wait until vets-api is ready

**Review by bramleyjl — APPROVED** [review]
Tested with [companion vets-api PR](https://github.com/department-of-veterans-affairs/vets-api/pull/11541), both old client_ids & new `vaweb`/`vamobile` work as expected.

**Comment by asg5704** [comment]
@department-of-veterans-affairs/benefits-team-1-frontend Can I get a review on this PR please and thank you.

**Review by data-doge — APPROVED** [review]

**Pull request merged**
