### PR TITLE
Updated component library version to 2.5.7 (Latest Version)

### PR DESCRIPTION
**Pull request by noahgelman**
## Description

Updated component library version to 2.5.7 (Latest Version)

## Original issue(s)
The latest version of the component library fixes this bug https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/241 so we are updating it vets-website

## Testing done
Testing on original issue already complete, approved, and merged into component library

### CODE REVIEW

**Review by 1Copenut — APPROVED** [review]
LGTM!

**Review by ndsprinkle — APPROVED** [review]

**Comment by noahgelman** [comment]
@1Copenut @ndsprinkle 
I am unable to merge till the failed tests are passed. Is there something I can do to remedy this? I've only updated the version on one of the packages.

**Comment by ddzz** [comment]
@noahgelman This PR is missing an updated `yarn.lock` file.

**Review by ddzz — APPROVED** [review]

**Comment by noahgelman** [comment]
@ddzz I did npm install and not yarn install. Silly me. Thank you so much!

**Pull request merged**
