### PR TITLE
Add role to validation errors

### PR DESCRIPTION
**Pull request by jbalboni**
This adds `role="alert"` to error messages so that they're read aloud. It also adds an "Error" prefix for screen readers to help with context.

### CODE REVIEW

**Review by cehsu — APPROVED** [review]
LGTM. There may be other instances, such as usages of "date-range-error".

**Review by cvalarida — APPROVED** [review]
How tedious. 😬 
Thanks for doing this! Looks great. 👍

**Comment by jbalboni** [comment]
@cehsu It looks like date-range-error is used mostly in an aria-live region, and should be announced? I'm not really sure how to address it if not. That code seems odd.

**Comment by cehsu** [comment]
Thanks @jbalboni, that's helpful context.

**Pull request merged**
