### PR TITLE
Add composer.json to allow CMS to install and update via packagist.org.

### PR DESCRIPTION
**Pull request by jonpugh**
# Context

The CMS team needs this so that we can have functional preview on local and PR review instance environments. For this to be stable, we need to automatically update and test the version of WEB that CMS installs. 

Currently CMS Team can only do the existing "live" preview on DEV, STAGING and PROD. We have added the ability to quickly run a full site rebuild on demand inside CMS-CI PR environments.

# Goal 

The high level goal is to be able to deploy CMS daily automatically, while not breaking WEB builds.

One way or another, the only way to do that is to have a tool that reads WEB commits and updates our stack to test and merge that commit. 

The easiest way to do that is to fold WEB into our existing dependency management tool, composer. Then, the automated update process we will be implementing anyway will take care of WEB updates for us.

## Node & Composer

The [CMS already includes NPM and Bower](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/7b53162c0d355100454660ae15a618e30d6b4513/composer.json#L91) assets via [Asset-packagist.org](https://asset-packagist.org).  Not just the CMS but it's upstream project, Acquia Lightnig, uses Asset Packagist to include many NPM packages without needing node, npm, or package.json.

The best argument for doing this is summarized on the original plugin that inspired the AssetPackagist project:

From https://github.com/fxpio/composer-asset-plugin#why-this-plugin :

> It goes without saying that each javascript, CSS, etc. library should be developed with the usual tools for that language, which front-end developers know well. However, in the case of a complete project in PHP, it shouldn't be necessary to use several tools (PHP, Nodejs, Composer, NPM, Bower, Grunt, etc.) to simply install these assets in your project.
>
>This plugin has been created to address these issues. Additionally, most developers will not add a composer.json file to their projects just to support php based projects, especially when npm and/or bower already exist and are widely used.

## CMS-CI & WEB

CMS-CI can now rebuild the entire static site inside our PR sites at `/docroot/static` with a single button push in under a minute. @jonpugh has a PR that connects the "Rebuild Site" button on  "admin/content/rebuild" to this CMS-CI button, while maintaining the functionality in DEV, STAGING, & PROD by using Jenkins to trigger the rebuild.

Interestingly, though, The CMS sites (all of them, DEV, STAGING, PROD, CI, LOCAL) now contain this ability: They can all regenerate the full static site by themselves. 

We have access to backend tasks on CMS-CI, so we can run full rebuilds on demand there. We don't have direct access to the DEV/STAGING/PROD servers, but we could setup a cron job to rebuild the self-hosted front-end every minute, for example. Then, PROD/STAGING/DEV could use *themselves* for the "Preview" functionality, and you could decomission the existing Preview server entirely. 

## Suggested Changes

This PR adds a single `composer.json` file so that Packagist.org can update the WEB SHA for us.

I have created a fork of `vets-website` and set that repo up on Packagist as an example: See https://packagist.org/packages/va-gov/web#dev-unity

## Testing done

This work is being done in three CMS PRs: 

### PR589: Packagist-based WEB Install

https://github.com/department-of-veterans-affairs/va.gov-cms/pull/589

- This CMS PR includes this WEB at `master` branch: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/589
- It uses the packagist.org hosted metadata.
- We can test automatic updates by controlling pushes to `master` branch on my fork.

### PR598: CMS-Native Preview

https://github.com/department-of-veterans-affairs/va.gov-cms/pull/598

- Changes "Site Rebuild" button to say "Build & Deploy to x.va.gov".
- Adds helpful descriptions to that form.
- Makes that form work to trigger a CMS-CI Front-end rebuild.
- Makes the form work for Local development by telling devs what command to run to get the same behavior.
- Changes "Preview" button on content to launch the self-hosted static file, if there is one (only on CMS-CI and local right now)
- Gives Drupal the concept of "static_html" version of a node: 
  - Visit /node/1, get the Drupal HTML.
  - Visit /node/1?_format=json : Get the json version of that node. (Drupal Core JSON REST API)
  - Visit /node/1?_format=static_html: Get the static rendering of that node. (VA Gov Preview Drupal Module)
- .htaccess trick allows for hosting Static assets in the CMS URL: `/js/va.js` loads `/static/js/va.js` so that when viewing pages like `/node/1?_format=static_html` or `/static/health-care`, all the CSS and other assets work.

# Alternatives

### Alternative # 1. Submit vets-website to NPM

Since we can already install any npm package, adding Vets website to NPM registry would solve this for us.

However it seems that maintaining an NPM repo is more work than maintaining a Packagist one.

### Alternative # 2: PR607: Self-managed Packages.json

https://github.com/department-of-veterans-affairs/va.gov-cms/pull/607

- Static Packages.json: Any packages.json file can be used as long as it's accessible via HTTP.
- We realized we can push a packages.json file to GitHub and just reference that.
- This is a viable solution, but we would still need to write a script to update this file for us. (This is what Packagist would do for us. 
- From @jonpugh: I tried to find a class that would convert GitHub data to `packages.json` but came up short. I am not opposed to creating a PHP/Composer plugin that reads GitHub commits and releases and generates the package.json, as this Node/Composer pattern is going to be used often. 

### Alternative # 3: Augment current solution: composer.json:repositories

We can continue to use the custom pseudo "repositories" entry in `composer.json` and create a plugin to update the SHA on `composer update`.

## Screenshots

Screenshot from 2019-09-25 10-01-20

## Acceptance criteria
- [ ] Valid composer.json is added, Vets-website is submitted to Packagist.org

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by gunsch** [comment]
@jonpugh: I've heard very little support from the VSP team in terms of adding Packagist into our set of things we have to care about, and @cvalarida has pushed back pretty regularly on this approach.

It sounds like there are other approaches here that don't conceptually entangle the `vets-website` itself with the CMS build process the way this PR would, including just grabbing the vets-website master SHA (i.e. https://api.github.com/repos/department-of-veterans-affairs/vets-website/git/refs/heads/master). Can we select another route?

**Comment by ElijahLynn** [comment]
We need this so that we can have functional preview on local and PR review instance environments. Currently we just have preview on DEV, STAGING and PROD. 

I updated the description to say this.

**Comment by jonpugh** [comment]
If we can generate a `packages.json` file similar to that which packagist.org provides, we can get the same effect: I have successfully manually created a file like this, and set our update process to point at that and it works.

https://raw.githubusercontent.com/department-of-veterans-affairs/va.gov-cms/VAGOV-5963-release-redux/packagist/packages.json

However, we would need this `packages.json` file to update everytime you merge to master or create a new release.

I could write a PHP command to read GitHub commits and update `packages.json` for us, and then we can setup a cron job so it continuously updates.

The main mission here is to allow CMS team to test WEB commits in the CMS-CI pipeline so we can guarantee WEB will work with each release of CMS.

Then, to guarantee stable deployment, we need to deploy the confirmed version of CMS before we deploy the confirmed version of WEB, so we know what version of CMS that WEB is building against,

**Comment by ElijahLynn** [comment]
@jonpugh is working on a new approach, closing.

**Comment by jonpugh** [comment]
It's taken me multiple days to figure out a way to hack into composer via a plugin to load the master SHA. I still don't have a solution working: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/611

The UpdateHandler.php looks for the sha and tries to force composer to use that sha, but the behavior has been very unpredictable and challenging. 

We are focused on resolving this today once we get the failure flags merged from https://github.com/department-of-veterans-affairs/va.gov-cms/pull/595

If this were approved, we would be thrilled and it would save a lot of work!... Let us know what you all think. Happy to figure out how to make it official that the CMS maintainers would be responsible for maintaining the Packagist.org account.

**Review by rianfowler — APPROVED** [review]

**Comment by jonpugh** [comment]
Thank you all!

**Comment by ElijahLynn** [comment]
https://packagist.org/packages/va-gov/web webhook for vets-website has just been setup and is updating on pushes.

**Pull request merged**
