### PR TITLE
un-italicizing e from My HealtheVet

### PR DESCRIPTION
**Pull request by accbjt**
## Description
un-italicizing e from My HealtheVet

## Testing done
Local Testing

## Acceptance criteria
- [ ] all <e> tags from removed My HealtheVet

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by ncksllvn** [comment]
Looks like there are a few results in the `src` directory we still need to grab - 

image

**Review by jbalboni — APPROVED** [review]

**Comment by ncksllvn** [comment]
@accbjt Can you connect this to the ticket? There are also some references remaining in the `src` directory that we ideally we can swoop through and update. Otherwise, this issue is going to pop back up.

**Comment by accbjt** [comment]
@ncksllvn Yeah I found some more of these. I think I got them all now. There were some that were in the markdown files also.

**Review by ncksllvn — APPROVED** [review]
LGTM

**Pull request merged**
