### PR TITLE
15835 create helper functions for cypress

### PR DESCRIPTION
**Pull request by holdenhinkle**
## Description
ZenHub ticket - https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/16330

This work also references this ticket, which is the parent to the one noted above - https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15835

Created the following Cypress custom commands:
- `cy.injectAxeThenAxeCheck()`
- `cy.viewportPreset()`

Created a handful of Cypress environment variables in `cypress.json` for groups of viewports that `va.gov` users use, grouped by mobile, tablet and desktop. Also created a group that contains all iPhone viewports.

## Testing done
Manual testing for each custom command and the environment variables was completed.

## Screenshots
NA

## Acceptance criteria
- [x] Cypress environment variables that each contain an array of viewport data by group (e.g. `allMobile`, `allTablet`, `allDesktop`, `top5Mobile`, `top5Tablet`, `top5Desktop`, etc.) will be created with United States, 2020 data or va.gov data from Google Analytics (va.gov data is preferred if it exists)

## Definition of done
- [ ] Events are logged appropriately - NA
- [ ] Documentation has been updated, if applicable - NA
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by holdenhinkle** [comment]
While writing the documentation for `cy.injectAxeThenAxeCheck()` I realized I didn't handle the optional arguments that can be passed to cy.axeCheck(). I'll add support for those now, then resubmit the PR.

**Comment by holdenhinkle** [comment]
`cy.injectAxeThenAxeCheck()` now accepts arguments that are passed to cy.axeCheck().

**Comment by holdenhinkle** [comment]
Here's the documentation for features added in this PR - https://github.com/department-of-veterans-affairs/va.gov-team/blob/write_documentation_for_new_cypress_viewport_env_vars_and_custom_command/platform/testing/end-to-end/cypress-best-practices-on-vsp.md

Once this PR and approved and merged, I'll update the 'source' links in this documentation and then submit a PR for it.

**Review by billfienberg — COMMENTED** [review]
The code makes sense. If you refactored any tests to use these helpers, I'd like to see those commits. Perhaps you could branch off of this branch and commit a couple refactored tests so you can point to CI passing while using your new helpers.

**Comment by holdenhinkle** [comment]
@billfienberg 

I created a new brach with refactored tests using the new Cypress environment variables and custom commands - refactor_tests_using_new_env_vars_and_custom_commands

Here are the files:
https://github.com/department-of-veterans-affairs/vets-website/blob/210807938a7a2f2f43c6212a6b93fda06ccfa9f5/src/applications/facility-locator/tests/e2e/mobile.cypress.spec.js

https://github.com/department-of-veterans-affairs/vets-website/blob/210807938a7a2f2f43c6212a6b93fda06ccfa9f5/src/applications/facility-locator/tests/e2e/search.cypress.spec.js

**Comment by billfienberg** [comment]
> I created a new branch with refactored tests using the new Cypress environment variables and custom commands - refactor_tests_using_new_env_vars_and_custom_commands
> 
> Here are the files:
> https://github.com/department-of-veterans-affairs/vets-website/blob/210807938a7a2f2f43c6212a6b93fda06ccfa9f5/src/applications/facility-locator/tests/e2e/mobile.cypress.spec.js
> 
> https://github.com/department-of-veterans-affairs/vets-website/blob/210807938a7a2f2f43c6212a6b93fda06ccfa9f5/src/applications/facility-locator/tests/e2e/search.cypress.spec.js

For anybody else that's curious, here's the comparison view so you can review it like a PR:
https://github.com/department-of-veterans-affairs/vets-website/compare/15835-create-helper-functions-for-cypress...refactor_tests_using_new_env_vars_and_custom_commands

**Review by billfienberg — APPROVED** [review]
LGTM. Thanks for making a [temp branch](https://github.com/department-of-veterans-affairs/vets-website/compare/15835-create-helper-functions-for-cypress...refactor_tests_using_new_env_vars_and_custom_commands) to show the helpers being used.

**Comment by holdenhinkle** [comment]
Thank you @billfienberg !

**Pull request merged**
