### PR TITLE
[Development/CI/CD] Fix ReviewCardField accessibility

### PR DESCRIPTION
**Pull request by Mottie**
## Description

This PR fixes an accessibility issue within the `ReviewCardField` and `ObjectField` components.

It's related to:

- issue https://github.com/department-of-veterans-affairs/va.gov-team/issues/7319
- PR https://github.com/department-of-veterans-affairs/vets-website/pull/12241

the errors fixed by this PR are preventing completion of the PR above.

### Before

When the `ObjectField` renders a `ReviewCardField` that contains `volatileData` (e.g. bank account info) it wraps the content in a `DL` tag. This tag only allows `DT` and `DD` as children, and a `DIV` wrapping those children (in modern browsers); That's `DL` > `DIV` > `DT/DD`. But because the ReviewCardField includes other elements, such as headers & buttons. This causes a "serious" impact accessibility issue

<details><summary>Axe Coconut DL content accessibility issue</summary>

Screen Shot 2020-04-28 at 3 47 47 PM</details>

<details><summary>DOM structure (before)</summary>

Screen Shot 2020-04-28 at 3 55 52 PM</details>

Since this issue only occurs when a `ReviewCardField` with `volatileData` set as `true` and both of the effected components are called separately, they both need to check this option and alter their behavior.

### After

<details><summary>Axe Coconut result</summary>

Please ignore the first two accessibility issues (missing document title & html language attribute). I only seems to appear locally, and not in the staging environment.

Screen Shot 2020-04-28 at 3 50 34 PM</details>

<details><summary>DOM structure (after)</summary>

Screen Shot 2020-04-28 at 3 57 20 PM</details>

## Testing done

Local unit tests; additional tests added & passing

## Screenshots

See above

## Acceptance criteria

Axe Coconut (extension) testing passes on:

- [x] (user 228) 526 banking account info page: https://staging.va.gov/disability/file-disability-claim-form-21-526ez/payment-information
- [x] (user 228) 526 review & submit page: https://staging.va.gov/disability/file-disability-claim-form-21-526ez/review-and-submit
- [x] (user 0) 0994 edu banking info: https://staging.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994/direct-deposit-information
- [x] (user 0) 0994 edu benefits review & submit: https://staging.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994/review-and-submit

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by 1Copenut — CHANGES_REQUESTED** [review]
@Mottie Thank you for taking on this work. I did some looking at the 526EZ on my local instance. I filled out a quasi-realistic form with two new disability ratings, then opened every accordion on Step 5 (review) and ran an axe check.

There were two instances where I was still seeing axe errors owing to the outputted HTML. Attaching them below as screenshots.

I think once those are cleaned up, we can merge this work. I'd also like to see axe checks added to the end-to-end tests if possible, so we can fill out a form, open the accordions, and validate that there's not a regression for future builds. LMK if you want to discuss this further or what I'm asking presents problems to your work in progress.

--
Screen Shot 2020-04-29 at 10 13 28 AM

---
Screen Shot 2020-04-29 at 10 46 10 AM

**Comment by Mottie** [comment]
@1Copenut If you don't mind, I'd like to address those other two additional problems in a different PR. This one was meant to handle the `ReviewCardField` (and the `ObjectField`, which is also a problem in the above screenshots you shared). Which only applies to the email, phone, address & bank account sections. 

The additional screenshots appear to use the ObjectField` and `SelectArrayItemsWidget` in a similarly complicated matter. So the changes might require adding a new `ui:option` and definitely more unit tests.

**Comment by 1Copenut** [comment]
@Mottie Thank you for clarifying that those are additional components. I tried to look at them using the React Component inspector, but missed the mark. I'll approve the PR, and open a related ticket for the other work I highlighted in my comment.

**Review by 1Copenut — APPROVED** [review]
After discussing scope of the work with @Mottie I'm changing my review to approved with no changes. 💯

**Review by jhonny218 — APPROVED** [review]
LGTM

**Review by ndsprinkle — APPROVED** [review]

**Pull request merged**
