### PR TITLE
Remove feature toggle for auth menu

### PR DESCRIPTION
**Pull request by adamwhitlock1**
## Summary

- The links for the 'enhanced authenticated menu' hav been in production at 100% for some time now, so this PR is to clean up the logic for using the toggle `show_authenticated_menu_enhancements`

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/70769

## Testing done

- Updated unit tests for display and GA events around these links

## Screenshots

No UI changes

## What areas of the site does it impact?

Sitewide user nav dropdown

## Acceptance criteria

- check for feature toggle has been removed
- feature toggle name has been removed from sitewide code

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed

Checked injected header as well locally:
Not logged in
Screenshot 2023-12-11 at 10 29 11 AM

Logged in using local api:
Screenshot 2023-12-11 at 10 35 18 AM

### CODE REVIEW

**Review by allisonlu — DISMISSED** [review]
lgtm! are you going to remove the feature flag from `vets-api` as well?

**Comment by adamwhitlock1** [comment]
> lgtm! are you going to remove the feature flag from `vets-api` as well?

Yep, that will be next on the ole chopping block

**Review by randimays — DISMISSED** [review]
LGTM. Thanks for the injected header screenshots!

**Review by allisonlu — APPROVED** [review]

**Review by randimays — APPROVED** [review]
LGTM

**Review by harshilmoradia — APPROVED** [review]
LGTM

**Pull request merged**
