### PR TITLE
12057 adds hook for staggered feature release

### PR DESCRIPTION
**Pull request by apisandipas**
## Summary

Allows for staggered release of soft launch modal via reusable hook. Specifically, this PR utilizes the hook to allow a percentage of visitors to be shown the soft-launch modal for the new hompage, currenrtly set at 25%.
As similar functionality was used in the past for the chat-bot, we've opted to implement this functionality as a custom React hook for future reuse. 

## Related issue(s)
- department-of-veterans-affairs/va.gov-cms/issues/12057

## Testing done

- Manual Testing completed.

## Screenshots
n/a - no visual aspect.

## What areas of the site does it impact?
Currently, this will effect 25% of users visiting the homepage, once the feature flag is enabled.

## Acceptance criteria

- [x]  I added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution - Handled by department-of-veterans-affairs/va.gov-cms/issues/12048
- [x]  Documentation has been updated (see doc block above new React hook)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [n/a]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [n/a]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [n/a]  I added a screenshot of the developed feature

## QA Steps
1. Build `vets website` with the following command: `yarn watch --env api=https://staging-api.va.gov` or visit the test environment.
2. There's a 25% chance you'll be shown the soft-launch modal automatically. If you aren't, check the localStorage for the key of `show-homepage-soft-launch-modal` and set the value to be below or equal to 25. 
3. Refresh the page. You should now see the modal. 
4.  Keep in mind, if you dismiss the modal at any point, this dismissal will be persisted in sessionStorage. Clear sessionStorage or repeat steps in a new tab to verify functionality more than once.
5. Try changing the localStorage value to a number greater than 25 and see that you're *not* shown the modal.

## Requested Feedback

Assure modal functions as desired according to the QA Steps above.

### CODE REVIEW

**Review by jtmst — APPROVED** [review]
code looks good.  not able to test in review instance at this time

**Review by it-harrison — APPROVED** [review]

**Comment by jilladams** [comment]
@apisandipas tried test steps on the review instance: 
* Load http://6648f6b34a4c8dfad3534af77a04aa0d.review.vetsgov-internal/
* Check local storage => `show-homepage-soft-launch-modal` = `55.000000001`
* Edit `show-homepage-soft-launch-modal` and set to 23
* Refresh page: modal does not show

Would you expect that I should be able to see the modal now on a Review Instance?

**Comment by jilladams** [comment]
Oh: the RI would probably need the modal flipper enabled for this to work. Yeah?

**Comment by apisandipas** [comment]
@jilladams That sounds accurate. Will merge once I get checks passing.

**Pull request merged**
