### PR TITLE
Content/wip/rate tables link fix

### PR DESCRIPTION
**Pull request by peggygannon**
Update links to rate tables on 3 vets.gov pages

### CODE REVIEW

**Comment by peggygannon** [comment]
@bethpotts PR is ready for your review. 

For the disability/ratings link, I had trouble getting the link to land on the Combined Ratings subhead, so the link goes to the top of the page. I also rewrote sentence a bit to help set up the link address. Let me know if you think additional rewriting is needed. There is space on the page if we wanted to provide more detail.

**Comment by bethpotts** [comment]
@peggygannon Looks good! The only change I made was to that Combined Ratings link. It's going to look like I'm reverting, but something changed on va.gov's end since I first opened this issue. They either added a heading over that table or changed the jump link, so now I think it works to link to that part of the page because there's context for the table (where there wasn't before). 
Now it says: Table I-Combined Ratings Table.

The link we originally had (that didn't show a heading above the table) was: 
https://www.benefits.va.gov/COMPENSATION/rates-index.asp#combined

The link I found on va.gov on that page, up higher, that jumps down to the table, was:
https://www.benefits.va.gov/COMPENSATION/rates-index.asp#combinedRatingsTable1

So I changed the link to that.

I like your rewriting. It's much better! Thank you for that.

**Review by bethpotts — APPROVED** [review]
Approved!

**Comment by peggygannon** [comment]
@phiden this PR is ready for your review and then merge!

**Review by phiden — APPROVED** [review]

**Pull request merged**
