### PR TITLE
Content/wip/removebrtags

### PR DESCRIPTION
**Pull request by bethpotts**

### CODE REVIEW

**Comment by bethpotts** [comment]
@phiden After you and @peggygannon have both signed off, would you please merge this PR? I believe you're our merger now! Fun for you. This PR is an effort to clean up files where we'd used now-outdated tagging. No content changes, but removing unneeded tags and changing <br /> to simply <br>.

**Review by phiden — APPROVED** [review]
LGTM

**Comment by phiden** [comment]
Will merge as soon as I have @peggygannon's ok!

**Review by peggygannon — APPROVED** [review]
LGTM!

**Pull request merged**
