### PR TITLE
Update webpack-dev-server proxy settings for new API URLs.

### PR DESCRIPTION
**Pull request by U-DON**
New API URLs are going to be dev-api.vets.gov/v0/\* and staging-api.vets.gov/v0/*. And it sounds like *.vets.gov/api will be decommissioned after next week. Be sure to update your local config.proxy.js accordingly.

@jbalboni I noticed edu-benefits has one instance of a fetch against an API endpoint and thought you guys might be using the proxy too, so just giving a heads up.

### CODE REVIEW

**Comment by webinista** [comment]
LGTM, I guess. I'm seeing lots of 404 errors though.

**Comment by jbalboni** [comment]
@U-DON Do you have a plan for how we choose the right url in the apps? I don't think `buildtype` is enough information to switch between dev/staging/prod.

**Comment by U-DON** [comment]
@webinista Did you update the host to `staging-api.vets.gov` in your config.proxy.js before running `npm run watch`? Also, if I run `npm list webpack-dev-server`, I get version 1.16.1 (I think only 1.15+ supports the `pathRewrite`). Maybe `npm run install` before the build for good measure.

@jbalboni Not really. We've just been working off of staging for local development, and in order to use either dev or staging for that, we need the proxy because neither support CORS. The proxy settings was originally set up by @alexose, and we just use the config/config.proxy.js file to modify where we point our API calls.

When the URLs change, our use of relative paths also won't work on the deploy environments either. In that case, I guess the better change would be a combination of (1) using `environment` from src/js/helpers/environment.js and (2) depending on the dev's preference, using the `buildtype` to use the proxy instead of running a local build of the API (at `localhost:3000`).

**Comment by webinista** [comment]
I ran `npm install`. I updated the host name. Maybe the switch hasn't happened yet? I still see 404s everywhere.

**Comment by U-DON** [comment]
Both are working for me. The URL from each project's config.js should remain as `/api/v0/*` as well.

**Comment by webinista** [comment]
Figured out what I was doing wrong. LGTM

**Pull request merged**
