### PR TITLE
Mhv 46006 reply sending spinner

### PR DESCRIPTION
**Pull request by KolbyVA**
## Are you removing, renaming or moving a folder in this PR?
- [ ] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

If the folder you changed contains a `manifest.json`, search for its `entryName` in the content-build [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) (the `entryName` there will match).

If an entry for this folder exists in content-build and you are:
1. **Deleting a folder**: Delete the application entry in [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) and merge that PR **before** this one
- _Add the link to your merged content-build PR here_

2. **Renaming or moving a folder**: Update the entry in the [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json), but do not merge it until your vets-website changes here are merged. The content-build PR must be merged immediately after your vets-website change is merged in to avoid CI errors with content-build (and Tugboat).

### :warning: TeamSites :warning:
Examples of a TeamSite: https://va.gov/health and https://benefits.va.gov/benefits/. This scenario is also referred to as the "injected" header and footer. You can reach out in the `#sitewide-public-websites` Slack channel for questions.

Did you change site-wide styles, platform utilities or other infrastructure?
- [ ] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary
Adds a spinner when you reply to a message to let the user know we are attempting to send their message.

## Related issue(s)
https://jira.devops.va.gov/browse/MHV-46006
Add spinner for Reply message page-Messages with large attachments

> This ticket includes the negative flow as well.
> 
> Note:  This does not apply to a multiple draft scenario. (0.1% of session on va.gov run into multiple drafts)
> 
> Given: a user has composed a Reply message
> When: a user clicks “send”
> Then: all body content is removed from screen and there is a loading screen shown for a minimum of 1 second until the front end receives the 'success response' from the server
> When: the message is successfully sent
> Then: user is redirected to inbox with success banner
> 
> When:  an error is 
> 
> Note: We do not want the user-entered data to disappear. If the loading spinner activates, and an error occurs, we want the user to return to the draft, with their information that they have entered present.
> 
> https://www.figma.com/design/2k0wyYzd2nmoFMSNb8xmZJ/Message-file-attachments?node-id=13-8732&t=BiuHFqF65nfcAcER-4

## Testing done
All unit tests passing

## Screenshots
Screen Shot 2024-07-31 at 11 28 37 AM

## What areas of the site does it impact?
secure-messaging

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by rmessina1010 — DISMISSED** [review]
LGTM

**Comment by oleksii-morgun** [comment]
@KolbyVA if this is still in progress, as I understand, let's convert to draft so that platform folks are not triggered by any updates before it is ready for review

**Review by alex-morgun-1 — DISMISSED** [review]
✅

**Review by vsaleem — APPROVED** [review]
💯

**Pull request merged**
