### PR TITLE
Fix a few spelling errors

### PR DESCRIPTION
**Pull request by hollomancer**

### CODE REVIEW

**Comment by jcmeloni-usds** [comment]
@robbiethegeek Can we clear this up in addition to your changes ongoing to the readme? Thanks!

**Comment by jcmeloni-usds** [comment]
ping @ayaleloehr @robbiethegeek-usds

**Comment by robbiethegeek-usds** [comment]
@hollomancer any chance you can do a cleanup of this conflict and then I will do my best to land this.  If not I am going to close this PR and make these changes in a new one.

**Review by robbiethegeek-usds — APPROVED** [review]

**Review by jkassemi — APPROVED** [review]

**Comment by hollomancer** [comment]
Made requested changes.

**Comment by robbiethegeek-usds** [comment]
Thanks for your updates, we couldn't merge because of our checks not being able to run against your fork of our repository.  I created a new PR https://github.com/department-of-veterans-affairs/vets-website/pull/5078 and will credit you there.

**Pull request closed without merging**
