### PR TITLE
content/wip/addchapter35

### PR DESCRIPTION
**Pull request by marybyrnepark**
Added reference to Chapter 35 for SEO

### CODE REVIEW

**Comment by marybyrnepark** [comment]
@1Copenut 
This PR is ready for your review and merge. Thanks!

**Review by bethpotts — APPROVED** [review]
Looks great! Go for the merge.

**Review by 1Copenut — APPROVED** [review]
Looks good to me

**Comment by 1Copenut** [comment]
@marybyrnepark @bethpotts Squashed and merged these changes. They'll be part of 5/09 production build.

**Pull request merged**
