### PR TITLE
Migrate letters app address updater to vet360

### PR DESCRIPTION
**Pull request by ndsprinkle**
## Description
This pull request is updating the letters app to use the vet360 mailing address component (used on the profile page) instead of the custom mailing address components (exclusive to this one place in the letters app) that use pciu_address.

## Screenshots
LettersAddress

Screenshot of the letters app using the vet360 mailing address component.

## Acceptance criteria
- [ ] AddressSection updated to use MailingAddress
- [ ] Import/export vet360 reducers in the letters reducer
- [ ] Update the emptyAddress banner to use vet360 for the address check
- [ ] Simplify the Main container to only pull letters/BSL data and no longer pull address data
- [ ] Update tests accordingly

### CODE REVIEW

**Comment by ndsprinkle** [comment]
For some reason, all of the code changes from my capitalizeEachWord PR are showing up in this PR. No idea how that can happen considering there should be no "difference" between those changes and what's currently in master since those changes have already been merged.

**Review by Mottie — APPROVED** [review]
Looks good! 👍

**Comment by ndsprinkle** [comment]
Original issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1832

**Review by rianfowler — APPROVED** [review]

**Comment by ncksllvn** [comment]
I just stumbled upon this, and just wanted to say how happy it makes me to see Vet360 implemented in this application! Also, that diff - `+34 −1,053 - 👏

**Pull request merged**
