### PR TITLE
VACMS-17884: VA-Icon upgrades for facility locator

### PR DESCRIPTION
**Pull request by chriskim2311**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary
Updates to facility locator to use va-icon. 

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17884

## Testing done
Tested locally

Was not able to find all use cases with data for certain changes. When looking at the facility locator provider search. 

## Screenshots

Find_VA_Locations___Veterans_Affairs
Find_VA_Locations___Veterans_Affairs

Facility Detail Page
VA_Regional_Benefit_Satellite_Office_at_Fresno___Veterans_Affairs

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by laflannery** [comment]
Approved, and just noting that I reviewed the [Facility detail page here](http://0048fb350c07a929847ddd1e09be5e2f.review.vetsgov-internal/find-locations/facility/vba_343ao)

**Review by eselkin — COMMENTED** [review]
LGTM

**Comment by thejordanwood** [comment]
Looks good to me!

My only note is that the [Facility page](http://0048fb350c07a929847ddd1e09be5e2f.review.vetsgov-internal/find-locations/facility/vba_343ao) Laura linked has the phone icon in black. We just need to make sure that it's blue like it is in your screenshot. 

Screenshot 2024-06-07 at 1 27 07 PM

**Comment by laflannery** [comment]
@thejordanwood and @chriskim2311 I do not believe colors can be changed on the `va-icon`, [there is a slack a discussion here](
https://dsva.slack.com/archives/C01DBGX4P45/p1715610025615829?thread_ts=1715375749.388949&cid=C01DBGX4P45) that speaks to this that might be helpful

**Comment by thejordanwood** [comment]
@laflannery Thanks for linking that! @chriskim2311 If we can't change the color, then this is fine as is.

**Review by CBonade — DISMISSED** [review]

**Comment by chriskim2311** [comment]
@CBonade thanks for the previous review! Can you do one more check please I made one more style change

**Review by CBonade — APPROVED** [review]

**Pull request merged**
