### PR TITLE
DO NOT MERGE Turn on VIC content pages in prod

### PR DESCRIPTION
**Pull request by jbalboni**
These are not behind a password, but they're not linked anywhere.

### CODE REVIEW

**Review by peggygannon — COMMENTED** [review]
@jbalboni Hi, Jeff, can you tell me what you need me to review for this PR? The url paths for: /how-to-get/ and /how-to-upload-photo/ are correct.

**Comment by jbalboni** [comment]
@peggygannon Nothing specifically needs review, just wanted you to be aware. When this is merged, the content pages will go live in the next deployment.

**Review by rianfowler — APPROVED** [review]

**Review by cehsu — APPROVED** [review]
LGTM.

**Comment by jkassemi** [comment]
@jbalboni expecting some build changes as a result of brand consolidation that might make this easier to just redo and open again later. Also trying to cut down on open PRs. 

How do you feel about closing this out?

**Comment by jbalboni** [comment]
I feel like VIC v2 is basically dead anyway, so closing seems fine

**Comment by jkassemi** [comment]
😞

**Pull request closed without merging**
