### PR TITLE
CT 116: Add VETTEC Providers to the Comparison Tool Search Results #19101 #19228

### PR DESCRIPTION
**Pull request by zurbergram**
## Description
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19101
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19228

As a Comparison Tool user, I need to be able to review VETTEC Providers if program data is unavailable so that I can review the potential benefits of using the VETTEC program.

As a comparison tool user, I need the landing page to not ask the "How do you want to take classes?" question so that I am able to see results while the providers are still limited.

## Assumptions
1. This story is to cover displaying ONLY provider related information.  Displaying program information will be covered in a future story once the data format / data is available.
2. This work will be behind a flag so that it is only available in the staging environment and below.
3. The VET TEC Refine Search functionality (AC #3, #4, #5) filters search results in the same manner as Standard Search Results. If different, leave a comment so the story can be updated.
4. "Filter By" on the wireframe will be covered by another story if necessary.

## Screenshots
Screen Shot 2019-07-11 at 12 33 36 PM
Screen Shot 2019-07-11 at 2 04 57 PM
Screen Shot 2019-07-11 at 2 05 04 PM
Screen Shot 2019-07-11 at 2 05 11 PM
Screen Shot 2019-07-11 at 2 05 21 PM

## Acceptance criteria
- [ ] The VET TEC Search Results only displays VET TEC Programs / Providers
- [ ] The search results can be refined using the following criteria:
     a. City, school, or training provider
     b. Country
     c. State
     d. Learning Format
- [ ] The "City, school, or training provider" field is a free text search.
     a. The Results are filtered using the same mechanism as on the Traditional Search Results Page.
- [ ] The "Country" is a dropdown list
     a. The values in the dropdown are limited to the Countries of the providers returned by the Search Results.
- [ ] The "State" is a dropdown list
     a. The values in the dropdown are limited to the States of the providers returned by the Search Results.
- [ ] "Learning Format" allows the user to filter by:
	a. In person
	b. Online
- [ ] The search results will display a list of Providers that meet the search criteria with the following data:
	a. Provider Name
	b. Provider City, State
	c. Tuition
	d. Housing
	e. A link to the VET TEC Provider profile page
- [ ] The "Housing" value displayed is based on the "Learning Format" selection:
	a. If both values are selected, it will show the range of housing available $[online DOD rate (1/2 DOD National Average)] - $[dod zip code housing rate].
	b. If no value is selected, it will show the range of housing available $[online DOD rate (1/2 DOD National Average)] - $[dod zip code housing rate].
	c. If "Online" is selected, it will display the $[online DOD rate (1/2 DOD National Average)].
	d. If "In person" is selected, it will display the $[DOD zip code housing rate]
- [ ] On the Landing Page the question "How do you want to take classes?" and the corresponding answers are not available when the answer to the type of institution question is "VET TEC providers".
- [ ] On the Landing Page the question "How do you want to take classes?" and the corresponding answers are available when the answer to the type of institution question is not "VET TEC providers".
- [ ] On the Landing Page the question "How do you want to take classes?" and the corresponding answers are available when the answer to the "Which GI Bill benefit do you want to use?" question is not "Post-9/11 GI Bill (Ch 33)".

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by zurbergram** [comment]
branch is based off of work done in https://github.com/department-of-veterans-affairs/vets-website/pull/10363

Cannot be merged until after https://github.com/department-of-veterans-affairs/vets-website/pull/10363

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Comment by zurbergram** [comment]
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!

**Review by rianfowler — APPROVED** [review]

**Comment by rianfowler** [comment]
Thanks for doing these refactors- good stuff!

**Review by sonntag-adam — APPROVED** [review]

**Review by delli-gatti-michael — APPROVED** [review]
Passes QA

**Pull request merged**
