### PR TITLE
Updates review instance deployment job name

### PR DESCRIPTION
**Pull request by jkassemi**
For deployment alongside https://github.com/department-of-veterans-affairs/devops/pull/1561, which introduces a new name.

### CODE REVIEW

**Review by knkski — APPROVED** [review]
👍

**Comment by ayaleloehr** [comment]
@jkassemi should this get in or is it waiting on something?

**Comment by ayaleloehr** [comment]
pinging @jkassemi

**Comment by jkassemi** [comment]
Nope, it's good to go in.

**Pull request merged**
