### PR TITLE
Adds healthcare card to vets.gov homepage

### PR DESCRIPTION
**Pull request by crwallace**
DO NOT MERGE UNTIL WE RECEIVE APPROVAL FROM @staceylanger.

### CODE REVIEW

**Comment by staceylanger** [comment]
Do we have a defined style for healthcare? Is it "Healthcare" or "Health Care" or "Health care"? @maryannbrody @crwallace

**Comment by bethpotts** [comment]
Just noticed this conversation, and thought I'd chime in @staceylanger @maryannbrody @crwallace Vets.gov style for this, which is in line with the VHA style guide, is two words, lowercased (unless it is the proper name of a VA medical center). I also added to our style guide another level of detail that VHA does not include: when "health care" precedes and modifies a noun, it is hyphenated.

**Comment by bethpotts** [comment]
@staceylanger @maryannbrody @crwallace Now that I've put it out there, I sheepishly retract my initial thoughts about using the hyphen. I actually don't think it is necessary to hyphenate "health care" when it modifies a noun (as in "health care system" and "health care benefits"). I looked around va.gov--where it is not hyphenated in this form--and it looks fine open. There is little risk of confusion without the hyphen because it is such a common term.

**Comment by webinista** [comment]
LGTM. Merge whenever. (Assuming the branch is up-to-date and all of the tests pass, natch.)

**Pull request merged**
