### PR TITLE
Fl additions

### PR DESCRIPTION
**Pull request by bshyong**
Various bug fixes

### CODE REVIEW

**Review by crwallace — APPROVED** [review]
This looks good to me with one question for @staceylanger and @NatalieEMoore.

**Comment by NatalieEMoore** [comment]
@patrickvinograd does the data include facilities in other countries like Germany?

**Comment by patrickvinograd** [comment]
Based on state codes that aren't US states, I see:
- VBA facilities in Puerto Rico, US Virgin Islands, Guam, and Philippines
- VHA facilities in American Samoa, Guam, Northern Mariana Islands, Philippines, and US Virgin Islands
- NCA facilities in Puerto Rico

**Comment by NatalieEMoore** [comment]
Working with stakeholders (re @staceylanger  request) to confirm.   So far:

NCA-Puerto Rico only

**Comment by bshyong** [comment]
closing deprecated PR

**Pull request closed without merging**
