### PR TITLE
[WIP] update diseases.md

### PR DESCRIPTION
**Pull request by peggygannon**

### CODE REVIEW

**Comment by jcmeloni-usds** [comment]
@rroueche Can you help with either merging or abandoning this PR? Thanks!

**Comment by rroueche** [comment]
Sure! I'll start looking into this, @bethpotts do you know what this is/was for? It pertains to this page: https://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/diseases/.

If we don't need it I can delete the PR and the associated branch. Let me know what you think!

**Comment by rroueche** [comment]
@maryannbrody and @bethpotts wondering if we can close this and delete the branch, or if we need to save the updates for later, or if we can take 'em live. See comments above. Let me know!

**Comment by rroueche** [comment]
I looked at the Files Changed and believe this is obsolete. I'm deleting this PR and branch.

**Pull request closed without merging**
