### PR TITLE
Disability date update 10 2

### PR DESCRIPTION
**Pull request by DanielleSoCompany**

### CODE REVIEW

**Comment by DanielleSoCompany** [comment]
Hi @bethpotts. This is ready for your review!

**Review by bethpotts — APPROVED** [review]
Approved!

**Comment by DanielleSoCompany** [comment]
@phiden @robertfairhead @robbiethegeek Could one of you please merge this PR today? Thank you!

**Review by robbiethegeek-usds — APPROVED** [review]

**Comment by DanielleSoCompany** [comment]
Thank you @robbiethegeek!!

**Pull request merged**
