### PR TITLE
59319 unorder lists

### PR DESCRIPTION
**Pull request by lee-delarm6**
## Summary

Changing ordered lists to unordered lists, this should have zero to minimal impact. Discovered one area did not display list icons (so no change) and other area likely didn't either.

## Related issue(s)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/59306

## Testing done

Verified old and new styles match, no other changes done except removing ol and replacing with ul, changed stylesheet to match
 
## Screenshots

Screenshot 2023-06-16 at 2 08 03 PM

Screenshot 2023-06-16 at 2 09 27 PM

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

Should be no impact, touching on displaying check-in lists for appointments

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### CODE REVIEW

**Review by brianseek — APPROVED** [review]
LGTM! nice work!

**Review by brianseek — CHANGES_REQUESTED** [review]
Looks like I jumped the gun. Some fixes needed in cypress tests

**Comment by lee-delarm6** [comment]
> Looks like I jumped the gun. Some fixes needed in cypress tests

Fixed the test, it was using a single defined component with ol[etcetcetc, changed to ul[etcetcetc

**Review by brianseek — APPROVED** [review]
Looks great!

**Pull request merged**
