### PR TITLE
Accessibility updates for sign-in page and modal

### LINKED ISSUE #7767: Standalone sign in page: Implement front-end changes per accessibility guidance
Per #6945, implement front-end changes outlined in Jennifer Strickland's accessibility review. [20200405-SSO-specs.pdf](https://app.zenhub.com/files/133843125/c9851baa-7aa1-4d90-9d10-53f57c7e9327/download)

Also apply changes as appropriate to the sign-put page.

### PR DESCRIPTION
**Pull request by hinzed1127**
## Description

This adds a11y fixes recommended by @jenstrickland

Close department-of-veterans-affairs/va.gov-team#7767

## Testing done

Visual verification of parity in appearance between the updates and existing pages/components

## Screenshots
Compare https://staging.va.gov/sign-in/ and the sign-in modal with the review instance. Other than negligible differences with "A secure account powered by ID.me" (line height differences not worth changing), appearance should be the same

## Acceptance criteria
- [ ] Pages/Components look the same with the requested a11y fixes

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by hinzed1127** [comment]
@jenstrickland the only recommendation I didn't end up adding from your report was wrapping the "One site. A lifetime of benefits and services at your fingertips" `h2` in a `<div class="va-introtext" >`. From what I could tell, that class adds some base styles that were already being applied elsewhere.

**Comment by jenstrickland** [comment]
> @jenstrickland the only recommendation I didn't end up adding from your report was wrapping the "One site. A lifetime of benefits and services at your fingertips" `h2` in a `<div class="va-introtext" >`. From what I could tell, that class adds some base styles that were already being applied elsewhere.

Having it be an `h2` is important. The styling only serves sighted users, but the heading tag provides screen readers, translation users, and other assistive tech the content hierarchy in non-visual ways.

**Comment by hinzed1127** [comment]
> Having it be an h2 is important.

I updated that, too, but looks like I forgot it in the modal. Should be fixed now!

**Review by ericbuckley — APPROVED** [review]

**Comment by jhonnyoddball** [comment]
cc @1Copenut

**Review by patrickvinograd — APPROVED** [review]
Not an accessibility expert but nothing here look problematic to me.

**Review by jhonny218 — APPROVED** [review]

**Review by 1Copenut — APPROVED** [review]
LGTM. The images have a `role` and `aria-hidden` attributes, so they have the same non-semantic value as `alt=""`, which is what we want.

**Pull request merged**
