### PR TITLE
Enables automatic refresh for Sign in Service

### LINKED ISSUE #50387: [Refactor] Fix Sign in Service Refresh
## Description
This will fix the way the `/refresh` functionality works.

## Tasks
- [x] Implement `fetch-retry` for OAuth only when the Access token is expired
- [x] Use unit tests & manual tests to verify functionality

### PR DESCRIPTION
**Pull request by asg5704**
## Summary

*(Summarize the changes that have been made to the platform)*
> This PR modifies the platform/utilities/api/index.js file to provide automatic refreshing of Access Tokens using the `fetch-retry` package

*(What is the solution, why is this the solution)*
> The solution was to add the `fetch-retry` package and use one of their built in methods `retryOn` with logic to conditionally send a fetch request to the `/refresh` endpoint if the `apiRequest` JSON ever comes back as `Access token has expired` (since we don't want it for every 403)

*(Which team do you work for, does your team own the maintainence of this component?)*
> Identity. No (shared functionality)

*(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)*
> While this piece of work doesn't necessarily use a Flipper flag, the `sign_in_service_enabled` flag determines if a user is signed in via the Sign in Service (aka OAuth).
> Currently the Sign in Service is enabled in the Staging & Dev environments.

## Related issue(s)
*Link to ticket created in va.gov-team repo*
> Closes department-of-veterans-affairs/va.gov-team#50387

*Link to epic if not included in ticket*
> References department-of-veterans-affairs/va.gov-team#48711

## Testing done

*Describe what the old behavior was prior to the change*
*Describe the steps required to verify your changes are working as expected*
> 1. Login as any user using the Sign in Service (aka ensure `oauth=true` with the Sign in Modal).
> 2. After authentication you should land on the `/my-va` page. Do not navigate away from that page!
> 3. Open up the Developer Tools > Local Storage and view the `atExpires` key & value pair. (The time should be 5 minutes from when the access token was issued)
> 4. In the Developer Tools > Network tab. Clear all the current requests in there and ensure the `Preserve log` option is checked.
> 5. After the `atExpires` time elapses, navigate to the `/profile` page using the link on the `/my-va` page.  The network tab should have some failing 403s (example is `/mhv_accounts` and `/user`).
> 6. Verify the `/user` (or any other 403) has a response of `Access token has expired`. For each 403 with this response there should be a `/refresh` call
> 7. Verify after the `/refresh` call is made, the user is still signed in and the previously failed `403: Access token has expired` are called with a `200`

*Describe the tests completed and the results*
> Manual testing + unit tests + E2E tests are all passing.

## Screenshots
_Note: This field is mandatory for component work and UI changes (non-component work should NOT have screenshots)._
> n/a

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*
> This impacts the entire SITE.  Please tests as you see fit for your application/portion of code.

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [x]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

> This impacts the entire SITE.  Please tests as you see fit for your applications / portion of the site.  I will not merge this code until a 80% majority gives the go ahead.

### CODE REVIEW

**Review by it-harrison — APPROVED** [review]

**Comment by AGarcia-Clarity** [comment]
@data-doge @simiadebowale @Mottie I would appreciate feedback to ensure VAOS, CoE, Save in Progress forms work with the Sign in Service (OAuth).  Thank you

**Review by Mottie — APPROVED** [review]
Looks good for Claim Status Tool changes

**Comment by data-doge** [comment]
Hey @AGarcia-Clarity, thank you! I'll make sure to have a look at this today.

**Review by data-doge — APPROVED** [review]
Wonderful! Works on COE. Thank you!

**Comment by simiadebowale** [comment]
@AGarcia-Clarity - no VAOS files were directly changed but this LGTM

**Review by jamigibbs — APPROVED** [review]
I'm not sure which part of this requires the design system team to review but approving so as not to block progress here.

**Comment by AGarcia-Clarity** [comment]
@simiadebowale no VAOS files are directly affected, but I want to ensure functionality and that this https://github.com/department-of-veterans-affairs/va.gov-team/issues/50013 is no longer an issue with this PR.

**Comment by simiadebowale** [comment]
> @simiadebowale no VAOS files are directly affected, but I want to ensure functionality and that this [department-of-veterans-affairs/va.gov-team#50013](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50013) is no longer an issue with this PR.

Agreed. However, the RI is outdated so I can't do any e2e testing for vaos.

**Comment by simiadebowale** [comment]
> @simiadebowale no VAOS files are directly affected, but I want to ensure functionality and that this [department-of-veterans-affairs/va.gov-team#50013](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50013) is no longer an issue with this PR.

**Comment by adamwhitlock1** [comment]
The RI is hanging when I click on Id.me in the login modal, so couldn't try this, but overall the code looks good.

**Review by adamwhitlock1 — APPROVED** [review]

**Comment by AGarcia-Clarity** [comment]
> The RI is hanging when I click on Id.me in the login modal, so couldn't try this, but overall the code looks good.

👋  @adamwhitlock1 what is the RI? 👀

**Comment by AGarcia-Clarity** [comment]
@simiadebowale Thank you for the clarification.  Let me talk with my Backend engineer as I'm not sure if Sign in Service (OAuth) is working for Review Instances.  I'll keep y'all updated.

**Comment by simiadebowale** [comment]
@AGarcia-Clarity - I was testing this more in the review instance. After a period of inactivity, I'm still seeing 'User Access Token Expired' error messages while using vaos

**Comment by AGarcia-Clarity** [comment]
@simiadebowale Can you provide a step-by-step in order for me to reproduce it?  There should still be the 'User Access Token is Expired' but there should be other calls. One to the `/refresh` route to get new Access Tokens, and the other should replay the original VAOS calls.

**Comment by ryanshaw** [comment]
@asg5704 We are still experiencing this issue within the VAOS application on staging. After a period of inactivity, the user's token expires. I am not seeing any calls around the token expiration to the `/refresh` endpoint. Is there something we need to look for or enable within VAOS to ensure this functionality works there?

Here's the [issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50013) where we are tracking it.

**Comment by asg5704** [comment]
@ryanshaw Yes, there was a bug with the automatic refresh that impacted both the MHV Secure Messaging team & Letter Downloads from occuring on production. (See https://github.com/department-of-veterans-affairs/va.gov-team/issues/53001). There was a decision to rollback, so automatic refresh is currently broken for staging & below for OAuth (you still are able to login via SSOe with `oauth=false` in the query parameter). 

[The new automatic refresh PR](https://github.com/department-of-veterans-affairs/vets-website/pull/23263) should help resolve the issue but I need all VFS teams & teams with applications on vets-website to QA the above Pull Request before rolling out.  While the PR is scoped to staging & below and won't be released to Production, I'd rather have more eyes on it.

**Comment by ryanshaw** [comment]
@asg5704 Thanks for the quick response! I'll share out with the team.

**Comment by asg5704** [comment]
Thank you for sharing with your team @ryanshaw. I'm planning on putting out a message in the vfs-frontend & vfs-all-teams channels.

**Pull request merged**
