### PR TITLE
Skip visibility check by default

### PR DESCRIPTION
**Pull request by jbalboni**
## Description
Skips React Testing Library's visibility check when using ByRole queries

Appears to take around 90s off of the unit test suite.

## Testing done
Unit testing

## Acceptance criteria
- [ ] Tests pass

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by jbalboni** [comment]
FYI @erikphansen

**Comment by erikphansen** [comment]
@jbalboni I've been running this locally and sometimes the tests pass, but I'm getting lots of runs where tests fail and the issue seems to stem from `msw` not working correctly. Which doesn't make a lot of sense given the one change you made in this PR.

Can you try running the entire suite with seed `byToFL7ocu` to confirm you also get 4 failures?

**Comment by erikphansen** [comment]
@jbalboni oh lucky day! This seed results in a single VAOS test failure in case you want to investigate 😆  `grMaG7BCLK`

**Comment by erikphansen** [comment]
@jbalboni sorry for all the comments here. I don't even know what's going on with this branch as I run it locally. I started fresh and tried running the entire suite with `byToFL7ocu` and the only failure was a VAOS test compared to the four failures I got before. And sometimes I can run just `src/applications/personalization/profile/tests/components/alerts/Profile.data-unavailable-error.unit.spec.js` and it'll have a failure once but then it'll pass the next time, even with the same seed. I tried upgrading `msw` since some of the failures seem to be due to that, but I still have problems. So right now I'm just getting very weird and inconsistent behavior.

**Comment by jbalboni** [comment]
@erikphansen I wonder if by reducing the time ByRole takes, maybe that's revealed some tests that aren't properly waiting for something to happen? I've seen that before when making global changes.

**Comment by erikphansen** [comment]
@jbalboni yes this could be revealing a real issue with the way some of my tests are written. If I could get the runs to fail consistently it'd be easier to figure out what's going on 😆  

The two things I've seen have been:
1. a loading spinner is supposed to be removed but it never is, which points to `msw` not returning a response and the app just hanging while it waits for data. (https://github.com/department-of-veterans-affairs/vets-website/blob/f4899068643c8f17bc8a6f920e0c2fea31500ed9/src/applications/personalization/profile/tests/components/alerts/Profile.data-unavailable-error.unit.spec.js#L105)
2. an error message never shows up when an update fails, which also points to `msw` not returning a response. I don't the offending line of code handy for this case.

I'm going to keep looking into this. This config option definitely speeds things up. And hopefully I'll learn something by trying to get to the bottom of things.

**Comment by erikphansen** [comment]
@jbalboni I was running into two different failures when running the full suite locally. The first I fixed by setting up two additional `msw` mocks for APIs the Profile calls on load. Causing those calls to fail fast fixed an issue where a loading spinner was still showing when the test expected it to be removed. The second issue was much stranger. In some runs, `userEvent.type()` wasn't working correctly. I have a test where two text fields are filled in sequentially. Sometimes only the first of 9 characters was entered in the first field before it moved on to the second field, where it would enter the remaining 8 characters that were supposed to go into the first field. Super, super weird but it would always happen with a certain choma seed. And it didn't seem like your `defaultHidden` change was the cause. I "fixed" it by changing the order in which the fields are filled out. This is a very unsatisfying "fix" to something that feels like a `user-event` bug. I tried upgrading the `user-event` package and that introduced an even worse bug :( I wonder if our usage of mocha or our JSDOM config has anything to do with this since I didn't see anyone else reporting the same problem. I'm still seeing some tests fail randomly when running the full suite, but that's par for the course :(

**Review by erikphansen — APPROVED** [review]

**Comment by jbalboni** [comment]
@erikphansen Thanks for looking into those failures. We have a VAOS test where userEvent.type() just [doesn't work correctly](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/tests/new-appointment/components/ContactInfoPage.unit.spec.jsx#L25) on a particular test order, too. I couldn't figure out why, but switching to `fireEvent.change()` fixed it. It feels like a JSDOM/environment issue like you mentioned, but I didn't come up with anything.

**Review by micahchiang — APPROVED** [review]

**Review by LeKeve — APPROVED** [review]

**Review by jhonny218 — APPROVED** [review]
LGTM

**Review by vbahinwillit — COMMENTED** [review]
LGTM

**Pull request merged**
