### PR TITLE
Making alert button background color transparent.

### PR DESCRIPTION
**Pull request by webinista**

### CODE REVIEW

**Comment by U-DON** [comment]
LGTM. The close icon looks a little big compared to the alert icon, but not sure what sizes they should be.

**Comment by webinista** [comment]
Yeah, I'm not clear on that either TBH. 

@melwoodard @gnakm How should these alert messages look relative to the warning messages?

**Comment by gnakm** [comment]
@webinista It should follow USWDS. https://standards.usa.gov/accordions/
It looks like they use svg and png there (402x402). 
@melwoodard  and I just discussed this. Since IE does not read font awesome, we may have to start change icons to svg. 

Just put the files in the assets folder. Could somebody merge?
https://github.com/department-of-veterans-affairs/vets-website/pull/4151

**Comment by webinista** [comment]
@gnakm I just want to double check that this alert should follow USWDS and not the [modified the disclaimer layout](https://github.com/department-of-veterans-affairs/kudos-team/issues/269). 

I think the problem with IE and FontAwesome is due to our use of a base64 encoded SVG font in our CSS file, not FontAwesome itself. See department-of-veterans-affairs/vets-website#3266.

**Comment by melwoodard** [comment]
@webinista @gnakm this should follow the modified layout [here](https://github.com/department-of-veterans-affairs/vets.gov-designpattrns/issues/28), not the USWDS default. We want to begin using the modified style across the board.

**Pull request merged**
