### PR TITLE
Migrate React Table component to web component

### PR DESCRIPTION
**Pull request by jamigibbs**
## Summary

This PR replaces any remaining deprecated `Table` React components with the `va-table` web component: https://design.va.gov/storybook/?path=/docs/components-va-table--default

## Related issue(s)

related https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1658

## Testing done

Local
E2E and Unit tests passing

## What areas of the site does it impact?

The following apps:
- disability-benefits
- medical-copays
- messages

## va-payments app

**Before (React)**

| React | Web Component |
| ------ | ----- |
|   01-react   |    01-web-component   |
|   02-react   |   02-web-component    |

## medical-copays

I don't think the app component `PaymentHistoryTable.jsx` is actually being used anywhere (I could not find any reference of it being imported anywhere) so I wasn't able to visually check but all tests are passing after converting.

`StatementCharges.jsx`:

| React | Web Component |
| ------ | ----- |
|  Screenshot 2023-06-06 at 12 08 58 PM |   Screenshot 2023-06-06 at 12 03 48 PM |

Screenshot 2023-06-06 at 12 04 17 PM

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by jerekshoe** [comment]
@jamigibbs One thing to watch out for is that the row styling doesn't get preserved when you move between pages
Screenshot 2023-06-06 at 2 16 33 PM
This issue was the reason this component hasn't been migrated yet.

**Comment by jamigibbs** [comment]
> @jamigibbs One thing to watch out for is that the row styling doesn't get preserved when you move between pages This issue was the reason this component hasn't been migrated yet.

Hi @jerekshoe! Thanks for the head's up. Has there been an issue logged about this yet for DST? I searched [the backlog](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues) but didn't seen any pending issue for va-table (otherwise we would fix those first before deprecating).

**Comment by jerekshoe** [comment]
> > @jamigibbs One thing to watch out for is that the row styling doesn't get preserved when you move between pages This issue was the reason this component hasn't been migrated yet.
> 
> Hi @jerekshoe! Thanks for the head's up. Has there been an issue logged about this yet for DST? I searched [the backlog](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues) but didn't seen any pending issue for va-table (otherwise we would fix those first before deprecating).

Not that I'm aware of. I made a PR to the component-library repo [here](https://github.com/department-of-veterans-affairs/component-library/pull/408) and making a ticket was brought up, but it looks like there was never a decision made to create a ticket

**Comment by jamigibbs** [comment]
> Not that I'm aware of. I made a PR to the component-library repo https://github.com/department-of-veterans-affairs/component-library/pull/408 and making a ticket was brought up, but it looks like there was never a decision made to actually do it

Thank you! I created an issue for this. If there's anything you think that hasn't been captured, please feel free to add more details: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1821

We will need to fix this before deprecating so I'm going to close this PR for now.

**Pull request closed without merging**
