### PR TITLE
Fix platform alias - ae

### PR DESCRIPTION
**Pull request by jhonny218**
## Description

`va/use-resolved-path` rule from the `va custom plugin` has been added to the testing stage in CircleCI (`circle.esint.json`).

The purpose of this rule is to resolve the path to use the existing aliases generated in babel.

In this case we are removing all instances containing `../` from the `platform` alias.

This change should help the code to be in compliance with the rule and removes the errors from `additional-linting` CircleCI check.

### Authenticated Experience
src/applications/personalization => 18
src/platform/user/profile/vet360 => 0
Total errors fixed: 18

## Testing done
Locally

## Screenshots

Screen Shot 2020-04-22 at 9 16 42 AM

## Acceptance criteria
- [x] Remove all `../platform/` instances

### CODE REVIEW

**Comment by erikphansen** [comment]
This just looks like a massive (and mysterious) diff to the yarn.lock and nothing else?

**Comment by jhonnyoddball** [comment]
I changed my custom eslint plugin and had to revert all my changes. I'm currently working on it and will push all changes soon

**Comment by jhonnyoddball** [comment]
@erikphansen The changes are good to go. Thank you!

**Review by ncksllvn — APPROVED** [review]
There are still `yarn.lock` changes but otherwise LGTM

**Pull request merged**
