### PR TITLE
Add title + description to manifest.json

### PR DESCRIPTION
**Pull request by kelsonic**
## Description
**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/8642

This PR has an incredible ticket number if you're into `evens`. Aside from that, this PR adds a title + description to the YR manifest.json file.

## Testing done
N/A

## Screenshots
N/A

## Acceptance criteria
- [x] Add title + description

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by kelsonic** [comment]
@department-of-veterans-affairs/frontend-review-group ready for review! 🎉

**Review by ncksllvn — APPROVED** [review]

**Review by theodur — COMMENTED** [review]
I noticed that `src/applications/yellow-ribbon/manifest.json` wasn't updated in this

**Comment by kelsonic** [comment]
The original implementation would have been to update `manifest.json` but I believe @cvalarida sent up a PR recently that moved most of the content in manfest.json to `registry.json`.

**Comment by theodur** [comment]
Right that was done in https://github.com/department-of-veterans-affairs/vets-website/pull/12367. I believe the `manifest.json` isn't completely deprecated yet so I don't know if it makes sense to still have consistency between `registry.json` and the manifest files? @cvalarida

**Comment by kelsonic** [comment]
@department-of-veterans-affairs/frontend-review-group ready for review! 🎉

**Review by theodur — APPROVED** [review]

**Pull request merged**
