### PR TITLE
dont auto logout the user if we dont have a response from keepalive

### LINKED ISSUE #11973: user is auto logged out if immediately redirected after login
If the user needs to be immediately redirected to another page after login, they could be auto logged out after doing so.

The call to `/keepalive` will return an empty response if a network error occurs, this is possible if the user is redirected to a new page before the XHR response is returned http://sentry.vfs.va.gov/vets-gov/website-staging/issues/108541

In this case the `transactionid` will be undefined and [won't match the value the user logged in with](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/utilities/sso/index.js#L47).

### PR DESCRIPTION
**Pull request by ericbuckley**
fixes https://github.com/department-of-veterans-affairs/va.gov-team/issues/11973

### CODE REVIEW

**Comment by ericbuckley** [comment]
@hinzed1127 do you think we should update the logic to prevent AutoSSO from rendering if there is a `?next=` query param and the user is logged in? https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/user-nav/containers/AutoSSO.jsx#L26-L29

**Review by patrickvinograd — APPROVED** [review]
LGTM

**Review by hinzed1127 — APPROVED** [review]
@ericbuckley it looks like the `?next` logic is only ever followed when the [user is known to be logged in](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/user-nav/containers/Main.jsx#L44), so I think if we just include "next=" in the bad paths of AutoSSO (does that feel like it's specific enough?), that would avoid unnecessary keep-alive calls. That feels like an improvement more than required, imo

**Comment by ericbuckley** [comment]
> @ericbuckley it looks like the `?next` logic is only ever followed when the [user is known to be logged in](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/user-nav/containers/Main.jsx#L44), so I think if we just include "next=" in the bad paths of AutoSSO (does that feel like it's specific enough?), that would avoid unnecessary keep-alive calls. That feels like an improvement more than required, imo

If an unauthenticated user goes to https://staging.va.gov/track-claims, they will be immediately redirected to https://staging.va.gov/?next=%2Ftrack-claims.  So in that case we may still want the auto login code to run.

**Review by rianfowler — APPROVED** [review]

**Review by Clark-W-Griswold — APPROVED** [review]
👍

**Pull request merged**
