### PR TITLE
Removed having residential address contraint for display of cc language page

### PR DESCRIPTION
**Pull request by vbahinwillit**
## Description
This PR removes having residential address contraint for display of cc language page

## Original issue(s)
department-of-veterans-affairs/va.gov-team#32294

## Testing done
Unit testing

## Screenshots
N/A

## Acceptance criteria
- [ ] All test should pass

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by grossb1 — APPROVED** [review]
LGTM

**Comment by jenniemc** [comment]
@vbahinwillit, i'm trying to remove the residential address in order to test this branch locally. Where is the mock setup where I can remove the address?

**Comment by vbahinwillit** [comment]
./vets-website/src/platform/user/profile/vap-svc/util/local-vapsvc.js

```
export const mockContactInformation = {
residentialAddress: {
    // Delete this
    addressLine1: 'PSC 808 Box 37',
    addressLine2: null,
    addressLine3: null,
    addressPou: 'RESIDENCE/CHOICE',
    addressType: 'OVERSEAS MILITARY',
    city: 'FPO',
    countryName: 'United States',
    countryCodeFips: 'US',
    countryCodeIso2: 'US',
    countryCodeIso3: 'USA',
    latitude: 37.5615,
    longitude: -121.9988,
    createdAt: '2018-04-21T20:09:50Z',
    effectiveEndDate: '2018-04-21T20:09:50Z',
    effectiveStartDate: '2018-04-21T20:09:50Z',
    id: 124,
    internationalPostalCode: '54321',
    province: 'string',
    sourceDate: '2018-04-21T20:09:50Z',
    stateCode: 'AE',
    updatedAt: '2018-04-21T20:09:50Z',
    zipCode: '09618',
    zipCodeSuffix: '1234',
  },
}
```

**Review by jenniemc — APPROVED** [review]
LGTM!

**Pull request merged**
