### PR TITLE
Bugfixes for identity

### PR DESCRIPTION
**Pull request by bshyong**
Ensures DS Logon on verify page triggers DSlogon flow

Resolves https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5054
Resolves https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5058

### CODE REVIEW

**Comment by bshyong** [comment]
@U-DON if you can get review and merge this one into `kudos-identity` before we merge to master

**Review by U-DON — APPROVED** [review]
LGTM. Seeing more and more of a case for Verify to be its own container, but still something to refactor later.

By the way, does Verify need to get `login` and `handleLogin` passed in from RequiredLoginView as well?

**Comment by bshyong** [comment]
Good catch yes I will add that.

**Comment by bshyong** [comment]
Interestingly enough Verify started out as a separate container, then I refactored into a component, now it probably makes more sense as its own container again. We can discuss when we're ready to refactor.

**Pull request merged**
