### PR TITLE
Added handling for required address parts and zip formatting.

### PR DESCRIPTION
**Pull request by brianseek**
## Description
Updated address block component to make sure address has required fields. Also updated Zip formatting to only display 5 digits.

## Original issue(s)
[department-of-veterans-affairs/va.gov-team#31794](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/31794)

[department-of-veterans-affairs/va.gov-team#31811](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/31811)

## Testing done
Updated unit tests to pass long zip and test each part of a missing address.

## Acceptance criteria
- [ ] Passes Accessibility checks using axe
- [ ]  Deployed to staging.
- [ ]  Designer has signed off on the feature
- [ ]  Product team has signed off on the feature

### CODE REVIEW

**Review by acrollet — APPROVED** [review]
Nice work! I see a couple of opportunities for streamlining but they're matters of taste, take or leave as you like. :-)

There's also a side quest accessibility question not introduced by your changes that I'm going to dig a little on...

One other question, have we validated the assumption that we should show only the first 5 digits of the zip with UX folks?

**Review by dcgoodwin2112 — APPROVED** [review]
These all look good to me.

**Review by acrollet — APPROVED** [review]
nice work! code looks good and check-in works correctly for me locally, formatting looks good:

Screen Shot 2021-10-22 at 12 26 00 PM

**Review by dcgoodwin2112 — APPROVED** [review]
Label case changes all look good to me.

**Pull request merged**
