### PR TITLE
74376 permissions page

### PR DESCRIPTION
**Pull request by cohnjesse**
Permission granted

## Summary

Since we know that we are going to need a permission page (or at least we bet we will) we should add the based page. This PR adds that page as well as refactors our breadcrumbs into a function that can be reused.

## Related issue(s)

https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/74376

## Testing done

Added basic smoke tests to ensure the page renders

## Screenshots

Screenshot 2024-02-29 at 12 14 35 PM

## What areas of the site does it impact?

Only our app, no external dependencies are affected

### CODE REVIEW

**Review by emily-gullo — CHANGES_REQUESTED** [review]
Couple of spots where the POA naming isn't consistent - I know we haven't picked one yet but we should probably at least keep them the same for now

**Review by williamphelps13 — CHANGES_REQUESTED** [review]
I accidentally sent through the switch case to object breadcrumb refactor on its own review comment earlier. Apologies for that. 

The acronym casing will be aligned in a closely following issue so I didn't discuss that at all.

Requesting some changes and then would love your thoughts on the Button documentation of when to use primary vs secondary buttons (brought up in my last comment).

**Review by williamphelps13 — DISMISSED** [review]
Approved and will re-approve after merge conflicts are resolved.

Some notes: 
1. As we progress further in our application, it would be helpful for reviewers, to have the scope of a PR mostly narrowed to the Zenhub issue at hand. For example, this issue is to add the Permissions page but only 4 of the 12 changed files are for this change. Breadcrumbs could and actually will be improved in the upcoming Layout issue and acronym fixing will be handled in the Acronym issue that has a PR open (but will now have many merge conflicts when this PR is merged because this PR changes to `POAPermissions` whereas the Acronym PR changes to `poaPermissions`).
2. There are a number of Lint errors viewable in the "Files changed" Github tab that would be good to get resolved before moving the PR out of draft mode.
3. It would be good to get in the habit of addressing agreed upon code problems that that were introduced with the review code resolved in the PR itself. As mentioned in the first note above, it actually feels not ideal to fix all problems in a space in a particular PR because many of the code problems are out of scope of the issue. However, code that is added with the PR that are agreed upon should be changed would be good to get addressed in that PR. For example, the issues around the breadcrumb test look like they will be solved in the Layout PR but in the meantime reviewers are needing to merge code that is knowingly not working. That not working pattern has the risk of being used as an example of our new practice by other engineers on the team (who are not involved in the particular review) before the subsequent fix PR is merged. 

These are of course just my thoughts, and I am definitely totally open for changing my thoughts on any of these points.

**Review by gabezurita — DISMISSED** [review]
LGTM! Agree with ➡️  https://github.com/department-of-veterans-affairs/vets-website/pull/28267#pullrequestreview-1920174312

**Review by emily-gullo — APPROVED** [review]

**Review by williamphelps13 — APPROVED** [review]

**Pull request merged**
