### PR TITLE
content/wip/track-your-claims-and-appeals

### PR DESCRIPTION
**Pull request by bethpotts**
Consistency across left nav, title of page, top nav, and Disability landing page.

### CODE REVIEW

**Comment by bethpotts** [comment]
@peggygannon Shooting for consistency across all locations. With this effort we are moving AWAY from:
"Check your claim and appeal status"

Instead, we're going with: "Track your claims and appeals"

**Review by peggygannon — APPROVED** [review]
@bethpotts LGTM. thanks

**Comment by jkassemi** [comment]
Is this good to merge?

**Comment by ncksllvn** [comment]
Hi there 👋 Because of the changes involved to meet the requirements of Brand Consolidation, this pull request is unfortunately incompatible with `vets-website` and is being closed as part of a post-launch clean-up effort. However, to make sure the intent of the work is not lost, we're collecting all relevant pull requests into https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15129 and will open a longstanding issue into https://github.com/department-of-veterans-affairs/vagov-content for the visibility of the content and product teams. Thank you and sorry for any inconvenience!

**Pull request closed without merging**
