### PR TITLE
Updates spacing around new join video appointment link

### PR DESCRIPTION
**Pull request by ryanshaw**
## Summary

Fixes spacing issues around join video appointment link on new appointment details page design within VAOS. This only updates styles/spacing.

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/88731#issuecomment-2266128982

## Testing done
- Local testing

## Screenshots

| Before | After |
| ------ | ----- |
|Screenshot 2024-08-06 at 6 17 22 AM|Screenshot 2024-08-06 at 6 18 12 AM|
|Screenshot 2024-08-06 at 6 20 04 AM|Screenshot 2024-08-06 at 6 22 01 AM|

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- Should show correct spcing

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [X] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Review by JunTaoLuo — COMMENTED** [review]
This fixes the spacing issues but what about the functionality faults that was found during validation?

**Comment by ryanshaw** [comment]
@JunTaoLuo There will be another PR.

**Review by JunTaoLuo — APPROVED** [review]
LGTM for spacing, will keep an eye out for the PR addressing other items.

**Review by jenniemc — APPROVED** [review]
LGTM!

**Pull request merged**
