### PR TITLE
Re-ordered options on VetTec search results page

### PR DESCRIPTION
**Pull request by NateJohnson-BAH**
## Description
As a comparison tool user, I need the VET TEC Search Results Page of the comparison tool to provide descriptive text and modal information so that I am not confused by the questions that I am answering.
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19335

## Testing done
Confirmed correct order in UI

## Screenshots
Screen Shot 2019-07-22 at 1 45 40 PM

## Acceptance criteria
- [x] The "Refine Search" criteria are displayed in the following order:
     "City, school, or training provider"
     "Country"
     "State"
     "Learning Format"

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by zurbergram — APPROVED** [review]
LGTM

**Review by sonntag-adam — APPROVED** [review]

**Comment by NateJohnson-BAH** [comment]
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!

**Review by cvalarida — APPROVED** [review]
Took me longer to figure out what the problem was than it did to approve the solution. :smile:

**Review by rianfowler — DISMISSED** [review]
Pending review by DSVA

**Comment by batemapf** [comment]
Reviewed by DSVA, this is good to go.

**Pull request merged**
