### PR TITLE
Feedback tool contact info

### PR DESCRIPTION
**Pull request by cehsu**
These changes set up the applicant contact information page for the feedback tool form. [Linked ticket](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11574).

localhost_3001_education_complaint-tool_form_contact-information 4

### CODE REVIEW

**Comment by cehsu** [comment]
@miamay345 Country can only have a value of "US" at present, does it make sense to display a country field? Or should we simply fill this in in the background?

**Review by peggygannon — CHANGES_REQUESTED** [review]
@cehsu Please see my edits below: 

Please replace "Complaint" with "Feedback" in the breadcrumb.

Please change "Zip code" to "Postal code", per the prototype

**Comment by cehsu** [comment]
Thanks @peggygannon, the ZIP -> postal update has been made. The breadcrumbs are not part of this PR, I'll note this on the PR where this change is made (https://github.com/department-of-veterans-affairs/vets-website/pull/8018), and once it is merged, the changes in this PR will only relate to the form fields.
localhost_3001_education_complaint-tool_form_contact-information 5

**Review by peggygannon — APPROVED** [review]
@ceshu Looks good. thanks...

**Comment by rianfowler** [comment]
I'm not able to fill the first email address field on this form. Clues:
- the error message on the field is **Please provide a response**
- no console error 
- when I paste an email address, it appears and then the input is cleared

No idea why this is happening- the schema looks right. It might have something to do with the email field on the previous page?

**Comment by cehsu** [comment]
Thanks @rianfowler, fixed by creating two separate properties: anonymousEmail and applicantEmail.

**Review by rianfowler — APPROVED** [review]
Works!

**Pull request merged**
