### PR TITLE
[CST] - Updated button components to use va web components (Second PR)

### PR DESCRIPTION
**Pull request by pmclaren19**
## Summary
Second PR for Button updates. I updated 4 different files!

- Updated claim-status.scss so that the headings in ClaimPhase.jsx didnt have a left padding that made it uneven with the description
- Removed ConsolidatedClaims.jsx since it is no longer being used and took the div `consolidatedClaimsContent` and added it directly to YourClaimsPageV2.jsx
- Updated the button component on ClaimSyncWarning.jsx to use va-button. 
- Updated the button component on UploadStatus.jsx to use va-button. Also updated tests.
- Updated the button components on AskVAPage.jsx to use va-button. Also updated cypress tests for TrackClaimsPage.js

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#75352

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| ClaimPhase.jsx | Screenshot 2024-02-22 at 11 39 22 AM | Screenshot 2024-02-22 at 11 39 45 AM |
| ClaimSyncWarning.jsx | Screenshot 2024-02-22 at 10 16 45 AM | Screenshot 2024-02-22 at 10 21 36 AM |
| UploadStatus.jsx | Screenshot 2024-02-22 at 12 27 56 PM |  Screenshot 2024-02-22 at 12 29 56 PM |
| AskVAPage.jsx | Screenshot 2024-02-22 at 1 49 35 PM | Screenshot 2024-02-22 at 1 54 43 PM |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by samcoforma — DISMISSED** [review]
LGTM

**Review by samcoforma — APPROVED** [review]

**Comment by pmclaren19** [comment]
@skylerschain this pr is ready for design qa.

**Comment by skylerschain** [comment]
LGTM 👍 

Only thing I noticed is that when the File is uploading the "X" doesn't seem to do anything when you click on it. See screen recording.

https://github.com/department-of-veterans-affairs/vets-website/assets/95102058/7e9c5061-1593-47a0-9ba8-3e75501ae03f

**Comment by pmclaren19** [comment]
> LGTM 👍
> 
> Only thing I noticed is that when the File is uploading the "X" doesn't seem to do anything when you click on it. See screen recording.
> 
>  Screen.Recording.2024-02-23.at.5.36.13.PM.mov

Hey @skylerschain, 
So I never changed the modal icon button (the 'x') I only updated the cancel button for the UploadStatus Modal. So it looks like that is a separate issue. I took a look at the va-modal and it looks like for some reason the modal has a icon button (the 'x') which my understanding is that it shouldnt...based off of what I see [here](https://design.va.gov/storybook/?path=/docs/uswds-va-modal--default). I'm thinking maybe this is something we can further investigate in another ticket?

**Pull request merged**
