### PR TITLE
Implement useGetReferralById with Referral Task Card

### LINKED ISSUE #97636: Implement single referral hook (useGetReferralById) for referraltaskCard component
Utilize the hook that is being used for the internal pages in the referral flow for task card.

Task
 - [ ] implement hook
 - [ ] update tests to use referral from fetch

### PR DESCRIPTION
**Pull request by juancstlm-a6**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Are you removing, renaming or moving a folder in this PR?
- [X] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

If the folder you changed contains a `manifest.json`, search for its `entryName` in the content-build [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) (the `entryName` there will match).

If an entry for this folder exists in content-build and you are:
1. **Deleting a folder**:
   1. First search `vets-website` for _all_ instances of the `entryName` in your `manifest.json` and remove them in a separate PR. Look particularly for references in `src/applications/static-pages/static-pages-entry.js` and `src/platform/forms/constants.js`. _**If you do not do this, other applications will break!**_
      - _Add the link to your merged vets-website PR here_
   2. Then, Delete the application entry in [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) and merge that PR **before** this one
      - _Add the link to your merged content-build PR here_

2. **Renaming or moving a folder**: Update the entry in the [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json), but do not merge it until your vets-website changes here are merged. The content-build PR must be merged immediately after your vets-website change is merged in to avoid CI errors with content-build (and Tugboat).

### :warning: TeamSites :warning:
Examples of a TeamSite: https://va.gov/health and https://benefits.va.gov/benefits/. This scenario is also referred to as the "injected" header and footer. You can reach out in the `#sitewide-public-websites` Slack channel for questions.

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

- Created `ReferralTaskCardWithReferral` that wraps `ReferralTaskCard` and utilizes the `useGetReferralById` hook to provide the task card with the referral from the hook.
- Updated tests

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#97636

## Testing done

- Prior task card used mock data directly
- Component now uses common hook for referral data

### Test Plan
GIVEN the `vaOnlineSchedulingCCDirectScheduling` feature flag is enabled 
WHEN I visit http://localhost:3001/my-health/appointments/?id=add2f0f4-a1ea-4dea-a504-a54ab57c6801
THEN I should see the Referral Task Card for the mock referral

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

- VAOS

## Acceptance criteria
 - [X] implement hook
 - [X] update tests to use referral from hook

### Quality Assurance & Testing

- [X] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [X] Linting warnings have been addressed
- [X] Documentation has been updated ([link to documentation](#) \*if necessary)
- [X] Screenshot of the developed feature is added
- [X] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [X] Browser console contains no warnings or errors.
- [X] Events are being sent to the appropriate logging solution
- [X] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [X] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Review by brianseek — DISMISSED** [review]
Nice work

**Comment by juancstlm-a6** [comment]
@ryanshaw This is ready for review. 
Here are a few test plans to check 
### Test Plan
GIVEN the `vaOnlineSchedulingCCDirectScheduling` feature flag is enabled 
WHEN I visit http://localhost:3001/my-health/appointments/?id=add2f0f4-a1ea-4dea-a504-a54ab57c6801
THEN I should see the Referral Task Card for the mock referral

GIVEN the `vaOnlineSchedulingCCDirectScheduling` feature flag is enabled 
WHEN I visit http://localhost:3001/my-health/appointments/?id=fake-id
THEN I should NOT see the Referral Task Card

**Review by brianseek — APPROVED** [review]
Looks good!

**Review by ryanshaw — APPROVED** [review]
LGTM 👍

**Pull request merged**
