### PR TITLE
GIBS QA fixes

### PR DESCRIPTION
**Pull request by annekainicUSDS**
Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3702

This fixes all the issues outlined in the above ticket except for 2:
1. For letters, address is in all caps: I believe this is something EVSS is going to fix on their side. Will follow up with them about that.
2. For GIBS, print page scrolling issues. While the scrolling is a bit odd for the print page, I wasn't able to reproduce the issues @phiden identified in the ticket. Might be useful to do a screenshare so I can see what Sophia is seeing.

### CODE REVIEW

**Review by raquelromano-gov — APPROVED** [review]
If you want to fix the all-caps stuff now so we don't have to think about it and remove later once EVSS fixes on their side, you can add `text-transform: capitalize;` (we do this already for the facility name)

**Comment by annekainicUSDS** [comment]
@raquelromano-gov hm, `text-transform: capitalize;` didn't work for me. I did some Googling and apparently `capitalize` only affects the first letters of each word. If the rest of the letters in the word are already capitalized, it won't make them lowercase. I don't think this is actually working elsewhere, at least what I can find. It looks like the data for service info (only other place in letters I see we're using `text-transform: capitalize;` is already coming in lowercase, so capitalize works in that case.

**Comment by raquelromano-gov** [comment]
Yeah, you first have to transform to lower case, then CSS will properly capitalize. We do this here: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/js/post-911-gib-status/components/EnrollmentPeriod.jsx#L86

**Comment by annekainicUSDS** [comment]
@raquelromano-gov ah gotcha, okay will do! Thanks!

**Comment by annekainicUSDS** [comment]
Messed up a rebase :/ Will reopen once I can merge this into master.

**Pull request closed without merging**
