### PR TITLE
[department-of-veterans-affairs/va-virtual-agent#464] Patch for Possible XSS

### PR DESCRIPTION
**Pull request by joehall-tw**
Wraps SSO call in an encodeURI call to satisfy Fortify scan alert to potential XSS vulnerability.

## Description

We're trying to pass a Fortify scan for the ATO reviewers, and the edited line of code was flagged by the scans as a possible XSS vulnerability. Wrapping the call in an encodeURI call satisfied the scan (as sanitized).

## Original issue(s)
department-of-veterans-affairs/va-virtual-agent#464

## Testing done
Tested in our environment using a localhost vets-api, vets-website on the latest builds. Login worked as expected. No difference to the user.

### CODE REVIEW

**Review by asg5704 — APPROVED** [review]
Would it be possibly to see the Fortify results/data?

**Comment by joehall-tw** [comment]
> Would it be possibly to see the Fortify results/data?

Yep. Once this is approved, I'll have a new report for you. If you'd prefer the on that called out the XSS vulnerability, I can send that as well. Or would you prefer me to attach to this PR?

**Comment by joehall-tw** [comment]
@AGarcia-Clarity, Here's the report that shows all the errors. This PR addressed the (potential) XSS vulnerability.

[VA SwA Code Validation Virtual Agent v1.0 2022-06-10 FAIL.pdf](https://github.com/department-of-veterans-affairs/vets-website/files/9001572/VA.SwA.Code.Validation.Virtual.Agent.v1.0.2022-06-10.FAIL.pdf)
.

**Comment by AGarcia-Clarity** [comment]
Awesome thanks for the information @joehall-tw

**Comment by joehall-tw** [comment]
We could view the findings in the audit workbench app via a Teams screen
share. Unless you have a Fortify scan results viewing app. Also, I think
the audit workbench has reports I can generate as well.

**Pull request merged**
