### PR TITLE
bradl3yC - 2429 - Add tabIndex to requested nodes

### PR DESCRIPTION
**Pull request by bradl3yC**
## Description
Add tabIndexs to specific nodes to allow them to be access via keyboard/tab

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by 1Copenut — CHANGES_REQUESTED** [review]
The implementation looks right, but I'm hesitant to be hard coding these values. We're going to start using an "On this page" anchor component a lot of places, so I think it'd be better to write this as a helper function:

```javascript
//  https://stackoverflow.com/a/49549464
const isIE = !!document.documentMode;

export const setTabIndex = el => {
  const target = document.getElementById(el);

  if (isIE) {
    target.setAttribute("tabindex", "-1");
  }
};

export const unsetTabIndex = el => {
  const target = document.getElementById(el);

  if (isIE) {
    target.removeAttribute("tabindex");
  }
};
```

You could then apply and remove the tabindex using lifecycle `componentDidMount()` and `componentWillUnmount()`. This feels more extensible and will serve us down the stretch.

/cc @rianfowler for visibility.

**Review by kelsonic — APPROVED** [review]
LGTM! 🎉It looks like we're hard coding `tabIndex` 26 times in `vets-website` atm, so perhaps @1Copenut we should make the `setTabIndex` and `unsetTabIndex` platform funcs in a separate ticket where we can address all of the `tabIndex`s in the codebase?

**Comment by 1Copenut** [comment]
@bradl3yC && @kelsonic Great point about hard coding tab indexes a number of times. I think it's the right call to create platform functions, and work through updating these at once, so we can properly attach QA time and energy since we're broadening scope. I'll add a platform ticket now, and update my comment.

Will also change my change request to approved and point to this comment.

**Comment by bradl3yC** [comment]
@department-of-veterans-affairs/frontend-review-group ready for review 👍

**Review by 1Copenut — APPROVED** [review]

**Comment by 1Copenut** [comment]
Added a related sitewide issue https://github.com/department-of-veterans-affairs/va.gov-team/issues/5125

**Review by jhonny218 — APPROVED** [review]
LGTM

**Pull request merged**
