### PR TITLE
Updating spanish translations

### PR DESCRIPTION
**Pull request by lee-delarm6**
## Summary

- Updating Spanish translations

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/67423
- The help section has been replaced with new text and needs all new updates

## Testing done

- Verified visually

## Screenshots

Screenshot 2023-10-13 at 2 54 32 PM
Screenshot 2023-10-13 at 2 49 41 PM

## What areas of the site does it impact?

- Translations areas

### CODE REVIEW

**Comment by brianseek** [comment]
@lee-delarm6 I went to look at the tickets to review these but didn't see them on the board. Were these prioritized into this sprint at some point?

**Comment by lee-delarm6** [comment]
> @lee-delarm6 I went to look at the tickets to review these but didn't see them on the board. Were these prioritized into this sprint at some point?

Yes, they were pulled in last thursday, although I guess they never made it onto the board itself.

**Comment by loripusey** [comment]
I'll add them to the sprint goals now

**Review by brianseek — APPROVED** [review]
LGTM!

**Pull request merged**
