### PR TITLE
Content/wip/small business 2

### PR DESCRIPTION
**Pull request by DanielleSoCompany**

### CODE REVIEW

**Comment by DanielleSoCompany** [comment]
@bethpotts This is ready for you to proof. Note the changes on homepage, careers/employment and job seekers pages, and then the full register page. Also, 2 questions/notes we'll need to follow up on:

- The alignment looks off to me on the Register page. Not sure if it's just my laptop. Can you confirm?
- I left the URL for the Register page as it was (/start) because I'd tried in an earlier branch to change it, and it messed up the page. We'd proposed in the word doc to change this to /register-your-business...we'll need to follow up with dev on this.

**Comment by bethpotts** [comment]
@robertfairhead How difficult/detrimental is it to change the URL at this point for an existing Careers & Employment page? (See @DanielleSoCompany's comment above.)

The ask is to switch this URL: https://www.vets.gov/employment/job-seekers/start/
To: https://www.vets.gov/employment/job-seekers/register-your-business/

**Comment by bethpotts** [comment]
@DanielleSoCompany As for the alignment on the Register page, it looks weird/wrong because Careers & Employment doesn't have a left nav incorporated onto pages at all!
@amybehrens We should discuss this. I checked in with Mel and she said at the time she worked on and launched the new templates, we weren't touching any of the employment pages because of the strained relationship. Is it worth our time now to add a left nav to this section?

**Comment by robertfairhead** [comment]
@bethpotts moving it is no big deal. I opened a PR against this branch with the change.

Here's the Heroku link to the updated page if you want to give it a look to make sure it's working right: https://vetsgov-pr-6723.herokuapp.com/employment/job-seekers/register-your-business/

If you and @DanielleSoCompany are okay with it, I can fold those changes in here.

**Comment by bethpotts** [comment]
@robertfairhead Can you go ahead and fold the URL change in here now?

**Comment by robertfairhead** [comment]
I rebased to pick up your latest changes. CI is running now. Once that's done, I'll merge it in and move everything over/update the links.

**Comment by robertfairhead** [comment]
Ok, it's all moved over. It lives at: https://vetsgov-pr-6708.herokuapp.com/employment/job-seekers/register-your-business/

Ping me a day or so before this gets released, and I can coordinate with the ops team to get the redirect in place.

**Comment by bethpotts** [comment]
@robertfairhead Ping! We want to launch on Wednesday. 
@DanielleSoCompany For awareness.

**Comment by DanielleSoCompany** [comment]
@amybehrens This is ready for your review of the DOL changes. I think I got everything, but I will also give it one final look before this afternoon's deploy! Also, because @bethpotts and @robertfairhead are still looking at this PR for making sure any errors are solved prior to deploy, we thought it would be best if you do see edits needed, that you send them to me and I'll make them. Just to reduce the number of people actually editing files. Let me know if that makes sense - thanks!

**Comment by DanielleSoCompany** [comment]
@amybehrens This is ready for your review of the DOL changes. I think I got everything, but I will also give it one final look before this afternoon's deploy! Also, because @bethpotts and @robertfairhead are still looking at this PR for making sure any errors are solved prior to deploy, we thought it would be best if you do see edits needed, that you send them to me and I'll make them. Just to reduce the number of people actually editing files. Let me know if that makes sense - thanks!

**Comment by DanielleSoCompany** [comment]
@amybehrens This is ready for your review of the DOL changes. I think I got everything, but I will also give it one final look before this afternoon's deploy! Also, because @bethpotts and @robertfairhead are still looking at this PR for making sure any errors are solved prior to deploy, we thought it would be best if you do see edits needed, that you send them to me and I'll make them. Just to reduce the number of people actually editing files. Let me know if that makes sense - thanks!

**Review by ghost — APPROVED** [review]

**Review by bethpotts — APPROVED** [review]

**Review by phiden — APPROVED** [review]

**Pull request merged**
