### PR TITLE
Remove legacy logic and repair health services page.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
Repairs system health services listing pages
attn: @mpelzsherman @kevwalsh @mmiddaugh 

## Testing done
Visual

## Screenshots
image
image
image

## Acceptance criteria
- [ ] `pittsburgh-health-care/health-services/` looks like the above screenshots, with spotlight items visible

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by mpelzsherman** [comment]
I checked the review environment (which is finally working again, yay) and noticed that the spotlight items are from New Jersey:

Health_services___Veterans_Affairs

There's something happening in that deleted code that was correcting this.

**Review by mpelzsherman — CHANGES_REQUESTED** [review]
Need to fix the New Jersey problem.

**Comment by ethanteague** [comment]
> I checked the review environment (which is finally working again, yay) and noticed that the spotlight items are from New Jersey:
> 
> Health_services___Veterans_Affairs
> 
> There's something happening in that deleted code that was correcting this.

That data is correct, @mpelzsherman - this is what @kevwalsh was talking about yesterday on our call. This data is coming from the health listing for Pittsburgh = node 2803.

**Comment by mpelzsherman** [comment]
> That data is correct, @mpelzsherman 

So is the data wrong in Drupal? https://prod.cms.va.gov/pittsburgh-health-care/health-services

Why is it talking about New Jersey on the Pittsburgh page?

If the data is wrong, we should fix it before merging this.

**Comment by ethanteague** [comment]
> > That data is correct, @mpelzsherman
> 
> So is the data wrong in Drupal? https://prod.cms.va.gov/pittsburgh-health-care/health-services
> 
> Why is it talking about New Jersey on the Pittsburgh page?
> 
> If the data is wrong, we should fix it before merging this.

Yeah, you are right, @mpelzsherman  - we are getting incorrect data. Just verified that the data is incorrect in graphql explorer. Node 2803 is getting featured data that doesn't match. Looping in @swirtSJW & @indytechcook to see if they have any ideas.
cc: @kevwalsh 
image

**Comment by indytechcook** [comment]
This was bad data left over from the issue we had earlier this week.  Looking at the revisions, the data fix was in draft status.  I published it and triggered a new content release to fix the page on prod.

**Review by mpelzsherman — APPROVED** [review]
Confirmed this is working now that the CMS data has been fixed.

Can we get rid of the other custom pages in src/site/stages/build/drupal as well?

**Comment by ethanteague** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/vets-website/pull/15217
cc: @mpelzsherman

**Pull request closed without merging**
