### PR TITLE
VIC e2e Content Review Edits

### PR DESCRIPTION
**Pull request by cehsu**
These changes update the following VIC and form content:
On this page: https://staging.vets.gov/veteran-id-card/apply/error

Capitalize the "I" in "in" for this button: Sign In
image

I have capitalized "Over", @peggygannon do other changes make sense here as well?
image

Veteran information page
12. Tweak this sentence: “If you have more than one branch of service, choose the one you want represented on the Veteran ID Card”

To: “If you have more than one branch of service, choose the one you want printed on your Veteran ID Card.”
image
Just above “Need help?” is a link that needs a period (but don’t link the period): “Finish this application later.” [fix on every page]
image
Discharge document upload page

Upload Your Discharge Document (initial cap button words)
image

### CODE REVIEW

**Comment by peggygannon** [comment]
@cehsu thanks. Here are a few additional edits that we need to make: 
1. For the top error message, in another PR I had rewritten that message to be:
You're signed out of your account. Please sign in again to continue your application for a Veteran ID Card. 
I want to be sure this message is fixed?

2. For the second message, can we change "would" to "will" and add hyphen between in and progress to: 
Starting over will delete your in-progress form.

3. I want to be sure the period is not part of the link for Finish this application later.

**Comment by cehsu** [comment]
Thanks @peggygannon , kindly refer to these updates:
image
image
image

**Comment by peggygannon** [comment]
@cehsu LGTM! thanks

**Review by peggygannon — APPROVED** [review]

**Review by rianfowler — APPROVED** [review]

**Review by jbalboni — APPROVED** [review]
LGTM. Some of these changes are in the errors PR I have, so one of us may end up with merge conflicts.

**Pull request merged**
