### PR TITLE
Connect Ask VA to Decide page to api for claims

### PR DESCRIPTION
**Pull request by jbalboni**
Closes [49](https://github.com/department-of-veterans-affairs/sunsets-team/issues/49).

Updates the ask va to decide page to make it submit to the api endpoint.

I also reorganized the routes and connected each page to Redux to make hooking up the api data more straightforward on Files and Details.

Unit tests are in progress.

### CODE REVIEW

**Comment by jbalboni** [comment]
@cagedcrown I still need to write some tests, but want to take a look?

**Review by molindoz — APPROVED** [review]
Nice! Looks great. There are gonna be some conflicts on my end based on the content/layout updates on `FilesPage.jsx`, but I will take care of that once this is merged.

**Comment by jbalboni** [comment]
@cagedcrown Ah, sorry about that! I didn't change any of the content specific to that page, just the layout it had in common with status and details, if that helps.

**Comment by cagedcrown** [comment]
Yeah it's nothing major, no worries 👍

**Pull request merged**
