### PR TITLE
Allows OAuth parameter to be changed

### LINKED ISSUE #55117: Bug: Fix the oauth query parameter
## Description
The `oauth` query parameter is not editable when the Sign in Modal is opened

## Tasks
- [ ] Ensure the `oauth` query parameter is editable

### PR DESCRIPTION
**Pull request by asg5704**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- *(Summarize the changes that have been made to the platform)*
When opening the Sign in Modal the `oauth` query parameter would be set to whatever the `sign_in_service_enabled` Flipper flag was set to.

- *(If bug, how to reproduce)*
1. Navigate to https://staging.va.gov/
2. Click the Sign in button in the header to open the Sign in Modal
3. Try to change the `oauth` query parameter

- *(What is the solution, why is this the solution)*
1. Change the parameter to get the `oauth` query parameter's value if it exists otherwise fallback to `true`
2. Also update the Main (MegaMenu) component to conditionally append `oauth` query parameter for the My VA link

- *(Which team do you work for, does your team own the maintenance of this component?)*
Identity. Yes for the Modal, No for the Main (MegaMenu)

- *(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)*

## Related issue(s)
- *Link to ticket created in va.gov-team repo*
Closes department-of-veterans-affairs/va.gov-team#55117

- *Link to previous change of the code/bug (if applicable)*
department-of-veterans-affairs/va.gov-team#48357

## Testing done

- *Describe what the old behavior was prior to the change*
See above

- *Describe the steps required to verify your changes are working as expected*

- *Describe the tests completed and the results*
Manual testing, unit + E2E

## What areas of the site does it impact?
Entire site as it is included in the mega menu

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [x]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature
- [ ]  [Accessibility foundational testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by ianmagenta — APPROVED** [review]
Tested it locally, LGTM!

**Review by jtmst — APPROVED** [review]

**Comment by asg5704** [comment]
@department-of-veterans-affairs/va-platform-cop-frontend Can I get a review on this?

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Review by alex-morgun-1 — APPROVED** [review]

**Review by stephenBarrs — APPROVED** [review]
LGTM

**Pull request merged**
