### PR TITLE
Content/wip/health care choice program updates

### PR DESCRIPTION
**Pull request by DanielleSoCompany**

### CODE REVIEW

**Review by bethpotts — APPROVED** [review]
I proofed this. It's ready to go!

**Comment by DanielleSoCompany** [comment]
Hi @rroueche @amybehrens @melwoodard. Changes from Choice Program SMEs have been incorporated and proofed. Please review and merge to master. Thank you!

**Comment by rroueche** [comment]
checking on the jenkins error

**Comment by rroueche** [comment]
unsure what Jenkins error is, @CyberKoz is researching for us.

**Review by ghost — APPROVED** [review]

**Pull request merged**
