### PR TITLE
bradl3yC - 8599 - Change form labels for pre needs

### PR DESCRIPTION
**Pull request by bradl3yC**
## Description
Change pre needs labels for inputs

## Screenshots
Screen Shot 2020-05-08 at 9 24 27 AM

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by jhonny218 — APPROVED** [review]
LGTM

**Review by kelsonic — APPROVED** [review]
LGTM! 🎉

**Comment by rianfowler** [comment]
Can we add your team as the code owner of the preneed app?

**Comment by bradl3yC** [comment]
@rianfowler yes

**Pull request merged**
