### PR TITLE
Profile Page Analytics

### PR DESCRIPTION
**Pull request by dsrr47**
added analytics to back to top button, caution flag additional info, school location view buttons and calculate benefits radio buttons.

## Description
OCTO reported the GIBCT Redesign is missing critical Google Analytics. After conducting thorough analysis and collaboration with the OCTO team it was determined by OCTO GIBCT Redesign cannot be released to production without Google Analytics

## Original issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32631

## Testing done
Trigger events via UI, validated using ObservePoint TagDebugger chrome extension

## Screenshots
Caution Flags
Screen Shot 2021-11-10 at 8 55 56 AM
Screen Shot 2021-11-10 at 8 55 41 AM

Jump Links
Screen Shot 2021-11-10 at 8 59 25 AM

Learn More
Screen Shot 2021-11-10 at 9 09 57 AM

School's Website
Screen Shot 2021-11-10 at 9 11 44 AM

VetTech program selection radio buttons
Screen Shot 2021-11-10 at 9 15 09 AM

Calculate benefits
   benefit
Screen Shot 2021-11-10 at 9 16 58 AM
    adjustment
    Screen Shot 2021-11-10 at 9 17 19 AM

Apply for benefits
Screen Shot 2021-11-10 at 9 34 41 AM

Submit a compliant through our Feedback System
Screen Shot 2021-11-10 at 9 37 42 AM

School Location buttons
view more
Screen Shot 2021-11-10 at 9 43 03 AM

view all
Screen Shot 2021-11-10 at 9 43 14 AM

view less
Screen Shot 2021-11-10 at 9 43 27 AM

Back to Top
Screen Shot 2021-11-10 at 9 48 20 AM

Exit about This Tool
Screen Shot 2021-11-10 at 9 49 26 AM

Download School Data
Screen Shot 2021-11-10 at 9 50 11 AM

## Acceptance criteria
- [ ] Add GA analytics calls to various points on profile page to trigger necessary events

## Definition of done
- [ ] GA analytics reporting if users open warning panel to view more information for schools with cautionary warnings.
- [ ]  GA analytics reporting if users visit profiles for schools with cautionary warning.
- [ ] GA analytics reportingUser engages with "On this page" jumplinks
- [ ] GA analytics reporting which"Learn more" links were selected.
- [ ] GA analytics reporting if user clicks school's website
- [ ] GA analytics reporting if user engages with program selection radio buttons (VET TEC PROFILE ONLY)
- [ ] GA analytics reporting if user engages with Calculate your benefits accordions
     - [ ] Which benefits?
     - [ ] Which adjustments?
- [ ] GA analytics reporting if user engages with content links in Apply for benefits section
- [ ] GA analytics reporting if user engages with "Submit a compliant through our Feedback System"
- [ ] GA analytics reporting if user engages with links to other schools in School locations section
- [ ] GA analytics reporting if user engages with "Back to top" element
- [ ] GA analytics reporting if user exits to About this tool page
- [ ] GA analytics reporting if user downloads data on all schools (Excel download)

### CODE REVIEW

**Review by AdamFreemer — CHANGES_REQUESTED** [review]
Since this is in the sandbox, we don't really need the environment feature flags (I believe we decided anything in sandbox isn't going to production anyway). Also some other lint warnings we might want to address.

**Comment by dsrr47** [comment]
@AdamFreemer ready for another look .

**Comment by AdamFreemer** [comment]
> @AdamFreemer ready for another look .

I think we're good here from what I can see if functionally we're passing and QA is good.

**Comment by dsrr47** [comment]
Awesome can you approve the request changes?

**Review by AdamFreemer — APPROVED** [review]

**Pull request merged**
