### PR TITLE
Changing the email form success message.

### PR DESCRIPTION
**Pull request by robbiethegeek-usds**

### CODE REVIEW

**Comment by ayaleloehr** [comment]
@bethpotts or @kerryilenahan can you look at this and let us know if you're good with it?  This feels like a more accurate message to me.

**Comment by suzchap** [comment]
LGTM

**Comment by kerryilenahan** [comment]
+1 to LGTM

**Review by ayaleloehr — APPROVED** [review]
Got LGTM from Suzanne and Kerry (which is most important), and LGTM as well.

**Comment by bethpotts** [comment]
@kerryilenahan @ayaleloehr @suzchap If this can still be updated at some point, I'd suggest this for plain language reasons:

We'll get back to you with instructions for finishing your application.

**Pull request merged**
