### PR TITLE
526 payment information

### PR DESCRIPTION
**Pull request by cehsu**
These changes set up the payment information page.

Tests for these and other veteran details pages have been split out into [this ticket](#10144), so as not to block @peggygannon's content review in staging.

[Prototype link.](https://adhoc.invisionapp.com/share/9MFXXQTUGDK#/screens/282992022)

# Review
screen shot 2018-04-13 at 12 14 09 pm

# Update
screen shot 2018-04-13 at 12 14 24 pm

image

### CODE REVIEW

**Review by peggygannon — COMMENTED** [review]
@cehsu I would like to update the intro to this: 

1. This is the bank account information we have on file for you. We'll pay your benefit to this account. If you need to make changes to your bank information, you can click the Edit button. 

2. There is a typo in the information about electronic transfer info. Can we update this to the below: 
The Department of Treasury requires all federal benefit payments be made by electronic funds transfer (EFT), also called direct deposit. If you don’t have a bank account, you must get your payment through Direct Express Debit MasterCard. To request a Direct Express Debit MasterCard you must apply at www.usdirectexpress.com or by telephone at 1-800-333-1795. If you chose not to enroll, you must contact representatives handling waiver requests for the Department of Treasury at 1-888-224-2950. They'll address any questions or concerns you may have and encourage your participation in EFT.

**Comment by cehsu** [comment]
Thanks @peggygannon , updated:
screen shot 2018-04-13 at 4 44 34 pm
screen shot 2018-04-13 at 4 44 45 pm

**Comment by peggygannon** [comment]
@cehsu Hi, claire. Looks good.

**Comment by cvalarida** [comment]
I believe this also is a branch of https://github.com/department-of-veterans-affairs/vets-website/pull/7528, so I'll wait to review until that's merged in so I can see what the changes specific to this branch are.

**Comment by markgreenburg** [comment]
@cehsu @cvalarida question for you two - what do you feel we should do regarding the chat we had with Alex earlier? I think I remember us settling on only using a `reviewContainer` (is that what it's called? Probably not...sorry), and either:

- Set to 'edit' (screenshot 2 in PR) if one or more of the `required` fields for that page wasn't filled out in a way that passed validations
- Set to 'view' (screenshot 1 in PR) if all of the `required` fields for that page were filled out in a way that passed validations

The current functionality in this PR seems to be a bit different. If we're trying to merge this in to enable a speedy content review - that may not be necessary anymore given our need to push back UAT. I'm happy to defer to you both regarding the way things should work, but definitely want to check that the functionality contained in this PR is still what we want before getting into the weeds on the review.

**Comment by cehsu** [comment]
Thanks @markgreenburg if the user is missing either address or military history information, they will be presented with the standard form view.

**Review by cvalarida — APPROVED** [review]
Looks good. :+1:

**Pull request merged**
