### PR TITLE
Remove healthcare folder and fix .travis.yml

### PR DESCRIPTION
**Pull request by robbiethegeek**

### CODE REVIEW

**Comment by robbiethegeek** [comment]
I think this is now a working PR for removing all the HCA work and getting travis to pass again.  I still think there is more to clean up here overall.  I don't think we need webpack at all, and we likely can scale way back on babel transpilation.

**Comment by robbiethegeek** [comment]
@webinista please take a look also, I removed all the non-landing page hca related files after talking to @crwallace and getting confirmation of them no longer being needed.

**Comment by ayaleloehr** [comment]
OK going to try to review... Starting at the top

**Comment by ayaleloehr** [comment]
OK, the vast majority of this is just deleting code that's not used anymore, and most of the additions are in npm-shrinkwrap. The other changes that are made are pretty much exclusively around removing react references/dependencies in the build process. 

LGTM. Assigning back to @robbiethegeek to determine when to merge; I know HCA testing is going on at some point today and don't want to potentially mess with the landing page for that without having more context.

**Comment by webinista** [comment]
LGTM as well. Merge whenever @robbiethegeek

**Comment by robbiethegeek** [comment]
Can we plan on merging tomorrow AM?

**Pull request merged**
