### PR TITLE
Revert "MBMS-46159 / Self-Service: 508 Compliance: Pre-Need: Review Page Focus"

### PR DESCRIPTION
**Pull request by ksantiagoBAH**
Reverts department-of-veterans-affairs/vets-website#28857

### CODE REVIEW

**Review by sonntag-adam — APPROVED** [review]

**Review by jordanBoardmanCodes — APPROVED** [review]

**Review by delli-gatti-michael — APPROVED** [review]

**Review by rmessina1010 — CHANGES_REQUESTED** [review]
I understand this is a revert but , the `else` on line 130 is not needed, you could simply to

```
      return () => {
        // Check main toggle to enable custom focus; the unmounting of the page
        // before the review & submit page may cause the customScrollAndFocus
        // function to be called inadvertently
        if (
          !(
            page.chapterKey === 'review' ||
            window.location.pathname.endsWith('review-and-submit')
          )
        ) {...subordinate stuff...}
        // h2 fallback for confirmation page
        focusByOrder([defaultFocusSelector, 'h2']);
      };
```


Or even concatenate the logic, if there in no future  branching of the  subordinate condition
```
      return () => {
        // Check main toggle to enable custom focus; the unmounting of the page
        // before the review & submit page may cause the customScrollAndFocus
        // function to be called inadvertently
        if (
          !(
            page.chapterKey === 'review' ||
            window.location.pathname.endsWith('review-and-submit')
          )
          && (formConfig.useCustomScrollAndFocus && page.scrollAndFocusTarget) 
          ){
            customScrollAndFocus(page.scrollAndFocusTarget, index);
          } 
          // h2 fallback for confirmation page
          focusByOrder([defaultFocusSelector, 'h2']);
      };
```

**Comment by ksantiagoBAH** [comment]
@rmessina1010 Another team will be working on this code, can we revert and we could pass this along to the other team? @rhasselle-oddball

**Review by powellkerry — APPROVED** [review]

**Comment by ksantiagoBAH** [comment]
@rmessina1010 need your approval to get this revert in, another team is going to be working on this file I could pass along the feedback.

**Review by rhasselle-oddball — APPROVED** [review]

**Comment by rhasselle-oddball** [comment]
hi @rmessina1010 , good suggestions. This area will need further changes, for example @tlei123 had worked on a large refactor for this area to [make the code asynchronous](https://github.com/department-of-veterans-affairs/vets-website/pull/28386/files#diff-6e641f2d76e75988190ce75e59c5cba9139cf9f661fbaf5506f523ec49b414adR118) which fixes a lot of issues. That code is on hold right now, but we want to pick it up again. It might make sense to just keep the revert how it was so code conflicts will be easier. But if we want to just do some refactors now, I imagine it's not that big of a deal, if you'd like to see those changes.

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Pull request merged**
