### PR TITLE
MHV Landing page: Opt in to continuous deploy and isolated builds

### PR DESCRIPTION
**Pull request by dcloud**
## Summary

- Update `onfig/changed-apps-build.json`, adding a new entry

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#53811
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/53194 (Initial creation of app)

## Testing done

- Checked for cross-dependencies, though this is a *new app*. Ran `yarn check-app-imports --app-folders mhv/landing-page`, it errored out, but again this app is new and has no cross-dependencies
- Ran `yarn cy:run --spec src/platform/site-wide/mega-menu/tests/megaMenu.cypress.spec.js --env app_url=/my-health`, it passed.

## Requested Feedback

We want to use our Slack Channel rather than a Slack group. I followed what I saw others have done in terms of `<@IDENT>`, **is that the right way to assign a channel for notifications**?

### CODE REVIEW

**Comment by dcloud** [comment]
CI run saw the same error:

```bash
$ node script/check-cross-app-imports.js --check-allowlist --fail-on-cross-app-import
[9](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4198397541/jobs/7281965723#step:4:10)
Analyzing app imports...
[10](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4198397541/jobs/7281965723#step:4:11)
/home/runner/work/vets-website/vets-website/script/check-cross-app-imports.js:40
[11](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4198397541/jobs/7281965723#step:4:12)
    Object.keys(importGraph[appFolder].appsThatThisAppImportsFrom).length ||
[12](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4198397541/jobs/7281965723#step:4:13)
                                       ^
[13](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4198397541/jobs/7281965723#step:4:14)

[14](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4198397541/jobs/7281965723#step:4:15)
TypeError: Cannot read property 'appsThatThisAppImportsFrom' of undefined
[15](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4198397541/jobs/7281965723#step:4:16)
    at appHasCrossAppImports (/home/runner/work/vets-website/vets-website/script/check-cross-app-imports.js:40:40)
[16](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4198397541/jobs/7281965723#step:4:17)
    at getCrossAppImports (/home/runner/work/vets-website/vets-website/script/check-cross-app-imports.js:75:9)
[17](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4198397541/jobs/7281965723#step:4:18)
    at Object.<anonymous> (/home/runner/work/vets-website/vets-website/script/check-cross-app-imports.js:114:25)
[18](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4198397541/jobs/7281965723#step:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
[19](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4198397541/jobs/7281965723#step:4:20)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[20](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4198397541/jobs/7281965723#step:4:21)
    at Module.load (internal/modules/cjs/loader.js:928:32)
[21](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4198397541/jobs/7281965723#step:4:22)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[22](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4198397541/jobs/7281965723#step:4:23)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
[23](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4198397541/jobs/7281965723#step:4:24)
    at internal/main/run_main_module.js:17:47
```

**Review by batemapf — APPROVED** [review]

**Comment by batemapf** [comment]
@dcloud have you reached out for support on that CI error?

**Comment by dcloud** [comment]
@batemapf I had not. Looking at the script, looks like an issue with a dependency. I'd like to try one thing related to our code before reaching out

**Comment by dcloud** [comment]
Linking the [discussion](https://dsva.slack.com/archives/CBU0KDSB1/p1677011071367079) with Platform support, as this appears to be a bug in the CI check script

**Comment by dcloud** [comment]
The issue noticed here spawned department-of-veterans-affairs/va.gov-team/issues/54169

**Comment by dcloud** [comment]
Noting that https://github.com/department-of-veterans-affairs/va.gov-team/issues/58176 is the latest ticket around allowing isolated builds for nth-level apps

**Pull request closed without merging**
