### PR TITLE
1995 Prefill and Submit Transformer Updates

### PR DESCRIPTION
**Pull request by devin-mccurdy**
## Description
Veteran email and home phone are not being transformed correctly (both from prefill data and to submitted form data)

Fix for issue:

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19364

## Testing done
Unit tests updated, QA review

## Screenshots
N/A

## Acceptance criteria
- [x] Veteran email and home phone fields are populated from prefill data
- [x] Veteran email and home phone fields are populated in spool file

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by zurbergram — APPROVED** [review]
LGTM

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by delli-gatti-michael — APPROVED** [review]
Passes QA Testing

**Comment by dmccurdybah** [comment]
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!

**Review by rianfowler — APPROVED** [review]

**Pull request merged**
