### PR TITLE
Check in/44335/text input error state

### PR DESCRIPTION
**Pull request by brianseek**
## Description
Adds a couple of bandaid fixes for the error state of the `va-text-input` component.

## Original issue(s)
department-of-veterans-affairs/va.gov-team#44335

## Screenshots
localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (24)

### CODE REVIEW

**Comment by brdunfield** [comment]
Noticing a weird bug (I don't think it's from this PR - we should probably open a new ticket), where if the error messages are visible and you change language, the error message language does not change until the error is triggered again.

**Review by brdunfield — APPROVED** [review]
LGTM and works locally - just make sure to address that eslint warning before merging!

**Comment by brianseek** [comment]
> Noticing a weird bug (I don't think it's from this PR - we should probably open a new ticket), where if the error messages are visible and you change language, the error message language does not change until the error is triggered again.

Weird! I will add a ticket for that

**Comment by brianseek** [comment]
> > Noticing a weird bug (I don't think it's from this PR - we should probably open a new ticket), where if the error messages are visible and you change language, the error message language does not change until the error is triggered again.
> 
> Weird! I will add a ticket for that

Bug ticket: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/44471

**Pull request merged**
