### PR TITLE
Update post-a-job.md

### PR DESCRIPTION
**Pull request by peggygannon**
Proofed. I think this page should have a second proofread.

### CODE REVIEW

**Comment by bethpotts** [comment]
Emily, could you help resolve this conflict?

**Comment by emilyville** [comment]
@bethpotts i don't see any conflicts, what do you see that's making this not look mergable?

**Comment by emilyville** [comment]
I'll go ahead and take this one @kantrowitz

**Comment by emilyville** [comment]
merged and pulled in https://github.com/department-of-veterans-affairs/vets-website/pull/1660 as well.

**Pull request merged**
