### PR TITLE
Vanguard style cleanup

### LINKED ISSUE #3808: [HOMEPAGE] Add hover state to popular buttons
Let's make the border color the same blue as the cards when a Veteran hovers over that button. Can we also increase it to 2px so that it's more visible?

### LINKED ISSUE #4033: LinkedIn Trademark symbol appears as ?
I noticed that on this page https://www.vets.gov/employment/job-seekers/ , the LinkedIn symbol isn't rendering correctly. A ? is showing up and it should be the TM symbol.  

It's on this page 3 times. 

Thanks! 
@bethpotts  FYI

### PR DESCRIPTION
**Pull request by bshyong**
- Resolves https://github.com/department-of-veterans-affairs/vets-website/issues/4027 move login bar to top nav
- Resolves https://github.com/department-of-veterans-affairs/vets-website/issues/4028 topnav styling improvements
- Resolves #3808; popular on vetsgov button borders
- Resolves #4033, linkedin trademark symbol

### CODE REVIEW

**Comment by crwallace** [comment]
@bshyong -- Should the VCL have a border radius on it?
screen shot 2016-12-01 at 6 34 37 pm

**Comment by crwallace** [comment]
Also @bshyong, do we want the search icon to match the large version?
screen shot 2016-12-01 at 6 37 19 pm

Would love to get @AnitraAppa and @maryannbrody's thoughts on if we can use and icon alone in the mobile view or if we need to keep the full "search" text.

**Comment by bshyong** [comment]
@crwallace looks like the border radius on the div doesn't show; fixed it in a commit.  

For the search icon, Mel had a mockup here that I missed implementing—this will be pushed up shortly

**Comment by maryannbrody** [comment]
@crwallace @bshyong Believe it or not, in usability testing the search icon isn't always recognizable to all users, especially those with lower literacy skills. I'd recommend sticking to "search" in a button if we can. 

cc/ @AnitraAppa

**Comment by AnitraAppa** [comment]
@maryannbrody Good to know, would have just used icon. +1 to keeping "Search" then.

**Comment by bshyong** [comment]
Added back the search button for mobile: for the small screen size, the textbox is too large to display, so instead there will be a button labeled "Search" which opens the full screen search input.

**Comment by melwoodard** [comment]
@bshyong looking good! A couple comments on the nav work:

1. Is there a middle breakpoint we can take advantage of? I had in mind that the 100% width for the VCL and beta banner outlined [here](https://cloud.githubusercontent.com/assets/4106356/20414361/e6577cf6-ace6-11e6-9a91-b99035f7da4c.png) would happen at something closer to <600px wide, but right now it's hitting everything <1024px when there's still plenty of room for them to sit side by side:

   vets_gov

2. I see the updated smaller size for the logo, but that smaller size was only supposed to be at the smallest breakpoint (corresponding to the idea of breakpoints above) - at the larger breakpoint it should remain at the original size we had before.

**Comment by bshyong** [comment]
@melwoodard just fixed the breakpoints and logo size this morning. The only issue that I can see now moving through the breakpoints is that the crisis line text will not fit on one line right before it breaks to the small breakpoint. Unless we shorten the text to Vets Crisis Line or reduce the font size I don't think it can fit in the current state. 

However, this issue only happens when you are resizing the window to a non-standard size

screen shot 2016-12-05 at 8 38 12 am

**Comment by melwoodard** [comment]
@bshyong is there a way to fix the width of the crisis line container until it breaks to the small breakpoint? It'd be preferable for the beta text to wrap and the crisis line to stay fixed, like so:

screen shot 2016-12-05 at 9 14 01 am

**Comment by bshyong** [comment]
Got it; that approach looks great

screen shot 2016-12-05 at 10 26 56 am

**Comment by melwoodard** [comment]
Thanks, looks great!

**Review by crwallace — APPROVED** [review]
LGTM

**Pull request merged**
