### PR TITLE
Remove prop type and test util warnings

### PR DESCRIPTION
**Pull request by jbalboni**
Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2397

This is giant, but it's almost all done with scripts. These are the actual changes I made:

- Ran `react-codemod/transforms/React-PropTypes-to-prop-types.js` codemod on files in src
- Added `babel-plugin-transform-react-remove-prop-types` and configured it to remove all prop type code in production
- Replaced all instances of `react-addons-test-utils` with `react-dom/test-utils` in `test/` and removed `react-addons-test-utils` package
- Fixed some minor unit test issues in `RequiredLoginView` that were a result of the test utils change.

### CODE REVIEW

**Comment by raquelromano-gov** [comment]
`RequiredLoginView.unit.spec.jsx` changes LGTM

**Review by cvalarida — APPROVED** [review]
Looks good, but you missed a spot 😉 

`test/util/unit-helpers.jsx` line 43 reads `const contextTypes = { router: React.PropTypes.object };`

**Review by U-DON — APPROVED** [review]
Changes for `gi`, `messaging`, and `rx` LGTM.

**Comment by ayaleloehr** [comment]
Thanks everyone here for the quick turnaround on a massive PR!

**Pull request merged**
