### PR TITLE
Corrected GIBCT housing allowance calculation for MGIB.

### LINKED ISSUE #5388: GI Bill CT: Monthly living allowance rate for MGIB incorrect
The benefits estimator is not correctly calculating the MGIB (CH 30) benefits when the user served less than 3 years. The correct rate for a 2 year enlistment under CH 30 is $1,509/month.

http://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch30/ch30rates100116.asp

**3 years**
image

**2 years**
image

### PR DESCRIPTION
**Pull request by U-DON**
Resolves #5388.

Compared with the existing calculator's code to find that the constants being used were different depending on the length of enlistment service, so that's the fix.

### CODE REVIEW

**Review by bshyong — APPROVED** [review]
LGTM

**Comment by bshyong** [comment]
Looks like some issue with the build reporting—you might need to push to a new branch without any `#` in the branch name for it to work. I remember Jenkins has an issue with that character in branch names

**Comment by U-DON** [comment]
D'oh, forgot about that...

**Comment by U-DON** [comment]
Duplicated this PR with #5418 using a valid branch name. Closing.

**Pull request closed without merging**
