### PR TITLE
Update document title on details pages

### PR DESCRIPTION
**Pull request by jenniemc**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

### :warning: TeamSites :warning:
Examples of a TeamSite: https://va.gov/health and https://benefits.va.gov/benefits/. This scenario is also referred to as the "injected" header and footer. You can reach out in the `#sitewide-public-websites` Slack channel for questions.

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

This PR updates our browser tab titles to make them consistent with design standards - namely using Initial Caps Case. 

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#95539

## Testing done

Visual check

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Upcoming | Canceled |  Past  |
| ------- | ------ | ----- |----- |
|  VA Request  |    Screenshot 2024-10-31 at 8 24 29 AM    |   Screenshot 2024-10-31 at 8 25 11 AM    |      |
| CC Request  |   Screenshot 2024-10-31 at 8 23 05 AM     |   Screenshot 2024-10-31 at 8 24 05 AM    |      |
| Video at VA |    Screenshot 2024-10-31 at 8 18 54 AM    |    Screenshot 2024-10-31 at 8 19 15 AM   |   Screenshot 2024-10-31 at 8 20 43 AM   |
| Video at ATLAS  |    Screenshot 2024-10-31 at 8 15 52 AM    |    Screenshot 2024-10-31 at 8 16 26 AM   |   Screenshot 2024-10-31 at 8 17 31 AM   |
| Video appt  |    Screenshot 2024-10-31 at 8 12 54 AM    |    Screenshot 2024-10-31 at 8 13 57 AM   |   Screenshot 2024-10-31 at 8 14 23 AM   |
| Claim Exam  |   Screenshot 2024-10-31 at 8 11 12 AM     |    Screenshot 2024-10-31 at 8 10 03 AM   |   Screenshot 2024-10-31 at 8 11 40 AM   |
| In-person |    Screenshot 2024-10-31 at 8 07 14 AM    |    Screenshot 2024-10-31 at 8 07 39 AM   |   Screenshot 2024-10-31 at 8 08 36 AM   |
| Phone appt  |   Screenshot 2024-10-31 at 8 04 04 AM     |   Screenshot 2024-10-31 at 8 04 27 AM    |   Screenshot 2024-10-31 at 8 04 55 AM   |
| COVID appt |    Screenshot 2024-10-31 at 8 01 32 AM    |   Screenshot 2024-10-31 at 8 02 01 AM    |   Screenshot 2024-10-31 at 8 03 03 AM   |
| CC appt |    Screenshot 2024-10-31 at 7 58 35 AM    |   Screenshot 2024-10-31 at 7 59 02 AM    |   Screenshot 2024-10-31 at 7 59 32 AM   |

## What areas of the site does it impact?

Document title 

## Acceptance criteria

Update document title on details page for:

- [ ] Community Care Request
- [ ] VA Request
- [ ] Video at VA
- [ ] Video at ATLAS
- [ ] Video appt 
- [ ] Claim Exam
- [ ] In-person
- [ ] Phone appt 
- [ ] COVID appt
- [ ] CC appt 

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by JunTaoLuo — APPROVED** [review]

**Comment by JunTaoLuo** [comment]
I think there are quite a few tests that need to be fixed given the updated titles but otherwise the changes look good.

**Review by JunTaoLuo — CHANGES_REQUESTED** [review]
Hmm I can't dismiss my own review so dropping a request changes until tests are updated.

**Comment by jenniemc** [comment]
> I think there are quite a few tests that need to be fixed given the updated titles but otherwise the changes look good.

I should have set this PR initially to draft mode as indicated for best practice.  The unit tests are fixed now. Thanks @JunTaoLuo for reviewing.

**Review by JunTaoLuo — APPROVED** [review]
Fortune favors the bold, no drafts necessary 😄

**Pull request merged**
