### PR TITLE
Added two new content pages

### PR DESCRIPTION
**Pull request by dannychapman**
- What happens after a rating
- Claims Exam

Added two new content pages to claims process section, at request of @bethpotts. Please review!

### CODE REVIEW

**Comment by dannychapman** [comment]
WIP - not ready to merge.

**Comment by crwallace** [comment]
@dannychapman -- Is this still WIP?

**Comment by dannychapman** [comment]
@crwallace yep! Circling back with content team on this later today.

**Comment by dannychapman** [comment]
Closing, replaced with two new PRs, one for each content page at @bethpotts's request. 

#2758 and #2754

**Pull request closed without merging**
