### PR TITLE
Refactored some #content CSS blocks.

### PR DESCRIPTION
**Pull request by ghost**
Related to department-of-veterans-affairs/vets.gov-team#656

- Refactored #content .section h* selectors (closes department-of-veterans-affairs/vets.gov-team#1474)
- Simplified selectors within the #content .splash block (closes department-of-veterans-affairs/vets.gov-team#1473)
- Simplified markup for index.md

### CODE REVIEW

**Comment by tiffanybbrown-va** [comment]
Screen shots:

### Tablet
screen shot 2017-03-15 at 17 49 28-fullpage

### Mobile
screen shot 2017-03-15 at 17 49 06-fullpage

### Desktop
screen shot 2017-03-15 at 17 48 38-fullpage

**Comment by jcmeloni-usds** [comment]
LGTM.  @melwoodard or anyone please give it a second sanity check and merge if you can today.  Thank you!

**Comment by melwoodard** [comment]
@tiffanybbrown-va looks good! I'll let you resolve those conflicts...

**Review by melwoodard — APPROVED** [review]
@tiffanybbrown-va looks good! I'll let you resolve those conflicts...

**Pull request merged**
