### PR TITLE
Title change and content change on print page

### PR DESCRIPTION
**Pull request by annekainicUSDS**
Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3908.

screen shot 2017-07-18 at 11 08 44 am

screen shot 2017-07-18 at 11 08 30 am

### CODE REVIEW

**Comment by rroueche** [comment]
@annekainicUSDS two comments:

1. The Benefit End Date needs the long format here too
2. Remove the link to the rate tables. "Find out how much money..."

**Comment by annekainicUSDS** [comment]
@rroueche the link to the rate tables should be removed from just the print page or both the print page and the regular status page too? Both pages are rendering the same component so that's why it's appearing in both right now.

**Comment by rroueche** [comment]
@annekainicUSDS ah I see, in that case just leave as is. I think it's fine to have it there.

**Comment by rroueche** [comment]
@annekainicUSDS i mean just leave the link as is, but please still do update the date formats :)

**Comment by rroueche** [comment]
@annekainicUSDS in the changes, I see the End Date format change, but I don't see it yet for the DOB - am I missing it, or is that still underway?

**Comment by annekainicUSDS** [comment]
@rroueche that change was made in a different PR, but I can make it here too if it's important for the screenshots

**Comment by rroueche** [comment]
@annekainicUSDS oh man ok yes please, and I'm sorry about that.

**Comment by rroueche** [comment]
@annekainicUSDS actually nvm, if the date work is in another PR no need to dupe it here. I'll just update in inspect element and send them a screenshot of that.

**Review by rroueche — APPROVED** [review]
LGTM

**Comment by annekainicUSDS** [comment]
No worries, just made the change here anyway :) will merge once the build passes

**Pull request merged**
