### PR TITLE
Update direct deposit downtime alerts

### PR DESCRIPTION
**Pull request by adamwhitlock1**
## Summary

- Updates alerts for the downtime approaching, and the active downtime alert
- Removes logic that prevents the edu form alert and overall alert showing at the same time since that is now a desired outcome.
- Show payment history card on page when temporary outage alert is shown
- Allow a custom message to be used in the outage alert so that we can quickly change that and not have to replace the fallback content over and over.
- Move the HelpDeskContact to the root of profile so it can be easily reused throughout profile.
- I did skip one unrelated test that kept failing in the CI/CD. It passes locally fine, but during the stability checks it was failing. I'm looking into it.

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80982

## Testing done

- Updated unit tests for changes

## Screenshots

|         | Before | After |
| ------- | ------ | ----- |
| Upcoming alert - HUB | Screenshot 2024-04-22 at 8 30 27 AM | Screenshot 2024-04-22 at 8 29 15 AM |
| Upcoming alert - DD page | Screenshot 2024-04-22 at 8 30 42 AM | Screenshot 2024-04-22 at 8 29 03 AM |
| Outage alert | Screenshot 2024-04-22 at 8 39 05 AM | Screenshot 2024-04-22 at 8 40 06 AM |

## What areas of the site does it impact?

Profile -> Direct Deposit

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Screenshot of the developed feature is added

### CODE REVIEW

**Review by allisonlu — APPROVED** [review]

**Comment by mtcA6** [comment]
@adamwhitlock1 these look good. We do want to update the outage one with a time, maybe until 8pm EST just to give us some cushion

**Comment by mtcA6** [comment]
@adamwhitlock1 chatting w/Chante, we do need to add the start and end dates for the upcoming:  

image


So this copy should be at the bottom of the upcoming:

**Start**: Friday, April 26, 2024, at TBD
**End:** Thursday, May 2, 2024, at TBD

**Comment by adamwhitlock1** [comment]
Screenshot 2024-04-22 at 11 51 50 AM
Screenshot 2024-04-22 at 11 50 16 AM

Okay I can put another PR in for this. Can you confirm that this is how we want it to look @mtcA6 and @clantosswett ?

**Comment by mtcA6** [comment]
@adamwhitlock1 closing the loop here since we chatted in slack and on zoom. The dates look good they just need the 8PM ET added in lieu of the TBD.

**Pull request merged**
