### PR TITLE
GIBCT: "How do you want to take classes" question missing from institution profile page #19467

### PR DESCRIPTION
**Pull request by zurbergram**
## Description
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19467

On the school profile page, a user is able to edit their eligibility details. Included in these details is a question asking "how do you want to take classes" with 3 radio button options. This question has gone missing from the institution profile page.

1. Access https://www.va.gov/gi-bill-comparison-tool
2. Type "College" into the search bar and click Search Schools
3. Click on any school in the results
4. Under Estimate your benefits, click Edit eligibility details

- "how do you want to take classes" question should be present

## Testing done
- local testing

## Screenshots
Screen Shot 2019-08-14 at 11 26 56 AM

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by delli-gatti-michael — APPROVED** [review]
Approved by QA

**Review by cvalarida — COMMENTED** [review]
Looks good. From what I can tell by doing a little git blaming, it _looks_ like this was accidentally removed? It's unclear to me.

At any rate, can you make sure this is unit tested as well?

**Comment by zurbergram** [comment]
> Looks good. From what I can tell by doing a little git blaming, it _looks_ like this was accidentally removed? It's unclear to me.
> 
> At any rate, can you make sure this is unit tested as well?

A unit test for the OnlineClassesFilter component or for its inclusion in the component for this PR?

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19475 https://github.com/department-of-veterans-affairs/vets-website/pull/10577 is going to move this into a different component

**Comment by zurbergram** [comment]
Added unit test to `src/applications/gi/tests/components/EligibilityForm.unit.spec.jsx` to check for existence of `OnlineClassesFilter`

**Review by cvalarida — APPROVED** [review]

**Pull request merged**
