### PR TITLE
aria-describedby

### PR DESCRIPTION
**Pull request by eselkin**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

## Summary

- Attach button group to label for input to indicate what effect the button has.
- Sitewide team

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12882

## Testing done

- Tested manually with Mac VoiceOver

## Screenshots

<details><summary>New: With aria-describedby</summary>
Screenshot 2024-08-09 at 10 53 22 AM

</details>

<details><summary>Former: Without aria-describedby</summary>
Screenshot 2024-08-07 at 5 04 17 PM
</details>

## What areas of the site does it impact?

Facility locator

## Acceptance criteria

- [x] Screen reader announces "Use my location City, state or zip code"
- [ ] Accessibility review

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user (unauthenticated)

## Requested Feedback

View RI with Voiceover or JAWS or something to announce the aria label over the "Use my location" button on /find-locations

### CODE REVIEW

**Comment by eselkin** [comment]
@laflannery There's an issue. The (* Required) also gets read out. Do we want to exclude this? If so, I have a fix ready to commit, but want your input first.

**Comment by laflannery** [comment]
@eselkin The review instance isn't coming up for me, are you able to try and rebuild this?

**Review by Andrew565 — DISMISSED** [review]

**Comment by laflannery** [comment]
@eselkin Thinking about this I do think it would be better without the "Required" if the fix isn't too much additional work

**Comment by eselkin** [comment]
@laflannery http://be581ab64cbf8f0784e67d188f1e4ca2.review.vetsgov-internal/ is now working for the RI

**Comment by laflannery** [comment]
Looks good!

**Review by randimays — APPROVED** [review]
LGTM!

**Pull request merged**
