### PR TITLE
508 fix: change element ID and name on 404 page

### PR DESCRIPTION
**Pull request by raquelromano-gov**
Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3087

### CODE REVIEW

**Review by omgitsbillryan — APPROVED** [review]
So long as nothing relies on this particular `ID` , LGTM.

**Review by cvalarida — APPROVED** [review]
Famous last words: Well that was easy.

**Comment by raquelromano-gov** [comment]
Yeah, no idea if anything relies on those IDs being what they are, but will keep an eye out for anything after the next production deploy.

**Comment by cvalarida** [comment]
I did a search in the entire project for it and found nothing, so :crossed_fingers: it looks good. Unless it's dynamically generated (which would be weird for this, I think).

**Comment by raquelromano-gov** [comment]
Yeah, I did that before changing it, but still wondered if some monitoring tool could rely on it for something. You made me paranoid so I just searched sentry logs for `affiliate`: http://sentry.vetsgov-internal/vets-gov/website-production/?query=is%3Aunresolved+affiliate
I can't make any sense of the errors though. They've been around for a while and look like something inside the VA network. I can't even tell if it's a coincidence or the same `affiliate`

**Pull request merged**
