### PR TITLE
Platform testing wkspc

### PR DESCRIPTION
**Pull request by it-harrison**
## Description
This PR adds a workspace to `platform/testing`
## Original issue(s)
[department-of-veterans-affairs/va.gov-team#45764
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45674)

## Testing done
unit tests

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by alexandec — APPROVED** [review]

**Comment by pjhill** [comment]
Is the `original issue` here correct?

**Comment by it-harrison** [comment]
> Is the `original issue` here correct?

good catch - updated!

**Review by ddzz — APPROVED** [review]
I tested Cypress locally and found no issues.

**Review by pjhill — APPROVED** [review]
I ran through some Cypress tests locally including some of the extensions made to Cypress, and they look good. LGTM!

**Pull request merged**
