### PR TITLE
Update HTML header elements for stepchild page and review page

### PR DESCRIPTION
**Pull request by zack**
https://github.com/department-of-veterans-affairs/va.gov-team/issues/63206

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- Fixed subheader on "remove a stepchild" page so that the DOM doesn't skip from h2 to h4.
- Added clarifying information to headers on final review page to avoid repeating and confuding headers

## Related issue(s)

- [https://github.com/department-of-veterans-affairs/va.gov-team/issues/63206](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63206)

## Testing done

- Manual testing on both pages before-and-after.

## Screenshots

|         | Before | After |
| ------- | ------ | ----- |
| Desktop (Stepchild)|63206-stepchild-before|63206-stepchild-after|
| Desktop (Review page) |23606-review-page-before|23606-review-page-after|

## What areas of the site does it impact?

21-686c dependents benefits form

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

N/A

### CODE REVIEW

**Review by tblackwe — APPROVED** [review]
Thanks, LGTM!

**Review by pjhill — APPROVED** [review]
This looks good -- thanks for resolving these accessibility issues!

**Comment by zack** [comment]
Hi @pjhill, thanks for the review. :) I see merging is still blocked. I neglected to check before I did this, but I accidentally updated the branch with a merge commit instead of a rebase and I'm wondering if that's why? Does it need a new review after a change? If so, could I bother you to do it again? :) Thanks!

**Comment by pjhill** [comment]
> Hi @pjhill, thanks for the review. :) I see merging is still blocked. I neglected to check before I did this, but I accidentally updated the branch with a merge commit instead of a rebase and I'm wondering if that's why? Does it need a new review after a change? If so, could I bother you to do it again? :) Thanks!

It looks like you're blocked by other codeowner reviews, namely --
* department-of-veterans-affairs/vsa-authd-exp-frontend
* department-of-veterans-affairs/benefits-team-1-frontend
* department-of-veterans-affairs/dbex-trex

Because the changed files hit this line from codeowners I believe --
`src/applications/disability-benefits @department-of-veterans-affairs/benefits-team-1-frontend @department-of-veterans-affairs/vsa-authd-exp-frontend @department-of-veterans-affairs/DBEX-TREX`

**Review by christinec-fftc — APPROVED** [review]

**Pull request merged**
