### PR TITLE
Main Nav Fix -- IE

### PR DESCRIPTION
**Pull request by cvalarida**
IE didn't like the `forEach` on an array-like object, so I just made it an array.

### CODE REVIEW

**Review by cehsu — APPROVED** [review]

**Comment by cehsu** [comment]
Does IE support forEach?

**Review by ncksllvn — APPROVED** [review]
LGTM

**Comment by cvalarida** [comment]
@cehsu Yeah, since IE9: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

Trouble was it was giving the following error: `Object doesn't support property or method 'forEach'`

Turns out a `NodeList` doesn't have `forEach` in IE. Because IE. :man_shrugging:

**Comment by cehsu** [comment]
Thanks @cvalarida!

**Pull request merged**
