### PR TITLE
Add linting to webpack

### PR DESCRIPTION
**Pull request by alexose**
This will cause webpack to run eslint automatically whenever webpack rebuilds the bundle.

Addresses #2777.

### CODE REVIEW

**Comment by awong-dev** [comment]
LGTM once the tests go green.

Looks like you forgot a shrinkwrap update?

**Comment by webinista** [comment]
There are some conflicts that need resolving :-(

**Comment by alexose** [comment]
One mildly annoying part of this is that webpack isn't aware of configuration files-- It's only aware of the files specified in the entry points.

I'm not sure about the best way to add them into webpack, nor am I sure about the best way to ask webpack-dev-server to run an external linting command on reload.

**Comment by jbalboni** [comment]
@alexose This would also skip running eslint on tests, too, right?

I think adding eslint to webpack could also make debugging a little harder. I know I still sometimes add console statements in code to check things, but with this change I'd need to suppress the eslint error, too.

**Comment by alexose** [comment]
Yeah.  Maybe it makes more sense to lint as a pre-commit hook?

**Comment by alexose** [comment]
Closing this in favor of a better solution: https://github.com/department-of-veterans-affairs/vets-website/pull/2860

**Comment by akainic** [comment]
@crwallace is there a reason we reopened this? Looks like the last decision was to close this in favor of another PR.

**Comment by crwallace** [comment]
@akainic -- This was reopened because we were going to try to add linting to the watch function in webpack instead of having it as a precommit hook. This will most likely not get finished before veterans day.

**Comment by leannammiller** [comment]
@alexose - is this eduben or hca?

@crwallace / @akainic - should we move this to the backlog since it won't be done by vet's day and revisit?

**Comment by crwallace** [comment]
Yes I think this is definitely a backlog item.



Sent with Good (www.good.com)


-----Original Message-----

**Comment by akainic** [comment]
@crwallace @alexose is this still being worked on?

**Comment by alexose** [comment]
I'm okay with the pre-commit hook solution that we've been using... I'd favor closing this.

**Comment by leannammiller** [comment]
@alexose hello! can you please close?

**Pull request closed without merging**
