### PR TITLE
Modify burial allowance content to a table format

### PR DESCRIPTION
**Pull request by melwoodard**
Closes vets.gov-team [#1438](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1438)

First pass at formatting burial allowances into tables - feel free to adjust the content as needed, but the structure is there!

### CODE REVIEW

**Comment by mollyblake** [comment]
It's hard for me to see what it looks like without it being merged into heroku. Can @rroueche help with that ?  Thanks

**Comment by melwoodard** [comment]
@mollyblake take a look here:

markdown: https://github.com/department-of-veterans-affairs/vets-website/blob/e17f50380bfd9f72df52058f2233124a90d1f7d3/content/pages/burials-and-memorials/survivor-and-dependent-benefits/burial-costs.md

preview: https://vetsgov-pr-5012.herokuapp.com/burials-and-memorials/survivor-and-dependent-benefits/burial-costs/

**Comment by mollyblake** [comment]
AH!  That looks amazing!  THANK YOU! Can we add the word STATUS to the top of the box (in the left side of the grey part)   Or can I do it in the the github file?  THANKS

**Comment by melwoodard** [comment]
@mollyblake yep! I just added it, should  show up in the heroku preview now. 

One question - there were two points in the last section (if the Veteran was hospitalized by the VA) that weren't laid out in the same format of [Status][Amount], so I left them as separate bullets below the table. Is that ok? Otherwise we could reformat them a bit to fit in the table like so:

| Status                   | Maximum Burial Allowance |
| ------------------------ | ------------------------ |
| If the Veteran was hospitalized or in a VA-contracted nursing home at the time of death | We may pay you back for some or all of the costs of moving the Veteran’s remains | 
| If the Veteran died while traveling to VA-authorized care | We may pay you back for some or all of the costs of moving the Veteran’s remains |

**Comment by mollyblake** [comment]
Awesome. Thanks again!  I don't know how to marry that into the current file so that we can see it on our 4998 heroku link?  THANKS @melwoodard @rroueche

**Comment by melwoodard** [comment]
@mollyblake if you hit the merge button on this pull request, the changes will be merged into your `content/wip/burials` branch and should show up in your link.

**Pull request merged**
