### PR TITLE
Lock bourbon @ version 4 to avoid future build problems

### PR DESCRIPTION
**Pull request by alexose-gov**

### CODE REVIEW

**Review by typesend — APPROVED** [review]
LGTM

**Comment by robbiethegeek-usds** [comment]
@alexose-gov can you resolve conflicts and if this passes all tests merge in.

**Comment by crwallace** [comment]
@webinista -- For a heads up.

**Comment by jcmeloni-usds** [comment]
ping @alexose @robbiethegeek-usds

**Comment by tiffanybbrown-va** [comment]
I just opened #4970, which supersedes this PR a bit. It updates USWDS to 1.0.0, which includes Bourbon 4.2.6 and Neat 1.8.0 as dependencies. I don't want to just close this PR, but I think it's safe to.

**Comment by alexose-gov** [comment]
Right.  FWIW, I haven't noticed bourbon errors on [newer PRs](http://jenkins.vetsgov-internal/blue/organizations/jenkins/department-of-veterans-affairs%2Fvets-website/detail/schemaform-address-unit-test/1/pipeline/62), so I think we're safe.

**Pull request closed without merging**
