### PR TITLE
Fixed header overflow for XS viewports. Closes #4155

### LINKED ISSUE #4155: Page header is wider than content at small screen sizes
At small screen sizes the page header doesn't collapse enough and sticks at a certain width, while the page content keeps shrinking:

screen shot 2016-11-30 at 9 01 16 am

This is pretty minor, as it only shows up on sub-iPhone 5 size screens.

### PR DESCRIPTION
**Pull request by webinista**
Affects header at viewports less than 320px wide.

- Removed html { overflow: -moz-scrollbars-vertical;} ruleset (unnecessary)
- Added xsmall-screen breakpoint variable
- Added changed .header .top-banner to .va-header-logosearch
- Removed empty flex-auto div.
- Now .va-header-logosearch applies display: flex; only when viewport > 320px
- .search-button now only floats right when viewport > 320px
- Removed unused `.search-button a` block

### CODE REVIEW

**Comment by webinista** [comment]
What these changes look like:

Extra small screens ( < 320px)
screen shot 2017-01-05 at 11 48 26-fullpage

Small screens ( ≥ 320px; < 481px)
screen shot 2017-01-05 at 12 18 54-fullpage

**Comment by crwallace** [comment]
I would love to get @melwoodard to way in on this and make sure this reflects our global design.

**Comment by melwoodard** [comment]
This makes sense to me. There may be more extensive changes to the nav design in the near future with the addition of global nav links, but this seems like a sensible update for now. 

I do want to point out that screens <320px make up less than 0.01% of sessions, so anything more complex to accommodate the XS screen size in the future should be considered with that in mind.

**Comment by jcmeloni-usds** [comment]
@webinista @melwoodard Any reason not to merge this at this point?

**Comment by webinista** [comment]
@jcmeloni I don't know if anyone has reviewed the code, but it's a small change that shouldn't break anything.

**Comment by jcmeloni-usds** [comment]
@webinista gotcha.  the code looks fine to me.  I can't roll up the branch but taking your word that your screenshot is accurate, I'm going to press the button. :)

**Pull request merged**
