### PR TITLE
February claims update

### PR DESCRIPTION
**Pull request by kellyskennedy**
Your VA Administration / Department VBA
Your VA email   misty.sweet@va.gov
Your phone number   (202) 530-9203
Is this update global?  No
Update Type Replace
Replace this content... 107.5
Average number of days to complete disability-related claims in January 2018
...on this page...  https://www.vets.gov/disability-benefits/apply/ and https://www.vets.gov/disability-benefits/after-you-apply/
...with this content    101.5
Average number of days to complete disability-related claims in February 2018
Does the update have a deadline?    Yes
Deadline    03/01/2018

### CODE REVIEW

**Comment by kellyskennedy** [comment]
@peggygannon This is ready for you -- it's one of those quick-turnaround content-user requests. Thanks!

**Review by peggygannon — APPROVED** [review]
@kellyskennedy Looks good! Thanks

**Comment by kellyskennedy** [comment]
@bethpotts This is ready for you -- content user request

**Review by bethpotts — APPROVED** [review]
@kellyskennedy @peggygannon Looks good! Kelly, go ahead and request the merge from Sophia. Thanks!

**Comment by kellyskennedy** [comment]
@phiden Could you merge this, too, please? Thanks!

**Review by phiden — APPROVED** [review]

**Pull request merged**
