### PR TITLE
Prevents the buy-up rate from being prorated twice

### PR DESCRIPTION
**Pull request by saintsoup52**
The buy-up rate should be prorated in the living allowance formulas and not when it is initially defined. 

A previous change to this formula only changed one of the formulas where the buy-up appears but not the other 16 instances.

### CODE REVIEW

**Review by U-DON — APPROVED** [review]
LGTM. Can you push up an empty commit so the build can get running again? Looks like it got stuck on the first push.

**Comment by saintsoup52** [comment]
Sorry... I don't really know how to do an empty commit. Can you please help?

**Comment by U-DON** [comment]
@CyberKoz This PR is still failing to build after merging. Any other way to unblock this?

**Comment by CyberKoz** [comment]
@U-DON @saintsoup52 this PR won't be able to be merged due to it originating from an outside repository. To get this to merge it must first be merged into a non-master branch by someone on the team, then they can open a PR to merge it into master.

**Comment by U-DON** [comment]
Closing; I've created another PR (#5420) with a branch within the repo.

**Pull request closed without merging**
