### PR TITLE
Update TTY numbers from 800-829-4833 to 711

### PR DESCRIPTION
**Pull request by kelsonic**
## Description
**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/8435

This PR updates the TTY number 800-829-4833 to 711. It does not update other TTY numbers.

## Acceptance criteria
- [x] Update TTY 800-829-4833 number to 711.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by RLHecht — APPROVED** [review]

**Review by ncksllvn — APPROVED** [review]

**Review by erikphansen — APPROVED** [review]
We could stop using the no-wrap class if we wanted to

**Comment by ncksllvn** [comment]
I was wondering about that no-wrap class. What did it do?

**Comment by kelsonic** [comment]
Thanks @erikphansen! The less code the better! 🎉Any idea what the `no-wrap` class did beforehand?

**Comment by erikphansen** [comment]
yeah I made it. It prevents phone numbers from wrapping across lines at the hyphens. Seeing one line end with `800-` and the next line continue with `829-4833` looks bad. I proposed making a `vads-u-no-wrap` class for this

**Comment by kelsonic** [comment]
Oh! That seems useful! We could make a [new design utility](https://design.va.gov/utilities) for `vads-u-white-space--nowrap` and the other `white-space` values 🙂

**Review by jhonny218 — APPROVED** [review]
LGTM

**Pull request merged**
