### PR TITLE
Feature/meb 4.0 to main

### PR DESCRIPTION
**Pull request by cesaresantiago**
## Original issue(s)
department-of-veterans-affairs/va.gov-team#0000

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by FernandoBoza — APPROVED** [review]

**Review by nathanielbuck — APPROVED** [review]

**Review by it-harrison — APPROVED** [review]

**Comment by it-harrison** [comment]
@cesaresantiago heads up: you need to sync with `main` to get some failing unit tests to pass.

**Comment by FernandoBoza** [comment]
> 

@it-harrison

**Comment by FernandoBoza** [comment]
> @cesaresantiago heads up: you need to sync with `main` to get some failing unit tests to pass.

Hi @ianhundere , we think one of the 3 might keep failing because of the property getHelp in configs/form.js expects a React component, vs our Redux container.

**Comment by it-harrison** [comment]
> > @cesaresantiago heads up: you need to sync with `main` to get some failing unit tests to pass.
> 
> Hi @it-harrison , we think one of the 3 might keep failing because of the property getHelp in configs/form.js expects a React component, vs our Redux container.

@cesaresantiago that sounds right - I know that two of the three tests were failing for a related reason but the third was a different case.

**Pull request merged**
