### PR TITLE
 MHV-60264 In-Chem-Hem-Reducer-Pull-Observation-From-The-Result-Field-Instead-Of-Contained-Array-Directly

### PR DESCRIPTION
**Pull request by tynyttie**
## Summary
Refactored the `labsAndTests` reducer to retrieve observations from the `result` field rather than directly accessing the `contained` array.

## Related issue(s)
[MHV-60264](https://jira.devops.va.gov/browse/MHV-60264) - In Chem/Hem reducer, pull observation from the result field, instead of contained array directly

In Chem/Hem reducer, pull observation from the result field, instead of contained array directly

Note:  This may be done, please verify and close.

User Story:  As a MR team, we want to  

Feature Flag Y/N ? N

DataDog/Analytics?  Y/N ?

Manual Testing Y/N ?  

Automated Testing Y/N ?

Accessibility Testing Y/N ?  

UCD Validation Y/N N

Acceptance Criteria:
AC1    
AC2   
AC3

AC4

Links to UCD:
Figma Link:   
Other Design Notes

Architectural Notes:

## Testing done
Conducted UI testing to ensure the expected behavior. I updated existing unit test for new components.

## Screenshots
No screenshot available to illustrate the change."

## What areas of the site does it impact?
The modification affects labs and test in Medical Records pages.

## Acceptance criteria
In Chem/Hem reducer, pull observation from the result field, instead of contained array directly 

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Review by mmoyer-va — DISMISSED** [review]
Looks good!

**Review by mattwrightva — COMMENTED** [review]
Did you test these changes with the codespaces mock data to be sure nothing needs to be added?

**Review by powellkerry — DISMISSED** [review]

**Review by mattwrightva — DISMISSED** [review]
Nice!

**Review by mmoyer-va — DISMISSED** [review]
Looks good -- thanks for fixing the mock data.

**Review by mattwrightva — APPROVED** [review]
Looks good!

**Review by powellkerry — APPROVED** [review]

**Pull request merged**
