### PR TITLE
Prevent edit if auth

### PR DESCRIPTION
**Pull request by stephenBarrs**
## Description
When a user has authenticated they should not be able to edit their name and date of birth. These fields will appear on the screen in a greyed out form field that cannot be edited.  When a user has not authenticated they should be able to edit the name and date of birth fields.  

## Testing done
Automated tests confirm fields are disabled when Profile data is used to populate the fields and not disabled otherwise. All tests pass.  

## Screenshots
Unauthenticated flow:
image
test cases:
image

Authenticated flow:
image
test cases:
image

## Acceptance criteria
- [x] Authenticated users are not able to edit the name and DOB fields
- [x] Un-Authenticated users are able to edit the name and DOB fields

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by ncksllvn — APPROVED** [review]
LGTM

**Comment by batemapf** [comment]
should we consider some kind of messaging in the auth'd / grey'd out experience that tells veterans where to go (if somewhere?) if they believe the information is incorrect? it is an edge case, but i can imagine a very frustrating one to be stuck between submitting an incorrect form or not submitting a form at all.

also, i _feel_ like i should ask if the auth/un-auth'd experiences screen shot above are covered by tests :-|

**Comment by stephenBarrs** [comment]
> should we consider some kind of messaging in the auth'd / grey'd out experience that tells veterans where to go (if somewhere?) if they believe the information is incorrect? it is an edge case, but i can imagine a very frustrating one to be stuck between submitting an incorrect form or not submitting a form at all. cc @DanielleThierryUSDSVA for your thoughts here.
Agree for sure.  @ncksllvn is there a link we can provide to an edit Profile page?  

> also, i _feel_ like i should ask if the auth/un-auth'd experiences screen shot above are covered by tests :-|
The unauthenticated flow is tested but not the authenticated flow.  I will add a test for that.

**Comment by DanielleThierryUSDSVA** [comment]
@batemapf @stephenBarrs Adding this here from slack. Agree that we'd want to give folks a way to change their info. And we'll need to change the note in general to reflect that this info is read only. 

**Note:** The information below is from your VA.gov profile. If you need to make a change, [go to your profile now](va.gov/profile/personal-information).

**Comment by batemapf** [comment]
from our mtg today: @stephenBarrs please add a GA event to this current implementation. we'll keep an eye on how many times people are utilizing the link out to profile (with the assumption that a large number will not return). if we see a rate of triple digits / week, then we can discuss further about how to guide people back to the KMI form after profile updates (and will likely need to have a larger convo with platform / public websites about how to do this comprehensively).

**Comment by stephenBarrs** [comment]
Talking to analytics team ( @bsmartin-ep) pointed out that this can be tracked by looking at the `Previous Page Path` of the `/profile` page so we will not need to send another GA event for this.

**Comment by stephenBarrs** [comment]
@batemapf tests have been added and a link to VA Profile is in place along with updated verbiage.  Ready for review!

**Review by batemapf — APPROVED** [review]

**Pull request merged**
