### PR TITLE
adds missing education subtopic flows

### PR DESCRIPTION
**Pull request by joehall-tw**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Are you removing, renaming or moving a folder in this PR?
- [X] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [X] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

- _(Summarize the changes that have been made to the platform)_
N/A
- _(If bug, how to reproduce)_
before this merge, navigate to and select the education/work study topic. There should be a list of subtopics preented.
- _(What is the solution, why is this the solution)_
Added the topic to the whitelist of topics that triggers subtopic selection
- _(Which team do you work for, does your team own the maintenance of this component?)_
AskVA, yes
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_
N/A

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/ask-va#1435
- _Link to previous change of the code/bug (if applicable)_
N/A
- _Link to epic if not included in ticket_
N/A

## Testing done

- _Describe what the old behavior was prior to the change_
Manual testing. Will perform same testing in the promoted environments.
- _Describe the steps required to verify your changes are working as expected_
See description, above.
- _Describe the tests completed and the results_
Before changes, no subtopic page is presented. After changes, subtopic page appears in the flow.
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

Only our own application.

### Quality Assurance & Testing

- [X] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [X] Linting warnings have been addressed
- [X] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by hemeshvpatel — APPROVED** [review]
Lgtm

**Review by CBonade — DISMISSED** [review]
hey there. Super simple on the files changed side, just please ensure the template is filled out before merging. Happy to approve once thats completed.

**Comment by joehall-tw** [comment]
@CBonade - I edited the description. Most had content, but I got lazy on the formatting. That's corrected now, and I added a bit more detail. Thanks!

**Review by joehall-tw — COMMENTED** [review]
I think I've addressed the missing template response. Let me know if you need anything else.

**Review by ataker — APPROVED** [review]

**Pull request merged**
