### PR TITLE
61692 Update the static landing page (Public Websites)

### PR DESCRIPTION
**Pull request by vbahinwillit**
## Summary
This PR fixes the CernerCallToAction widget to only display the new format for the VAOS application only when the feature flag is on.

## How to test locally
Prerequisites
- The file 'build/localhost/data/cms/vamc-ehr.json' must exist.
- Add browser Local Storage variable 'hasSession' = true

Add the following entries to registry.scaffold.json
```
{
    "appName": "Refill and track VA prescriptions",
    "rootUrl": "/health-care/refill-track-prescriptions",
    "widgetType": "refill-track-prescriptions-page"
  },
  {
    "appName": "VA secure messaging",
    "rootUrl": "/health-care/secure-messaging",
    "widgetType": "secure-messaging-page"
  },
  {
    "appName": "Get your VA medical records online",
    "rootUrl": "/health-care/get-medical-records",
    "widgetType": "get-medical-records-page"
  },
  {
    "appName": "View your VA lab and test results online",
    "rootUrl": "/health-care/view-test-and-lab-results",
    "widgetType": "view-test-and-lab-results-page"
  }
```
Change the following facility to Cerner in vamc-ehr.json
```
        {
          "title": "Cheyenne VA Medical Center",
          "fieldFacilityLocatorApiId": "vha_442",
          "fieldRegionPage": {
            "entity": {
              "title": "VA Cheyenne health care",
              "fieldVamcEhrSystem": "cerner"
            }
          }
        },

```
Change the facility id of the mock user to 442 in ../vaos/services/mocks/index.js
```
          facilities: [
            {
              facility_id: '442',
              is_cerner: false,
            },
            {
              facility_id: '984',
              is_cerner: false,
            },
          ],
```
Toggle the 'vaOnlineSchedulingStaticLandingPage' feature flag to true in ../vaos/services/mocks/index.js

Run the following commands in a terminal from the vets-website directory:

- yarn watch
- yarn run mock-api --responses ./src/applications/vaos/services/mocks/index.js

In a browser, navigate to the following:
http://localhost:3001/health-care/refill-track-prescriptions/
http://localhost:3001/health-care/secure-messaging/
http://localhost:3001/health-care/schedule-view-va-appointments/
http://localhost:3001/health-care/view-test-and-lab-results/
https://staging.va.gov/health-care/get-medical-records/

## Related issue(s)
department-of-veterans-affairs/va.gov-team#61692

## Testing done
Unit testing

### Feature flag on
**Expected:**
Should show new layout
localhost_3001_health-care_schedule-view-va-appointments_ (4)

### Feature flag off
**Expected:**
Should show original layout
localhost_3001_health-care_schedule-view-va-appointments_ (5)

### Feature flag on
**Expected:**
Should show original layout
localhost_3001_health-care_refill-track-prescriptions_

### Feature flag on
**Expected:**
Should show original layout
localhost_3001_health-care_secure-messaging_

### Feature flag on
**Expected:**
Should show original layout
localhost_3001_health-care_view-test-and-lab-results_

### Feature flag on
**Expected:**
Should show original layout
localhost_3001_health-care_get-medical-records_

## What areas of the site does it impact?
Public website static landing page

## Acceptance criteria
All test should pass

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by randimays** [comment]
@vbahinwillit Could you provide a bit more context and screenshots in the PR description?

**Review by simiadebowale — APPROVED** [review]
LGTM

**Comment by randimays** [comment]
@vbahinwillit The expectation is that both the MHV and Cerner sides of **all 5 Cerner widgets** are thoroughly tested before requesting review from PW. When you are ready for us to review, please provide valid test users for us to look it over in the review instance.

**Comment by vbahinwillit** [comment]
@randimays - I do not know how to do what you are asking in the review instance. The api request to get vamc-ehr.json is failing in the review instance. I have tested locally all 5 Cerner widgets and added unit tests. I need your help or someone from your team with this.

**Comment by jilladams** [comment]
@vbahinwillit @randimays  Started a slack thread, https://dsva.slack.com/archives/C52CL1PKQ/p1692214229041639

**Review by jenniemc — APPROVED** [review]
LGTM

**Review by randimays — APPROVED** [review]
LGTM

**Pull request merged**
