### PR TITLE
32199 Vaccine Contact Facility copy doc update

### PR DESCRIPTION
**Pull request by cferris32**
## Description
This is a content update to the vaccine contact facility page, changes further outlined in screenshots below.

## Original issue(s)
department-of-veterans-affairs/va.gov-team#32199

## Screenshots
Old content:
image

New content:Screen Shot 2021-11-16 at 3 46 49 PM

## Acceptance criteria
- [x] content updated

### CODE REVIEW

**Comment by outerpress** [comment]
@cferris32  the content looks great, just a couple notes about the  text "Here's what to know:"
* Should be left-aligned to the header
* Should not be bold

**Comment by cferris32** [comment]
Newest visual:
Screen Shot 2021-11-17 at 3 16 03 PM

**Comment by outerpress** [comment]
> Newest visual: Screen Shot 2021-11-17 at 3 16 03 PM

Looks great @cferris32 !

**Review by vbahinwillit — APPROVED** [review]
LGTM!

**Comment by vbahinwillit** [comment]
FYI, Don't forget to merge the latest changes from master into the branch before your merge. Thanks

**Pull request merged**
