### PR TITLE
I added the TTY number to help dropdown and footer

### PR DESCRIPTION
**Pull request by ghost**
@jcmeloni-usds can you see if we can get the header tty number on one line?

### CODE REVIEW

**Comment by jcmeloni-usds** [comment]
I'm a-lookin', @amybehrens, and also I will make those other changes we discussed and tack them on here.

**Comment by jcmeloni-usds** [comment]
@tiffanybbrown-va could you see if we can get the TTY in the dropdown not to break to a new line? 

@rroueche we edited the style around tel numbers we could find -- could you review? it's deployed to heroku.

**Comment by rroueche** [comment]
@jcmeloni-usds is there a class we need to apply to the phone numbers on the md pages? this one for example doesn't have a special class or anything, and also has no special formatting:  https://vetsgov-pr-5224.herokuapp.com/disability-benefits/conditions/ptsd/

**Comment by jcmeloni-usds** [comment]
@rroueche Yes! and it's not special, just an `<a>` tag.  For example:

`<a href="tel:+15555551212">555-555-1212</a>`

**Comment by rroueche** [comment]
oh excellent, ok cool. I saw a couple other locations where that was in use, and looks good to me. I'm also going to pass to @amybehrens to give a once-over. 

@jcmeloni-usds i think i know what the conflicts are about - would you like me to resolve those?

**Comment by jcmeloni-usds** [comment]
@rroueche It would be awesome if you resolved the conflicts; i wouldn't get to it for a bit.  Thanks!

**Comment by rroueche** [comment]
@jcmeloni-usds ok i'm on it - should have 'em done here in a few.

**Comment by rroueche** [comment]
@jcmeloni-usds I made one fix, but it looks like Jenkins is encountering a 'nightwatch' error? I'm not familiar with what that is, but if there's anything else I can/should adjust on my side, let me know!

**Comment by jcmeloni-usds** [comment]
@tiffanybbrown-va can you see what the error is? (I don't have access :))

**Comment by amybehrens** [comment]
@rroueche this looks good to me (there are a few pages I can't load in herokuapp, but the pages I could see look good). Yay for mobile-friendly phone numbers! Thanks @jcmeloni-usds!

**Comment by rroueche** [comment]
@jcmeloni-usds here's the error:

**Comment by tiffanybbrown-va** [comment]
Also some conflicts on this PR.

**Comment by jcmeloni-usds** [comment]
@rroueche would you be so kind as to fix the merge conflict and then I think we're good to go on this? Your call -- not sure if you're thumbs up across the board.

**Comment by rroueche** [comment]
one sec - I found a few more instances of the old format, so I'm updating those locally real quick and will sync them up here.

**Comment by jcmeloni-usds** [comment]
Ok! Thank you @rroueche -- I think this is good to go if @tiffanybbrown-va can suggest a solution for fitting the TTY info on one line in the drop-down.  I would be apt to make the menu 3px wider or something but please do not let my hacky impulses dictate that.....

**Review by rroueche — APPROVED** [review]
Yes, all looks good to me!

**Comment by jcmeloni-usds** [comment]
@tiffanybbrown-va can you see why the TTY line is breaking to 2, please?  Then we can merge this...

**Comment by jcmeloni-usds** [comment]
Thank you!  Pressing the button on this.  @amybehrens can finally celebrate :tada:

**Pull request merged**
