### PR TITLE
Tweaks to account profile page

### PR DESCRIPTION
**Pull request by aub**
Connects to department-of-veterans-affairs/vets.gov-team#3272

This makes a few tweaks to the account profile page as described here: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3272

Here is what it looks like on my machine for LOA3. Note that the name, DOB, and sex are weird because I'm not actually LOA3 locally:

screen shot 2017-06-20 at 4 17 30 pm

And for LOA1:

screen shot 2017-06-20 at 4 17 47 pm

### CODE REVIEW

**Review by melwoodard — APPROVED** [review]
Looks good from a design/functional perspective.

**Comment by raquelromano-gov** [comment]
Should "Get your VA health care records" show up in the bottom list when you're LOA1?

**Comment by raquelromano-gov** [comment]
You may want to edit the first line of the PR description to `Closes department-of-veterans-affairs/vets.gov-team#3272` since this doesn't actually close it (looks like there will be more changes rolling in as other stuff launches and that issue will track those)

**Review by bshyong — APPROVED** [review]
^ I don't know definitively which apps are LOA1 vs LOA3 but code changes LGTM

**Comment by leannammiller** [comment]
@bshyong would you please you merge this in for Aubrey?

**Comment by raquelromano-gov** [comment]
I updated the description to "Connects to..." so that https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3272 stays open for the other features that will be added over the next few weeks

**Pull request merged**
