### PR TITLE
Content/wip/change disability claim questions

### PR DESCRIPTION
**Pull request by kellyskennedy**
Updated three pages so questions are now answers and match our style: https://www.vets.gov/disability-benefits/after-you-apply/date/

https://www.vets.gov/disability-benefits/apply/one-year/

https://www.vets.gov/disability-benefits/apply/help/

#6206

### CODE REVIEW

**Comment by kellyskennedy** [comment]
Could you review this, please, @peggygannon ?

**Review by peggygannon — COMMENTED** [review]
@kellyskennedy I wanted you to see some of my edits. In addition to making sure the related links matched the page heads, I checked that links still linked to the same page. Also, I updated instances of "pre-discharge" on some of the pages these related links link to. Let me know if you have any questions about my changes!

**Comment by kellyskennedy** [comment]
@peggygannon Yikes. Okay--I'll make sure to check that in the future. Thanks!

**Comment by peggygannon** [comment]
@bethpotts This PR is ready for your ME review.

**Comment by bethpotts** [comment]
@kellyskennedy You can work with Sophia or Nick on getting this reviewed and merged. It's ready to go!

**Comment by kellyskennedy** [comment]
@phiden could you review and merge this, please? Thanks!

**Review by phiden — APPROVED** [review]

**Pull request merged**
