### PR TITLE
added SR audio feedback to zipcode entry

### PR DESCRIPTION
**Pull request by ksantiagoBAH**
## Description
As a screen reader user, I want to understand that I've entered a zip code correctly, and the UI has returned a valid city. I want to hear either the valid city + state read aloud, or the error message as a call to correct my entry.

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1655

## Testing done
1. Navigate to http://localhost:3001/gi-bill-comparison-tool/profile/11806124
2. activate voice over
3. Find the question Where will you take the majority of your classes? 
4. select the "An extension campus" radio button
5. other from the "Choose the location where you'll take your classes" drop down.
6. select a valid zip code
7. "Your postal code is located in..." will be heard by the user user using voiceover but not seen by a user not using voice over.

## Acceptance criteria
- [x] I want to hear either the valid city + state read aloud, or the error message as a call to correct my entry.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by sonntag-adam — APPROVED** [review]

**Review by 1Copenut — CHANGES_REQUESTED** [review]
@ksantiagomorgan6 Is there a way we can put the `<p>` tag in the DOM on first paint? There generally needs to be an empty container for the aria-live flag to attach itself to. By adding the tag when we show the Other entry field, NVDA and JAWS won't work correctly.

In this case, VO gives us a false sense of affirmation.

LMK if you want to discuss further.

**Comment by sonntag-adam** [comment]
@1Copenut new changes were made

**Review by 1Copenut — CHANGES_REQUESTED** [review]
I checked this feature update on my local machine, and VoiceOver was still announcing the city message too early. The `<div>` and the `<p>` you're using for the live region need to be on the page all the time as empty containers, and then add the label and input when users select "Other" from the previous dropdown to make assistive tech behave correctly.

Feel free to ping me on Monday if you'd like to chat over Slack.

---
Screen Shot 2019-09-13 at 4 33 51 PM

**Review by sonntag-adam — APPROVED** [review]

**Comment by sonntag-adam** [comment]
@1Copenut new changes were made

**Review by 1Copenut — APPROVED** [review]
I tried this out on `localhost` with Safari. I don't have access to the background data to test 1:1 with staging, but met with @ksantiagomorgan6 today and have confidence the fix will work based on his testing with QA team.

Please let me know when this is in Staging and I will test again with NVDA and JAWS for completeness.

**Review by rianfowler — APPROVED** [review]

**Pull request merged**
