### PR TITLE
VACMS 12905 - Add h2 for screen reader to map in FL

### PR DESCRIPTION
**Pull request by eselkin**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

## Summary

- Adds sr-only h2 for map results
- Sitewide team

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12905

## Testing done

- Tested locally

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |    Screenshot 2024-07-18 at 1 02 03 PM    |   Screenshot 2024-07-18 at 1 00 29 PM    |
| Desktop |     Screenshot 2024-07-18 at 1 02 26 PM   |    Screenshot 2024-07-18 at 12 59 07 PM   |

## What areas of the site does it impact?

Facility locator only

## Acceptance criteria
- [x] Add visually hidden H2 heading ("Map of Results") for the map section of the page
- [x] The class sr-only is used to hide the heading
- [ ] Accessibility lead review

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user (unauthenticated)

## Requested Feedback

view /find-locations search for something, check screen reader response or check markup for page to see h2 with sr-only class

### CODE REVIEW

**Comment by laflannery** [comment]
@eselkin I didn't think of this before but is it possible to make this heading conditional, like the results information currently is?

Right now it's exactly where I wanted it but it doesn't make sense within the context of the page, I haven't searched for anything yet so I don't have any results:
image

However, once you search for something this suddenly makes so much more sense:
image

If that's not possible let me know, thanks!

**Comment by eselkin** [comment]
Let me check if possible

**Comment by eselkin** [comment]
@laflannery Whenever it builds again (hopefully picked up by RI) the h2 for screen readers now only displays when there is a results list (a search has been performed).

**Comment by laflannery** [comment]
@eselkin you're my hero!

**Review by laflannery — APPROVED** [review]

**Review by chriskim2311 — APPROVED** [review]
LGTM

**Pull request merged**
