### PR TITLE
Add Toggler and useFeatureToggle hook to platform folder code

### PR DESCRIPTION
**Pull request by adamwhitlock1**
## Summary

- Provides a `Toggler` component to access feature toggle values in a more uniform way.
- Provides a hook `useFeatureToggle` that can be used to access a feature toggle value directly.
- Several individuals have asked about this component, so I moved it into the platform folder code so that it could be used outside the Profile application.

### Two ways to use the Toggler component:

1. Import the Toggler and then use the shared context and compound components to display and hide react components based on the feature toggle value:

```jsx
<Toggler toggleName={Toggler.TOGGLE_NAMES.someToggle}>
    <Toggler.Enabled>
        <p>Enabled</p>
    </Toggler.Enabled>

    <Toggler.Disabled>
        <p>Disabled</p>
    </Toggler.Disabled>
</Toggler>
```

2. Use a High Order Component (HOC) to access the toggle value. This can be useful for using the toggle value inside a Class Based Component, or if you need to do something other than just conditionally render based on the value.

```jsx
<Toggler.Hoc toggleName={Toggler.TOGGLE_NAMES.someToggle}>
        {toggleValue => <p>{toggleValue ? 'Yay its enabled' : 'Boo it is disabled'}</p>}
</Toggler.Hoc>,
```

### Using the `useFeatureToggle` hook

The hook provides a way to get the toggle value with a simple hook that provides a secondary hook `useToggleValue` along with the main list `TOGGLE_NAMES`.

```jsx
const { useToggleValue, TOGGLE_NAMES } = useFeatureToggle();

const toggleValue = useToggleValue(TOGGLE_NAMES.someToggle);
```

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/56003

## Testing done

- Unit tests written for component and hook
- Toggler is currently in use in the Profile and has been working well

## Screenshots
No UI based changes

## What areas of the site does it impact?
Right now just Profile, and adds new functionality to Platform

## Acceptance criteria

- [ ] Feature toggle hook and component available via platform utilities

## Requested Feedback

If this addition is acceptable to Platform, how can we update the feature toggle guidance to use these? I think I got the exportsFile edits correct, but not 100% sure on that.

### CODE REVIEW

**Review by allisonlu — APPROVED** [review]
lgtm on the frontend. but not sure about the exportsFile.js exports

**Comment by rmessina1010** [comment]
I like this! LGTM.

**Comment by adamwhitlock1** [comment]
@rmessina1010 I actually noticed I didn't get an approval on this ;) if you get a moment to approve that would be great.

**Review by rmessina1010 — APPROVED** [review]
Liking this where this is going. Approved.

**Pull request merged**
