### PR TITLE
(Refactor): Move to useSelector hook

### PR DESCRIPTION
**Pull request by mdewey**
## Description
- Deprecating the `mapStateToProps` in favor of [redux hooks](https://react-redux.js.org/api/hooks)

## Original issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/31557

## Testing done
- non yet

### CODE REVIEW

**Comment by mdewey** [comment]
Looks like a bad merge. No need to review from all the teams yet. Looking into why

**Review by dcgoodwin2112 — APPROVED** [review]
It looks like a todo markdown file accidentally made it into the commit, but everything else looks great to me. All tests run and pass locally.

**Comment by mdewey** [comment]
Good Catch @dcgoodwin2112 , Removed todo and will merge after CI

**Review by acrollet — CHANGES_REQUESTED** [review]
I'm seeing an odd issue with the `src/applications/health-care-questionnaire/list/utils/tests/order.questionnaire.by.date.unit.spec.js` test - it's failing on CI and fails for me locally, passes on master. Digging in a little...

**Comment by acrollet** [comment]
> I'm seeing an odd issue with the `src/applications/health-care-questionnaire/list/utils/tests/order.questionnaire.by.date.unit.spec.js` test - it's failing on CI and fails for me locally, passes on master. Digging in a little...

I merged master, hopefully that's all it will take.

**Comment by mdewey** [comment]
@acrollet  Here is chatter around the failing tests: https://dsva.slack.com/archives/C37M86Y8G/p1635790695108200

**Review by acrollet — APPROVED** [review]
looks like that did it!

**Comment by acrollet** [comment]
@mdewey sorry for the noise, this should be good to merge now!

**Pull request merged**
