### PR TITLE
DO NOT MERGE: VAGOV-1810 (refactor) && VAGOV-1811

### PR DESCRIPTION
**Pull request by aurora-a-k-a-lightning**
## Description
VAGOV-1810: Refactor regional health care services to use node
VAGOV-1811: Add local health care description to local facilities

### 1810: regional refactor
localhost_3001_pittsburgh-health-care-old_health-services_index html
## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by acabouet** [comment]
Code looks good! On staging health services with no content show an empty accordion - see health & wellness: https://staging.va.gov/pittsburgh-health-care/health-services/ An 'if' statement before the list starts in the health_service template would fix it. Within the scope of this ticket?

**Comment by ahay-agile6** [comment]
> Code looks good! On staging health services with no content show an empty accordion - see health & wellness: https://staging.va.gov/pittsburgh-health-care/health-services/ An 'if' statement before the list starts in the health_service template would fix it. Within the scope of this ticket?

@acabouet there actually is an `if` statement surrounding all of those accordions! but, there was an incorrect variable reference for the wellness services one. thanks for pointing that out 😄

**Review by jbalboni — APPROVED** [review]
LGTM, looks like we just need to wait for Drupal to be updated.

**Comment by ElijahLynn** [comment]
This corresponds to https://github.com/department-of-veterans-affairs/va.gov-cms/pull/268

**Review by acabouet — APPROVED** [review]

**Pull request closed without merging**
