### PR TITLE
Create field

### PR DESCRIPTION
**Pull request by DanielleSoCompany**
## Description
Creating to view content in heroku

## Testing done
NA

## Testing Plan
NA

## Screenshots
NA

## Acceptance Criteria (Definition of Done)
Copy and URL finalized
#### Unique to this PR
- [ ] Content written
- [ ] Content edited
- [ ] Content reviewed by dev

#### Applies to all PRs

- [ ] Appropriate logging
- [ ] Documentation has been updated, if applicable
- [ ] Provide link to originating GitHub issue, or connected to it via ZenHub
- [ ] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [ ] Provide which alerts would indicate a problem with this functionality (if applicable)

### CODE REVIEW

**Comment by bethpotts** [comment]
@ncksllvn Two things about this one.
- Again, the left nav isn't there.
- There's one page that hasn't been entered into github yet, but we link to it from this page. The file has been created, but it's blank. That's intentional at this point. We're waiting to hear back from Andy on Monday if that's the way he wants it.
For now, we're good with it and you can merge this.

**Comment by bethpotts** [comment]
@ncksllvn Sorry, I didn't tell you which page is blank: Get Paid Back for Testing Fees

**Comment by ncksllvn** [comment]
Thank you @bethpotts for the clarification!

**Review by ncksllvn — APPROVED** [review]
👍 The mappings spreadsheet is a little weird about this - there are two files that both point to using `/education/about-gi-bill-benefits/how-to-use-benefits/test-fees/`:

- `www.vets.gov/education/advanced-training-and-certifications/licensing-certification/`
- `www.vets.gov/education/advanced-training-and-certifications/national-testing-program/`

I used the top one to populate that empty page, but obviously it can be blanked out if you prefer.

**Comment by ncksllvn** [comment]
I also had to add a stub for `va-gov/pages/education-training/gi-bill.md`  because that was generated as part of the breadcrumbs for `va-gov/pages/education-training/gi-bill/how-to-use-benefits.md`, and it didn't exist so the build was failing.

**Comment by mnorthuis** [comment]
The reason there are 2 pages pointing to the /test-fees/ page is because they are being combined.  So both the old pages need to be redirected to the new page.  

Also, the URLs you have for the gi bill page are both incorrect, I'm not sure where those URLs came from?  The correct ones are below.  "training" is not part of the URL, and the second level should have "about" and "benefits" in it. 
/education/about-gi-bill-benefits/
/education/about-gi-bill-benefits/how-to-use-benefits/

**Pull request merged**
