### PR TITLE
7753: Remove unnecessary 22-1995 artifacts

### PR DESCRIPTION
**Pull request by elder-joseph**
## Description
As a developer, I need to remove the 1995 steps that are included in the new STEM form so that only the necessary data is collected in the new form.

[Origination Issue](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7753)

## Testing done
Testing passes locally

## Acceptance criteria
- [x] The following steps are removed from the new form workflow:
  - [x] Step 3 of 6 Military History (Periods of Service)
  - [x] Step 3 of 6 Military History (1978)
  - [x] Step 4 of 6 School Selection (Want to Attend)
  - [x] Step 4 of 6 School Selection (Last Attended)
  - [x] Step 5 of 6 Personal Information
- [x] The new form number 22-10203 is displayed in place of 22-1995 in the workflow.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — CHANGES_REQUESTED** [review]
I think we still need contact information. I don't think we need serviceBefore1977. Is that still in the 10203 schema?

**Comment by elder-joseph** [comment]
> I think we still need contact information. I don't think we need serviceBefore1977. Is that still in the 10203 schema?

I think you're right, I'll add contact information back in and can take serviceBefore1977 out. I did not see serviceBefore1977 in the 10203 schema.

**Comment by elder-joseph** [comment]
@shawkey-daniel also It looks like this `chapter.js` is still using the 1995 schema in some places for example:
`contactInformation: createContactInformationPage(fullSchema1995),`

Should this be updated in this PR or is that being handled elsewhere?

**Comment by shawkey-daniel** [comment]
It should be updated to use the 10203 schema instead of 1995 if possible.

**Comment by shawkey-daniel** [comment]
> @shawkey-daniel also It looks like this `chapter.js` is still using the 1995 schema in some places for example:
> `contactInformation: createContactInformationPage(fullSchema1995),`
> 
> Should this be updated in this PR or is that being handled elsewhere?

It should be updated to use the 10203 schema instead of 1995 if possible.

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by sonntag-adam — APPROVED** [review]

**Review by zurbergram — APPROVED** [review]

**Pull request merged**
