### PR TITLE
[CMS] Allow build step for generating outreach-assets.json to fail outside of prod

### PR DESCRIPTION
**Pull request by ncksllvn**
## Description
Because of a migration error, builds for Dev/Staging were recently failing during this build step. Since CMS build errors are acceptable in Dev/Staging (broken links, etc), it makes sense for build errors to be acceptable during this step as well for Dev/Staging.

## Testing done
Ran local builds and read the output 

## Acceptance criteria
- [ ] Builds pass in dev/staging

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by ethanteague — APPROVED** [review]

**Comment by jbalboni** [comment]
@ncksllvn Don't we want to catch these kinds of errors in builds? Broken links are a unique case in that they happen for in progress content and they don't mean anything is actually broken. But for all other errors, I think we'd want to know something is wrong and have to fix it. That's the main way we'll catch issues before changes make it into cms prod.

**Comment by ncksllvn** [comment]
@jbalboni That works for me! I suppose I was thinking that on Dev/Staging, if the whole Drupal API is down, we still carry on the build, just without the HC section. WIth this build step, the build carries on to this point, where it errors out because the Drupal data is empty. So in our output, it looks like the problem was at this step, when the problem originated at the `metalsmith-drupal` build step. Maybe we should throw the error there if the server responds with `500` or another error?

**Comment by jbalboni** [comment]
@ncksllvn I believe we're failing the build for any drupal error on dev/staging. We weren't doing that temporarily, but I switched it back a while ago.

**Comment by ncksllvn** [comment]
@jbalboni Ah yeah you're right, just checked the source. That sounds good to me! I'll close this.

**Pull request closed without merging**
