### PR TITLE
Copy change on calculator results for OJT

### PR DESCRIPTION
**Pull request by bshyong**
Resolves https://github.com/department-of-veterans-affairs/vets-website/issues/5403

### CODE REVIEW

**Review by U-DON — COMMENTED** [review]
I don't think we want to show the '/mo' on every `CalculatorResultRow`. And we should only show it if the institution is OJT.

I would make the change in selectors/calculator.js to add the '/mo' if it's OJT, similar to how it's being handled for `bookStipend`.

**Comment by bshyong** [comment]
looks like conditionally adding `/mo` will cause the total calculation to fail somewhere

screen shot 2017-04-24 at 4 25 07 pm

**Comment by U-DON** [comment]
In that screenshot, the terms are fall and spring, which means this is appearing in a non-OJT institution. It shouldn't be a problem if you also check for the institution type in the condition.

**Review by U-DON — COMMENTED** [review]
After some debugging, the errors have been resolved. LGTM.

**Pull request merged**
