### PR TITLE
mock Fetch calls in MHV medications unit tests

### PR DESCRIPTION
**Pull request by dcloud**
## Summary

- Look for tests that don't already mock api requests, e.g.:
`rg --files-without-match 'mock(ApiRequest|Fetch)' src/applications/mhv/medications/tests/`
- Add `mockFetch` and `resetFetch` where useful
- Update exports for `src/platform/testing/unit/helpers.js` so that eslint stops complaining

## Related issue(s)

- https://jira.devops.va.gov/browse/MHV-55037
> Pager duty - change unit tests to mock API

## Testing done

- Before these changes, unit tests might make calls to `*.va.gov` APIs. Used Wireshark to monitor for calls to `*.va.gov` while running tests with `NODE_OPTIONS='--tls-keylog="/Users/dcloud/ssl_key_log_file.log"'`

## What areas of the site does it impact?

Unit tests in `src/mhv/medications/tests`.

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by dcloud** [comment]
It looks like I might have to make some changes to `src/platform/testing/unit/` exports due to eslint errors.

**Review by agravell047 — APPROVED** [review]

**Review by vmenshutin-bylight — APPROVED** [review]

**Comment by dcloud** [comment]
@acrollet These are the changes I came up with for preventing unit tests from making external API calls. Can you verify?

Also, do you think your [fail unit tests when network calls are detected](https://github.com/department-of-veterans-affairs/vets-website/pull/24631/files) PR will get resurrected? Wondering if there's work planned to identify similar issues when tests are being written, or prevent network calls from unit tests

**Review by acrollet — COMMENTED** [review]
This is a great start, and I really like the improvements to the platform testing file! Not sure of the intended scope but I'm still seeing some un-mocked calls:

```
  1) Get prescription list action
       should dispatch a get paginated, sorted list action:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions?page=1&per_page=20. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  2) Get allergies action
       should dispatch a get allergies list action:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/medical_records/allergies. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  3) Get allergies action
       should dispatch an get list error:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/medical_records/allergies. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  4) Get prescription details action
       should dispatch a get details action:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions/undefined. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  5) Fill prescription action
       should dispatch a clear error action:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions/undefined/refill. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  6) Fill prescription action
       should dispatch a fill prescription error:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions/undefined/refill. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  7) Fill Refill Button component
       dispatches fillPrescription action and shows correct loading message:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions/1234567890/refill. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  8) Prescription details container
       renders without errors:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/medical_records/allergies. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  9) Prescription details container
       should display loading message when loading specific rx:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/medical_records/allergies. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  10) Prescription details container
       displays the prescription name and filled by date:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/medical_records/allergies. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  11) Prescription details container
       displays "Not filled yet" when there is no dispense date:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/medical_records/allergies. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  12) Prescription details container
       displays "Documented on" instead of "filled by" date, when med is non VA:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/medical_records/allergies. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  13) Medications Prescriptions container
       renders without errors:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions?page=1&per_page=20&sort[]=-dispensed_date&sort[]=prescription_name. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  14) Medications Prescriptions container
       should display loading message when loading prescriptions:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions?page=1&per_page=20&sort[]=-dispensed_date&sort[]=prescription_name. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  15) Medications Prescriptions container
       displays intro text :
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions?page=1&per_page=20&sort[]=-dispensed_date&sort[]=prescription_name. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  16) Medications Prescriptions container
       shows title :
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions?page=1&per_page=20&sort[]=-dispensed_date&sort[]=prescription_name. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  17) Medications Prescriptions container
       should show the allergy error alert:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions?page=1&per_page=20&sort[]=-dispensed_date&sort[]=prescription_name. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  18) Medications Prescriptions container
       displays text inside refill box "find a list of prescriptions you can refill online." when refill flag is true:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions?page=1&per_page=20&sort[]=-dispensed_date&sort[]=prescription_name. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  19) Refill Prescriptions Component
       renders without errors:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions/list_refillable_prescriptions. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  20) Refill Prescriptions Component
       should render loading state:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions/list_refillable_prescriptions. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  21) Refill Prescriptions Component
       Shows 404 page if feature toggle is disabled:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions/list_refillable_prescriptions. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  22) Refill Prescriptions Component
       Shows h1 and h2:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions/list_refillable_prescriptions. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  23) Refill Prescriptions Component
       Shows the request refill button:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions/list_refillable_prescriptions. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  24) Refill Prescriptions Component
       Shows the select all button:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions/list_refillable_prescriptions. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  25) Refill Prescriptions Component
       Clicks the medications list page link:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions/list_refillable_prescriptions. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  26) Refill Prescriptions Component
       Shows the correct "last filled on" date for refill:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions/list_refillable_prescriptions. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  27) Refill Prescriptions Component
       Shows the correct "last filled on" date (w/rxRfRecords) for refill:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions/list_refillable_prescriptions. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  28) Refill Prescriptions Component
       Checks the checkbox for first prescription:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions/list_refillable_prescriptions. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  29) Refill Prescriptions Component
       Unchecks the checkbox for first prescription:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions/list_refillable_prescriptions. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  30) Refill Prescriptions Component
       Shows the correct text for one prescription:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions/list_refillable_prescriptions. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

  31) Refill Prescriptions Component
       Completes api request with selected prescriptions:
     Error: Network call made to https://dev-api.va.gov/my_health/v1/prescriptions/list_refillable_prescriptions. Please mock this call with mockFetch.
      at checkForNetworkCalls (src/platform/testing/unit/mocha-setup.js:187:13)
      at Context.afterEach (src/platform/testing/unit/mocha-setup.js:213:5)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)
```
      
Perhaps it's happening because `mockFetch` only mocks one call at a time?

**Comment by acrollet** [comment]
> Also, do you think your [fail unit tests when network calls are detected](https://github.com/department-of-veterans-affairs/vets-website/pull/24631/files) PR will get resurrected? Wondering if there's work planned to identify similar issues when tests are being written, or prevent network calls from unit tests

This is a great question! Tagging @CBonade, who was working on discovery for the frontend CoP 🙂

**Comment by dcloud** [comment]
> This is a great start, and I really like the improvements to the platform testing file! Not sure of the intended scope but I'm still seeing some un-mocked calls:

@acrollet That's odd. I was monitoring the actual network calls in Wireshark, and multiple test runs yielded no network calls. So either Wireshark is missing things, or `checkForNetworkCalls` isn't working as expected in conjunction with `mockFetch`.

**Review by jamigibbs — APPROVED** [review]

**Pull request merged**
