### PR TITLE
VAOS V0 FE removal: remove getRequestMessages

### PR DESCRIPTION
**Pull request by ryanshaw**
This PR removes the `getRequestMessages` function from the VAOS application, it was only used when using V0. 

## Summary

- In `vets-website/src/applications/vaos/services/var/index.js`) the `getRequestMessages` function was removed
- e2e tests were updated
- Unit tests were updated

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/53087

## Testing done

- e2e testing
- Unit testing

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  [Accessibility foundational testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### CODE REVIEW

**Review by vbahinwillit — CHANGES_REQUESTED** [review]
I think the following should be removed as well:

appointment-list.cypress.spec.js:11,258
community-care.cypress.spec.js:12,21
appointment-list/redux/reducers:54
appointment-list/redux/selectors:160,239
va-appointment.cypress.spec.js:13,38
va-request.cypress.spec.js:6,30,110
vaos-cypress-helpers.js:622

**Comment by ryanshaw** [comment]
@vbahinwillit Good catch. I'm working on a few other ones and noticed the mock stuff needing to be removed.

**Comment by ryanshaw** [comment]
@vbahinwillit I made the changes on this, good catch.

**Review by vbahinwillit — COMMENTED** [review]
LGTM!

**Review by vbahinwillit — APPROVED** [review]

**Pull request merged**
