### PR TITLE
Sign-in widget: Remove some widget post-signin-alert content

### PR DESCRIPTION
**Pull request by dcloud**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

- Removed content from widgets that is or will be obsolete as accepted account types changes
- Removed a broken link to an MHV National Portal Classic page about MHV account types. MHV  login accounts are going away January 2025
- Removed mention of Premium MyHealtheVet account from ServiceProvidersList component

## Related issue(s)

- department-of-veterans-affairs/va.gov-team/issues/98147
- department-of-veterans-affairs/va.gov-team/issues/97279

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  | Screen Shot 2024-12-03 at 13 51 08 | Screen Shot 2024-12-03 at 14 01 56 |
| Desktop |  Screen Shot 2024-12-03 at 13 50 58 | Screen Shot 2024-12-03 at 14 01 33 |

## What areas of the site does it impact?

These changes impact _widgets_ that get embedded on static pages. The following are some paths that embed widgets that used this text.

- `/health-care/schedule-view-va-appointments/`
- `/health-care/refill-track-prescriptions/`
- `/health-care/secure-messaging/`
- `/health-care/view-test-and-lab-results/`
- `health-care/get-medical-records/`

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

Should I delete `ServiceProvidersList.jsx` if this PR removes all the places it is currently used?

### CODE REVIEW

**Comment by dcloud** [comment]
Another CI failure: `cp: cannot stat 'qa-standards-dashboard-data/src/allow-list/data': No such file or directory`

**Comment by dcloud** [comment]
More CI error nonsense `cp: cannot stat 'qa-standards-dashboard-data/src/allow-list/data': No such file or directory`

**Review by IGallupSoCo — DISMISSED** [review]
LGTM

**Comment by dcloud** [comment]
Per [this platform support thread](https://dsva.slack.com/archives/CBU0KDSB1/p1733514034038189), there are CI errors that affect PRs like this one. The errors are in CI itself, not the PR

**Review by asg5704 — CHANGES_REQUESTED** [review]
Can you revert the components you deleted in our authentication/componenents please and thank you.

**Comment by dcloud** [comment]
> Can you revert the components you deleted in our authentication/componenents please and thank you.

Reverted the component removal. Identity team should own removal of unreferenced components

**Review by asg5704 — APPROVED** [review]
Thank you

**Review by eselkin — APPROVED** [review]
LGTM

**Pull request merged**
