### PR TITLE
[CDP] VBA payment history remove payment disclaimer and heading updates 

### LINKED ISSUE #93565: [CDP] VBA Payment History Overview heading updates to match design
## Issue Description
Given: A veteran visits the CDP  
When: The veteran views the overpayments summary page
Then: They should see a [simplified header view](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=2075-17888&node-type=frame&t=UV65Nj1cIaZp65Dh-11) without the payment disclaimer now that [payment history for VBA is 100% live](https://dsva.slack.com/archives/CPE4AJ6Q0/p1727104980842939).

Follow-up to https://github.com/department-of-veterans-affairs/va.gov-team/issues/86972 

**Current version:** 

**Proposed version:**

## Tasks
- [x] Updated heading structure, remove redundant `h2`
- [x] Turn cards into `h2`

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [ ] Headings have been updated and payment disclaimer info has been removed.

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

### PR DESCRIPTION
**Pull request by josephrlee**
## Are you removing, renaming or moving a folder in this PR?
- [X] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

## Summary

- Changed headings to `h2s` from `h3s` to have correct heading maps
- Removed outdated payment disclaimer info from detail and debt summary page
- Updated overview page payment disclaimer to be specific to just copays now 

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#93565

## Testing done

- Tested locally 

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Overview  |  Screenshot 2024-09-25 at 3 36 28 PM | Screenshot 2024-09-25 at 3 37 27 PM |
| Debt Summary | Screenshot 2024-09-25 at 3 36 47 PM | Screenshot 2024-09-25 at 3 38 03 PM |
| Debt Detail | Screenshot 2024-09-25 at 3 37 12 PM | Screenshot 2024-09-25 at 3 38 41 PM |

## What areas of the site does it impact?

Combined Debt Portal

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [X] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [X] Screenshot of the developed feature is added
- [X] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [X] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [X] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by Dr-Pongo — CHANGES_REQUESTED** [review]
Just the one missing space!

**Comment by Dr-Pongo** [comment]
Also just noticed the r[enderOtherVA section for the copays page](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/combined-debt-portal/medical-copays/containers/SummaryPage.jsx#L53-L72) can be updated with new heading size as well!

**Comment by josephrlee** [comment]
@Dr-Pongo, just made the two fixes!

**Review by Dr-Pongo — DISMISSED** [review]
Just wanted to note a slight difference in phrasing between copays and debts:
- "Our records show you have a VA health care copay bill."
- "Our records show you have VA benefit debt."

Not sure if that "a" makes the biggest difference, but otherwise

LGTM! 🚀

**Review by Dr-Pongo — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
