### PR TITLE
Swapped in proper 526 content

### PR DESCRIPTION
**Pull request by peggygannon**
updated this file:  vets-website/content/pages/disability-benefits/apply/form-526-disability-claim.md with proper 526 content

### CODE REVIEW

**Review by markgreenburg — APPROVED** [review]
LGTM 🚀
One other little thing that you could update if you really felt like it is the comment `<!-- Edu Benefits Application End -->` but that's not a blocker by any means.

**Review by cvalarida — APPROVED** [review]
:shipit: Ahh, that's much better. :relaxed:

**Comment by peggygannon** [comment]
@markgreenburg @cvalarida OK, great. I just made that content tweak--changing "EDU Benefits" to "Disability Benefits."

Since this is approved, are one of you able to merge this in to staging?

**Comment by cvalarida** [comment]
Can do. Once Jenkins is done with it, I'll hit the big green button. :smile:

**Pull request merged**
