### PR TITLE
Hca help content

### PR DESCRIPTION
**Pull request by cehsu**
Connects to department-of-veterans-affairs/vets.gov-team#3058

Verbiage
__________________________________________________________________________________________________________

screen shot 2017-06-08 at 6 11 18 pm

Phone Number
__________________________________________________________________________________________________________
screen shot 2017-06-08 at 6 11 28 pm

### CODE REVIEW

**Review by jbalboni — APPROVED** [review]
LGTM

**Comment by J-Quag** [comment]
I made a kerfloffle of this. The content should be Health Eligibility Center rather than Enrollment. I'm sorry about that.

**Comment by cehsu** [comment]
Thanks @J-Quag, I'll update this pronto.

**Comment by J-Quag** [comment]
Thanks @cehsu !

**Pull request merged**
