### PR TITLE
Welcome Kit page

### PR DESCRIPTION
**Pull request by kellyskennedy**
Creating new page to download welcome kit

### CODE REVIEW

**Comment by kellyskennedy** [comment]
Can you take a look, @DanielleSoCompany ?

**Comment by kellyskennedy** [comment]
@peggygannon can you review this? Thanks!

**Review by peggygannon — COMMENTED** [review]
@kellyskennedy I've made a some content edits to the intro, making it more active voice. I am not familiar with what will be in the welcome kit, so I kept to the benefits that you mention in your version.

**Comment by kellyskennedy** [comment]
Okay, @bethpotts Ready to take a look?

**Review by phiden — APPROVED** [review]

**Pull request merged**
