### PR TITLE
Updated logic to direct 1990E to new TOE app

### PR DESCRIPTION
**Pull request by FernandoBoza**
## Summary
Updates the Education Wizard to redirect users to the new TOE app for 1990E forms via /education/how-to-apply/

## Testing done
- [] Done

## Screenshots

image

## What areas of the site does it impact?
/education/how-to-apply/

### CODE REVIEW

**Comment by jsimonVA** [comment]
@FernandoBoza do you have a link to the original request for this? If not, can you tell me who requested this change.

**Comment by FernandoBoza** [comment]
@jsimonVA sure, I believe this [is it ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/edu-1990e-authenticated.md)

**Comment by jsimonVA** [comment]
Thank you @FernandoBoza. We will have to hold off on approving this PR until we can speak with Darla Nieukerk and Cinda Quattrini who are both OOO today and should return 12 Dec 2022. There is one major issue with this pull request which is the new URL points to a duplicated form 1990e that we were unaware of. We are also working on changes to this form and the current changes we have made will be lost. We are looking into this a little more to see what needs to be corrected before we move further with this. I apologies for any delay this may cause, should have a clearer direction early next week.

**Comment by jsimonVA** [comment]
@btruongafs, @FernandoBoza, apologies for the delayed response on this. I wanted to make sure I got clarification before I got back to you. Per Darla Nieukerk, we have been instructed not to approve this PR since this work falls under the contract for GovCIO. If there are any questions, please reach out to Darla.

**Review by markkvba — APPROVED** [review]
Post discussions with EDU/OIT, we are approving this PR.

**Pull request merged**
