### PR TITLE
4630 swap banners

### PR DESCRIPTION
**Pull request by phiden**

### CODE REVIEW

**Comment by phiden** [comment]
@bethpotts @robbiethegeek could you please review this one?

**Review by robbiethegeek-usds — APPROVED** [review]
Looks good @bethpotts please give 👍 if you approve.

**Comment by bethpotts** [comment]
@phiden Is this all the text I need to proof?: This is an official website of the United States government.

If so, looks great!

**Comment by phiden** [comment]
@bethpotts yeah, it's super simple! Thanks!

**Pull request merged**
