### PR TITLE
Skip flaky VAP SVC test

### PR DESCRIPTION
**Pull request by timwright12**
## Description
CI Failure: http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fvets-website/detail/master/11920/tests

### CODE REVIEW

**Review by k80bowman — APPROVED** [review]

**Comment by erikphansen** [comment]
What about this very simple unit test is flaky?

**Comment by k80bowman** [comment]
It [failed in `master`](http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fvets-website/detail/master/11920/tests) this morning with this error:
```
Error
document.getElementById is not a function
Stacktrace
TypeError: document.getElementById is not a function
    at Object.get (node_modules/react-scroll/modules/mixins/scroller.js:41:39)
    at Object.scrollTo (node_modules/react-scroll/modules/mixins/scroller.js:54:23)
    at Timeout.<anonymous> (src/platform/forms-system/src/js/review/ArrayField.jsx:101:16)
    at Timeout.sentryWrapped [as _onTimeout] (node_modules/@sentry/browser/src/helpers.ts:87:17)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by erikphansen** [comment]
Yes I saw that. But nothing in that unit test is triggering a call to `getElementById` or anything else in that stack trace.

**Comment by k80bowman** [comment]
It may have been a one-off weird thing, I looked through it and you're right, nothing in that test is calling that function. I ran the tests locally with the same CHOMA_SEED and they all passed. If you want to submit a PR to remove the `.skip` I'll approve it. I'd just ask we not merge it until after today's deploy just in case there is a problem I'm not seeing.

**Comment by erikphansen** [comment]
Yeah that's really maddening. I also ran the the tests locally with that CHOMA_SEED on commit hash `8b2eba39e739937476ccd574ab1282fa301ee6d5` and it passed :( Given that the error stemmed from a timer, my theory is that the entire test suite completes faster on our machines than it does on Jenkins, so the suite finishes before that offending timer fires.

**Comment by k80bowman** [comment]
Yes, the test suite does finish faster locally, generally, and so yes that is entirely possible. It's also going to make finding whatever is causing that error incredibly difficult to find. 😕

**Comment by erikphansen** [comment]
This PR includes instructions on how to replicate the unit test failure locally as well as fix (that feels very hacky, but seems to do the job) https://github.com/department-of-veterans-affairs/vets-website/pull/17993

**Pull request merged**
