### PR TITLE
Va gov/feature/13082: Careers: Create sidebar

### PR DESCRIPTION
**Pull request by accbjt**
## Description
Careers: Create left sidebar

## Testing done
Manual Testing

## Screenshots
screen shot 2018-09-20 at 5 27 34 pm
screen shot 2018-09-20 at 5 27 58 pm
screen shot 2018-09-20 at 5 28 13 pm
screen shot 2018-09-20 at 5 28 36 pm
screen shot 2018-09-20 at 5 28 47 pm

## Acceptance criteria
- [ ] Left Rail links should look like the left rail spreadsheet for Careers and Employment

https://docs.google.com/spreadsheets/d/1SsA5RVkERpMF8DE4Oal7fy4dK617JkdJgMQ2zrRdJXc/edit#gid=203626042

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by accbjt** [comment]
@mnorthuis In the spreadsheet `Reemployment` was labeled as `Remployment`. Can you verify which spelling is the correct one before I this gets approved.

**Comment by mnorthuis** [comment]
Correct spelling is "Reemployment". I corrected the error in the spreadsheet.  URL is correct, left nav label was incorrect.

**Review by RobAWilkinson — APPROVED** [review]
This looks killer Bill, everything looks in order to me and all good.

**Review by ncksllvn — APPROVED** [review]
Solid work Bill!!

**Pull request merged**
