### PR TITLE
Few more bug fixes

### PR DESCRIPTION
**Pull request by akainic**
Takes care of tickets:
- [x] #3357 (apply nested styling to school selection)
- [x] #3350 (add nested content style to relinquishment date)
- [ ] #3356 (blank records for employment and education should have placeholder text)
- [ ] #3355 (format ROTC scholarship cards to match service periods)
- [ ] #3361 (box gets bigger)
- [x] #3367 (convert "branch of service" input from dropdown to text field)
- [x] #3363 (educational goals should be text field, not area)

### CODE REVIEW

**Comment by akainic** [comment]
@alexose do you mind reviewing in the morning so we can merge before the testing session at 1 tomorrow?

**Comment by goldenmeanie** [comment]
Re: #3356 should empty cards render in the preview?

**Comment by goldenmeanie** [comment]
#3355 card should show both year and amount

**Comment by goldenmeanie** [comment]
#3361 looks like the field is now full width. An earlier tweak was to size inputs to their data. Is there a compromise that would accommodate the widest characters with dashes but be 1/2 width or less? Maybe large-5 in foundation parlance?

**Comment by goldenmeanie** [comment]
The other four issues (checked in OP) LGTM!

**Comment by cweber** [comment]
Re: #3356 should empty cards render in the preview? ()

I'm getting lost in terms here, but I think I agree? (Is preview review, or is preview the cards on that page? Is 'empty' completely empty or does empty also include a selected radio button, but no free-form data?)

I also saw a comment from @akainic over the weekend about state changes, but can't remember what/where it was.

**Comment by akainic** [comment]
@goldenmeanie @cweber Just added the additional fixes you mentioned. Can't change preventing empty cards from being added for the reason listed here: https://github.com/department-of-veterans-affairs/vets-website/issues/3356. If we could merge this without that fix and get to that one later that would be great.

**Comment by akainic** [comment]
To be reviewed later by @alexose, but need to merge this for demo.

**Pull request merged**
