### PR TITLE
85907 Add a feature toggle for the Medication Review Appointment Instructions

### PR DESCRIPTION
**Pull request by vbahinwillit**
## Summary
This PR add feature toggle 'va_online_scheduling_med_review_instructions' to update the Medication Review instructions on the Appointment Details page.

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#85907

## Testing done
N/A

## Screenshots
N/A

## What areas of the site does it impact?
VAOS

## Acceptance criteria
- [x] The toggle is created for VAOS

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by JunTaoLuo — COMMENTED** [review]
Need updates for `src/platform/utilities/feature-toggles/featureFlagNames.json` as well.

**Review by jenniemc — COMMENTED** [review]
Looks good so far. Just need to add the feature toggle name to one more file `src/platform/utilities/feature-toggles/featureFlagNames.json` according to [VA Platform document](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-5.Addthefeaturetogglenametovets-websitebyupdatingfeatureFlagNames.json)

**Comment by vbahinwillit** [comment]
Thanks for the review. I thought I was missing a file!

**Review by JunTaoLuo — APPROVED** [review]

**Review by jenniemc — APPROVED** [review]
LGTM!

**Review by IGallupSoCo — APPROVED** [review]
LGTM

**Pull request merged**
