### PR TITLE
[eFSR] Other asset user flow update

### PR DESCRIPTION
**Pull request by Dr-Pongo**
## Summary
Updating flow for Other Asset pages, so summary is skipped if nothing is checked and list is empty. `OtherAssetsSummary` was changed to a `CustomPage` to help with navigating away if all of the items in the list were deleted on the summary page. 
This lead to some tweaks for the custom pages data setting methods in `AddAsset` and `OtherAssetsSummary` and adding in a view only list on the review page for some kind of feedback. 

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#55202

## Testing done
Cypress and unit tests ran locally along with manual testing navigation back and forth with different conditions

## Screenshots

| No checks | (skips summary page) |
| --- | --- |
| image | image |

#### Summary page table
image 

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [x]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [x]  I added a screenshot of the developed feature
- [ ]  [Accessibility foundational testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### CODE REVIEW

**Review by OptionSelect — APPROVED** [review]
LGTM! 🚀

**Review by OptionSelect — APPROVED** [review]
LGTM 🚀

**Review by amponce — APPROVED** [review]
Solid! Love seeing the new alternative to dispatch

**Review by kelsonic — APPROVED** [review]
LGTM 🎉 Nice work!

**Pull request merged**
