### PR TITLE
Disability wizard content fix

### PR DESCRIPTION
**Pull request by cehsu**
These changes update the content for the disability wizard when the user has a new condition and a condition that has increased.

image

### CODE REVIEW

**Review by cvalarida — APPROVED** [review]
Looks good! I'm not super familiar with the wizard; are these the only instances of this (and similar) text?

**Review by markgreenburg — APPROVED** [review]
LGTM

**Comment by cehsu** [comment]
Thanks @cvalarida, that's probably a question for @peggygannon, but AFAIK this is the only instance of this kind of messaging.

**Review by peggygannon — APPROVED** [review]
@cehsu Looks good. thank you for making the update!

**Pull request merged**
