### PR TITLE
Sets up yarn workspaces in platform/user

### PR DESCRIPTION
**Pull request by rmessina1010**
## Description
This PR sets up a yarn workspace  in platform/user

## Original issue(s)
department-of-veterans-affairs/va.gov-team#39205

## Testing done
local testing passed. project built successfully; browser testing in local, dev, staging, prod , RI environments.

## Acceptance criteria
- [ ] does not change vets-website behavior

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by tmitchellgcio — APPROVED** [review]

**Comment by tmitchellgcio** [comment]
LGTM

**Review by alexandec — APPROVED** [review]

**Review by adamwhitlock1 — APPROVED** [review]
LGTM. A couple minor questions:

So if we create any new exports in the user platform folder, then we should be adding them to the `exportsFile.js`? 

Is there documentation that I can read through to make sure I understand this fully?

**Comment by AGarcia-Clarity** [comment]
Looks fine to me.  Expanding on @adamwhitlock1 question, how will `CODEOWNERS` work in workspaces.  Will I have to wait for a review from one of the teams listed if a new PR doesn't impact them?

**Review by asg5704 — APPROVED** [review]

**Review by joeniquette — APPROVED** [review]

**Comment by rmessina1010** [comment]
@adamwhitlock1 
As codeowners your team's role will be a `worktree maintainer` for this directory. I highly recommend keeping the  `exportsFile.js` up to date.   It serves as a convention, allowing  you more granular control of the exports,  as well as serving as a convenient hub  and giving engineers in other team the ability to see what can be imported from the package. 

DOCS: https://depo-platform-documentation.scrollhelp.site/developer-docs/yarn-workspaces

**Pull request merged**
