### PR TITLE
Add analytics for the va-notification web component

### PR DESCRIPTION
**Pull request by jamigibbs**
## Summary

The design system has a new component [va-notification](https://design.va.gov/storybook/?path=/docs/components-va-notification--default) and this PR will add analytics to vets-website (GA and GA4) to update the datalayer during interactions.

## Related issue(s)

Related issue: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1803
Related PR: https://github.com/department-of-veterans-affairs/component-library/pull/738

## Testing done
locally with vets-website

## Screenshots

**Close - GA**
Screenshot 2023-07-06 at 3 07 43 PM

```
{
  event: "int-notification-close",
  event-source: "component-library",
  component_version: undefined,
  notification-type: "action-required",
}
```

**Close - GA4**

Screenshot 2023-07-06 at 3 26 03 PM

```
{
  event: "interaction",
  component_version: undefined,
  component_name: "va-notification",
  custom_string_1: "component-library",
  action: "int-notification-close",
  heading_1: "Notification heading",
  type: "action-required"
}
```

**Link Click - GA**

Screenshot 2023-07-06 at 3 21 02 PM

```
{
  event: "nav-notification-link-click",
  event-source: "component-library",
  component_version: undefined,
  notification-clickLabel: "Manage your notifications",
  notification-type: "action-required",
  notification-headline: "Notification heading"
}
```

**Link Click - GA4**

Screenshot 2023-07-06 at 3 27 17 PM

```
{
  event: "interaction",
  component_version: undefined,
  component_name: "va-notification",
  custom_string_1: "component-library",
  action: "nav-notification-link-click",
  custom_string_2: "Manage your notifications",
  heading_1: "Notification heading",
  type: "action-required"
}
```

## What areas of the site does it impact?
None. It only sets up the analytics mapping for the web component.

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by randimays — APPROVED** [review]

**Comment by ajakabcin** [comment]
hey @jamigibbs can you keep myself and @allisonlu in the loop on this? this is the last piece of the puzzle for us to be able to release the component on My VA :)

**Comment by ajakabcin** [comment]
hey @jamigibbs! Checking in to see if there was any further work needed on on the analytics here - thanks!

**Comment by jamigibbs** [comment]
@ajakabcin I'm meeting with Michelle tomorrow (19th) and we'll let her know this component has had analytics wired up as part of [this manifest](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1892). She'll need to let us know if there's anything further we need to do on our end.

But we are still scheduled to create a component library release tomorrow with the current analytics setup so it should be in vets-website either way then.

**Comment by jamigibbs** [comment]
@ajakabcin We have a PR here for getting the latest component library version in vets-website: https://github.com/department-of-veterans-affairs/vets-website/pull/24924

**Pull request merged**
