### PR TITLE
WIP/Content disability claims hardening

### PR DESCRIPTION
**Pull request by peggygannon**
This PR includes two Disability claims page updates that we want to launch ahead of 526 MVP release:

- [ ] Adding the new Supplemental Forms page
- [ ] Adding Increase Claim accordion to Claims Type page
- [ ] Added crosslink for Supplemental forms page to /disability-apply/

### CODE REVIEW

**Comment by peggygannon** [comment]
@bethpotts This PR is ready for your review. It includes the two Disability updates we wanted to do ahead of 526 MVP launch. 
--Adding in the Supplemental Form page
--Adding an accordion for Increased Claims to the Claims Type page

**Comment by peggygannon** [comment]
@bethpotts 
The crosslink to the Supplemental page (on disability/apply) has been added to this PR. Ready for your review.

**Review by bethpotts — APPROVED** [review]
Looks good, and thanks for flagging the left nav issue so we don't link to the 526 claims increase form.

**Review by 1Copenut — APPROVED** [review]
👍 LGTM. I reviewed with @peggygannon and @markgreenburg and @cvalarida for content accuracy. 

I also merged the `master` branch in and tested locally for link accuracy.

**Pull request merged**
