### PR TITLE
Change FAA certificates field to a textarea

### PR DESCRIPTION
**Pull request by jbalboni**
The wireframes changed the FAA certificates field from a growable table to a single textarea.

PLEASE DO NOT MERGE until I comment that it's ok. It's relying on a branch in the schema repo that I need to change to master once the schema PR is merged.

### CODE REVIEW

**Comment by jbalboni** [comment]
screen shot 2016-09-23 at 11 05 25 am

**Comment by jbalboni** [comment]
@alexose Can you take a look?

**Review by alexose — APPROVED** [review]
Looks good!

**Comment by jbalboni** [comment]
Schema update made, I'll merge this when CI is done.

**Pull request merged**
