### PR TITLE
Organic adoption modal take 2

### PR DESCRIPTION
**Pull request by kscoulter**
## Summary
Creates a modal that displays when a user is 1) logged in with DS Logon, 2) does not have alternative Idme or login gov credentials linked to the account, 3) is part of the experiment as determined by a feature flag.

The modal uses a prop derived from a backend endpoint that checks for all items listed above.

Each button/action fires off a Google Analytics event when pressed.

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/54478
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/53788

## Testing done

- Previously no modal appeared after login
- Turn on the feature flag for organic experiment for just yourself, log in with a DS logon credential, observe the modal. The modal closes on click outside or close button.

## Screenshots
Screen Shot 2023-03-22 at 1 17 53 PM

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [x]  I added a screenshot of the developed feature
- [ ]  [Accessibility foundational testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by alex-morgun-1 — APPROVED** [review]

**Review by harshilmoradia — APPROVED** [review]

**Review by joeniquette — CHANGES_REQUESTED** [review]
@kscoulter Can you please test with the [instructions](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/proxy-rewrite/README.md) provided by Jill for the injected header and post a screen capture of it working inside your PR.

**Review by jtmst — APPROVED** [review]
verified that injected header sites were not affected locally 
image

**Comment by kscoulter** [comment]
Screen Shot 2023-04-11 at 1 42 28 PM

**Comment by kscoulter** [comment]
@joeniquette please re-review

**Review by joeniquette — APPROVED** [review]
From a visual standpoint, this looks good and meets the requirements.

**Review by ryanshaw — APPROVED** [review]
The VAOS test changes look good to me

**Pull request merged**
