### PR TITLE
Added examples

### PR DESCRIPTION
**Pull request by cvalarida**
References department-of-veterans-affairs/vets.gov-team#1165

Possibilities given by @leannammiller:

- Graduated
- Completed course
- Moved
- Changed my mind
- Did not like the school

---

image

### CODE REVIEW

**Comment by mollyblake** [comment]
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1173

**Comment by mollyblake** [comment]
This content is referenced in this issue. Thanks https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1173  


Should read: 

 Why did you stop taking classes or participating in the training program? (for example, “I moved” or “The program wasn't right for me” or “I graduated.”)

**Comment by cvalarida** [comment]
@mollyblake Perfect, thanks! Didn't see that one before.

Updated:

---
image

**Comment by goldenmeanie** [comment]
I reordered the examples. LGTM

**Pull request merged**
