### PR TITLE
Fix for search pagination state not updating

### LINKED ISSUE #11282: Implement fix for FE: Search pagination: shows results for previous search
## Description
Follow up to Spike2: shows results for previous search #10819
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10819

As a Veteran, I want to be able to use the pagination arrows to see more pages of my current search, not my previous search.

Defective behavior: in front-end, search pagination UI will pull up results for previous search.

Observations from research spike:
- Currently the prod SearchDropdownComponent isn’t properly updating the userInput state on change correctly
- It works locally because of the searchDropdownComponentEnabled prop / feature flag is set to true on prod, but defaults to false on local
- Check out state for the search app props in react dev tools to see that userInput isnt being updated on change

### To Reproduce as a user
1. Go to VA.gov and enter any keyword/s (e.g. **message doctor**) in Search drop-down in the header. Note you will arrive at the Search Results page with no issues.
3. Enter a different keyword in the search field on the current Search Results page (e.g. **refill prescription**). Note you will arrive at page 1 with no issues. 
4. Scroll down and click on any page after 1. 
5. Note that you will be redirected to page 1 of the previous search (i.e. **message doctor**)

### To repro locally:
    1. On your local vets-website repo, go to the following file: src/platform/utilities/api/index.js
    2. Change line 57 from: const baseUrl = `${environment.API_URL}/${apiVersion}`; to const baseUrl = `https://api.va.gov/${apiVersion}`;
    3. Comment out the conditional rendering on lines 342-359 in /vets-website/src/applications/search/containers/SearchApp.jsx
    4. Switch the condition on 360 to !this.props.searchDropdownComponent

## Acceptance Criteria
- [ ] Update SearchDropdownComponent to change userInput state changes
- [ ] Verify that the pagination bug no longer occurs
- [ ] Remove old fallback code if it is no longer required

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by jtmst**
## Description
This fixes a bug where state was not updating on the search app from the new searchDropdown component.  It also removes all fallback code that was in place from when this 

## Original issue(s)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11282

## Testing done
Tested on Local,  steps to QA:
1. On your local vets-website repo, go to the following file: src/platform/utilities/api/index.js
2. Change line 57 from: const baseUrl = `${environment.API_URL}/${apiVersion}`; to const baseUrl = `https://api.va.gov/${apiVersion}`;
3. Search for something on VA.gov
4. Search for something different, using the search input on the results page
5. Observe that results render as expected

## Screenshots
Screen Shot 2022-10-25 at 9 26 24 AM
Screen Shot 2022-10-25 at 9 26 39 AM
Screen Shot 2022-10-25 at 9 26 48 AM

## Acceptance criteria
- [ ] Update SearchDropdownComponent to change userInput state changes
- [ ] Verify that the pagination bug no longer occurs
- [ ] Remove old fallback code if it is no longer required

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by lzapson — APPROVED** [review]

**Comment by jilladams** [comment]
@jtmst does search not work on review instances?  If I try from the linked env, the header search form won't take input, and results pages like http://b057f336e576d4a7cb80d52b50700d60.review.vetsgov-internal/?query=benefit&t=false redirect to the homepage. Is that expected? (Genuinely don't know.)

**Comment by jtmst** [comment]
> @jtmst does search not work on review instances? If I try from the linked env, the header search form won't take input, and results pages like http://b057f336e576d4a7cb80d52b50700d60.review.vetsgov-internal/?query=benefit redirect to the homepage. Is that expected? (Genuinely don't know.)

Seems to be not working on this review instance where it does on others.  Works completely fine on my local. Will have to investigate

**Comment by jilladams** [comment]
May be worth just rebuilding and see if a new one works, since RIs have been weird in the last week or two. 🤷‍♀️

**Review by maxx1128 — APPROVED** [review]

**Comment by maxx1128** [comment]
Leaving this as approved by me after the commit removing the fallback code.

**Review by it-harrison — APPROVED** [review]

**Review by ryguyk — COMMENTED** [review]
This looks very good, including the steps to remove the old fallback input. However, there are other places in code that reference the same Flipper, and I'm wondering if removing all of these together might best be handled in a separate ticket.

**Comment by ryguyk** [comment]
> This looks very good, including the steps to remove the old fallback input. However, there are other places in code that reference the same Flipper, and I'm wondering if removing all of these together might best be handled in a separate ticket.

I think I'm falling on the side of changing all of this here or none of this here (and then fixing all in a separate ticket/PR).

After a deeper look, I discovered this:
- There are THREE places that utilize `SearchDropdownComponent`.
  1. The search page; component is `SearchApp`.
  2. Mobile search in the main navbar/header
  3. Desktop search in the main navbar/header
  
Currently, this PR removes the old plain `<input>` search in TWO of those places (search page and mobile search). It's odd to me to have it this way. I think we should fix this all here or all in a separate ticket.

**Review by jilladams — APPROVED** [review]
Took a quick QA pass -- 
* Autocomplete working in search review instance
* Search results load as expected
* Pagination takes me to next page of results with
  * Current page number highlighted in pagination
  * Showing X of XX results  for "term" updates correctly
* Search new term on page - 1st and 2nd page of results use new search results, pagination works
* Search new term from header - same

Approving, but I'm not a merge-unblocking reviewer.

**Review by ryguyk — APPROVED** [review]
This looks like it does the trick. Paging is working as expected. Nice clean code.

**Pull request merged**
