### PR TITLE
WIP/Update static content for allowances form

### PR DESCRIPTION
**Pull request by peggygannon**

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by peggygannon** [comment]
@phiden Hi, Sophia, here is the updated Burial Allowances page for your review. This page will launch tomorrow when the Burial Allowances form launches. If all looks good, can you merged this branch into the master for tomorrow's build?

**Review by phiden — APPROVED** [review]

**Comment by phiden** [comment]
@peggygannon merged. I'm relatively new to this  -- what time does this usually deploy to production? I'd like to take another look at it then!

**Comment by ayaleloehr** [comment]
@phiden I can answer that one. It deploys to staging right away (or more realistically 30ish minutes after merging) and then to production around 4PM Eastern each day.

**Comment by phiden** [comment]
Thanks @ayaleloehr -- I'll double-check it in staging in half an hour, then!

**Comment by peggygannon** [comment]
@phiden @ayaleloehr Thank you both!

**Pull request merged**
