### PR TITLE
Update support-veteran-employees.md

### PR DESCRIPTION
**Pull request by rcarthur**
@mariana-almeida 
- VR&E SMEs asked us to unlink the "SEI Program" because the previously linked PDF was out of date. 
- VR&E SMEs requests we add the word "Employment" in the phrase "VR&E Employment Coordinators" 
- VR&E SMEs requested that we add reference to the NPWE program
- I noticed that the tax credit DOL link was not linked to the optimum page - so I adjusted this.
- Note - normally, I would assign this to @bethpotts for merge so that she can put a copy editor eye on the words. Because she's gone, can you please just double-check my the changed language?

### CODE REVIEW

**Comment by rcarthur** [comment]
@mollyblake  - pls check also.

**Comment by mollyblake** [comment]
@rcarthur I don't have access to the patch, but the excel spreadsheet that lists the VR&E Employment Coordinators needs to be unlinked as it is outdated, per SME.

**Comment by mariana-almeida** [comment]
@rcarthur Can you make a note to re-check va.gov for a newer version of the excel later? Maybe when we finally put up the VR&E content would be a good time.

http://www.benefits.va.gov/vocrehab/index.asp <-- I think this page would have the updated Excel, if anywhere. Theoretically, they would keep the same file name, but who knows.

**Comment by rcarthur** [comment]
I've added it as a task inside of this pivotal story.  In addition it is on
the SME response document - that should function both as a reminder to SMEs
that they need to send us the document....and a checklist for us as we go
through the next revision.

 BTW, this seems to highlight something that would be a good spec for CMS -
basically, it would be nice to have a comment section that only we could
see for every live page where we could keep track of stuff like this excel
spreadsheet AND even send us periodic reminders.

**Pull request merged**
