### PR TITLE
Absolutely position calendar options row

### PR DESCRIPTION
**Pull request by jbalboni**
## Description
In order to keep the correct tab order and not disturb the table structure of the calendar, we need to keep the expandable options inside the cell for a particular day. This means we need to absolutely position them so they can be wider than their container, and push down next week on the calendar.

## Testing done
Local testing

## Screenshots
Screen Shot 2020-01-08 at 1 38 45 PM

## Acceptance criteria
- [ ] Options displayed in correct tab order

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by narin — APPROVED** [review]
LGTM.  Still getting used to following react hooks and this definitely helped.

**Review by 1Copenut — APPROVED** [review]
@jbalboni This looks good to me. I'm not able to see the radio button direct selects on this branch locally, and the AM/PM checkbox groups aren't showing up inside the table cell, so I'm winging just a bit. I like how you approached the change and think this should get us down to polish items.

**Comment by 1Copenut** [comment]
@jbalboni I retested this morning on `localhost` with Safari. We're getting closer to the correct solution.

Is there a way we can render `<CalendarOptions />` on every cell, every time, but add a `hidden` attribute until `isCurrentlySelected` === true ? VoiceOver is skipping over the div being added to the DOM and moving on to the next day's cell when we repaint the DOM with the div included. My hunch is the accessibility object model takes note of things that are hidden or display: none and handles them differently than things being added after the fact, and that's why VO is skipping over the div and form fields.

**Comment by jbalboni** [comment]
@1Copenut Probably, let me try that.

**Review by rianfowler — APPROVED** [review]

**Comment by 1Copenut** [comment]
@jbalboni Good news! This latest revision worked perfectly in Safari. I was able to expand the form, and move directly into it using the VoiceOver virtual cursor. I have high confidence this will fix the issue for NVDA and JAWS as well.

LMK when this is in Staging and I'll test with those screen readers.

We may need to make some adjustments to the labeling, but that'll be a separate ticket. Thank you for keeping after this item.

**Pull request merged**
