### PR TITLE
Bah 19016 Update Auto-complete on CT to delay queries between keystrokes

### PR DESCRIPTION
**Pull request by hughes-dustin**
## Description
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19016

## Testing done
Dev tested

## Acceptance criteria
- [ ] On the landing page, when a user types in the school text box, there will be a [configurable amount] second delay between the end of the keystroke and the call to the server.
     - If another keystroke happens within [configurable amount] of a second, the timer will reset.
     - If no keystroke happens within [configurable amount] of a second, the data request will occur to prepopulate the autocomplete options.
- [ ] On the search results page, when a user types in the school text box, there will be a [configurable amount] second delay between the end of the keystroke and the call to the server.
     - If another keystroke happens within [configurable amount] of a second, the timer will reset.
     - If no keystroke happens within [configurable amount] of a second, the data request will occur to prepopulate the autocomplete options.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — CHANGES_REQUESTED** [review]
Please add a comment to WAIT_INTERVAL informing the reader the wait is in milliseconds.

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by sonntag-adam — APPROVED** [review]

**Comment by hughes-dustin** [comment]
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!

**Review by accbjt — APPROVED** [review]
LGTM

**Pull request merged**
