### PR TITLE
[Keyboard] VA.gov Search manage focus on results 

### PR DESCRIPTION
**Pull request by aubreyarcangel**
## Description
This PR does the follow:
1. On first search, focus is set to the `breadcrumb`.
2. If a user searches more than once, the focus is shifted to a `<div>` wrapped around the search results.

This was achieved by creating a `firstSearch` boolean propType and checking if it's `true`[ in `renderResultsList`](https://github.com/department-of-veterans-affairs/vets-website/pull/9743/files#diff-6811be1fe498feb3887a75c8f296f1acR227)  
Then switching it to `false` so the focus is shifted to `allResults` <div> for all following search attempts.

## Testing done
Tested on local build with:
1. ChromeVox extension for Chrome.
2. Safari
3. Firefox

## Screenshots
searchfocus

## Acceptance criteria
- [x] On first search, focus is set to `breadcrumb`
- [x] On all searches following the first search, focus is set to `<div> surrounding results 

## Definition of done
- [X] Events are logged appropriately
- [X] Documentation has been updated, if applicable
- [X] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by 1Copenut — CHANGES_REQUESTED** [review]
I did a quick walk through and noticed the focus is being returned to the `<h4>` after one or two key presses if I run a second search. I captured it as an animated GIF that I'll post in an issue comment.

I'd also like to ask if we can focus the breadcrumb on first page load, then the H4 after users have searched a second time on the page. That's on me for not making that clear in the ticket and consult.

Please holler at me tomorrow if you'd like to discuss further!

**Comment by 1Copenut** [comment]
@aubreyarcangel Here's the animated GIF showing what I was observing about focus being set after I started a follow up search, and a static image illustrating different focus points for different user flows.

In this animated GIF, I'm refocusing the search field, and only type out the `g` before focus is reset to the `<h4>`. This was Chrome latest on MacOS.

focus-manager-search

---
Screen Shot 2019-03-26 at 5 05 06 PM

**Comment by ncksllvn** [comment]
Hey @aubreyarcangel, looks like you're on the right track. 

- I'm not sure if you need a flag in state for detecting first load. You may be able to get away with applying focus in `componentDidMount` instead.
- I see the `setTimeout` you have there, with the `4000` as the duration so that you can assume the search is done loading. Have you tried handling this in `componentDidUpdate` instead? I see a prop called `loading` that you can like use to check for when new search results are rendered. If `loading` was true, and now it's false, then than seems likely an indicator that the results just finished loading. 
- We have a platform utility for applying focus at `platform/utilities/ui`.

So, altogether, I think something like this would work -

```jsx
componentDidMount() {
    // If there's data in userInput, it must have come from the address bar, so we immediately hit the API.
    const { userInput, page } = this.state;
    if (userInput) {
      this.props.fetchSearchResults(userInput, page);
      this.writeBreadcrumb();
      focusElement(breadcrumbId);
    }
  }

componentDidUpdate(prevProps) {
    if (this.props.search.query !== prevProps.search.query) {
      this.writeBreadcrumb();
    }

    const hasFreshResults = !this.props.loading && prevProps.loading;
    if (hasFreshResults) {
      focusElement(headingId);
    }
  }
```

**Review by ncksllvn — COMMENTED** [review]
A few comments but looking good. I'm going to load the search app locally and take a stab at this.

**Comment by ncksllvn** [comment]
I tried this locally and I see why this is more complicated than it appears. I think there is some refactoring required here for this flow to feel more natural.

Currently, the breadcrumbs-update is handled by `getElementById`. This seems like something that was done in a rush, because querying the DOM breaks the encapsulation of a React component. I think we should remove the breadcrumbs from the content file, and start handling the breadcrumbs-update in React using the [design system component](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/breadcrumbs/). 

I started a WIP pull request for this here - https://github.com/department-of-veterans-affairs/vets-website/pull/10003. We just need to apply browser focus when new results are loaded. @aubreyarcangel, can you look into how to add that code into 10003?

**Comment by ncksllvn** [comment]
@aubreyarcangel @1Copenut  I went ahead and implemented the rest of the browser focus criteria and assigned you all for review, https://github.com/department-of-veterans-affairs/vets-website/pull/10003.

**Comment by 1Copenut** [comment]
@aubreyarcangel @ncksllvn Should I look at this PR or https://github.com/department-of-veterans-affairs/vets-website/pull/10003 or both for focus management on the search page? I'm looking at code for both, and not quite certain if one supersedes the other, or they're working together to solve different pieces of the ask.

**Comment by ncksllvn** [comment]
@1Copenut https://github.com/department-of-veterans-affairs/vets-website/pull/10003, I think, because I don't think we'll be able to write the perfect solution for this without moving the breadcrumbs into React.

**Comment by ncksllvn** [comment]
Closing, because the work here was carried over into https://github.com/department-of-veterans-affairs/vets-website/pull/10003. Thanks again @aubreyarcangel!

**Pull request closed without merging**
