### PR TITLE
Spacing tweaks in new content templates

### PR DESCRIPTION
**Pull request by melwoodard**
Modified spacing in major/related links lists to decrease overall vertical space and improve clustering of link groups.

pasted_image_5_22_17__11_18_am

### CODE REVIEW

**Comment by rroueche** [comment]
@melwoodard do you need anyone to review this, and once reviewed, could we assign to Leanna and Ian to determine if there are any front-end engineers with bandwidth to tackle?

**Comment by melwoodard** [comment]
@rroueche I already made the code changes, the screenshot above is a preview of what it looks like. I assigned @U-DON for a review and just need a thumbs up to merge this in.

**Review by U-DON — APPROVED** [review]
LGTM.

**Comment by rroueche** [comment]
YAY!!!

**Pull request merged**
