### PR TITLE
CT Redesign: Create copy of profile pages for use in sandbox #23581

### PR DESCRIPTION
**Pull request by zurbergram**
## Description
https://github.com/department-of-veterans-affairs/va.gov-team/issues/23581

## Testing done
http://localhost:3001/gi-bill-comparison-tool-sandbox/profile/2V000343/CYBERSECURITY%20PROFESSIONAL%20PENETRATION
http://localhost:3001/gi-bill-comparison-tool-sandbox/profile/11929140
## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Comment by k80bowman** [comment]
I see several a11y eslint rules being disabled. Is this going to create accessibility problems?

**Comment by zurbergram** [comment]
> I see several a11y eslint rules being disabled. Is this going to create accessibility problems?

@k80bowman No, this application is a sandbox for testing the redesign of the Comparison Tool in `src/applications/gi`, this PR is primarily copying over a portion of the current CT app to use in the sandbox

**Review by k80bowman — APPROVED** [review]

**Review by delli-gatti-michael — APPROVED** [review]
👍

**Pull request merged**
