### PR TITLE
Codeowners: Sitewide team name changes

### PR DESCRIPTION
**Pull request by jilladams**
## Summary

Platform support request Slack: https://dsva.slack.com/archives/CBU0KDSB1/p1698336681097449

 I have 2 teams, Sitewide Public Websites & Facilities. We have a variety of Github teams and I'd like help understanding how they are managed / if we can make some changes.
* https://github.com/orgs/department-of-veterans-affairs/teams/vfs-facilities/members - what is this team used for? (Lindsey Hattamer is maintainer.)  I see this Team listed as codeowners in vets-api, and it includes researchers.
* https://github.com/orgs/department-of-veterans-affairs/teams/vsa-facilities-frontend/members -- this is the correct group of people for vets-api / vets-website / content build code reviewers. Is it possible to EOL the @vfs-facilities team and rename this team to be @vfs-facilities?
* https://github.com/orgs/department-of-veterans-affairs/teams/vsa-public-websites-frontend -- this team should really be named @vfs-public-websites-frontend, but we don't have the power to change it. Could someone do that? We need to add this team as codeowners to a few things in vets-api but would like to rename it before we do that.\

We'll need to make codeowners changes at the same time.
- vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/26402
- content-build PR: https://github.com/department-of-veterans-affairs/content-build/pull/1764

### CODE REVIEW

**Review by eselkin — APPROVED** [review]
These changes are appropriate and inline with the content-build desired changes.

**Review by ataker — APPROVED** [review]

**Review by chriskim2311 — APPROVED** [review]
Approved!

**Comment by jilladams** [comment]
Updating branch, running again to see if I get lucky.

**Comment by jilladams** [comment]
The test fail re: prod push has nothing to do with these code changes, so if that keeps failing, gonna need Plat assistance.

**Comment by jilladams** [comment]
Another timeout. Test run #4 kicked off for failed jobs.

**Pull request merged**
