### PR TITLE
[61817] Set up NOD RUM dashboard

### PR DESCRIPTION
**Pull request by data-doge**
## Summary

We are setting up an RUM dashboard in DataDog for the NOD form, as part of a limited pilot of the RUM feature. @va-albers has already set up the dashboard in DataDog for us. This PR is the code component of that dashboard. We plan on using this RUM to 1) help us debug front end errors, and 2) help with design and research. This code is largely modeled after similar implementations for the HCA and check-in products (see other `useBrowserMonitoring.jsx` files).

Although we have a 'mask-user-input' flag on the RUM configuration, we still need to verify that no PII/PHI is exposed to the RUM. For that reason, we've hidden this work behind a feature toggle (created in https://github.com/department-of-veterans-affairs/vets-api/pull/13312). 

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#61817

## Testing done

Once we've verified that this all works in staging, and that no PII/PHI is exposed to the RUM, then we will flip the feature toggle in prod. Afterwards, we will 1) develop a plan to ensure that _future_ changes won't expose PII/PHI to the RUM either, and 2) we will draft a PR to tear down the feature toggle previously mentioned.

## Screenshots

N/A

## What areas of the site does it impact?

The NOD form

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by data-doge** [comment]
@va-albers We'll leave this PR in draft state until you feel comfortable with us moving forward at a 100% `sessionReplaySampleRate`. For the record, based on the typical volume of user sessions we get on NOD, we expect the cost of this dashboard to be ~$25/month.

**Review by Mottie — APPROVED** [review]
LGTM

**Review by holdenhinkle — CHANGES_REQUESTED** [review]
Do you need to add any tests?

**Comment by Mottie** [comment]
We didn't plan on adding any tests. The other RUM implementations that was looked at didn't have any tests either.

**Review by holdenhinkle — APPROVED** [review]
LGTM

**Review by CBonade — APPROVED** [review]

**Pull request merged**
