### PR TITLE
Fix className

### PR DESCRIPTION
**Pull request by radavis**
Fixes typo

## Screenshots

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |      Screenshot 2024-04-23 at 16-05-32 My HealtheVet Veterans Affairs  |  Screenshot 2024-04-23 at 16-04-56 My HealtheVet Veterans Affairs     |

### CODE REVIEW

**Review by asg5704 — APPROVED** [review]

**Comment by asg5704** [comment]
@radavis Ready for merge. Thank you for this 🚀

**Comment by radavis** [comment]
@asg5704 Updated the PR w/ screenshots. If there's a difference in UI, I don't see it! :shrug:

**Comment by asg5704** [comment]
> @asg5704 Updated the PR w/ screenshots. If there's a difference in UI, I don't see it! 🤷

Is the `showVerifyIdenityHelpInfo` set to `true`?

**Comment by radavis** [comment]
@asg5704, Yes, here's our code where we call the component: https://github.com/department-of-veterans-affairs/vets-website/blob/IdentityNotVerifiedComponent-classNameTypoFix/src/applications/mhv-landing-page/components/LandingPage.jsx#L34:L34

**Pull request merged**
