### PR TITLE
GIBS Update link

### PR DESCRIPTION
**Pull request by annekainicUSDS**
Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3952

### CODE REVIEW

**Comment by rroueche** [comment]
@annekainicUSDS is there a reason for using the absolute URL instead of relative?

**Comment by annekainicUSDS** [comment]
@rroueche I've heard pros and cons for both, apparently absolute URLs are better for SEO. But seems like a relative url is mostly used from within the same domain, so I'll switch to that.

**Comment by rroueche** [comment]
@annekainicUSDS i might be misunderstanding, but wouldn't the relative URL be `/gi-bill-comparison-tool` instead of `/vets.gov/gi-bill-comparison-tool` ?

**Review by rroueche — APPROVED** [review]
LGTM

**Pull request merged**
