### PR TITLE
WIP/content/pension/FDC 

### PR DESCRIPTION
**Pull request by peggygannon**
Removed "Optional Faster Process"

### CODE REVIEW

**Comment by peggygannon** [comment]
@bethpotts Here is the updated pension FDC page, with the parenthetical references to (Optional Faster Process) taken out.

also, the path to this page is pension/apply/pension-fully-developed-claim. Is this the correct naming convention? with "pension" repeated?

**Review by bethpotts — APPROVED** [review]
@peggygannon I agree with Rachael's comment that we don't need to repeat "pension." We don't have path conventions written down anywhere though, as far as I know. The content here looks great! Approved.

**Comment by peggygannon** [comment]
@bethpotts OK, thank you for your review. 

regarding the path name, should I rename the github file to: pension/apply/fully-developed-claim?

**Comment by bethpotts** [comment]
@peggygannon As we just discussed, you'll verify with Sophia that it's ok to just go ahead and rename in github in the folders. Thanks!

**Comment by goldenmeanie** [comment]
Looks like this branch started two days ago. I'll rebase and see if that picks them up.

**Comment by peggygannon** [comment]
@bethpotts Hi, Beth, this PR needs your review again, as I had to redo content edits for the FDC page. 

 I'm also troubleshooting why 1 check has not passed yet. The form URL look correct to me...

**Review by bethpotts — APPROVED** [review]
Latest round of changes are approved!

**Comment by peggygannon** [comment]
Closing, as this PR was merged earlier into another PR before the Pension form launched.

**Pull request closed without merging**
