### PR TITLE
VET TEC: Update Introduction Page Link #18560

### PR DESCRIPTION
**Pull request by zurbergram**
## Description

As an applicant, I need to be redirected to a list of programs so that I can determine if I would like to complete the VETTEC application.

## Testing done
- [ ] local testing

## Acceptance criteria
- [ ] The "Learn more about the programs covered under VET TEC" link on the introduction page takes the user to the following page:
https://www.benefits.va.gov/GIBILL/FGIB/VetTecTrainingProviders.asp

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by devin-mccurdy — APPROVED** [review]
LGTM

**Comment by zurbergram** [comment]
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!

**Review by rianfowler — COMMENTED** [review]
I think this might have been branched off some unmerged changes- the description is for a link update but there's a new form included in this PR.

**Comment by zurbergram** [comment]
> I think this might have been branched off some unmerged changes- the description is for a link update but there's a new form included in this PR.

you are correct, new form changes are in https://github.com/department-of-veterans-affairs/vets-website/pull/10043
I'll make sure to merge that first before this PR so PR size is reduced

**Review by rianfowler — APPROVED** [review]

**Review by delli-gatti-michael — APPROVED** [review]
This passes QA

**Pull request merged**
