### PR TITLE
Month year fix

### PR DESCRIPTION
**Pull request by alexose**
Fixes issue with review component described in #3675:

image

### CODE REVIEW

**Comment by cweber** [comment]
I could never really replicate that bug so it's hard for me to do too much review, but I did realize one more thing about language.

For some reason we have a completely different statement for high school graduation date in form/review. I had just noticed the month/year business before, but we need to fully normalize that statement. And let's just remove the reference to date fields entirely. It should read:

When did you earn your high school diploma or equivalency certificate?

**Comment by jbalboni** [comment]
@alexose, I think this fixes the date not showing up on the review page, but it seemed like #3675 described a validation bug, too? I couldn't replicate it, though.

**Review by jbalboni — APPROVED** [review]
LGTM as far as fixing the date displaying on the review page.

**Comment by alexose** [comment]
Correct, this is just for the review page.  Will merge after CI

**Pull request merged**
