### PR TITLE
initial yarn workspace set up for vaos app

### PR DESCRIPTION
**Pull request by rmessina1010**
Setting up yarn workspaces for vaos app.

## Description
Adds Yarn Workspaces  to vaos app in vets website

## Original issue(s)
---

## Testing done
- [x] Confirm demo scripts run
- [x] Confirm sym link in root  `node_modules` folder is present after  yarn install
- [x] Unit/e2e
- [ ] Visual Web Test:  link  pending 

## Tasks for vaos team to do prior to merging
- [x]  Check dependencies/devDependecies / peerDependencies are correct for your app
- [x]  If required, add `nohoist`  dependencies to root `package.json`
- [x]  If required , add scripts
- [ ]   Visual Test  link pending
- [ ]  Approve PR

Docs:
https://depo-platform-documentation.scrollhelp.site/developer-docs/guide-for-maintainers-overview
(Please note that as a VSF app, you don't have any exports (or need an exportsFile.js)

## Acceptance criteria
- [ ] Testing done completed
- [x]  Tasks For vaos team to do

### CODE REVIEW

**Comment by rmessina1010** [comment]
Passed  Local  e2e with `CHOMA_SEED=8Yl4bEGoUS`

Worthy of investigation: `src/applications/personalization/dashboard/tests/unit/ClaimsAndAppeals.unit.spec.jsx:510:23`
```
  1) ClaimsAndAppeals component
       happy path render logic
         when user has two open claims (one recently updated), one open appeal, and one closed claim
           shows details for the most recently updated claim:
     TestingLibraryElementError: Unable to find an element with the role "link" and name `/^view claim received/i`

**Comment by simiadebowale** [comment]
@rmessina1010 - LGTM! Tested locally and everything works as expected.

**Review by vbahinwillit — APPROVED** [review]

**Review by CBonade — APPROVED** [review]
LGTM

**Review by ryanshaw — COMMENTED** [review]
LGTM

**Pull request merged**
