### PR TITLE
Updated navigation menu to reflect new eligibility links/content.

### PR DESCRIPTION
**Pull request by ghost**
Related to department-of-veterans-affairs/vets.gov-team#1584

### CODE REVIEW

**Comment by tiffanybbrown-va** [comment]
I hope this is failing because the links don't exist yet, and not for some other reason.

**Review by rroueche — APPROVED** [review]
LGTM, agree that it's erroring bc the links don't exist yet. Here they are in staging:

https://vetsgov-pr-5043.herokuapp.com/healthcare/eligibility/
https://vetsgov-pr-5043.herokuapp.com/disability-benefits/eligibility/
https://vetsgov-pr-5043.herokuapp.com/education/eligibility/

I'll add @melwoodard as a reviewer as well, but I think this is good to be merged on Thursday 3/16!!

**Comment by rroueche** [comment]
That seems to be the case!
image

**Review by jcmeloni-usds — APPROVED** [review]
LGTM; I think we'll have to work with James to ensure timing is ok so that this can be merged after the content is merged so that Jenkins doesn't throw up -- does that sound right?

**Review by melwoodard — APPROVED** [review]
Looks good! 

Side note: seeing that Tiffany had to manually increase the menu height to allow for one more link in Disability, we'll probably need to tweak that design to make it more scaleable in parallel with upcoming content additions.

**Comment by tiffanybbrown-va** [comment]
I'll play around with height and positioning and see if I can't make it more flexible.

**Comment by rroueche** [comment]
@tiffanybbrown-va should I just ping you tmrw morning to merge? or should we assign to @jkassemi  so that he can manage this + the redirects?

**Comment by tiffanybbrown-va** [comment]
I added redirects to our MetalSmith configuration, but I'm not sure whether that's all that needs to be done. I'd assign it to @jkassemi just in case.

**Comment by rroueche** [comment]
ok! i also created this issue and assigned to james, so not sure if that should be closed if you already have somethin going on? https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1679 feel free to update however is necessary!

**Comment by rroueche** [comment]
@tiffanybbrown-va ^

**Pull request merged**
