### PR TITLE
Schemaform review array bug fix

### PR DESCRIPTION
**Pull request by cvalarida**
Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2852

Per @jbalboni's [suggestion](https://github.com/department-of-veterans-affairs/vets-website/pull/5553#issuecomment-302427388), I switch between `this.props.arrayData` and `this.state.items` depending on whether or not the items count is locked.

Note: This does do a weird thing where when I add another item to the array, the `updateSchema` is only called once and the title below (if one is set, as it is in this case) doesn't get updated to what it should be. Turns out like this:
image

Only the first letter of the first name makes it, but after I edit, the title is right as rain. Not sure what the deal is there, exactly.

### CODE REVIEW

**Comment by jbalboni** [comment]
@cvalarida I pushed a fix for the title issue. The way it was originally written the title wasn't expected to change, so some internal state wasn't being updated.

**Comment by jbalboni** [comment]
One thing I've noticed is that the scrolling/focusing when you add or remove rows is messed up now, I think because there are two instances of this component pointing to the same array.

**Review by jbalboni — COMMENTED** [review]
This looks good, but I'd like to see the the scrolling issues when editing rows fixed. If that turns into a big thing, we can make a separate item for it.

**Comment by cvalarida** [comment]
Yeah, I noticed that too...I'll see what I can figure out about that.

**Comment by cvalarida** [comment]
I went with the workaround you mentioned, @jbalboni. It's not meant to be a solid solution, but it'll get us out the door without a problem. It will have problems later if we don't use arrays like we are right now, though...

**Pull request merged**
