### PR TITLE
update text per SME request

### PR DESCRIPTION
**Pull request by mollyblake**
update text 'you and your eligible dependents' per request from SME

### CODE REVIEW

**Comment by dannychapman** [comment]
LGTM, assigning to @maryannbrody for a quick pass.

**Comment by maryannbrody** [comment]
LGTM, assuming we all agree that this will change in a few weeks with the plain language editing underway! @jkassemi can you get this content change to prod? thanks!

**Comment by mollyblake** [comment]
@maryannbrody yes, it will change. We thought it was best to make the small fix now, since this page is linked off the new education benefits app that is launching on Monday.  Thanks!

**Comment by jkassemi** [comment]
@maryannbrody, should this be cherry-picked into production or go out with the weekly release cycle along with all changes in master?

cc @crwallace for awareness

**Comment by dannychapman** [comment]
@jkassemi Confirmed with @bethpotts, if it is not too much trouble to cherry pick and go to production, that would be great. If it already has and this is moot, please ignore. Thanks!

**Pull request merged**
