### PR TITLE
VACMS-19960 Update CTA heading level

### PR DESCRIPTION
**Pull request by randimays**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

### :warning: TeamSites :warning:
Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary
Updates the heading level for these CTA widgets:

- Claim or Appeal Status (`/claim-or-appeal-status`) -> changed to `h2`
- Disability Rating (`/disability/view-disability-rating`) -> changed to `h2`
- Education Letters (`/education/download-letters`) -> changed to `h3`
- Home Loan COE Status (`/housing-assistance/home-loans/check-coe-status`) -> changed to `h2`
- View Payment History (`/va-payment-history`) -> changed to `h2`

Also changes the button color of the `Sign in or create an account` button to green to match the [Design System guidance](https://design.va.gov/components/alert/#sign-in-or-tool-prompt) **only when** the widget is using the green ("continue") alert banner. This applies to all widgets in [the CTA configuration file in vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/cta-widget/ctaWidgets.js).

In addition to the above list, a couple of examples where the button color changed:
- Manage VA Debt (`/manage-va-debt/summary`)
- Refill/Track Prescriptions (`/health-care/refill-track-prescriptions/`)

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19956 (Claim or Appeal Status)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19957 (Disability Rating)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19958 (Education Letters)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19959 (Home Loan COE Status)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19960 (View Payment History)

## Screenshots

<details><summary>Claim or Appeal Status (updated heading & button)</summary>

<br />

| Before | After |
| --- | --- |
| Screenshot 2024-12-16 at 3 09 30 PM | Screenshot 2024-12-16 at 3 08 10 PM |
| Screenshot 2024-12-16 at 3 09 34 PM | Screenshot 2024-12-16 at 3 08 15 PM |

</details>

<details><summary>Disability Rating (updated heading & button)</summary>

<br />

| Before | After |
| --- | --- |
| Screenshot 2024-12-16 at 3 13 16 PM | Screenshot 2024-12-16 at 3 12 56 PM |
| Screenshot 2024-12-16 at 3 13 33 PM | Screenshot 2024-12-16 at 3 13 03 PM |

</details>

<details><summary>Education Letters (updated heading & body text)</summary>

<br />

| Before | After |
| --- | --- |
| Screenshot 2024-12-16 at 3 17 35 PM | Screenshot 2024-12-16 at 3 17 13 PM |
| Screenshot 2024-12-16 at 3 17 41 PM | Screenshot 2024-12-16 at 3 17 20 PM |

</details>

<details><summary>Home Loan COE Status (updated heading & button)</summary>

<br />

| Before | After |
| --- | --- |
| Screenshot 2024-12-16 at 3 23 56 PM | Screenshot 2024-12-16 at 3 23 22 PM |
| Screenshot 2024-12-16 at 3 24 32 PM | Screenshot 2024-12-16 at 3 23 37 PM |

</details>

<details><summary>View Payment History (updated heading & button)</summary>

<br />

| Before | After |
| --- | --- |
| Screenshot 2024-12-16 at 3 27 01 PM | Screenshot 2024-12-16 at 3 26 39 PM |
| Screenshot 2024-12-16 at 3 27 07 PM | Screenshot 2024-12-16 at 3 26 47 PM |

</details>

<details><summary>Manage VA Debt (only picked up button color change)</summary>

<br />

| Before | After |
| --- | --- |
| Screenshot 2024-12-16 at 3 44 41 PM | Screenshot 2024-12-16 at 3 44 46 PM |

</details>

<details><summary>Refill/Track Prescriptions (only picked up button color change)</summary>

<br />

| Before | After |
| --- | --- |
| Screenshot 2024-12-16 at 3 49 13 PM | Screenshot 2024-12-16 at 3 49 18 PM |

</details>

## Acceptance criteria

- [x] The widget heading "Sign in to view your VA payment history" is now an H2
- [x] The widget heading "Sign in to view your VA disability rating' is now an H2
- [x] The widget heading "Sign in to check your claim, decision review, or appeal status" has been updated to H2
- [x] The widget heading "Sign in to download your VA education decision letter" is now using an h3 heading instead of using the current <p> tag
- [x] The widget heading "Sign in to check the status of your COE" is now an H2

### Quality Assurance & Testing

- [x] Linting warnings have been addressed
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.

### CODE REVIEW

**Review by eselkin — DISMISSED** [review]
LGTM

**Comment by randimays** [comment]
@laflannery This is ready for your review please!

**Comment by laflannery** [comment]
@randimays the 3 widgets covered but the 3 tickets are correct:
- Payment History
- Disability Ratings
- Claim status

However, the other 2 that were not called out in tickets (Manage Debt and View dependents) should not have had their headings changed, those currently have correct H3 headings because their parent heading is an H2. Can we remove these from this PR?
Screenshot 2024-12-13 at 12 11 11 PM
Screenshot 2024-12-13 at 12 15 23 PM

**Comment by randimays** [comment]
@eselkin I originally made updates to all CTA widgets but they should have been more specific. There are updates to the code; do you mind re-reviewing please?

**Review by eselkin — APPROVED** [review]
LGTM

**Review by IGallupSoCo — APPROVED** [review]
LGTM

**Comment by randimays** [comment]
@laflannery This is ready for another review please :)

**Comment by laflannery** [comment]
@randimays All the headings on these pages in the RI look good now. However, these seem to have changed on Prod in a couple places and aren't using the same widget anymore, will that matter? For example:
- [Claim Status on Prod](https://www.va.gov/claim-or-appeal-status/) has a blue sign in widget instead of a green one that is [on the RI](http://ffb92bacea7172c590dd38a9606a7862.review.vetsgov-internal/claim-or-appeal-status/)
  - Will the Heading change you made on the green one still apply to the blue widget?
  - Will the button change to green because it should now remain blue?

This same situation is happening on View payment History, Disability Rating, and Home Loan Status as well

**Comment by randimays** [comment]
@laflannery Thanks for checking that! The green button color goes with the "continue" type of alert. Since some of these changed to "info" (blue), they'll get a blue button. I updated with the `main` branch locally and checked the 5 widgets again. I didn't push these changes so the review instance will not be updated, but if you'd like to sanity check here are some screenshots:

### `/claim-or-appeal-status/`

Screenshot 2024-12-18 at 8 33 36 AM
Screenshot 2024-12-18 at 8 33 45 AM

### `/disability/view-disability-rating`

Screenshot 2024-12-18 at 8 36 55 AM
Screenshot 2024-12-18 at 8 37 02 AM

### `/education/download-letters`

Screenshot 2024-12-18 at 8 37 31 AM
Screenshot 2024-12-18 at 8 37 40 AM

### `/housing-assistance/home-loans/check-coe-status`

Screenshot 2024-12-18 at 8 38 39 AM
Screenshot 2024-12-18 at 8 38 45 AM

### `/va-payment-history`

Screenshot 2024-12-18 at 8 39 58 AM
Screenshot 2024-12-18 at 8 40 04 AM

**Comment by laflannery** [comment]
Excellent, thank you!! and approved!

**Pull request merged**
