### PR TITLE
Add babel caching and fix sourcemaps

### PR DESCRIPTION
**Pull request by jbalboni**
This fixes a couple issues I've noticed:
1. Sourcemaps have stopped working. I'm not sure exactly when, but I think it's [this issue](https://github.com/webpack/webpack/issues/2145). Changing to `#eval-source-map` works at the cost of slightly slower rebuilds.
2. `cacheDirectory: true` does not appear to do anything. Changing it from `true` to a directory results in what you'd expect if Webpack were caching Babel transformations: a ~10s boost in build times after the first one.

### CODE REVIEW

**Comment by jbalboni** [comment]
I'm not sure who should look at this. @alexose, @crwallace, or @bshyong?

**Comment by alexose** [comment]
LGTM.  

I suspect adding .babelcache to [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.travis.yml#L19-L22) would improve our travis build times as well.

**Comment by jbalboni** [comment]
@alexose Think that's worth doing in this PR?

**Comment by alexose** [comment]
It's a big pain to test travis builds (believe me), so maybe it's best saved for a future branch :)

**Pull request merged**
