### PR TITLE
VACMS-14613: Remove scroll from Income Limits

### PR DESCRIPTION
**Pull request by chriskim2311**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary
This ticket resolves an A11y defect that had the page scroll up when navigating through income limits app. Now we auto focus to breadcrumbs and will not auto scroll.

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-cms#14613

## Testing done

- _Describe what the old behavior was prior to the change_
Each page would auto-scroll to top of page no matter where you were on screen.
- _Describe the steps required to verify your changes are working as expected_
Now we load at the top of page with navigating through the app.

### Quality Assurance & Testing

- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### CODE REVIEW

**Comment by chriskim2311** [comment]
@laflannery Can you take a look at this new functionality for IL. I have removed the scrolling up functionality and will load at the top of the page. I can setup a mobile link for you as well.

**Comment by laflannery** [comment]
@chriskim2311 The loading looks much better, approved!

I did have just one other note because I wanted to make sure it wouldn't be an issue when you push this to prod - I can't get past the zip code screen anymore, it's saying that the zip codes I'm adding are all invalid but that's not true:

(O2038 is Franklin, MA where I live and 02210 is in Boston, MA):
Current Flow:
image

Past Flow:
image

**Comment by laflannery** [comment]
Also @chriskim2311 I also would like a mobile link - because I happened to look at the code (for other reasons) and the waitForRender I believe was what we had done to make the focus work properly for screen readers in iOS so I want to see if this changed that behavior

**Comment by chriskim2311** [comment]
@laflannery Not a problem! Here is the mobile link.
https://46f2-108-206-151-63.ngrok-free.app/health-care/income-limits/introduction

**Comment by randimays** [comment]
@chriskim2311 I'm seeing a little bit of inconsistency when going from page to page with this solution. @laflannery for accessibility, is it best if we scroll all the way to the top of the page (including the header) when going forward and backward? In some cases, it's only scrolling to the top of the `<h1>` and the breadcrumbs aren't visible.

https://github.com/department-of-veterans-affairs/vets-website/assets/19175324/39250e32-64c4-41b4-bc7b-224e32a90994

**Comment by laflannery** [comment]
@randimays We were having trouble getting the API to work with the review instance so I only had the into, year and zip screens to work with. It would be best to always see the breadcrumbs each time the user navigates to any of the screens

**Comment by chriskim2311** [comment]
@randimays Just met with @laflannery and verified behavior was working as expected locally

**Review by randimays — APPROVED** [review]

**Pull request merged**
