### PR TITLE
[CDP] - [LTR] - Remove Unused Applications

### PR DESCRIPTION
**Pull request by OptionSelect**
## Summary

Combined Debt Portal has replaced the old applications Medical Copays and Debt Letters. Removing these old unused applications has been on our radar for a while now but now that CDP has been released for at least half a year we feel comfortable removing the now deprecated applications.

This PR is for removing Debt Letters as well as updating links in other apps that used to point to the now removed application that will now point to our combined experience.

The below PR is when the last vestiges of those applications usage existed, and have since been removed.
https://github.com/department-of-veterans-affairs/vets-website/pull/22023

## Related issue(s)

department-of-veterans-affairs/va.gov-team#77329

## Testing done

Navigated through other applications and ran site successfully.

image

image

## What areas of the site does it impact?

CDP, MCP, LTR

### Quality Assurance & Testing

- [ X ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ X ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ X ] Linting warnings have been addressed
- [ X ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ X ] Screenshot of the developed feature is added
- [ X ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ X ] Browser console contains no warnings or errors.
- [ X ] Events are being sent to the appropriate logging solution
- [ X ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ X ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by Dr-Pongo** [comment]
[x-posting a comment](https://github.com/department-of-veterans-affairs/vets-website/pull/28461#issuecomment-1988781699) on the sister PR for removing `medical-copays` for some helpful references!

**Review by ataker — DISMISSED** [review]

**Review by adamwhitlock1 — DISMISSED** [review]
LGTM for authenticated experience/personalization changes

**Review by allisonlu — DISMISSED** [review]

**Review by randimays — DISMISSED** [review]
Looks good from the Public Websites perspective.

**Review by adamwhitlock1 — DISMISSED** [review]

**Review by longmd — DISMISSED** [review]

**Comment by OptionSelect** [comment]
Investigating / working on fixing the failing unit tests, it's passing locally atm which is interesting.
image

**Comment by OptionSelect** [comment]
Still working on figuring out 
image

**Comment by OptionSelect** [comment]
Closing to make v2 branch because of previously deleted folder and reverting commits in sister branch caused an explosion of reviews / untracked files.

**Pull request closed without merging**
