### PR TITLE
removes outdated DD downtime banner

### PR DESCRIPTION
**Pull request by asg5704**
## Summary

- _(Summarize the changes that have been made to the platform)_
This will remove the outdated Disability & Direct Deposit Downtime banner that was displaying in Production recently.
- _(If bug, how to reproduce)_
It was observed in Production by Elizabeth (see Before image)
- _(What is the solution, why is this the solution)_
The solution is to update the `LoginHeader` component and remove the custom logic request from that team (over 9 months ago)
- _(Which team do you work for, does your team own the maintenance of this component?)_
Identity. Yes.
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_
n/a

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#57874
- _Link to previous change of the code/bug (if applicable)_
department-of-veterans-affairs/vets-website#21918
- _Link to epic if not included in ticket_
department-of-veterans-affairs/va.gov-team#0000

## Testing done

- _Describe what the old behavior was prior to the change_
Updated unit tests (removed the test checking for the downtime banner)
- _Describe the steps required to verify your changes are working as expected_
Unit tests are successful, manual using Flipper to confirm
- _Describe the tests completed and the results_
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Desktop | image  | Screenshot 2023-05-04 at 10 55 40 AM |

## What areas of the site does it impact?
This impacts the entire site when a user Signs in (Sign in Modal or Unified Sign in Page)
*(Describe what parts of the site are impacted and*if*code touched other areas)*

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.go header) :warning:

- [x] The vets-website header does not contain any web-components
- [x] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [x] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by joeniquette — APPROVED** [review]
I tested on localhost and confirmed the banner is gone and authentication still works.

@asg5704 Do we need to test if this impacts teamsites?

**Comment by asg5704** [comment]
> I tested on localhost and confirmed the banner is gone and authentication still works.
> 
> @asg5704 Do we need to test if this impacts teamsites?

Because this is removing code rather than adding it I think it will be fine.

**Comment by asg5704** [comment]
> I tested on localhost and confirmed the banner is gone and authentication still works.
> 
> @asg5704 Do we need to test if this impacts teamsites?

@joeniquette I think we should be fine since this is removing code rather than adding it.

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Pull request merged**
