### PR TITLE
EZR: Remove TERA feature toggle

### PR DESCRIPTION
**Pull request by dellerbie**
Removes the TERA feature toggle

## Related issue(s)

- department-of-veterans-affairs/va.gov-team#85114

## Testing done

- Ensure specs still pass

## What areas of the site does it impact?
Form 10-10EZR

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### CODE REVIEW

**Review by rmessina1010 — DISMISSED** [review]
LGTM

**Review by coope93 — APPROVED** [review]

**Review by coope93 — CHANGES_REQUESTED** [review]
I noticed we still have `  "ezrTeraEnabled": "ezr_tera_enabled",` in the `featureFlagNames.json` and `ezr_tera_enabled: true,` in the `feature-toggles.unit.spec.js`. Do those need removed as part of this? Additionally, it looks like in vets-api we still have the toggle in the `features.yml` file.

**Review by Mitch-A6 — DISMISSED** [review]
👏  that's a lot of touchpoints to remove one feature flag! Nice work.

**Review by mkerns1 — DISMISSED** [review]
LGTM!

**Review by coope93 — DISMISSED** [review]

**Review by coope93 — APPROVED** [review]

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Pull request merged**
