### PR TITLE
Show status descriptions for previous appeals history events in accordion style.

### PR DESCRIPTION
**Pull request by U-DON**
Resolves department-of-veterans-affairs/vets.gov-team#3870.

screen shot 2017-07-21 at 8 37 44 pm

### CODE REVIEW

**Comment by altangel** [comment]
@U-DON the expanded text should be indented to lineup with the date and the + and - should be smaller (try 13px width).

**Review by aub — APPROVED** [review]
I dig it

**Comment by U-DON** [comment]
Updated. @altangel 

screen shot 2017-07-24 at 3 39 33 pm

**Comment by altangel** [comment]
@U-DON Looking good! Is it possible to center the + with the text when it's 2 lines?

**Pull request merged**
