### PR TITLE
Content/wip/health care plain language updates

### PR DESCRIPTION
**Pull request by rroueche**
Creating PR for the most up-to-date branch for this work, replacing PR #4106

### CODE REVIEW

**Comment by bethpotts** [comment]
@rroueche I've incorporated SME suggestions. Looks like there's a failed check. Can you help? Then we're ready for Mary Ann's approval to push the PL edits to production for this one HCA page.

**Comment by rroueche** [comment]
@bethpotts checking now!

**Comment by bethpotts** [comment]
@maryannbrody @rroueche I've incorporated SME feedback and this is ready to push to production pending your approval, Mary Ann.

**Comment by maryannbrody** [comment]
Looks good to me @bethpotts and @rroueche. Thanks!!

**Comment by rroueche** [comment]
@bethpotts and @maryannbrody this has been merged and should go live this afternoon. I'm sorry for the delay again! I think I have my github process set now so that I won't miss things like this.

**Pull request merged**
