### PR TITLE
Added What happens after rating page

### PR DESCRIPTION
**Pull request by dannychapman**
WIP

### CODE REVIEW

**Comment by dannychapman** [comment]
what to expect after you get a disability rating vets gov

**Comment by bethpotts** [comment]
@mariana-almeida @dannychapman Mariana and I rewrote a subhead. Waiting now to be able to preview, but "View deployment" isn't working. Danny will send another screenshot so we can preview.

**Comment by mariana-almeida** [comment]
@bethpotts - what's the status on this please?

**Comment by dannychapman** [comment]
what to expect after you get a disability rating vets gov

**Comment by mariana-almeida** [comment]
@dannychapman Can you confirm if that grey highlight is or isn't part of the page? Otherwise, it looks good to publish. @bethpotts have a look!

**Comment by bethpotts** [comment]
@dannychapman @mariana-almeida It all looks good to me, except what Mariana is noting: there's a whole line under the subhead "Look for a payment within 15 days" that's highlighted gray. Can you remove that? 

Thanks so much for your work on this page, Danny! Is it you or someone else I should contact about getting this published (which involves adding a piano key on the Claims Process page, I believe)?

**Comment by dannychapman** [comment]
@mariana-almeida Grey highlight is not part of the page, so I'm going to merge this one.

**Comment by mariana-almeida** [comment]
@dannychapman Question - what is the URL of the live page? I tried this one and it wasn't correct:

https://www.vets.gov/disability-benefits/claims-process/what-happens-after-rating

**Comment by dannychapman** [comment]
@mariana-almeida you can view it here: https://dev.vets.gov/disability-benefits/claims-process/what-happens-after-rating/

**Pull request merged**
