### PR TITLE
41492 Display Type of Care on Community Care Booked Appointment [V2]

### PR DESCRIPTION
**Pull request by vbahinwillit**
## Description
This PR modifies the CC details page to display type of care.

## Original issue(s)
department-of-veterans-affairs/va.gov-team#41492

## Testing done
Unit testing

## Screenshots
localhost_3001_health-care_schedule-view-va-appointments_appointments_
---
localhost_3001_health-care_schedule-view-va-appointments_appointments_cc_01aa456cc
---
localhost_3001_health-care_schedule-view-va-appointments_appointments_ (1)

## Acceptance criteria
- [ ] All test should pass

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by simiadebowale — APPROVED** [review]
LGTM!

**Comment by jenniemc** [comment]
Hi @vbahinwillit, I'm not able to access review instance,  http://e370a40bd8aaa4800719377a502e61da.review.vetsgov-internal/  Maybe it has lapsed. Can you build a new review stance?

**Review by jenniemc — APPROVED** [review]
Looks good to me!
The only discrepancy is when cancelling a CC pending appointment in local environment, it correctly shows canceled by patient. Whereas, in the review instance, it shows canceled by Facility. The cancel bug is beyond the scope of this ticket.

**Review by jenniemc — APPROVED** [review]
LGTM!

**Review by ryanshaw — APPROVED** [review]

**Comment by vbahinwillit** [comment]
Closing this pull request and creating a new one due to the file 'CalculateYourBenefits.jsx' being modified by a merge from main into my local branch. This is now requiring a code review from afs-codereview-owners.

**Pull request closed without merging**
