### PR TITLE
[12679] Print Appointment Details

### PR DESCRIPTION
**Pull request by LanceGundersen**
## Description
Currently to print in VAOS means printing the full homepage of all the upcoming appointments. This isn't practical, especially for some Veterans who have a long list of appointments.

Instead, as part of us improving details about appointments, we should enable the ability to print individual appointments.

## Testing done
Local and Unit

## Screenshots
VVC
image
image
CC
image
image
VA
image
image

## Acceptance criteria
- [ ] Changes are behind the `va_online_scheduling_homepage_refresh` feature flag
- [ ] Print link appears on confirmed appointment detail pages
- [ ] When user clicks/taps Print link, open default browser dialog box [VA, CC, VVC]
- [ ] Printable page does not include navigation links (breadcrumb, go back)
image
- [ ] DESIGN - All desktop, tablet, and mobile designs match the specs:
VA - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/WKROK1n#Inspector
CC - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/QbaZbAx#Inspector
VVC - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/Kv9bDLV#Inspector

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by vbahinwillit** [comment]
LGTM

**Comment by jbalboni** [comment]
@LanceGundersen Should we hide the add to calendar, cancel, etc links while we're at it? Those aren't useful when printing.

**Comment by LanceGundersen** [comment]
> @LanceGundersen Should we hide the add to calendar, cancel, etc links while we're at it? Those aren't useful when printing.

@jbalboni Reasonable point, I will run it by Peter and Lauren to see if they want it in this ticket or another.

**Comment by LanceGundersen** [comment]
> @LanceGundersen Should we hide the add to calendar, cancel, etc links while we're at it? Those aren't useful when printing.

@jbalboni it is noted and deemed outside the scope for this ticket. Will fix in a follow-up ticket.

**Review by jbalboni — APPROVED** [review]

**Pull request merged**
