### PR TITLE
VACMS 16945 Vet Centers - Locations - Expandable alert component

### PR DESCRIPTION
**Pull request by eselkin**
## Summary

- Simplifies operating status code. Converts custom react code to VA DS expandable alert component 
- Sitewide Facilities

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16945
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/79970

## Testing done

- Operating Status was a custom component
- Unfortunately dev lighthouse doesn't seem to ever give us back something not code normal, so I added a test to cover the presence or absence of the va-alert-expandable

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._
<details>
<summary>Before</summary>
Screenshot 2024-05-16 at 4 55 29 PM
</details>

<details>
<summary>After limited service</summary>
Screenshot 2024-05-16 at 4 50 43 PM
</details>

<details>
<summary>After closed</summary>
Screenshot 2024-05-16 at 4 52 50 PM
</details>

## What areas of the site does it impact?

Vet Center Locations page, Nearby Vet Centers

## Acceptance criteria

- [x] uses component
- [ ] accessibility testing

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Comment by maxx1128** [comment]
@eselkin, I saw this as still waiting for review; I'm sorry I didn't look more closely at the code sooner. The code itself looks good. Does it need any updates or rebasing before I give any official approval?

**Comment by eselkin** [comment]
@maxx1128 I forgot all about this PR. Actually checked on it because of a question from @jestutt 

@maxx1128 Shouldn't need any more updates, just merged in main. It basically just changes the Operating Status to use the expandable alert.

**Review by maxx1128 — DISMISSED** [review]

**Comment by jilladams** [comment]
@eselkin does this PR correlate to your note on https://github.com/department-of-veterans-affairs/va.gov-team/issues/79970#issuecomment-2115783083 ?

**Comment by eselkin** [comment]
Yes. But for some reason I didn't complete the top text of this PR. Going to do that after it builds locally.

**Comment by eselkin** [comment]
Added a test

**Comment by laflannery** [comment]
@eselkin a couple questions/issues:
- The After screen shots look good, they are using the component so yay
  - However, I'm not going to be able to test in the RI this because of the weird issue RIs have where the Expandable alert component disappears
- Also, if I'm understanding correctly, this work will close [this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17892), correct?

**Review by laflannery — APPROVED** [review]

**Comment by eselkin** [comment]
@laflannery Yes, it that ticket, but it actually had been in the pipeline before that ticket was written, just didn't get approved then got stale and I forgot about it.

**Review by maxx1128 — APPROVED** [review]

**Pull request merged**
