### PR TITLE
Enable connected accounts feature in production environments.

### PR DESCRIPTION
**Pull request by dvogel**
This feature is scheduled to go live soon. Prepping this PR now so that we can quickly merge it when the time comes.

### CODE REVIEW

**Review by juliasolorzano — COMMENTED** [review]
@dvogel exciting!

I think we might need to update this too for official launchtime: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/account/components/ConnectedAccountsSection.jsx#L14

**Comment by rtluu** [comment]
@department-of-veterans-affairs/frontend-review-group would you all be able to give this a review? Thanks!

**Review by jbalboni — APPROVED** [review]

**Comment by jbalboni** [comment]
@dvogel You might want to prefix the name of this PR with `HOLD` or `DO NOT MERGE`. We typically do that for PRs that are approved and waiting to get the go ahead to go live, just to be safe.

**Review by juliasolorzano — APPROVED** [review]

**Review by ncksllvn — APPROVED** [review]
LGTM 👍

**Comment by dvogel** [comment]
My team is ahead of schedule and ready for this to go live tomorrow so removing the `[HOLD]` tag and merging now.

**Pull request merged**
