### PR TITLE
Removed blog posts, Experience index page.

### PR DESCRIPTION
**Pull request by webinista**
Closes department-of-veterans-affairs/vets.gov-team#674

- Removed "Message from the Secretary" from footer.
- Removed blog-related CSS.

### CODE REVIEW

**Comment by webinista** [comment]
I have no idea why this is failing. Can you help with insight @jkassemi?

**Comment by jkassemi** [comment]
Just getting it fixed as part of https://github.com/department-of-veterans-affairs/devops/issues/1352. I just merged a change from master that should resolve the problem. Will monitor.

**Comment by jkassemi** [comment]
Jenkin's running the build correctly. 

It looks like there are some issues with the Jenkins Blue Ocean build details when the branch name contains a '#'. I'll look into whether this is a known issue with Jenkins and see if I can get a fix in place. 

In the meantime, is it possible we can figure out an alternate branch naming convention?

**Comment by webinista** [comment]
😕 that's inconvenient. Should I rename this branch and open a new PR?

**Comment by jkassemi** [comment]
It's an issue with the "new" Jenkins UI (Blue Ocean). We still have the logs from the build, it's just not as easy to navigate to them from the "Details" link next to the check results. 

We're good to keep this PR, just concerned about maintaining the naming convention until we've found a way to address the problem.

**Comment by webinista** [comment]
Okay. Going forward, I'll leave # out of branch names. Thanks for debugging!

**Comment by jcmeloni** [comment]
LGTM

**Pull request merged**
