### PR TITLE
[EFSR](Bug)Credit card cancel button and installment contracts

### PR DESCRIPTION
**Pull request by amponce**
## Summary

Clicking cancel resulted in a blank screen when bills === 0.

- [Parent Functionality Ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55628)
- Cancel (back) button on adding first Credit Card bill should take the user back to the radio button question, and Mini Summary page should be able to display if length of list is zero (blank screen is page rendering but not map in component).

Investigate to see if this issues also applies to similar pages (Vehicle, Installment Contracts)
## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#58977

## Testing done

- Old behavior resulted in an error if the user hit the cancel button when 0 contract-installments existed
- Manual testing
- Cypress Testing

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

 <table>
  <tr>
    <th>Credit card bill fix</th>
  </tr>
  <tr>
 <td>
      Screenshot 1
    </td>
    <td>
      Screenshot 2
    </td>
</tr>
  
</table>

## What areas of the site does it impact?

EFSR form

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

- [x] Update Cancel (back) navigation from first instance of new Credit Card Bill.
- [x]  Confirm Credit Card Bill mini summary page can handle empty list.
- [x] Confirm issue doesn't exist on related pages..

### CODE REVIEW

**Comment by Dr-Pongo** [comment]
### Credit Cards
- No Amount overdue results in `Amount overdue: $NaN` on mini summary card. It's optional, so maybe we can give it zero if nothing is provided (somewhere in the `setFormData`). 
  - Slightly out of navigation scope, so we can spin a new ticket if it's easier. 
- Adding to empty page results in form break
  - Check onDelete (if length is 0 we flip the `question` to false, let's try removing that (I'm doing something similar for vehicles).
- onDelete throws `Cannot read properties of undefined (reading 'type')` error.

### Installment Contracts
- Seeing add new page between radio and summary when we already have something in the list. Steps to reproduce:
  - Select Yes on radio
  - Fill out info for installment contract
  - See card on review page - select back
  - Back to radio button, select continue
    - continue here navigates to adding new contract when it should go to summary.
  - Note: this also borks the form complaining about `Cannot read properties of undefined (reading 'length')`. Maybe something to do with trying to add to an existing contract (indexing), not super sure, but we can take a closer look later. 
- `Date the loan began` required tag gets removed after filling out Minimum monthly payment amount
  - Slightly out of scope of navigation, so we can spin a new ticket if it's easier. 
- `Date the loan began` showing with empty no date if not completed on summary card, can probably just conditionally render that row if it's not provided. 
  - Slightly out of scope of navigation, so we can spin a new ticket if it's easier. 

### Other notes
- `employmentHistory` can be removed from `mapStateToProps` since it doesn't apply here

**Comment by amponce** [comment]
@Dr-Pongo 

> - [x] No Amount overdue results in Amount overdue: $NaN on mini summary card. It's optional, so maybe we can give it zero if nothing is provided (somewhere in the setFormData). Slightly out of navigation scope, so we can spin a new ticket if it's easier. Adding to empty page results in form break
Fixed

> - [x] Check onDelete (if length is 0 we flip the question to false, let's try removing that (I'm doing something similar for vehicles).

Turned out to be related to `setData` import

> - [x] onDelete throws Cannot read properties of undefined (reading 'type') error.

Was related to missing import causing `setFormData` to send undefined object to our analytics middleware, also was causing the .`length` error on installment contracts 

> - [x] Date the loan began required tag gets removed after filling out Minimum monthly payment amount
Slightly out of scope of navigation, so we can spin a new ticket if it's easier.

Fixed with` !!`

**Comment by amponce** [comment]
Looks like hiding the date is causing some tests to fail, I'll fix that in the morning

**Review by Dr-Pongo — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
