### PR TITLE
Removal of production flags for stories 19402 and 19418

### PR DESCRIPTION
**Pull request by elder-joseph**
## Description
Removing the productions flags used for:
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19402

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19418

Originating Issue (for 19418): 
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19469

## Testing done
Local Unit tests pass QA and UX approval in staging environment

## Screenshots
image

fullpage

## Acceptance criteria
- [x] Production flags removed

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by zurbergram — APPROVED** [review]
LGTM

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by sonntag-adam — APPROVED** [review]

**Comment by cvalarida** [comment]
@elder-joseph Can you give this a little more color? The connected ticket is pretty bare, so I'm not confident I know what's going on. Removing the production flag for the "VET TEC profile application process changes", but I don't know what that is or what all it entails.

The code itself looks fine, but I think I need a little more context before I can give this the thumbs up.

**Comment by shawkey-daniel** [comment]
> @elder-joseph Can you give this a little more color? The connected ticket is pretty bare, so I'm not confident I know what's going on. Removing the production flag for the "VET TEC profile application process changes", but I don't know what that is or what all it entails.
> 
> The code itself looks fine, but I think I need a little more context before I can give this the thumbs up.

This PR is just removing the production flags associated with issues 19402 and 19418. 19402 is a styling change for a learn more link and 19418 is a minor text correction.

**Comment by elder-joseph** [comment]
Thanks for the reply @shawkey-daniel. @cvalarida please let me know if there is any additional information you may need regarding these changes.

**Review by cvalarida — APPROVED** [review]

**Pull request merged**
