### PR TITLE
MDOT: Batteries Page- Add Prescribed Date

### PR DESCRIPTION
**Pull request by maharielrosario**
## Description
This PR focused on adding the prescribed date of the battery.

## Screenshots
screenshot-localhost_3001-2020 05 14-10_55_33

## Acceptance criteria
- [ ] Each battery display should show a prescribed date

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by bradl3yC** [comment]
Dates should be formatted like: `April 5, 2020`

**Comment by mr0sari0** [comment]
> Dates should be formatted like: `April 5, 2020`

I think the design had prescribed dates in the MM/DD/YYYY format.

**Comment by bradl3yC** [comment]
> > Dates should be formatted like: `April 5, 2020`
> 
> I think the design had prescribed dates in the MM/DD/YYYY format.

Yes but this is coming directly from 508 review.

**Comment by mr0sari0** [comment]
> > > Dates should be formatted like: `April 5, 2020`
> > 
> > 
> > I think the design had prescribed dates in the MM/DD/YYYY format.
> 
> Yes but this is coming directly from 508 review.

Ok just pushed an update.

**Review by bradl3yC — APPROVED** [review]

**Pull request merged**
