### PR TITLE
Certificate of Eligibility | Fix review & submit a11y

### PR DESCRIPTION
**Pull request by Mottie**
## Description

While running e2e tests on the review & submit page, a previously passing problem showed up. When the previous loan chapter is expanded, there is a outer wrapping DL which has nested DIVs, and the cards within the chapter are missing the wrapping DL.

review & submit page showing html with dl wrapping 4 nested divs before reaching a div which should be a dl

## Original Ticket

[#46916](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46916)

## URL of change

`/housing-assistance/home-loans/request-coe-form-26-1880/review-and-submit`

## Background

The form system is using the platform review `ObjectField` to render the loan chapter. However, it is improperly wrapping the entire chapter in a DL, when it should be wrapping each card (array item) in a DL. In order to fix the outer wrap, a `customTitle` value was set to be a truthy value. This did not fix the inner DL wrapping, and in order to accomplish this, a custom `ui:objectViewField` was set to render the necessary semantic HTML.

## Steps to test

1. Go to https://staging.va.gov/housing-assistance/home-loans/request-coe-form-26-1880/introduction
2. Log into user 228 (Colder Polarbear)
3. Start the form
4. Enable the [save-in-progress menu](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-use-the-save-in-progress-m)
5. Open the save-in-progress menu
6. In a new tab, use "Copy raw contents" from the [COE maximal test data](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/lgy/coe/form/tests/fixtures/data/maximal-test.json)
7. Paste in the data into the save-in-progress menu
8. Set the return url to the review & submit page
9. Use the save-in-progress "Replace" button
10. Expand the "Your VA loan history accordion"
11. Run axe dev tools

## Code changes

- Fixed `existingLoanScreener` yes/no reverse as it was causing the minimal data e2e test to fail
- Updated test data to remove unnecessary data
- Fixed review & submit page a11y issue with wrapping DL/DIV

## How was your code tested

- Manual axe testing on the review & submit page
- Cypress e2e tests

## Acceptance criteria
- [x] Fixede review & submit page a11y issue
- [x] Fixed e2e tests
- [x] All tests passing

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specsv

### CODE REVIEW

**Comment by scottymeyers** [comment]
@Mottie have you gone through and made sure that we're still able to make submissions and that generally things are still working as expected? I'm worried after the introduction of the last bug about breaking anything else at this point during LGY's testing.

**Review by rocio-desantiago — APPROVED** [review]
Ran AxeDev Tools and confirmed DL, DT, DD issues were gone with this fix.

**Review by data-doge — APPROVED** [review]
Looks great. Tested locally. Axe dev tools happy.

**Comment by Mottie** [comment]
> @Mottie have you gone through and made sure that we're still able to make submissions and that generally things are still working as expected?

I just tested it locally a few times. And it is also passing in Cypress e2e tests (locally). Now that the feature flag work has been merged, we can finally get the form to render in production (behind a flag) and test it there

**Pull request merged**
