### PR TITLE
Update CareerScope page

### PR DESCRIPTION
**Pull request by mollyblake**
Add link to CareerScope. Plain language edit

### CODE REVIEW

**Review by rroueche — APPROVED** [review]

**Comment by mollyblake** [comment]
@bethpotts can you eagle eye this?  Thanks!

**Comment by bethpotts** [comment]
@mollyblake @rroueche How can I preview this page? Before you merge, Rachael, I'd like to check the links from preview. I've edited the words and all's good on that front.

**Comment by rroueche** [comment]
@bethpotts let me reset the link - should just take a sec

**Comment by bethpotts** [comment]
@rroueche @mollyblake OK, ready for production! Thank you for merging.

**Review by rroueche — APPROVED** [review]

**Pull request merged**
