### PR TITLE
Updates to run certain entry files and use specific host name

### PR DESCRIPTION
**Pull request by jbalboni**
This has two changes:

- The first is the ability to pass a host name to the build script. The use case for this is to set the host name to `0.0.0.0`, so that the app is visible on your local network and you can pull it up on a phone. We could do this by default, but that seemed slightly risky.
- The second is the ability to pass a list of entry files you want to build. Our Webpack build is slow and most people are not looking at all the apps, they're working on one or two. I think this is especially noticeable for content people, who might just want to build `no-react`, and work on the static pages.

### CODE REVIEW

**Comment by jbalboni** [comment]
@ayaleloehr @jkassemi Thoughts on these changes? Not sure who else to pull in.

**Comment by ayaleloehr** [comment]
@alexose helped a bunch with setting up these things on Rx when we were getting going, so tagging him to see if he has thoughts!

**Comment by alexose** [comment]
Seems like a good, developer-friendly set of changes.  I would add in a line or two to README.md with a few examples.

LGTM though!

**Comment by ayaleloehr** [comment]
Agree with @alexose ; Please add a row in the [README table](https://github.com/department-of-veterans-affairs/vets-website#i-want-to) documenting this, then feel free to merge @jbalboni .

**Pull request merged**
