### PR TITLE
Removes unused feature flag conditional code from appointments list

### PR DESCRIPTION
**Pull request by ryanshaw**
## Summary

This PR removes some unused conditionals based on feature flags that are no longer in use and cleans up the main appointment list component (`src/applications/vaos/appointment-list/components/AppointmentsPageV2/index.jsx`). This should make it easier to make changes to this component.

The following feature flags are no longer in use:

- `vaOnlineSchedulingAppointmentList`
- `vaOnlineSchedulingStatusImprovement`

**_This PR is based on the assumption that we no longer use the feature flags mentioned above._**

Going forward, individual PRs would be authored for other logical groups of components within the `src/applications/vaos/appointment-list/components/AppointmentsPageV2/` directory.

I'd also suggest, during code review, going through commit by commit if the combined diff is difficult to understand -- hopefully the commit messages will add needed detail.

## Related issue(s)

None.

## Testing done

- e2e testing
- Unit testing

### CODE REVIEW

**Review by vbahinwillit — CHANGES_REQUESTED** [review]
The e2e tests are failing. These tests need to be updated to test what's currently in production as well.

**Comment by ryanshaw** [comment]
@vbahinwillit I'll update. Thanks for taking a look.

**Comment by simiadebowale** [comment]
@ryanshaw there are merge conflicts

**Comment by ryanshaw** [comment]
@simiadebowale Yeah, this was semi-exploratory (also removed more than one feature flag). I might use it to do work on: https://github.com/department-of-veterans-affairs/va.gov-team/issues/63664

**Pull request closed without merging**
