### PR TITLE
Add Photo Information to VIC Copy (Plain content)

### PR DESCRIPTION
**Pull request by ncksllvn**
Resolves department-of-veterans-affairs/vets.gov-team/issues/6226

### CODE REVIEW

**Comment by ncksllvn** [comment]
@bethpotts 

image

**Comment by bethpotts** [comment]
@ncksllvn Thanks for updating the screenshot! Can you add another paragraph tag to bring "Note:" down to a new line? And bold "Note:" (bold the colon too)?

**Comment by ncksllvn** [comment]
@bethpotts 

image

**Comment by bethpotts** [comment]
@ncksllvn Perfecto! Thanks, approving now.

**Review by bethpotts — APPROVED** [review]
Changes look good! Thanks, Nick.

**Pull request merged**
