### PR TITLE
reduce app JS size 

### PR DESCRIPTION
**Pull request by mchelen-gov**
## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by batemapf** [comment]
Looks pretty straightforward. How many bytes are we saving from not pulling in all of `lodash`?

**Comment by mchelen-gov** [comment]
> Looks pretty straightforward. How many bytes are we saving from not pulling in all of `lodash`?

Hmm not sure, current size is `163kB` gzipped, `597kB` uncompressed

i was hoping to look at review env for comparison but it looks like the build params are different

**Comment by mchelen-gov** [comment]
lolol afaik this took us from `597kB` to `584K` (uncompressed). we might as well merge it since every bit counts and it also makes the code slightly more readable :shrug:

**Review by stephenBarrs — APPROVED** [review]
LGTM.

**Pull request merged**
