### PR TITLE
Test version of Keyboard End to End tests and a filler test

### PR DESCRIPTION
**Pull request by noahgelman**
[Cypress Commands to add additional keyboard functionality](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16413)

More information about these updates:
These are additional form helper functions that utilize the `cypress-real-events` package to better emulate a user pressing a key. These allow navigating the form via keyboard (Tab), selecting options, and entering text. 

**Note:** Currently choosing an option from a select dropdown is done via typing the characters of that item. Ideally, this would use the arrow keys to go through the options and select one but with the current tools using the arrow keys within a select does not work on Mac devices. This typing method is a workaround until that is fixed in the libraries used.

**To test:**
- Checkout this branch
- Start up `vets-website`: `yarn watch`
- Start the Cypress tool: `yarn cy:open`
- Find `edu-benefits` > `tests` > `feedback-tool` > `02.feedback-tool-keyboard-navigation.cypress.spec.js` and the test should run without issue.)

### CODE REVIEW

**Review by micahchiang — APPROVED** [review]
This looks good to me @noahgelman. You also need an approver from the qa standards github team, as they are codeowners of these files. I recommend filling out the description of the ticket a little more and then converting from draft PR to PR.

**Comment by rsmithadhoc** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/16413
More information about these updates:
These are additional form helper functions that utilize the `cypress-real-events` package to better emulate a user pressing a key. These allow navigating the form via keyboard (Tab), selecting options, and entering text. 

**Note:** Currently choosing an option from a select dropdown is done via typing the characters of that item. Ideally, this would use the arrow keys to go through the options and select one but with the current tools using the arrow keys within a select does not work on Mac devices. This typing method is a workaround until that is fixed in the libraries used.

**To test:**
- Checkout this branch
- Start up `vets-website`: `yarn watch`
- Start the Cypress tool: `yarn cy:open`
- Find `edu-benefits` > `tests` > `feedback-tool` > `02.feedback-tool-keyboard-navigation.cypress.spec.js` and the test should run without issue.

**Comment by rsmithadhoc** [comment]
@department-of-veterans-affairs/qa-standards This is ready for review, I put details in the comment above. There is also additional information on the Issue linked as well, thanks!

**Review by holdenhinkle — APPROVED** [review]
All tests pass:
image

LGTM!

**Comment by rsmithadhoc** [comment]
Hi @department-of-veterans-affairs/frontend-review-group and @department-of-veterans-affairs/afs-code-reviewers,

This PR is ready, is someone able to review and approve this?

Thanks!

**Review by alexandec — APPROVED** [review]

**Review by dan-brooking — APPROVED** [review]

**Review by pjhill — APPROVED** [review]
The down arrow workaround appears to be working in WSL locally for me.

LGTM!

**Pull request merged**
