### PR TITLE
Va gov/content wip health landing page sme edits

### PR DESCRIPTION
**Pull request by DanielleSoCompany**
## Description
Incorporating edits from SMEs into health landing pages

## Acceptance criteria
- [ ]

## Definition of done
- [x] Events are logged appropriately
- [x] Content reviewed
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by bethpotts — APPROVED** [review]
There are two conflicts with links, but the text looks perfect.

**Comment by DanielleSoCompany** [comment]
@ncksllvn @RobAWilkinson @accbjt This is ready to merge. There seems to be a conflict on 2 pages. I think those conflicts are due to the sign-in cta modules, and that "master" has the right cta modules. But I'd like to defer to you all to review/resolve those just in case. Thanks!

**Review by ncksllvn — APPROVED** [review]
👍

**Comment by ncksllvn** [comment]
CTA conflicts have been resolved! Will merge once the build checks out.

**Pull request merged**
