### PR TITLE
Update schema

### PR DESCRIPTION
**Pull request by akainic**
Here's the schema change: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/36

### CODE REVIEW

**Comment by jbalboni** [comment]
In other words: this change in vets-website looks fine, but the commit from vets-json-schema seems weird.

**Comment by akainic** [comment]
@jbalboni ah, good point. Not sure we ran build before merging this PR: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/36. I tried to do that locally myself and no changes were made, however. So perhaps it's okay?

**Comment by jbalboni** [comment]
@akainic Hmm. That schema change isn't going to affect anything in the front end. Ours is in utils/options-for-select.js. Should probably make the same change there.

**Comment by akainic** [comment]
Yup! We did: https://github.com/department-of-veterans-affairs/vets-website/pull/3658

**Comment by jbalboni** [comment]
@akainic Ah, gotcha. This looks good to me, then.

**Review by jbalboni — APPROVED** [review]

**Pull request merged**
