### PR TITLE
Add helper text for facility input

### PR DESCRIPTION
**Pull request by jbalboni**
Adds helper text on the facility page, since we can't make it optional.

screen shot 2017-11-07 at 3 32 05 pm

### CODE REVIEW

**Comment by stacyhlinn** [comment]
@jbalboni Does that link open up facility locator in a new tab?

**Comment by jbalboni** [comment]
@stacyhlinn Yes. All those links open in a new tab. The facility locator line is also currently there already, what's below it is new.

**Comment by jbalboni** [comment]
@stacyhlinn It might be good to try to surface this information earlier (if we aren't already), so people don't fill out a chunk of the form and get here and realize they can't continue.

**Review by cehsu — APPROVED** [review]
LGTM.

**Review by peggygannon — APPROVED** [review]
@jbalboni LGTM. Thanks!

**Review by stacyhlinn — APPROVED** [review]

**Pull request merged**
