### PR TITLE
14472: Update link in how to apply wizard content.

### PR DESCRIPTION
**Pull request by elder-joseph**
## Description
As a user of the form wizard, I need the how to apply wizard to provide me with a direct link to the STEM information page so that I do not have to go through an unnecessary redirect.

[Originating Issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14472)

## Testing done
Testing, passes locally. Unit tests updated.

## Screenshots
N/A

## Acceptance criteria
- [x] The "Edith Nourse Rogers STEM Scholarship" links to: https://www.va.gov/education/other-va-education-benefits/stem-scholarship/

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — CHANGES_REQUESTED** [review]
Can we make these relative links?

**Comment by elder-joseph** [comment]
@shawkey-daniel Sure, I'll switch them over to be relative.

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by delli-gatti-michael — APPROVED** [review]

**Review by rianfowler — APPROVED** [review]
We should update the [codeowners](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/codeowners.md) so changes to this app don't need @department-of-veterans-affairs/frontend-review-group approval.

**Review by zurbergram — CHANGES_REQUESTED** [review]
Fix the relative links

**Review by zurbergram — APPROVED** [review]

**Pull request merged**
