### PR TITLE
Server error copy change for VIC

### PR DESCRIPTION
**Pull request by jkassemi**
When a server error prevents determining Veteran status, use an error
message that points less to a records problem and more to a temporary
systems problem.

### CODE REVIEW

**Comment by bethpotts** [comment]
I'd recommend this PL version:
We're sorry. We can't process your request for a Veteran ID card right now because of a temporary system error.

**Comment by jkassemi** [comment]
Thanks @bethpotts - so you think we shouldn't suggest retrying after a few minutes?

**Comment by bethpotts** [comment]
@jkassemi Sorry about that! I DO think you should leave that in. I just had no changes to that line of text. So, yes, please keep: Please try again in a few minutes.

**Comment by jkassemi** [comment]
Closing, further updates can be made in a new PR.

**Pull request closed without merging**
