### PR TITLE
Updating va-alert styles, prescriptions disclaimer.

### PR DESCRIPTION
**Pull request by webinista**
- Closes department-of-veterans-affairs/kudos-team#269
- Related to department-of-veterans-affairs/vets.gov-designpattrns#28

Changes:

- Moved Disclaimer component inside of the refills application container.
- Changed rx.scss to import _m-alert partial.
- Removed extraneous styles.
- Deleted rx-disclaimer partial
- Removed unneeded classes from Disclaimer.jsx.
- Changed rx-disclaimer to va-alert.

### CODE REVIEW

**Comment by webinista** [comment]
Assigned to Eugene for a code review. Adding Mel and Gina, for a design review.

vaalertclosed
vaalertopen

**Comment by gnakm** [comment]
@webinista It looks like the bolded body is not the same color as the icon and rest of body text. Could you make sure that is our dark-grey (#323A45)?

**Comment by melwoodard** [comment]
Can you check the size of the icon as well? It's a lot larger than in the mockup in https://github.com/department-of-veterans-affairs/vets.gov-designpattrns/issues/28

**Comment by webinista** [comment]
Adjusted color and icon size.

screen shot 2016-11-28 at 2 07 50 pm

**Comment by gnakm** [comment]
LGTM!

**Comment by melwoodard** [comment]
LGTM!

**Comment by U-DON** [comment]
LGTM. @gnakm @melwoodard Is the size of the "+/-" icon okay compared to the resized alert icon?

**Comment by gnakm** [comment]
+/- should be 1.45em.

**Pull request merged**
