### PR TITLE
facility-locator: swap css variable imports

### PR DESCRIPTION
**Pull request by it-harrison**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

### :warning: TeamSites :warning:
Examples of a TeamSite: https://va.gov/health and https://benefits.va.gov/benefits/. This scenario is also referred to as the \"injected\" header and footer. You can reach out in the `#sitewide-public-websites` Slack channel for questions.

Did you change site-wide styles, platform utilities or other infrastructure?
- [ ] No
- [x] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

This PR swaps css variable imports from Formation to CSS-Library in accordance with the deprecation of Formation from vets-website

## Related issue(s)

[3328](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3328)

## Testing done
- local testing on profile, mhv, and combined-debt-portal

## Screenshots
<details><summary>MHV Landing page and Messages</summary>

image
image
image
image
image
image
image
image
image
image

</details>

<details><summary>Profile</summary>

image
image
image
image
image
image
image

</details>

<details><summary>Combined Debt Portal</summary>

image
image
image
image

</details>

<details><summary>Claims Status</summary>

image
image
image
image

</details>

<details><summary>Facility Locator</summary>

image
image

</details>

<details><summary>GI</summary>

image
image
image
image
image

</details>

<details><summary>Injected Header</summary>

image
image
image
image
image
image
image
image

</details>

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by eselkin** [comment]
I have to check out the RI before approving and it's still loading/building

**Comment by eselkin** [comment]
Actually, I forgot, I have it on a tugboat here: https://web-rdikukigkjapf0z74ocsofi8izmc2gmo.demo.cms.va.gov/boston-vet-center/

**Review by randimays — COMMENTED** [review]
Changes look good; will approve when CI is passing.

**Review by powellkerry — APPROVED** [review]

**Review by CBonade — APPROVED** [review]

**Comment by eselkin** [comment]
Changes look good, RI looks good, but not sure what's going on with the E2E tests

**Comment by eselkin** [comment]
breakpoint stability tests are failing for Facility Locator with this change.

**Pull request closed without merging**
