### PR TITLE
Update test logic for SelectDate1Page test for end of month

### LINKED ISSUE #86044: VAOS failing test: VAOS vaccine flow: SelectDate1Page should fetch slots when moving between months
# 1. Test failure or skipped test

- "VAOS vaccine flow: SelectDate1Page should fetch slots when moving between months" is now failing due to slot fetch failure
- This is reproducible on the CI and locally

## Steps to Reproduce
- CI link: https://github.com/department-of-veterans-affairs/vets-website/actions/runs/9541649855/job/26317605669

### Actual Result
Here's the error message for the test failure:
```
1) VAOS vaccine flow: SelectDate1Page
       should fetch slots when moving between months:
     TestingLibraryElementError: Unable to find a label with the text of: /Tuesday, July 2nd/i
<body>
  <div>
    <div>
      <h1
        class="vads-u-font-size--h2"
      >
        Choose a date and time
        <span
          class="schemaform-required-span vaos-calendar__page_header vads-u-font-size--base vads-u-font-family--sans vads-u-font-weight--normal"
        >
          (*Required)
        </span>
      </h1>
      <div
        aria-atomic="true"
        aria-live="assertive"
        class="vads-u-margin-bottom--2"
      >
        <va-alert
          class=""
          status="error"
          uswds="true"
        >
          <h2
            class="vads-u-font-size--h3"
            slot="headline"
          >
            We’ve run into a problem when trying to find available appointment times
          </h2>
          <div
            class="vads-u-font-size--base"
          >
            To schedule this appointment, you can
             
            <a
              aria-label="call your local VA medical center Link opens in a new tab."
              href="/find-locations/facility/vha_442"
              rel="noopener noreferrer"
              target="_blank"
            >
              call your local VA medical center
            </a>
            .
          </div>
        </va-alert>
      </div>
...
      at Object.getElementError (node_modules/@testing-library/dom/dist/config.js:37:19)
      at getAllByLabelText (node_modules/@testing-library/dom/dist/queries/label-text.js:119:38)
      at /home/runner/work/vets-website/vets-website/node_modules/@testing-library/dom/dist/query-helpers.js:62:17
      at getByLabelText (node_modules/@testing-library/dom/dist/query-helpers.js:111:19)
      at _callee5$ (src/applications/vaos/tests/covid-19-vaccine/components/SelectDate1Page.unit.spec.js:423:35)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:294:22)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:119:21)
      at asyncGeneratorStep (src/applications/vaos/tests/covid-19-vaccine/components/SelectDate1Page.unit.spec.js:39:103)
      at _next (src/applications/vaos/tests/covid-19-vaccine/components/SelectDate1Page.unit.spec.js:41:194)
```

## Definition of Done
- [ ] Root cause for test failure is found
- [ ] Test is updated or fixed

---
## How to configure this issue
- [ ] **Labeled with Team** (`appointments`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `testing`
- [ ] **Assigned to** Product for prioritization

### PR DESCRIPTION
**Pull request by JunTaoLuo**
## Summary

- This change uses a more robust logical approach to fix the test instead of the quick fix in https://github.com/department-of-veterans-affairs/vets-website/pull/30204.
  - The previous approach didn't work for the later half of the month since the UI elements will filter out slot dates before the 15th.
  - The current approach adjusts the navigation used in the test based on whether the test is run on the last day of the month or not.
- I have tested this approach for all dates in the next three months to ensure we don't hit any other corner cases.

## Related issue(s)

- Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/86044

## Testing done

- To ensure this test is reliable and won't have corner cases. I ran the test for all future dates in June, July, August and September locally to ensure the logic is robust. See [this commit](https://github.com/department-of-veterans-affairs/vets-website/commit/0f04b06dfb4294e4a94dc8f109c18967f3b9a4cf) for how I ran these tests.

## Screenshots

N/A

## What areas of the site does it impact?

VAOS test changes only.

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Review by vbahinwillit — COMMENTED** [review]
LGTM. There is a duplicate test in:

 ./tests/new-appointment/components/DateTimeSelectPage/index.unit.spec.js:804. 

Should it be modified with your changes for now? The 2 tests should probably be refactored into one at some point.

**Comment by JunTaoLuo** [comment]
It turns out that these two sets of tests are used for two completely separate components. I took a look at `DateTimeSelectPage` and its associated test and it turns out that it has a completely different business logic for displaying dates revolving around `preferredDate` that's not present in `SelectDate1Page`. As a result, that test does not suffer from the end of month arithmetic issue like in this test so we don't need to make any modifications to it.

As to the consolidation effort, I think that covers a lot more than just this one component and its tests. I see a lot of similar components between `new-appointment` and `covid-19-vaccine`. Are you familiar with the history here?

**Comment by vbahinwillit** [comment]
I am not familiar.

**Review by vbahinwillit — APPROVED** [review]

**Pull request merged**
