### PR TITLE
VACMS-17826 Header/footer icon switch to SVG

### PR DESCRIPTION
**Pull request by randimays**
## Summary
The Design System team is deprecating Font Awesome and encouraging teams to use `<va-icon>` where possible by the end of May 2024. Slack post here: https://dsva.slack.com/archives/C03R5SBELQM/p1710776364414359

Because the header and footer code overlaps with the injected header and footer, we cannot convert to `<va-icon>` for these files. Instead, we're going to convert all `<i>` in this application to plain SVGs from the Design System team. **Note**: The scope of this ticket is only to convert icons using Font Awesome (`<i>` tags). If the icon exists in an `` tag, we can track those to convert at a later date.

Slack thread about the injected header/footer icons here: https://dsva.slack.com/archives/C01DBGX4P45/p1712856278144429

Also fixes an Income Limits Cypress test that started failing in the pipeline (presumably because of the 2024 values? But weird that it didn't start failing when we implemented those months ago).

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17826

## Testing done
Tested VA.gov H/F and injected H/F locally on Chrome, Firefox, Safari and mobile. Includes testing for authenticated header/footer as well.

## Screenshots

<details>
<summary>VA.gov header</summary>
Screenshot 2024-04-18 at 3 11 10 PM
Screenshot 2024-04-18 at 3 10 56 PM
Screenshot 2024-04-18 at 3 10 52 PM
Screenshot 2024-04-18 at 3 10 49 PM
Screenshot 2024-04-18 at 3 10 36 PM
Screenshot 2024-04-18 at 3 10 26 PM
Screenshot 2024-04-18 at 3 10 20 PM
Screenshot 2024-04-18 at 3 10 10 PM
Screenshot 2024-04-18 at 3 10 04 PM
Screenshot 2024-04-18 at 3 09 27 PM
</details>

<details>
<summary>Injected header</summary>
Screenshot 2024-04-18 at 3 17 55 PM
Screenshot 2024-04-18 at 3 17 50 PM
Screenshot 2024-04-18 at 3 17 46 PM
Screenshot 2024-04-18 at 3 17 39 PM
Screenshot 2024-04-18 at 3 17 24 PM
Screenshot 2024-04-18 at 3 17 17 PM
</details>

<details>
<summary>VA.gov header, logged in</summary>
Screenshot 2024-04-19 at 1 41 54 PM
Screenshot 2024-04-19 at 1 41 50 PM

</details>
## What areas of the site does it impact?

VA.gov header and footer, injected header and footer

## Acceptance criteria

- [ ] a11y review
- [x] all instances of `<i>` that can be converted to plain SVG are converted

### Error Handling

- [x] Browser console contains no warnings or errors

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [x] The vets-website header does not contain any web-components
- [x] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario

### CODE REVIEW

**Review by powellkerry — DISMISSED** [review]

**Review by laflannery — DISMISSED** [review]
I checked everything except the auth header - I tried to do that locally but wasn't able to get it to work. But everything else looks good

**Comment by randimays** [comment]
@powellkerry Could you please review again? I pushed a fix on `SignInProfileMenu.jsx` to override some formation styles.

**Comment by laflannery** [comment]
Got auth header locally and confirmed auth icons look good

**Review by chriskim2311 — APPROVED** [review]
LGTM Great work! Tested locally

**Review by powellkerry — APPROVED** [review]

**Pull request merged**
