### PR TITLE
Remove Nightwatch specs and helpers that have been replaced with Cypr…

### PR DESCRIPTION
**Pull request by CBonade**
…ess tests

## Description
This PR addresses phase 2 of our effort to move our test specs off of Nightwatch.  After two weeks of monitoring, the converted tests do not seem to be posing issues.  As such, we feel the next step is to clean out the Nightwatch specs and their associated helpers that are no longer necessary.

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by Mottie — APPROVED** [review]
ghe-emoji

**Review by asg5704 — APPROVED** [review]
Woohoo less code!

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by dat-gcio — APPROVED** [review]
LGTM

**Review by micahchiang — APPROVED** [review]

**Review by batemapf — APPROVED** [review]

**Review by erikphansen — APPROVED** [review]
This didn't touch anything that's actually owned by auth-exp so 👍

**Pull request merged**
