### PR TITLE
63664 - Removes va_online_scheduling_appointment_list feature toggle

### PR DESCRIPTION
**Pull request by ryanshaw**
# Summary
Removes references to the `va_online_scheduling_appointment_list` which is no longer used within the appointments application. This should be merged after all related PRs are merged.

## Related issue(s)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/63664
## Testing done
- Unit tests
- e2e tests 

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### CODE REVIEW

**Comment by ryanshaw** [comment]
Closing, duplicate.

**Review by jenniemc — COMMENTED** [review]
Looking good
1.  You may also want to remove the toggle name from https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/utilities/feature-toggles/featureFlagNames.json#L211
2. And include the github ticket for `va_online_scheduling_appointment_list` removal on our [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) under "Ticket to Remove" column

**Comment by ryanshaw** [comment]
> Looking good
> 
>     1. You may also want to remove the toggle name from https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/utilities/feature-toggles/featureFlagNames.json#L211

I believe this was done in [my branch](https://github.com/department-of-veterans-affairs/vets-website/pull/27935/files)... that link goes to `main` I think.

> 
>     2. And include the github ticket for `va_online_scheduling_appointment_list` removal on our [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) under "Ticket to Remove" column

Ahh, good catch. Thanks! Didn't scroll to the right. At any rate, updated.

**Comment by jenniemc** [comment]
> I believe this was done in [my branch](https://github.com/department-of-veterans-affairs/vets-website/pull/27935/files)... that link goes to `main` I think.
>
This json file is located in `/src/platform/utilities/feature-toggles/featureFlagNames.json` outside of the VAOS application folder. You can do a search for `va_online_scheduling_appointment_details_redesign` at the top level of vets-web on your branch and you should be able to locate the json file.

**Review by jenniemc — APPROVED** [review]
LGTM!

**Review by jamigibbs — APPROVED** [review]

**Pull request merged**
