### PR TITLE
remove querySelectors and use refs

### PR DESCRIPTION
**Pull request by rianfowler**
Think I got them all.

### CODE REVIEW

**Comment by jbalboni** [comment]
Should we use the function syntax instead of the string method? https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs

**Comment by rianfowler** [comment]
We should use the callback- I hadn't seen the string ref before working on this project and thought it was new.

I usually store refs as an instance variable on the component. I think we could also store them on the state.

**Comment by jbalboni** [comment]
Instance variable sound good to me.

**Comment by rianfowler** [comment]
Updated to use ref callbacks.

**Review by cehsu — APPROVED** [review]
LGTM. Is there an issue that should be linked to this?

**Review by jbalboni — APPROVED** [review]

**Pull request merged**
