### PR TITLE
Revert "54478 organic experiment modal"

### PR DESCRIPTION
**Pull request by kscoulter**
Reverts department-of-veterans-affairs/vets-website#23695

### CODE REVIEW

**Review by dsasser — APPROVED** [review]
LGTM

**Review by rmessina1010 — APPROVED** [review]
Rollback Approved.

**Review by ryanshaw — APPROVED** [review]
Rollback looks good

**Review by joeniquette — APPROVED** [review]

**Comment by joeniquette** [comment]
@dsasser @oleksii-morgun-va can you please take a look at this to approve the revert. The code introduced a bug.

**Review by RachalCassity — APPROVED** [review]

**Review by alex-morgun-1 — APPROVED** [review]

**Review by mmoyer-va — APPROVED** [review]

**Pull request merged**
