### PR TITLE
EVSS: Change "complete" to "closed"

### PR DESCRIPTION
**Pull request by earthboundkid**
Refs. https://github.com/department-of-veterans-affairs/sunsets-team/issues/321

### CODE REVIEW

**Comment by jbalboni** [comment]
@carlmjohnson There's a line in ClaimEstimate.jsx that says "We estimated your claim would be completed by now..." Should that be changed, too?

**Review by jbalboni — APPROVED** [review]
LGTM, one minor question.

**Review by austin-martinez — APPROVED** [review]
LGTM :shinto_shrine:

**Comment by carlmjohnson** [comment]
I'll merge this now and open another PR if Suzanne wants "We estimated your claim would be completed by now..." changed too.

**Pull request merged**
