### PR TITLE
Change language for expected income

### PR DESCRIPTION
**Pull request by cehsu**
screen shot 2017-08-01 at 2 04 01 pm
screen shot 2017-08-01 at 2 06 40 pm
screen shot 2017-08-01 at 2 07 05 pm

### CODE REVIEW

**Comment by jbalboni** [comment]
Might want to let @peggygannon decide if that's the right wording.

**Review by peggygannon — APPROVED** [review]

**Comment by peggygannon** [comment]
@cehsu @jbalboni Looks good.

**Review by jbalboni — APPROVED** [review]

**Comment by cvalarida** [comment]
I'll defer to @peggygannon, but "previously unreported" seems a bit confusing to me. I would assume it means "income not reported previously in this form," not "income I've previously not reported to the government," but we may get some confusion there.

Or it may be just me. :man_shrugging:

**Comment by peggygannon** [comment]
@cvalarida @cehsu Thanks for your feedback. I agree... there might be some confusion. So let's go with the below language:

Any income you didn't previously report in this form that you expect to receive in the next 12 months

Any income you didn't previously report in this form that your spouse expects to receive in the next 12 months

Any income you didn't previously report in this form that your dependent expects to receive in the next 12 months

**Comment by cehsu** [comment]
Thanks @cvalarida and @peggygannon, what about:
"Any new sources of income that you expect..."

**Comment by cehsu** [comment]
Thanks @peggygannon would "new income" be another way to simplify this?
screen shot 2017-08-01 at 11 14 39 am
screen shot 2017-08-01 at 11 14 59 am
screen shot 2017-08-01 at 11 15 19 am

**Comment by peggygannon** [comment]
@cehsu Thanks for checking back in. I think we should avoid using "new" as the SMEs were clear about wanting to say income "not already reported on the form". Let's go with the below copy for those pages: 

Any income you didn't already report in this form that you expect to receive in the next 12 months

Any income you didn't already report in this form that your spouse expects to receive in the next 12 months

Any income you didn't already report in this form that your dependent expects to receive in the next 12 months

**Comment by cehsu** [comment]
Thanks again for your guidance on this @peggygannon, changes made and screenshots updated above.

**Comment by peggygannon** [comment]
@cehsu Thank you. LGTM

**Pull request merged**
