### PR TITLE
Remove status improvement canceled flag

### PR DESCRIPTION
**Pull request by jenniemc**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

## Summary

This PR removed the feature toggle flag `va_online_scheduling_status_improvement_canceled`

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#89130

## Testing done

n/a

## Screenshots

n/a

## What areas of the site does it impact?

Feature toggle flag

## Acceptance criteria

- [ ] Remove `va_online_scheduling_status_improvement_canceled` from the application code.

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by JunTaoLuo — CHANGES_REQUESTED** [review]
I think you're missing a removal from `src/applications/mhv-secure-messaging/tests/e2e/fixtures/generalResponses/featureToggles.json`

**Comment by jenniemc** [comment]
> I think you're missing a removal from `src/applications/mhv-secure-messaging/tests/e2e/fixtures/generalResponses/featureToggles.json`

This file belongs to the MyHealthyVet application team. Reaching out to let them know of the feature flag removal.

Hi @KolbyVA, the Application team is removing the feature flag `va_online_scheduling_status_improvement_canceled` from our code. You can safely remove the same flag from your codebase at your leisure.

**Comment by JunTaoLuo** [comment]
Since we own the flag, maybe we should remove it for them? Especially since it's not being used anywhere in code.

**Review by JunTaoLuo — APPROVED** [review]
Switching review to approval to unblock PR. I originally wanted to remove it for mhv secure messaging since I was concerned not removing it might cause flipper to regenerate this flag. However, it looks like that other file is used in tests only so I'm less concerned. I still think we should remove it otherwise we'll forget about it and it'll zombie on but it's more aesthetics than functionality so I'm not as opinionated.

**Review by Andrew565 — APPROVED** [review]

**Comment by jenniemc** [comment]
Hi @JunTaoLuo , looks like the MHV team deleted the file `src/applications/mhv-secure-messaging/tests/e2e/fixtures/generalResponses/featureToggles.json` completely from their codebase. Would you proceed to remove the flag name `va_online_scheduling_status_improvement_canceled` from the flipper admin page in dev and staging? Thanks!

**Comment by JunTaoLuo** [comment]
Perfect I'll remove it in the non-prod envs right now and file a support issue for the prod env after I'm done.

**Pull request merged**
