### PR TITLE
Fixed scroll/focus logic on close of modal

### PR DESCRIPTION
**Pull request by cosu419**
## Summary

- Updated scroll/focus behavior onClose of Report Modal
- Set CSRF token from fetch representatives response headers
- Added method for formatting request object into snake case

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/77120
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75311

## Related issue(s)
New unit test written for method that formats reports

### CODE REVIEW

**Comment by Andrew565** [comment]
PR has failing required tests, opting not to review at this time. - Tier 2/FE COP

**Review by holdenhinkle — DISMISSED** [review]
LGTM

**Review by holdenhinkle — DISMISSED** [review]
LGTM!

**Review by holdenhinkle — APPROVED** [review]
LGTM

**Review by micahchiang — APPROVED** [review]

**Pull request merged**
