### PR TITLE
WIP/pension/Intent to file content

### PR DESCRIPTION
**Pull request by peggygannon**
SME request: 
Content updates to Pension/Apply page letting users know how to file an intent to file for pension claim and that starting an application is not considered an Intent to File.

### CODE REVIEW

**Comment by peggygannon** [comment]
@bethpotts Hi, Beth, I've updated the pension/apply page, based on SME request to add information about intent to file, and that starting an application is not an Intent to File.

**Review by bethpotts — APPROVED** [review]
Looks good, Peggy!

**Comment by peggygannon** [comment]
@bethpotts Here is the PR that shows the Pension and Burial pages before we took down the forms. In addition to having the green buttons reinstated, I updated the applicable pages with conditional content updates. Let me know if you have any questions! 

The pages that need a review are: 
-[ ] Pension top nav (green apply button has been reinstated)
-[ ] Pension Eligibility page (green Apply button and updated conditional content)
-[ ] Pension Apply (green Apply button and Intent to File paragraph)
-[ ] Pension FDC (updated links that go to online form and updated conditional content updates)
-[ ] Burial Allowances page (green Apply button and updated conditional content)

**Comment by bethpotts** [comment]
Looks great, @peggygannon!

**Comment by jbalboni** [comment]
I'm going to close this because it was merged in another PR.

**Pull request closed without merging**
