### PR TITLE
Switch to using stationNo

### PR DESCRIPTION
**Pull request by wullaski**
## Summary

- Switch to use stationNo as identifier for new travel logic

## Related issue(s)

- [department-of-veterans-affairs/va.gov-team#65628](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65628)

### CODE REVIEW

**Review by lee-delarm6 — APPROVED** [review]
Good to go

**Review by brianseek — CHANGES_REQUESTED** [review]
Looks like you need to update the tests

**Comment by lee-delarm6** [comment]
> Looks like you need to update the tests

I missed that, good catch

**Review by brianseek — APPROVED** [review]
test, update looks great!

**Pull request merged**
