### PR TITLE
Remove health services legacy field.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
Removes old helathservices graphql query that is no longer in use on system or system health services pages.

## Testing done
Visual and build

## Screenshots
image
image

## Acceptance criteria
`pittsburgh-health-care/health-services/` and `pittsburgh-health-care/` appear as in screenshots

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by mpelzsherman — CHANGES_REQUESTED** [review]
fieldFeaturedContentHealthser is still in use [here](https://github.com/department-of-veterans-affairs/vets-website/blob/3e19098df474187fc584eee5004a3a8947d80cb5/src/site/layouts/health_services_listing.drupal.liquid#L33).

**Comment by ethanteague** [comment]
> fieldFeaturedContentHealthser is still in use [here](https://github.com/department-of-veterans-affairs/vets-website/blob/3e19098df474187fc584eee5004a3a8947d80cb5/src/site/layouts/health_services_listing.drupal.liquid#L33).

Yep, @mpelzsherman - That comes from the health services listing query: `src/site/stages/build/drupal/graphql/healthServicesListingPage.graphql.js` 
image

What I'm removing was used for the system page (legacy).

**Review by mpelzsherman — APPROVED** [review]
OK, I reviewed this again and it looks like we can safely remove this.

**Review by brangi — APPROVED** [review]

**Review by billfienberg — APPROVED** [review]
Jenkins tests pass

**Pull request merged**
