### PR TITLE
Bumping Axe V

### PR DESCRIPTION
**Pull request by zacharymorel**
## Description
Axe bump needed for solution to a couple of 508-2's .
See comment chain here => https://github.com/department-of-veterans-affairs/va.gov-team/issues/18389#issuecomment-802919186

## Testing done
Reinstalled package and ran repo locally. 

## Acceptance criteria
- [x] axe-core package is bumped

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by timwright12 — APPROVED** [review]

**Review by 1Copenut — APPROVED** [review]
👍 LGTM. As long as no tests are breaking in the e2e runs, we are good to go.

**Comment by 1Copenut** [comment]
@zacharymorel Thank you for taking this through the pipeline. If you have a few minutes, would you mind running the following command on your local machine: `$ yarn test:accessibility` ?

This will open the Nightwatch tester and plow through all the static content pages using the bumped to 4.1.3 axe-core. I do not anticipate any issues, but forgot earlier the static checks are removed from feature branch builds, but are still in the daily deploy to master.

**Comment by zacharymorel** [comment]
Yes, I'll get on that right now @1Copenut !

**Comment by zacharymorel** [comment]
@1Copenut Interesting enough, after re install of new packages, I still run in to eslint flags after the minor bump. Any thoughts on this? 

I can, for now, just add a eslint inline disable to get pass.
Screen Shot 2021-03-22 at 12 08 31 PM

**Pull request merged**
