### PR TITLE
Upgrade MapBox SDK

### PR DESCRIPTION
**Pull request by brangi**
## Description
Issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/3585

## Testing done
Locally.

## Acceptance criteria
- [x] Run automated scans periodically
- [x] Run the axe-core plugin while developing new components. Many automated errors can be avoided or fixed during the development cycle.
- [x] Documentation and points of contact for any new backend dependencies
- [x] Links to important dashboards for investigating relevant issues

## Main Changes
 - Upgrade mapbox SDK to the new version and package dependency **@mapbox/mapbox-sdk (forwardGeocode, reverseGeocode)**

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by mmiddaugh** [comment]
@tlei123 FYI

**Comment by brangi** [comment]
^ I need to update the conditional that switches the API version to use the flag from  platform/utilities/environment isStaging instead

**Comment by brangi** [comment]
@department-of-veterans-affairs/frontend-review-group  can you provide some feedback?

**Comment by kelsonic** [comment]
It looks good to me, but it's a lot of code change and I'm not exactly sure what it's doing or what this PR's purpose is (the ticket had clear AC but no user story). In regards to the code, I'd love it if there were more comments above code blocks if that's possible 🙂Nice work @brangi!

**Comment by brangi** [comment]
@kelsonic ,  I updated the code with some comments highlighting the main changes.

**Comment by bkjohnson** [comment]
We won't approve this until someone from your team gives it a peer review + approval.  We don't peer review PRs for app-specific teams because we can't know the context of each PR that each team puts out.

Like Kelson, I am not really sure what is going on here or why (which is why we rely on the peer approval from a team member).  At first glance I see a dependency added to `package.json` yet the PR title mentions that mapbox is being _upgraded_.  This confused me, so I had to dig around and I found this on the mapbox [github page](https://github.com/mapbox/mapbox-sdk-js):

> As of 6/11/18, the codebase has been rewritten and a new npm package released. The `mapbox` package is deprecated in favor of the new @mapbox/mapbox-sdk package.

Having that in the PR description would have been helpful, but it also raises the question of why the `mapbox` dependency hasn't been removed from `package.json` if this PR is meant to upgrade to `mapbox-sdk`

**Comment by brangi** [comment]
@bkjohnson thanks for your comments. 

The PR is solely to upgrade mapbox sdk and yes it requires to add another package (dependency). 

However, the reason I left  the deprecated `mapbox` in the `package.json` is in order to test the changes on staging environment before using the new SDK in production. I know it would need some clarification so just recently added some comments to explain the why of using the two dependencies and when to be removed.

I hope it makes more sense.

```
import MapboxClient from 'mapbox';
import MapboxClient1 from '@mapbox/mapbox-sdk';
import MapboxClient2 from 'mapbox'; // TODO remove dependency after QA

import { mapboxToken } from '../utils/mapboxToken';
import environments from '../../../platform/utilities/environment';

/**
 New: @mapbox/mapbox-sdk is initialized with the accessToken key as an object
 The conditional is for using the SDK version according to the environment ( New SDK in staging temporarily for QA)
 TODO: remove this logic after new sdk tested in staging
export const mapboxClient = new MapboxClient(mapboxToken);
 MapboxClient1 : New SDK
 MapboxClient2 : Current SDK
*/
export const mapboxClient = environments.isStaging()
  ? new MapboxClient1({ accessToken: mapboxToken })
  : new MapboxClient2(mapboxToken);
```

**Review by kelsonic — APPROVED** [review]
LGTM 🎉

**Review by bkjohnson — APPROVED** [review]

**Pull request merged**
