### PR TITLE
[WIP] life insurance

### PR DESCRIPTION
**Pull request by rroueche**
From this issue: https://github.com/department-of-veterans-affairs/vets.gov-content/issues/231

### CODE REVIEW

**Comment by rroueche** [comment]
@bethpotts this is ready now for you to pour the content in!

**Comment by bethpotts** [comment]
@rroueche Thanks! @DanielleSoCompany Here you go for uploading content to content/wip/life-insurance

**Comment by bethpotts** [comment]
@rroueche There's an errant "Need help?" callout on this page--there's no info that goes under it, so we need to remove it: https://vetsgov-pr-5240.herokuapp.com/life-insurance/options-and-eligibility/

**Comment by tiffanybbrown-va** [comment]
Ok. Needed to do a comparison to `life-insurance/options-and-eligibility`.

Should this come up again, you can "dump" a variable or property by enclosing it in double curly braces: e.g. `{{ variablename }}`. In this case, adding {{ path }} somewhere in the include file would have revealed `life-insurance/options-and-eligibility`.

**Comment by tiffanybbrown-va** [comment]
I may have borked this PR @rroueche 😞 ... May need to open a new one. I can do that if you'd like.

**Comment by rroueche** [comment]
@tiffanybbrown-va just spot checked and it looks ok to me, aside from still wanting a bit more info to be pulling in under Need Help here: https://vetsgov-pr-5240.herokuapp.com/life-insurance/options-and-eligibility/

what seems to be borked -- is it something behind the scenes?

**Comment by tiffanybbrown-va** [comment]
The tests fail now. They didn't before.

**Comment by rroueche** [comment]
@tiffanybbrown-va it's probably failing bc of the branch name -- Jenkins automatically fails anything that has ```content/wip``` in the branch name (bc of a prior need). I need to work with @jkassemi to get that function adjusted/deactivated.

**Comment by bethpotts** [comment]
Top left nav update...
L2 order and text should be:
Life insurance overview
Options & eligibility
Disabled & terminally ill policyholders
Managing your policy

**Comment by melwoodard** [comment]
@bethpotts @mnorthuis @DanielleSoCompany @rroueche I updated nav per Beth's spec above and the link order on the life insurance L1 page.

**Comment by rroueche** [comment]
nice, @amybehrens @bethpotts could you approve this PR if all looks good?

**Review by bethpotts — APPROVED** [review]
Content is ready to go on my end!

**Comment by amybehrens** [comment]
Two things:

1. I'm concerned about not using person-first language... do we have something in the style guide about this?  

@bethpotts , can you brainstorm some other labels for the nav and page titles?
 - Claims for Disabled and Terminally Ill Policyholders
 - Disabled & Terminally Ill Policyholders

If this isn't something in our style guide, this is fine for now, but I'd like us to revisit in the maintenance/refresh phase. (If we do change, we'd need to run by the SMEs.) My apologies for not catching this earlier.

2. @melwoodard The grey boxes at the bottom of pages (https://vetsgov-pr-5240.herokuapp.com/life-insurance/disabled-and-terminally-ill/) need an extra return at the bottom, or padding added to the template. I can't upload screenshots from this laptop, but I'll slack you an image.

**Comment by bethpotts** [comment]
@amybehrens @rroueche This is a totally valid point for us to consider. And thank you for being our "pause point," Amy. We probably decided the nav too quickly on the spur of the moment yesterday! Here's my recommendation: we should reconsider the title of this page, and the resulting nav label, and we'll definitely need to run it by the SMEs. As for timing, I think we could launch with this, and revisit in July. Once in a while we have to deviate from our style of the user asking questions in first person, followed by our second person answer. This was one of those exceptions for a number of reasons, but I think we should work at it a bit more and see if there's any other option. I don't think we should to try to quickly change the title this morning and push it live without a SME look.

**Comment by melwoodard** [comment]
Padding fixes are merged into master!

**Comment by amybehrens** [comment]
@bethpotts just to clarify, by person-first language I mean "people with disabilities" vs. "disabled people" (i.e., not defining people by their disability, abilities, etc.). This is tricky with VA because they're not great about adopting this standard either, but it's general best practice among the disability community. And in this case it makes the title much longer. Anyway, I'm good to move forward, but can you make an issue so we don't forget to address this later? Thanks!

**Review by ghost — APPROVED** [review]

**Pull request merged**
