### PR TITLE
Coronavirus research breadcrumbs and review page for weight and height widget

### PR DESCRIPTION
**Pull request by stephenBarrs**
## Description
Update `registry.json` to include custom breadcrumbs
We are using custom widgets for `weight` and `height` inputs and thus have to customize the behavior on the review screen. This includes re-populating the input fields fro `height` when editing on the review screen. This was accomplished by modifying the initial state to be populated with appropriate feet and inches values if a value already existed in `props` as seen [here](https://github.com/department-of-veterans-affairs/vets-website/blob/e907f7cc05f0e501169006cc144df34bf064ce42/src/applications/coronavirus-research/widgets/HeightWidget.jsx#L4). 

Determining if the application was displaying the review page or allowing editing of the form elements is accomplished by: `formContext.onReviewPage && formContext.reviewMode` which is used to [determine what content is returned from the render() function](https://github.com/department-of-veterans-affairs/vets-website/blob/e907f7cc05f0e501169006cc144df34bf064ce42/src/applications/coronavirus-research/widgets/HeightWidget.jsx#L69). 

## Testing done
unit tests all pass and manual tests

## Screenshots
Review Screen display for Weight and Height 
image

Breadcrumbs display
image

## Acceptance criteria
- [ ] Weight displays in a readable format on the review screen
- [ ] height  displays in a readable format on the review screen
- [ ] Breadcrumbs display on all pages

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by artsymartha68** [comment]
cc @DanielleThierryUSDSVA to review capitalization of the breadcrumb header.

**Comment by artsymartha68** [comment]
I like the height/weight display view, cc @DanielleThierryUSDSVA again for official sign-off.

**Comment by DanielleThierryUSDSVA** [comment]
For capitalization:

- Breadcrumb: Health care > Coronavirus research sign-up
- For the steps: Could we use sentence casing there too? So "Volunteer information" and "Review application"

I like height and weight display too! I was just looking at AP style for measurement abbreviations, and they write out the full words (inches, feet, pounds). @artsymartha68 @stephenBarrs Thoughts on that for the limited space or other issues? I don't think we need to change this now so let me know your thoughts and I can also check in with our copy editors for added thoughts.

**Comment by stephenBarrs** [comment]
@DanielleThierryUSDSVA 
> * Breadcrumb: Health care > Coronavirus research sign-up

Yep - should we try to leave off the `Home` element?  it may not be possible as currently in review instance there are two `Home` elements displayed.  Looking into that as well. 

> I like height and weight display too! I was just looking at AP style for measurement abbreviations, and they write out the full words (inches, feet, pounds). @artsymartha68 @stephenBarrs Thoughts on that for the limited space or other issues? I don't think we need to change this now so let me know your thoughts and I can also check in with our copy editors for added thoughts.

I *think* there is room for full words.  I will implement and take screen shot on a smaller phone emulation screen and we can discuss.  

This PR has not been merged into `Staging` yet so now is the time to make these great changes!  Thanks for the feedback!

**Comment by DanielleThierryUSDSVA** [comment]
@stephenBarrs @artsymartha68 

Re: question about leaving "Home" off of the breadcrumb - Apologies, I didn't meant to imply we should leave that off. I just started with "Health care" in my comment because that's where the need for sentence casing changes started.

But this brings up another question. Our url is va.gov/coronavirus-research/volunteer. So this isn't living in the health care hub. So should we remove "Health care" from the breadcrumb? Thoughts?

**Comment by stephenBarrs** [comment]
@DanielleThierryUSDSVA @artsymartha68 

> But this brings up another question. Our url is va.gov/coronavirus-research/volunteer. So this isn't living in the health care hub. So should we remove "Health care" from the breadcrumb? Thoughts?

*should* this be in the health care hub?  I don't know :).   

Looking at the URL and the workflow to get to the form, would it make sense to build breadcrumbs like:

`Home` > `Coronavirus research` > `Sign-up`

Home - `staging.va.gov`
Coronavirus research - `https://staging.va.gov/coronavirus-research/`
Sign-up - form page at `https://staging.va.gov/coronavirus-research/volunteer/sign-up`, but would not be a link

**Comment by batemapf** [comment]
@mchelen-gov mind giving this an engineering review on behalf of `va-cto-health-products`?

**Comment by stephenBarrs** [comment]
This PR has been overtaken by https://github.com/department-of-veterans-affairs/vets-website/pull/14142.  I will close this PR as the new one was forked from this code base and contains all associated changes.

**Pull request closed without merging**
