### PR TITLE
Fac loc design revisions

### PR DESCRIPTION
**Pull request by rickleegit**
@ayaleloehr: Legend added. Can you take a look and merge if all good? Thanks!

### CODE REVIEW

**Comment by ayaleloehr** [comment]
@rickleegit Build errors are:

- ./_site/facility-locator/index.html
  *  image markers/m1_40.png does not have an alt attribute (line 340)
  *  image markers/m2_40.png does not have an alt attribute (line 346)
  *  image markers/m3_40.png does not have an alt attribute (line 352)
  *  image markers/m4_40.png does not have an alt attribute (line 358)
  *  image markers/m5_40.png does not have an alt attribute (line 364)
  *  image markers/m6_40.png does not have an alt attribute (line 370)
  *  image markers/m7_40.png does not have an alt attribute (line 376)
  *  image markers/m8_40.png does not have an alt attribute (line 382)
htmlproof 2.6.1 | Error:  HTML-Proofer found 8 failures!

Also, this is what those search boxes look like on mobile:  



Feels really stuck together to me. Is that something you think we should fix here or in a different PR?

**Comment by rickleegit** [comment]
I'll fix it here. Didn't even look at that. Thanks for mentioning.

**Comment by rickleegit** [comment]
@ayaleloehr Search bar spacing adjusted. alt tags added.

**Comment by ayaleloehr** [comment]
A few more errors now:
- ./_site/facility-locator/index.html
  *  Unexpected end tag : div (line 452)
  *  Unexpected end tag : li (line 413)
  *  Unexpected end tag : ul (line 414)
  *  image markers/m8_40.png does not have an alt attribute (line 406)
htmlproof 2.6.1 | Error:  HTML-Proofer found 4 failures!

**Comment by ayaleloehr** [comment]
Looks good to me

**Pull request merged**
