### PR TITLE
[526] Using primary action links instead of buttons for Intro page

### PR DESCRIPTION
**Pull request by jerekshoe**
## Description
Using primary action links instead of buttons for 526 Introduction page. Introduced some custom styling as well to retain the existing look and feel.

## Original issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/41773

## Screenshots
<details><summary>Before with green button</summary>

Screen Shot 2022-05-24 at 2 36 38 PM
</details>

<details><summary>After with primary action link</summary>

Screen Shot 2022-05-24 at 2 38 50 PM
</details>

<details><summary>After with primary action link (no additional styling)</summary>

Screen Shot 2022-05-24 at 2 40 23 PM
</details>

## Acceptance criteria
- [x] 526 Introduction page uses primary action links in place of action buttons

## Definition of done
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Review by adamwhitlock1 — APPROVED** [review]

**Comment by Mottie** [comment]
Oh, I thought we were going to show the action links as part of A/B testing?

**Comment by cohnjesse** [comment]
@Mottie Were we gonna run the A/B test on the NOD or the 526?

**Comment by Mottie** [comment]
We can do whatever. I didn't know what was being planned

**Comment by cohnjesse** [comment]
@Mottie I think the A/B test is gonna be on the NOD app but we might be able to apply the results to the 526

**Pull request merged**
