### PR TITLE
Mock out filtering for user testing

### PR DESCRIPTION
**Pull request by bshyong**
Mocks out the filtering function for user testing. When user selects a specific service type from the drop down, search result names and titles will reflect the selected service type

### CODE REVIEW

**Comment by bshyong** [comment]
@crwallace this PR makes it so that selecting a specific type of facility filters the results to make it less confusing for people who are testing the facility locator—if it's not necessary anymore feel free to close this PR

**Review by crwallace — APPROVED** [review]
LGTM!

**Comment by crwallace** [comment]
@bshyong -- I think this fail has something to do with edu-benefits not us really.

https://travis-ci.org/department-of-veterans-affairs/vets-website/jobs/165527315#L9571

cc: @akainic

**Comment by akainic** [comment]
@crwallace and @bshyong I've seen some builds fail due to edu-benefits and all that's needed is to restart the build. Not sure why this is happening, I will create a ticket to look into that, but looks like for now at least this is working.

**Comment by bshyong** [comment]
Thanks @akainic!

**Pull request merged**
