### PR TITLE
[Development] Update HLR schema & reference

### PR DESCRIPTION
**Pull request by Mottie**
## Description

Update Higher-Level Review (form 20-0996) references to the schema in the `vets-json-schema` repository.

Associated ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/7154

## Testing done

Local unit tests

## Screenshots

N/A

## Acceptance criteria
- [ ] The latest vets-json-schema is available

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by ndsprinkle — APPROVED** [review]

**Review by bkjohnson — COMMENTED** [review]
Can you make sure that there is an associated PR in `vets-api` to update the json schema to the matching version?

**Comment by Mottie** [comment]
@bkjohnson Already done - https://github.com/department-of-veterans-affairs/vets-json-schema/commit/8a1e91213e28610d0f682a67797e65fe862f3b65 is a PR I recently merged

**Comment by Mottie** [comment]
Oh oops... vets-api... I'll open one

**Comment by Mottie** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4355

**Comment by Mottie** [comment]
Is merging this PR blocked until the API is updated?

**Comment by bkjohnson** [comment]
Yes. Having the api and the frontend get out of sync regarding the json schema causes problems.

**Comment by Mottie** [comment]
API PR was just merged.

**Review by bkjohnson — APPROVED** [review]
:+1:

**Pull request merged**
