### PR TITLE
define reusable executors

### PR DESCRIPTION
**Pull request by mchelen-gov**
## Description
reference: https://circleci.com/docs/2.0/pipeline-variables/#pipeline-parameters-in-configuration
updated: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by U-DON** [comment]
I think the proper way to set up commonly used images is by [configuring executors](https://circleci.com/docs/2.0/executor-intro/).

**Comment by mchelen-gov** [comment]
> I think the proper way to set up commonly used images is by [configuring executors](https://circleci.com/docs/2.0/executor-intro/).

@U-DON I think the executor type is "docker" but I don't see any way to define the image at a global level? btw for some steps it uses `cypres/node` and then for others it uses `cypress/base` not sure why

**Comment by U-DON** [comment]
There's no `cypress/node` image, from what I can tell. Feel free to refer to how `vets-api` [set up their executor](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.circleci/config.yml#L20-L39).

**Comment by mchelen-gov** [comment]
> There's no `cypress/node` image, from what I can tell. Feel free to refer to how `vets-api` [set up their executor](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.circleci/config.yml#L20-L39).

@U-DON Oh whoops, I was totally mixing up cypress & circleci when reading the code.
looks like `vets-api` is using YAML anchors & aliases https://circleci.com/blog/circleci-hacks-reuse-yaml-in-your-circleci-config-with-yaml/
there is a newer way to define reusable executors in circleci now: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors
modified code to use this approach

**Review by U-DON — APPROVED** [review]

**Pull request merged**
