### PR TITLE
Updated login error messages

### PR DESCRIPTION
**Pull request by U-DON**
## Description
New login error messages.

## Testing done
Local testing.

## Acceptance criteria
- [x] Error messages for 001, 002, 003, 004, and general cases should be implemented as [mocked](https://adhoc.invisionapp.com/share/5TQPWHKDQPK#/screens/349076705_000_Sign_In_Errors).

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by U-DON** [comment]
All of the button click handlers and links still need to be filled in.

Code 002 is also still pending discussion.

**Comment by U-DON** [comment]
Filled in link URLs and click handlers. 002 handling will be separate work, and this can proceed without it.

**Review by narin — COMMENTED** [review]
LGTM, but Jenkins checks seem to be failing.

**Review by narin — APPROVED** [review]
Tests are passing now.  Approved.

**Pull request merged**
