### PR TITLE
Change labels urgent care to urgent needs and h4 instead of p tags

### PR DESCRIPTION
**Pull request by eselkin**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- Replace "Urgent care appointments" label with "Appointments for urgent needs"
- Replace "Routine care appointments" label with "Appointments for routine care"
- Update headings and content to establish the following headings (and styling as appropriate) as below (Currently the H4s listed below are just p tags)

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11709

## Testing done

- Labels representing new language appear
- Care sub-types under each appointment type in satisfaction reporting now appear as `h4` tags instead of `p` tags
- Go to http://localhost:3002/greater-los-angeles-health-care/locations/west-los-angeles-va-medical-center/
- Compare with https://www.va.gov/greater-los-angeles-health-care/locations/west-los-angeles-va-medical-center/
 
## Screenshots

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  | Screenshot 2023-08-15 at 8 24 59 AM   |    Screenshot 2023-08-14 at 5 16 26 PM   |
| Desktop |  Screenshot 2023-08-14 at 5 09 20 PM   |  Screenshot 2023-08-14 at 5 08 53 PM    |

## What areas of the site does it impact?

This impacts the patient satisfaction reporting areas of the medical centers.

## Acceptance criteria

- [x] Current behavior is discussed with Content team and SMEs - new label/content is defined (handled in issue)
- [x] Confirm language with VHA - DM - (Handleed in issue)
- [x] Labels are updated with approved language
- [x] Headings follow a logical order
- [ ] Styling is consistent with design system
- [ ] Accessibility check (checked with keyboard, axe, and screen reader on Mac)
- [ ] PM/PO review

### Quality Assurance & Testing

- [x] No tests altered.
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated (no related documentation found)
- [x] Screenshot of the developed feature is added

### Error Handling

- [x] Browser console contains no warnings or errors. (None related to this change or underlying feature)
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user (unrelated to logged in route)

## Requested Feedback

N/A

### CODE REVIEW

**Review by chriskim2311 — APPROVED** [review]
LGTM!

**Review by randimays — APPROVED** [review]

**Review by maxx1128 — APPROVED** [review]

**Comment by eselkin** [comment]
@thejordanwood can you take a look at the wrapping of the words "Specialty Care" now that we're using H4 instead of p tags to mark that text. Should we decrease the font size or weight to make it not wrap?

**Comment by eselkin** [comment]
After communication with @thejordanwood and @laflannery 
Add styling for h4 to make h4 look like normal weighted h5 text:
Screenshot 2023-08-16 at 9 08 34 AM

**Comment by eselkin** [comment]
@randimays re-requesting you review this, just because made some styling changes.

**Review by randimays — APPROVED** [review]
LGTM

**Pull request merged**
