### PR TITLE
VACMS 18386 - x empty divs, divs to p, span to p in Facility Locator results

### PR DESCRIPTION
**Pull request by eselkin**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

- Remove empty divs, replace divs surrounding phone numbers in FL with p, replace spans around address with p in Facility Locator(FL)
- Sitewide team (we own FL)

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18386

## Testing done

- Manual testing of all types of facilities.

## Screenshots

<details>
<summary>FL Result of CCP/Urgent Care (desktop)</summary>
Screenshot 2024-09-16 at 5 18 52 PM
</details>

<details>
<summary>FL Result of VA Health Type (Dekstop) with code shown for phone markup</summary>
Screenshot 2024-09-16 at 5 19 30 PM
</details>

<details>
<summary>FL Result CCP in mobile</summary>
Screenshot 2024-09-16 at 5 19 45 PM
</details>

<details>
<summary>FL Result VA Health Mobile</summary>
Screenshot 2024-09-16 at 5 19 55 PM
</details>

## What areas of the site does it impact?

Facility Locator results

## Acceptance criteria
- [x] No empty div's are appearing in search results
- [x] Content is wrapped using `<p>` tags instead of more generic tags
- [ ] Requires design review
- [ ] Requires accessibility review

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

In RI, check FL results on VA Health and other types.

### CODE REVIEW

**Comment by laflannery** [comment]
@eselkin This looks good. Only one request, Can you also change the wrapping `<div>` on the Get directions link to a `<p>`? Then you can also remove the margin class because the p tag has default spacing:
image

**Review by powellkerry — DISMISSED** [review]

**Comment by eselkin** [comment]
@laflannery Odd. I did. Not sure why it didn't get in my last push. Let me fix that.

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Review by randimays — APPROVED** [review]
LGTM

**Review by laflannery — APPROVED** [review]

**Comment by thejordanwood** [comment]
Looks like I was too slow, but this LGTM!

**Pull request merged**
