### PR TITLE
65477 update help section content

### PR DESCRIPTION
**Pull request by lee-delarm6**
## Summary

- Added new help section that is displayed only on travel pages
- Added cypress test for new help section

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/65477

## Testing done

- Included new cypress tests
- Compared new component to sketch designs

## Screenshots

Screenshot 2023-09-21 at 10 38 23 AM
Screenshot 2023-09-21 at 10 38 15 AM

## What areas of the site does it impact?

Help section along bottom for travel pages only

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] Linting warnings have been addressed
- [x] Screenshot of the developed feature is added

### CODE REVIEW

**Comment by benbrasso-agile6** [comment]
Missed a (TTY: 711) in there. Update the tel ahref on the 911. 

Can I check this in stg once it's through engineer review?

**Comment by lee-delarm6** [comment]
> Missed a (TTY: 711) in there. Update the tel ahref on the 911.
> 
> Can I check this in stg once it's through engineer review?

Sure, also, should we have a true link for 911? I feel like that might have accidental clicks and everyone knows that number

**Comment by benbrasso-agile6** [comment]
> > Missed a (TTY: 711) in there. Update the tel ahref on the 911.
> > Can I check this in stg once it's through engineer review?
> 
> Sure, also, should we have a true link for 911? I feel like that might have accidental clicks and everyone knows that number

@kellysmith1008 thoughts?

**Comment by benbrasso-agile6** [comment]
> @benbrasso-agile6 @lee-delarm6 911 should be a link, but I'm not sure I understand the "true" link question. Our design system states: "Hyperlink all phone numbers, including TTY numbers. It is not a requirement to link the “call” or “text” verb that precedes the number. We do however include “TTY” in the link and aria-label to make it clear that it’s specifically for TTY so that users who need the service see it and so those who do not do not unintentionally call a TTY number." https://design.va.gov/content-style-guide/dates-and-numbers

I can always keep an eye on it in GA if we're concerned.

**Review by wullaski — COMMENTED** [review]
We could add more tests, one for each page, to the footer.unit.spec.jsx file. Asserting that the needs help block shows up on those pages.

**Review by wullaski — CHANGES_REQUESTED** [review]
I suggest we change the name of the component to TravelHelpBlock for clarity.

**Review by wullaski — CHANGES_REQUESTED** [review]
Add the validateHelpSection to the travel-question.display.cypress.spec.js test

**Comment by lee-delarm6** [comment]
@wullaski Made those updates as requested, good catch!

@benbrasso-agile6 It's on staging right now (hopefully remains so if checking tomorrow!)

**Review by wullaski — APPROVED** [review]
LGTM! 🚢

**Pull request merged**
