### PR TITLE
Fix margin bugs on VA.gov homepage

### PR DESCRIPTION
**Pull request by jbalboni**
## Description

This fixes some margin bugs on the homepage and continues moving styles to a separate homepage file. I didn't completely move everything because I'm wary of making too many changes and breaking things.

## Testing done

Tested locally at different screen sizes and on Browserstack.

## Screenshots
Sorry for the length of these.

Mobile:
localhost_3001_ pixel 2 xl 7

Desktop:
localhost_3001_ 4

## Acceptance criteria
- [x] Looks correct on mobile
- [x] Looks correct on desktop

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by emilywaggoner — CHANGES_REQUESTED** [review]
Thanks @jbalboni! I see one minor issue in the screenshots: the `Health Care` and `Education` boxes have more padding on the bottom than the `Disability` and `Records` sections. Would you mind shortening Health Care and Education so that they match the other two? We are good to go after that.

Edited to clarify I'm referring to the mobile view specifically.

**Comment by ncksllvn** [comment]
@jbalboni Looking good! Much needed cleanup. 

Only thing I see is that it looks like the grid on the footer was affected a bit, and that there isn't enough for the Contact Us section to line up -

image

**Comment by jbalboni** [comment]
@emilywaggoner Good catch, I updated the screenshot.

@ncksllvn That's how it looks in staging currently. The fix doesn't look immediately obvious to me, so I will make a separate issue.

**Review by emilywaggoner — APPROVED** [review]

**Review by ncksllvn — APPROVED** [review]
LGTM! 👍 🔥

**Comment by ncksllvn** [comment]
Kind of a gotcha with our branch names, the prefix `va-gov/` has to be used instead of `va.gov/` to make the deploys work. That got me a couple times before I got used to it.

**Pull request merged**
