### PR TITLE
Reordered dropdowns on GIBCT landing page.

### PR DESCRIPTION
**Pull request by U-DON**
Resolves department-of-veterans-affairs/vets.gov-team#1591.

> screen shot 2017-03-20 at 7 49 43 pm

### CODE REVIEW

**Comment by U-DON** [comment]
@mikeusdsva: Double checking this is what you had in mind.

**Review by bshyong — APPROVED** [review]
LGTM pending verification from @mikeusdsva

**Comment by mikeusdsva** [comment]
Yes. This is what it looks like

**Comment by U-DON** [comment]
TIL branch names with '#' will have problems building. Closing and merging through a different branch.

**Pull request closed without merging**
