### PR TITLE
Content template updates (all live static content)

### PR DESCRIPTION
**Pull request by melwoodard**
Related: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2155

Updates all currently live static content with new templates and side navigation:

- Health care (excluding WIP content): https://vetsgov-pr-5618.herokuapp.com/healthcare/
- Disability: https://vetsgov-pr-5618.herokuapp.com/disability-benefits/
- Education: https://vetsgov-pr-5618.herokuapp.com/education/
- Employment: https://vetsgov-pr-5618.herokuapp.com/employment/
- Burials and Memorials: https://vetsgov-pr-5618.herokuapp.com/burials-and-memorials/

Content review should include the following:
- New short names (display_title) for use in breadcrumbs/side nav/previous+next page nav
- Modifications to link sections (previously blue cards + piano keys)
  - Removed links
  - Link sections that need headings for context
- Side nav for different
- Rehomed sidebar content in certain pages

I've written up notes and questions for review and proposed short names for the pages that need them. Updates are highlighted in yellow: https://docs.google.com/spreadsheets/d/1jY8bebVuNmS0Au2KGavtjQYbjQdqTX3TEyqn_X8lYaY/edit#gid=869619117

### CODE REVIEW

**Review by peggygannon — COMMENTED** [review]
LGTM

**Comment by peggygannon** [comment]
@mel @rroueche Content review for Live site updated templates and display titles is complete. 
Mel, I've sent you the updated spreadsheet with my content notes. I've highlighted in yellow any questions I have for you or followups (ie, adding shaded boxes around the majorlinks).

**Comment by melwoodard** [comment]
Thanks @peggygannon -- I reviewed all your notes and added some comments in the spreadsheet status column, highlighted in blue. I addressed the issues like missing prev/next navigation, majorlinks styling and added back majorlinks to a few pages where they were useful for user navigation.

**Comment by peggygannon** [comment]
@melwoodard  OK, thank  you. For the pages in which we need to add back in the majorlinks, do you need me to do that today? I don't see them added back in the Github files yet.

**Comment by melwoodard** [comment]
@peggygannon sorry, I just added them back on the Conditions page -- I think that's the only one I missed in my updates. So the pages with majorlinks added back are:

https://vetsgov-pr-5618.herokuapp.com/disability-benefits/conditions/
https://vetsgov-pr-5618.herokuapp.com/education/other-educational-assistance-programs/
https://vetsgov-pr-5618.herokuapp.com/employment/job-seekers/start/

**Comment by peggygannon** [comment]
@melwoodard  OK, thanks. I checked the links above and all looks good.

**Comment by melwoodard** [comment]
@leannammiller @iantopper can I get a quick look from an engineer to figure out why the build is breaking on this branch? I don't have jenkins configured so I can't look at the errors.

**Comment by iantopper** [comment]
@melwoodard dropped it in Rainbows Slack to see if we can run this down

**Comment by jbalboni** [comment]
Broken link according to the logs:

```
Error: Link is broken: href: "/disability-benefits/conditions/exposure-to-hazardous-materials/gulf-war-illness-from-service-in-Afghanistan/", text: "
                Gulf War Illness in Afghanistan

                If you served in Afghanistan, you may be at risk of certain illnesses linked to that region.
              ", in file: disability-benefits/conditions/index.html
```

**Comment by melwoodard** [comment]
@jbalboni still failing after I fixed the link :( any other clues?

**Comment by jbalboni** [comment]
@melwoodard Looks like the link is still broken (though differently?):

```
Error: Link is broken: href: "/disability-benefits/conditions/exposure-to-hazardous-materials/gulf-war-illness-from-service-in-Afghanistan/", text: "
                Gulf War Illness in Afghanistan

                If you served in Afghanistan, you may be at risk of certain illnesses linked to that region.
              ", in file: disability-benefits/conditions/exposure-to-hazardous-materials/index.html
```

**Comment by melwoodard** [comment]
Ah! There were two bad instances of this link and I only fixed one. That did it, thank you!

**Comment by U-DON** [comment]
Remaining failures are in Rx and SM tests that just need to be updated. Will address.

**Comment by melwoodard** [comment]
THANK YOU @U-DON and @jbalboni for all your help!

**Review by bethpotts — APPROVED** [review]
GTG

**Pull request merged**
