### PR TITLE
Replace SystemDownView React component with HTML

### PR DESCRIPTION
**Pull request by jamigibbs**
The `SystemDownView` React component has been deprecated. This PR will replace it with equivalent HTML (there is no corresponding web component).

Additionally, it updates the `button` element with a link because the behavior of this element is to navigate back to the home page. [Buttons do things, links go places](https://design.va.gov/components/button/#when-to-use-a-button).

### Before and After
Screenshot 2023-03-31 at 1 39 24 PM

## Summary

- Removed and replaced the remaining three instances of the `SystemDownView` react component.
- Updated any necessary tests

## Related issue(s)
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1640

## Testing done

- Locally on vets-website
- PR e2e and unit tests passing

## What areas of the site does it impact?
- `/records/get-veteran-id-cards/apply`
- `src/platform/user/authorization/components/RequiredLoginView.jsx`

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature
- [ ]  [Accessibility foundational testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### CODE REVIEW

**Comment by jamigibbs** [comment]
@department-of-veterans-affairs/patient-check-in We are seeing this test fail on a couple of unrelated PR. Is someone able to look at why that might be failing?

https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4578199721/jobs/8084927196?pr=23810

```
Running:  phone.appointment.path.cypress.spec.js                                         (8 of 38)


  Pre-Check In Experience 
    1) Happy Path yes to demographics
    ✓ Happy Path no to demographics


  1 passing (20s)
  1 failing

  1) Pre-Check In Experience 
       Happy Path yes to demographics:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-testid="appointment-type-label"]`, but never found it.
      at Introduction.validateAppointmentType (http://localhost:[300](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4578199721/jobs/8084927196?pr=23810#step:9:301)1/__cypress/tests?p=src/applications/check-in/pre-check-in/tests/e2e/phone-appointments/phone.appointment.path.cypress.spec.js:14876:10)
      at Context.eval (http://localhost:3001/__cypress/tests?p=src/applications/check-in/pre-check-in/tests/e2e/phone-appointments/phone.appointment.path.cypress.spec.js:15105:26)
```

**Comment by brianseek** [comment]
> @department-of-veterans-affairs/patient-check-in We are seeing this test fail on a couple of unrelated PR. Is someone able to look at why that might be failing?
> 
> https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4578199721/jobs/8084927196?pr=23810
> 
> ```
> Running:  phone.appointment.path.cypress.spec.js                                         (8 of 38)
> 
> 
>   Pre-Check In Experience 
>     1) Happy Path yes to demographics
>     ✓ Happy Path no to demographics
> 
> 
>   1 passing (20s)
>   1 failing
> 
>   1) Pre-Check In Experience 
>        Happy Path yes to demographics:
>      AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-testid="appointment-type-label"]`, but never found it.
>       at Introduction.validateAppointmentType (http://localhost:[300](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/4578199721/jobs/8084927196?pr=23810#step:9:301)1/__cypress/tests?p=src/applications/check-in/pre-check-in/tests/e2e/phone-appointments/phone.appointment.path.cypress.spec.js:14876:10)
>       at Context.eval (http://localhost:3001/__cypress/tests?p=src/applications/check-in/pre-check-in/tests/e2e/phone-appointments/phone.appointment.path.cypress.spec.js:15105:26)
> ```

I'll take a look. If you want to add a skip for now, that also works for us.

**Comment by brianseek** [comment]
@jamigibbs looks like @wullaski has a fix for it in an upcoming PR. So I would say to go ahead and skip it here, and we will get it fixed up with his PR.

**Review by brianseek — APPROVED** [review]
check-in skip reviewed ✅

**Review by brianseek — APPROVED** [review]

**Review by jhonny218 — APPROVED** [review]
Thank you!

**Review by Andrew565 — APPROVED** [review]
LGTM

**Pull request merged**
