### PR TITLE
Move form element components and common utils out of hca directory

### LINKED ISSUE #2767: Move shared components/files out of project directories
Such as form element and question components, validations, options for select, etc.

### PR DESCRIPTION
**Pull request by jbalboni**
Pretty much all the changes in here are moving files and updating paths. There was a src/js/components directory already, so I moved them in there. There's also a common folder at that level, not sure if that would make more sense as a location.

Closes #2767

### CODE REVIEW

**Comment by akainic** [comment]
Looks good! Wondering a couple of things:
1. Should we move the shared /components directory into common? To indicate that is shared across projects?
2. Should we also move the /questions directory (contains components like `Address`, `SocialSecurityNumber`, etc.) into the shared /components directory? These seem generic enough that they might also be shared across projects.

**Comment by jbalboni** [comment]
@akainic I think both of those make sense. I'll update this pr.

**Comment by jbalboni** [comment]
@akainic Updated. I also moved the application schema into the hca directory, since that was common code.

**Comment by akainic** [comment]
LGTM! Once tests pass feel free to merge.

**Pull request merged**
