### PR TITLE
Personalization: add Content-Type header to API request

### PR DESCRIPTION
**Pull request by ncksllvn**
- Change API routes for email, telephones to POST
- Change API route for address to PUT
- On beta enrollment page, disables the enroll button while the user profile is loading

Resolves department-of-veterans-affairs/vets.gov-team/issues/10117

### CODE REVIEW

**Comment by ncksllvn** [comment]
Still seeing a `404` when I do send an update request

**Comment by ncksllvn** [comment]
@hpjaj Here's the request info. Any ideas from looking at this?

```
Request URL: http://localhost:3000/v0/profile/email
Request Method: PUT
Payload: {email: "test2@test1.net", effectiveAt: "2012-04-03T04:00:00.000+0000"}
Status Code: 404 Not Found
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Authorization: Token token=Pt47tvDMggxPuPhq6nKsfBxrWhRz1griore2tnx_
Connection: keep-alive
Content-Length: 72
Content-Type: application/json
Host: localhost:3000
Origin: http://localhost:3001
Referer: http://localhost:3001/profile-beta/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
X-Key-Inflection: camel
```

**Comment by hpjaj** [comment]
@ncksllvn - Hey, re:

https://github.com/department-of-veterans-affairs/vets-website/blob/9da7648c73afcb5db4c55148b4298a99045806c2/src/js/personalization/va-profile-beta/actions/index.js#L49

so for the endpoints, just the `mailing_address` endpoint is a `PUT`.  The other ones are `POST`.  Perhaps that could be it?

**Comment by ncksllvn** [comment]
@hpjaj PTAL. The FE and API are definitely linked up now so I think we can merge this PR, but there is a 500 error when doing an address update

**Review by bshyong — APPROVED** [review]
LGTM

**Pull request merged**
