### PR TITLE
New main link style for content templates.

### PR DESCRIPTION
**Pull request by ghost**
Closes department-of-veterans-affairs/vets.gov-team#1984

- Added m-nav-channel partial to account for new navigation links.
- Added level2-index and nav-link-list template partials.
- Updated disability-benefits/index.md to use new major links YAML structure.

### CODE REVIEW

**Comment by tiffanybbrown-va** [comment]
Added a new template so that this can be rolled out incrementally. It will require some content updates.

**Comment by melwoodard** [comment]
@tiffanybbrown-va this is great! I'll need to figure out with @rroueche how we should do this iteratively so that the content team work on converting when their time allows.

To echo my comment in #1985, I think the hover state for the links should be just the underline on the header, without the grey background.

**Comment by tiffanybbrown-va** [comment]
@rroueche Just an heads up: I don't think that `one-year.md` should actually use this template. But it's a good way to see now the Related Links should look.

**Review by melwoodard — APPROVED** [review]
I'm good with this, as long as the two disability pages are reverted back before merging, to allow the content team to come in later and address all these pages in one go.

@rroueche @jcmeloni-usds look good to you?

**Comment by tiffanybbrown-va** [comment]
Blocks department-of-veterans-affairs/vets.gov-team#2152

**Comment by rroueche** [comment]
ok @tiffanybbrown-va so to confirm, in order for these new styles to appear, the content team needs to:

1. update the page template in the YAML to `level2-index`
2. add the following the YAML for the gray-box related links:
```relatedlinks:
  - heading:
    links:  ```
3. add the following to the YAML for the big blue major links:
```majorlinks:
  - heading: Apply for Benefits
    links:```

@amybehrens and @suzchap cc'ing you in case you want to take a peek. Here are the new changes for majorlinks:
https://vetsgov-pr-5314.herokuapp.com/disability-benefits/
and related links:
https://vetsgov-pr-5314.herokuapp.com//disability-benefits/apply/one-year/
we have a new template that can be used to display these changes, so we can control when they go live.

I'm approving bc I think it looks great, but @tiffanybbrown-va please do revert the 2 disability pages back beforehand (once Amy and Suzanne have had a look)

**Review by rroueche — APPROVED** [review]

**Comment by rroueche** [comment]
also @phiden in case you need to document these updated styles in your pattern library

**Comment by suzchap** [comment]
LGTM!

**Comment by tiffanybbrown-va** [comment]
@rroueche Yes.

**Comment by tiffanybbrown-va** [comment]
I thought I knew how to `git rebase`, but Git and GitHub disagree.

**Comment by tiffanybbrown-va** [comment]
@melwoodard @rroueche @jcmeloni-usds Do you want to take one last look at things before I merge? I rolled back the changes to one-year.md and the other Markdown file.

**Comment by jcmeloni-usds** [comment]
Looks ok to me....

**Comment by melwoodard** [comment]
LGTM!

**Pull request merged**
