### PR TITLE
Update employers.md

### PR DESCRIPTION
**Pull request by mollyblake**
add in text about VECI

### CODE REVIEW

**Comment by bethpotts** [comment]
Emily, would love your help figuring out why the checks failed. Thanks!

**Comment by emilyville** [comment]
It looks like you might have created this off of an outdated version, I can fix this one, but if you update your local v2 branch you shouldn't have this issue. Next time you make a new pr, if you ping me I can help.

**Comment by emilyville** [comment]
@mollyblake you also have more not-real links in here

Vets.gov/voc-rehab.link 
Vets.gov/employerfacingOJTpage
vets.gov/CWTPage

I'm going to make a new PR and replace these three with the dummy link.

**Comment by emilyville** [comment]
closing

**Pull request closed without merging**
