### PR TITLE
Removes create/update MHV accounts from CTA

### LINKED ISSUE #52477: [FE] Remove MHV Accounts on vets-website
## Description
Removes all show/create/update functionality for My HealtheVet on vets-website that pertain to the `mhv_accounts` URL.

## Tasks
- [ ] Remove `mhv/actions` that call the endpoint
- [ ] Update the `static-pages/cta-widget` to remove portions of the MHV calls

### PR DESCRIPTION
**Pull request by asg5704**
## Summary

- *(Summarize the changes that have been made to the platform)*
This removes the ability to `create` and `update` MHV accounts on VA.gov

- *(What is the solution, why is this the solution)*
The solution is to remove the `createMHVAccount`, `createAndUpgradeMHVAccount`, and `upgradeMHVAccount` from the `actions/mhv.js` file primarily and remove anywhere where the actions + reducers + unit tests call it.

- *(Which team do you work for, does your team own the maintenance of this component?)*
Identity.  No

- *(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)*
No flipper is involved.

## Related issue(s)
- *Link to ticket created in va.gov-team repo*
Closes department-of-veterans-affairs/va.gov-team#52477
Waiting on https://github.com/department-of-veterans-affairs/vets-website/pull/23442

- *Link to epic if not included in ticket*
department-of-veterans-affairs/va.gov-team#32749

## Testing done

- *Describe what the old behavior was prior to the change*
Old behavior is to create and/or upgrade MHV accounts.  That functionality will be removed from vets-api which requires the necessary changes on vets-website

- *Describe the steps required to verify your changes are working as expected*
Unit tests and E2E tests continue to work as expected.

- *Describe the tests completed and the results*
Completed & passing

## Screenshots
n/a

## What areas of the site does it impact?
This should only impact VA.gov users who log in with a MHV account with no state.

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

## Requested Feedback
Ensure MHV accounts are neither created nor upgraded on the FE

### CODE REVIEW

**Comment by asg5704** [comment]
Can I get a review @department-of-veterans-affairs/vsa-public-websites-frontend @department-of-veterans-affairs/va-platform-cop-frontend

**Comment by asg5704** [comment]
Can I get a review @department-of-veterans-affairs/vsa-public-websites-frontend @department-of-veterans-affairs/va-platform-cop-frontend

**Comment by asg5704** [comment]
Can I get a review https://github.com/orgs/department-of-veterans-affairs/teams/vsa-public-websites-frontend https://github.com/orgs/department-of-veterans-affairs/teams/va-platform-cop-frontend

**Comment by asg5704** [comment]
Can I get a review @department-of-veterans-affairs/vsa-public-websites-frontend @department-of-veterans-affairs/va-platform-cop-frontend

**Review by jtmst — APPROVED** [review]

**Comment by asg5704** [comment]
@department-of-veterans-affairs/va-platform-cop-frontend Can I get a review on this please?

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Pull request merged**
