### PR TITLE
Fix travel pay claims spinner loading forever

### PR DESCRIPTION
**Pull request by athifw**
Before this change, if `vets-api` returns an error while fetching error claims, the loading spinner spins forever. Now, the error is properly handled and displays the proper message.

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/87542

## Testing done

- Reproduced bug locally, fixed bug.
- Reproduced bug in tests as well

## Screenshots

Screenshot 2024-07-05 at 2 36 30 PM

### CODE REVIEW

**Comment by kjduensing** [comment]
2 things:
1. Reminder not to merge this until after the 9th
2. I'm thinking we should give the error message a little more special treatment. Make it more prominent, add advice, etc. Something to consider for another ticket.

**Review by hinzed1127 — APPROVED** [review]
Ditto to Kevin's thoughts, but this fixes the immediate issue. Thanks for the fix!

**Review by IGallupSoCo — COMMENTED** [review]
LGTM

**Comment by athifw** [comment]
> LGTM

@IGallupSoCo - can you re-approve? It's not letting me merge

**Review by IGallupSoCo — APPROVED** [review]
LGTM

**Pull request merged**
