### PR TITLE
incorporating hardening changes

### PR DESCRIPTION
**Pull request by DanielleSoCompany**

### CODE REVIEW

**Comment by bethpotts** [comment]
@DanielleSoCompany Can you make changes to the green "Select Correct Form" button? Here's my suggestion there (I think the current button is pretty misleading as far as what comes next): We add text under "How do I apply online?" (feel free to adjust this text):

How do I apply online?
Just answer a few questions so we can point you to the education benefits form that's right for you.
[Get Started Toward Your Form] 
OR
[Answer a Few Questions]

--or something like that! This button is tricky.

Other than trying this new set up for the green button, it looks great!

**Comment by DanielleSoCompany** [comment]
@bethpotts @ncksllvn @robertfairhead It looks like we would need to go into the "education wizard" to make these additional changes. I just see the h3 tag that I changed and then code for the education wizard. Nick and Bob, is that something you could help us get into to edit? Thank you!

**Comment by robertfairhead** [comment]
Ok so instead of:

screen shot 2017-12-21 at 11 52 16 am

You want (essentially just a quick rough mock):

screen shot 2017-12-21 at 11 52 16 am


If so, i can do those changes for you

**Comment by robertfairhead** [comment]
Ok, https://vetsgov-pr-6981.herokuapp.com/education/apply/ is updated per above. let me know if you need other tweaks

**Comment by DanielleSoCompany** [comment]
Thank you so much, @robertfairhead! Just confirmed with Beth that we'd like to tweak language just a little. 
Intro to read:
Just answer a few questions, and we'll help you get started with the education benefits form that's right for you.
Button to read: Find Your Education Benefits Form

**Comment by robertfairhead** [comment]
Ok updated

**Comment by DanielleSoCompany** [comment]
Thank you @robertfairhead!

**Comment by jkassemi** [comment]
Seeing these changes as part of https://github.com/department-of-veterans-affairs/vets-website/pull/7812 in master. Please reopen if necessary.

**Pull request closed without merging**
