### PR TITLE
Bug fix 781 conclusion

### PR DESCRIPTION
**Pull request by aaronjlech**
## Description
Update order of 781 and 781a conclusion pages, and logic to allow pages to show up after form upload pages as well. 

## Testing done
- [x] tested locally

## Screenshots
image

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by rtluu** [comment]
thanks for the heads up @aaronjlech. Is there an issue you can connect this PR to that may be able to provide some context into, it's a bit unclear what problem this is meant to solve.

It's straightforward what the code changes are doing, but we're curious why it's needed. Thanks!

**Review by cvalarida — COMMENTED** [review]
Looks good, I think, but can we get some screenshots demonstrating the fix? Specifically for the difference between the 781 and 781a and how the title changes as it should.

**Comment by aaronjlech** [comment]
@cvalarida So this is mainly a workflow change and like 4 word difference from the content updated...

The titles `PTSD: $PTSDCLASSIFICATION` are dynamic on all 781/781a pages based off of the ptsd type selection page...
image

The title comes from this page (entry into 781/781a based off ptsd selection)
image

**Comment by cvalarida** [comment]
Ahh, okay, so the original screenshot demonstrates that the 781a gets the proper title if both forms are entered?

**Review by cvalarida — APPROVED** [review]
Heh, @markgreenburg just pinged me and was like, "I _swear_ I have to click the continue button twice on this page." Glad to know what the story is!

:shipit:

**Comment by aaronjlech** [comment]
@cvalarida Yeah both pages were next to each other before(which they are not supposed to be), and them having the same `page: { title: "Disability Details" ... }` was causing some re render weirdness...

**Comment by aaronjlech** [comment]
@cvalarida So They wanted to update the titles to be sentence case, and remove some of the bloat. Let me know if this is ok to add within this PR. If not I'll roll back the commit and create a new PR

**PTSD type Selection Page**
image

**New Updated double title for 781**
image

**New Updated double title for 781a**
image

**Pull request merged**
