### PR TITLE
Update register.md

### PR DESCRIPTION
**Pull request by lanaduffy**
Changed piano key link to vendor information link

### CODE REVIEW

**Comment by ss0ss** [comment]
@awong-dev @emilyville - two checks failed. What's our remediation so this doesn't happen in the future?

**Comment by awong-dev** [comment]
Hi @ss0ss, 39 errors were found on each of the two "checks"

Please click through the "Details" link when you see a failure. That is where the information is and learning how to decode that quickly will be a useful skill.

For your team, look for the build failures after the `bundle exec htmlproof` line.  Errors are usually rendered in red. In this specific example, lines 334 to 385 have the errors.

The problem is same as yesterday. There were existing errors on the `jobs-employment-v2` branch from previous changes. Until those are fixed, things will look red.

That being said, @emilyville just fixed them in #1392. If you rerun the tests, hopefully they should all be green now.

**Comment by awong-dev** [comment]
(You rerun the test by going to the Details link and then clicking on the circle button near the upper right of the status page. I restarted one check for you, but left the other red so you have an example for what I wrote in my last comment.)

screen shot 2016-03-12 at 12 30 42 am

**Comment by ss0ss** [comment]
Got it...but not seeing rebuild in any of the. Probably painfully obvious,
but what am I missing here?

[image: Inline image 1]

### shaun.so ###

**Comment by awong-dev** [comment]
Hmm... for some reason your screenshot didn't come through. Can you send it again?

**Comment by ss0ss** [comment]
@awong-dev - So, I was able to rerun the test (I think it's where/how I logged in that prevented me from rebuilding, but it was fine). But the rebuild failed.

**Comment by awong-dev** [comment]
hmmm...this is an interesting scenario.  I *think* what is happening is the `/push` check isn't actually noticing the updates to `jobs-employment-v2`. I need to consult some of the other engs to see what's going on.... will get back to you.

**Comment by ss0ss** [comment]
Yeah - some of the more recent PR's aren't also passing checks. I've been going through and rerunning the tests, and they're still failing.

**Comment by awong-dev** [comment]
@ss0ss For now, to unblock you...if the `/pr` check passes, I think you should feel free to merge.  This is a systemic mistake on our side which we haven't hit because our "merge" flow is different from your guys's.

Specifically, what's occurring is when you create a PR, you create a new branch like `lanaduffy-patch-1`.  This takes a snapshot of `jobs-employment-v2`. I'm assuming this is done via the github UI whereas most of us do this via the commandline.

Where we diverge in process is as a developer, we would usually continually merge changes from `jobs-employment-v2` back into `lanaduffy-patch-1` which means for us, the `/pr` check and the `/push` check are roughly equivalent. That would be the "normal" course of action to green-up the tests.

Unfortunately, I haven't been able to find a way to merge `jobs-employment-v2` back into `lanaduffy-patch-1` without using the commandline. This means, unless you close this PR/branch and recreate it, `lanaduffy-patch-1` is stuck at an old snapshot of `jobs-employment-v2` and will always error on the `/push` check.

The `/pr` check actually does the merge for you so it went green when we fixed `jobs-employment-v2`.  I think the right course of action is to disable the `/push` checks since they seem redundant, but I need to consult with some people before doing it....

For now though, if `/pr` is green, I say go ahead and push.  Also, if you never manage to let the feature branch (eg, `jobs-employment-v2`) go red, you won't end up in this situation again.

**Comment by ss0ss** [comment]
Thanks @awong-dev and tracking. I will merge the one where /pr check has passed. Of note, it seems that today's new PR's are passing their checks. But there are eight PR's where both checks have failed. They have been assigned to @emilyville.

Also noted about never letting the features branch going red.

**Pull request merged**
