### PR TITLE
VACMS-15731: Crisis modal update for TTY Information

### PR DESCRIPTION
**Pull request by chriskim2311**
## Summary

This PR updates the TTY information and matches the current styles for the other links in the crisis modal. 

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15731

## Testing done
Verified the updated text and call link is now 711 in the modal. Also changed the styles to match the other links in the modal.

## Screenshots
VA_gov___Veterans_Affairs

## What areas of the site does it impact?

Homepage and header

## Acceptance criteria
- [ ] CAIA signoff in Review instance prior to merge
- [ ] A11y review pre-merge
- [ ] Content is updated in the VCL on VA.gov to change "Call TTY if you have hearing loss 800-799-4889" to "[For TTY, call 711 then 988]" as one link, with 711 as the `tel:` attribute
  - [ ] in desktop header
  - [ ] in the mobile header
  - [ ] in the injected header

### CODE REVIEW

**Review by ataker — APPROVED** [review]

**Review by randimays — APPROVED** [review]
LGTM! Nice work.

**Comment by chriskim2311** [comment]
Injected header screenshot
Veterans_Health_Administration_and_Randi_-_Kind_Systems_-_1_new_item_-_Slack

**Comment by chriskim2311** [comment]
Latest css changes
Veterans_Health_Administration

**Comment by chriskim2311** [comment]
@thejordanwood Before I merge this can you take a quick look to give the okay to merge. To match the styles in the injected header modal, we will need to make changes in a separate repo with DS team approval. But this is the closest I could get, let me know thanks!

**Comment by thejordanwood** [comment]
@chriskim2311 This looks good to me!

**Pull request merged**
