### PR TITLE
Add mhv route guard to SM

### PR DESCRIPTION
**Pull request by jzucadi**
The purpose of this PR is to implement a route guard for the tool pages under the /my-health/ umbrella. The route guard checks for the presence of mhvAccountState having a value of ‘OK’ or ‘MULTIPLE’ to indicate whether a user has an MHV account. When a user does not have an MHV account, the property mhvAccountState will have a value of ‘NONE’. When a user has an MHV account, they are permitted to access the various tools under /my-health/. When a user does not have an MHV account, the route guard will redirect the user to the /my-health/ landing page where an alert notification will be shown explaining that they do not have an MHV account and need to register. This route guard will prevent the need to have this alert notification on each of the /my-health/ too pages. 

When a user does not have an MHV account, they are redirected to the /my-health/ landing page and will see the following:

Screenshot 2024-04-24 at 1 37 20 PM

Ticket:
https://app.zenhub.com/workspaces/mhv-on-vagov-landing-page-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/77237

## Testing done

To test this, mock user data must be used and toggled between values of 'NONE' = no mhv account and 'OK' or 'MULTIPLE' = has an mhv Account.

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Review by pjhill — APPROVED** [review]

**Review by alex-morgun-1 — COMMENTED** [review]
Secure Messaging already [handles](https://github.com/department-of-veterans-affairs/vets-website/blob/6c6023bcef9d262122855cf5b822c557cbcd9e87/src/applications/mhv-secure-messaging/containers/App.jsx#L146) guarding unauthorized users from accessing the tool by means of validating presence of `messaging` in user services that is returned by `/v0/user`. At the same time, `messaging` service is derived by [a policy](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/policies/mhv_messaging_policy.rb) that attempts to establish a session with MHV SM API. The `session` endpoint logic contains all SM eligibility requirements. 

Although our current redirect for ineligible users is different then what is provisioned in this PR, the question here is if we need another route guard here? Or perhaps we need to settle on one or a combination of both? 

I like the proposed solution, I just want to ensure one or the other is not redundant.

**Review by vbahinwillit — APPROVED** [review]

**Comment by jzucadi** [comment]
> Secure Messaging already [handles](https://github.com/department-of-veterans-affairs/vets-website/blob/6c6023bcef9d262122855cf5b822c557cbcd9e87/src/applications/mhv-secure-messaging/containers/App.jsx#L146) guarding unauthorized users from accessing the tool by means of validating presence of `messaging` in user services that is returned by `/v0/user`. At the same time, `messaging` service is derived by [a policy](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/policies/mhv_messaging_policy.rb) that attempts to establish a session with MHV SM API. The `session` endpoint logic contains all SM eligibility requirements.
> 
> Although our current redirect for ineligible users is different then what is provisioned in this PR, the question here is if we need another route guard here? Or perhaps we need to settle on one or a combination of both?
> 
> I like the proposed solution, I just want to ensure one or the other is not redundant.

I think it would be OK to have this route guard in parallel with the existing policy you described. This PR would just ensure if the user doesn't have an MHV account then they don't get to this page. Then if they do they have an MHV account, the existing check of validating the presence of 'messaging' in user services would be enforced. If they don't have an MHV account, it would make sense that they wouldn't even have any secure messaging services, but if they do have an MHV they still may or may not have any secure messaging services. Does that sound correct?

**Comment by jzucadi** [comment]
Based on the upcoming Oracle migration, there will be a  percentage of users that don't rely on data in the vets-api for validation. This means that they will not have an MHV which the route guard relies upon. Closing the PR based on this information

**Comment by dcloud** [comment]
We've come up with a different set of suggested changes in https://github.com/department-of-veterans-affairs/va.gov-team/issues/86422 that doesn't involve using the route guard technique.

@oleksii-morgun I'm going to reach out to you and your team about https://github.com/department-of-veterans-affairs/va.gov-team/issues/86422

**Comment by dcloud** [comment]
Meant to close this PR with my prior comment

**Pull request closed without merging**
