### PR TITLE
Removes lint pre-commit hook

### PR DESCRIPTION
**Pull request by crwallace**
I wanted to remove this as a pre-commit hook because we are still running lint on the CI and I have a concern that you can hop around this if you wanted to.

### CODE REVIEW

**Comment by webinista** [comment]
You can hop around it, but lint running as part of CI will still catch the errors. This is an additional pre-build step that saves the overhead of remembering to run `npm run lint`.

There are other ways to solve this problem, but IIRC, the choice to use a commit hook was to prevent slow local builds while eslint ran as part of the webpack build process.

**Comment by alexose** [comment]
+1 to @webinista.  The ideal thing would be for everyone to lint inside of their text editor, but that's pretty difficult to set up across the team.

Also I'd recommend you `git revert 68be0d7` if you want to remove prelinting from the repo.

**Comment by jkassemi** [comment]
I believe this was triggered on my comment (https://github.com/department-of-veterans-affairs/vets.gov-team/pull/252#discussion_r77261977) that this occurs in two places.

It seems like it's a useful pre-commit hook and it'll prevent commits from actually going up without checks, so this is probably best to hold off on?

**Comment by crwallace** [comment]
Do we not think that we should maybe lint on watch rather than this pre-commit hook?

**Comment by alexose** [comment]
Watch would be better, especially when we're building incrementally.  I actually implemented linting via webpack in a different PR (#2792), but I decided to go this direction.

Since Webpack only looks at build files, it's not aware of config/test files that we should also be linting.  I spent an hour or so looking at how to piece that together, but failed to come up with anything reasonable..

**Comment by crwallace** [comment]
I am closing this in favor of trying to add this into the webpack watch.

**Comment by webinista** [comment]
I am really 👎 with regard to running lint on watch. I concede that I may be a workflow unicorn here. But I think running lint as a commit hook is the right decision.

- It lets us output data to the console while we're working on a feature, but prevents us from committing code with errors or issues.
- A developer can make a partial commit* and continue working by circumventing the commit hook.

Running on watch doesn't let us do either of those things.

(I typically make smaller several commits while I work, then rebase them into a single commit before pushing to a branch.)

**Comment by alexose** [comment]
I've grown to like it too... It's especially nice when you want to throw in a console.log just to test something.

**Pull request closed without merging**
