### PR TITLE
Correct 508 screenreader defect on Caregiver Sign as Representive field

### PR DESCRIPTION
**Pull request by longmd**
## Description
A 508-defect-2 [SCREENREADER] issue within the Sign as a Representative section of the Caregiver application was discovered where the string "On behalf of [Veteran name]" was being skipped by most screen readers. It was discovered that when switching from the React text input component to the text input web component that the `aria-describedby` attribute was removed as unnecessary by the Design System Team. 

After consultation with the DST, they have created a workaround attribute and made it available for this component. This PR updates the attributes to successfully pass the aria-describedby message to the web component.

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#24502

## Testing done
- [x] Voiceover on Mac
- [x] Unit tests

## Acceptance criteria

- [ ]  Screenreaders can successfully read the `aria-describedby` message in the context of the text input

### CODE REVIEW

**Comment by longmd** [comment]
@jamigibbs , I'm curious if you have any advice on my failing e2e test. I'm getting an accessibility violation with the way the React Binding is rendering the web component. It seems to be rendering with both an `aria-describedby-message` attribute, AND a `ariadescribedbymessage` attribute.

Is there something we need to do differently with that react binding component to correct that rendering?

**Review by Mottie — APPROVED** [review]

**Comment by jamigibbs** [comment]
@longmd I think it's failing because `aria-describedby-message` (the name of the new prop) is not a valid ARIA attribute name which is something our accessibility checks did not flag unfortunately. If it was named `describedby-message-aria` (or anything without aria at the front), I'd wager this would pass. I will need to test this locally though and get back to you. I'm suspecting that we will need to rename this prop.

**Comment by jamigibbs** [comment]
@longmd I just merged in the latest release of the component library to `main` so that updated prop name should be available now `message-aria-describedby`. Apologies for the extra work on this one.

**Comment by longmd** [comment]
@jamigibbs , thanks for all your work and testing on this! Really glad we were able to come up with a great solution.

**Pull request merged**
