### PR TITLE
Add Custom ES Lint Rule to Flag Deprecated Cypress Viewport Method

### PR DESCRIPTION
**Pull request by rjohnson2011**
## Description
Resolves https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/16980

Adds a custom ES Lint rule that looks for `cy.viewport()` and triggers an ES Lint warning.

## Testing done
Went through instances of `cy.viewport` throughout the app and noticed they were flagged with the ES Lint warning.

## Screenshots
image

## Acceptance criteria
- [x] Created a mechanism to enforcing use of platform recommended viewport variables in Cypress specs
- [x] Created a mechanism to measure the ongoing use of viewport variables in Cypress specs

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by jhonny218 — APPROVED** [review]
LGTM

**Comment by ddzz** [comment]
@rjohnson2011 will this rule cause failures on CI, or will it only throw a warning?

**Comment by empireofryan** [comment]
> @rjohnson2011 will this rule cause failures on CI, or will it only throw a warning?

The last commit was to throw a warning rather than an error so CI still passes.

**Comment by pjhill** [comment]
> > @rjohnson2011 will this rule cause failures on CI, or will it only throw a warning?
> 
> The last commit was to throw a warning rather than an error so CI still passes.

Warning seems like the right approach for now. I think we want to gently shift teams toward this change.

**Comment by rjohnson2011** [comment]
> > > @rjohnson2011 will this rule cause failures on CI, or will it only throw a warning?
> > 
> > 
> > The last commit was to throw a warning rather than an error so CI still passes.
> 
> Warning seems like the right approach for now. I think we want to gently shift teams toward this change.

@pjhill This looks good to go, just throwing a couple errors on CI blocking the merge:
In Jenkins: [2021-01-27T22:28:57.365Z]   │ ✖  applications/find-forms/tests/e2e/0      267ms        1        -        1        -      In test_and_build: For can_i_deploy, Error: Failed to get verification status for Contact Us: 401 Unauthorized

Any insight on these? They seem unrelated to the code changes.

**Comment by ddzz** [comment]
> > > > @rjohnson2011 will this rule cause failures on CI, or will it only throw a warning?
> > > 
> > > 
> > > The last commit was to throw a warning rather than an error so CI still passes.
> > 
> > 
> > Warning seems like the right approach for now. I think we want to gently shift teams toward this change.
> 
> @pjhill This looks good to go, just throwing a couple errors on CI blocking the merge:
> In Jenkins: [2021-01-27T22:28:57.365Z] │ ✖ applications/find-forms/tests/e2e/0 267ms 1 - 1 - In test_and_build: For can_i_deploy, Error: Failed to get verification status for Contact Us: 401 Unauthorized
> 
> Any insight on these? They seem unrelated to the code changes.

I would re-run both builds here and maybe rebase. The Jenkins failure looks like a new flaky test, and I'm pretty sure the CircleCI failure is a known Pact issue that should also go away eventually when you retry.

**Pull request merged**
