### PR TITLE
VACMS 18539 - Vet Center Google Maps link, change to VADS component and remove recordEvent

### PR DESCRIPTION
**Pull request by eselkin**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

## Summary

- Change anchor tag to va-link with aria label attribute
- Sitewide team

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18539

## Testing done

- Manually tested several Vet Centers

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Desktop |   old Vet Center nearby locations link  | new Vet Center nearby locations link |

<details><summary>GA info</summary>
Screenshot 2024-08-14 at 9 21 29 AM
</details>

## What areas of the site does it impact?

Vet Center pages

## Acceptance criteria

- [x] Element: "Get directions on Google maps" link
  - [x] convert to web component
  - [x] enable component's baked-in analytics
  - [x] remove custom events
- [ ] a11y review

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user (unauthenticated)

## Requested Feedback

Test on a Vet center like /boston-vet-center

### CODE REVIEW

**Comment by laflannery** [comment]
@eselkin I am confused? The Get directions link on Vet Center pages is already a `va-link` component. Here's a page from prod: https://www.va.gov/bangor-vet-center/ and this is what it looks like:
image

**Comment by randimays** [comment]
@laflannery This is actually for the vet center nearby locations list: `/bangor-vet-center/locations` -> Other nearby Vet Centers

**Comment by eselkin** [comment]
Oops. That would explain why I was seeing something different. Will retest and fix.

**Comment by eselkin** [comment]
Fixed, but RI is not yet up. Also fixed images and click event screenshot.

**Review by randimays — APPROVED** [review]
LGTM! Sorry for the misdirect on the ticket as to where this link lived 😬

**Review by laflannery — APPROVED** [review]
Looks good!

**Comment by eselkin** [comment]
@randimays Reading is evidently not my strong suit. Not your fault.

**Pull request merged**
