### PR TITLE
Content/wip/add receive gi bill transfer page

### PR DESCRIPTION
**Pull request by kellyskennedy**

### CODE REVIEW

**Comment by kellyskennedy** [comment]
Hi @peggygannon Could you review this, please? #4387

**Review by peggygannon — COMMENTED** [review]
@kellyskennedy Hi, Kelly. I made some edits to both pages and updated the internal links. 
When linking internally you don't need to include "https:/vets.gov..." 
A few other things:
--I tweaked the intro to the new page. I tried to make it more of a call to action. Let me know what you think. 
--the footers on the new page are now appearing at the top! I couldn't figure out how to fix, as I believe the footers are in another file. Did you update the footers? 
--I think that in the left nav "Transferring Benefits" should come before "Using Transferred Benefits"  I can show you how to update this if you need me to.

**Comment by kellyskennedy** [comment]
@bob Can you help us figure out why the headers are now footers? Thanks!

**Comment by kellyskennedy** [comment]
Ready for your review, @bethpotts

**Comment by jkassemi** [comment]
To @bethpotts for review/close.

**Comment by ncksllvn** [comment]
Hi there 👋 Because of the changes involved to meet the requirements of Brand Consolidation, this pull request is unfortunately incompatible with `vets-website` and is being closed as part of a post-launch clean-up effort. However, to make sure the intent of the work is not lost, we're collecting all relevant pull requests into https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15129 and will open a longstanding issue into https://github.com/department-of-veterans-affairs/vagov-content for the visibility of the content and product teams. Thank you and sorry for any inconvenience!

**Pull request closed without merging**
