### PR TITLE
Pensions e2e documents ceh

### PR DESCRIPTION
**Pull request by cehsu**
Connects to department-of-veterans-affairs/vets.gov-team#3417
Connects to department-of-veterans-affairs/vets.gov-team#3743

### CODE REVIEW

**Comment by jbalboni** [comment]
@cehsu I want to try testing this locally, but I get an error at the second dependent's expected income page. Any idea?

**Review by cvalarida — COMMENTED** [review]
What's `test/pensions/test.png` for?

**Comment by cehsu** [comment]
Thanks @jbalboni, that's an interesting bug. The logic in `00-all-fields.e2e.spec.js` and test data in `maximal-test.json` for both dependents are the same.
Thanks @cvalarida, the `test/pensions/test.png` is to test out mocking document upload, thanks for any thoughts on whether there is another better way to go about this, or if you also have thoughts on the issue @jbalboni pointed out, as I do not currently encounter that error locally.

**Comment by jbalboni** [comment]
It looks like on my machine we need some wait calls before the additional sources inputs. I'm not entirely sure why. Changes pushed here.

**Review by jbalboni — APPROVED** [review]

**Review by cvalarida — APPROVED** [review]

**Pull request merged**
