### PR TITLE
Update announcements.json

### PR DESCRIPTION
**Pull request by TamGIBill**
## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — CHANGES_REQUESTED** [review]
Based on the start and end dates, neither of these announcements will ever display. Did you want the end dates to be in the future?

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by shawkey-daniel — CHANGES_REQUESTED** [review]
The JSON formatted test is very sensitive to extra whitespace. Please remove the extra line break on line 2.

**Review by rianfowler — APPROVED** [review]

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Pull request merged**
