### PR TITLE
Update VAOS links to be tab-navigable and interactive

### PR DESCRIPTION
**Pull request by JunTaoLuo**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

## Summary

- This PR adds interactivity to the different `va-link` elements in VAOS. 
- Though tab navigation functionality was added in https://github.com/department-of-veterans-affairs/vets-website/pull/30126 by adding `tabindex="0"`, this was insufficient for interaction (e.g. navigating to the link and voice over).
- To ensure correct functionality and appearance:
  - Add href to all va-link elements to ensure it is tab navigable, read correctly by Voice Over, opens in the same window when enter is pressed and the target link appears when hovering over with the mouse
  - Remove `history.push` for links to new appointments since regular navigation to the link specified by `href` is sufficient
  - Add `e.preventDefault()` for links to edit and retain usage of `history.push` to ensure saved content is not erased during appointment booking/request workflows.

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88961

## Testing done

- Tested locally using a canceled appointment.
- See attached video for test result.

## Screenshots

No UI impact see above for video on interactivity.

## What areas of the site does it impact?

VAOS

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

Since this PR modifies the behavior of many links and changes how we navigate to the target URLs for some, thorough testing of each link should be done as part of the review. I've listed in a comment below how to find each of these links and what the expected targets should be.

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
# Link Navigation

## Reviewing appointments

NoAppointments
- Where: Used in Upcoming, Pending(requests), Past appointment lists
- What: Link to create new appointment
  - Target: http://localhost:3001/my-health/appointments/schedule/type-of-care

StatusAlert
- Where: Alert displayed for upcoming, proposed and cancelled appointments detail pages
  - Upcoming and proposed appointments must add `?confirmMsg=true` to display the links
- What: Link to create new appointment
  - Target: http://localhost:3001/my-health/appointments/schedule/type-of-care

## Covid vaccine flow

ReviewPage
- Where: Review page before confirmation
- What: Link to edit contact information
  - Target: http://localhost:3001/my-health/appointments/schedule/covid-vaccine/contact-information

ConfirmationPageV2
- Where: Confirmation after booking covid 19 vaccine
- What: Link to create new appointment
  - Target: http://localhost:3001/my-health/appointments/schedule/type-of-care

## VA Direct schedule flow

ReasonForAppointmentSection
- Where: Edit reason from the review page
- What: Link to edit reason for appointment
  - Target: http://localhost:3001/my-health/appointments/schedule/reason

ContactDetailsSection
- Where: Edit contact details from the review page
- What: Link to edit contact details
  - Target: http://localhost:3001/my-health/appointments/schedule/contact-information

ConfirmationDirectScheduleInfoV2
- Where: Confirmation after booking a direct schedule appointment
- What: Link to create new appointment
  - Target: http://localhost:3001/my-health/appointments/schedule/type-of-care


## VA request flow

PreferredDatesSection
- Where: Edit preferred date from the review page
- What: Link to edit preferred date
  - Target: http://localhost:3001/my-health/appointments/schedule/va-request/

ReasonForAppointmentSection
- Where: Edit reason from the review page
- What: Link to edit reason for appointment
  - Target: http://localhost:3001/my-health/appointments/schedule/va-request/reason

TypeOfVisitSection
- Where: Edit type of visit from the review page
- What: Link to edit type of visit
  - Target: http://localhost:3001/my-health/appointments/schedule/va-request/preferred-method

ContactDetailsSection
- Where: Edit contact details from the review page
- What: Link to edit contact details
  - Target: http://localhost:3001/my-health/appointments/schedule/va-request/contact-information

## CC request flow

PreferredDatesSection
- Where: Edit preferred date from the review page
- What: Link to edit preferred date
  - Target: http://localhost:3001/my-health/appointments/schedule/community-request/

SchedulingFacilitySection
- Where: Edit selected facility from the review page
- What: Link to facility selection
  - Old Target: http://localhost:3001/my-health/appointments/schedule/community-request/preferred-provider
  - New Target: http://localhost:3001/my-health/appointments/schedule/community-request/closest-city

SelectedProviderSection
- Where: Edit selected provider from the review page
- What: Link to provider selection
  - Target: http://localhost:3001/my-health/appointments/schedule/community-request/preferred-provider

PreferredLanguageSection
- Where: Edit preferred language from the review page
- What: Link to preferred language
  - Old Target: http://localhost:3001/my-health/appointments/schedule/community-request/preferred-provider
  - New Target: http://localhost:3001/my-health/appointments/schedule/community-request/preferred-language

ReasonForAppointmentSection
- Where: Edit reason from the review page
- What: Link to edit reason for appointment
  - Target: http://localhost:3001/my-health/appointments/schedule/community-request/reason

ContactDetailsSection
- Where: Edit contact details from the review page
- What: Link to edit contact details
  - Target: http://localhost:3001/my-health/appointments/schedule/community-request/contact-information

## Obsolete

RequestedStatusAlert
- Obsolete

PreferredProviderSection
- Obsolete

**Review by jenniemc — APPROVED** [review]
Great work!

**Review by ryanshaw — APPROVED** [review]
Did a bunch of local test, looks good on this end. 🥳

**Review by vbahinwillit — APPROVED** [review]
LGTM! Great Job!

**Comment by JunTaoLuo** [comment]
Thanks for the review everyone! But given that this is still kind of risky and we're opt-in to deploy to prod directly, I'll merge this on Monday just so that I don't break things over the weekend.

**Pull request merged**
