### PR TITLE
Fix for sidebar disappearing too soon on top landing pages

### PR DESCRIPTION
**Pull request by ncksllvn**
Resolves https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4600

### CODE REVIEW

**Comment by ncksllvn** [comment]
To expand on this, we had a great set up using Foundation. Foundation's grid was set to collapse the main content area (right) at 640px. However, we had a custom breakpoint defined at 768px, where the left sidebar would disappear (visibility to 0) and a button for toggling a side drawer would appear above the main content. Because of this discrepancy between the breakpoints, the left sidebar would disappear but its place in the grid would still be there on viewports between 640px and 768px. 

The fix for this was to switch to USWDS's grid system (it was using both framework classes before) and a few adjustments.

### Before:
image

### Proposed:
image

**Comment by ncksllvn** [comment]
Just to add, after looking through the SASS, we import the modules strategically so that we override USWDS's medium breakpoint to be 768px (it's 600px by default) before the grid classes are defined. That's why switching entirely to USWDS's grid system worked.

**Review by melwoodard — APPROVED** [review]
Looks good from a visual perspective!

**Comment by ncksllvn** [comment]
Thanks @melwoodard! I'm gonna go ahead and merge it because I feel really good about this fix.

**Pull request merged**
