### PR TITLE
Bump formation to 6.9.2

### PR DESCRIPTION
**Pull request by kelsonic**
## Description
**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/8790

This PR bumps `formation` to include styling changes that resolve the focus border around pagination numbers.

## Acceptance criteria
- [x] Bump formation

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by ncksllvn — APPROVED** [review]

**Comment by kelsonic** [comment]
Closing this PR as @jenstrickland would prefer if VSP fixed this issue

**Review by rianfowler — APPROVED** [review]

**Review by rianfowler — APPROVED** [review]

**Comment by kelsonic** [comment]
These e2e tests keep failing:

image

I don't think it is related but I want to make sure our common Pagination component styling tweak didn't break that team's application. I don't actually know the team that manages `claims-status`, however, so I'm not sure who to ping on their team to make sure this PR doesn't break it 🙂

**Comment by jenstrickland** [comment]
@kelsonic I think `claims status` would be BAM1. Is it y'all, @Mottie ?

**Comment by Mottie** [comment]
Yes, our team owns the claim status. We haven't touched that component, so I'm not sure why there's an error. It looks like the word `Error` is being prepended making that e2e test fail. I'm not sure why.

**Comment by Mottie** [comment]
Ok, so in the `ErrorableFileInput` component, there is this block in the JSX:

```jsx
<span className="sr-only">Error</span>
```

I wonder if my `sr-only` css update is now making this block show up in the text check? I don't see any thing that would cause that: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/231/files

**Comment by kelsonic** [comment]
Weird... @Mottie this was the change to the `<Pagination />` component: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/254/files

It seems unrelated to the prepending of `Error` issue and I think you're right that the sr-only node is what's causing the issue now! 🙂It's funny how this isn't failing on other PRs though and just this one

**Comment by ncksllvn** [comment]
If Formation hasn't been bumped since https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/231 was merged, then it makes sense that this is the first the error would pop up

**Pull request merged**
