### PR TITLE
VACMS 17913 impostor alert FL emergency note

### PR DESCRIPTION
**Pull request by eselkin**
## Summary

- Facility Locator shows a Note with an info alert-like impostor background. Replaced with slim info alert with top margin
- Sitewide Facilities

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17913

## Testing done

- Old behavior when Facility type: "Emergency care" was selected showed a div with info alert bg color. Changed to alert.
- Updated tests to check for slim alert.

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |    Screenshot 2024-05-24 at 4 36 39 PM    |    Screenshot 2024-05-24 at 4 37 13 PM   |
| Desktop |    Screenshot 2024-05-24 at 4 36 28 PM    |   Screenshot 2024-05-24 at 4 37 28 PM    |

## What areas of the site does it impact?

Facility Locator

## Acceptance criteria

- [x] Alert in the Emergency Care filter is updated to use the slim v3 component
- [x] Update and run existing test(s).
- [x] If additional tests are needed, stub a ticket to note this for future work. (N/A)
- [x] QA is completed on all supported browsers (I checked Edge, Safari, Chrome, Firefox, but @laflannery may want to check again)
- [ ] Requires accessibility review

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user (unauthenticated)

## Requested Feedback

Check on [review instance](http://3659db32177de4e6ade58f584f4fe0e4.review.vetsgov-internal/find-locations/?address=Los%20Angeles%2C%20CA&bounds%5B%5D%5B%5D=-118.99168&bounds%5B%5D%5B%5D=33.304077&bounds%5B%5D%5B%5D=-117.49168&bounds%5B%5D%5B%5D=34.804077&bounds%5B%5D%5B%5D%5B%5D=-118.99168&bounds%5B%5D%5B%5D%5B%5D=33.304077&bounds%5B%5D%5B%5D%5B%5D=-117.49168&bounds%5B%5D%5B%5D%5B%5D=34.804077&bounds%5B%5D%5B%5D%5B%5D%5B%5D=-118.99168&bounds%5B%5D%5B%5D%5B%5D%5B%5D=33.304077&bounds%5B%5D%5B%5D%5B%5D%5B%5D=-117.49168&bounds%5B%5D%5B%5D%5B%5D%5B%5D=34.804077&context=Los%20Angeles%2C%20California%2C%20United%20States&facilityType=emergency_care&latitude=34.054077&longitude=-118.24168&page=1&radius=29&serviceType&bounds%5B%5D=-118.99168&bounds%5B%5D=33.304077&bounds%5B%5D=-117.49168&bounds%5B%5D=34.804077)

### CODE REVIEW

**Comment by laflannery** [comment]
@eselkin Can you remove the `message-aria-describedby` on the 911 number within the alert? I know this isn't something you added it was there before but it's odd because there is no visual text that this belongs to so it's not needed and actually can cause confusion for visual-screen reader users.
Screenshot 2024-05-28 at 8 24 55 AM

**Comment by laflannery** [comment]
I just re-reviewed and this looks good now, thanks!

**Review by maxx1128 — APPROVED** [review]
LGTM 👍

**Review by dsasser — APPROVED** [review]
Code changes look good and functionality remains. LGTM!

**Comment by eselkin** [comment]
Ugh, VAOS tests failing

**Review by ataker — APPROVED** [review]

**Pull request merged**
