### PR TITLE
content/wip/Add-mention-of-appeals-to-accred-rep

### PR DESCRIPTION
**Pull request by bethpotts**

### CODE REVIEW

**Review by DanielleSoCompany — APPROVED** [review]
Beth - This looks great. In looking at the full page, I wondered if we might want to make a couple more tweaks. Leaving here for your consideration/call. Proposed edits are in all caps for visibility.

These trained professionals can also:

Help you gather supporting documents (like a doctor’s report or medical test results)
File a claim OR APPEAL on your behalf
Provide ADDED SUPPORT, such as helping with transportation to medical appointments or emergency funds
Note: Veterans Service Officers work for Veterans Service Organizations (both are called VSOs), as well as for local government offices.

What does it cost to use an accredited representative or a VSO?
In general, no individual or organization may charge you a fee to help you file your initial application for benefits. But they may charge you for unusual expenses. It's only after WE'VE MADE a decision about your ORIGINAL claim that VA-accredited claims agents and attorneys may charge for their services. Make sure you ask up front what, if any, fees you’ll be charged. If you believe a claims agent or attorney charged a fee that’s too high, you can challenge it. 
Find out more in the “How to Challenge a Fee” guide.

**Comment by bethpotts** [comment]
@peggygannon Please proof these changes for typos. Thanks!

**Review by peggygannon — APPROVED** [review]
@bethpotts I made one small tweak (changing such as to like). Otherwise, changes look good.

**Comment by bethpotts** [comment]
@phiden This is ready for your review and merge.

**Review by phiden — APPROVED** [review]

**Pull request merged**
