### PR TITLE
Removed references to 90 days

### PR DESCRIPTION
**Pull request by kellyskennedy**
CURF requests that we remove all 90-day pre-need references.

### CODE REVIEW

**Comment by kellyskennedy** [comment]
@peggygannon Could you review this? Checked in with the SME, and she asked that we leave the residual information, just take out the 90-day stuff. Thanks!

**Review by peggygannon — COMMENTED** [review]
@kellyskennedy I made a few adjustments. sending it to @bethpotts for her review/thoughts

**Review by peggygannon — APPROVED** [review]

**Comment by kellyskennedy** [comment]
@phiden Could you please review and merge this for today's build? Thanks!

**Review by bethpotts — APPROVED** [review]

**Comment by phiden** [comment]
@kellyskennedy this probably won't make today's build -- there's an error we have to clear and I think the next release is happening in the next hour. Probably in the future we should come up with a process for ensuring PRs get merged with enough time to allow for builds and failures especially for time sensitive stuff, but I'll get this in as quick as I can

**Review by phiden — APPROVED** [review]

**Comment by kellyskennedy** [comment]
Okay, @bethpotts I reworded the "Please wait" bit--I think it offers more of an explanation, but keeps it short

**Comment by bethpotts** [comment]
@kellyskennedy I tweaked a bit, and I think we're ready with this one! Finally. You can get it merged.

**Pull request merged**
