### PR TITLE
Migrate text-align utility classes to CSS Library utilities

### LINKED ISSUE #3217: CSS Library - Utilities - Swap text-align import
## Description
We need to import text-align utilities from css-library into vets-website and content-build. This is broadly a two step process:
1. Update breakpoint names for the text-align classes to USWDS v3 equivalents in vets-website and content-build
2. Comment out the text-align import in [formation/core.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/core.scss#L83), manually publish a new formation release, and then update the version of Formation in vets-website. 

| Current VADS Name | USWDS v3 Name |
| --------------------------- | ------------------------- |
| xsmall-screen (320px)          | mobile (320px) |
| small-screen (480px) | mobile-lg (480px) |
| small-desktop-screen (1008px) | desktop (1024px) 
| large-screen (1200px) | desktop-lg (1200px) |

## Considerations
- We won't need to touch the `medium-screen` breakpoint since we're keeping that in and have manually added it to our utilities.css file. 
- Likewise, `tablet` is identical across both stylesheets and doesn't need to be changed, so it isn't included in the table above. 
- There's a 16px difference between `small-desktop-screen` and its replacement, `desktop`, but this shouldn't matter. 
- Global search in vets-website shows:
  - 1 instances of `xsmall-screen:vads-u-text-align-...`
  - 2 instances of `small-screen:vads-u-text-align-...`
- Global search in content-build shows: nothing
- Above changes may need to be split into a couple of PRs to accommodate vets-website CI. 

## Tasks
- [ ] Search and replace instances of `<vads-responsive-prefix>:vads-u-<utility>-` with corresponding uswds v3 name in the table above. Example: `xsmall-screen:vads-u-border-bottom--0` becomes `mobile:vads-u-border-bottom--0`
- [ ] run vets-website locally to verify that breakpoints are being applied from css-library `utilities.css`
- [ ] specifically run the [proxy-rewrite](https://github.com/department-of-veterans-affairs/vets-website/blob/aab3a4bb7c55625604ce8f62b71097f16e858ef3/src/applications/proxy-rewrite/README.md#L1) application and test the injected header and footer
- [ ] In formation, comment out the text-align import in [formation/core.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/core.scss#L83)
- [ ] Bump the version number for Formation and manually publish to NPM
- [ ] Update the Formation version in vets-website. 

## Acceptance Criteria
- [ ] Above tasks have been completed

### PR DESCRIPTION
**Pull request by jamigibbs**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

This updates to the latest release of Formation which has the [text-align utilities](https://design.va.gov/foundation/utilities/text-align) import removed so that the CSS Library utility classes will be used instead. 

There are new breakpoints names which are being updated in this PR as well:

| Current VADS Name | new USWDS v3 Name |
| --------------------------- | ------------------------- |
| xsmall-screen (320px)          | mobile (320px) |
| small-screen (480px) | mobile-lg (480px) |

## Related issue(s)

closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3217

## Testing done

Locally using verdaccio and reviewing e2e tests

## Screenshots

Screenshot 2024-09-10 at 9 17 32 AM

Screenshot 2024-09-10 at 9 17 27 AM

Screenshot 2024-09-10 at 9 17 23 AM

Screenshot 2024-09-10 at 1 14 20 PM

Screenshot 2024-09-10 at 1 18 10 PM

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by jsimonVA — COMMENTED** [review]
@jamigibbs I just want to make sure that the break points were tested and all works as it did prior to the new classes being added. I would test the review instance but I do not see a link for it.

**Comment by jamigibbs** [comment]
> @jamigibbs I just want to make sure that the break points were tested and all works as it did prior to the new classes being added. I would test the review instance but I do not see a link for it.

Hi @jsimonVA! Absolutely! I have done testing locally as well in the review instance but I would appreciate your help as well. The review instance was generated here: http://a8c52e0e29257152f2577018f9347e1c.review.vetsgov-internal/

**Review by jsimonVA — APPROVED** [review]
LGTM :)

**Review by powellkerry — APPROVED** [review]

**Review by JunTaoLuo — APPROVED** [review]
LGTM for the appointments portion.

**Review by vbahinwillit — APPROVED** [review]
LGTM!

**Review by simiadebowale — APPROVED** [review]
LGTM

**Review by asiisii — APPROVED** [review]
LGTM on the Profile > Connected Apps page 🚀

**Pull request merged**
