### PR TITLE
Replace formation module imports in site-wide

### PR DESCRIPTION
**Pull request by powellkerry**
## Summary

This is part of the effort to deprecate formation. This PR replaces formation module imports with css-library module imports. These modules were copied from formation to css-library and updated to work with the newer version of sass and USWDS.

This PR is for site-wide only, application imports will be addressed in a separate PR in an effort to get CI passing. Original PR:  https://github.com/department-of-veterans-affairs/vets-website/pull/30267

## Related issue(s)
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2538
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2911

## Testing done

Visual testing comparing local to dev

## Screenshots

There should be no visual differences

## What areas of the site does it impact?

All code and applications that were using formation module imports

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [x] The vets-website header does not contain any web-components
- [x] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [x] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by randimays** [comment]
@powellkerry Please fill out the part of the PR template regarding Team Sites. It's important that the injected header/footer are tested thoroughly when changes to the proxy-rewrite package are made.

**Comment by micahchiang** [comment]
@randimays - These changes have already been tested and signed off by site-wide in this other PR - https://github.com/department-of-veterans-affairs/vets-website/pull/30267. We decided to break that other PR into smaller more manageable ones to better deal with CI

**Review by randimays — DISMISSED** [review]
@micahchiang Oh good! Thanks for the clarification.

**Comment by powellkerry** [comment]
@randimays Thanks for the reminder! I thought we were safe because we had already tested these changes, but there were some changes made on main that caused the icons and font-size in the footer to be smaller than on the homepage. I have added fixes for that in this PR.

**Review by rsmithadhoc — APPROVED** [review]

**Review by randimays — APPROVED** [review]
LGTM

**Pull request merged**
