### PR TITLE
VACMS-17887 Facility locator slim alert

### PR DESCRIPTION
**Pull request by randimays**
## Summary
Convert the alert on urgent and emergency care facility search results to a slim `<va-alert>`.

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17887

## Testing done
Tested locally with facility locator search for Emergency Care and Urgent Care.

Steps to test:
1. From va.gov -> Find a VA Location
2. City, state: Los Angeles, CA
3. Facility type: Emergency Care
4. Service type: All in-network emergency care
5. Slim alert is under each search result

Screenshot 2024-05-30 at 1 40 29 PM

### CODE REVIEW

**Review by micahchiang — DISMISSED** [review]

**Review by eselkin — DISMISSED** [review]
LGTM

**Comment by laflannery** [comment]
Accessibility wise these look good, but I would like design to review because they look a bit aggressive with the longer text. I have asked @aklausmeier [in slack here](https://dsva.slack.com/archives/C06NMUK12LR/p1717092547805419)

**Comment by laflannery** [comment]
Per Design decision - we should unbold the links

**Review by laflannery — APPROVED** [review]
LGTM!

**Review by eselkin — APPROVED** [review]
LGTM

**Pull request merged**
