### PR TITLE
VACMS-16938 Step 2 for DUW v2

### PR DESCRIPTION
**Pull request by chriskim2311**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary
Adding the Step 2 Results components

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16938

## Testing done
Mural for content:
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696352911500/80253b1c7200212cbcbcfb940d2cf4a29fed8417?sender=ua4eca0cc168eff677bd03940

## Screenshots
<details><Summary>Flow 1 No Step 2</Summary>
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs
Screenshot 2024-08-13 at 9 10 03 AM
</details>

<details><Summary>Flow 2 PTSD</Summary>
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs
Screenshot 2024-08-13 at 9 10 03 AM

Discharge Year less than 1997
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs
Screenshot 2024-08-13 at 9 10 03 AM

Discharge Year before 1992
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs
Screenshot 2024-08-13 at 9 10 03 AM
</details>

<details><Summary>Flow 3 TBI</Summary>
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs
Screenshot 2024-08-13 at 9 10 03 AM
</details>

<details><Summary>Flow 4 Sexual Orientation</Summary>
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs
Screenshot 2024-08-13 at 9 10 03 AM
</details>

<details><Summary>Flow 5 Sexual Assault</Summary>
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs
Screenshot 2024-08-13 at 9 10 03 AM
</details>

## What areas of the site does it impact?
DUW v2

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### CODE REVIEW

**Comment by laflannery** [comment]
Few things @chriskim2311 
**Flow issues:**
1. In Flow 4 Sexual Orientation I'm not seeing paragraph 3 under **Military Record**, the one that starts with Remember and that you have the orange highlight in your screenshot:
image


**Updates**
1. Can we do the download icon again here for consistency?
image
2. Can you change the heading level of this "Need help preparing..." alert to h3? Now that I see it in more context it should be the same level as the other headings in the process list
image

**Comment by chriskim2311** [comment]
@laflannery The paragraph will only show if Reason is PTSD, TBI or Sexual Assault. So that is working as expected. I have updated the heading and the icon for the download link.

**Review by randimays — APPROVED** [review]
LGTM! Great work.

**Review by powellkerry — APPROVED** [review]

**Comment by laflannery** [comment]
@chriskim2311 The headings and icons look good but I still have a question on Flow 4:
- In your screen shot in the description above for testing/confirmation it has the 3rd paragraph under **Military Records**, the one that starts with "Remember". I used the same answers you have in your example and do not have this 3rd paragraph. 
- Also, this paragraph in your screen shot actually references sexual orientation which does enforce the fact that it should show for sexual orientation.

I just want to be sure we have the proper results for this particular flow

**Comment by chriskim2311** [comment]
@laflannery Thanks! I fixed the screenshot I think uploaded a stale one by accident. It is working as expected with the correct answer to discharge type question.

**Comment by laflannery** [comment]
Thanks for clarifying, approved!

**Comment by thejordanwood** [comment]
I know this is already merged, but since my review was also asked for, I wanted to comment that this is also approved by me!

**Pull request merged**
