### PR TITLE
Page description changed to match new requirements

### PR DESCRIPTION
**Pull request by ptouchton**
## Description
This PR changes the covid vaccine contact information page description to match the new requirements in the copy doc

## Original issue(s)
department-of-veterans-affairs/va.gov-team#32194

## Testing done
Manual and Unit

## Screenshots

- New Appointment Flow
image

## Acceptance criteria
- [ ] Given the COVID-19 new appointment workflow,
When the user enters the Confirm your contact information page,
Then the page description matches the copy doc

- [ ] Given the new appointment workflow,
When the user enters the Confirm your contact information page,
Then the page description matches the copy doc

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by jenniemc — APPROVED** [review]
Looks good to me!

**Review by jhonny218 — APPROVED** [review]
LGTM

**Review by vbahinwillit — CHANGES_REQUESTED** [review]
I think the new appointment workflow changes are missing.

**Comment by ptouchton** [comment]
@vbahinwillit I'm not sure what you mean by "missing new appointment flow"...I looked back through the copy doc to see what I missed but, I couldn't find a reference to a new flow. Would you have time today to discuss?

**Comment by ptouchton** [comment]
@jenniemc ....The build finally cleared up. I was missing the new appointment change originally. Thank you!

**Review by jenniemc — APPROVED** [review]
Looks good to me! Tony has eagle eyes...glad he spotted the two AC.

**Comment by jenniemc** [comment]
Since Tony made the request for change, it's up to his approval to unblock the merge.

**Review by vbahinwillit — APPROVED** [review]

**Pull request merged**
