### PR TITLE
CT: 203 - Update DEAS Benefit Calculation on School Profile Page #18165, #18412, #18417 

### PR DESCRIPTION
**Pull request by zurbergram**
## Description

As a Compare Tool user, I need the School Profile Benefit Estimator to display the correct information for the "Dependents Educational Assistance (DEA)" benefit so that I can make an informed decision about how to use my benefits.

This includes uses on the Search Results page as well as the Profile page

Uses new GIDS constants
- DEARATEFULLTIME
- DEARATETHREEQUARTERS
- DEARATEONEHALF

## Testing done
- local testing
- unit testing

## Screenshots
Screen Shot 2019-04-29 at 1 56 38 PM
Screen Shot 2019-04-29 at 1 56 49 PM
Screen Shot 2019-04-29 at 1 56 57 PM
Screen Shot 2019-04-29 at 1 57 04 PM
Screen Shot 2019-04-29 at 1 57 10 PM
Screen Shot 2019-05-06 at 11 10 21 AM

## Acceptance criteria
- [ ] The following amounts can be updated/changed using the "CalculatorConstant" of the GIDS service.
     - DEA 3/4 Time
     - DEA 1/2 Time
- [ ]  When the answer to the "Enrolled" question is "Full Time", the amount $1,224 is used to calculate the Housing benefit in the Benefit Estimator.
- [ ] When the answer to the "Enrolled" question is "3/4 Time", the amount $967 is used to calculate the Housing benefit in the Benefit Estimator.
- [ ]  When the answer to the "Enrolled" question is "1/2 Time", the amount $710 is used to calculate the Housing benefit in the Benefit Estimator.
- [ ] The amount of $1,224 (DEA Full Time Rate) is displayed for the Housing benefit on the Search Results Page.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Comment by zurbergram** [comment]
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!

**Comment by rianfowler** [comment]
What university did you use to get those screenshots? I'm getting NaN when I run this locally against University of Utah. My GIDS is pointing to staging.

**Review by rianfowler — APPROVED** [review]
This looks fine. I think it would be good to test this in staging against a few universities. the staging data doesn't match up to the production data so it would mostly be making sure it doesn't break the different school types (they don't call have housing allowance)

https://staging.va.gov/gi-bill-comparison-tool/profile/149D9435 
https://staging.va.gov/gi-bill-comparison-tool/profile/30251015
https://staging.va.gov/gi-bill-comparison-tool/profile/20149844 
https://staging.va.gov/gi-bill-comparison-tool/profile/10B00106

**Comment by zurbergram** [comment]
> What university did you use to get those screenshots? I'm getting NaN when I run this locally against University of Utah. My GIDS is pointing to staging.

The new constant don't exist on STAGING yet and is most likely the reason you are getting NaN.

**Comment by zurbergram** [comment]
> This looks fine. I think it would be good to test this in staging against a few universities. the staging data doesn't match up to the production data so it would mostly be making sure it doesn't break the different school types (they don't call have housing allowance)
> 
> https://staging.va.gov/gi-bill-comparison-tool/profile/149D9435
> https://staging.va.gov/gi-bill-comparison-tool/profile/30251015
> https://staging.va.gov/gi-bill-comparison-tool/profile/20149844
> https://staging.va.gov/gi-bill-comparison-tool/profile/10B00106

Will let QA know, also added unit tests to test against an OJT institution and for the case of `tuitionFeesPerTerm < totalHousingAllowance` when selecting `less than half` or `quarter` for enrolled.

**Comment by delli-gatti-michael** [comment]
#18165 has passed QA. Will approve once #18412 has as well

**Review by delli-gatti-michael — APPROVED** [review]
Both Stories passing QA. Looks good to me

**Comment by jbalboni** [comment]
@zurbergram What's your plan for merging this PR? Rian and I took a look at it early on, and there have been a few changes since then, so It seems like we should take another look through it when you're ready?

**Comment by zurbergram** [comment]
> @zurbergram What's your plan for merging this PR? Rian and I took a look at it early on, and there have been a few changes since then, so It seems like we should take another look through it when you're ready?

I'm waiting on the GIDS Calculator Constants to be updated in Staging, the changes since approval are also relevant to Colmery 203 work either from QA review or Product Owner requests.

**Review by jbalboni — APPROVED** [review]

**Pull request merged**
