### PR TITLE
Cleaned up Cypress fixtures behavior

### PR DESCRIPTION
**Pull request by U-DON**
## Description
Fixtures were recently changed to be served from `"src"` as part of the Cypress parallelization in CI. As a result, `cy.syncFixtures` no longer worked as it used to, resulting in some unexpected behavior when using it. It originally linked fixtures in a temporary folder under `"cypress/fixtures"`, but `cy.fixture` started looking in `"src"`, so the temp directory was getting created there, thus needing some extra path resolution.

This set of changes reconciles the new location with the use of fixtures to make fixtures work in a consistent and less roundabout manner.

1. Set the root to be the project root for paths passed to `cy.fixture`. This means that you may now use `__dirname` to use relative paths for your fixtures instead of typing long paths with `src` as the root.

    ```js
    const fixtureFile = path.join(__dirname, 'fixtures', 'file.json');
    cy.fixture(myFile).then(data => { ... });
    ```

2. Deprecated `cy.syncFixtures`.
    - As mentioned, this no longer serves a purpose due to the new path that `cy.fixture` searches.
    - This was not used often either, especially not for syncing multiple fixture paths.

3. Deprecated the `fixtures` property in the test configuration for tests using the Form Tester.
    - With the way that fixtures work now, it's only useful for setting the test data directory.
    - Added the `dataDir` property to replace `fixtures.data`, which will continue to work for now.
    - Updated documentation accordingly.

4. Updated tests using fixtures to use `cy.intercept` instead of `cy.route` and passing the imported fixtures directly.
    - `cy.syncFixtures` was used mainly to pass `'fx:some/fixture'` to the last argument of `cy.route`, but it seemed like most instances of `cy.route` or `cy.intercept` were directly passing in imported JSON data, so I opted for consistency.

## Testing done
Tests pass.

## Acceptance criteria
- [ ] Cypress fixture usage should be consistent with sensible defaults to provide expected results.
- [ ] Cypress fixture usage should be documented.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by mdewey — APPROVED** [review]
LGTM - Thanks!

**Review by jhonny218 — APPROVED** [review]

**Comment by U-DON** [comment]
Looking for reviews from:
- @department-of-veterans-affairs/va-cto-health-products
- @department-of-veterans-affairs/vsa-facilities-frontend 
- @department-of-veterans-affairs/vsa-public-websites-frontend 

Just need y'all to check that your tests still look good. Thank you!

**Review by mpelzsherman — APPROVED** [review]
LGTM

**Review by batemapf — APPROVED** [review]
:shipit:

**Pull request merged**
