### PR TITLE
CT 116: Update GI Bill Comparison Tool Landing Page #19099, #19214

### PR DESCRIPTION
**Pull request by zurbergram**
## Description
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19099
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19214

As a Comparison Tool user, I need the ability to specify the type of institution that I would like to review when searching so that I can easily find VET TEC providers.

As a Comparison Tool user, I need the School/Employer Search Results page to exclude VET TEC programs/providers if I change the filter to "All" so that my results match my expectations.

## Assumptions:
1. This work will be completed behind a flag so that it is only available in the staging environments and below.
2. This story will use a URL that is coordinated with the user completing story #19101 (VET TEC Search Results)

## Screenshots
Screen Shot 2019-07-10 at 10 25 50 AM
Screen Shot 2019-07-10 at 2 03 25 PM
Screen Shot 2019-07-10 at 2 03 16 PM

## Acceptance criteria
- [ ] When the user visits the landing page, the following questions and details are displayed by default:
     - What is your military status?
            - Default answer value: Veteran
            - Answer values: No change to current values
     - Which GI Bill benefit do you want to use?
            - Default answer value: Post-9/11 GI Bill (Ch 33)
            - Answer values: No change to current values
     - Cumulative Post-9/11 active duty service
            - Default answer value: 36+ months: 100% (includes BASIC)
            - Answer values: No change to current values
     - Type of institution
            - Default answer value: Schools
            - Answer values: Schools, Employers, VET TEC training providers
     - How do you want to take classes?
            - Default answer value: In person only
            - Answer values: No change to current values
     - Enter a city, school or employer name
            - Default answer value: [blank]

- [ ] The answer "VET TEC training providers" to the new question "Type of Institution" is hidden when any of the following criteria are met:
a. The answer to the "What is your military status?" question is "Active Duty"
b. The answer to the "Which GI Bill benefit do you want to use?" question is not "Post-9/11 GI Bill (Ch 33)"

- [ ] The "VET TECH training providers" answer has a ("Learn more") link that opens the following page in a new window: https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/.

- [ ] If the user selects "Schools" or "Employers" it will redirect the user to the Standard Search Results page when "Search Schools" is clicked.
     a. The Search Results will have the "Type of Institution" radio button list pre-populated with the value selected on the "Landing Page".
     b. The Search Results are filtered based on the "Type of Institution" selection.

- [ ] If the user selects "VET TEC training providers":
     a. The "Enter a city, school or employer name" label and textbox are hidden.
     b. The user is taken to the VETTEC Search Results page when "Search Schools" is clicked.

- [ ] When the user selects "All" under the "Type of Institution" filter on the Standard Search Results Page, VET TEC providers and programs are not included in the results.
- [ ]  When the user selects "Schools Only" under the "Type of Institution" filter on the Standard Search Results Page, VET TEC providers and programs are not included in the results.
- [ ] When the user selects "Employers Only" under the "Type of Institution" filter on the Standard Search Results Page, VET TEC providers and programs are not included in the results.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Comment by zurbergram** [comment]
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!

**Review by sonntag-adam — APPROVED** [review]

**Review by delli-gatti-michael — APPROVED** [review]
Passes QA

**Comment by zurbergram** [comment]
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!

**Review by rianfowler — APPROVED** [review]

**Pull request merged**
