### PR TITLE
Fix empty artifact tags for horizontal rules

### PR DESCRIPTION
**Pull request by acrollet**
## Summary

This PR updates the horizontal rule helper to add only one artifact tag and ensure that empty artifact tags are not added to the document tree by the helper.

## Related issue(s)

https://jira.devops.va.gov/browse/MHV-50604

## Testing done

- Updated unit tests data + manual testing

## What areas of the site does it impact?

/my-health/medications/
/my-health/medical-records

## Acceptance criteria

- [ ] horizontal rules are not shown as unmarked content
- [ ] empty artifact tags are not added to the document tree by the horizontal rule util method

### Quality Assurance & Testing

- [X] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [X] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [X] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Comment by acrollet** [comment]
@SarahKay8 could you review the attached sample? thank you!

(note: this sample contains only test data, with no PII or PHI)

[test_horizontal_rules.pdf](https://github.com/department-of-veterans-affairs/vets-website/files/13573953/test_horizontal_rules.pdf)

**Review by vmenshutin-bylight — DISMISSED** [review]

**Comment by SarahKay8** [comment]
@acrollet this looks good!

**Comment by acrollet** [comment]
thank you @SarahKay8 !

**Review by SarahKay8 — COMMENTED** [review]
review completed in Adobe. VO + Safari

**Review by vmenshutin-bylight — APPROVED** [review]

**Review by harshilmoradia — APPROVED** [review]

**Pull request merged**
