### PR TITLE
MHV-53646 SM resolve redundant api calls, 401 on allrecipients

### PR DESCRIPTION
**Pull request by alex-morgun-1**
## Summary
- We are sending an API call to retrieve a list of triage teams prior to authenticating to va.gov if a user hits /my-health/secure-messages domain directly resulting 401 error code from /my_health/v1/messaging/allrecipients. Need to rebuild logic to call only after authentication
- Reduce redundant calls to get a user signature and categories. Currently calls are being made every time a user hits compose or reply page. Instead, make a call only if that data is missing, unless a page is fully refreshed

## Related issue(s)

- https://jira.devops.va.gov/browse/MHV-53646

## Testing done

- unit tests updated

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Desktop ||image|

## What areas of the site does it impact?

My Health - Secure Messages

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by oleksii-morgun-va** [comment]
image
Related error logging ☝🏻

**Review by KyleCardwell — DISMISSED** [review]
Looks great!

**Review by KyleCardwell — APPROVED** [review]
LGTM!

**Review by vsaleem — APPROVED** [review]
Nice.💯

**Pull request merged**
