### PR TITLE
Content-wip-ID-card-page

### PR DESCRIPTION
**Pull request by peggygannon**
This PR includes: 
- [x] New "Type of ID Card" page, that details the cards available to Veterans, who's eligible, and where to go to apply.   
- [x] Updated VIC landing page (that doesn't require users to be signed in to view)

### CODE REVIEW

**Comment by peggygannon** [comment]
@bethpotts Here is the new ID Card page for your review.

**Comment by peggygannon** [comment]
@bethpotts Can you approve this PR, so we can move forward with the next step for these page?  

also, for the email address on the VIC page, I mirrored the format we use on this page: /disability-benefits/conditions/exposure-to-hazardous-materials/mustard-gas/

**Review by bethpotts — APPROVED** [review]

**Comment by peggygannon** [comment]
@ncksllvn this PR is ready for your review and merge. **Please note, these pages should be merged into Staging only (not to Production).**

thank you!

**Comment by ncksllvn** [comment]
I had to fix some accessibility issues in your markup for the build to pass. Do you want to take another look at the pages and make sure they look and function okay before I merge?

**Comment by peggygannon** [comment]
@ncksllvn Yes, i'll take another look right now. I'll ping you when I'm done

**Comment by peggygannon** [comment]
@ncksllvn the pages look good. We should be good to merge to staging!

**Review by ncksllvn — APPROVED** [review]

**Pull request merged**
