### PR TITLE
16645 refactor flakey cypress tests

### PR DESCRIPTION
**Pull request by holdenhinkle**
## Description
In reference to ticket - https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/16645#issuecomment-751876550

## Testing done
All the (flaky) tests in this PR now consistently pass.

### CODE REVIEW

**Comment by holdenhinkle** [comment]
I removed test `src/applications/facility-locator/tests/e2e/mobile.cypress.spec.js` because @ddzz is working on fixing it in another branch.

**Review by ddzz — APPROVED** [review]

**Comment by holdenhinkle** [comment]
I just re-ran the tests in headless mode (`yarn cy:run`) and all but two passed. One of the two that failed was [fixed by @ddzz in another branch](https://github.com/department-of-veterans-affairs/vets-website/pull/15503). The other test--`src/applications/personalization/view-representative/tests/view-representative.cypress.spec.js`--is skipped in CI:

```
describe(manifest.appName, () => {
  // Skip tests in CI until the app is released.
  // Remove this block when the app has a content page in production.
  before(function() {
    if (Cypress.env('CI')) this.skip();
  });

  it('is accessible', () => {
    cy.visit(manifest.rootUrl);
    cy.injectAxeThenAxeCheck();
  });
});
```

Here are the results:

```
      Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  applications/ask-a-question/tests/c        9ms        1        -        -        1        - │
  │    ypress/ask-a-question.authed.cypres                                                         │
  │    s.spec.js                                                                                   │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/ask-a-question/tests/c       14ms        2        -        -        2        - │
  │    ypress/ask-a-question.unauthed.cypr                                                         │
  │    ess.spec.js                                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/caregivers/tests/e2e/1      01:02        4        4        -        -        - │
  │    010cg.cypress.spec.js                                                                       │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/debt-letters/tests/e2e       19ms        5        -        -        5        - │
  │    /debt-letters.cypress.spec.js                                                               │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/debt-letters/tests/e2e       21ms        7        -        -        7        - │
  │    /diary-codes-content.cypress.spec.j                                                         │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/debt-letters/tests/e2e       11ms        4        -        -        4        - │
  │    /diary-codes-next-step.cypress.spec                                                         │
  │    .js                                                                                         │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/disability-benefits/23      00:15        4        4        -        -        - │
  │    46/tests/mdot.cypress.spec.js                                                               │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/disability-benefits/68      01:01        3        3        -        -        - │
  │    6c-674/tests/e2e/686C-674-ancilliar                                                         │
  │    y.cypress.spec.js                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/disability-benefits/68      01:06        2        2        -        -        - │
  │    6c-674/tests/e2e/686C-674.cypress.s                                                         │
  │    pec.js                                                                                      │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/disability-benefits/99      00:08        2        2        -        -        - │
  │    6/tests/hlr.cypress.spec.js                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/disability-benefits/al      14:48        8        8        -        -        - │
  │    l-claims/tests/all-claims.cypress.s                                                         │
  │    pec.js                                                                                      │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/disability-benefits/vi      00:06        6        6        -        -        - │
  │    ew-payments/tests/e2e/view-payments                                                         │
  │    .cypress.spec.js                                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/edu-benefits/0994/test       11ms        1        -        -        1        - │
  │    s/e2e/edu-0994.cypress.spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/edu-benefits/10203/tes      00:19        2        2        -        -        - │
  │    ts/edu-10203.cypress.spec.js                                                                │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/edu-benefits/1990/test      00:24        1        1        -        -        - │
  │    s/e2e/edu-1990.cypress.spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/edu-benefits/1990e/tes      00:18        1        1        -        -        - │
  │    ts/e2e/edu-1990e.cypress.spec.js                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/edu-benefits/1990n/tes      00:15        1        1        -        -        - │
  │    ts/e2e/edu-1990n.cypress.spec.js                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/edu-benefits/1995/test      00:13        1        1        -        -        - │
  │    s/e2e/edu-1995.cypress.spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/edu-benefits/5490/test      00:25        1        1        -        -        - │
  │    s/e2e/edu-5490.cypress.spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/edu-benefits/5495/test      00:17        1        1        -        -        - │
  │    s/e2e/edu-5495.cypress.spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/facility-locator/tests      00:01        1        1        -        -        - │
  │    /e2e/accessibility.cypress.spec.js                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/facility-locator/tests      00:01        1        1        -        -        - │
  │    /e2e/ccpDisabled.cypress.spec.js                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/facility-locator/tests      00:02        2        2        -        -        - │
  │    /e2e/ccpEnabled.cypress.spec.js                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/facility-locator/tests      00:05        1        1        -        -        - │
  │    /e2e/gaEvents.cypress.spec.js                                                               │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  applications/facility-locator/tests      00:01        2        -        1        1        - │
  │    /e2e/mobile.cypress.spec.js                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/facility-locator/tests      00:25       10        9        -        1        - │
  │    /e2e/search.cypress.spec.js                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/financial-status-repor       14ms        1        -        -        1        - │
  │    t/tests/e2e/fsr-5655.cypress.spec.j                                                         │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/find-forms/tests/e2e/0      00:03        1        1        -        -        - │
  │    0-required.cypress.spec.js                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/gi/tests/e2e/00-requir      00:16        1        1        -        -        - │
  │    ed.cypress.spec.js                                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/gi/tests/e2e/02-profil      00:01        1        1        -        -        - │
  │    e-error.cypress.spec.js                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/gi/tests/e2e/03-vet-te      00:09        1        1        -        -        - │
  │    c.cypress.spec.js                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/gi/tests/e2e/04-dea.cy      00:11        1        1        -        -        - │
  │    press.spec.js                                                                               │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/gi/tests/e2e/05-ojt.cy      00:09        1        1        -        -        - │
  │    press.spec.js                                                                               │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/gi/tests/e2e/06-vet-te       18ms        1        -        -        1        - │
  │    c-mobile.cypress.spec.js                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/gi/tests/e2e/07-gibct-      00:05        1        1        -        -        - │
  │    mobile.cypress.spec.js                                                                      │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/hca/tests/hca.cypress.      01:04        3        3        -        -        - │
  │    spec.js                                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna      00:02        2        2        -        -        - │
  │    ire/list/tests/e2e/00.home.cypress.                                                         │
  │    spec.js                                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna      00:06        3        3        -        -        - │
  │    ire/list/tests/e2e/01.tabs.switch.c                                                         │
  │    ypress.spec.js                                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna       13ms        1        -        -        1        - │
  │    ire/list/tests/e2e/02.bread.crumbs.                                                         │
  │    cypress.spec.js                                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna      00:02        2        2        -        -        - │
  │    ire/questionnaire/tests/e2e/00.ques                                                         │
  │    tionnaire.loads.cypress.spec.js                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna      00:01        1        1        -        -        - │
  │    ire/questionnaire/tests/e2e/01.ques                                                         │
  │    tionnaire.demographics.address.cypr                                                         │
  │    ess.spec.js                                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna      00:01        1        1        -        -        - │
  │    ire/questionnaire/tests/e2e/01.ques                                                         │
  │    tionnaire.demographics.basicInforma                                                         │
  │    tion.cypress.spec.js                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna      00:01        1        1        -        -        - │
  │    ire/questionnaire/tests/e2e/01.ques                                                         │
  │    tionnaire.demographics.phoneNumbers                                                         │
  │    .cypress.spec.js                                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna      00:01        1        1        -        -        - │
  │    ire/questionnaire/tests/e2e/03.ques                                                         │
  │    tionnaire.landing.page.accessibilit                                                         │
  │    y.cypress.spec.js                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna      00:01        1        1        -        -        - │
  │    ire/questionnaire/tests/e2e/04.appo                                                         │
  │    intment.id.is.missing.cypress.spec.                                                         │
  │    js                                                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna      00:01        1        1        -        -        - │
  │    ire/questionnaire/tests/e2e/04.appo                                                         │
  │    intment.id.is.present.cypress.spec.                                                         │
  │    js                                                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/messages/tests/message      00:01        1        1        -        -        - │
  │    s.cypress.spec.js                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/dashbo      00:01        1        1        -        -        - │
  │    ard/tests/e2e/dashboard.all-widgets                                                         │
  │    .cypress.spec.js                                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/dashbo      00:01        1        1        -        -        - │
  │    ard/tests/e2e/dashboard.find-benefi                                                         │
  │    ts-empty.cypress.spec.js                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/dashbo      00:01        1        1        -        -        - │
  │    ard/tests/e2e/dashboard.find-benefi                                                         │
  │    ts-selected.cypress.spec.js                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/dashbo      00:06        6        6        -        -        - │
  │    ard/tests/e2e/dashboard.health-care                                                         │
  │    -widgets.cypress.spec.js                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/dashbo      00:01        1        1        -        -        - │
  │    ard/tests/e2e/dashboard.minimal-wid                                                         │
  │    gets.cypress.spec.js                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:05        1        1        -        -        - │
  │    e/tests/e2e/address-validation/bad-                                                         │
  │    unit.cypress.spec.js                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:04        1        1        -        -        - │
  │    e/tests/e2e/address-validation/conf                                                         │
  │    irm-address.cypress.spec.js                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:01        1        1        -        -        - │
  │    e/tests/e2e/address-validation/conf                                                         │
  │    irm-state-diff.cypress.spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:04        1        1        -        -        - │
  │    e/tests/e2e/address-validation/inte                                                         │
  │    rnational-address.cypress.spec.js                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:04        1        1        -        -        - │
  │    e/tests/e2e/address-validation/low-                                                         │
  │    confidence.cypress.spec.js                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:04        1        1        -        -        - │
  │    e/tests/e2e/address-validation/mili                                                         │
  │    tary-address.cypress.spec.js                                                                │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:04        1        1        -        -        - │
  │    e/tests/e2e/address-validation/miss                                                         │
  │    ing-unit.cypress.spec.js                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:05        1        1        -        -        - │
  │    e/tests/e2e/address-validation/one-                                                         │
  │    suggestion.cypress.spec.js                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:04        1        1        -        -        - │
  │    e/tests/e2e/address-validation/two-                                                         │
  │    suggestions.cypress.spec.js                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:04        1        1        -        -        - │
  │    e/tests/e2e/address-validation/vali                                                         │
  │    d-address.cypress.spec.js                                                                   │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:03        2        2        -        -        - │
  │    e/tests/e2e/profile.connected-apps.                                                         │
  │    cypress.spec.js                                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:05        2        2        -        -        - │
  │    e/tests/e2e/profile.cypress.spec.js                                                         │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:09        6        6        -        -        - │
  │    e/tests/e2e/profile.direct-deposit.                                                         │
  │    cypress.spec.js                                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:04        1        1        -        -        - │
  │    e/tests/e2e/profile.loa1.cypress.sp                                                         │
  │    ec.js                                                                                       │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:07        2        2        -        -        - │
  │    e/tests/e2e/profile.mpi-error.cypre                                                         │
  │    ss.spec.js                                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:05        2        2        -        -        - │
  │    e/tests/e2e/profile.not-in-mpi-erro                                                         │
  │    r.cypress.spec.js                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:01        1        1        -        -        - │
  │    e/tests/e2e/profile.personal-and-co                                                         │
  │    ntact-information-fields-check.cypr                                                         │
  │    ess.spec.js                                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:09        2        2        -        -        - │
  │    e/tests/e2e/profile.personal-and-co                                                         │
  │    ntact-information-modals.cypress.sp                                                         │
  │    ec.js                                                                                       │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:01        1        1        -        -        - │
  │    e/tests/e2e/profile.personal-and-co                                                         │
  │    ntact-information-vap-error.cypress                                                         │
  │    .spec.js                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:09        2        2        -        -        - │
  │    e/tests/e2e/profile.personal-and-co                                                         │
  │    ntact-mailing-address.cypress.spec.                                                         │
  │    js                                                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  applications/personalization/view-r      00:05        1        -        1        -        - │
  │    epresentative/tests/view-representa                                                         │
  │    tive.cypress.spec.js                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/static-pages/health-ca      00:02        3        3        -        -        - │
  │    re-manage-benefits/schedule-view-va                                                         │
  │    -appointments-page/tests/index.cypr                                                         │
  │    ess.spec.js                                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/vaos/tests/e2e/appoint      00:06        4        4        -        -        - │
  │    ment-list.cypress.spec.js                                                                   │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/vaos/tests/e2e/communi      00:10        1        1        -        -        - │
  │    ty-care.cypress.spec.js                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/vaos/tests/e2e/express      00:03        1        1        -        -        - │
  │    -care.cypress.spec.js                                                                       │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/vaos/tests/e2e/va-appo       12ms        3        -        -        3        - │
  │    intment.cypress.spec.js                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/vaos/tests/e2e/va-requ      00:11        3        3        -        -        - │
  │    est.cypress.spec.js                                                                         │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/vre/28-1900/tests/e2e/       97ms        1        -        -        1        - │
  │    authenticated.cypress.spec.js                                                               │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/vre/28-1900/tests/e2e/       66ms        1        -        -        1        - │
  │    unauthenticated.cypress.spec.js                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/vre/28-8832/tests/e2e/      00:12        1        1        -        -        - │
  │    dependent-workflow.cypress.spec.js                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/vre/28-8832/tests/e2e/      00:10        1        1        -        -        - │
  │    veteran-workflow-not-logged-in.cypr                                                         │
  │    ess.spec.js                                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  platform/site-wide/side-nav/tests/e      00:01        1        1        -        -        - │
  │    2e/sideNav.cypress.spec.js                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  site/layouts/tests/vamc/smoke.mobil      00:01        1        1        -        -        - │
  │    e.cypress.spec.js                                                                           │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  2 of 85 failed (2%)                      26:48      164      132        2       30        -  
```

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by 1Copenut — APPROVED** [review]
LGTM!

**Review by micahchiang — APPROVED** [review]

**Pull request merged**
