### PR TITLE
Add DoD ID to Veteran Status Card

### PR DESCRIPTION
**Pull request by nicksayre**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- Added DoD ID to the Veteran Status Card, removed unnecessary date of birth info. Also adjusted the spacing/positioning in the layout a bit to match the given design.
- Did this by updating the PDF template, and by passing the appropriate data to it.
- I work for VA IIR. Currently we're the caretakers of this application.

## Related issue(s)

- Closes [#673](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/673)
- Follows on from the research gleaned from [#745](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/745)

## Testing done

- Added test to check the PDF for the presence of the DoD ID, and one to test that it doesn't appear when the appropriate data doesn't exist.
- Removed a test checking for date of birth
- To run tests to `yarn test:unit src/platform/pdf/test/templates/veteran_status/veteran_status.unit.spec.js`

## Screenshots

Note: increased the length of the surname to make sure all the info fits on the card even when the name wraps to the next line.
card

## What areas of the site does it impact?

This change only affects only the card downloaded from Profile -> Military information (https://www.va.gov/profile/military-information).

## Acceptance criteria

- [ ] DoD ID appears on the card
- [ ] Tests pass

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by nicksayre** [comment]
There is a linting warning on line 115 of `ProofOfVeteranStatus.jsx` that is mutually exclusive with a prettier warning. Linter wants parens around multi-line JSX but prettier does not. Prettier blocks commits, though, so I'm going with it, and ignoring the linter warning.

**Comment by nicksayre** [comment]
There's a linter warning about a dependency cycle in `src/platform/user/profile/utilities/index.js`. Although this PR did touch this file, it didn't change any imports, so if there is indeed a dependency loop, and it can be shown to be causing a problem, that should be handled in another ticket.

**Review by asiisii — COMMENTED** [review]
what will the veteran status card look like if there's no or an unknown DoD ID number?

**Comment by nicksayre** [comment]
> what will the veteran status card look like if there's no or an unknown DoD ID number?

When the DoD ID Number is not available, we don't show its heading or content. Thanks for asking this. When I went to double-check it, I found an issue with the layout in this case, and I fixed it.
Screenshot 2024-07-09 at 10 13 51 PM

**Review by asiisii — DISMISSED** [review]
LGTM 🚀

**Review by khenson-oddball — DISMISSED** [review]
👍

**Review by khenson-oddball — APPROVED** [review]
LGTM

**Review by IGallupSoCo — APPROVED** [review]
LGTM

**Review by asiisii — APPROVED** [review]

**Pull request merged**
