### PR TITLE
[1995 STEM] Remove STEM question condition

### PR DESCRIPTION
**Pull request by devin-mccurdy**
## Description
Remove all conditions from the stem page

## Testing done
Tested locally and passes QA process

## Screenshots
image

## Acceptance criteria
- [x] Stem page is always displayed

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by zurbergram — APPROVED** [review]
LGTM

**Review by delli-gatti-michael — APPROVED** [review]
Testing Passes

**Comment by dmccurdybah** [comment]
@department-of-veterans-affairs/backend-review-group Could I get a code review on this at your earliest convenience. Thank you!

**Comment by dmccurdybah** [comment]
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!

**Review by rianfowler — APPROVED** [review]

**Pull request merged**
