### PR TITLE
526 Chapter 4 Copy Edit

### PR DESCRIPTION
**Pull request by cvalarida**
image

### CODE REVIEW

**Review by cehsu — APPROVED** [review]
LGTM pending @peggygannon's approval. (Is there a ticket to reference for this work?)

**Review by peggygannon — COMMENTED** [review]
@cvalarida Hi, Chris.. looks good. Can I see the screenshot for the message that will appear if a user selects No?

**Comment by cvalarida** [comment]
@peggygannon:
image

**Comment by peggygannon** [comment]
@cvalarida looks good!

**Pull request merged**
