### PR TITLE
Updated contentions list and ordered list by codes

### PR DESCRIPTION
**Pull request by ndsprinkle**
## Description
The contentions/disabilities list has been updated based on the provided excel document in the linked issue. The list was also updated to be ordered by code in the few places that codes were out of place in addition to removing a couple duplicates.

## Acceptance criteria
- [ ] Contentions list has been updated with provided excel document

### CODE REVIEW

**Review by smoonpeyes — COMMENTED** [review]
Looks good! The only thing I noticed is that "Addison's disease" is in double-quotes while all of the other contentions are in single quotes. Not sure if that matters.

**Comment by ndsprinkle** [comment]
@smoonpeyes  Good catch, most of these contentions are using single quotes, but there are some that use double quotes because the string actually contains a single quote in it. For example: athlete's foot has a single quote in it so it has to be double quoted. I actually had used back ticks in my original commit, so I have now changed that to be double quotes to match the others.

**Review by Mottie — COMMENTED** [review]
I didn't see this entry in the spreadsheet, but it was in the file. Should it be removed?

`109: '2010 Presumptive Herbicide Condition',`

In both the spreadsheet and in this file, this entry doesn't have a space after the comma. Does it need to be changed?

`6110: 'sarcoma,soft-tissue-malignant giant cell tumor/tendon sheath',`

**Comment by ndsprinkle** [comment]
@Mottie I also wondered about 109 (and there may have been another one too) but after talking with Mark Greenburg it sounds like I should leave in all old ones even if they are expired.

Another good question about 6110, I guess we should keep things identical to the spreadsheet, but I can't imagine it would matter if we put a space to make things pretty since I think only the code ultimately matters.

When I create the real PR for this, I'll run both of those questions by the FE review team.

**Review by Mottie — APPROVED** [review]

**Review by rianfowler — APPROVED** [review]

**Comment by ndsprinkle** [comment]
I just pushed another commit that removes code 109 from the list: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1206 Should this have been a separate PR since it is a separate issue? Or is combining the issues into this one very related PR okay?

**Comment by rianfowler** [comment]
You're good- we generally prefer no major changes _logic_ after approval but I think it's fine for configurations and static content changes.

**Comment by ndsprinkle** [comment]
@rianfowler Okay cool, thanks for letting me know. Do you know why the jenkins check hasn't completed yet? It's like this on my other PR too. Is there something that I need to be doing to get it to finish?

**Pull request merged**
