### PR TITLE
[FSR] Updating survey text & adding to production

### PR DESCRIPTION
**Pull request by Dr-Pongo**
## Summary
Updating end of form survey text, and adding production number and removing the production check to hide the button.

Production form number `43`
Staging form number `41`

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#72105
- _Link to previous change of the code/bug (if applicable)_
department-of-veterans-affairs/vets-website#27338
- _Link to previous change of the code/bug (if applicable)_
department-of-veterans-affairs/vets-website#27420

## Testing done
Has been tested on staging

### Confirmation page alert
| Form version | Before | After | 
| -------- | -------- | -------- |
| Full FSR | image | image |
| Streamlined | image | image |

## What areas of the site does it impact?
FSR
*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Review by OptionSelect — DISMISSED** [review]
LGTM! 🚀

**Review by amponce — DISMISSED** [review]
LGTM :shipit:

**Review by CBonade — DISMISSED** [review]

**Review by OptionSelect — APPROVED** [review]
LGTM! 🚀

**Review by aubreyarcangel — APPROVED** [review]
Looks good.

**Pull request merged**
