### PR TITLE
Content/wip/camp-lejeune-update

### PR DESCRIPTION
**Pull request by bethpotts**
I've replaced the whole camp lejeune page here with this updated version that incorporates plain-language reworking of the page as well as SME updates and changes because of the camp lejeune final rule (AP66) to be published Friday, 1/13.

### CODE REVIEW

**Comment by bethpotts** [comment]
@rroueche Please wait to merge this until we know if there will be any further changes needed. I'm waiting to hear back from Jennifer Rudisill tomorrow on that.

**Comment by rroueche** [comment]
@bethpotts understood, I'll wait to review and merge until I get the green light from you.

**Comment by bethpotts** [comment]
@rroueche Ready to merge and push to production! Thanks so much.

**Comment by rroueche** [comment]
Great, thanks @bethpotts ! I'll merge to master here in a second, and then will work with @crwallace and @aub to push to production to have it live around 11 AM ET.

**Review by rroueche — APPROVED** [review]

**Pull request merged**
