### PR TITLE
Updating Veterans Crisis Line functionality.

### LINKED ISSUE #2473: Remove vets-app class from links in footer.
Related to #2467

### LINKED ISSUE #2475: Change .footer a into something a bit more targeted and granular
Related to / affects work in #2467

### LINKED ISSUE #2476: Simplify .footer ul.final-list selector in _va.scss

### PR DESCRIPTION
**Pull request by webinista**
- Moved .footer-crisis styles to a partial
- Renamed .footer-crisis to .va-crisis
- Added va-crisis--touch / va-crisis--notouch class names
- Changed div element to an a for crisis line buttons
- Removed vets-app class from footer links (closes #2473)
- Reformatted .footer block for readability
- Removed .footer a.contact, .footer a.blog. Unnecessary.
- Simplified .footer .footer-logo a, .footer .footer-seal to be .footer-logo a and footer-seal
- Removed unused .footer span.source, .footer blockquote, and .footer .post-script blocks
- Removed a margin from .footer ul
- Added .va-list--linkgroup class / pattern
- Removed .footer dl, .footer dt, .footer dd, and .footer li blocks
- Added .va-list--linkgroup-title class to replace .footer dt
- Added .va-list--linkgroup--inline to replace .footer ul.final-list (closes #2476)
- Changed mobile crisis line trigger to an a element.
- Eliminated .footer a block in favor of va-list--linkgroup(--inline) a blocks (closes #2475)
- Added a .va-overlay-body class.
- Adding close button SVG

### CODE REVIEW

**Comment by gnakm** [comment]
@webinista This is amazing! 

Comments for **Desktop**

The yellow bar is supposed to be anchored to the bottom of the page. Currently, it is a sticky. Would you help us have it fixed at the bottom?

Font size changes
- Get help from Veterans Crisis Line = **1.7rem**
- Call 1-800-273-8255 (press1) = **1.7rem**
- Text 838255 = **1.7rem**
- Chat confidentially now = **1.7rem**
- If you are in a crisis.... = **1.4rem**

Could we have 'Chat confidentially now' in #0071bc and underlined hyperlink, and have it hover the way it does with the rest of the links throughout the site?

screen shot 2016-06-15 at 3 47 29 pm

Could we add a little more padding (+1rem) above the Call 1-800-273-8255 (press 1) text?

Make padding for 'Get Help from Veterans Crisis Line' and 'If you are in crisis or having thoughts of suicide...' **2.5 rem**

Comments for **Mobile**

Right now on the iphone 5c, the Get Help from Veterans Crisis Line and the X are overlapping. 

I think what would help is to have the Get Help from Veterans Crisis Line text moved more towards the left (so less padding on the left). The Get Help from Veterans Crisis Line text and "If you're in a crisis and having thoughts..." lines should be aligned. 

screen shot 2016-06-15 at 4 10 38 pm

**Comment by webinista** [comment]
@gnakm Ready for a second look.

**Comment by gnakm** [comment]
Desktop:

Could we get the popup to align with the Popular on Vets.gov header line?
screen shot 2016-06-20 at 5 32 19 pm

Could we add more padding above the Call Number so that it's equidistant to the Text number?
screen shot 2016-06-20 at 5 32 04 pm

The "If you are in crisis" text needs to be left padding 2.5rem (so that text looks more centered).

Mobile:

This is so ghetto but in my defense I cannot get screenshots to work on these tiny phones. 

This is a new problem and needs a design change.


New Solution? 
screen shot 2016-06-20 at 6 07 04 pm
Font awesome (fa-times-circle) (&#xf057;) in primary darkest (and white). 


New add on:
When a Veteran clicks text, could we pre-populate the text box to say "I need help," so that Veterans have something to send over?

**Comment by webinista** [comment]
@gnakm When you're done reviewing, can you be sure to make me the assignee? Otherwise tasks get lost in the shuffle.

**Comment by webinista** [comment]
> Could we remove the blue focus around the yellow bar?

Keyboard users need to be able to determine which link or button their keyboard is focused on. I **DO NOT** recommend removing the indicator for two reasons:

1. A fuzzy blue box shadow is the standard `:focus` style across Vets.gov.
2. Removing the focus style would be an accessibility no-no, and something we'd have to fix at some point to meet 508 compliance standards.

If we remove the blue focus indicator, we should replace it with another `:focus` style. But that means we'll have inconsistent behavior for this one element.

**Comment by webinista** [comment]
@gnakm How about doing using the design of the search modal here? 

screen shot 2016-06-20 at 5 50 50 pm

There are a couple of advantages of doing it this way:

1. Consistency for the user. Our modals work the same way every time.
2. Clarity for the user. "Close" is easier to understand than ×.
3. Less CSS to write and manage because it re-uses what's already there.

**Comment by gnakm** [comment]
@webinista Thanks for assigning back.

1. Okay totally agree on the focus. Thanks for pointing 508 out. 
2. Design of the search modal may not be the best because it's really easy to miss. Since the options on this modal was listed in a certain order, what if we had close button at the bottom? 
screen shot 2016-06-21 at 1 16 47 pm

**Comment by webinista** [comment]
Done.

**Comment by gnakm** [comment]
This looks amazing @webinista!
One last detail that I mentioned yesterday -- would it be possible to have "I need help" in a text box? Some of us had a discussion yesterday on how maybe Veterans may need a prompt or starting point to a conversation. 

screenshot_20160621-225620_720

cc @maryannbrody @crwallace

**Comment by webinista** [comment]
@gnakm We can try it. I'm not sure how tell it works across mobile OSes though.

**Comment by webinista** [comment]
@gnakm This will not work for iPhones, based on [Apple's documentation](https://developer.apple.com/library/ios/featuredarticles/iPhoneURLScheme_Reference/SMSLinks/SMSLinks.html). Tests on my phone suggest that it doesn't work on Android either.

**Comment by gnakm** [comment]
@webinista Thanks for checking in on that. It looks great otherwise! Thank you for doing this. Merging now.

**Pull request merged**
