### PR TITLE
add relative file paths from manifest to app list

### PR DESCRIPTION
**Pull request by CBonade**
## Description
This PR adds the file paths to the app list that's generated off our manifests. This will allow us to link the manifests to the appropriate test results by the path of the spec and allow us to proceed with our dashboarding efforts.

## Testing done
App list generates and has appropriate properties in CI.

## Acceptance criteria
- [x] App list generates and has appropriate filepath added to each application.

### CODE REVIEW

**Review by timwright12 — CHANGES_REQUESTED** [review]
needs review

**Comment by timwright12** [comment]
@CBonade is this PR to add absolute paths to this file? https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/file-manifest.json

**Comment by CBonade** [comment]
> @CBonade is this PR to add absolute paths to this file? https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/file-manifest.json

Nope! This is a separate app list we generated for stuff to do with testing results, we just piggyback off the function you all were using to get a list of the manifests and associated data. I don't believe anything else uses this list other than our testing results processing for dashboards (I wrote it fresh for that purpose)

**Comment by timwright12** [comment]
ok wonderful thank you!

**Review by timwright12 — APPROVED** [review]

**Pull request merged**
