### PR TITLE
526 ITF React

### PR DESCRIPTION
**Pull request by cehsu**
These changes set up the disability increase compensation ITF React components and have been split out of #7672 (in which the content was already approved as well).

image

The prestart message has been added to several form pages, but adding it to others requires additional work, which is captured in these tickets:

- [ ] [Fix PrestartAlert spacing above non-arrayfields](https://github.com/department-of-veterans-affairs/vets-website/issues/7822)
- [ ] [Display ITF alert on veteran information page](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10891)
- [ ] [Display ITF message on review page](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10892)

Original ticket is available at department-of-veterans-affairs/vets.gov-team#10113

### CODE REVIEW

**Comment by cehsu** [comment]
@peggygannon thanks for already taking a look at these ITF messages. We've decided to split these changes into multiple PRs. Here are the screenshots again if you'd like to take another look/provide additional feedback.

Pending
image

Created
 image

Retrieved
 image

Renewed
image

Error: not retrieved for a returning user
image

Error: not retrieved for a new user
image

Error: not created
image

Error: not renewed
image

**Comment by peggygannon** [comment]
@cehsu Thanks, Claire. Here is my feedback on the one that need a tweak:
 
for the messages that provide a date, 
--Can we spell out April? I believe I had this month spelled out in my month list?

**Comment by cehsu** [comment]
Thanks @peggygannon, good catch, it looks like these month abbreviations are being set differently in multiple places across the site, a [ticket](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11210) has been set up to make our use of month abbreviations consistent.

**Comment by cehsu** [comment]
Closing this for now, since it's not needed for user testing.

**Comment by cehsu** [comment]
@peggygannon @goldenmeanie please refer to this updated screenshot for the content change discussed in https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10954#issuecomment-398853298.
image

**Pull request closed without merging**
