### PR TITLE
Migrate letters app to use accordion web component

### PR DESCRIPTION
**Pull request by bkjohnson**
## Description

Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/32872

The `<va-accordion>` migration can't be handled by the script, so it will need to be done manually. This was an old PR that I used for testing, but I've merged in master, updated the tests, and verified locally that it still works.

### Benefits

By removing `<CollapsiblePanel>` we no longer have the problematic smooth scroll to the opened item. Additionally, the accordion item headers are _actually_ headers, so this semantic document structure will benefit screen reader users.

## Testing done

Local browser testing :eyes: 

I modified the api mock:

<details>
<summary>Mock API response</summary>

image

</details>

### With `<CollapsiblePanel>`

Peek 2021-06-10 17-52

### With `<va-accordion>`

Peek 2021-06-10 19-18

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by Mottie** [comment]
Thank for your hard work! I checked this locally and noticed the "Service Verification" content includes a horizontal scrollbar. I think it might be from the warning alert inside? Is there anything we can do about this?

Screen Shot 2021-12-17 at 9 15 59 AM

Also, the font appears to be a bit smaller with less padding. I'll run that by our design team.

**Comment by bkjohnson** [comment]
I think we could make an update to the component so that it has these two overflow properties in its CSS:

image

**Comment by Mottie** [comment]
I think `overflow-x: clip` does the same as `hidden`, maybe adding `word-break: break-word;` would be better?

**Comment by bkjohnson** [comment]
That didn't seem to work :/. I think I'm going to pause this PR and write a ticket for us to investigate & fix the horizontal scrolling issue.

**Comment by bkjohnson** [comment]
Issue written: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/602

**Pull request closed without merging**
