### PR TITLE
Add letters navigation

### PR DESCRIPTION
**Pull request by cvalarida**
image

Fun fact: I can't really tell the `a:visited` color is different than the `a` color. I only just noticed in the above screenshot.

### CODE REVIEW

**Review by rroueche — APPROVED** [review]
perf

**Review by annekainicUSDS — APPROVED** [review]
LGTM!

**Comment by djmunoz1** [comment]
Update: the nav has changed since this PR was created. Per Mikki: The link should now be placed as the bottom option in the Request Your Records menu.   Titled "Download Your VA Benefit Letters".

**Comment by cvalarida** [comment]
Closing this because the nav structure has changed and @egarreau is working on it.

**Pull request closed without merging**
