### PR TITLE
9860 experimental design change

### LINKED ISSUE #315: sitewide, forms 508-defect-2 [AXE-CORE, SEMANTIC MARKUP, COGNITION]: Email inputs MUST be paired with labels
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

```diff
! Team impacted: VSA BAM2; Project: MDOT MVP
```

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

On the 1 of 3 Veteran information screen, there are text inputs for email addresses. At present, the label that says "Email address" is in a `<p>`, but must be in a `<label>` with a for attribute whose value matches the id of the input field. Additionally, h4 is not valid HTML as child of element label in this context.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

~~As a mouse user, I want to be able to select the label of an input to move focus into the input.~~

As a user with cognitive considerations, I expect to see a label and input pairing consistently styled as throughout the rest of the site, with the label just above the text/email/search input or to the right of a radio/checkbox input, so that I am clearly able to understand what entry is expected.

## Environment

* Operating System: all
* Browser: 
* Server destination: staging

## Steps to Recreate

1. Enter ~~https://staging.va.gov/hearing-aid-batteries-and-accessories/veteran-information/addresses~~ NEW URL: https://staging.va.gov/health-care/order-hearing-aid-batteries-and-accessories/ while logged in as user 1 in browser
2. Inspect the Email address code
3. Verify that the code appears as below in the "Current code"

### Current code
```diff
<div class="schemaform-field-template vads-u-margin-bottom--3 schemaform-first-field">
- <label id="root_email-label" class="schemaform-label" for="root_email">
    <h4>Email address</h4>
  </label>
  <p>We will send an order confirmation email with a tracking number to this email address.</p>
- <p class="vads-u-margin-bottom--1">Email address</p>
  <div class="schemaform-widget-wrapper">
-   <input type="email" id="root_email" name="root_email" maxlength="80" class="va-input-large" value="">
  </div>
  <div></div>
</div>
```

### Recommended code
```diff
<div class="schemaform-field-template vads-u-margin-bottom--3 schemaform-first-field">

  <h4>Email address</h4>

  <p>We will send an order confirmation email with a tracking number to this email address.</p>

+ <label id="root_email" class="schemaform-label" for="root_email">Email address</label>
+ <input id="root_email" type="email" name="root_email" maxlength="80" class="va-input-large"/>
</div>
```

## WCAG or Vendor Guidance (optional)

* [W3C Labeling Controls](https://www.w3.org/WAI/tutorials/forms/labels/)

* [MDN Basic Form Hints](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/forms/Basic_form_hints) - "Note that each `<input>` element has an id, and each `<label>` element has a for attribute, indicating the id of the associated `<input>`.

## Screenshots or Trace Logs

Screen Shot 2020-06-04 at 5 12 54 PM

### PR DESCRIPTION
**Pull request by bkjohnson**
## Description

This is a design change to the forms library to help close department-of-veterans-affairs/va-forms-system-core#315

This PR allows an optional `'ui:header'` property (which is a React component) to be rendered above the `label` in our `<FieldTemplate>`. It is important for this `<h4>` and `<p>` tag to not come between the label and the input, but currently the forms library doesn't support that kind of design.

## Testing done

manual

## Screenshots

image

## Acceptance criteria
- [ ] As a user, I want a label to be presented directly next to the associated input consistently throughout a form, so I may easily understand and complete the form.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by jenstrickland** [comment]
@bkjohnson Just checking here, is the goal of this pull request to ensure that an input's label will only be right next to the associated input, and not separated by a heading or paragraph?

The current forms library implementation allowed the h4 above to be the input's label, and allowed a paragraph to also separate the label and input. It was confusing because an input's label isn't a heading elsewhere, and it is a UX convention that labels are next to the associated input. As our users have a greater incidence of cognitive considerations, consistency is valued.

The goal here is to make sure labels are always next to the input, and always styled as a label (never as a heading).

The only exception is that sometimes there may be a "Learn more about ####" link to show additional info inside the form label (https://github.com/department-of-veterans-affairs/va.gov-team/issues/1817).

**Comment by bkjohnson** [comment]
> is the goal of this pull request to ensure that an input's label will only be right next to the associated input, and not separated by a heading or paragraph?

Partially. Even with this PR, it is still possible for the "description" to come between the label and the input, but moving/removing that is a change that would have a much larger impact beyond form 2346. But, as long as there isn't a "description", then no other elements will be between the label and the input.

**Comment by jenstrickland** [comment]
Is the "description" optional? (So I can tell VSA teams not to use it 😁 )

**Comment by bkjohnson** [comment]
Yes, the description is completely optional. However, what we have been seeing with this issue involves how the description is used on each _field_. A description can also be given to a page, and I'm not aware of that causing any problems. Here is an example:

image

And the "description" for this page is:

```html
  <span>
    <span>VET TEC focuses on 5 areas of high-tech training:</span>
    <ul>
      <li>Computer programming</li>
      <li>Data processing</li>
      <li>Computer software</li>
      <li>Information science</li>
      <li>Media application</li>
    </ul>
  </span>
```

**Comment by jenstrickland** [comment]
@bkjohnson That implementation is interesting. It's good that it maintains labels directly next to their associated inputs, and doesn't insert any description in between. 

Curious about the `span` instead of `p`.

**Review by 1Copenut — APPROVED** [review]
LGTM. I'm unable to test it locally, but have confidence in the fix. We can re-test in staging when ready.

**Comment by rianfowler** [comment]
Can we move this into a DRAFT state or do we need to work on getting all of these approvals?

**Pull request closed without merging**
