### PR TITLE
Update links for V1 526 to point to V2

### PR DESCRIPTION
**Pull request by bshyong**
## Description
Updates links for V1 526 to point to V2

## Acceptance criteria
- [x] Resolves https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17204

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by markgreenburg — APPROVED** [review]
LGTM

**Comment by markgreenburg** [comment]
@bshyong are you also working on updating links in static content in the `vagov-content` repo?

**Comment by bshyong** [comment]
Yep

**Comment by bshyong** [comment]
Content repo PR here https://github.com/department-of-veterans-affairs/vagov-content/pull/306

**Pull request merged**
