### PR TITLE
Prevent use of @extend in SCSS.

### PR DESCRIPTION
**Pull request by ghost**
Closes department-of-veterans-affairs/vets.gov-team#1903

  - Upgraded sass-lint to 1.10.2

Other changes to sass-lint configuration

  - Add verbose, no-exit options so that linter displays errors
  - Enforce double quotes for strings
    - Updated SCSS files to use double quotes instead of single quotes
  - Modified mixin rule to allow use of some mixins before declarations
  - Updated SCSS files to use double quotes instead of single quotes
  - Disallow color literals
    - Consolidated colors and added variables to account for one-offs
  - Disallow trailing white space (and removed trailing white space)
  - Enforce space after colon (and added spaces after colons)
  - Disallow space before colon

### CODE REVIEW

**Comment by jcmeloni-usds** [comment]
Lots of good collaboration here -- @raquelromano-gov @rroueche @U-DON @tiffanybbrown-va are you waiting on any other contributions before merging?

**Comment by rroueche** [comment]
I have not, but this is the first time I've heard of these updates, so take that with a grain of salt :) I'm creating a heroku build for this PR now so I can help check through the colors and stuff (if that's helpful).

**Comment by rroueche** [comment]
Did a quick spot check: fonts, colors, and buttons look good to me!

**Comment by jcmeloni-usds** [comment]
Let's merge it!

**Pull request merged**
