### PR TITLE
Profile: Add E2E tests

### PR DESCRIPTION
**Pull request by ncksllvn**
(reopened after updating Nightwatch Babel)

Resolves department-of-veterans-affairs/vets.gov-team/issues/10735

### CODE REVIEW

**Review by bshyong — APPROVED** [review]

**Comment by ncksllvn** [comment]
@wyattwalter @jbalboni Do you know how to get Jenkins to check out after updating the Nightwatch/Babel version? 

```
There was an error while starting the test runner:

ReferenceError: regeneratorRuntime is not defined
    at /application/src/applications/personalization/va-profile/tests/e2e/index.e2e.spec.js:4:32
    at Object.<anonymous> (/application/src/applications/personalization/va-profile/tests/e2e/index.e2e.spec.js:78:2)
    at Module._compile (module.js:652:30)
    at loader (/application/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/application/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

**Comment by wyattwalter** [comment]
@ncksllvn What do you mean by check out?

**Comment by ncksllvn** [comment]
I think that error refers to an E2E test that requires a later version of Node being executed with an old. Not sure if there’s like a caching involved with Jenkins or something.

**Comment by wyattwalter** [comment]
Ah, of course. It does look like the container image is being cached which I didn't think should be the case but obviously is happening.

The container image is named after the branch, so you could re-re-open (😄) this PR with a different branch name to pick up a different container name as a quick path to resolution. I can take a look at why this is caching where I didn't expect, but likely won't get to it anymore today.

```[_vets-website_profile-e2e-2-J7EQVZGXV2Y6GFEPMAXNFORF2JTVX2X4IKSNAKORAXX4PQAY7OCA] Running shell script

+ docker build -t vets-website:jenkins-testing-vets-website-profile-e2e-2-1 .

Sending build context to Docker daemon  270.7MB


Step 1/8 : FROM node:8

 ---> ff2509c12bff

Step 2/8 : RUN groupadd --gid 504 jenkins   && useradd --uid 504 --gid jenkins --shell /bin/bash --create-home jenkins

 ---> Using cache

 ---> 0f3a94556403

Step 3/8 : ENV YARN_VERSION 1.5.1

 ---> Using cache

 ---> 195d080b27ab

Step 4/8 : ENV NODE_ENV production

 ---> Using cache

 ---> b9723f63a84d

Step 5/8 : RUN apt-get update && apt-get install -y netcat   && npm install -g yarn@$YARN_VERSION   && npm install -g nsp   && npm install -g s3-cli   && npm install -g codeclimate-test-reporter   && chmod +x /usr/local/lib/node_modules/yarn/bin/yarn.js

 ---> Using cache

 ---> ad88a4ad7319

Step 6/8 : RUN mkdir -p /application

 ---> Using cache

 ---> ffbed08ae647

Step 7/8 : WORKDIR /application

 ---> Using cache

 ---> 5364104ddaf1

Step 8/8 : USER jenkins

 ---> Using cache

 ---> 186b876f62c2

Successfully built 186b876f62c2

Successfully tagged vets-website:jenkins-testing-vets-website-profile-e2e-2-1
```

**Comment by wyattwalter** [comment]
Oops! Just looked at the Jenkinsfile again before closing this tab.. The packages are being installed during the Jenkins run, not at Docker container build time 🤔

**Comment by ncksllvn** [comment]
@wyattwalter Yeah that was my thinking when I closed the old PR and opened this one but no luck. Hm any other ideas? I'm drawing a blank at the moment.

**Comment by ncksllvn** [comment]
Closing, as the work here will be integrated into the Profile 360 E2E tests and reopened in another PR.

**Pull request closed without merging**
