### PR TITLE
17766 dashboard style guide changes loa1

### PR DESCRIPTION
**Pull request by tlei123**
## Description
[17766](/department-of-veterans-affairs/vets.gov-team/issues/17766) - Change Dashboard content per Style Guide changes.  See [changes doc](/department-of-veterans-affairs/vets.gov-team/files/3040551/Dashboard-LOA1_Content.updates_Feb.2019.docx) for details.

## Testing done
Ran yarn test:unit:personalization and all passed.
No logic or functional code changes.

## Acceptance criteria
- [ ] All content changes made per [changes doc](/department-of-veterans-affairs/vets.gov-team/files/3040551/Dashboard-LOA1_Content.updates_Feb.2019.docx).

## Definition of done
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by tlei123** [comment]
Sorry for the noisy commit-history!

All my own commits in this branch have messages starting with ticket# ("17766 - ...").

**Comment by erikphansen** [comment]
LGTM, just got a broken unit test.

**Comment by tlei123** [comment]
Unit test fixed...

Now just failing on some "site-map.." integration tests.

Watching master now to merge once I see new commit(s) that might fix those.

**Comment by tlei123** [comment]
@erikphansen , ready for your re-review; unit-test fixed & all checks passed.  thx!

**Review by erikphansen — APPROVED** [review]

**Pull request merged**
