### PR TITLE
Add breadcrumbs and gatePage property to sign-in pages

### PR DESCRIPTION
**Pull request by ghost**
Closes department-of-veterans-affairs/vets.gov-team#735

- Adds breadcrumbs to sign-in pages when gatePage is true.
- Updated healthcare/messaging, healthcare/prescriptions, disability-benefits/track-claims

Updated hard-coded gray variables to closest USWDS colors.

 - Closes department-of-veterans-affairs/vets.gov-team#597
 - Updated build.js with comment to clarify how redirects are managed.

### CODE REVIEW

**Comment by jcmeloni-usds** [comment]
@tiffanybbrown-va you have the build fail message or do you need a hand from someone?

**Comment by tiffanybbrown-va** [comment]
@jcmeloni-usds I have the build message. Now I'm trying to figure out what's going wrong.

**Comment by jcmeloni-usds** [comment]
@tiffanybbrown-va cool! (well, depending on  your perspective....)

**Comment by tiffanybbrown-va** [comment]
Stared at the error until it made sense and it finally does. Need to go back to the drawing board on this one for a bit.

**Comment by jcmeloni-usds** [comment]
@tiffanybbrown-va sounds good (well, actually sounds frustrating, but you know what I mean)

**Comment by jcmeloni-usds** [comment]
LGTM! I tested the breadcrumbs. Merging!

**Pull request merged**
