### PR TITLE
[WIP] education plain language update

### PR DESCRIPTION
**Pull request by rroueche**
Creating new PR for education PL updates for the branch with the new naming convention. To replace PR #4000.

### CODE REVIEW

**Comment by jkassemi** [comment]
Fixed Jenkins CI in https://github.com/department-of-veterans-affairs/vets-website/pull/4705. Should run properly after master merge once in place.

**Comment by jcmeloni-usds** [comment]
@rroueche See @jkassemi's note above

**Comment by rroueche** [comment]
@jkassemi looks like the schema file is conflicting here - could you help resolve?

**Comment by jcmeloni-usds** [comment]
@rroueche @jkassemi How's the resolution going?

**Comment by rroueche** [comment]
@jcmeloni schema issue is resolved, but this is a long term content PR that is still in review and iteration phases, so we likely will not merge for another couple of weeks or so.

**Comment by bethpotts** [comment]
At last we heard back from SMEs with their changes to a couple pages. We can work toward incorporating those next week. @rroueche Let's decide when we want to schedule these pages to roll to production.

**Comment by bethpotts** [comment]
@rroueche Can you kick start this again so I can preview? Thanks!

**Comment by rroueche** [comment]
@bethpotts  yes! so sorry, just did it.

also - I see that there was likely an error in the last commit. lmk if you'd like to screenshare so I can show you how to see what was changed, and thus narrow down where to look for the error!

**Comment by ayaleloehr** [comment]
Can you update status here @rroueche ?

**Comment by rroueche** [comment]
Blocked my SMEs who want more time to review. planning to launch next Friday instead, 4/14.

**Pull request merged**
