### PR TITLE
Change HP 3rd link and update login text

### PR DESCRIPTION
**Pull request by earthboundkid**
DO NOT MERGE. This should not go live until Feb. 3 when the feature is rolled out. Opening it early just to get the review out of the way.

Refs. https://github.com/department-of-veterans-affairs/vets.gov-team/issues/759 and https://github.com/department-of-veterans-affairs/vets.gov-team/issues/807

screen shot 2017-01-23 at 6 03 29 pm
screen shot 2017-01-24 at 11 13 29 am
screen shot 2017-01-24 at 11 13 36 am

### CODE REVIEW

**Comment by jcmeloni-usds** [comment]
LGTM now and will probably still LGTM on 3 Feb. :)

**Comment by crwallace** [comment]
Everything on the new homepage link looks great. I would like for @melwoodard and @AnitraAppa to take a look at the new copy on the login screen since they wrote the previous copy.

**Comment by melwoodard** [comment]
LGTM!

**Comment by AnitraAppa** [comment]
One catch -- from https://github.com/department-of-veterans-affairs/vets.gov-team/issues/759#issuecomment-276464636 it looks like we removed "VR&E" from the last bullet in case it's removed from scope. Unless there have been any updates since then, I think the last bullet should be:
"- Check the status of a disability or pension claim."

**Comment by austin-martinez** [comment]
@AnitraAppa The screenshot with that bullet point is out of date. VR&E has been removed. 
https://github.com/department-of-veterans-affairs/vets-website/pull/4739/files#diff-bfd9dbb0438611bdffc450ccad344895R106
Merging for release tomorrow

**Pull request merged**
