### PR TITLE
77683 Cancelation Redesign - Request Details Page

### PR DESCRIPTION
**Pull request by vbahinwillit**
## Summary
This PR implements the cancelation redesign for the appointment request details page.

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#77683

## Testing done
Unit and e2e

### VA Request
localhost_3001_my-health_appointments_pending_mock1(iPhone 14 Pro Max)
---
localhost_3001_my-health_appointments_pending_mock1_confirmMsg=true(iPhone 14 Pro Max) (1)
---
localhost_3001_my-health_appointments_pending_mock1_confirmMsg=true(iPhone 14 Pro Max) (2)
###
CC Request
localhost_3001_my-health_appointments_pending_mock1(iPhone 14 Pro Max) (4)
---
localhost_3001_my-health_appointments_pending_mock1(iPhone 14 Pro Max) (5)
---
localhost_3001_my-health_appointments_pending_mock1_confirmMsg=true(iPhone 14 Pro Max) (3)

## What areas of the site does it impact?
VAOS

## Acceptance criteria
All test must pass

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by rmessina1010 — DISMISSED** [review]
LGTM

**Review by simiadebowale — COMMENTED** [review]
@vbahinwillit - Great job on the CancelPageLayout, CancelConfirmationPage & CancelWarningPage components!

**Review by simiadebowale — APPROVED** [review]
LGTM!

**Review by simiadebowale — CHANGES_REQUESTED** [review]
@vbahinwillit - I requested a cc appointment and when I cancel it, the facility field is empty.
Screenshot 2024-04-09 at 5 31 06 PM

**Review by simiadebowale — APPROVED** [review]
LGTM

**Pull request merged**
