### PR TITLE
Updates to healthcare/apply content

### PR DESCRIPTION
**Pull request by melwoodard**
Closes https://github.com/department-of-veterans-affairs/vets.gov-content/issues/215

- Adds back caregiver alert & link down to caregiver instructions
- Condenses download instructions for caregiver form
- Adds back 10-10EZR instructions

### CODE REVIEW

**Comment by bethpotts** [comment]
@melwoodard All these commits look great!

**Comment by melwoodard** [comment]
@bethpotts thanks :) I'll let you know when the PR link is back up so you can get a proper preview before we merge.

**Comment by melwoodard** [comment]
@jkassemi I merged master into the branch, but it doesn't seemed to have triggered a deploy to the heroku app. Thoughts?

**Comment by jkassemi** [comment]
@melwoodard - Not sure. Had to bump it manually from the Heroku dashboard.

**Comment by melwoodard** [comment]
Ok, thanks!

@bethpotts ready for a look over at https://vetsgov-pr-5103.herokuapp.com/healthcare/apply/

**Comment by melwoodard** [comment]
@tiffanybbrown-va I'm seeing some gnarly layout bugs on the homepage: https://vetsgov-pr-5103.herokuapp.com/

Does this have anything to do with the PR you just merged? https://github.com/department-of-veterans-affairs/vets-website/pull/5106/files

screenshot-vetsgov-pr-5103 herokuapp com-2017-03-17-15-58-24

**Comment by tiffanybbrown-va** [comment]
It does. I merged a hotfix right after it. Merging the latest from master should fix.

**Comment by melwoodard** [comment]
Thanks! @bethpotts ready for your eyes again.

**Comment by bethpotts** [comment]
@melwoodard Looks great!

**Pull request merged**
