### PR TITLE
Add missing page titles

### LINKED ISSUE #3129: Add page titles to every page in edu benefits form
Each page in the edu benefits form should have a title at the top on the desktop view.

If the page title is the same as the chapter title, hide it on mobile.

### PR DESCRIPTION
**Pull request by jbalboni**
Closes #3129.

This adds titles to every page and hides them on mobile if they're the same as the chapter title.

I've also updated the page titles to be sentence case. I've left the side navigation alone for now.

### CODE REVIEW

**Comment by jbalboni** [comment]
@goldenmeanie It looks like in the content files the titles are sentence case. Is that correct? Either way I'll make them all consistent.

**Comment by jbalboni** [comment]
@alexose Can you take a look at this when you have a chance?

**Comment by alexose** [comment]
Looks good, aside from the failing unit test:

`  1) Edu benefits json schema should pass validation with valid generated data:
     AssertionError: expected false to be true`

**Comment by jbalboni** [comment]
Accidentally included a schema repo update, looks like.

**Pull request merged**
