### PR TITLE
Adjusted break point for header, navigation mega menu

### PR DESCRIPTION
**Pull request by ghost**
Closes department-of-veterans-affairs/vets.gov-team#1221

Other changes:

- Rewrote media queries affecting Crisis Line, .va-cards, other home page components.
- Removed unused .va-nav-breadcrumbs--inline block.
- Refactored va-card classes for better layout on smaller screens.
- Added medium-large-screen variable.
- Added media-maxwidth mixin.
- Resized logo on desktop (closes department-of-veterans-affairs/vets.gov-team#1232)
- Adjusted layout of mobile search overlay.
- Refactored CSS to make header layout more consistent across breakpoints.

### CODE REVIEW

**Comment by jcmeloni-usds** [comment]
@tiffanybbrown-va Is this a running PR (I know you combined stuff -- yay!) or are you ready for review?

**Comment by tiffanybbrown-va** [comment]
@jcmeloni-usds It's ready for review. Was just about to ask for one.

**Comment by robbiethegeek-usds** [comment]
Just went through the deployed version on heroku and it looks good, I saw one card while clicking that the content seemed to be cut off when I was at 760ish px wide (I can't find it again LOL I know not super useful sorry) it was a blue card and the verbage in the card was right to the bottom and I think was cut off. 

Other then that I think this looks great,

**Comment by jcmeloni-usds** [comment]
WHOO HOOO

**Comment by tiffanybbrown-va** [comment]
Which browser are you using, @robbiethegeek? Is the cut-off Is this something that should delay a merge?

**Comment by robbiethegeek-usds** [comment]
I don't think it is a merge blocker, I was using chrome and the device toolbar with responsive as the device.

**Comment by melwoodard** [comment]
I found one in the playbook, between 641-685px. Probably not a very common device width playbook__vets_gov

**Comment by tiffanybbrown-va** [comment]
Ok. Will merge. The playbook card issue isn't a regression, and can be fixed by shortening the text.

**Comment by melwoodard** [comment]
@tiffanybbrown-va I was in the middle of my comment when you merged - the homepage header is not looking good on desktop - we need to make sure people's heads are not getting cut off:

discover__apply_for__track_and_manage_your_veteran_benefits_with_vets_gov__vets_gov

**Comment by tiffanybbrown-va** [comment]
Sorry. Will open a PR to fix that.

**Pull request merged**
