### PR TITLE
Add unassociated incomes

### PR DESCRIPTION
**Pull request by ToddWebDev**
## THIS FORM IS DISABLED IN PRODUCTION

# Income and Asset Statement Form (21P-0969)

## Description
Add a new section with the [Array Builder Pattern(Multiple responses list & loop)](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/patterns/array-builder/README.md)

## Issue
[Section III: Recurring Income Not Associated with Accounts or Assets #86213](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86213)

### Related Issues
n/a

### Epic
[Digitize Income and Asset Statement Form 21P-0969](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/80925)

#### Intro page
| Pristine | Required |
| ------- |  ------- | 
|localhost_3001_income-and-asset-statement-form-21p-0969_form-saved (3)|localhost_3001_income-and-asset-statement-form-21p-0969_form-saved (4)|

#### Recurring income pages
| First page | Second page |
| ------- |  ------- |
|localhost_3001_income-and-asset-statement-form-21p-0969_form-saved (5)|localhost_3001_income-and-asset-statement-form-21p-0969_form-saved (6)|

#### Summary page
| Single Entry | Multiple Entries |
| ------- |  ------- |
|localhost_3001_income-and-asset-statement-form-21p-0969_form-saved (7)|localhost_3001_income-and-asset-statement-form-21p-0969_form-saved (2)|

#### Review and edit page
| Multiple Entries |
| ------- |
|localhost_3001_income-and-asset-statement-form-21p-0969_form-saved (8)|

## How to run in local environment
1. Check out this branch locally in 'vets-website'
2.  Checkout this [branch](https://github.com/department-of-veterans-affairs/content-build/pull/2075) locally in 'content-build'
3. Run 'vets-api' in your local environment
4. Run the 'vets-website' app with `yarn watch --env entry=static-pages,auth,login-page,profile,dashboard,income-and-asset-statement`

## How to toggle feature flag in local environment
1. Go to [income_and_assets_form_enabled](http://localhost:3000/flipper/features/income_and_assets_form_enabled)

## How to verify
1. Go to `http://localhost:3001/income-and-asset-statement-form-21p-0969` in your browser
2. Sign in with a mock user and 'Start application'
3. Go to the 'Unassociated incomes' chapter
4. Verify that required fields are required
5. Verify that optional fields are optional
6. Verify that all fields follow validation rules
7. Verify that up to 5 unassociated incomes can be added, edited and deleted
8. Verify that the unassociated incomes are visible and editable on the 'Review and submit' page
9. Verify that the form can be saved via the api endpoint
10. Verify that the form can be submitted

## Testing
- [x]  Unit tests passing
- [x] E2E tests passing

## What areas of the site does it impact?
Income and Asset Statement Application

### Quality Assurance & Testing
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling
- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication
- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Review by TaiWilkin — CHANGES_REQUESTED** [review]
This is looking great!

The only issue I experienced was with going backwards through the form - if I select 'no income' and go to the review page, then click the 'back' button, I get a blank screen instead of the form.

**Comment by ToddWebDev** [comment]
Thanks @TaiWilkin, I'll look into that flow. This pattern introduces so many flows it's hard to test them all.

**Review by powellkerry — DISMISSED** [review]

**Review by TaiWilkin — APPROVED** [review]
Looks good!

**Comment by ToddWebDev** [comment]
@powellkerry A small change dismissed your approval. Can you please review again?

**Review by rsmithadhoc — APPROVED** [review]

**Pull request merged**
