### PR TITLE
BAH 781/781a Upload choice page content updates

### PR DESCRIPTION
**Pull request by robfelder**
## Description
This PR covers content updates necessary for both the 781 (new-disabilities/walkthrough-781-choice) and 781a (new-disabilities/walkthrough-781a-choice) upload choice pages. 

- Link to updated 781 content: [0781-2.2.1.1](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Disability%20Compensation/BAH-526/design/781-781a%20PTSD/Content/781%20Content-NewTech.md#0781-2211)
- Link to updated 781a content: [0781a-2.2.1](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Disability%20Compensation/BAH-526/design/781-781a%20PTSD/Content/781a%20Content-NewTech.md#0781a-221)

## Testing done
Manual

## Screenshots
781 Choice Before:
screen shot 2018-11-20 at 10 10 45 pm

781 Choice After:
screen shot 2018-11-20 at 10 11 35 pm

781a Choice Before:
screen shot 2018-11-20 at 10 11 06 pm

781a Choice After:
screen shot 2018-11-20 at 10 07 19 pm

## Acceptance criteria
- [x] Content adheres to copy deck specified above 

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by robfelder** [comment]
Hello, can I bother someone to review this PR, please? Have a great day!
@department-of-veterans-affairs/code-reviewers-for-external-teams-group
@rtluu

**Comment by peggygannon** [comment]
@rtluu @robfelder 

Please see below for my content tweaks for the 781 screens:

0781 screen
Please fix the quotation marks in the following words to make them forward:
we're 
you've 
I've 

Please add a space between Form and 21 it should be (VA Form 21-0781) 

0781a screen
Please fix quotation marks to make them forward

Please change: "What does this mean?" link TO
 "Which should I choose?" to match the prototype edits

under Answer questions header, 
please fix quotation mark in we'll
please make you will >> you'll 
please change you'll be able to upload that TO you'll be able to upload them

under Upload a form
please add a space between "complete" and the form name

**Comment by robfelder** [comment]
Hi @peggygannon, thank you for taking a look at the updates. I've made the updates you pointed out. When you get a chance, do you mind checking it out again and letting me know if I got everything correct?

**Comment by peggygannon** [comment]
@robfelder Hi, Rob. Are there updated screenshots that you could post here for me to check? or can you let me know if there is another place I should look to check the updates. I'm not able to view the deployment (don't have access).

**Comment by robfelder** [comment]
@peggygannon, as requested:

screen shot 2018-12-03 at 10 03 49 am
screen shot 2018-12-03 at 10 04 15 am

**Comment by peggygannon** [comment]
Hi, @robfelder thanks for the updated screenshots. My only additional edit is on the 781a screen. Please fix how we write the form (to match the 781 screen)

Under **Upload a form**, please change 21-0781a form 

TO: VA Form 21-0781a. So it should read: ....a completed VA Form 21-0781a,

**Comment by robfelder** [comment]
How's this @peggygannon?
screen shot 2018-12-03 at 1 59 12 pm

**Comment by peggygannon** [comment]
Hi, @robfelder thanks.. Looks like we still need to delete the 2nd extra "form" here: VA Form 21-0781a form

the sentence should read: ..a completed VA Form 21-0781a,

**Comment by robfelder** [comment]
Sorry about that @peggygannon:

screen shot 2018-12-03 at 2 43 39 pm

**Comment by robfelder** [comment]
This PR is OBE at this point.

**Pull request closed without merging**
