### PR TITLE
3831 create unit testing for the two components for the form 2346 medical device tool

### PR DESCRIPTION
**Pull request by mojaray2k**
## Description
As a _Front-end developer_, I need _to unit test my code_ so that I can __ensure me build is compatible and meets expectations____.

## Testing done
npm run test

## Screenshots
No screenshots

## Acceptance criteria
The requirements that must be met in order to mark this user story as completed
- [ ] Given that the test results are compliant
- [ ] When errors are displayed when issues accrue
- [ ] Then success will produce no errors when ideal process is conducted
## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by kelsonic** [comment]
Could you add more context description to this PR? (e.g. linking the related issue, the purpose of it, update the title of the PR since it does more than just adding unit tests, etc.) 🙂

**Comment by mojaray2k** [comment]
@keithdadkins Ooops my fault dude.  https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/3831

**Comment by mojaray2k** [comment]
@kelsonic  We are just trying to get something in place for future development.

**Comment by mojaray2k** [comment]
This is a **Draft PR** as we will be adding more meaningful test for a real MVP

**Comment by kelsonic** [comment]
GitHub doesn't have a way to go from an open PR to a draft PR to my knowledge 🙁So you would have to close this PR and then reopen a subsequent one in draft mode

**Pull request closed without merging**
