### PR TITLE
VACMS-17654 VAMC Facilities web component updates

### PR DESCRIPTION
**Pull request by randimays**
## Summary
Add v1 and v3 web components to VAMC Facility pages where possible. Affects the facility appointment wait times and facility appointment patient satisfaction score links.

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17654

## Testing done
Tested locally on `/minneapolis-health-care/locations/minneapolis-va-medical-center/`

## Screenshots
<details><summary>Satisfaction with appointment wait times</summary>

### Desktop
Screenshot 2024-05-16 at 2 37 26 PM
Screenshot 2024-05-16 at 2 36 21 PM

### Mobile
Screenshot 2024-05-20 at 2 04 30 PM

</details>

<details><summary> Avg days to get an appointment</summary>
### Desktop
Screenshot 2024-05-16 at 2 37 39 PM
Screenshot 2024-05-16 at 2 35 58 PM

### Mobile
Screenshot 2024-05-20 at 2 04 46 PM

</details>

### CODE REVIEW

**Comment by randimays** [comment]
@thejordanwood Nothing visual should have changed here; but since this shares a review instance with content-build for some reason, I thought I'd add you here for the extra set of eyes 👀

**Review by eselkin — APPROVED** [review]
Hi it's curious. I know the social links CSS moved to content-build in your other PR. Any idea why it was here to start? Did they want to keep CSS in vets-website?

**Comment by randimays** [comment]
@eselkin I moved the social links stuff in the other PR since it was just one style block. I'm not actually sure whether we should be moving styles to content-build, so I decided against it in this PR. I think maybe we need to have a discussion about that as we transition over to next-build.

**Comment by laflannery** [comment]
@randimays I didn't get to fully finish reviewing before the RI stopped working but here are my notes so far:

- On the card components, can you remove the `VADS` padding? I don't think it's actually doing anything but we are trying to consciously
Screenshot 2024-05-17 at 3 22 34 PM
 trying use these fewer of these so the templates are easier to maintain and adhere to DS spacing more easily
- The Get updates social links, thank you for updating these to the `va-link` and removing the external link behavior, what a treat! 2 things:
  - Do we need the `rel` attribute anymore? I haven't seen it on any of our other links so it's more just clean up, but not sure the purpose.
  - I noticed that the Twitter/X Text changed, which normally is fine however this is editor managed content so editor unfortunately control how this displays.
  - FWIW, we do have a backlog ticket in Facilities to look at this and standardize this in the future.
Screenshot 2024-05-17 at 3 29 07 PM

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Comment by thejordanwood** [comment]
@randimays I'm unable to get the RI to work for me. The screenshots looks good, but I'd like to see some mobile screenshots before approving this. Can you add those whenever you have time?

**Review by thejordanwood — APPROVED** [review]
@randimays I went to the PR you suggested to review this change. Looks good!

**Review by laflannery — APPROVED** [review]

**Pull request merged**
