### PR TITLE
VET TEC: Update page URLs for the workflow #16931

### PR DESCRIPTION
**Pull request by zurbergram**
## Description

As a va.gov developer I need to update the URL for each page within the 0994 workflow so that the workflow resides in the correct section within the va.gov platform. 

_Supporting Artifacts_
- TBD

_Assumptions_
- DSVA will eventually add 'VET TEC' to the left navigation under the GI Bill Benefits > How to use benefits which is why the URL pattern needs to be updated
        - url: https://staging.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/
- DSVA (Peggy Gannon) is creating a New VET TEC static page
        - url: https://staging.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program
        - DSVA will be adding a new button to apply for VET TEC to the static page
- This story is related to #16421 

## Testing done
- local testing

## Acceptance criteria
- [ ] After the user answers the questions to trigger the VET TEC form under [Education>How to Apply] then the user will be routed to the first page of the 0994 workflow (intro page) and it will correspond to:  https:/staging.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994/introduction 

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by zurbergram** [comment]
Related PR https://github.com/department-of-veterans-affairs/vagov-content/pull/273

**Review by devin-mccurdy — APPROVED** [review]
LGTM

**Comment by zurbergram** [comment]
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!

**Comment by jbalboni** [comment]
We'll also need to make a change in the devops repo to add the new url to our react routes list. I can create that.

**Review by jbalboni — APPROVED** [review]

**Pull request merged**
