### PR TITLE
Removes page from the SET_DATA action

### PR DESCRIPTION
**Pull request by cvalarida**
Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2939

Removes `page` from :all-the-thingz:!

### CODE REVIEW

**Review by jbalboni — APPROVED** [review]
Looks good, except I think there are some unit tests still to update.

**Comment by cvalarida** [comment]
I ran all unit and e2e tests locally before I pushed and they all passed. The build failed in the e2e phase with the following error after having lots of passing tests:

```
Connection refused! Is selenium server started?
{ Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketCloseListener (_http_client.js:285:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12) code: 'ECONNRESET' }

```

**Comment by cvalarida** [comment]
@jbalboni After retriggering Jenkins to "recover" from a bad build, it works like a ~charm~ working thing...What unit tests do you mean?

**Comment by jbalboni** [comment]
If it's passing now, I think I must have misread the search I did. Looks good to merge, in that case.

**Pull request merged**
