### PR TITLE
[69346] Add unit test coverage for AppointmentCard.jsx

### PR DESCRIPTION
**Pull request by young1205**
## Related issue(s)

- [Ticket](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/69346)

## Testing done
 
Checked file coverage and confirmed it was 100% covered.
 
Screenshot 2023-12-14 at 12 14 26 PM

## Acceptance criteria
 - [x] file coverage for Branches, functions, lines and statements is 100%

### CODE REVIEW

**Review by simiadebowale — APPROVED** [review]

**Review by vbahinwillit — COMMENTED** [review]
I would check with Simi on this but I thought AppointmentCard and all associated tests was supposed to be removed since the AppointmentList is the new default view.

**Comment by simiadebowale** [comment]
> I would check with Simi on this but I thought AppointmentCard and all associated tests was supposed to be removed since the AppointmentList is the new default view.

**Comment by vbahinwillit** [comment]
@simiadebowale - Is the route '/canceled' still valid? If not, then the CanceledAppointmentListPage and unit test can be removed.

**Comment by simiadebowale** [comment]
@vbahinwillit - We no longer use the /canceled route. I'll write up a ticket to remove the CanceledAppointmentsList component

**Pull request merged**
