### PR TITLE
Upgrade all major dependencies related with ESLint

### PR DESCRIPTION
**Pull request by jhonny218**
## Description
In this PR all major dependencies related with ESLint will be upgraded.

No breaking changes in all of them but `eslint-plugin-unicorn`, however, after testing all version before and after the breaking changes there are no errors.

## Original issue(s)
department-of-veterans-affairs/va.gov-team#28952

## Testing done
Locally with `yarn lint:js`

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by erikphansen — APPROVED** [review]
🎉

**Review by timwright12 — APPROVED** [review]

**Review by ashagross — APPROVED** [review]

**Review by zacharymorel — APPROVED** [review]
WOO!

**Review by ddzz — APPROVED** [review]

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by mpelzsherman — APPROVED** [review]

**Review by Rleahy22 — APPROVED** [review]

**Review by micahchiang — APPROVED** [review]

**Review by asg5704 — APPROVED** [review]

**Review by bkjohnson — APPROVED** [review]

**Review by LeKeve — APPROVED** [review]

**Review by stephenBarrs — APPROVED** [review]

**Review by jgacek — APPROVED** [review]

**Review by f1337 — APPROVED** [review]
Ship it! :shipit:
Guinea pigs let out of a pen and running like lemmings

**Review by craigwheeler — APPROVED** [review]

**Pull request merged**
