### PR TITLE
Pension mvp 71727 Add care expenses

### PR DESCRIPTION
**Pull request by ToddWebDev**
## Summary
On the Pension Benefits application(21P-527EZ), update the 'Financial information' chapter to collect information about care expenses.

## How to run in local environment
1. Check out this branch locally
2. In your local environment, set the `pension_form_enabled` flipper to 'enabled' at http://localhost:3000/flipper/features/pension_form_enabled
3. Run `vets-website` and `vets-api`

## How to verify
1. Go to `http://localhost:3001/pension/application/527EZ` in your browser
2. Start or continue the application
3. Go to the 'Financial Information' chapter
4. Continue to the 'Care expenses' page
5. Verify that the 'Care expenses page' Add an unreimbursed care expense page is the next page when 'Yes' is selected
6. Verify that the 'Care expenses page' Add an unreimbursed care expense page is NOT the next page when 'No' is selected
7. Verify the layout and content on the Add an unreimbursed care expense page
8. Verify that appropriate fields are required to add a care expense
9. Verify that a valid entered care expanse collapses when [ Add another expense ] is pressed
10. Verify that you can edit and add multiple care expenses 
12. Verify that the form data is saved to the redux store and submitted to the api

## Related issue(s)
[Ticket in Github](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71727)
[Epic in Github](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63349)

## Testing done
- [x] Existing unit tests updated
- [x] New unit tests added

### Desktop
| Add care expense | Valid | Invalid | Multiple care expenses |
| ------ | ------ | ------ | ------ |
|localhost_3001_pension_application_527EZ_ (1)|localhost_3001_pension_application_527EZ_financial_care-expenses (1)|localhost_3001_pension_application_527EZ_ (2)|localhost_3001_pension_application_527EZ_financial_care-expenses

## What areas of the site does it impact?
Pension Benefits Application

## Acceptance criteria
[Ticket in Github](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71727)

### Quality Assurance & Testing
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Comment by TaiWilkin** [comment]
Should [this](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71727) be the linked ticket?

**Comment by TaiWilkin** [comment]
Is the line of text under this text box ("Add an unreimbursed care expense") intentional? It feels out of place to me
Screenshot 2023-12-15 at 1 21 11 PM

**Comment by ToddWebDev** [comment]
@TaiWilkin Whoops. No that's not supposed to be there. I pushed an update to remove it.

**Review by TaiWilkin — APPROVED** [review]
LGTM

**Pull request merged**
