### PR TITLE
Use function replaceWithStagingDomain to make sure stage doesn't go to prod

### PR DESCRIPTION
**Pull request by GovNapoleon**
## Summary

-  If you go to https://staging.va.gov/ > search for 1995 in the search area in the center of the screen you'll get redirected to production

Screenshot 2023-09-21 at 9 56 34 AM

## Issue

- The problem was introduced into the codebase on 10/12/2022

Screenshot 2023-09-21 at 10 33 59 AM

### CODE REVIEW

**Comment by randimays** [comment]
@GcioNapoleon I'm not able to get the review instance to work on this PR. Is it working for you?

**Comment by GcioNapoleon** [comment]
Just finished merging the latest main into the branch.

**Review by rsmithadhoc — APPROVED** [review]
Looked good on preview environment for me, thanks!

**Review by randimays — APPROVED** [review]
I think SOCKS was down for me yesterday. Preview instance is working for me now, and it looks good! Thanks.

**Pull request merged**
