### PR TITLE
Add DeleteChildren component and test

### PR DESCRIPTION
**Pull request by wullaski**
## Summary

- Wraps appointment list content in a <del> tag if the appointment is cancelled
- Adds a wrapper component and test

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
[department-of-veterans-affairs/va.gov-team#83225](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83225)

## Testing done

- Unit
- Visual

## Screenshots
Screenshot 2024-05-24 at 11 29 05 AM

## What areas of the site does it impact?

Check-in 

## Acceptance criteria

- [ ] It adds a delete tag around list item content 

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by brianseek — COMMENTED** [review]
I think I'm going to need to be talked into using a component for this. It seems like something that could just be inline since the component is just utilizing a single html element. 

Even going with the component, I have issues with the name. The majority of the time its not going to be using the `<del>` tag so its a bit of a misleading name. I think something more generic like `<AppointmentInfo>` would be better. Then you can take in that data-testId as a prop and output with the div wrapper too. But I still think it would be better to wrap the whole block in a single `<del>` tag if the appointment is canceled, you can do it inline in the return and ditch the component.

like this
```
<li>
  <del>
   ...all the stuff
  </del>
 <details link>
</li>
```

**Review by brianseek — APPROVED** [review]
🚀 LGTM

**Review by ataker — APPROVED** [review]

**Comment by cgednalske** [comment]
Looks good to me as well! @zach-park look good?

**Comment by zach-park** [comment]
Looks good. Thank you!

**Pull request merged**
