### PR TITLE
bump up z-indexes of overlays and dropdowns

### PR DESCRIPTION
**Pull request by rianfowler**
## Description
screen shot 2018-09-28 at 15 36 13

## Screenshots
screen shot 2018-09-28 at 15 35 53
screen shot 2018-09-28 at 15 35 47

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by rianfowler** [comment]
Should we name these z-index values and use that instead of these arbitrary numbers? I think we're going to be updating the z-indexes a bit to deal with the team site stuff and it might be easier if we abstract the it.

**Review by erikphansen — COMMENTED** [review]
It's not possible to just move the offending nav bar down without also adjusting the modal?

**Comment by ncksllvn** [comment]
@rianfowler that sounds like an awesome idea. There are z-index changes in this PR too, https://github.com/department-of-veterans-affairs/vets-website/pull/8595#pullrequestreview-160026670. Does this impact the work here?

**Review by ncksllvn — APPROVED** [review]

**Comment by ncksllvn** [comment]
@bshyong @rianfowler @accbjt @RobAWilkinson @jbalboni  Looks like we have a few elements that may wind up fighting over the z-index. I really like @rianfowler's suggestion of naming these values. How we can get that pattern started?

**Comment by rianfowler** [comment]
@erikphansen We're pushing our header onto a site which has styling we don't control- this is why we're using such high z-index values. For [example](https://dev.va.gov/health/). I think we'll endeavor to keep the values as low as we can.

**Review by cehsu — APPROVED** [review]
LGTM.

**Review by erikphansen — APPROVED** [review]

**Pull request merged**
