### PR TITLE
Added 404 React component to MHV Landing Page

### PR DESCRIPTION
**Pull request by carlosfelix2**
## Summary
If a user enters a bad URL that is part of a root for a React app then a blank or partial page will be shown to the user. The correct behavior is to show a 404 page to the user. This is achieved by adding a default route to a React app to catch any URLs that are invalid for the app. Note that this only affects each app and they are isolated by the root URL, hence, each app will have to implement a default route for a 404 page. The 404 page will be shown even for unauthenticated users. This PR only adds the 404 page to the MHV Landing Page. Other apps will be done on separate tickets and will require coordination with other teams.

As part of this PR, the DHP Connected Devices app was changed to use this new shared component, and the app specific PageNotFound component was removed since it is duplicate code. This shows as a move of the file since the files were almost identical.

## Related issue(s)
https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/74176

## Testing done
- Added e2e test to the MHV landing page
- DHP connected devices app already has an e2e test that includes the page not found component.

## Screenshots
These screenshots are for the path `/my-health/sdfsdfsdf`

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  | staging va gov_my-health_sdfsdfsdf(iPhone 14 Pro Max) |  localhost_3001_my-health_sdfsdf(iPhone 14 Pro Max)  |
| Desktop | staging va gov_my-health_sdfsdfsdf | localhost_3001_my-health_sdfsdf |

## What areas of the site does it impact?
- /my-health

## Acceptance criteria
- Child paths to the MHV landing page result in a page not found error.

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by radavis — DISMISSED** [review]
Tested locally. Looks great! Nice work.

**Comment by radavis** [comment]
We probably want a unit test for the PageNotFound component. [Here's one](https://github.com/department-of-veterans-affairs/vets-website/pull/27812/files) I threw together. Feel free to merge this into your branch, or copy-paste it.

**Review by jzucadi — DISMISSED** [review]
Looks good, tested and working as intended. One thing, you might consider adding an empty dependency array so that it only runs once and doesn't send an analytics event for each render

```
const PageNotFound = ({ recordEvent = recordEventFn } = {}) => {
  useEffect(() => {
    recordEvent({
      event: `nav-404-error`,
    });
  }, []);
```

**Comment by carlosfelix2** [comment]
That's a good one! I added the recordEvent dependency. There is a linter warning about using just an empty array, but in reality recordEvent is a value and should be a dependency.

> Looks good, tested and working as intended. One thing, you might consider adding an empty dependency array so that it only runs once and doesn't send an analytics event for each render
> 
> ```
> const PageNotFound = ({ recordEvent = recordEventFn } = {}) => {
>   useEffect(() => {
>     recordEvent({
>       event: `nav-404-error`,
>     });
>   }, []);
> ```

**Review by radavis — APPROVED** [review]

**Review by jzucadi — APPROVED** [review]

**Review by IGallupSoCo — APPROVED** [review]
LGTM

**Review by randimays — APPROVED** [review]

**Pull request merged**
