### PR TITLE
Error messages for RX

### PR DESCRIPTION
**Pull request by bshyong**
Addresses department-of-veterans-affairs/vets.gov-team#943

Some of the messaging is open to change depending on content team.

The ErrorView restricts access to the app for 'blocking' errors; other errors, i.e. action-based errors like Refill Failure fall through to the alert boxes.

Screenshots:

screen shot 2017-02-02 at 2 07 41 pm

screen shot 2017-02-02 at 12 12 27 pm

screen shot 2017-02-02 at 12 03 08 pm

### CODE REVIEW

**Comment by bshyong** [comment]
@saneshark before this is merged, can you confirm that the error codes from the backend are sent in this format `RX101` (capital letters for RX)?

**Review by austin-martinez — APPROVED** [review]
LGTM 👌 Can you add some specs around ErrorView?

**Comment by saneshark** [comment]
@bshyong Yes, I can confirm that errors will be of the form RX101, and not Rx101.

**Comment by bshyong** [comment]
Unit test for ErrorView is added

**Pull request merged**
