### PR TITLE
[MHV-47987] Adding_arrow_functionality_for_Print_button

### PR DESCRIPTION
**Pull request by Wyzardsleeves**
## Summary

- I have implemented functions that allow users to select print options with the keyboard.
- Built out a function in the PrintDownload component.
- MHV Medical Records

## Related issue(s)

- [Link to Ticket](https://jira.devops.va.gov/browse/MHV-47987)

### CODE REVIEW

**Review by mattwrightva — COMMENTED** [review]
Nice work! I like your solution! My feedback:

1. I think the normal select/dropdown open/close keystroke is the spacebar. I could be wrong, but that is what I have always used in lieu of a mouse click. 
2. You might consider focusing the button elements on up/down keystrokes, rather than just changing the styling. 
3. It seems natural to me to have the default selection be at the top (index 0), although I would also argue that index 0 should be the dropdown itself. 

I think we are trying to mimic the behavior of a typical select/dropdown, such as this:
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

I could be wrong about any of this, these are issues that the UCD or accessibility team should be able to give specific guidance on.

**Comment by Wyzardsleeves** [comment]
@mattwrightva I demo'ed it to UCD and they liked it. They just wanted me to allow both "enter" and "spacebar" to open the menu. I will go ahead and create a validation sub-ticket unless you have any other concerns.

**Review by mattwrightva — APPROVED** [review]
Awesome!

**Review by mattwrightva — APPROVED** [review]
Looks good!

**Pull request merged**
