### PR TITLE
PT. 2 . - [HOLD] Brand Consolidation - QA Patches for PI10-S1 #8536

### PR DESCRIPTION
**Pull request by ncksllvn**
Work continued from https://github.com/department-of-veterans-affairs/vets-website/pull/8536

## Description
This PR consists of all QA patches of limited scope for Brand Consolidation, PI10-S1. 

As this PR will have many contributors, please use a meaningful commit message, along with a link to the corresponding issue in a comment or in this description.

## Acceptance criteria
- [ ] Deadline for PI Code Complete has been reached, or we've resolved all QA tickets.

## Closed tickets
- https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13575
    - 489d54aeb5d40a3c163ba6d6613108a46e12af40
- https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13574
    - 199578b57a6383d6525ce139a0727e3287ea1fd8
- https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13573
- https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13549
   - c1b8addb1d88947ddc6ec0f2be29776eb4233a95

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by RobAWilkinson** [comment]
- https://github.com/department-of-veterans-affairs/vets.gov-team/issues/12870
    - 451cfed1151080bc5bd72e108e762cf57c6aabff

**Comment by jbalboni** [comment]
- https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13603
    - 9d3d2a18caa97e9276f7a48326f1b1632eee9b62
- https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13613
    - 9d3d2a18caa97e9276f7a48326f1b1632eee9b62
- https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13601
    - 89157f70828e87995ec8fc782375f1e150f98db2
    - f1783103fac77dc568a9964c089393d166c58c11
- https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13592
    - ebe81f6bfc3ec0d5dbdeaae6e7564164b33e0024

**Comment by ncksllvn** [comment]
- https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13589
  - f2a0ac791bc2000bceceda219f8743386ccaf639

**Comment by jbalboni** [comment]
- https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13558
  - f4521048234fbac4e96c8212c9205d3ee485cfd5

**Comment by RobAWilkinson** [comment]
- https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13267
    - 8c50962851092191b1407ffd95f588e982fced70

**Comment by RobAWilkinson** [comment]
- https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13482
    - 451fcb6b6d01be9aa5a8b902ed9fb98c5cf10738

**Comment by jbalboni** [comment]
- https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13412
  - e8b9c5843c7b6fd653dde7c9a2d671fc4a9eb7d3

**Comment by RobAWilkinson** [comment]
- https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13560
    - d114623ff3b2328583d83ff0b122488080ae0b28

**Comment by RobAWilkinson** [comment]
- https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13581
    - c35d239b7fbe25bef88189b6cf47ae1bcde254fc

**Comment by ncksllvn** [comment]
- https://github.com/department-of-veterans-affairs/vets.gov-team/issues/12873
   - 50b2dafb0c098735a31eb55b25571b4d35867d87

**Review by RobAWilkinson — APPROVED** [review]
LGTM

**Pull request merged**
