### PR TITLE
Edu apply wizard adjustments

### PR DESCRIPTION
**Pull request by cehsu**
Connects to department-of-veterans-affairs/vets.gov-team#3020
Connects to department-of-veterans-affairs/vets.gov-team#3019

Add a warning when NCS is chosen.
Are you sure? This is extremely rare.

screen shot 2017-05-30 at 5 41 35 pm

Fix backtracking bugs

### CODE REVIEW

**Comment by jbalboni** [comment]
@cehsu @goldenmeanie What is this waiting on? I see it's been hanging out for almost a week.

**Comment by goldenmeanie** [comment]
It’s waiting on me to make a final decision on copy/emphasis for the NCS question. We’re getting usability feedback on it this week.

**Comment by J-Quag** [comment]
Also, I would like to see something that has the ability to choose something directly... even if its de-emphasized and lower on the page.

**Comment by jbalboni** [comment]
@J-Quag Can you make an item for that?

**Comment by J-Quag** [comment]
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3145

**Comment by goldenmeanie** [comment]
Made some updates, that required conflict resolution. @cehsu Can you take a look to make sure I chose correctly?

**Review by cvalarida — APPROVED** [review]
Waded through the commits to see which were actually for this branch. I think I found them all. The ones I looked at were good, at any rate. 👍

**Pull request merged**
