### PR TITLE
Added display_title property for breadcrumbs, side navigation.

### PR DESCRIPTION
**Pull request by ghost**
Closes department-of-veterans-affairs/vets.gov-team#1977

- Uses title or final path segment if the last breadcrumb is the indicator of the current page.
- Uses the display title, then the page title, then the path otherwise.

### CODE REVIEW

**Comment by melwoodard** [comment]
I think this approach is great. Since the breadcrumbs will fall back to the Page title if there is no Display title, this means Content won't need to do anything tied to this launching and everything will still work. Then you'll be able to identify and address pages that need a shorter display title on your own time.

Adding @amybehrens and @rroueche to weigh in - please take a look through to see the adjustment to breadcrumb names: https://vetsgov-pr-5303.herokuapp.com/

**Review by jcmeloni-usds — APPROVED** [review]

**Review by rroueche — APPROVED** [review]
Love it, and checked through pages w/longer titles (certain pages under Conditions and under Burials), and IMO it's no big deal for those to be like that at least for now.

**Comment by jcmeloni-usds** [comment]
Argh! So close, one conflict away from merging and living the good life. :)

**Review by melwoodard — APPROVED** [review]

**Comment by jcmeloni-usds** [comment]
@melwoodard @rroueche Everyone good w/ merging these in on a Friday? If you are, please press the green button. :)

**Comment by rroueche** [comment]
Yes I am good with merging these today! (I think I approved, but if there's something else I should do lmk 😆  )

@amybehrens mentioning you so you know this update's launching today, woo!

**Comment by tiffanybbrown-va** [comment]
Pressing the button.

**Comment by jcmeloni-usds** [comment]
whoo hooo!

**Pull request merged**
