### PR TITLE
Upgrade `webpack-dev-server`

### PR DESCRIPTION
**Pull request by ddzz**
## Description
PR to upgrade `webpack-dev-server` to the latest version and fix a deprecation warning.

## Testing done
- `webpack-dev-server` works locally.
- Cypress tests run locally.

## Acceptance criteria
- [ ] CI passes.

### CODE REVIEW

**Comment by theodur** [comment]
Nothing stands out to me, but I'm tagging @alexandec since he worked on the recent Webpack upgrade

**Comment by alexandec** [comment]
LGTM, thanks for keeping us up to date Darius!

**Review by alexandec — APPROVED** [review]

**Comment by ddzz** [comment]
@alexandec @theodur @timwright12 Do you think it's worth doing additional testing for this PR? They're all minor version bumps. I went through the changelogs for all the updated dependencies and couldn't find any breaking changes other than `onBeforeSetupMiddleware` being deprecated in `webpack-dev-server`, which I fixed in this PR.

**Review by timwright12 — CHANGES_REQUESTED** [review]
@ddzz yeah we have to run through a whole test plan when we upgrade major systems like this. Might want to hold off on this.

This is the last test plan, it's pretty intense https://docs.google.com/spreadsheets/u/1/d/1KxJpc6a7XeJOQVG9C1IGQF6SnQsRMvj3WoaOz0bhbAs/edit#gid=0

**Comment by ddzz** [comment]
> @ddzz yeah we have to run through a whole test plan when we upgrade major systems like this. Might want to hold off on this.
> 
> This is the last test plan, it's pretty intense https://docs.google.com/spreadsheets/u/1/d/1KxJpc6a7XeJOQVG9C1IGQF6SnQsRMvj3WoaOz0bhbAs/edit#gid=0

👍 Makes sense, I'll change this PR to upgrade only `webpack-dev-server` then so it can get merged, otherwise this will sit around for a long time.

**Review by timwright12 — APPROVED** [review]

**Pull request merged**
