### PR TITLE
Profile/aw/51085/account security cond process list

### PR DESCRIPTION
**Pull request by adamwhitlock1**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

The Account Security page of the Profile application is undergoing some changes. This is the first work for these changes.

- New feature toggle added for `profile_use_security_process_list`
- `ConditionalProcessList` component created to show a list of content with checkmarks next to complete items in the process list.
- Toggle will allow legacy and new work to be set up and viewed in staging before deployement
- Tests added for new feature.

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/51085

## Testing done

- Unit tests added for core functionality of the `ConditionalProcessList` component
- E2E tests written for functionality of new component and usage within Account Security utilizing the feature toggle
- Further tests will be added for edge cases and other UI state as this work moves forward, but this PR is pushing 750 LOC diff so didn't want to go too much further.

## Screenshots

| | Before | After |
| --- | --- | --- |
| Mobile | Screenshot 2023-01-26 at 9 32 29 AM | Screenshot 2023-01-26 at 9 35 37 AM | Screenshot 2023-01-26 at 9 35 37 AM | Screenshot 2023-01-26 at 9 35 25 AM |

## What areas of the site does it impact?
Profile application - Authenticated Experience

## Acceptance criteria

- [x] Component built to specs
- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x]  I added a screenshot of the developed feature

### CODE REVIEW

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Comment by adamwhitlock1** [comment]
@allisonlu I made the updates that we talked about for styling cleanup and this PR should be good to go for review now.

**Comment by allisonlu** [comment]
**Note to reviewers**: one of the items in the [Tasks section for this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51085) mentions the fiduciary flag. Per conversation w @adamwhitlock1:

> That work for the issue didn’t actually have to touch anything that would impact fiduciary flag stuff

Some thoughts (out of scope of this issue, but for consideration in the future):
- If this passes UAT and gets pushed to prod, we should make a ticket to clean up some old components (e.g. [Verified](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/profile/components/account-security/Verified.jsx))
- While using VoiceOver, the Rotor menu for headings is reading the h2 "Profile" on the side nav is getting read first before the h1 "Account Security"

**Review by allisonlu — APPROVED** [review]

**Review by nathanielbuck — APPROVED** [review]

**Comment by adamwhitlock1** [comment]
@allisonlu great points!

> Some thoughts (out of scope of this issue, but for consideration in the future):
> 
> * If this passes UAT and gets pushed to prod, we should make a ticket to clean up some old components (e.g. [Verified](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/profile/components/account-security/Verified.jsx))
> * While using VoiceOver, the Rotor menu for headings is reading the h2 "Profile" on the side nav is getting read first before the h1 "Account Security"

There will be certainly some significant cleanup after this new ui launches, so lets definitely make sure that that appropriate tickets are created around that when the time comes.

The VoiceOver heading hierarchy issue i believe is documented here:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/40593

^ I will make a note to discuss the history of that issue with you soon and maybe we can continue to figure out how to fix it.

Thanks for the feedback!

**Pull request merged**
