### PR TITLE
Change call center number

### PR DESCRIPTION
**Pull request by akainic**
Updated call center number to vets.gov number.

There are a few places where I'm not sure if I should still update the number:
1. When referring them to a specialist to talk about their benefits options: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/js/edu-benefits/components/benefits-eligibility/BenefitsRelinquishmentFields.jsx#L51
2. On other content pages (see bottom): https://github.com/department-of-veterans-affairs/vets-website/blob/master/content/pages/education/gi-bill/montgomery-selected-reserve.md

Should this new vets.gov number replace ALL GI Bill number references? Even when it has to do with the specifics of the GI Bill and not our applications? @koconnor719

### CODE REVIEW

**Comment by koconnor719** [comment]
yes.  the goal is we will have 1 vets.gov number--and a live person will transfer users to the appropriate call center.  @staceylanger @akainic

**Comment by koconnor719** [comment]
other than the Veterans Crisis Line--that should remain where it is and not be changed.

**Comment by akainic** [comment]
Got it, will change all of them then, thanks!

**Comment by akainic** [comment]
This PR is on hold until next week so wait to merge.

**Comment by mollyblake** [comment]
@akainic I called the number an hour ago and again, just now and the recording says, "we are temporarily unable to take your call, please try back in an hour or so."  Just FYI.

**Comment by akainic** [comment]
No longer relevant. Closing.

**Pull request closed without merging**
