### PR TITLE
[WIP] Plain Language Update for Disability Benefits

### PR DESCRIPTION
**Pull request by rcarthur**

### CODE REVIEW

**Comment by maryannbrody** [comment]
@rcarthur -- following up from our call yesterday -- we would like to review the plan and approach for editing all pages before work begins. Let me know if there is any confusion on this. Thanks! cc/ @staceylanger

**Comment by bethpotts** [comment]
@maryannbrody Understood! I just told the content team to hold off working on this.

**Comment by staceylanger** [comment]
Yes - some of the things I think we need to align on (I'm hoping this is covered in your approach plan):
-What is the best way to ensure alignment with DSVA? For example, is DS reviewing everything? Should a few sample pages be done by the content team and discussed with DSVA?
-How does this project fit into the other tasks that need to be completed?
-What is needed from DSVA resources to be successful with this task?
I'm sure there are other things, but this is a large project, we need to make sure we are aligned on the path forward as there are many ways to potentially approach this.

**Comment by bshyong** [comment]
Updated Review app is here https://vetsgov-pr-3324.herokuapp.com/

**Comment by bethpotts** [comment]
@rroueche In anticipation of a meeting this week with SMEs to go over the PL edits for Disability, can you help me get heroku preview working? I committed a change yesterday, but it didn't kick start the heroku link as I thought it would. Thanks!

**Comment by rroueche** [comment]
@jkassemi I think the heroku link has expired for this - could you set it back up please? Thank you!

**Comment by jkassemi** [comment]
@rroueche - deployment requested, review app should be online shortly.

**Comment by jkassemi** [comment]
This popped up on a list of PRs with inconsistent Jenkins and Travis CI results. An update from master should get the Jenkins tests passing here.

**Comment by jcmeloni-usds** [comment]
@rroueche Please see @jkassemi's comment above -- is there anything you can do to help to get this PR moved along? Thanks!

**Comment by rroueche** [comment]
I resolved the conflicts, so I think we're good to go re:your note @jkassemi (let me know if that's not true!!). In terms of being ready to have this merged in @jcmeloni-usds, we're now working in a last round of commits bc the SMEs finished reviewing last week and requested some changes. Once those are done and copy-edited, we should be good to move forward w/the merge.

@bethpotts cc'ing you since you're heading up the content changes. let us know here when this is ready to go!

**Comment by jkassemi** [comment]
@rroueche: issue with build was just a "broken" link reference. Fixed in 50a4464, and review instances are back online.

**Comment by rroueche** [comment]
@jkassemi I'm not sure why the Jenkins check isn't passing - something about Docker daemon it seems like? Would you be able to take a look? If it's a content-related error that I'm just not reading correctly (broken link, etc), please let me know.

image

**Review by ghost — APPROVED** [review]

**Comment by rroueche** [comment]
@jkassemi and @amybehrens this is ready to go from my perspective! I plan to merge it Thursday Feb 23 morning so that it can be live in prod that afternoon.

Could you both take a peek to make sure you don't see red flags?

**Pull request merged**
