### PR TITLE
[eBenefits] replace external manifest imports

### PR DESCRIPTION
**Pull request by jerekshoe**
## Description
Replaces imports to external `manifest.json` files with calls to `getAppUrl` from `platform/utilities`. This is to get ready for single app builds. Also replaces an instance of `AlertBox` with `va-alert` and adds a copy of `mock-dependents.json` to `static-pages/dependency-verification`

## Original issue(s)
department-of-veterans-affairs/va.gov-team#34660

## Acceptance criteria
- [x] All imports to external `manifest.json` files are replaced with calls to `getAppUrl` for eBenefits applications

## Definition of done
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Review by cohnjesse — APPROVED** [review]
LGTM

**Comment by alexandec** [comment]
Nice! Tagging @theodur on this since he's the best person from our team to review it

**Review by theodur — APPROVED** [review]
This looks great! Glad to see these external imports being removed 🚀

**Review by adamwhitlock1 — APPROVED** [review]
LGTM

**Pull request merged**
