### PR TITLE
[Footer] Update casing

### PR DESCRIPTION
**Pull request by ncksllvn**
## Description
Updates the casing of a few links per https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16929.

## Testing done
Verified locally

## Screenshots
image

## Acceptance criteria
- [ ] Casing looks good

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by ncksllvn** [comment]
@bethpotts Glad I requested your review lol

**Comment by bethpotts** [comment]
@ncksllvn Hi there, I lowercased more link labels as needed here, but I didn't see where to make edits to the 5 headers in the footer (the far right column has 2 headers, stacked).
These need lowercasing as follows (can you do this in whatever file they're in?):
Veteran programs and services
More VA resources
Get VA updates
In crisis? Get help now
Contact us

**Comment by ncksllvn** [comment]
@bethpotts Done 💥

**Review by bethpotts — APPROVED** [review]
This is good to go, Nick!

**Pull request merged**
