### PR TITLE
#62996: Event tracker CTA for Cerner Re-direct - Public Website widget

### PR DESCRIPTION
**Pull request by simiadebowale**
## Summary
This PR:
adds Tracking to the `Go to My VA Health` CTA link on the new cerner appointments widget.

## Related issue(s)

- https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/62996

## Testing done
Tested by clicking the `Go to My VA Health` CTA link in my local instance and confirmed that analytics event was triggered.

## Acceptance criteria
- [x] Given when the user is authenticated and is registered at a Cerner site, when the user is on the Appointments widget on the static landing page and clicks on `Go to My VA Health`, Then it will trigger an event `vaos-cerner-redirect-static-landing-page` in UA4

### CODE REVIEW

**Review by powellkerry — APPROVED** [review]

**Comment by randimays** [comment]
@simiadebowale When posting PRs for review, please fill out the description of the pull request. This should include:

- Relevant ticket(s)
- Screenshots of the working functionality
- Description of the problem and the solution
- Testing steps
- Test users for others to use

Also, please make sure the review instance is functioning as expected with the test users before requesting reviews; you can do this by keeping the PR in draft while the CI finishes, and marking it `Ready for review` once you've validated.

**Comment by randimays** [comment]
@ldelacosta Please see above. Before requesting review from Public Websites, it would be helpful to have more information on the pull request as well as proof of testing by the Appointments team.

**Comment by simiadebowale** [comment]
@randimays - I am still testing this ticket out in the RI. When it is ready for review, I will fill out the details

**Comment by randimays** [comment]
@simiadebowale Curious what happened here. Did you need a review from Public Websites?

**Comment by simiadebowale** [comment]
@randimays - Review from either the platform team or Public websites was needed.

**Pull request merged**
