### PR TITLE
Adds package.json and export file and registers workspace for platfor…

### PR DESCRIPTION
**Pull request by rmessina1010**
## Description
This PR introduces a yarn workspace to `platform/utilities`.

## Original issue(s)
department-of-veterans-affairs/va.gov-team#45145

## Testing done
local unit testing. local builds for all environments. browser testing.

## Acceptance criteria
- [ ] behavior of website not altered other than adding the workspace

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by it-harrison — APPROVED** [review]
are you still working on adding the babel aliases?

**Comment by rmessina1010** [comment]
@Ian, I only took a glance at Babel, there are no additions that am aware of. Were there any on your end?

**Comment by it-harrison** [comment]
> @ian, I only took a glance at Babel, there are no additions that am aware of. Were there any on your end?

I mean, don't you need to add [these aliases](https://github.com/department-of-veterans-affairs/vets-website/blob/01c356a420385052b2439d2dc18730be6c308af6/babel.config.json#L181)?

**Review by it-harrison — APPROVED** [review]

**Review by it-harrison — APPROVED** [review]
looks good

**Pull request merged**
