### PR TITLE
[package.json] Update USWDS to 1.6.10

### PR DESCRIPTION
**Pull request by ncksllvn**
Commit c339b29170c83975ffceed02fd2ad092ca189702 updates this PR to use an alpha design system solely to make peer review easier. This way, the Heroku instance here will use the updated VA Design System and USWDS version so that we can test more easily.

You can verify that you're seeing the correct USWDS version by inspecting a focusable element, applying the focus state, then see that the focus rule is [no longer `*:focus`](https://user-images.githubusercontent.com/1915775/55360054-50963580-54a1-11e9-993c-b88c3a5be7db.png).

---
## Description
This PR upgrade our version of USWDS, and updates Formation to use the USWDS-updated version of that as well. This immediate reason for this is to patch an accessibility error with the focus indicator showing in IE11 on non-focusable elements.

Design System PR - https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/50

USWDS new version - https://github.com/uswds/uswds/pull/2997
    - We contributed! 😄 
Ticket - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14912
Ticket for USWDS upgrade - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17724

## Testing done
- Audited website locally
- Visual Regression Testing (everything checked out)

## Acceptance criteria
- [ ] Received upgrades from USWDS

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by jbalboni** [comment]
@ncksllvn Can you talk with @jaredcunha-usds about this? This impacts the design system and how that relates to USWDS.

**Comment by ncksllvn** [comment]
@jaredcunha-usds what are your thoughts on this? It looks the design system currently has [uswds installed as a peerDependency at 1.4.2](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/package.json#L35).

**Comment by jaredcunha-usds** [comment]
@ncksllvn When I first got the documentation site up and running, I was using version 1.6.x (can't remember exactly which). What I noticed was some weirdness with the alerts, something that changed with them between 1.4.x and 1.6.x: the icon size and spacing between the icon and the text in the alert. I can't remember if I saw anything else. 

That was before we updated the alert design. What I mentioned in the paragraph above _seems_ to be resolved since we updated the design. I just checked the documentation site on a branch using 1.6.10 and now the alerts look identical between Formation using 1.4.2 and 1.6.10. 

What I don't know is how that impacts other things on va.gov.

**Comment by jaredcunha-usds** [comment]
Also, @jbalboni, after the #17368 and #17375 are complete, we wouldn't need to include USWDS as separate dependency. 

Or does va.gov not use the formation.min.css file.

**Comment by jbalboni** [comment]
@jaredcunha-usds It doesn't use formation.min.css, but it uses most of the same scss files as the source, so we would still likely be able to remove USWDS as a separate dependency after those items.

**Comment by ncksllvn** [comment]
I opened a PR in the design system to also update USWDS there. I published an alpha version of VFST that's being consumed here, so we can audit the site from this PR's Heroku instance.

**Comment by ncksllvn** [comment]
I also ran visual regression testing, and the only failed tests were just from the loading GIF being in different states when the screenshot was taken, so I think this work is safe 👌

**Review by rianfowler — APPROVED** [review]

**Comment by ncksllvn** [comment]
Hey @rianfowler, I'm seeing some reference errors occurring during the build that may be related to https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/54. Do you mind taking a look when you get the chance?

**Pull request merged**
