### PR TITLE
25707/coronavirus screener cypress

### PR DESCRIPTION
**Pull request by CBonade**
## Description
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/25707

This covers the rewrite of the coronavirus screener tests from Nightwatch to Cypress.  The first test (00) all conditions pass as expected.  The second test (01) was disabled in Nightwatch.  I have converted it over in the same fashion as the first test, however both the new test and the old Nightwatch test fail at the same place. From what I can tell, this looks to be a result of the content on the page possibly having changed.  I have left this test disabled in Cypress in the same fashion, as it was being skipped currently.

As the current objective is just to port over what exists, we have a separate ticket opened to rewrite any tests that may need better coverage and/or eliminate any tests that are no longer relevant as part of a future initiative.

## Testing done

00 - Tested in Chrome Cypress test runner - working as expected
01 - Matches the functionality of the existing Nightwatch test, fails at the same point, currently disabled as with the current Nightwatch test.

## Screenshots
image

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by pjhill — APPROVED** [review]
LGTM

**Comment by mchelen-gov** [comment]
hey thanks for doing this! does this mean the NW tests can be removed?
.cc @stephenBarrs

**Comment by pjhill** [comment]
> hey thanks for doing this! does this mean the NW tests can be removed?
> .cc @stephenBarrs

Yeah, we are planning a phased approach. Once the Cypress version of the test is merged in and running without any issues for a sprint or so then we will come in with another PR and remove the NW version.

**Review by mchelen-gov — APPROVED** [review]

**Comment by pjhill** [comment]
This resolves [25707](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25707).

**Pull request merged**
