### PR TITLE
Add support for non-military HCA enrollment status type

### PR DESCRIPTION
**Pull request by erikphansen**
Also stop showing the 877-222-VETS version of the number and just use 877-222-8387 in all places where we show the enrollment support number (as discussed here https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19220#issuecomment-523931650 and here https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19220#issuecomment-523934535

## Description
This PR handles the new `non_military` status that can come back from the `GET health_care_applications/enrollment_status` endpoint

## Testing done
Local + updated unit tests

## Screenshots
image

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by Samara-Strauss — APPROVED** [review]
Screenshot looks good to me!

**Review by mojaray2k — CHANGES_REQUESTED** [review]
So are the unit test going to be fixed? Or should I ignore that? Also, what about the phone number?

**Comment by erikphansen** [comment]
@mojaray2k which unit tests? they are all passing. And the phone number should be correct. We _don't_ want to show the 800 number that was included in the original ticket. And we also no longer want to show the `877-222-VETS` version of the number like we had been.

**Review by mojaray2k — APPROVED** [review]
@erikphansen I was looking at your last commit message. If everything is good I will approve. 
https://github.com/department-of-veterans-affairs/vets-website/pull/10615/commits/9e0517ad19770861d1087108860ec312e77ac7ab

**Comment by erikphansen** [comment]
yeah, the commit message as saying that the commit itself fixes the broken unit test, not that there was still a unit test to fix.

**Review by cvalarida — APPROVED** [review]

**Comment by Samara-Strauss** [comment]
WOO! Thanks!!

**Pull request merged**
