### PR TITLE
[WIP] GIBCT Institution STEM indicator

### PR DESCRIPTION
**Pull request by nagaborra**
Added indicator whether a school or institution participates or offers a STEM program.

### CODE REVIEW

**Comment by jkassemi** [comment]
Ref: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9371

**Comment by jbalboni** [comment]
@rianfowler This should be ready to review now. I was able to test it locally.

**Comment by rianfowler** [comment]
Verified it locally. Approving for now- LMK if you want me to review it again after adding the modal content or if we need to track that separately.

**Review by rianfowler — APPROVED** [review]

**Comment by rianfowler** [comment]
The following work against dev data: 

Search: http://localhost:3001/gi-bill-comparison-tool/search?stemOffered=true
Detail: http://localhost:3001/gi-bill-comparison-tool/profile/14953411
screen shot 2018-06-26 at 16 52 50
screen shot 2018-06-26 at 16 53 09

**Pull request merged**
