### PR TITLE
Fix RX routing issue

### PR DESCRIPTION
**Pull request by alexose**
Via #2780

### CODE REVIEW

**Comment by U-DON** [comment]
When I try this change along with the API config from your other branch, it seems to direct all routing to root. I'm not sure if there's something else I'm missing,

**Comment by alexose** [comment]
Erp, you're right.  Looks like we're going to need slightly more complex proxy rules.  Give me about 20 minutes.

**Comment by alexose** [comment]
Still trying to get this to work with `webpack-dev-server`.

**Comment by U-DON** [comment]
LGTM!

**Pull request merged**
