### PR TITLE
Remove claims status from ignore list

### PR DESCRIPTION
**Pull request by jbalboni**
Removes claims status page from ignore list, so it builds on staging. It's not linked, so it won't be visible in production yet.

### CODE REVIEW

**Review by austin-martinez — APPROVED** [review]
🌴  LGTM

**Comment by ayaleloehr** [comment]
Hang on, I don't think we want this to be ignored in production yet!  Please don't merge until @jkassemi reviews. I think we want something more similar to https://github.com/department-of-veterans-affairs/vets-website/pull/3390.

**Review by ayaleloehr — CHANGES_REQUESTED** [review]
Sorry to put a block here, but I feel strongly that we don't want this to build in production yet so going to block until we get confirmation I am wrong.

**Comment by jbalboni** [comment]
@ayaleloehr We were told we're supposed to do stakeholder testing on staging. Whatever the best way to get this app to build on staging works for me.

**Comment by jbalboni** [comment]
This isn't useful even if it were merged, since it won't use the staging api. We need the PR Alex linked to be merged to use staging.

**Pull request closed without merging**
