### PR TITLE
removing the redirect flag

### PR DESCRIPTION
**Pull request by tmitchellgcio**
## Description
Post launch cleanup for my VA redirect

## Testing done
Local testing

### CODE REVIEW

**Review by asg5704 — CHANGES_REQUESTED** [review]
Can you also cleanup the selectors & featureToggles?

- `shouldRedirectToMyVA` in the `platform/user/selectors.js`
- `myVARedirect: 'my_va_redirect',` in the `platform/utilities/feature-toggles/featureFlagNames.js`

Everything else looks good.

**Comment by tmitchellgcio** [comment]
> Can you also cleanup the selectors & featureToggles?
> 
> * `shouldRedirectToMyVA` in the `platform/user/selectors.js`
> * `myVARedirect: 'my_va_redirect',` in the `platform/utilities/feature-toggles/featureFlagNames.js`
> 
> Everything else looks good.

on it

**Comment by tmitchellgcio** [comment]
Completed @AGarcia-Clarity

**Review by asg5704 — APPROVED** [review]

**Comment by AGarcia-Clarity** [comment]
@tmitchellgcio Approved

**Review by theodur — APPROVED** [review]

**Pull request merged**
