### PR TITLE
Brand-consolidation: Update Healthcare links

### PR DESCRIPTION
**Pull request by ncksllvn**
This PR updates the links on the Healthcare Hub, as well as though in the top navbar.

Resolves department-of-veterans-affairs/vets.gov-team/issues/12368

### CODE REVIEW

**Comment by bethpotts** [comment]
I found one broken link on the health care hub:

screen shot 2018-08-23 at 2 46 54 pm

**Comment by bethpotts** [comment]
@mnorthuis What's the correct url for this link? The one we have now, that's broken, is:
https://www.va.gov/healthbenefits/cost/index.asp/

**Comment by ncksllvn** [comment]
@bethpotts It looks like that link just had a trailing slash that it shouldn't have. Fixed it just now!

**Review by bethpotts — APPROVED** [review]
Looks good!

**Pull request merged**
