### PR TITLE
Fixing DUW style bug

### PR DESCRIPTION
**Pull request by randimays**
## Summary
Updating some styles to fix spacing and page width issues in the WIP app and the prod app.

## Testing done
Tested the WIP app (`/discharge-upgrade-instructions/introduction`) locally:

https://github.com/department-of-veterans-affairs/vets-website/assets/19175324/5c60323f-8811-4de2-93c6-d946fd457266

Tested the prod app (`/discharge-upgrade-instructions`) locally:

https://github.com/department-of-veterans-affairs/vets-website/assets/19175324/fdade716-3419-4e86-bc6f-2f734a1c5d5f

### CODE REVIEW

**Comment by laflannery** [comment]
Added in slack to but the RI doesn't look like your After screenshot - it has a very small max-width:
Screenshot 2024-05-09 at 4 37 28 PM

**Comment by rmessina1010** [comment]
Looking at the RI, there seems to be too much of and indent to the breadcrumb and headline, so they do not line up with the rest of the content
Screenshot 2024-05-10 at 11 26 42 AM (2)

**Review by harshilmoradia — DISMISSED** [review]

**Comment by randimays** [comment]
Thanks all for the feedback. Made some style updates. Screen recordings are in the PR description.

**Review by jtmst — APPROVED** [review]
Needing to set the va-breadcrumbs padding manually feels weird, but it renders correctly as is so I'd consider that non blocking. ✅

**Pull request merged**
