### PR TITLE
All claims intro content mg

### PR DESCRIPTION
**Pull request by markgreenburg**
## Description
Updates content for the 526 All Claims Introduction page, per the the latest copy in the attached ticket.

*Note* Removing the comma in the SiP notification will affect all forms. If this wasn't the intent, please let me know.

## Testing done
- Tested locally
- Updated unit test

## Screenshots
screen shot 2018-11-26 at 1 51 49 pm
screen shot 2018-11-26 at 1 52 14 pm
screen shot 2018-11-26 at 1 52 23 pm

## Acceptance criteria
- [x] Content matches ticket

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by peggygannon — CHANGES_REQUESTED** [review]
@markgreenburg Just one more fix: 

Please fix the phone number in the below sentence to: 
To find the nearest regional office, please call 1-800-827-1000.

**Review by cvalarida — APPROVED** [review]
As soon as it's good by Peggy, it's good by me.

**Comment by markgreenburg** [comment]
Thanks @peggygannon - phone number's been changed:
screen shot 2018-11-28 at 3 34 15 pm

**Review by peggygannon — APPROVED** [review]

**Comment by peggygannon** [comment]
@markgreenburg Looks good. thank you!

**Pull request merged**
