### PR TITLE
**Note**: We have received a record number

### PR DESCRIPTION
**Pull request by kellyskennedy**
Please refer to zen #8757 on this one. The request is pretty long, and I cut it down by about a twentieth.

### CODE REVIEW

**Comment by kellyskennedy** [comment]
Ready for a review, @peggygannon This is much different and on a different page than requested in the Content Update Request Form, and I am open to suggestions!

**Review by peggygannon — COMMENTED** [review]
@kellyskennedy Hi, Kelly. I've reviewed this PR, and have a few questions for you:
-- I want to be sure I am looking at the correct PR. You said you put this message on a different page than what was requested. But it looks like the SME request was to be on the pre-need/after-you-apply/ page
--I moved the message position, to under the "How long does it take VA" header as I thought it didn't really belong as part of the intro paragraph.  
--I also tweaked the wording, as I understood from the SME's request was that the focus was that sending out notifications would delay application review (not so much the large amount of applications). 

Let me know if you want to discuss!

**Comment by kellyskennedy** [comment]
@peggygannon That all makes sense to me, and yes, it looks as if you're working from the correct issue:

The Department of Veterans Affairs National Cemetery Administration receives applications and makes Pre-Need burial eligibility determinations on a first in - first out basis. We are pleased to be providing this service and honored that so that so many view national cemeteries as national shrines commemorating service and sacrifice to our Nation. Due to the unprecedented number of applications received, we have temporarily shifted our focus to notifying each applicant that we have received their application and communicating with them about expected timelines for completion of our determination. We expect to have this notification out to each applicant shortly. 

Please note that it is most critical that we provide eligibility and scheduling support to families with Time of Need requests for burial, meaning those circumstances where a death has occurred and families need to schedule a burial at a national cemetery. If that is your situation, you should contact your funeral service provider or the National Cemetery Scheduling Office at 1-800-535-1117.

We sincerely apologize for the delay, appreciate your patience and thank Veterans and their families for their service to our nation.

Thanks!

I think this is ready for you, @bethpotts

**Review by bethpotts — APPROVED** [review]
SMEs approved our edits to their language. This is GTG!

**Review by phiden — APPROVED** [review]

**Pull request merged**
