### PR TITLE
Changed first sentence

### PR DESCRIPTION
**Pull request by kellyskennedy**
First sentence duplicated this page's first sentence: https://www.vets.gov/disability-benefits/eligibility/

### CODE REVIEW

**Comment by kellyskennedy** [comment]
Can you review and edit this, @peggygannon Thanks!

**Review by peggygannon — COMMENTED** [review]
@bethpotts @kellyskennedy hello! I made some tweaks to shorten the intro, as it seemed a bit long. Let me know what you think of my suggested edits.

**Comment by kellyskennedy** [comment]
Hi @peggygannon and @bethpotts That looks great! And makes sense. Thank you!

**Comment by bethpotts** [comment]
@peggygannon Take one more look for typos since I edited. Thanks! If it looks good to you, go ahead and ask Sophia to review and merge.

**Review by peggygannon — APPROVED** [review]

**Comment by peggygannon** [comment]
@phiden This PR is ready for your review and if all looks good, it can be merged. Thx!

**Review by phiden — APPROVED** [review]

**Pull request merged**
