### PR TITLE
8520 accessibility fixes view dependents

### PR DESCRIPTION
**Pull request by micahchiang**
## Description
[Ticket for definition list update](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8515)
[Ticket for date format](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8520)

This pull request addresses two accessibility issues in view-dependents:
1. Updates the definition list used for dependent list items to more semantic markup. Adds a `dt` tag and switches out `<span>` tags for `<dfn>` tags.
1. Formats dates to long form so months are represented by word instead of number.

## Testing done
- local.

## Screenshots
Screen Shot 2020-05-07 at 2 27 33 PM
Screen Shot 2020-05-07 at 2 28 02 PM

## Acceptance criteria
- [x] definition list has been updated
- [x] dates have been formatted

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by micahchiang** [comment]
@jenstrickland - tagging you on this pull request since you were the one who originally surfaced the issues in the linked tickets.

**Comment by jenstrickland** [comment]
> @jenstrickland - tagging you on this pull request since you were the one who originally surfaced the issues in the linked tickets.

How might I check the fix? Is it in staging, yet? When I select View deployment, I get an error (likely because I don't have socks access). :(

**Comment by micahchiang** [comment]
@jenstrickland - Unfortunately it isn't in staging just yet. Things don't usually get there until they are merged into master. If you prefer, I could jump on a call with you and we could go over things together in localhost. I've also attached screenshots of the updated date and definition list markup.

**Comment by jenstrickland** [comment]
Thanks! I'd like to take a look into the dl code, to check on where the dl closes, where the dt tags are. Feel free to schedule some time on my calendar to show me what you have in local, or ping me when it is in staging. I think this isn't a 🔥 , so waiting until it is merged may be okay.

**Review by cohnjesse — APPROVED** [review]
LGTM

**Pull request merged**
