### PR TITLE
47132 vaos va link/appointment list

### PR DESCRIPTION
**Pull request by ryanshaw**
## Description
This is one of several PRs that replace the react-router `Link` component in VAOS with the newer `va-link` web component.

[va-link](https://design.va.gov/components/link/)
[va-link storybook](https://design.va.gov/storybook/?path=/docs/components-va-link--default)

This was broken up into multiple PR's to allow for easier code review as this change impacts nearly every file and every test within VAOS.

## Original issue(s)
[department-of-veterans-affairs/va.gov-team/issues/47132](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47132)

## Related to these other PR's:
- [breadcrumbs](https://github.com/department-of-veterans-affairs/vets-website/pull/22779)
- [requested appointments](https://github.com/department-of-veterans-affairs/vets-website/pull/22776)
- [covid flow](https://github.com/department-of-veterans-affairs/vets-website/pull/22818)
- [new appointment](https://github.com/department-of-veterans-affairs/vets-website/pull/23125)

## Testing done
- Unit testing
- e2e testing

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by jenniemc — CHANGES_REQUESTED** [review]
The upcoming and pending appointment list works as expected. However, with the past appointment list, I'm unable to open past appointment detail page because the target URL contains a double forward slash

Screenshot 2023-02-01 at 9 41 14 AM
Screenshot 2023-02-01 at 9 37 56 AM

**Review by vbahinwillit — COMMENTED** [review]
LGTM! Jenny has already done the bulk of the review.

**Comment by jenniemc** [comment]
@ryanshaw, Using test user `john.morrison@id.me` in the review instance, the double forward slash is still present in the target URL within the past appointment lists

**Comment by ryanshaw** [comment]
@jenniemc Will take a look at the `//`'s

**Comment by ryanshaw** [comment]
@jenniemc I believe the link issue with the extra slashes has been resolved.

**Review by jenniemc — APPROVED** [review]
Great work Ryan!

**Pull request merged**
