### PR TITLE
Modifying API_URL for preview site to point to prod api

### PR DESCRIPTION
**Pull request by b00klegger**
## Description
Modifying the preview API_URL to point to prod API as part of our support to allow real veterans to use the site.

## Acceptance criteria
- [ ]

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by wyattwalter** [comment]
ref: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/12330

**Review by wyattwalter — COMMENTED** [review]
LGTM, need to hold off for the weekend for the flip.

**Comment by b00klegger** [comment]
🙇

**Review by wyattwalter — APPROVED** [review]

**Comment by wyattwalter** [comment]
Thank you for updating this @ncksllvn !

**Pull request merged**
