### PR TITLE
Separate ToE App

### PR DESCRIPTION
**Pull request by nathanielbuck**
## Description
Add a new app directory for updates to the 1990E form, Transfer of Education benefits (ToE). These form changes were previously included alongside the existing 1990E app and hidden via feature flag, but issues in production led to removing the updates in #21650.

### CODE REVIEW

**Comment by it-harrison** [comment]
There is a failing unit test. I re-ran the workflow and the test failed again, so I don't think it is flaky.

**Review by it-harrison — APPROVED** [review]
looks good

**Comment by theodur** [comment]
@nathanielbuck Feel free to add this app to the [allowlist](https://github.com/department-of-veterans-affairs/vets-website/blob/main/config/changed-apps-build.json) since it doesn't have any cross app imports 🙂

**Comment by nathanielbuck** [comment]
> @nathanielbuck Feel free to add this app to the [allowlist](https://github.com/department-of-veterans-affairs/vets-website/blob/main/config/changed-apps-build.json) since it doesn't have any cross app imports 🙂

https://github.com/department-of-veterans-affairs/vets-website/pull/21746

**Pull request merged**
