### PR TITLE
updated Fiscal year to 2018 behind a prod flag

### PR DESCRIPTION
**Pull request by ksantiagoBAH**
## Description
As a user of the Comparison Tool, I need to see current Historical Information when reviewing the School Profile so that I have accurate information on which to base my decisions.

## Testing done
Ran the comparison tool locally and ensured changes are behind a production flag. 

## Screenshots
Screen Shot 2019-07-08 at 2 27 23 PM

## Acceptance criteria
- [X] On the School Profile Page under the "Additional Information" section; the "Historical Information" table header "Total paid (FY 2016)" is replaced with "Total paid (FY 2018)".

## Definition of done
- [X] Events are logged appropriately
- [X] Documentation has been updated, if applicable
- [X] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — CHANGES_REQUESTED** [review]
Minor minor quibble. The camel case should be updateFiscalYearTo2018, but I would just shorten to updateFiscalYear.

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by delli-gatti-michael — APPROVED** [review]
Passes QA

**Comment by ksantiagomorgan6** [comment]
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!.

**Review by rianfowler — APPROVED** [review]

**Review by rianfowler — APPROVED** [review]

**Pull request merged**
