### PR TITLE
Add feature toggle for request flow content update

### PR DESCRIPTION
**Pull request by jenniemc**
## Summary

Add a feature toggle flag to simplify and improve language clarity for the VA and Community Care appointment request flow.

## Related issue(s)
- Add `va_online_scheduling_request_flow_update` feature toggle

## Testing done

- n/a

## Screenshots
n/a

| | Before | After |
| --- | --- | --- |
| Mobile | | |
| Desktop | | |

## What areas of the site does it impact?
Future development for content updates to the VA and Community Care request flow

## Acceptance criteria

- [ ]  Add `va_online_scheduling_request_flow_update` feature toggle

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by vbahinwillit — APPROVED** [review]
Everything LGTM other than the failed e2e tests.

**Review by vbahinwillit — CHANGES_REQUESTED** [review]
Failed tests.

**Comment by jenniemc** [comment]
> Failed tests.

@vbahinwillit, Looks to have passed E2E tests after merging latest with main. Would you do another review on this PR?

**Review by vbahinwillit — APPROVED** [review]

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Pull request merged**
