### PR TITLE
Refer to WW2 on GI Bill page (fixes #2941)

### LINKED ISSUE #2941: UserVoice Idea: "Since 1994, the GI Bill has helped millions of Veterans pay for college so they can have successful civilian careers." Does not ring true.
https://www.vets.gov/education/gi-bill/

"Since 1994, the GI Bill has helped millions of Veterans pay for college so they can have successful civilian careers."

Really? Hasn't the GI Bill been around since WWII?

Even if there is a fact behind the year 1994 it doesn't make sense to anyone with a general knowledge of the GI Bill. You need to contextualize this statement.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/15897718--since-1994-the-gi-bill-has-helped-millions-of-ve

### PR DESCRIPTION
**Pull request by hollomancer**

### CODE REVIEW

**Comment by bethpotts** [comment]
@hollomancer Thank you for addressing this typo! The date appears correctly (as 1944) one level up on the L2 page (https://www.vets.gov/education/). Though you are correct that the GI Bill was signed into law toward the end of WWII, let's use the specific date rather than World War II (for specificity as well as brevity--avoiding "toward the end of WWII" or something similar). Can you update this PR to say, "Since 1944..."? I went to do it, but didn't know if I should fork it. Didn't want to mess anything up. Thanks!

**Comment by hollomancer** [comment]
Thanks @bethpotts - made the requested change!

**Comment by jcmeloni-usds** [comment]
@ayaleloehr @robbiethegeek Can we get this PR in/resolved somehow? Thanks!

**Comment by ayaleloehr** [comment]
@bethpotts is this accurate now? Or if you're not sure, who could answer that?

**Comment by jcmeloni-usds** [comment]
ping @ayaleloehr @bethpotts

**Comment by ayaleloehr** [comment]
Given @bethpotts's comments, 1944 seems like the accurate. So LGTM and we should merge.  @knkski Jenkins seems to be having issues. Can you help get this merged?

**Comment by ayaleloehr** [comment]
I just checked `master` and this seems already updated to 1944 there, so going to close. https://github.com/department-of-veterans-affairs/vets-website/blob/master/content/pages/education/gi-bill.md

**Pull request closed without merging**
