### PR TITLE
12138 Update copy on PDF Cert expiration warning

### PR DESCRIPTION
**Pull request by apisandipas**
## Summary
This PR changes the copy for the PDF Expiration Alerts on the find a form page.

## Related issue(s)
- department-of-veterans-affairs/va.gov-cms/issues/12138
 

## Testing done
Manual testing.

## Screenshots
Before: 
Screenshot 2023-01-04 at 11 12 43 AM

After:
Screenshot 2023-01-04 at 11 12 03 AM

## What areas of the site does it impact?
This effects on the the /find-forms/ page.

## Acceptance criteria
- [x] Search page – info alert updated
- [ ] Form Detail page – remove alert completely (another PR see: department-of-veterans-affairs/content-build/pull/1426)
- [n/a]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [n/a]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [n/a]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [x]  I added a screenshot of the developed feature

## Requested Feedback
 
Validate that the update text matched those requested in the ticket.

### CODE REVIEW

**Comment by jilladams** [comment]
Copy may not be final, pending https://github.com/department-of-veterans-affairs/va.gov-team/issues/51357.

**Comment by apisandipas** [comment]
Ticket has been updated with finalized copy as of 2023-01-06. PR has been updated.

**Review by jtmst — APPROVED** [review]

**Comment by jilladams** [comment]
@apisandipas in ticket body and final on https://github.com/department-of-veterans-affairs/va.gov-team/issues/51357#issuecomment-1373828339 I'm seeing copy should be: 

Search page:
Header: Use the latest version of Acrobat Reader
Body: Some VA forms may not work with older versions of Acrobat Reader. You may also need to download a new copy of the VA form.

**Review by jilladams — DISMISSED** [review]
Copy updates are not coming through. Should use copy from #12138 ticket body re: Adobe reader version.

**Pull request merged**
