### PR TITLE
Looks like EDU copy made it into the can’t save warning.

### PR DESCRIPTION
**Pull request by goldenmeanie**
It looks like some EDU copy got pasted into the "can’t save" warning. I've proposed a fix but would love for content to weigh in!

### CODE REVIEW

**Comment by ayaleloehr** [comment]
pinging @peggygannon for review

**Comment by goldenmeanie** [comment]
@bethpotts can you give this a once over since Peggy is out? I'd like to get this fixed! :)

**Comment by bethpotts** [comment]
@goldenmeanie Text looks good. We just had the wrong language in there?

**Comment by goldenmeanie** [comment]
Correct @bethpotts. Looked like copy/paste

**Review by bethpotts — APPROVED** [review]
Content looks good!

**Pull request merged**
