### PR TITLE
Update pension introduction content

### PR DESCRIPTION
**Pull request by ToddWebDev**
## Summary
On the Pension Benefits application(21P-527EZ),
On the Introduction page

Update content

## How to run in local environment
1. Check out this branch locally
2. In your local environment, set the `pension_form_enabled` flipper to 'enabled' at http://localhost:3000/flipper/features/pension_form_enabled
3. Run `vets-website` and `vets-api`

## How to verify
Unauthenticated
1. Go to `http://localhost:3001/pension/application/527EZ` in your browser
2. Verify application redirects you to the Introduction page
3. Verify content is updated to match the acceptance criteria

Authenticated 
1. Sign in via `http://localhost:3001/sign-in/mocked-auth` to authenticate your user
2. Go to `http://localhost:3001/pension/application/527EZ` in your browser
3. Verify application redirects you to the Introduction page
4. Verify content is updated to match the acceptance criteria

Saved
1. Sign in via `http://localhost:3001/sign-in/mocked-auth` to authenticate your user
2. Go to `http://localhost:3001/pension/application/527EZ` in your browser
3. Verify application redirects you to the Introduction page
4. Start new application
5. Select 'Finish this application later' on any page
6. Verify you are taken to the application saved page

Continue
1. Sign out with a saved application
2. Sign in via `http://localhost:3001/sign-in/mocked-auth` to authenticate your user
3. Go to `http://localhost:3001/pension/application/527EZ` in your browser
4. Verify application redirects you to the Introduction page
5. Verify that the resume application UI is showing

## Related issue(s)
[Ticket in Github](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69745)
[Epic in Github](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63349)

## Testing done
- [x] Existing unit tests updated
- [ ] New unit tests added

## Screenshots
_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

### Desktop
| Before | After | Authenticated | Saved | Continue |
| ------ | ------ | ------ | ------ | ------ |
|staging va gov_pension_application_527EZ_introduction|localhost_3001_pension_application_527EZ_introduction|localhost_3001_pension_application_527EZ_ (2)|localhost_3001_pension_application_527EZ_ (1)|localhost_3001_pension_application_527EZ_

## What areas of the site does it impact?
Pension Benefits Application

## Acceptance criteria
The intro page section of the 527EZ (Apply for Veterans Pension page), will have updated copy and and links within the Prepare section, as shown on the designs.

### Quality Assurance & Testing
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by TaiWilkin — CHANGES_REQUESTED** [review]
This is looking good. Two nitpicks:
- On the introduction page, in the designs it looks like "(VA Form 21-2680)", "(VA Form 21-0779)", and "(VA Form 21-2680)" should be links
- In the designs, "Your application will expire on [date]" includes the time as well as the date

**Comment by ToddWebDev** [comment]
@TaiWilkin 

> On the introduction page, in the designs it looks like "(VA Form 21-2680)", "(VA Form 21-0779)", and "(VA Form 21-2680)" should be links

I gathered the VA form details and added links to them

> In the designs, "Your application will expire on [date]" includes the time as well as the date

I believe this change is out of scope as it would require updating the SaveInProgress component which is shared across all VA forms and would require a separate requested design component change.

**Review by TaiWilkin — APPROVED** [review]
> I believe this change is out of scope as it would require updating the SaveInProgress component which is shared across all VA forms and would require a separate requested design component change.

Makes sense, thanks for explaining!
Good to go!

**Review by powellkerry — APPROVED** [review]

**Review by Midge-dev — APPROVED** [review]
LGTM

**Pull request merged**
