### PR TITLE
17765 - Change Dashboard content further.

### PR DESCRIPTION
**Pull request by tlei123**
## Description
[17765](/department-of-veterans-affairs/vets.gov-team/issues/17765) - Change Dashboard content further per [Samara's latest feedback](/department-of-veterans-affairs/vets.gov-team/issues/17765#issuecomment-487110084)

## Testing done
Verified locally in browser.
No logic-/functional-code changes.
Ran `yarn test:unit:personalization` and all unit-tests still passing.  No dashbaord-specific e2e tests exist.

### Before changes:
Screen Shot 2019-04-26 at 11 53 33 AM
Screen Shot 2019-04-26 at 11 53 55 AM

### After changes:
17765-after-changes

## Acceptance criteria
- [ ] All changes verified in browser.

## Definition of done
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by tlei123** [comment]
Not sure what the failed check's "security" tests are failing, but I'm pretty sure it's not caused by my content-changes.

**Comment by tlei123** [comment]
Sorry, @erikphansen !  The commit-history got noisy here again.

The **only** file I touched for the Dashboard add'l changes in **DashboardAppNew.jsx**, and my commit msg starts with "17765 - ...".  All other commits/files are from rebasing master.

**Comment by erikphansen** [comment]
@tzelei I'm not sure why things are getting so weird with the commit history. Can you try merging in the latest `master` into your branch to see if that cleans things up?

**Comment by tlei123** [comment]
Will do.  Watching master right now for new commits.

**Comment by tlei123** [comment]
History looks much cleaner now.  Just merged master into my branch, instead of rebase.

**Review by erikphansen — APPROVED** [review]

**Pull request merged**
