### PR TITLE
Moves changes out from behind mhvPersonalizationEnabled feature toggle

### PR DESCRIPTION
**Pull request by radavis**
## Summary

Due to [the Personalization work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72972) being blocked and confusion around which feature flags are enabled in production, visual and content changes made to the landing page (specifically, the HeaderLayout component) were not being reflected in production. 

- Removes HeaderLayoutV1 component
- Adds showWelcomeMessage prop to HeaderLayout component, which show/hides the WelcomeContainer -- the part of the page we are personalizing.
- Uses [classnames](https://www.npmjs.com/package/classnames) to break out long lines of class names into individual lines.

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#68424

## Testing done

- Tested on localhost, with and without personalization feature enabled.

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After (`mhvLandingPagePersonalization` enabled) |
| ------- | ------ | ----- |
| Mobile  |  Screenshot 2024-05-02 at 10-17-27 My HealtheVet Veterans Affairs      |  Screenshot 2024-05-02 at 10-28-37 My HealtheVet Veterans Affairs     |
| Desktop |  Screenshot 2024-05-02 at 10-16-26 My HealtheVet Veterans Affairs      |  Screenshot 2024-05-02 at 10-18-18 My HealtheVet Veterans Affairs     |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### CODE REVIEW

**Comment by jonathanjnelson** [comment]
Reviewed and this looks good @radavis!

**Review by carlosfelix2 — APPROVED** [review]
Looks fine. I tested with and w/o the personalization feature.

**Comment by radavis** [comment]
@jonathanjnelson Should the border be visible between the Headline and notification states, as well? Here's how this branch currently looks...

For Unregistered users:

Screenshot 2024-05-03 at 10-33-05 My HealtheVet Veterans Affairs

For loa1 users:

Screenshot 2024-05-03 at 10-32-33 My HealtheVet Veterans Affairs

**Comment by radavis** [comment]
Had a chat w/ @jonathanjnelson on Slack, and he was fine with the border between the heading and alerts.

**Pull request merged**
