### PR TITLE
#vfep-1575 #comment Updated 22-1995 introduction page behind feature …

### PR DESCRIPTION
**Pull request by govcioChad**
### - _(Summarize the changes that have been made to the platform)_
- Updated the language on the 22-1995 introduction page
### - _(What is the solution, why is this the solution)_
- Updated the language to properly represent the information on the 22-1995 form
### - _(Which team do you work for, does your team own the maintenance of this component?)_
- GovCIO, we are the code owners
## Related issue(s)

Jira -> https://jira.devops.va.gov/browse/VFEP-1575

As a...

VFEP Business User

I want...

to understand what I need to apply

So that...

I can complete the form in entirety

 

Acceptance Criteria:

1. The intro page to the 22-1995 needs the following updates: under the Prepare:  To fill out this application, you'll need your:

Remove the (required) after the bullet for "Basic information about the school or training facility you want to attend"
Remove the bullet "Education history"
Add the following bullets:
Benefit you have most recently used and benefit you want to change to
Sponsor information if using or want to use DEA Chapter 35 benefit
Guardian information if applicant is under the age of 18 

2. Under Decision, remove ",or award letter" 

3. Remove the The Learn more about educational programs, but keep the wording below it  "See what benefits you’ll get at the school you want to attend. [Use the GI Bill Comparison Tool"](https://staging.va.gov/education/gi-bill-comparison-tool/)

### - _Describe what the old behavior was prior to the change_
- (required) is present after "Basic information about the school or training facility you want to attend", Education History is present, ",or award letter" is present under Decision, and 'Learn more about educational programs' header is present
### - _Describe the steps required to verify your changes are working as expected_
- Above language is removed and  three new bullet points under Prepare are added. Benefit you have most recently used and benefit you want to change to, Sponsor information if using or want to use DEA Chapter 35 benefit, Guardian information if applicant is under the age of 18 
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

Before:
image
image

After: 
image
image

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by jsimonVA — COMMENTED** [review]
Why is there an IntroductionPage and and IntroductionPageUpdate?

**Review by jsimonVA — COMMENTED** [review]
@govcioChad where is the flag that keeps this in staging?

**Comment by govcioChad** [comment]
> Why is there an IntroductionPage and and IntroductionPageUpdate?

I made a separate file to avoid calling isProductionOfTestProdEnv multiple times for each line that has to be edited inside of IntroductionPage.

**Comment by govcioChad** [comment]
> @govcioChad where is the flag that keeps this in staging?

introduction in form.js calls a helper function in helpers.jsx (line 15-20) that conditionally renders IntroductionPage or IntroductionPageUpdate based on the environment.

**Review by jsimonVA — APPROVED** [review]
LGTM

**Pull request merged**
