### PR TITLE
Added VSOC learn more modal.

### LINKED ISSUE #5475: GI Bill CT: Add learn more for VSOC
Feedback from stakeholder: "Quick note, I get that VSOC isn’t available at most schools; would it be possible to hyperlink it to VSOC’s landing page anyway?  For those who don’t know what VSOC is, they’ll be like “Veterans don’t have success on this campus—pass”."

image

Since we already have approved text from the about this tool page we probably should add it to the CT as a learn more

Veteran Success on Campus (VSOC)

The VetSuccess on Campus (VSOC) program aims to help Veterans, Servicemembers, and their qualified dependents succeed and thrive through a coordinated delivery of on-campus benefits assistance and counseling, leading to completion of their education and preparing them to enter the labor market in viable careers. Read the VetSuccess on Campus (VSOC) fact sheet.
For more information visit: https://www.ebenefits.va.gov/ebenefits/vsoc  

http://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp

@leannammiller @melwoodard

### PR DESCRIPTION
**Pull request by U-DON**
Resolves #5475.

> screen shot 2017-08-09 at 2 44 04 pm

### CODE REVIEW

**Review by patrickvinograd — APPROVED** [review]
LGTM.

**Review by melwoodard — CHANGES_REQUESTED** [review]
@U-DON taking a closer look at the copy provided, I think we need the following changes:

1. The text "VetSuccess on Campus (VSOC) fact sheet" should be linked to: http://www.benefits.va.gov/vocrehab/vsocfactsheet.asp
2. You can remove the link to http://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp since it's not that useful in this context (it just reiterates the VetSuccess copy we're putting in this modal).
3. Since we always give links a description, I'm thinking we can remove the last sentence, and instead link the text in the first sentence like so "The [VetSuccess on Campus (VSOC) program](http://www.benefits.va.gov/vocrehab/vsoc.asp) aims..."

@DanielleSoCompany does #3 above sound right to you?

**Comment by U-DON** [comment]
@melwoodard: Thanks for confirming on copy. Here's what it will look like now (with the links going to the URLs you specified):

> screen shot 2017-08-10 at 12 57 40 am

**Comment by DanielleSoCompany** [comment]
Hi @melwoodard. Sorry for not being able to look at this yesterday. I had to run out unexpectedly for a doctor's appointment in the afternoon. We avoid links within running sentences, so I would recommend removing that first link and adding it as a separate link below that says "Learn more about the VetSuccess on Campus program." Would also recommend making the entire "Read the VSOC fact sheet" sentence a link to align with our style guide. In addition to that, though, this copy isn't all that plain language friendly overall. For example, the first sentence is super long and it's written in the third person POV. Are we able to offer edits to the copy? If yes, I can edit and provide. Thanks!

**Comment by melwoodard** [comment]
@DanielleSoCompany I think that's fine - would you be able to get your edit done this week and passed back to Eugene?

**Comment by DanielleSoCompany** [comment]
Thanks @melwoodard. Yes, I'm out tomorrow so I'll make sure to get it done today. Thanks!

**Comment by DanielleSoCompany** [comment]
@melwoodard @U-DON here is revised copy (proofed/copy edited by @bethpotts - thank you, beth!):

**Veteran Success on Campus (VSOC)**

This program supports Servicemembers, Veterans, and qualified dependents through on-campus counseling and help overcoming barriers—like accommodating disabilities or getting referrals to health services. It's designed to help you succeed at school and get ready to enter the job market in a promising career field.
[Download the VSOC fact sheet](http://www.benefits.va.gov/vocrehab/vsocfactsheet.asp).
[Learn more about the VSOC program](http://www.benefits.va.gov/vocrehab/vsoc.asp).

**Comment by melwoodard** [comment]
Thank you @DanielleSoCompany and @bethpotts! @U-DON revised copy above.

**Comment by U-DON** [comment]
@melwoodard

> screen shot 2017-08-11 at 2 55 37 pm

**Comment by patrickvinograd** [comment]
LGTM but @melwoodard needs to change her ❌  to ✅

**Review by melwoodard — APPROVED** [review]

**Review by melwoodard — APPROVED** [review]
Looks great, thanks for working through the copy changes!

**Pull request merged**
