### PR TITLE
Spacing changes to reflect semantics of markup

### PR DESCRIPTION
**Pull request by ncksllvn**
This was originally opened here, department-of-veterans-affairs/vets-website/pull/6753, but due to the number of files affected and resultant merge conflicts as content changed or was deleted, I'm backfilling the `.va-introlead` to match `.usa-font-lead` so many files won't have to be updated. We can change those instances later in a single sweep if we want to, but I want to keep this PR simple enough for a code reviewer to see the core of the changes.

----------

This PR addresses the issue of margins, padding, etc. not reflecting the semantics of the markup. My solution here is really just a continuation of fully integrating USWDS's design into our application. This is because semantic spacing is usually a design library's first priority, so it didn't make sense to me we would see these issues. 

I also elected not to override the USWDS font choices because I think their typography is really nice and legible, so I think it is worth a discussion and a conscious decision of whether or not we should incorporate their font decisions into our application. It is easy to go back and override these fonts, so don't worry if you don't like them. The headings may also be a bit smaller than what we're use to, so that may be worth overriding.

Tasks include:

- Modify headings to use USWDS standard font sizing and spacing
- Replace `va-intro-text` class with USWDS's equivalent `usa-font-lead` style
- Change heading font to Bitter Serif

# Issues
Resolves department-of-veterans-affairs/vets.gov-team/issues/4767
Resolves department-of-veterans-affairs/vets.gov-team/issues/5883

### Related Issues
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4497

---

# Regressions to address in this PR

- [x] Remove the special font size for H3 within `.feature` (blue boxes) 
- [x] There are some places where process list headings are either [visually larger than the higher level heading above them](https://vetsgov-pr-6753.herokuapp.com/housing-assistance/home-loans/loan-options/purchase-loan/) or [offset from the numbers next to them](https://vetsgov-pr-6753.herokuapp.com/disability-benefits/after-you-apply/). I think a good solution to address both is to make all headings within process lists look the same regardless of whether they're H4, H5, etc. by giving them all the following attributes:
   - Font size equal to H4 size
   - margin-top: 0
   - padding-top: .3em
- [x] Change H6 to non-uppercase (uppercase causes literacy issues) and bold
- [x] Remove margin-top on page titles in:
   - Facility locator - facility info page
   - All forms
   - Claim & appeal status
   - Post-9/11 GI Bill status (ch 33 benefit)
   - GIBCT
   - Prescription refills
   - Secure messaging
   - VA health records - download page
- [x] Tabbed nav layout is broken in:
   - Claim status
   - Prescription refills
- [x] Table layout is too narrow and missing gray heading in:
   - GIBCT (school profile page, student complaints section)
   - Prescription refills
   - Secure messaging
- [x] Sign in modal:
   - Remove margin-top on "Sign in to Vets.gov", "Sign in with an existing account", and "Don't have those accounts?" headings
   - Change "One site. A lifetime…" text to a `usa-font-lead` paragraph and remove margin-top
- [x] Profile page:
   - 2FA warning banner: change heading to H4, remove margin-top
   - Applications in process - remove margin-top from card headings  (blue text)
- [x] Claim status:
   - Claims list cards — remove margin-top from card headings (blue text)
   - Blue banners — remove margin-top from headings
- [x] Remove margin-top on alert banners in:
   - Health records 
   - Prescriptions
- [x] GIBCT:
   - Search results grey cards:
      - Remove margin-top on heading
      - Change everything on right side of the card ("you may be eligible...") to paragraph text / source sans pro (maintaining same bolding)
   - Detail view:
      - First accordion needs margin above it

### CODE REVIEW

**Review by melwoodard — CHANGES_REQUESTED** [review]
Thanks Nick, looking pretty good! A few more things I noticed:

- [ ] Need extra margins removed on the search results cards on GIBCT

search_results

- [ ] The bordered table change looks odd in a couple places. Please revert the table on the prescription details tab and all the tables in secure messaging back to borderless.

refill_prescriptions__vets_gov

- [ ] Need top margins removed on headings in claims and appeals: card list of claims and appeals, and blue banners in claim status.

track_claims__vets_gov

status_-_your_compensation_claim

**Comment by melwoodard** [comment]
@ncksllvn looks like not all the margins were removed on the grey cards on GIBCT, and the grey cards on claim status still need the header top margin removed too. Once you've done those can you just drop screencaps here so we don't have to do the dev deploy dance again? Thanks!

**Comment by ncksllvn** [comment]
GIBCT is better I think - 

image

I unfortunately don't have Claims set up to run locally but I saw the CSS class I missed so I feel pretty confident that one is fixed too.

I still need to changed the loading for the fonts to be local.

**Review by melwoodard — APPROVED** [review]
Much better! I think I'm safe to put a visual stamp of approval on this PR. I'd recommend getting another FE eye on this for a sanity check too @ncksllvn

**Pull request merged**
