### PR TITLE
add field for biological stepchild

### PR DESCRIPTION
**Pull request by evansmith**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- Added the field biologicalStepchild to the 686c from within childStatus in "src/applications/disability-benefits/686c-674/config/chapters/add-a-child/child-place-of-birth/child-place-of-birth.js"
-This field will now persist in the SavedClaim and InProgressForm. If neither yes or no is chosen (with the assumption adopted or biological are chosen instead of stepchild) then no value is saved.
- Benefits and Claims.
- No Flipper Used

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
[department-of-veterans-affairs/va.gov-team#0000](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61673)

## Testing done

- The old behavior did not include the biological stepchild field. This one now does and the first four children are applied to the generated pdf.
- Fill out a 686C form with a child under 18. Select them as a stepchild and then choose to indicate whether they are or are not a biological stepchild.
- Tested through multiple versions of the form. Added a spec test to confirm the presence of this new field.

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  | Screenshot 2023-08-25 at 3 54 42 PM | Screenshot 2023-08-25 at 3 50 51 PM |
| Desktop | Screenshot 2023-08-25 at 3 54 01 PM | Screenshot 2023-08-24 at 4 11 33 PM|

## What areas of the site does it impact?

686C form when adding a dependent.

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by zack — APPROVED** [review]
looks great 💪🍔👍

**Review by powellkerry — APPROVED** [review]

**Comment by tblackwe** [comment]
@evansmith on mobile, do we still ask for the date stepchild became dependent? screenshot didnt capture it

**Comment by evansmith** [comment]
@tblackwe yeah we still grab that, i left it off the screenshot.

**Review by tblackwe — APPROVED** [review]
LGTM, TY

**Review by data-doge — APPROVED** [review]

**Pull request merged**
