### PR TITLE
VetTec: Contact Information page#16440

### PR DESCRIPTION
**Pull request by zurbergram**
## Description

As a Veteran who wants to enroll in a VetTec program I need to be verify/add my contact information as part of the 0994 online interview so that it is accurate.

## Testing done
- [x] local testing
- [x] unit testing

## Screenshots
screen shot 2019-01-25 at 2 01 22 pm

## Acceptance criteria
- [x] Phone number, Email and Mailing Address are required fields and follow standard format patterns 
- [x] Alternate phone number is not required but if entered it will follow standard format pattern
- [x] The user has the ability to edit the information on this page
- [x] The content of the contact information page matches the screenshot below
- [x] Contact Information page content: 
image
image

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by devin-mccurdy — APPROVED** [review]

**Comment by dmccurdybah** [comment]
LGTM!

**Comment by zurbergram** [comment]
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!

**Review by robfelder — APPROVED** [review]
LGTM!

**Review by rianfowler — APPROVED** [review]
LGTM

**Pull request merged**
