### PR TITLE
VAGOV-6419: Updating facility page text.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
Minor updates to facility page text - see side by side (before and after) screenshots, below.

## Testing done
Visual

## Screenshots
image
image

### CODE REVIEW

**Comment by bkjohnson** [comment]
Hey @ethanteague, the next time you are working on a PR please follow [these guidelines](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/code_review_guidelines.md#the-pull-request-review-lifecycle-in-brief).  Here are some highlights:

> 1. For initial review by your project team, create a Draft Pull Request
> 2. Once you are ready for the VSP team to review your PR, use the GitHub Ready for review button in the merge section of your pull request

We ask this because the frontend review group receives participating notifications for every non-draft PR.  If we receive notifications about PRs that are not ready for us to review (i.e. they have not been peer-reviewed) then it clogs up the notification queue.  The `needs peer approval` label can help us deal with this, but we still end up seeing the PR before it is ready for us.

**Comment by ethanteague** [comment]
> Hey @ethanteague, the next time you are working on a PR please follow [these guidelines](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/code_review_guidelines.md#the-pull-request-review-lifecycle-in-brief). Here are some highlights:
> 
> > 1. For initial review by your project team, create a Draft Pull Request
> > 2. Once you are ready for the VSP team to review your PR, use the GitHub Ready for review button in the merge section of your pull request
> 
> We ask this because the frontend review group receives participating notifications for every non-draft PR. If we receive notifications about PRs that are not ready for us to review (i.e. they have not been peer-reviewed) then it clogs up the notification queue. The `needs peer approval` label can help us deal with this, but we still end up seeing the PR before it is ready for us.

Will do, @bkjohnson :+1:

**Review by swirtSJW — APPROVED** [review]
Code looks good.

**Review by bkjohnson — APPROVED** [review]
:+1:

**Pull request merged**
