### PR TITLE
Scroll to errors on edu benefits form

### LINKED ISSUE #3330: Check scrolling on form submissions with errors
In at least one case when an error is triggered on page submission, the page is scrolling to a point that does not correlate to the actual error.

This is probably worth checking for all errors. It currently is happening on Military history if someone chooses to apply the service period to a different benefit and does not select which benefit. In this case it sends you to the top of the tour section instead of the top of the error.

### PR DESCRIPTION
**Pull request by jbalboni**
Closes #3330 

This scrolls to the first invalid input element and sets focus.

### CODE REVIEW

**Comment by jbalboni** [comment]
@cweber @goldenmeanie Can one of you try this out and make sure it works the way you expect?

**Review by akainic — COMMENTED** [review]
This looks great! One thing I noticed is that on date fields it scrolls past the error message. Maybe we can make an exception for if it's a date field and handle that differently?

screen shot 2016-12-09 at 3 26 32 pm

**Comment by cweber** [comment]
LGTM. 

One thing I noticed, but I don't think needs to be fixed: 
When the error that triggers the scroll is a date component, the alignment with the top of the screen is weird. The label for that component gets cut off. I'm guessing it has something to do with being a more complex component.

Samesies Anne!

**Comment by jbalboni** [comment]
I think we can some top margin to the scroll position to capture the error message. Should still look fine for other fields.

**Comment by jbalboni** [comment]
@cweber @akainic Added code to handle dates specifically, so this should work better now.

**Review by akainic — APPROVED** [review]
LGTM! Thanks for adding the handling of date inputs differently. Looks awesome.

**Pull request merged**
