### PR TITLE
Improved z-index layering for menus. closes #5180

### LINKED ISSUE #5180: Z-index bug
Nav drop-downs aren't overlaying properly

screen shot 2017-03-28 at 8 55 38 am

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by phiden** [comment]
LGTM

**Comment by tiffanybbrown-va** [comment]
Fix one problem, cause another ... Now borked on mobile. Don't merge this PR until I update this comment.

**Review by cvalarida — APPROVED** [review]
Looks good! Tested against a modal and mobile. Both seem to work swimmingly.

**Comment by raquelromano-gov** [comment]
LGTM

**Comment by jcmeloni-usds** [comment]
👍

**Pull request merged**
