### PR TITLE
Add Prepare for Appointment section for cc appointments

### PR DESCRIPTION
**Pull request by JunTaoLuo**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

## Summary

- Add "Prepare for your appointment" section to cc appointments.
- This feature is toggled by the Flipper flag `va_online_scheduling_med_review_instructions `
- Appointments (VAOS) team

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/89495

## Testing done

- Unit tests updated to account for the new content
- The new content (text and link) is verified locally with the feature toggle enabled

## Screenshots

New screenshots:

| Confirmed Appointment | Cancelled Appointment | 
| - | - |
| image | image |

## What areas of the site does it impact?

N/A

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
@outerpress I noticed that in the mockups there is a small gap/margin between the heading "Prepare for appointment" and the content below. However, I removed this gap since all other sections, e.g. "When", "Provider", don't have this gap to make the UI more consistent. Just wanted to make sure that made sense to you and if it does should I update all the other appointment types (including ones with lists or only the ones without lists)?

**Comment by outerpress** [comment]
> @outerpress I noticed that in the mockups there is a small gap/margin between the heading "Prepare for appointment" and the content below. However, I removed this gap since all other sections, e.g. "When", "Provider", don't have this gap to make the UI more consistent. Just wanted to make sure that made sense to you and if it does should I update all the other appointment types (including ones with lists or only the ones without lists)?

@JunTaoLuo good catch! You're correct and I'll update the designs to remove the erroneous gap. Thank you!

**Comment by JunTaoLuo** [comment]
Thanks @outerpress! @ryanshaw @simiadebowale this PR is ready for review then. I'll update the video appointment PR and let you know when that's ready as well.

**Review by simiadebowale — APPROVED** [review]
LGTM!

**Pull request merged**
