### PR TITLE
MHV landing page design tweaks

### PR DESCRIPTION
**Pull request by batemapf**
## Summary

- *(Summarize the changes that have been made to the platform)*
- *(If bug, how to reproduce)*
- *(What is the solution, why is this the solution)*
- *(Which team do you work for, does your team own the maintenance of this component?)*
- *(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)*

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/54087
- *Link to ticket created in va.gov-team repo*
- *Link to previous change of the code/bug (if applicable)*
- *Link to epic if not included in ticket*

## Testing done

- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected*
- *Describe the tests completed and the results*
- *Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)*

## Screenshots
_Note: This field is mandatory for component work and UI changes (non-component work should NOT have screenshots)._

| | Before | After |
| --- | --- | --- |
| Mobile | | [Screen Shot 2023-03-03 at 12 39 11-fullpage](https://user-images.githubusercontent.com/279327/222790453-036255dc-2aab-4fad-ad58-6a504a58df97.png) |
| Desktop | | [Screen Shot 2023-03-03 at 12 38 42-fullpage](https://user-images.githubusercontent.com/279327/222790552-cee6635a-d9c1-4790-a82f-fd5c9d916f0b.png) |

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature
- [ ]  [Accessibility foundational testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by dcloud** [comment]
After not seeing the MHV logo I added appear in staging, I learned that the logo needs to be [added to the content-build](https://depo-platform-documentation.scrollhelp.site/developer-docs/s3-bucket-locations) (or served from an s3 domain URL, but why would want to do that). I'll grab the image you've updated here and put it into a content-build PR

**Comment by dcloud** [comment]
Added department-of-veterans-affairs/content-build/pull/1491 for logo image in content build repo

**Comment by dcloud** [comment]
Screenshot with all the tweaks so far, including less bold headings:

Screen Shot 2023-03-02 at 14 25 49-fullpage

Mobile one:

Screen Shot 2023-03-02 at 14 27 24-fullpage

**Review by mdewey — APPROVED** [review]
LGTM

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Pull request merged**
