### PR TITLE
Content/wip/update disability claim time january

### PR DESCRIPTION
**Pull request by kellyskennedy**

### CODE REVIEW

**Comment by kellyskennedy** [comment]
@peggygannon this is ready for your copy-edit/review. Thanks!

**Review by peggygannon — APPROVED** [review]
@kellyskennedy the updates look good to me. The only odd thing is that the previous copy is showing the month of October.. shouldn't it be showing December? I just want to make sure there is nothing wonky with the files.

**Comment by kellyskennedy** [comment]
@phiden can you review and merge, please? It's one of those 24-hour jobbies. Thanks!

**Comment by kellyskennedy** [comment]
Also, @ncksllvn When Peggy and I went through this, we spotted some weirdness: The copy should have said "December" after last month's update, but for me, it said "November," and for Peggy, it said "October. The live site says "December." Is this anything we need to be concerned about? Thanks!

**Review by phiden — APPROVED** [review]

**Comment by ncksllvn** [comment]
@kellyskennedy @peggygannon This branch was created on December 1st and was outdated, so the changes weren't up-to-date and things were appearing a little weird. But @phiden brought in the latest changes (by merging master into this branch) and got things back on track. The latest changes from December to January should be accurate. If you notice anything weird though definitely let me know.

**Pull request merged**
