### PR TITLE
Form 781/781a: Write e2e tests for all functionality in the launched product#15226

### PR DESCRIPTION
**Pull request by zurbergram**
## Description
As a MVP development team, I need to write e2e tests so that we have full test coverage.
End to end testing documentation is located in [GitHub](https://github.com/department-of-veterans-affairs/vets-external-teams/blob/master/DeveloperDocs/testing/end-to-end-testing.md).

## Acceptance criteria
1. Automated e2e tests exist for all functionality in for 781 & 781a
1. All automated 781 and 781a e2e tests run successfully

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by zurbergram** [comment]
@department-of-veterans-affairs/code-reviewers-for-external-teams-group - This is PR that is carrying over from BAH

**Comment by jbalboni** [comment]
@zurbergram Can you fix the build errors and also get a review from someone on your team?

**Comment by zurbergram** [comment]
@jbalboni Unfortunately today is our last day on the project and you will not have time to resolve all of the build errors along with other errors caused by pages that have possibly changed since last commit to this PR.

**Comment by zurbergram** [comment]
not all of the pages are being tested because of odd issues occurring and max test data not having real proper values for things (“First Condition” is not a disability), additional many of the tests will probably need updates to account for any schema changes

in order to finish the work every page in the max flow (not really max because some yes/no block paths to other pages) would need to be finished and while a large majority of these are done there have been several new pages added before you even get to 781/a

additionally 4142 e2e tests weren’t working as expected and there are no e2e tests beyond the currently failing 4142 e2e tests (well there might be cause a lot of commented out tests in the e2e file but no guarantee these are the tests that are needed)

**Comment by jbalboni** [comment]
Ok, so this isn't something you want a review on, it's something you're handing over to another team?

**Comment by zurbergram** [comment]
Correct

**Pull request closed without merging**
