### PR TITLE
Add divider to .va-h-ruled--stars

### PR DESCRIPTION
**Pull request by ghost**
Related to department-of-veterans-affairs/vets.gov-team#2555
Blocks #5479

### CODE REVIEW

**Comment by tiffanybbrown-va** [comment]
# Screen shots of the new divider

## Desktop > 1200px breakpoint 

newdivider-fullpage

## Mid-range 768px viewport

screen shot 2017-05-02 at 19 20 01

## Smallest < 768px viewport
screen shot 2017-05-02 at 19 19 48

**Review by melwoodard — CHANGES_REQUESTED** [review]
Awesome, looks good and very close, a few adjustments:

- decrease the stars image width to be 11rem
- decrease the divider height to 1px
- make the margin between stars and dividers on either side ~12px

**Comment by tiffanybbrown-va** [comment]
Ready for a re-review.

**Review by melwoodard — APPROVED** [review]
LGTM!

**Comment by melwoodard** [comment]
@tiffanybbrown-va I'd like to get all of the homepage PRs wrapped up into a single PR that we can share with folks to preview before launch. What's the best way to do that?

**Comment by melwoodard** [comment]
Sorry, was a minute too late :(

**Comment by tiffanybbrown-va** [comment]
The good news, if there is any, is that this PR probably caused merge conflicts in some others. I'll merge them into a single branch.

**Pull request merged**
