### PR TITLE
bradl3yC - 5865 - screen reader reading previous modal twice

### PR DESCRIPTION
**Pull request by bradl3yC**
## Description
- [x] - remove aria-live from modal field inputs

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by erikphansen — APPROVED** [review]

**Comment by jenstrickland** [comment]
@bradl3yC Just checked on JAWS + ie11. The first time through the flow, it worked as we hoped, but the second time it repeated the previous behavior. Here's what I tested and experienced:

1. Edit mailing address, pressed Update
2. Read Please confirm your address, selected `edit it` link
3. Returned to Edit mailing address, selected Update
4. Screen reader continued reading the Edit mailing address form again

**Comment by bradl3yC** [comment]
@1Copenut any idea why this may be happening? I'm really at a loss.  I'm assuming its a prop change causing the modal to refresh before its exiting the DOM.  We may be able to remove the modal sooner.

**Comment by jenstrickland** [comment]
Is it possible to put `display:none` on the modal that is not visible to sighted users, so it also isn't in the DOM & a11y tree?

**Comment by bradl3yC** [comment]
@jenstrickland if you pull and test the latest code, I believe its fixed now.  Trevor tested last night and the issue seems to have been resolved.

**Comment by jenstrickland** [comment]
@bradl3yC Let me know when it's available on staging and I'll test again.

**Comment by bradl3yC** [comment]
@department-of-veterans-affairs/frontend-review-group ready for review 👍

**Review by jhonny218 — APPROVED** [review]
LGTM

**Comment by jenstrickland** [comment]
The content is still not reading properly. When I hit `edit it` and go back to Edit mailing address, instead of reading the modal, I hear 575 20th Ave, San Francisco… the address content on the Profile page.

**Comment by jenstrickland** [comment]
For testing, please let me know when you have something in staging, and we can hop on a call on my Windows laptop to test. JAWS bugs can be tricky.

**Comment by bradl3yC** [comment]
@jenstrickland this PR is closed/merged - comment on the card itself for visibility

**Pull request merged**
