### PR TITLE
Update alert for no recent visit in the request flow

### PR DESCRIPTION
**Pull request by jenniemc**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

### :warning: TeamSites :warning:
Examples of a TeamSite: https://va.gov/health and https://benefits.va.gov/benefits/. This scenario is also referred to as the "injected" header and footer. You can reach out in the `#sitewide-public-websites` Slack channel for questions.

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

Update the alert message in the request flow when there is no recent visit eligibility

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#96999

## Testing done
unit and e2e

## How to test locally
**Scenario:**

Request is enabled
Facility requires a recent visit
AND User doesn’t have a recent visit (VATS: noRecentVisit)
AND DS are disabled

### Steps to test
___
1. Update `scheduling_configurations.json` to enable the request toggle to `true` in amputation care for facility 984 and 983
```
      "id": "984",
      "type": "scheduling_configuration",
      "attributes": {
        "facilityId": "984",
        "services": [
          {
            "id": "amputation",
            "name": "Amputation Services",
            "stopCodes": [{ "primary": "211" }],
            "direct": { "canCancel": true, "enabled": false },
            "request": { "enabled": true }
          },

```

```
      "id": "983",
      "type": "scheduling_configuration",
      "attributes": {
        "facilityId": "983",
        "services": [
          {
            "id": "amputation",
            "name": "Amputation Services",
            "stopCodes": [{ "primary": "211" }],
            "direct": {
              "patientHistoryRequired": true,
              "patientHistoryDuration": 365,
              "canCancel": true,
              "enabled": false
            },
            "request": { "enabled": true }

```
2. Replace "facility-request-limit-exceeded" with "patient-history-insufficient"  in `mocks/index.js` on line 462 to match below
```
    if (!isDirect && !req.query.facility_id.startsWith('983')) {
      ineligibilityReasons.push({
        coding: [
          {
            code: 'patient-history-insufficient',
          },
        ],
      });
    }
```
3. Make a new amputation appointment using Dayton VAMC
## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile |   Screenshot 2024-12-09 at 11 50 52 AM     |   Screenshot 2024-12-09 at 10 57 54 AM    |

## What areas of the site does it impact?

Eligibility alert message

## Acceptance criteria

- [ ] Alert is updated
- [ ] Update unit tests
- [ ] Update/create e2e test

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Review by JunTaoLuo — APPROVED** [review]
LGTM!

**Review by simiadebowale — APPROVED** [review]
LGTM

**Comment by melissa-lefevre** [comment]
LGTM, thanks!

**Pull request merged**
