### PR TITLE
[Development] Use sentence-case in ArrayField

### PR DESCRIPTION
**Pull request by Mottie**
## Description

Change the "Add Another" title case to use sentence case per design feedback in https://github.com/department-of-veterans-affairs/va.gov-team/issues/12678

This is a **global** change to the form system

Doc update: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/387

## Testing done

Updated `ArrayField` tests

## Screenshots

<details><summary>Sample "Add another" buttons from form 526</summary>

Screen Shot 2020-08-31 at 2 31 57 PM
Screen Shot 2020-08-31 at 2 31 47 PM
Screen Shot 2020-08-31 at 2 31 28 PM
Screen Shot 2020-08-31 at 2 31 11 PM
Screen Shot 2020-08-31 at 2 30 52 PM
</details>

## Acceptance criteria
- [x] Use of sentence case in "Add another" buttons

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by ndsprinkle — APPROVED** [review]

**Review by micahchiang — APPROVED** [review]

**Comment by meganhkelley** [comment]
Please hold off on this pending design system council discussion in Slack cc @Mottie @KevinMHoffmanUSDS

**Comment by Mottie** [comment]
I ended up adding an `itemNameLowerCase` option (I know it's not ideal) to go along with the existing `itemName` option. That way we control what is being added. It's still a change to the platform code, but not as dramatic as adding code to convert strings to title, sentence or lower case.

**Comment by meganhkelley** [comment]
@Mottie would this affect existing forms? and can you please restate the change you're proposing? my understanding is this change allows developers to customize the casing of all "Add another" buttons on VA.gov. is that correct?

**Comment by Mottie** [comment]
> @Mottie would this affect existing forms? and can you please restate the change you're proposing? my understanding is this change allows developers to customize the casing of all "Add another" buttons on VA.gov. is that correct?

As this update stands, it adds a global `itemNameLowerCase` option (horrible name, I know) to the `ArrayField` code in the `platform` folder (owned by VSP), but currently only form 526 is utilizing this new option to make the "Add another {whatever}" buttons include lower cased text.

**Comment by meganhkelley** [comment]
ok thanks @Mottie ! to confirm: 

* this change means that developers could, moving forward, make "Add another" buttons lowercase
* developers will still also be able to make "Add Another" buttons title case 
* this will not change any other forms live on VA.gov

what about: 
* developers will (??? will not ???) be able to use custom casing (for a button that might in the future say "Add another Veteran"?) 
* we should add a ticket to our backlog to document this new option?

**Comment by Mottie** [comment]
Oh, this change is also globally making the word "another" lower case, so non-526 forms would show "Add another Something" - mixed title case. Hmmm, that might not be good.

The way things are set up, a developer will add title case text to the `itemName` option, and lower-cased content to the `itemNameLowerCase`. The `itemNameLowerCase` option can be left blank and the button will include the `itemName` instead.

**Comment by meganhkelley** [comment]
Got it! I'm going to huddle with VSP Design & with Kevin H on this and hope to get back to you tomorrow

**Comment by meganhkelley** [comment]
Hi @Mottie based on your comment yesterday it sounds like there are still some pieces to think through in how this would affect other forms (I agree that the `Add another Something` affect on all other forms is not desirable). 

Is there a path forward that allows y'all to change the casing on the 526 `Add Another` button, but not force a change to all other forms? Can we simply remove the casing rules on that button?

Whatever the proposal is will need a 👍 from VSP FE and/or design system council (depending on the change), but I'm trying to brainstorm options — what do you think?

**Comment by Mottie** [comment]
In the `fileUploadUI` is a `addAnotherLabel` option, which I can duplicate in the `ArrayField` code. I'll make it default to use title-case (`Add Another`). Then in form 526, I'll include this extra option to make the buttons show sentence-cased wording. I'll work on this tomorrow.

**Comment by Mottie** [comment]
Changed `itemNameLowerCase` to `addAnotherLabel` & limited content change to only all-claims forms.

**Comment by Mottie** [comment]
@meganhkelley Would your team please check this PR again? It now only makes changes (globally) to the button text using the `addAnotherLabel` setting.

**Comment by meganhkelley** [comment]
Hi @Mottie ! Apologies for the delay — I need to follow up with Kevin again real quick on this one and will get back to you tomorrow. (We're discussing process, whether we should just address this as a global change now on VSP and remove it as a launch blocker for your team, etc).

**Comment by cvalarida** [comment]
Heya! I wanted to circle back around to this and make sure we're all on the same page.

## Background
This change was prompted by VSP design review. There was some misunderstanding that this would require a global change when the review was left. After discussing it with the design system council, we were all in agreement that sentence-casing the "Add Another..." buttons for array fields
- Is not a blocker for BAM1
- Should be applied globally, not just to the 526
- Is VSP's responsibility to implement the change globally

## Action items
- I'm closing this PR to get it off @Mottie's plate
  - I don't think we should merge it as-is because we want a more global approach
  - We'll keep the branch so we can use the parts we want to keep of what you've already written to make sure you get credit for your work
- VSP will prioritize making this change against the rest of the forms library system changes

---

Thanks for writing this, @Mottie, and for bearing with us while we work through iterating on the design review process.

**Comment by cvalarida** [comment]
I created [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13684) to keep track of the remaining work for VSP.

**Pull request closed without merging**
