### PR TITLE
Use production build settings for staging

### PR DESCRIPTION
**Pull request by jkassemi**
Removes debug toolbars and sets up standard source-map generation (without eval) for the staging environment. Parity improvement for staging/production.

Enables better testing of CSP header on staging environment (to avoid an `unsafe-eval` declaration).

Part of work for https://github.com/department-of-veterans-affairs/vets.gov-team/issues/611

### CODE REVIEW

**Comment by robbiethegeek-usds** [comment]
@jkassemi is this ready for review?

**Comment by jkassemi** [comment]
Yes, this is ready.

**Comment by robbiethegeek-usds** [comment]
LGTM @crwallace @aub @alexose-gov  any concerns?

**Comment by aub** [comment]
LGTM as well.

**Comment by crwallace** [comment]
LGTM

**Review by crwallace — APPROVED** [review]

**Pull request merged**
