### PR TITLE
[Rx] Arranged sort menu and view toggle to be on the same line.

### PR DESCRIPTION
**Pull request by U-DON**
Closes department-of-veterans-affairs/vets.gov-team#757.

### CODE REVIEW

**Comment by U-DON** [comment]
@gnakm Now in list view, there is a lot of space left of the toggle. Is this okay?

> screen shot 2017-01-18 at 7 47 43 pm

**Comment by gnakm** [comment]
Thanks for flagging. Could we then flip it a bit so that the description and view toggle are aligned and the sort is on the next line? In addition, could you unbold `View:`

List view
screen shot 2017-01-19 at 10 54 01 am

Card view
screen shot 2017-01-19 at 10 54 23 am

**Comment by U-DON** [comment]
Updated. @gnakm @bshyong 

#### Card View
> screen shot 2017-01-19 at 1 49 02 pm

#### List View
> screen shot 2017-01-19 at 1 49 16 pm

**Comment by gnakm** [comment]
lgtm!

**Pull request merged**
