### PR TITLE
Update apply-for-benefits.md

### PR DESCRIPTION
**Pull request by rcarthur**
@dannychapman  - Please merge the September update. Thanks!

@koconnor719

### CODE REVIEW

**Comment by dannychapman** [comment]
LGTM, please review @maryannbrody so we can merge. Thanks!

**Comment by maryannbrody** [comment]
LGTM @dannychapman -- this can be merged and then go to production.

**Comment by rcarthur** [comment]
@plusjeff  Do you know when this is scheduled to go live? This is high vis for VBA. Thanks!  
@dannychapman @koconnor719

**Comment by plusjeff** [comment]
@rcarthur I believe this went live yesterday with the deployment.

**Comment by rcarthur** [comment]
@plusjeff thanks, Jeff.

**Pull request merged**
