### PR TITLE
[Check-in] Add params to common errors for analytics

### PR DESCRIPTION
**Pull request by brdunfield**
## Description
This PR passes some URL params to the error page with many common (and easy to code discern) errors to assist with analytics understanding until we are able to better refactor how our error pages work.

I would appreciate a sanity check on all of these to make sure I correctly interpreted the error from the code. All calls should now have a param passed with them. ~~Also, I didn't add params to all the `goToErrorPage()` calls, as some (mostly around request errors) felt like there isn't one specific reason we could point to in a param there. If you think I missed any calls that *should* have a param, let me know.~~

## Original issue(s)
department-of-veterans-affairs/va.gov-team#45777

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by brianseek** [comment]
I think we should add one on the AppointmentAction.jsx check-in button click. Something like `check-in button fail`

For some of the other generic ones, I wonder if it would be helpful to send the page it was referred from. For example, we could do `error-unknown-from-[page]` 

Is that redundant since GA lists the previous page? I'm open to just leaving them blank for now.

**Comment by brdunfield** [comment]
cc @benbrasso-agile6 for Brian's question above - do you have any thoughts on what you'd prefer?

**Comment by loripusey** [comment]
I like Brian's idea

**Comment by benbrasso-agile6** [comment]
The view/report in GA that lists previous pages can be cumbersome. So, I think I'd stick to a strategy that includes having the unique identifier of what the error is in the url param. For example, the param value could be the page title, url, etc.

If there's a list here of the specific one we're talking about, I either can't see it or don't know how to see it. Hopefully my previous answer provides enough information.

**Review by brianseek — APPROVED** [review]
LGTM!

**Pull request merged**
