### PR TITLE
20-10206 & SaveInProgressIntro - Migrate Introduction-page SIP-alerts to v3-web-components.

### PR DESCRIPTION
**Pull request by tlei123**
## Summary

- Migrate all Introduction-page SIP-alerts to v3-web-components
- Team: Veteran Facing Forms
- Flipper ON in Staging, OFF in Prod. End-date TBD.

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#72155

## Testing done

- Local browser-, unit-, & e2e-tests all successful

## Screenshots

**Note**: Saved-form alerts \[last 2 rows\] now have icons.

|         | Before | After |
| ------- | ------ | ----- |
| Unauth’ed | image | image |
| Auth’ed, with prefill | image | image |
| Auth’ed, no prefill | image | image |
| Auth’ed, saved form | image | image |
| Auth’ed, saved form expired | image | image |

## What areas of the site does it impact?

Appearance of ALL forms’ Introduction-page SIP-alerts.

### CODE REVIEW

**Review by longmd — APPROVED** [review]
Looks good with regards to the HCA. Glad we're getting these rolled out to USWDS v3 styling. 🚀

**Comment by tlei123** [comment]
Announcements posted on Slack channels [#veteran-facing-forms](https://dsva.slack.com/archives/C044AGZFG2W/p1704297614954529) & [#vfs-change-announcements](https://dsva.slack.com/archives/C03R5SBELQM/p1704297322502879) to give VFS teams 'til Thu next week (1/11) to test and report any issues.

**Review by Mottie — APPROVED** [review]
Thanks!

**Review by rhasselle-oddball — APPROVED** [review]
Looks good, it's good that this is just scope to saving progress intro. 
Before merging, can you test this change on forms that previously used custom CSS based on the previous selectors?

**Pull request merged**
