### PR TITLE
WIP/Content/curly quote fix

### PR DESCRIPTION
**Pull request by peggygannon**
Updating quotation marks sitewide to make them consistent. 

Connects to department-of-veterans-affairs/vets.gov-team#3390

### CODE REVIEW

**Comment by peggygannon** [comment]
@bethpotts  Hi, Beth, this PR is ready for your review. There are two conflicting files, which I will need Bob's help to resolve (I can't figure out what the conflict is).  Also, some of the red Xs in the PR seem to be related to a Jenkins build error.

**Review by bethpotts — APPROVED** [review]
Edits look good. Approved!

**Comment by bethpotts** [comment]
@peggygannon Amy doesn't need to approve this one, so you can you ahead and ask for it to be merged.

**Comment by peggygannon** [comment]
@phiden Hi, Sophia, this PR is ready for your review and merge! Thank you.

**Review by phiden — CHANGES_REQUESTED** [review]
Why were the address blocks changed back to `<dd>` tags? Per https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3859 they should remain `<p>`s and `<br>`s

**Comment by peggygannon** [comment]
@bethpotts Did you update the address blocks in this PR? (see Sophia's query above)

**Comment by bethpotts** [comment]
@phiden @peggygannon I didn't change address blocks either. I suspect some of them got reverted back when Bob merged master into this branch. How can we help you fix this, Sophia?

**Comment by phiden** [comment]
No worries @bethpotts @peggygannon -- I'll change them back! Just wanted to be sure there wasn't some rhyme or reason for the change I wasn't aware of. :)

**Review by phiden — APPROVED** [review]

**Pull request merged**
