### PR TITLE
Update desktop appointment list view

### PR DESCRIPTION
**Pull request by jenniemc**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

## Summary

This PR updates the appointment list for the desktop view to match [Figma](https://www.figma.com/design/dnfMEuJi3EiK2Tub51oD6f/Remove-truncation-on-appt-list-(desktop-view)-%7C-Appointments-FE?node-id=1-52&t=reWBcMbmrvgs3cs7-0)

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#89119

## Testing done

Visual Inspection

## Acceptance criteria
- [ ] When the user is on the Upcoming list
       Then the spacing will be updated for desktop users
       And page design matches the [design spec](https://www.figma.com/design/dnfMEuJi3EiK2Tub51oD6f/Remove-truncation-on-appt-list-(desktop-view)-%7C-Appointments-FE?node-id=1-52&t=rzxrQfCl3NjjG5jA-0)

- [ ] When the user is on the Past list
       Then the spacing will be updated for desktop users
       And page design matches the [design spec](https://www.figma.com/design/dnfMEuJi3EiK2Tub51oD6f/Remove-truncation-on-appt-list-(desktop-view)-%7C-Appointments-FE?node-id=1-52&t=rzxrQfCl3NjjG5jA-0)

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._
|         | **Upcoming** |
| ------- | ----- |
| Before  |    Screenshot 2024-08-14 at 1 25 09 PM  |
| After |     Screenshot 2024-08-13 at 10 38 03 AM      |
|         |    **Past Appointments** |
| Before  |   Screenshot 2024-08-14 at 1 25 54 PM  |
| After |    Screenshot 2024-08-13 at 10 37 36 AM  |

## What areas of the site does it impact?
Vaos Upcoming and Past appointment list page

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
@outerpress do we want this for pending appointments (i.e. requests) too?

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Comment by outerpress** [comment]
> @outerpress do we want this for pending appointments (i.e. requests) too?

@JunTaoLuo no, the pending list has a very different layout - no dates/times for example. So far we haven't seen a need to adjust that one. Good question though, thank you! FYI @jenniemc

**Review by vbahinwillit — APPROVED** [review]
LGTM!

**Review by JunTaoLuo — APPROVED** [review]
Thanks @outerpress  for double checking. Changes look good!

**Pull request merged**
