### PR TITLE
Brand Consolidation Disability Hub and Sidenav

### PR DESCRIPTION
**Pull request by RobAWilkinson**
## Description
Sets up disability hub and homepage links

Refactors `how-to-file-a-claim` to `how-to-file-claim` sitewide.

## Testing done
Local testing, checked all links for validity

## Acceptance Criteria (Definition of Done)
Disability Hub is complete and all pages conform to designs
#### Applies to all PRs

- [x] Appropriate logging
- [x] Documentation has been updated, if applicable
- [x] Provide link to originating GitHub issue, or connected to it via ZenHub
- [x] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [x] Provide which alerts would indicate a problem with this functionality (if applicable)

Closes multiple issues https://app.zenhub.com/workspace/o/department-of-veterans-affairs/vets.gov-team/issues/12931

and https://app.zenhub.com/workspace/o/department-of-veterans-affairs/vets.gov-team/issues/12772

### CODE REVIEW

**Comment by accbjt** [comment]
@RobAWilkinson I took a look and there are some links that are missing or out of order. Make sure you have all the links down to the lowest level in the correct order. Here is the list I have been working off of. Let me know if you have any questions.

https://docs.google.com/spreadsheets/d/1SsA5RVkERpMF8DE4Oal7fy4dK617JkdJgMQ2zrRdJXc/edit#gid=1082032970

**Review by ncksllvn — APPROVED** [review]
LGTM 🚀

**Comment by DanielleSoCompany** [comment]
Hi @RobAWilkinson @ncksllvn @accbjt. I got a notification to review this PR. It looks like it was already merged, but I did see some things that I wanted to bring to your attention. Will  be adding them here in a moment.

**Comment by ncksllvn** [comment]
@DanielleSoCompany Copied your comment into this ticket - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/12950

**Pull request merged**
