### PR TITLE
[Due April 6] Redirects in Education based on parity work

### PR DESCRIPTION
**Pull request by ncksllvn**
## Description
Adds a bunch of redirects into the proxy-inject script.

Ticket - https://github.com/department-of-veterans-affairs/va.gov-team/issues/2052

## Acceptance criteria
- [x] Redirects are setup correctly

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by lunascoop — COMMENTED** [review]
Should this be here?

See my other comment below

**Review by lunascoop — COMMENTED** [review]
"domain": "www.benefits.va.gov",
    "src": "/gibill/non_college_degree.asp",
    "dest": "/education/about-gi-bill-benefits/how-to-use-benefits/non-college-degree-programs/ **note below"**.  <- Should the "Note below" be there?

**Comment by ncksllvn** [comment]
@lunascoop nice catch! that's why I assigned you for review 🙂

**Review by kelsonic — APPROVED** [review]
LGTM! 🎉

**Pull request merged**
