### PR TITLE
Remove vic-v2

### PR DESCRIPTION
**Pull request by bkjohnson**
## Description

This removes the `vic-v2` app.

It also removes the `<RateLimiter>` component which was only used in `vic-v2`.  This component was using `window.settings`, and removing it will [help us remove `settings.js`](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1973)

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by ncksllvn — APPROVED** [review]

**Comment by ncksllvn** [comment]
Just curious - does the launched VIC app include all of the features of this one? I never knew the differences.

**Comment by jbalboni** [comment]
@bkjohnson I think you could also remove the `react-cropper` package as part of this PR.

@ncksllvn I don't know what VIC looks like now, but if it's largely the same as it was a couple years ago, then no. This one is a much cleaner form and has a much richer photo upload/cropping experience. This was meant to be an improvement to the VIC app that launched before it, but it never launched for...reasons.

**Comment by bkjohnson** [comment]
@jbalboni I think I'll need to remove [this file from `vets-json-schema`](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/VIC-schema.json) in order for that [remaining test](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/vets-website/3397/workflows/2a40cb85-b253-427e-9590-99cc0573883a/jobs/18244/tests) to pass - does that seem right?

**Comment by jbalboni** [comment]
@bkjohnson yeah, I think that makes sense. That could impact vets-api, too.

**Review by rianfowler — APPROVED** [review]

**Pull request merged**
