### PR TITLE
Updated 97.1 to 99.4 days to complete claim

### PR DESCRIPTION
**Pull request by kellyskennedy**

### CODE REVIEW

**Comment by kellyskennedy** [comment]
Hi @peggygannon Could you give this a look? It's a CURF. Thanks!

**Review by peggygannon — APPROVED** [review]
@kellyskennedy I updated the month. Otherwise it looks good.

**Comment by peggygannon** [comment]
@bethpotts ready for your ME review.

**Review by bethpotts — APPROVED** [review]

**Comment by kellyskennedy** [comment]
Hi @ncksllvn Could you review and merge this, please? Thanks!

**Review by ncksllvn — APPROVED** [review]
LGTM

**Pull request merged**
