### PR TITLE
Update apply.md

### PR DESCRIPTION
**Pull request by bethpotts**
Hi Courtney, 
Mary Ann wanted your opinion on a callout box I'm suggesting we add to this page in the upper right. I would like to move the language/link (and rewrite it a bit) from the first bullet under "Additional forms for caregivers...": Update income from a previous application (10-10EZR).

Here's what the callout box would say, with the first two sentences here in bold as a sort of header:
**Already enrolled? Update information on your 10-10EZ.**
To update your personal, insurance, or financial information from a previous application, download and fill out a [10-10EZR](/healthcare/forms/vha-10-10ezr-fill.pdf).

### CODE REVIEW

**Comment by bethpotts** [comment]
@crwallace I didn't explain the reason for the callout box: The link to the 10-10EZR doesn't fit where it is now. It is a form for Veterans. Where it lives now is with forms for caregivers and active duty.

**Comment by crwallace** [comment]
@bethpotts -- Got it! I don't know if a callout box is the right way to go. Maybe just another heading with the same copy ("Already enrolled? Update information on your 10-10EZ.") that can explain to the user which information can be updated using this form. @maryannbrody any thoughts?

**Comment by bethpotts** [comment]
@crwallace You're right that a callout box isn't the best way to go. But I'm wrestling with where to put that subhead/subsection. How about this: According to the edits I gave you in this PR, the "Notes" section at the very bottom is going away. Could we put it there? Can we try that and see how it looks?

**Comment by bethpotts** [comment]
@crwallace Any update on placing the language "Already enrolled? Update information on your 10-10EZ."?

**Comment by bethpotts** [comment]
@crwallace Ping! The only thing outstanding on this now is to place in a more logical location the language and link about updating an existing application. Would like your opinion on the best place for that link. Happy to get on the phone if that's fastest.

**Comment by bethpotts** [comment]
@dannychapman Two additions to this PR are still needed. I can't see how to edit this file after the migration. So I'm putting the info here to make sure it doesn't get lost. 

1) I tried to bold some text under "Instructions for downloading the forms" but I guess using **asterisks around text ** no longer does that. So you'll see errant asterisks. That text needs to be made bold instead. 
2) We need to remove the top link from the "Additional forms for caregivers..." list. We would like to place it above the blue box, under the section "Others ways to apply," like this: **Note:** Already enrolled? To update your personal, insurance, or financial information from a previous application, download and fill out a [10-10EZR](https://www.vets.gov/healthcare/forms/vha-10-10ezr-fill.pdf).

**Comment by dannychapman** [comment]
screen shot 2016-08-16 at 2 33 41 pm

@bethpotts Let me know what you think of this. For the heading you mentioned, I think we should keep as is for now. There's some work being done to clean up heading styles, so this will likely get bolded automatically as we move forward.

**Comment by maryannbrody** [comment]
@dannychapman @bethpotts -- sorry if i'm jumping in late! Can we look at moving the "Already enrolled?" line down underneath the eligibility criteria? Primary audience for this page is people who are applying for healthcare, so eligibility and applying info should be higher up on the page. 

Also wondering if we need the lines -- not sure why it needs to be called out separately than the rest of the content on the page? This seems like a small subset of users who need to be on this page -- where we'd want to call out the most important/takeaway information. 

Just some thoughts!

**Comment by bethpotts** [comment]
We can certainly move it down, just above the "Additional forms for caregivers..." subhead following eligibility. 

The lines were a way to separate this info from the rest of the page without giving it a subhead, which would make it more prominent, I think, call more attention to it. The text and link to the form don't belong under any other subhead. @dannychapman @maryannbrody Any thoughts on ways to present it without the lines?

**Comment by dannychapman** [comment]
@maryannbrody Fair point. Updated to be a normal subhead for now.

**Comment by dannychapman** [comment]
apply for va health care vets gov

**Comment by bethpotts** [comment]
@maryannbrody If this looks good to you, we'll proceed with the merge.

**Comment by maryannbrody** [comment]
Looks great, thanks @bethpotts @dannychapman !

**Comment by dannychapman** [comment]
@bethpotts merged!

**Pull request merged**
