### PR TITLE
Clarify dependent disability notification

### PR DESCRIPTION
**Pull request by cehsu**
screen shot 2017-08-01 at 11 01 22 am
screen shot 2017-08-01 at 11 01 17 am
screen shot 2017-08-01 at 10 16 02 am

### CODE REVIEW

**Comment by jbalboni** [comment]
@cehsu I don't think this is a change they wanted. I think they wanted the mention of the dependent credit on the other warning removed. Maybe @peggygannon or @goldenmeanie can say for sure?

**Comment by peggygannon** [comment]
@cehsu @jbalboni  Please note "they are" should be "they're":
-- Your child won't qualify as a dependent unless they're in school or disabled.   

This box should appear on the household/dependents/children/information/ page if the user enters "no" for the questions is your child is seriously disabled? and is your child in school"

**Comment by jbalboni** [comment]
Thanks @peggygannon. 

@cehsu I think you need to change `dependentWarning` instead of this one.

**Comment by peggygannon** [comment]
@jbalboni @cehsu Does this warning appear in two different places/pages? If so, we will want to update the language in both.  I was only able to see it pop up on the /children/information/ page

**Comment by jbalboni** [comment]
@peggygannon Not that I know of. There are two disability related warnings on the child info page:

>You'll need to provide all private medical records for your child's disability.

and 

>Your child won't qualify for the dependent credit unless they are in school or disabled.

The first is for when you choose Yes to the disabled question, the second is when you choose No for the disabled question and the school question.

My understanding is we want to update the second one to be

>Your child won't qualify as a dependent unless they are in school or disabled.

**Comment by peggygannon** [comment]
@jbalboni Ok, thanks for clarifying.

**Comment by cehsu** [comment]
Thanks @jbalboni @peggygannon for clarifying the changes involved. Please see screenshots for the changes above and here. I wonder if we want the style of these panels to be consistent? It looks like one has a background image and the other does not. Is this deliberate or simply due to the potentially different times at which these changes were made?
screen shot 2017-08-01 at 10 11 20 am
screen shot 2017-08-01 at 10 11 14 am

**Comment by jbalboni** [comment]
@cehsu I think the background difference is due to one of them originally having a title. @stacyhlinn should they both have background images, or neither?

**Comment by stacyhlinn** [comment]
@jbalboni @cehsu Yes they should be consistent. Let's stick with the background image. I'd make sure the rest of the yellow warning messages on the form all get the treatment.

**Review by jbalboni — APPROVED** [review]

**Comment by cehsu** [comment]
Thanks @stacyhlinn changes made.

**Pull request merged**
