### PR TITLE
Revert problematic unit tests

### PR DESCRIPTION
**Pull request by it-harrison**
## Description
This PR reverts commit `57a669` which was causing downstream unit test failures.
## Original issue(s)
department-of-veterans-affairs/va.gov-team#0000

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by Mottie** [comment]
All 29 files are failing? Why revert/remove all this work. The tests can be skipped...

**Review by Mottie — CHANGES_REQUESTED** [review]
Instead of reverting ALL this work, please bypass the failing tests. I doubt all 29 files are causing failures.

**Comment by it-harrison** [comment]
> All 29 files are failing? Why revert/remove all this work. The tests can be skipped...
A test somewhere in this commit is causing downstream test failures and preventing CI from passing. We're not sure what test is causing the problem since there are so many that were touched.

**Review by Mottie — APPROVED** [review]
I restored my 3 days worth of work and skipped a few unit tests that may have been problematic. I left the render-only unit tests intact. If they turn out to cause errors, then please feel free to skip them.

**Pull request closed without merging**
