### PR TITLE
[Brand Consolidation] CTA for Health Tools

### PR DESCRIPTION
**Pull request by U-DON**
## Description
- Implemented CTA functionality for health tool pages (except appointments, which is awaiting content changes).
- Resolves department-of-veterans-affairs/vets.gov-team#12425.
- Resolves department-of-veterans-affairs/vets.gov-team#12360.
- Resolves department-of-veterans-affairs/vets.gov-team#12373.
- Resolves department-of-veterans-affairs/vets.gov-team#12362.

## Testing done
Local testing.

## Acceptance criteria
- [x] The page should behave according to the matrix: https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/SSO/%5B%2311505%5D%20VA.gov%20MHV%20SSO%20Matrix.md#navigate-to-secure-messaging

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by dhall — APPROVED** [review]
LGTM

**Comment by U-DON** [comment]
@smoonpeyes: The styles shown in the Invision mocks are a departure from our standard alert styles, and would require a bit of hacking and more resources.

In particular, the green alert with the lock icon is not something that exists within the USWDS, which is what we have been adhering to. https://designsystem.digital.gov/components/alerts/

Green typically indicates success, and using the lock icon involves manually adding the PNG/SVG of the lock to our assets in order to style it in the same way that the current set of icons are being used by USWDS. Since it would require some extra effort to change the styles this drastically, I chose what I thought would be the most appropriate standard alert styles for now.

screen shot 2018-09-24 at 6 29 09 am

screen shot 2018-09-24 at 6 28 37 am

**Comment by smoonpeyes** [comment]
@U-DON We're knowingly departing from the USWDS styles based on the [user research](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/SSO/Research/results-summary.md) that we conducted a couple of weeks ago. 

During the user research sessions, many users were confused by the first message style (gold warning box and blue CTA button) that you've chosen. The new green message box was chosen for these contextual message types so that users immediately know that they can move forward. We do not show a warning or alert message unless the user is completely blocked.

Also in the recent study, the red alert box caused a lot of stress and anxiety with users, and we changed the light red background to a light grey background and increased the size of the header text. (This style is applied to all of the contextual messages.) 

The design team agreed that we would move forward with these visual changes for all contextual messages on VA.gov. I'm happy to walk through the updates and discuss the rationale behind each change if it's helpful. 

I mentioned that @emilywaggoner  will be making these updates to Formation, our design system. Would the Formation updates help with implementing these visual changes?

cc: @davidsbao @WinishaSmith

**Comment by U-DON** [comment]
@smoonpeyes: If the changes can be made in Formation, then that should be fine. I don't think I've seen them yet, so should we proceed with the old styles or wait for the new styles to make it into Formation?

**Comment by davidsbao** [comment]
cc: @andrewlewandowski @jbalboni Re: Formation changes

**Comment by jbalboni** [comment]
Yeah, I have the same questions as @U-DON. Are the new alerts a complete replacement? And is it ok for the new alerts to show up on vets.gov, before it becomes va.gov? That would be ideal, then we could make the changes in Formation and pull in the new version.

If it's not, then we have to figure out how to have them live side by side, which is harder, given that alerts are part of the core styles exported by Formation.

**Comment by smoonpeyes** [comment]
@jbalboni and @U-DON Yes. The new contextual alerts are meant to be a complete replacement for the existing alerts. I'm not sure if it's okay for these to show up on vets.gov. Who would make that decision?

**Comment by jbalboni** [comment]
@smoonpeyes I think that's a design decision, so maybe @andrewlewandowski (or he may know who to ask)?

**Comment by davidsbao** [comment]
Just confirmed with @andrewlewandowski and @lalexanderson-dsva - these changes can go live on Vets.gov.

**Comment by andrewlewandowski** [comment]
@jbalboni, @davidsbao, @smoonpeyes, @emilywaggoner - These global alert changes can go live on both Vets.gov and Preview.VA.gov.

It's my understanding that we will replace the four global alerts in Formation (https://department-of-veterans-affairs.github.io/design-system/components/detail/alertbox.html) AND add a fifth alert, which is the green + lock combination that came out of user research for the new VA.gov. @smoonpeyes - please confirm.

**Comment by smoonpeyes** [comment]
@andrewlewandowski That is correct!

**Pull request merged**
