### PR TITLE
Modify login screen messaging

### PR DESCRIPTION
**Pull request by melwoodard**
Closes https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3433

### CODE REVIEW

**Comment by melwoodard** [comment]
Tagging folks from all corners for a review - @U-DON in particular, along with the copy update I also updated the only test I could find for this page, let me know if there were more that I missed.

image

**Review by U-DON — APPROVED** [review]
LGTM.

**Review by ghost — APPROVED** [review]
@melwoodard can you double check that letters has launched before merging? otherwise lgtm!

**Comment by melwoodard** [comment]
@rroueche can you confirm timing on the launch of Letters?

**Comment by rroueche** [comment]
Letter won't launch until August probably @melwoodard

**Comment by melwoodard** [comment]
@amybehrens should I remove mention of Letters from this PR so that we can get this out sooner, and follow up to add letters later once it's live?

**Comment by rroueche** [comment]
@melwoodard i second that motion

**Comment by amybehrens** [comment]
@melwoodard @rroueche yes please! just make an issue to add it back once letters launch

**Comment by melwoodard** [comment]
Great! Removed the Letters copy and added a separate issue for it here: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4083

**Pull request merged**
