### PR TITLE
Migrated V1 to V3 Modal web component

### PR DESCRIPTION
**Pull request by harshilmoradia**
## Summary

This PR migrates all V1 Modal to V3.

## Related issue(s)
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2661

## Testing done
Manual testing

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by adamwhitlock1** [comment]
There are some nasty a11y issues with using the new version of the modal that I need to work through before I can use the v3 / uswds prop for these particular modals.

I am working on fixing them here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/75892

But until then I need to have it explicitly set to `false`

**Comment by harshil1793** [comment]
@adamwhitlock1 oh okay, I believe for the both Modals, correct?

**Comment by adamwhitlock1** [comment]
Yep. I should have both modals fixed by the 23rd when my sprint ends.

**Review by powellkerry — APPROVED** [review]

**Review by Andrew565 — APPROVED** [review]

**Comment by adamwhitlock1** [comment]
@harshil1793 I have merged my changes to the profile modals and both of the modal in question are now using the uswds v3 version, so there should be no further need for this PR.

**Comment by harshil1793** [comment]
thanks @adamwhitlock1 I appreciate it :)

**Pull request closed without merging**
