### PR TITLE
Update STEM scholarship text in education forms wizard

### LINKED ISSUE #50880: Update STEM scholarship text in education forms wizard Sitewide content - target 11/30

### PR DESCRIPTION
**Pull request by jtmst**
## Description
Updated copy in the education forms wizard

## Original issue(s)
closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/50880

## Testing done
Local visual testing
URL to check in QA: education/how-to-apply/

## Screenshots
Screen Shot 2022-11-29 at 9 23 35 AM

## Acceptance criteria
- [ ] New text renders as expected

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by jsimonVA** [comment]
Just to double check, all this change did was reword the STEM scholarship text to -> Applying for the Edith Nourse Rogers STEM Scholarship after using Post-9/11 GI Bill or Fry Scholarship benefits. No other change was made?

**Comment by jilladams** [comment]
(Confirming yes: that copy change is the extent of the request / changes.)

Heads up to @apisandipas , and you'll need this change pulled into your other EDU wizard changes, once it merges.

**Review by GovNapoleon — APPROVED** [review]

**Review by jilladams — APPROVED** [review]

**Comment by jilladams** [comment]
@jtmst we got this approval today, so once tests pass, we can merge this. If I see that happen today, I'll mash the button. If it happens once I'm offline today, pls merge tomorrow por favor.

**Comment by jtmst** [comment]
> @jtmst we got this approval today, so once tests pass, we can merge this. If I see that happen today, I'll mash the button. If it happens once I'm offline today, pls merge tomorrow por favor.

That tugboat test isnt blocking, we should be good to go

**Pull request merged**
