### PR TITLE
Pension refactors

### PR DESCRIPTION
**Pull request by ToddWebDev**
## Summary
On the Pension Benefits application(21P-527EZ)
- Consolidate alerts
- Update data sets to make more sense
- Update radio (key, value) select and storage patterns

### Description
By using object keys for enumeration and storage with consistent naming and casing conventions we can improve maintainability and reusability across the Pensions app.

Examples:
```
CEREMONY: 'In a civil or religious ceremony with an officiant who signed my marriage license',
OTHER: 'Some other way',
```
Rather than storing the current marriage by it's value as 'In a civil or religious ceremony with an officiant who signed my marriage license' and 'Some other way', we store it by it's key as 'CEREMONY' or 'OTHER'.

```
MARRIED: 'Married',
NEVER_MARRIED: 'Never Married',
SEPARATED: 'Separated',
WIDOWED: 'Widowed',
DIVORCED: 'Divorced',
```
Rather than storing the martial status by it's value 'Never married', we store it as  'NEVER_MARRIED'  and vice-versa.
````
  VETERAN: 'Veteran',
  SPOUSE: 'Veteran’s spouse',
  DEPENDENT: 'Veteran’s child',
````
Rather than storing recipient and receiver as separate key, values, we will use the same key, value pairs.

## How to run in local environment
1. Check out this branch locally
2. In your local environment, set the `pension_form_enabled` flipper to 'enabled' at http://localhost:3000/flipper/features/pension_form_enabled
3. Run `vets-website` and `vets-api`

## How to verify
1. Go to `http://localhost:3001/pension/application/527EZ` in your browser
2. Start or continue the application
3. Verify the application is able to be saved and submitted

## Related issue(s)
[Epic in Github](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/zh/224)

## Testing done
- [x] Existing unit tests updated
- [ ] New unit tests added

## What areas of the site does it impact?
Pension Benefits Application

## Acceptance criteria
[Ticket in Github](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/zh/224)

### Quality Assurance & Testing
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Review by danlim715 — DISMISSED** [review]
@ToddWebDev LGTM. Maybe once the schema changes are in, we can update the json schema version here before merging in the changes. Also, corresponding backend changes in [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15407)

**Comment by ToddWebDev** [comment]
@TaiWilkin I don't think so since this branch includes your added migration and version change. No data storage keys we're changed.

**Review by danlim715 — APPROVED** [review]
@ToddWebDev LGTM. Maybe once the schema changes are in, we can update the json schema version here before merging in the changes.

**Review by danlim715 — DISMISSED** [review]

**Comment by danlim715** [comment]
> @TaiWilkin I don't think so since this branch includes your added migration and version change. No data storage keys we're changed.

@ToddWebDev I just realized that we probably will need to add some migration changes to reset or transform some of the old existing data, i.e. change `reasonForSeparation` values from `spouse's death` to `DEATH`, or income -> recipient values from `CHILD` to `DEPENDENT`. Otherwise, these values won't map correctly to the generated PDF.

**Review by IGallupSoCo — DISMISSED** [review]
LGTM

**Pull request closed without merging**
