### PR TITLE
calculate expenses transform refactor 

### PR DESCRIPTION
**Pull request by amponce**
## Summary

This PR represents the second phase of the transform cleanup, aiming to make the code more modular, efficient, and easier to read. As an initial step, the income calculation logic has been extracted into its own helper file, named 'getAllExpenses, and getMonthlyExpenses'. More phases will follow to further refine and organize the code.

### Returned Object

When calling 'getAllExpenses, and getMonthlyExpenses', you receive the most important properties for the veteran and spouse separately, along with the combined total. The function `getMonthlyExpenses` calculates the monthly totals, then returns the following object:

```javascript
{
   utilities +
    installments +
    otherExp +
    calculatedExpenseRecords +
    food +
    rentOrMortgage +
    creditCardBills
}
```

### Usage Example

```javascript
import { getMonthlyExpenses, getAllExpenses } from './calculateExpenses';

// Expenses
const totalMonthlyExpenses = getMonthlyExpenses(form.data);

// Extract values from getAllExpenses
const {
    food,
    rentOrMortgage,
    utilities,
    otherLivingExpenses,
    filteredExpenses,
    otherExpenses,
    installmentContractsAndCreditCards,
    expensesInstallmentContractsAndOtherDebts,
} = getAllExpenses(form.data);
```

## Tasks

- Broke out income calculation from transform functionality, separating it by feature flag and chapter-level calculations.
- Updated helpers to break out transform-specific functionality.

## Acceptance Criteria

- The feature-flagged transform functionality for the income section is more modular, efficient, and readable.

## Related Issue(s)

[Link to ticket created in va.gov-team repo](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63224)

## Testing Done

```
cypress ✔ All specs passed!

efsr-transform.unit.spec.jsx ✅ 69 passing (410ms)
transform.unit.spec.jsx ✅ 68 passing (406ms)
```

## What Areas of the Site Does It Impact?

Financial Status Report

## Quality Assurance & Testing

- I fixed/updated/added unit tests and integration tests for each feature (if applicable).
- Verified the numbers sent to the submission object by generating test PDFs and testing calculations for `dan-path`, `zoe-path`, and `efsr-maximal`.
- Please review the attached PDF (VA Form 5655 - Submitted.pdf) to verify the accuracy of the form data, specifically checking the income calculations for the veteran and spouse, as well as the combined total.

 Income: 3800 + 2200 = 6000 Expenses: 4000 + 500 +675 +550 + 700 = 6425
 Discretionary income adds up correctly:  -425
 
Screenshot 2023-08-08 at 8 59 00 PM

### CODE REVIEW

**Comment by amponce** [comment]
Converting to draft until I get back from vacation

**Comment by amponce** [comment]
We'll need to update the SW references to total expenses in order to merge this safely

**Review by OptionSelect — APPROVED** [review]
Looks fantastic to me! 🚀

**Review by Dr-Pongo — APPROVED** [review]
LGTM! 🚀 

Nice work!

**Pull request merged**
