### PR TITLE
Split GIBCT complaints table (all and by type) with some copy and style tweaks.

### PR DESCRIPTION
**Pull request by U-DON**
Resolves department-of-veterans-affairs/vets.gov-team#2251.

### Changes
* Changed "# total complaints" to "# student complaints".
* Split complaints table into two (all and by type). By type table doesn't include all complaints row.
* Modified first column header of complaints by type table.
* Removed borders at bottoms of tables.

> screen shot 2017-04-18 at 8 06 27 pm

### CODE REVIEW

**Review by melwoodard — APPROVED** [review]
LGTM!

**Comment by saintsoup52** [comment]
This is looks a lot better. TY

**Review by bshyong — APPROVED** [review]
LGTM

**Review by bshyong — APPROVED** [review]
LGTM

**Pull request merged**
