### PR TITLE
Label for British IOT was too vague

### LINKED ISSUE #3655: Change "British" to Great Britain in Drop Down  in Personal Information
From Shay: 3)      Looking at the country drop down. Is “British” a country? I did not see Britain or Great Britain, but there is a United Kingdom in the list.

### PR DESCRIPTION
**Pull request by goldenmeanie**
Closes #3655

### CODE REVIEW

**Review by akainic — APPROVED** [review]
LGTM!

**Comment by akainic** [comment]
@goldenmeanie One thing I noticed is that I think we'll also have to update the schema: https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/common/constants.js#L32

**Comment by goldenmeanie** [comment]
Thanks Anne! I'll put a PR in for that too.

**Comment by goldenmeanie** [comment]
How closely do those two merges need to be coordinated @akainic?

**Comment by akainic** [comment]
@goldenmeanie I think pretty closely. There are a few additional steps we need to do in vets-website once we merge the vets-json-schema PR. Easiest to chat on Slack about that if you don't mind.

**Pull request merged**
