### PR TITLE
Spacing changes to reflect semantics of markup

### PR DESCRIPTION
**Pull request by ncksllvn**
This PR has been moved here - department-of-veterans-affairs/vets-website/pull/6780

-----------

This PR addresses the issue of margins, padding, etc. not reflecting the semantics of the markup. My solution here is really just a continuation of fully integrating USWDS's design into our application. This is because semantic spacing is usually a design library's first priority, so it didn't make sense to me we would see these issues. 

I also elected not to override the USWDS font choices because I think their typography is really nice and legible, so I think it is worth a discussion and a conscious decision of whether or not we should incorporate their font decisions into our application. It is easy to go back and override these fonts, so don't worry if you don't like them. The headings may also be a bit smaller than what we're use to, so that may be worth overriding.

Tasks include:

- Modify headings to use USWDS standard font sizing and spacing
- Replace `va-intro-text` class with USWDS's equivalent `usa-font-lead` style
- Change heading font to Bitter Serif

# Issues
Resolves department-of-veterans-affairs/vets.gov-team/issues/4767
Resolves department-of-veterans-affairs/vets.gov-team/issues/5883

### Related Issues
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4497

---

# Regressions to address in this PR

- [x] Remove the special font size for H3 within `.feature` (blue boxes) 
- [x] There are some places where process list headings are either [visually larger than the higher level heading above them](https://vetsgov-pr-6753.herokuapp.com/housing-assistance/home-loans/loan-options/purchase-loan/) or [offset from the numbers next to them](https://vetsgov-pr-6753.herokuapp.com/disability-benefits/after-you-apply/). I think a good solution to address both is to make all headings within process lists look the same regardless of whether they're H4, H5, etc. by giving them all the following attributes:
   - Font size equal to H4 size
   - margin-top: 0
   - padding-top: .3em
- [x] Change H6 to non-uppercase (uppercase causes literacy issues) and bold
- [x] Remove margin-top on page titles in:
   - Facility locator - facility info page
   - All forms
   - Claim & appeal status
   - Post-9/11 GI Bill status (ch 33 benefit)
   - GIBCT
   - Prescription refills
   - Secure messaging
   - VA health records - download page
- [x] Tabbed nav layout is broken in:
   - Claim status
   - Prescription refills
- [x] Table layout is too narrow and missing gray heading in:
   - GIBCT (school profile page, student complaints section)
   - Prescription refills
   - Secure messaging
- [x] Sign in modal:
   - Remove margin-top on "Sign in to Vets.gov", "Sign in with an existing account", and "Don't have those accounts?" headings
   - Change "One site. A lifetime…" text to a `usa-font-lead` paragraph and remove margin-top
- [x] Profile page:
   - 2FA warning banner: change heading to H4, remove margin-top
   - Applications in process - remove margin-top from card headings  (blue text)
- [x] Claim status:
   - Claims list cards — remove margin-top from card headings (blue text)
   - Blue banners — remove margin-top from headings
- [x] Remove margin-top on alert banners in:
   - Health records 
   - Prescriptions
- [x] GIBCT:
   - Search results grey cards:
      - Remove margin-top on heading
      - Change everything on right side of the card ("you may be eligible...") to paragraph text / source sans pro (maintaining same bolding)
   - Detail view:
      - First accordion needs margin above it

### CODE REVIEW

**Review by melwoodard — COMMENTED** [review]
@ncksllvn it doesn't appear that Bitter is loading, I'm seeing the headings fall back to Georgia.

**Comment by ncksllvn** [comment]
@melwoodard wow, whoops, you're right....I'm gonna try a couple things and will update.

**Comment by melwoodard** [comment]
Awesome. And generally I'd like to make sure we do a good sweep of all the things on site that this PR will touch in regard to spacing and font sizing changes. Do you think we can leverage visual regression testing for this?

**Comment by ncksllvn** [comment]
@melwoodard If you do a cache refresh on the PR deployment now it should be updated. And also I think that I gotta give up all credibility on fonts because those two are completely different and I just immediately accepted the first result.

Visual regression testing may be helpful, but it will definitely detect changes on every page and I'm not sure how useful the diff images will be for something like that. The next version of VRT will be better I think. We're talking about those for the next program increment, we have some [ideas](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Work%20Practices/Engineering/Visual%20Regression%20Testing.md) we want to have a discussion about.

**Comment by melwoodard** [comment]
Great! Much better, although now the headings are showing as regular weight rather than bold, even though the weight in the CSS is 700.

I had a feeling VRT might be moot here. I'll take some time today to look through the content pages. Since the review instance only includes the static content, what's the best way for me to be able to look through all the apps?

**Comment by melwoodard** [comment]
Nevermind! Got the socks proxy up and running. I'll start looking through the apps now

Overall the content pages are pretty good! Spacing is definitely in a better spot now. Just two things there that I'd like to see fixed, and I'll update here later today with any more bugs once I've gone through all the apps.

1. Remove the special font size for H3 within `.feature` (blue boxes) 
2. There are some places where process list headings are either [visually larger than the higher level heading above them](https://vetsgov-pr-6753.herokuapp.com/housing-assistance/home-loans/loan-options/purchase-loan/) or [offset from the numbers next to them](https://vetsgov-pr-6753.herokuapp.com/disability-benefits/after-you-apply/). I think a good solution to address both is to make all headings within process lists look the same regardless of whether they're H4, H5, etc. by giving them all the following attributes:
   - Font size equal to H4 size
   - margin-top: 0
   - padding-top: .3em

**Comment by ncksllvn** [comment]
@melwoodard I hadn't defined the bold version of Bitter into our style. It should be bold now in the next deployment!

Both of your suggestions make perfect sense to me. Should we start a list here to help keep track, or is there a better place?

**Comment by melwoodard** [comment]
Awesome, real bold! Let's keep the list here for ease of tracking. I'll covert to a checklist.

**Comment by ncksllvn** [comment]
@melwoodard feel free to edit the description. We probably don't need those screenshots anymore if we want to keep it simple.

**Comment by melwoodard** [comment]
I updated the original description to outline the major tasks you completed in this PR and started the list of regressions to fix. Please update if you notice anything missing!

**Comment by melwoodard** [comment]
Some screenshots of regressions captured in the checklist at the top:

2FA warning banner in profile - heading is too large and too low:

2fa_banner

Claim status tabs layout issues:

track_claims__vets_gov

Cards with too much margin above headings (affects profile + claim status):

screen shot 2017-11-10 at 11 27 27 am

**Comment by ncksllvn** [comment]
@melwoodard good finds! Those issues make sense - we had all margins removed by default for headings, which played a big part in why we were having spacing issues on our content pages. But yeah, unfortunately those little instances will need to be patched.

**Comment by melwoodard** [comment]
@ncksllvn that makes sense. It seems to me that we could safely remove margin-top on H1s across the board since they'll always be in the same spot at the top of the page. The other cases where a margin-top isn't desirable are when a heading is inside a container that has a background -- alert banners, grey cards, etc. Otherwise I think we're largely good on the default spacing.

**Comment by melwoodard** [comment]
I think there were some regressions caused by the USWDS 1.4.2 bump, which is why the list above got quite long. Does it make sense to split the upgrade out from the heading updates, or continue to tackle these all in one go?

**Comment by ncksllvn** [comment]
I can't remember exactly why I did it like that, but the import order changed in USWDS for each of their stylesheets, so I went ahead and pulled it over to prevent a conflict....I think it makes sense to do them all at once. I can actually close that issue for bumping to 1.4.2 if we want to just do it in this one. Hopefully after this our style issues will be a lot simpler going forward lol

Here's the USWDS 1.4.2 issue
department-of-veterans-affairs/vets-website/pull/6757

**Comment by melwoodard** [comment]
Great, yes please connect this PR with that issue.

I finished looking through all but post-9/11 status and letters, I can’t get the test account for those two to work. But I imagine they’ll have the same margin-top issues on H1s and alerts that we've already been seeing.

**Comment by ncksllvn** [comment]
The H6's may need some sprucing up, or maybe we're using them where an h5 should be used instead:

image

**Comment by ncksllvn** [comment]
> Table layout is too narrow and missing gray heading in:
> GIBCT (school profile page, student complaints section)
> Prescription refills
> Secure messaging

This appears to be the new USWDS style for tables. See [borderless tables](https://standards.usa.gov/components/tables/) at the bottom.  We could switch to the bordered table style. I think it looks pretty good - 

image

Or we can fix it here now and make a note of it in the PR for tracking style changes - department-of-veterans-affairs/vets.gov-team/issues/5618.

**Comment by ncksllvn** [comment]
@melwoodard PTAL

**Comment by melwoodard** [comment]
Thanks Nick! I think changing to the bordered tables sounds good, not a huge fan of their decision to remove the grey header background. For H6 I'd say bump the size up to just a bit smaller than H5.

**Comment by ncksllvn** [comment]
@melwoodard do you think the hero on the landing page should also be in Bitter? 

image

**Comment by ncksllvn** [comment]
@melwoodard deployed to dev!

**Comment by ncksllvn** [comment]
I moved this PR to another branch because too many files have changed and caused too many merge conflicts for me to feel comfortable. The other PR is simpler - department-of-veterans-affairs/vets-website/pull/6780

**Pull request closed without merging**
