### PR TITLE
Add  screen reader only message to FL Map

### PR DESCRIPTION
**Pull request by brangi**
## Description

issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/10784

## Acceptance criteria

- [x] Replace text which would have introduced map content to screenreader with explanation that the map has been suppressed from screen readers.

## Definition of done
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by brangi** [comment]
@jenstrickland, What is the markup needed to add the text context after the map container is hidden so far I have done:

```
<div class="desktop-map-container" aria-hidden="true" role="img">
.... MAP here
</div>
```

Screen Shot 2020-09-29 at 10 53 12 AM

**Comment by jenstrickland** [comment]
```
<p class="sr-only"> <!-- there's a VA Design System class for this, and I posted in #vetsgov-accessibility to ask @1Copenut -->
  Please note: Due to technical limitations, the map has been hidden from screen reader devices. We're working to deliver an enhanced screen reader experience.
</p>

**Comment by jenstrickland** [comment]
Updated the above with the correct class: `.vads-u-visibility--screen-reader`

**Comment by brangi** [comment]
@jenstrickland, I am getting failure after adding `aria-hidden="true" role="img` in the container. 

The error comes from cypress axeChecks:

Screen Shot 2020-09-29 at 2 27 36 PM

I tried adding ```tabindex="-1"``` for elements inside the container to make it not focusable, however it will not work

```
        <div className="desktop-map-container" aria-hidden="true" role="img">
          <Map
            tabindex="-1"
            ref="map"
            id="map-id"
            center={position}
            onViewportChanged={e =>
              recordZoomPanEvents(
                e,
                currentQuery.searchCoords,
                currentQuery.zoomLevel,
              )
            }
            zoomSnap={1}
            zoomDelta={1}
            zoom={parseInt(currentQuery.zoomLevel, 10)}
            style={{ minHeight: '78vh', width: '100%' }} // TODO - move this into CSS
            scrollWheelZoom={false}
            onMoveEnd={this.handleBoundsChanged}
          >
            <TileLayer
              tabindex="-1"
              url={`https://api.mapbox.com/styles/v1/mapbox/streets-v9/tiles/256/{z}/{x}/{y}?access_token=${mapboxToken}`}
              attribution="Map data &copy; <a href=&quot;http://openstreetmap.org&quot;>OpenStreetMap</a> contributors, \
                <a href=&quot;http://creativecommons.org/licenses/by-sa/2.0/&quot;>CC-BY-SA</a>, \
                Imagery © <a href=&quot;http://mapbox.com&quot;>Mapbox</a>"
            />
            {facilityLocatorMarkers &&
              facilityLocatorMarkers.length > 0 && (
                <FeatureGroup ref="facilityMarkers" tabindex="-1">
                  {facilityLocatorMarkers}
                </FeatureGroup>
              )}
          </Map>
        </div>
```

Can you advice ?

**Comment by brangi** [comment]
Ok, I have been able to reduce these issues to only 4:
Screen Shot 2020-09-29 at 3 11 30 PM

```        <div className="desktop-map-container" aria-hidden="true" role="img">
          <Map
            tabindex="-1"
            ref="map"
            id="map-id"
            center={position}
            onViewportChanged={e =>
              recordZoomPanEvents(
                e,
                currentQuery.searchCoords,
                currentQuery.zoomLevel,
              )
            }
            zoomSnap={1}
            zoomDelta={1}
            zoom={parseInt(currentQuery.zoomLevel, 10)}
            style={{ minHeight: '78vh', width: '100%' }} // TODO - move this into CSS
            scrollWheelZoom={false}
            onMoveEnd={this.handleBoundsChanged}
          >
            <TileLayer
              tabindex="-1"
              url={`https://api.mapbox.com/styles/v1/mapbox/streets-v9/tiles/256/{z}/{x}/{y}?access_token=${mapboxToken}`}
              attribution="
              Map data &copy; <a href=&quot;http://openstreetmap.org&quot; tabindex=&quot;-1&quot;>OpenStreetMap</a> contributors, \
                <a  href=&quot;http://creativecommons.org/licenses/by-sa/2.0/&quot; tabindex=&quot;-1&quot;>CC-BY-SA </a>, \
                Imagery © <a href=&quot;http://mapbox.com&quot; tabindex=&quot;-1&quot;>Mapbox</a>"
            />
            {facilityLocatorMarkers &&
              facilityLocatorMarkers.length > 0 && (
                <FeatureGroup ref="facilityMarkers" tabindex="-1">
                  {facilityLocatorMarkers}
                </FeatureGroup>
              )}
          </Map>
        </div>```

However, The leaflet map is provided on react components so I do not have access to the whole HTML markup of the map so it will be really tricky to override all of them. Any other solution more straightforward to avoid this violation?

**Comment by jenstrickland** [comment]
@brangi Yes, it's because the map is in the focus order yet we're trying to hide it from screen reader users. 

1. aria-hidden="true" role="img" — would you please change the role to role="presentation"?

@1Copenut — since we're hiding the map area, is it okay to make the map not focusable? Items that are `aria-hidden="true"` cannot be focusable.

**Comment by brangi** [comment]
@jenstrickland @1Copenut - I came up with a solution that makes AXE plugin happy but still breaks cypress axe checks. The main reason is that, the only way we can modify the focusable elements inside the map with `tabindex="-1"` is to manipulate the DOM after the Map leaflet components rendered and this adds delay to find the elements.

```
          <Map
            tabindex="-1"
            ref="map"
            id="map-id"
            center={position}
            onViewportChanged={e =>
              recordZoomPanEvents(
                e,
                currentQuery.searchCoords,
                currentQuery.zoomLevel,
              )
            }
            zoomSnap={1}
            zoomDelta={1}
            zoom={parseInt(currentQuery.zoomLevel, 10)}
            style={{ minHeight: '78vh', width: '100%' }} // TODO - move this into CSS
            scrollWheelZoom={false}
            onLoad={setTimeout(makeLeafletNotFocusable, 1)}
            onMoveEnd={this.handleBoundsChanged}
          >
            <TileLayer
              tabindex="-1"
              url={`https://api.mapbox.com/styles/v1/mapbox/streets-v9/tiles/256/{z}/{x}/{y}?access_token=${mapboxToken}`}
              attribution="
              Map data &copy; <a href=&quot;http://openstreetmap.org&quot; tabindex=&quot;-1&quot;>OpenStreetMap</a> contributors, \
                <a  href=&quot;http://creativecommons.org/licenses/by-sa/2.0/&quot; tabindex=&quot;-1&quot;>CC-BY-SA </a>, \
                Imagery © <a href=&quot;http://mapbox.com&quot; tabindex=&quot;-1&quot;>Mapbox</a>"
            />
            {facilityLocatorMarkers &&
              facilityLocatorMarkers.length > 0 && (
                <FeatureGroup ref="facilityMarkers" tabindex="-1">
                  {facilityLocatorMarkers}
                </FeatureGroup>
              )}
          </Map>
```

Screen Shot 2020-09-30 at 12 30 59 PM
Screen Shot 2020-09-30 at 12 31 27 PM

Please know that there are limitations with the Map (I had already mentioned this couple of times )  and I do not think this is a reliable solution.  But if this is good enough for you, I will need my team to support this as well and then work with VSP to make the cypress AXE check pass.

**Comment by jenstrickland** [comment]
I think we may need to not hide the map, due to the focusable elements inside the map (I thought that aria-hidden would also hide those, but realize 🤦  that wasn't something I thought all the way through, since keyboards need to be able to access them).

We can include the screen reader only message that this map experience is not screen reader accessible due to limits of the map technology and that it is something that we are working on.

Updated text may read:

```
<p class="vads-u-visibility--screen-reader">
  Please note: Due to technical limitations, the map is not providing an accessible experience for screen reader devices. We're working to deliver an enhanced screen reader experience.
</p>
```

@peggygannon @1Copenut @mmiddaugh What do you think?

**Comment by 1Copenut** [comment]
@jenstrickland I agree, we will have to keep the links inside the map focusable, which means the map will be in document flow. The SR-only language about the map not being optimized for assistive tech is good. 

Is there a roadmap item to improve the map? I understand we don't have timelines, but having an idea that this is work we want to do will help bolster the message.

/cc @mmiddaugh

**Review by mpelzsherman — APPROVED** [review]

**Comment by jenstrickland** [comment]
@1Copenut It's difficult to define a roadmap for addressing it because it depends on the Mapbox/Leaflet.js vendor and the VA's decision to upgrade to [Mapbox GL Accessibility](https://github.com/mapbox/mapbox-gl-accessibility). @mmiddaugh has more info about the status of that.

**Pull request merged**
