### PR TITLE
made content edits to log in page per Peggy

### PR DESCRIPTION
**Pull request by phiden**
See https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4254

### CODE REVIEW

**Comment by peggygannon** [comment]
@phiden Thanks, Sophia! Is there a staging environment for me to view the updated page before this gets merged?

**Comment by bethpotts** [comment]
@phiden Or can you just show us a screen shot of it?

**Comment by phiden** [comment]
@bethpotts @peggygannon screenshot! 
screen shot 2017-08-29 at 11 08 21 am

**Review by robbiethegeek-usds — APPROVED** [review]
:shipit:

**Comment by bethpotts** [comment]
@phiden @peggygannon First I added this comment to the issue... now adding here, where it's more useful!: I see two capitalization issues I'm hoping you can fix, both in the buttons. We need to capitalize "In" and "Up": Log In / Sign Up.

These words that usually serve as prepositions are used adverbially in these instances.

**Comment by phiden** [comment]
made the capitalization changes & merged

**Comment by NatalieEMoore** [comment]
@melwoodard do you want to drop what we are thinking would replace this screen when we go live with the additional identity stuff?  I don't think we mention login just sign in or sign up.

**Pull request merged**
