### PR TITLE
Personalization: Profile design updates

### PR DESCRIPTION
**Pull request by ncksllvn**
- Design updates
- Fix address modal getting cut off (not scrolling when larger than viewport)
- Add the opt-out link to account page

### Todo 
- [x] Meta title tag should read: "Profile: Firstname Lastname"
  - Waiting for clarification on this one

Resolves department-of-veterans-affairs/vets.gov-team/issues/9764
Resolves department-of-veterans-affairs/vets.gov-team/issues/10073
Resolves department-of-veterans-affairs/vets.gov-team/issues/9865

### Design Updates
image

### Modal scroll (scrolled to top)
image

### Opt-out link
image

### CODE REVIEW

**Comment by ncksllvn** [comment]
This PR should be merged first, department-of-veterans-affairs/vets-website/pull/7649

**Review by melwoodard — CHANGES_REQUESTED** [review]
Thanks Nick! Couple small visual changes:

- Remove bottom borders on headings
- First sentence "Review your contact info..." should be styled as `va-introtext`
- The top section (name, branch, first sentence) should be the same width as the content below

personalization__profile_design_updates_by_ncksllvn_ _pull_request__7657_ _department-of-veterans-affairs_vets-website

**Comment by ncksllvn** [comment]
Thanks @melwoodard! Updated the screenshot with those changes.

**Review by melwoodard — APPROVED** [review]
Awesome, thanks Nick!

**Review by bshyong — APPROVED** [review]
LGTM

**Pull request merged**
