### PR TITLE
Connected Account Grants

### PR DESCRIPTION
**Pull request by ATeal**
## Description
Update the connected accounts page to include the individual grants that you have allowed

resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/520

## Testing done
- local

## Screenshots
image
image
image

## Definition of done
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by juliaelman** [comment]
@ATeal thanks for posting the screenshots. Looks like there might be some things missing. Did you reference this design when building this out, screenshots here: https://github.com/department-of-veterans-affairs/vets-contrib/issues/520#issuecomment-439180472

There are also some changes coming down the pike from @hubgitian, so those screens will have updates.

**Review by juliasolorzano — DISMISSED** [review]
See https://github.com/department-of-veterans-affairs/vets-website/pull/9135#issuecomment-439460463

**Comment by ATeal** [comment]
> @ATeal thanks for posting the screenshots. Looks like there might be some things missing. Did you reference this design when building this out, screenshots here: [department-of-veterans-affairs/vets-contrib#520 (comment)](https://github.com/department-of-veterans-affairs/vets-contrib/issues/520#issuecomment-439180472)
> 
> There are also some changes coming down the pike from @hubgitian, so those screens will have updates.

I did reference those designs... I'm not sure which part of the design I'm missing, I do notice now that the modal on mine has a bar on the left where in the deisgn it doesn't, should be able to fix that right up. Besides that in the detail expanded view I left the application name as a link, as I wasn't too sure if we wanted to link back to applications from this screen or not.

**Comment by juliaelman** [comment]
@ATeal cool - thanks for letting me know 👍 

Here are a few other things I am seeing that need to be updated:

- [ ] The logo image should have more padding or a height adjustment to it. 5px each side should do the trick!
- [ ] The modal has an alert styling associated with it that should be removed.
- [ ] The gray in the background on the expanded scopes view looks a bit dark. Please check with Ian to make sure that it's correct.
- [ ] 

Also, quick remind that @hubgitian is doing another round of edits. Sounds like he should have those done by EOD today. Here is a link to those requested changes, FYR: https://github.com/department-of-veterans-affairs/vets-contrib/issues/520#issuecomment-439219478

**Comment by ATeal** [comment]
Updated to use the standard gray and updated the padding around the logo (https://designsystem.digital.gov/components/colors/):
image

Updated to take away the styling from before on the modal:
image

**Comment by ATeal** [comment]
demo

Thanks @hubgitian for the suggestion on the gif creation

**Comment by ATeal** [comment]
Just kidding, just realized I still used the wrong gray 
demo2

**Review by hubgitian — CHANGES_REQUESTED** [review]
@ATeal this looks great! Just a couple of minor adjustments and this one should be ready to rock. I'm happy to hop on slack or a call if you have any questions. Thanks for wrenching on this!

one_less_em
padding
up_one_em

**Comment by ATeal** [comment]
Man I just have to say @hubgitian that is some hella specific feedback, I absolutely love it. Gives me something quantitative to look at. Sometimes implementing designs is a bit of a guessing game, this makes it pretty easy on me.

**Comment by ATeal** [comment]
After Pushes:
image

**Review by hubgitian — APPROVED** [review]

**Pull request merged**
