### PR TITLE
Update error message on schemaform

### PR DESCRIPTION
**Pull request by jbalboni**
Related to [1189](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1189)

I wasn't sure on the styling part of this, so here's my attempt. we can change it around if necessary.

screen shot 2017-03-07 at 10 52 56 am

### CODE REVIEW

**Comment by mollyblake** [comment]
Content looks good to me!  Thanks @jbalboni

**Comment by raquelromano-gov** [comment]
Unit test failure error:

```
/Users/romano/dsva/vets-website/src/js/edu-benefits/utils/helpers.jsx:236
  return enumValues.map(function (item) {
                   ^

TypeError: Cannot read property 'map' of undefined
    at enumToNames (/Users/romano/dsva/vets-website/src/js/edu-benefits/utils/helpers.jsx:147:10)
```

so looks like relationship isn't defined

**Comment by raquelromano-gov** [comment]
```
    at Object.<anonymous> (/Users/romano/dsva/vets-website/src/js/edu-benefits/1990e/config/form.js:64:28)
```

**Comment by raquelromano-gov** [comment]
Oops, ignore all of the above--this was meant for PR 5036

**Comment by goldenmeanie** [comment]
LGTM

**Comment by cvalarida** [comment]
If it's successful, we have a button that says "Go Back to Vets.gov" (at least on the 1995):

> image

Should it be a button here too?

**Comment by mollyblake** [comment]
Probably need a design person to answer that.

**Comment by jbalboni** [comment]
@goldenmeanie Any opinion on Chris's question?

**Comment by goldenmeanie** [comment]
I'd propose `Go to Vets.gov Home` or anything better @mollyblake suggests. But yes, next action button sounds good.

**Comment by jbalboni** [comment]
screen shot 2017-03-08 at 1 36 55 pm

(In dev and staging, there's a link next to the back button to re-submit)

**Pull request merged**
