### PR TITLE
[WIP] PL edits

### PR DESCRIPTION
**Pull request by mollyblake**
PL edits

### CODE REVIEW

**Comment by leannammiller** [comment]
@mollyblake - is this for education benefits? who is the assignee on this?

**Comment by mollyblake** [comment]
Hi @leannammiller. We are reviewing current pages and doing a plain language edit on them. This is a work in progress so we aren't ready to merge. Correct @dannychapman ?  Can you comment?  THANKS!

**Comment by dannychapman** [comment]
@leannammiller Correct, still a WIP, so this will get assigned to USDS and stakeholder review when it is ready to go.

**Comment by mollyblake** [comment]
@leannammiller Yes, will do!  Thanks for the help.

**Comment by rroueche** [comment]
@mollyblake, since this PR is not requesting that the updates be merged into the master but rather into the Education PL Updates branch, I'm going to go ahead and take care of this for you. I'll merge them into the new content/wip/education-plain-language-updates branch however since that's the branch we'll use going forward.

In the future, when you hop into GitHub to make some content updates for an existing topic, it's best if you make those updates directly in the branch for that topic. So in this case directly in the content/wip/education-plain-language-updates branch, instead of creating a new branch. I know all of this GitHub craziness is confusing, so thanks for your patience!

**Comment by mollyblake** [comment]
Thanks @rroueche ....I think this one was from a SME request so we were trying to get it pushed through quickly. Thanks.

**Comment by rroueche** [comment]
@mollyblake ok cool. Done! Changes can be seen here: https://vetsgov-pr-4098.herokuapp.com/education/advanced-training-and-certifications/

Please let me know if this looks good and I'll go ahead and close out this PR. Thanks!

**Comment by rroueche** [comment]
@mollyblake @bethpotts @DanielleSoCompany as a note: if you already have a PR open for a branch, you can actually still open up that branch and commit new changes to it, and they'll show up in the heroku staging URL. So you don't need to create a new branch to add in new changes to staging. 

So for education, just continue opening up the branch: content/wip/education-plain-language-updates, make changes, commit them, and since there's already a PR open for that branch, you'll see your new changes within about 5 minutes on this staging site: https://vetsgov-pr-4098.herokuapp.com/education/

Let me know whether that makes sense... I'm also typing up a doc w/this info so you can keep it handy!

**Comment by dannychapman** [comment]
Let me know if this PR / branch can be deleted. Thanks!

**Pull request closed without merging**
