### PR TITLE
Travel Pay/change root url

### PR DESCRIPTION
**Pull request by liztownd**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

If the folder you changed contains a `manifest.json`, search for its `entryName` in the content-build [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) (the `entryName` there will match).

If an entry for this folder exists in content-build and you are:
1. **Deleting a folder**:
N/A

2. **Renaming or moving a folder**: Update the entry in the [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json), but do not merge it until your vets-website changes here are merged. The content-build PR must be merged immediately after your vets-website change is merged in to avoid CI errors with content-build (and Tugboat).

**NOTE:**
- While I am not "renaming" a folder, I am changing the `manifest.json` and `rootUrl` for our application, so I will have a `content-build` PR to merge as well. 
- _Link to `content-build` PR_
[PR #2385](https://github.com/department-of-veterans-affairs/content-build/pull/2385)

### :warning: TeamSites :warning:
Examples of a TeamSite: https://va.gov/health and https://benefits.va.gov/benefits/. This scenario is also referred to as the "injected" header and footer. You can reach out in the `#sitewide-public-websites` Slack channel for questions.

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

- _(Summarize the changes that have been made to the platform)_
Changing the `rootUrl` for our application to allow for future features.

Old URL: `my-health/travel-claim-status`
New URL: `my-health/travel-pay`

Also adding a sub-route `/claims` to consolidate all travel claim related pages. The root path (`/`) will redirect (using React Router `<Redirect>` component) within the mounted Travel Pay app.

The application has not yet been publicly rolled out, so a server-side redirect is not necessary.

- _(What is the solution, why is this the solution)_
The initial `rootUrl` for the application as a whole was `travel-claim-status` but new features currently in development are not related to `claim status` specifically, so we needed to update the base URL to reflect new capabilities.

- _(Which team do you work for, does your team own the maintenance of this component?)_
Travel Pay

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
[department-of-veterans-affairs/va.gov-team#98178](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98178)(Team GH Issue)
[department-of-veterans-affairs/va.gov-team#98336](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98336) (MHV team issue to update on their landing page)

- _Link to `content-build` PR_
[PR #2385](https://github.com/department-of-veterans-affairs/content-build/pull/2385)

- _Link to `vsp-platform-revproxy` PR_
[PR #780](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/pull/780)

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots
N/A

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*
Travel Pay
MHV landing page (currently the only entry point to our application on staging)
Appointment app (currently behind a different feature flag)

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by IGallupSoCo — APPROVED** [review]
LGTM

**Review by ryanshaw — APPROVED** [review]
VAOS files look good

**Review by kjduensing — APPROVED** [review]
🐸

**Review by dcloud — APPROVED** [review]
The change to `src/applications/mhv-landing-page/utilities/data/index.js` looks good!

**Pull request merged**
