### PR TITLE
Last name min length

### PR DESCRIPTION
**Pull request by lihanli**
https://github.com/department-of-veterans-affairs/healthcare-application-team/issues/512

### CODE REVIEW

**Comment by akainic** [comment]
@lihanli Didn't notice that you had created a PR for this work. I had already started working on it, oops! Just pushed up what I have so far: https://github.com/department-of-veterans-affairs/vets-website/compare/hca-require-min-2-characters-for-name?expand=1.

The way I handled this was mainly through custom validation functions, and passing optional props to FullName to include those custom validation functions where necessary. What do you think about this approach?

**Comment by jbalboni** [comment]
@lihanli @akainic I think I prefer the direction in Anne's PR, for what it's worth. It's closer to how we've been doing validation in edu and here, where we pass in validation functions/results and errors.

We do need a good solution for setting error messages based on the specific validation failure, though. That's a weakness in our current approach.

**Comment by lihanli** [comment]
we can go with your branch anne, i worked on it because leanne assigned me to it, don't know the frontend conventions yet though

**Comment by akainic** [comment]
@lihanli ah gotcha. Sorry about that confusion. I appreciate you giving this a shot in any case!

**Pull request closed without merging**
