### PR TITLE
VACMS 18386 - Removes span around h3s - moves click handler

### PR DESCRIPTION
**Pull request by eselkin**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

- Removes span around h3s that were just receptacles for click. Moves the click handlers to the h3 on VA Facility Results
- Sitewide team (we own facility locator)

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18386

## Testing done

- Manual testing of all facility type responses in Facility Locator
- Check that tabIndexes still work

## Screenshots

<details>
<summary>VA Health Facility Result in PR</summary>
Screenshot 2024-10-07 at 3 11 05 PM
</details>

<details>
<summary>VA Health Facility Result prior</summary>
Screenshot 2024-10-07 at 4 21 55 PM
</details>

<details>
<summary>Urgent Care (CCP above and VA Health Below) Result in PR</summary>
Screenshot 2024-10-07 at 4 37 20 PM
Screenshot 2024-10-07 at 4 37 33 PM
</details>

<details>
<summary>Urgent Care (CCP above and VA Health Below) Result prior</summary>
Screenshot 2024-10-07 at 4 26 33 PM
Screenshot 2024-10-07 at 4 26 56 PM
</details>

<details>
<summary>Emergency Facility (CCP above and VA Health Below) Result in PR</summary>
Screenshot 2024-10-07 at 3 13 00 PM
</details>

<details>
<summary>Emergency Facility (CCP above VA Health below) Result prior</summary>
Screenshot 2024-10-07 at 4 23 17 PM

</details>

<details>
<summary></summary>
</details>

## What areas of the site does it impact?

Facility locator results section

## Acceptance criteria

- [x] Span is no longer surrounding H3 elements in result items

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by randimays** [comment]
@eselkin Could you finish filling out the PR template please? Some screenshots and test scenarios would be helpful, including the browser font size issue that was called out in the ticket.

**Comment by eselkin** [comment]
Oh. This is not the change that affects the font size, that was already merged and checked by Laura. But I will add things here. Sorry, I accidentally moved it to ready when I was merging updates

**Review by pjhill — DISMISSED** [review]

**Comment by laflannery** [comment]
@eselkin the Review instance isn't working? I looked at the screenshots but I would like to double check the tabbing and clicking just in case if we can get the RI up again

**Comment by eselkin** [comment]
Let me see if I can get it started again.

**Review by laflannery — APPROVED** [review]
Review instance worked, Approved!

**Review by randimays — APPROVED** [review]
LGTM

**Pull request merged**
