### PR TITLE
Content/wip/opt out static page

### PR DESCRIPTION
**Pull request by peggygannon**
Content for the static landing page for Colmery Act Opt Out

### CODE REVIEW

**Comment by peggygannon** [comment]
@marybyrnepark , per additional SME feedback, can you move the green Opt Out button down lower on the page, as we want users to fully read the page before making the decision to opt out. 

also, I'm adding @rianfowler to this PR, so he can check the green Opt Out button coding. Rian, this is the PR for the static opt out landing page. 

thank you!

**Comment by peggygannon** [comment]
Thanks, @cehsu for posting the prefill message. 
@marybyrnepark it came up today that maybe we should include a note on the static opt out page letting users know that if they're signed in, then we could prefill part of their application. Our standard message is above, but for the purposes of the static Opt Out, i suggested we shorten the message to the below. Let me know what you think or if you have a another suggestion for the message. 


**Note:** If you're signed in to your account, we can prefill part of your application based on your account details.

**Comment by cehsu** [comment]
Once the cross link changes in `content/pages/education/gi-bill.md` and `content/pages/education/index.md` are moved into their own PR (and removed from this one), the changes in this PR will be hidden in production and can be merged into staging.

**Review by bethpotts — APPROVED** [review]
@marybyrnepark This looks great and is ready for testing.

**Comment by marybyrnepark** [comment]
@cehsu This page is ready to merge into the staging environment.

**Comment by marybyrnepark** [comment]
@cehsu I took out all the changes related to crosslinking and will give those their own PR. Ready to merge into staging environment.

**Review by cehsu — APPROVED** [review]
LGTM. I fixed the broken link issue which was caused by the form root url page markdown file having an outdated name, the form manifest has also been updated to ensure that the updated form root url page is blocked in production.

**Comment by cehsu** [comment]
@marybyrnepark it looks like @peggygannon [recommended](https://github.com/department-of-veterans-affairs/vets-website/pull/7947#issuecomment-404612860) adding the following after the form button:
Note: If you're signed in to your account, we can prefill part of your application based on your account details.
Please create a new ticket to capture this if you decide to not include the change in this PR, but it should not block this PR from getting merged.

**Pull request merged**
