### PR TITLE
Support message count on MHV landing page

### PR DESCRIPTION
**Pull request by ericvoshall**
## Summary

- Displays an unread message badge on the MHV landing page.

## Related issue(s)

- department-of-veterans-affairs/va.gov-team#60007
- department-of-veterans-affairs/va.gov-team#60311

## Testing done

- Tested manually
- Added unit tests
- Added Cypress tests

## Screenshots

Screenshot 2023-07-20 at 11 46 03 AM
Screenshot 2023-07-20 at 11 52 05 AM
Screenshot 2023-07-20 at 11 48 47 AM
Screenshot 2023-07-20 at 11 52 10 AM

## What areas of the site does it impact?

MHV Landing Page

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

### CODE REVIEW

**Review by radavis — COMMENTED** [review]
Looks good!

I added mock data for `vets.gov.user+220` for use in dev/staging: https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/396

**Review by radavis — APPROVED** [review]
:+1:

**Review by mdewey — CHANGES_REQUESTED** [review]
Nice work, some minor finds in the code I did see one blocker

BLOCKER: I would like to see a cypress test validating this works.

**Review by radavis — APPROVED** [review]
Nice work

**Review by mdewey — APPROVED** [review]

**Review by rsmithadhoc — APPROVED** [review]

**Pull request merged**
