### PR TITLE
Telephone/date-time fixes in content pages

### PR DESCRIPTION
**Pull request by robertfairhead**
Closes https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4800

### CODE REVIEW

**Comment by robertfairhead** [comment]
@peggygannon : This is ready for you to start reviewing. I need to make one more pass on the date/time issues but all phone numbers should be good.

**Comment by robertfairhead** [comment]
I double checked the times and didn't see any that were mis-formatted so no more changes from me! Once you're done reviewing, I'll take care of the merge conflicts but won't make any changes to this until I hear back from you.

**Comment by peggygannon** [comment]
@robertfairhead OK, thanks! I'll let you know when I've finished reviewing the PR.

**Review by peggygannon — COMMENTED** [review]
@robertfairhead Hello! Thank you for all the work in creating this PR. I pushed through several updates/edits (mainly removing the days/hours in a bulleted list, when we want to keep that text short).

**Comment by robertfairhead** [comment]
@peggygannon Can you approve the PR as a reviewer?

I'll probably wait and merge after Friday's release so that we'll have enough time to review this in staging. Thanks!

**Review by peggygannon — APPROVED** [review]
@robertfairhead OK, approved. I can also review the pages in staging, if needed. Just let me know.

**Pull request merged**
