### PR TITLE
VACMS 19905 - Guam, USVI, Puerto Rico, Philippines as country and their cities

### PR DESCRIPTION
**Pull request by eselkin**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

### :warning: TeamSites :warning:
Examples of a TeamSite: https://va.gov/health and https://benefits.va.gov/benefits/. This scenario is also referred to as the "injected" header and footer. You can reach out in the `#sitewide-public-websites` Slack channel for questions.

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

- Adds the ability to search for a country (as defined by Mapbox - Guam, USVI, etc are countries). Fixes a processing error that caused Guam & Puerto Rico not to return results even though it was in the approved list of "countries". Also adds IP proximity priority for search result list. No added IP data being sent to Mapbox.
- Adds "country" and possible result type to consider, adds "vi" country to filter list. Makes context conditional since country responses to not have context.
- Sitewide team, we own the Facility Locator

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19905

## Testing done

- Manual testing
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

<details><summary>Guam</summary>
Screenshot 2024-12-03 at 3 33 24 PM
</details>

<details><summary>Puerto Rico</summary>
Screenshot 2024-12-03 at 3 32 43 PM
</details>

<details><summary>Utuado, Puerto Rico</summary>
Screenshot 2024-12-03 at 3 33 04 PM
</details>

<details><summary>Philippines</summary>
Screenshot 2024-12-03 at 3 33 58 PM
</details>

<details><summary>Pasay City, Philippines</summary>
Screenshot 2024-12-03 at 3 34 51 PM
</details>

<details><summary>Los Angeles (from Los Angeles area IP)</summary>
Screenshot 2024-12-03 at 3 35 30 PM
</details>

<details><summary>Arcadia - Urgent care (same results as Dev Arcadia, CA)</summary>
Screenshot 2024-12-03 at 3 41 19 PM
</details>

Same results for dev for provider, pharmacy, etc.

## What areas of the site does it impact?

Facility Locator

## Acceptance criteria

- [x] When user searches for Guam, Puerto Rico, anything within USVI, USVI, Philippines, the Facility Locator successfully pulls up the address / location

- [x] Adapt existing [Facility Locator regression test plan](https://docs.google.com/spreadsheets/d/1wgIM4oIwAQk-E151z07P3hhZuQJ6mhepv7U5tZjdpEI/edit?gid=0#gid=0) to cover new functionality for country searches

- [x] Test plan passes all tests

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user (unauthenticated)

## Requested Feedback

Review /find-locations on the RI and search for Guam, Puerto Rico, USVI, Philippines or any cities in those areas. Test IP based proximity with a "Springfield" search and see what comes up for you vs va.gov/find-locations

### CODE REVIEW

**Review by SnowboardTechie — APPROVED** [review]
LGTM 👍🏻

**Comment by eselkin** [comment]
I copied and updated some the FL test plan here: https://docs.google.com/spreadsheets/d/15dDcZh777FbBucW11c13BxFeD4Yd-Rs0oxs5v4uOXGU/edit?usp=sharing

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Comment by eselkin** [comment]
test plan run by @jilladams looks good. Merging.

**Pull request merged**
