### PR TITLE
HLR | Replace button with va-button

### PR DESCRIPTION
**Pull request by rocio-desantiago**
## Summary

- _(Summarize the changes that have been made to the platform)_
  > web component replaced with va component for buttons in higher level review form
- _(If bug, how to reproduce)_
  > Not a bug
- _(What is the solution, why is this the solution)_
  > Per design system, updating for consistency
- _(Which team do you work for, does your team own the maintenance of this component?)_
  > Benefits Decision Reviews
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_
  > Higher Level Review form (0996) already active

## Related issue(s)
- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#56927

## Testing done

- _Describe what the old behavior was prior to the change_
  > No behavior changes
- _Describe the steps required to verify your changes are working as expected_
  > Visually and functionality should be the same
- _Describe the tests completed and the results_
  > unit tests updated to look for `va-button`

cancel-addissue

> The option to `edit` or `remove` added issue
edit-remove

> When editing added issue with option to `cancel` updating issue
cancel-updateissue

## What areas of the site does it impact?
  > Higher Level Reviews
*(Describe what parts of the site are impacted **if** code touched other areas)*
  > none

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

### CODE REVIEW

**Review by Mottie — APPROVED** [review]
Looks good! Thanks!

**Comment by Mottie** [comment]
Oh oops!!

**Comment by rocio-desantiago** [comment]
Aaaah good catch @jerekshoe

**Comment by rocio-desantiago** [comment]
Fixed here: https://github.com/department-of-veterans-affairs/vets-website/pull/24326

**Pull request merged**
