### PR TITLE
Supply Reordering: Hides 'Start order' link when alerting

### PR DESCRIPTION
**Pull request by radavis**
## Summary

This change applies to the new Supply Reordering application at `src/applications/mhv-supply-reordering`, and not the existing app at `src/applications/health-care-supply-reordering`.

- Hides 'Start order' link when alerting
- Adds `isAlerting` selector

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#98861

## Testing done

- local testing with mock-api

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| alerting  |   Screenshot 2024-12-12 at 10-25-17 Order Medical Supplies Veterans Affairs     |  Screenshot 2024-12-12 at 10-28-07 Order Medical Supplies Veterans Affairs    |
| not alerting |   Screenshot 2024-12-12 at 10-25-41 Order Medical Supplies Veterans Affairs     |   Screenshot 2024-12-12 at 10-27-49 Order Medical Supplies Veterans Affairs    |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by nichia** [comment]
I tested it locally with mock-api by removing the suppliers from the suppliers array (const supplies = []) and the alert shows up correctly without 'Start order' link. The developer console is throwing below warning because reorderDate is undefined.
`Warning: Failed prop type: The prop `reorderDate` is marked as required in AlertNoSuppliesForReorder, but its value is `undefined`.`

**Comment by radavis** [comment]
> The developer console is throwing below warning...

@nichia Thank you for catching this!

**Review by Jenny-yw — APPROVED** [review]

**Review by IGallupSoCo — APPROVED** [review]
LGTM

**Review by nichia — COMMENTED** [review]
LGTM

**Pull request merged**
