### PR TITLE
Moving demo video listing site to Vets.gov

### PR DESCRIPTION
**Pull request by robertfairhead**
Closes https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2725

### CODE REVIEW

**Comment by robertfairhead** [comment]
It's not agreed yet in the issue that we should actually do this, so this is in limbo for the moment. Let me ping folks on the issue to see if this should move forward or die.

If move forward, it'd be whoever has general front-end review duties now that tiffany is gone. Maybe anne? If you have thoughts, let me know.

**Review by melwoodard — COMMENTED** [review]
Should the title "Demonstration Videos" appear at the top of the page?

**Comment by robertfairhead** [comment]
https://vetsgov-pr-5529.herokuapp.com/playbook/demos/ is updated with a title on the page title.

**Review by melwoodard — APPROVED** [review]
LGTM!

**Pull request merged**
