### PR TITLE
10307  show events until they end (alt)

### PR DESCRIPTION
**Pull request by apisandipas**
## Summary

- This change effect the duration of which Events are displayed on the Event Listing page (/outreach-and-events/events) 
- Previously events would display in "All Upcoming" up until their start time, which inconveniently hid them from Veterans who might need to find the event location, etc as it was starting. This change causes events to display in Upcoming, Next Week and Next Month until their end time has passed.

## Related issue(s)
- department-of-veterans-affairs/va.gov-cms#10307
 
## Testing done
- Manual testing against live data.

## What areas of the site does it impact?
the Event Listing page (/outreach-and-events/events)

## Acceptance criteria
- [x] Events should appear in Upcoming until the end time has passed, then move to Past Events.
- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [n/a]  Events are being sent to the appropriate logging solution
- [n/a]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [n/a]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [n/a]  I added a screenshot of the developed feature

## Requested Feedback

Assure events still display after they've started,

### CODE REVIEW

**Review by jtmst — APPROVED** [review]

**Comment by jilladams** [comment]
Using http://8c999e254403bb801f8119ed2fe914f4.review.vetsgov-internal/outreach-and-events/events/, verified: a 5-5:30p event shows Upcoming at 5:17p, and no longer shows upcoming at 5:35p.
<details><summary>5p-530p Outreach event upcoming at 517p ET</summary>
5p-530p Outreach event upcoming at 517p ET
</details>
<details><summary>5p-530p Outreach event no longer Upcoming at 535p ET</summary>
5p-530p Outreach event no longer Upcoming at 535p ET
</details>

Re: Recurring events: The only way to test these is locally, bc vets-website + CMS + Content build needed. Per discussion with Bryan, there didn't seem to be anything in the changes made here that pertains to them in a specific way. As far as the Front end is concerned they're separate events, and the front-end deals with their start time in a one-off manner.

@jtmst We can merge this, imo. However, noting: Bryan's on PTO for the next 3 days, so we'll need you as backup in the event that anything goes awry. I will let you click the button, in the spirit of consent.

**Review by jilladams — CHANGES_REQUESTED** [review]
Pause on merge for a bug I found: On a couple of healthcare centers, past events are showing up as Upcoming on the Review Instance, vs. prod. We need to investigate.

* 🔴 /**tuscaloosa**-health-care/events/ - Shows a Jan 19 past event recurrence in Upcoming, bug.
  * http://8c999e254403bb801f8119ed2fe914f4.review.vetsgov-internal/tuscaloosa-health-care/events/ -- Upcoming events starts with a Jan 19 recurrence that should not show here
  * https://www.va.gov/tuscaloosa-health-care/events/ -- upcoming events start with 2/14
  * Node: https://prod.cms.va.gov/node/50705/revisions - no edits since Jan 12, this should be in Past events for sure.

* 🔴 /**greater-los-angeles**-health-care/events/ -- 2/10 event (past) shows up as Upcoming. Could be due to data on Review Instance being stale?
  * Prod: https://www.va.gov/greater-los-angeles-health-care/events/
  * Review instance: http://8c999e254403bb801f8119ed2fe914f4.review.vetsgov-internal/greater-los-angeles-health-care/events/ -- shows a past event in All Upcoming filter
  * Node: https://prod.cms.va.gov/node/53154/revisions/view/745834/748166/visual_inline --This node's date/time was modified today (2/13) to change it from a 2/10 to a 2/17 event. On Prod, it shows correctly in the event listing as Upcoming on 2/17. On the Review instance for this change, it shows _incorrectly_ as 2/10 (old date, pre-edit), so is a past event showing up as Upcoming.
 
Screen Shot 2023-02-13 at 3 41 09 PM

* 🟡 /**chicago**-health-care/events - prod shows an upcoming recurrence on 3/9, RI shows no upcoming events. 
  * http://8c999e254403bb801f8119ed2fe914f4.review.vetsgov-internal/chicago-health-care/events
  * https://www.va.gov/chicago-health-care/events/
  * Node: https://prod.cms.va.gov/node/53499/revisions -- was created today on 2/13. Not sure if this should be showing up on the RI or not, depending on its data source.


* 🟢 /**minneapolis**-health-care/events/ -- correctly shows future dates in Upcoming, past dates in Past , including correct handling of a recurring event with occurrences both past and future: https://prod.cms.va.gov/minneapolis-health-care/events/48208
* 🟢 /**connecticut**-health-care/events/ -- correctly shows future dates in Upcoming, past dates in Past
* 🟢 /**indiana**-health-care/events/ -- correctly shows future dates in Upcoming, past dates in Past
* 🟢 /**tennessee**-valley-health-care/events/ -- prod shows an upcoming event on 2/17, RI shows no upcoming events, but the prod event was just created as a future date today: https://prod.cms.va.gov/node/51971/revisions
* 🟢 /**salt-lake-city**-health-care/events/
* 🟢 /**palo-alto**-health-care/events/
* 🟢 /montana/-health-care/events/ -- no upcoming events
* 🟢 /kansas-city-health-care/events
* 🟢 /madison-health-care/events/?selectedOption=upcoming

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Comment by jilladams** [comment]
We are finally reviving this effort, don't close.

**Comment by randimays** [comment]
Tackled this in a different PR. Closing.

**Pull request closed without merging**
