### PR TITLE
[FSR] Fixing confirmation page survey button click

### PR DESCRIPTION
**Pull request by Dr-Pongo**
## Summary

- Fixing `onClick` function for loading survey!
- Updating text for survey based on content feedback (screenshots included)

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#72105
- _Link to previous change of the code/bug (if applicable)_
department-of-veterans-affairs/vets-website#27338

## Testing done
Testing in review instance

### Confirmation page alert
| Form version | Before | After | 
| -------- | -------- | -------- |
| Full FSR | image | image |
| Streamlined | image | image |

## What areas of the site does it impact?
FSR confirmation page 
*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback
Feel free to load up review instance and complete a form to check if survey button is visible and functional 
(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by OptionSelect — DISMISSED** [review]
LGTM! 🚀

**Review by aubreyarcangel — DISMISSED** [review]
Looks good!

**Review by aubreyarcangel — APPROVED** [review]
LGTM

**Review by OptionSelect — APPROVED** [review]
LGTM! part deux!

**Pull request merged**
