### PR TITLE
VACMS-15924 Fix Breadcrumbs spacing and update components

### PR DESCRIPTION
**Pull request by randimays**
## Summary
[Slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1698676437427859) for context.

We discovered that the DST [made a change](https://github.com/department-of-veterans-affairs/component-library/pull/861/files) to remove padding from the <va-breadcrumbs> component. This created an issue with the left-side spacing on the breadcrumbs across screen widths.

The changes here both fix the spacing on the left side and update our breadcrumb components to the latest (USWDS v3) version available.

Fixes included for:
- PACT Act `/pact-act-eligibility`
- Income Limits `/health-care/income-limits`
- Search
- Yellow Ribbon `/education/yellow-ribbon-participating-schools/`

Also includes a fix for the results errors Cypress test for Income Limits. It was failing because the endpoint I had mocked was targeting the "current year" of 2023. I made this dynamic so it won't fail again in the future.

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15924
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16736

## Testing done
Locally tested all affected applications on mobile and desktop.

## Screenshots

<details>
<summary>PACT Act</summary>

### Before (Desktop)
This app was already converted to breadcrumbs v3, so I adjusted spacing only.
Screenshot 2024-01-09 at 3 11 06 PM

### After (Desktop)
Screenshot 2024-01-09 at 2 41 45 PM

### Before (Mobile)
Screenshot 2024-01-09 at 3 11 12 PM

### After (Mobile)
Screenshot 2024-01-09 at 2 42 00 PM
</details>

<details>
<summary>Income Limits</summary>

### Before (Desktop)
Screenshot 2024-01-09 at 2 58 44 PM

### After (Desktop)
Screenshot 2024-01-09 at 2 46 36 PM

### Before (Mobile)
Screenshot 2024-01-09 at 2 58 36 PM

### After (Mobile)
Screenshot 2024-01-09 at 2 46 25 PM
</details>

<details>
<summary>Search</summary>

### Before (Desktop)
Screenshot 2024-01-09 at 2 58 18 PM

### After (Desktop)
Screenshot 2024-01-09 at 2 57 55 PM

### Before (Mobile)
Screenshot 2024-01-09 at 2 58 24 PM

### After (Mobile)
Screenshot 2024-01-09 at 2 58 01 PM

</details>

<details>
<summary>Yellow Ribbon</summary>

### Before (Desktop) - Pre-Search
Screenshot 2024-01-09 at 2 58 59 PM

### After (Desktop) - Pre-Search
Screenshot 2024-01-09 at 2 53 55 PM

### Before (Desktop) - Post-Search
This app already had adequate spacing on the left side, so I updated breadcrumbs only
Screenshot 2024-01-09 at 2 59 20 PM

### After (Desktop) - Post-Search
Screenshot 2024-01-09 at 2 53 44 PM

### Before (Mobile) - Pre-Search
Screenshot 2024-01-09 at 2 59 05 PM

### After (Mobile) - Pre-Search
Screenshot 2024-01-09 at 2 54 03 PM

### Before (Mobile) - Post-Search
Screenshot 2024-01-09 at 2 59 05 PM

### After (Mobile) - Post-Search
Screenshot 2024-01-09 at 2 54 11 PM

</details>

### CODE REVIEW

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Comment by laflannery** [comment]
The mobile screens are different than the screenshots in the description. However, they are supposed to look like this, with just a single breadcrumb displaying on mobile. Can you make sure that they are displaying like the below in all cases on mobile?

**PACT**
Screenshot 2024-01-10 at 10 57 46 AM

**Income Limits**
Screenshot 2024-01-10 at 11 00 45 AM

**Yellow Ribbon**
Screenshot 2024-01-10 at 11 05 51 AM

**Comment by randimays** [comment]
@laflannery Whoops, my screenshots were taken at too wide a screen (480px I think). Here are all of the breadcrumbs at 320px width.

## PACT Act
Screenshot 2024-01-10 at 10 39 14 AM

## Income Limits
Screenshot 2024-01-10 at 10 37 58 AM

## Search
Screenshot 2024-01-10 at 10 36 34 AM

## Yellow Ribbon
Screenshot 2024-01-10 at 10 39 04 AM
Screenshot 2024-01-10 at 10 38 52 AM

**Comment by laflannery** [comment]
Ah gotcha, that makes sense. This looks good then, thanks!

**Review by chriskim2311 — APPROVED** [review]
LGTM!

**Pull request merged**
