### PR TITLE
MHV-60250: MHV secondary nav added

### PR DESCRIPTION
**Pull request by mattwrightva**
## Summary
- MHV secondary nav from platform added to app
- The secondary nav was also added to the loading screen because in the future when there are no feature toggle conditions, it should display while the app is loading

## Related issue(s)
https://jira.devops.va.gov/browse/MHV-60250
### Implement secondary nav bar

> Implement MR on the  secondary nav bar.  Do not launch until Phase 1.
> 
> Important update from the cartography team 8/16/24:
> Right now, the secondary nav in prod does not point to medical records. It points to a temporary MR page. The cartography devs have a ticket in this sprint to put a different destination URL behind a feature flag on that component that will route the 1% of users to the true /medical-records.  Basically Ty needs to wait & work with cartography to implement the feature flag version. He should connect with Daniel Cloud, Richard Davis, or Carlos Felix - I'm not sure which one is working on this, but any of them would have this context.
> 
> Component information:  
> 
> Comment from Kaitlin during PI planning:  At some point we need to remove the content link on the MR landing page and probably could be added to this ticket "Email your feedback and questions to us at [vamhvfeedback@va.gov](mailto:vamhvfeedback@va.gov)."
> 
> User Story:  As a MR user, I want to see a secondary navigation bar since I will no longer have the left navigation bar.
> 
> 
> 
> 
> Feature Flag Y/N ? Y-ticket entered assigned to Mike
> 
> DataDog/Analytics?  Y/N ?
> 
> Manual Testing Y/N ?  Y
> 
> Automated Testing Y/N ? Y
> 
> Accessibility Testing Y/N ?  Y
> 
> UCD Validation Y/N Y
> 

## Testing done
Unit test added to verify component exists when feature flags are loaded

## Screenshots
Screenshot 2024-08-27 at 12 09 22 PM
Screenshot 2024-08-27 at 12 09 14 PM

## What areas of the site does it impact?
MHV medical records

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by Wyzardsleeves — DISMISSED** [review]
Approved!

**Review by mmoyer-va — DISMISSED** [review]
Looks good! Sadly there will be a conflict with my PR, depending on which gets merged first, but will be easy to sort out.

**Review by mmoyer-va — DISMISSED** [review]
Thanks for adding that fix!

**Review by jamigibbs — DISMISSED** [review]

**Review by mmoyer-va — APPROVED** [review]
Looks good!

**Pull request merged**
