### PR TITLE
Process updated rated disabilities list

### PR DESCRIPTION
**Pull request by Mottie**
## Description

Form 526 has a new save-in-progress endpoint that provides updated rated disabilities. When the disabilities have changed, the save-in-progress endpoint will redirect the user back to the rated disability selection page.

This PR compares the new and previous lists, and attempts to update the user selections - this may not be possible given that the values within the rated disability may change (see the related sample data). A message is also shared with the user to let them know things have changed.

Related:
- Ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/13128
- New save-in-progress endpoint: https://github.com/department-of-veterans-affairs/vets-website/pull/16051
- Sample data: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/163

## Testing done

Updated unit tests

## Screenshots

Placeholder content (in blue box)

Screen Shot 2021-02-16 at 2 05 08 PM

## Acceptance criteria
- [x] Rated disabilities are updated
- [x] An attempt is made to maintain the user's previous selections
- [ ] Show user information on what happened and why it happened (awaiting content feedback)

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by annaswims** [comment]
not to self: ensure that we don't end up with an empty array of rated disabilities.

**Comment by annaswims** [comment]
Here's my testing strategy: 
in vets-api, settings.loca.yml set
````yml
evss:
  mock_pciu_address: true
````

log in as user 228 and start the form.  This is the original prefill data from the BE:
````json
 "disabilities": [
            {
                "decisionCode": "SVCCONNCTED",
                "decisionText": "Service Connected",
                "diagnosticCode": 5238,
                "name": "Diabetes mellitus0",
                "ratedDisabilityId": "0",
                "ratingDecisionId": "63655",
                "ratingPercentage": 100
            },
            {
                "decisionCode": "SVCCONNCTED",
                "decisionText": "Service Connected",
                "diagnosticCode": 5238,
                "name": "Diabetes mellitus1",
                "ratedDisabilityId": "1",
                "ratingDecisionId": "63655",
                "ratingPercentage": 100
            }
        ],
````

immediately gets transformed to this on the Front end. 
  ````json
"ratedDisabilities": [
    {
      "name": "Diabetes mellitus0",
      "ratedDisabilityId": "0",
      "ratingDecisionId": "63655",
      "diagnosticCode": 5238,
      "decisionCode": "SVCCONNCTED",
      "decisionText": "Service Connected",
      "ratingPercentage": 100,
      "disabilityActionType": "NONE"
    },
    {
      "name": "Diabetes mellitus1",
      "ratedDisabilityId": "1",
      "ratingDecisionId": "63655",
      "diagnosticCode": 5238,
      "decisionCode": "SVCCONNCTED",
      "decisionText": "Service Connected",
      "ratingPercentage": 100,
      "disabilityActionType": "NONE"
    }
  ],
````


## test scenario
## a user starts the form, returns to the form later and rated disabilities are updated
   - change rated disability name using `save-in-progress menu`
   - leave and return to form
  Does not work as expected.  the rated disabilities json looks like:  
   ````json
    "ratedDisabilities": [
    {
      "name": "Diabetes mellitus0",
      "ratedDisabilityId": "0",
      "ratingDecisionId": "63655",
      "diagnosticCode": 5238,
      "decisionCode": "SVCCONNCTED",
      "decisionText": "Service Connected",
      "ratingPercentage": 100
    },
    {
      "name": "Diabetes mellitus1",
      "ratedDisabilityId": "1",
      "ratingDecisionId": "63655",
      "diagnosticCode": 5238,
      "decisionCode": "SVCCONNCTED",
      "decisionText": "Service Connected",
      "ratingPercentage": 100
    }
  ],
```` 
but I don't see the rated disabilites on the page
Screen Shot 2021-03-02 at 12 28 02 PM

**Comment by Mottie** [comment]
@annaswims I've updated this branch to use form data `updatedRatedDisabilities` - it's much easier to test using the SiP menu!

**Review by micahchiang — APPROVED** [review]

**Comment by annaswims** [comment]
hm... this is a step towards updating rated disabilities, but it won't actually update rated disabilities until we start calling the disability_compensation_in_progress_forms, which makes it hard to e2e test.  Should we merge https://github.com/department-of-veterans-affairs/vets-website/pull/16051 into this branch?

**Comment by annaswims** [comment]
or at least make a branch that combines these two to do e2e testing even if we keep them as separate PR's that are merged at the same time.

**Pull request merged**
