### PR TITLE
WIP: Create index.html

### PR DESCRIPTION
**Pull request by rickleegit**
DO NOT MERGE

Alex, 

This is the redirect to the survey that we discussed. 

There may be additional changes including the url, so I just wanted to test this. I would not merge. 

Thanks,

Rick

### CODE REVIEW

**Comment by ayaleloehr** [comment]
@emilyville can you take a look at this (but don't merge) and make sure you agree with the approach. Basically Rick has set this up so that once merged vets.gov/agp will redirect to a survey elsewhere. Is this a reasonable thing to do?  It seems to make sense to me, but just wanted another set of eyes on it. Thanks!

**Comment by ayaleloehr** [comment]
@emilyville bump ^^.  Thanks!

**Comment by emilyville** [comment]
ok! My 2 cents:

I think we should capitalize on the thing that happens after submit to send them back to vets.gov? @rickleegit do you know what that will look like?

I would also suggest making the logo at the be clickable back to vets.gov if that's not too insane of an undertaking.

**Comment by rickleegit** [comment]
The redirect from the thank you will bring them back to our home page. 

We also asked them to put our header and footer on the page. That's in progress as well. 

The survey page itself is out of our control, but the contractor has been very accommodating, so I am expecting to see the finished version early next week. 

All sound good?

**Comment by emilyville** [comment]
Could you clarify which page the header and footer would go on? (confused since if the survey page is out of our control - and we just redirect back to vets.gov on completion, which step that would be.)

so it goes 
vets.gov/shorturl --> auto loads survey page --> then upon completion "success!" and on you go to vets.gov?

**Comment by rickleegit** [comment]
@staceylanger and I had spoken about putting our header and footer on the actual survey page. But at this point, we just need to get the branding correct, as it has reverted to VA.gov branding.

**Comment by rickleegit** [comment]
Stakeholder went another route. No longer needed.

**Pull request closed without merging**
