### PR TITLE
Acknowledgement spelling

### PR DESCRIPTION
**Pull request by igreulich**
## Description
Make sure we are
- spelling acknowledgement like a c k n o w l e d g e m e n t
- spelling it the same way everywhere

## Testing done
n/a

## Screenshots
n/a

## Acceptance criteria
- Change the word "Acknowledgment" to "Acknowledgement" throughout the text so they are all consistent (with the "e")

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by igreulich** [comment]
@robfelder and/or @imeecuison Can I get a review?

**Review by imeecuison — APPROVED** [review]
Looks great!

**Review by robfelder — CHANGES_REQUESTED** [review]
I left a comment about the linter errors that github is catching.

**Comment by igreulich** [comment]
@robfelder I went ahead and fixed those error, even though they are/were not ours. Can I get a recheck?

**Comment by igreulich** [comment]
@robfelder There are also a lot of linter fixes in #8481.

**Comment by robfelder** [comment]
@igreulich - linter errors look good, but Unit test is failing now. Are you able to see the jenkins link under the "All checks have failed" text below? (You'll have to have socks running)

**Comment by igreulich** [comment]
@robfelder I will take a look, but the error I am seeing is not directly related to my work. Should we have a different story fo that at this point? If so, than should should the fix be done over there?

**Review by robfelder — APPROVED** [review]

**Pull request merged**
