### PR TITLE
Update va311 numbers

### PR DESCRIPTION
**Pull request by kelsonic**
## Description
**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/14609

This PR bumps formation-react for the update in the `<Telephone />` component and updates all VA311 numbers. If I missed any, please lmk asap!! 🙂 

## Testing done
N/A

## Screenshots
N/A

## Acceptance criteria
- [x] Update VA311 numbers from 844-698-2311 to 800-698-2411

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by micahchiang — COMMENTED** [review]
Hey @kelsonic - I just merged this PR in minutes ago, so you might want to pull master into your branch - https://github.com/department-of-veterans-affairs/vets-website/pull/14765

**Comment by kelsonic** [comment]
Oh thanks for the heads up @micahchiang, did you update `formation-react`'s `<Telephone />` component too?

**Comment by micahchiang** [comment]
> Oh thanks for the heads up @micahchiang, did you update `formation-react`'s `<Telephone />` component too?

I did not update the `formation-react` component. Just the numbers in the rated disabilities, view-dependents, and 686c-674 files.

**Review by sanlouise — APPROVED** [review]

**Review by ncksllvn — APPROVED** [review]

**Review by Mottie — APPROVED** [review]

**Review by U-DON — APPROVED** [review]

**Comment by Mottie** [comment]
2020-10-30 10_52_04-additional-linting (129075) - department-of-veterans-affairs_vets-website

**Review by DanielleThierryUSDSVA — COMMENTED** [review]
Hi @kelsonic. Thank you for making these changes! There are some supporting text changes that also need updating. I've listed below. Will go back through again to make sure I didn't miss any.  

1

image

In above, we need to also change "VA311" to "our MyVA411 main information line at"

2

image

In above, we also need to change "VA311" to "us"

3
image

In above, we need to also change "VA311" to "our MyVA411 main information line at"

4

image

In above, we need to also change "VA311" to "our MyVA411 main information line at"

5

image

image

In above 2, we need to change "VA311" to "us"

**Comment by DanielleThierryUSDSVA** [comment]
Adding one more:

image

Need to change "VA311" to "our MyVA411 main information line at"

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht When the text changes are ready, would you be able to give it a final copy edit review? Thank you!

**Comment by kelsonic** [comment]
@DanielleThierryUSDSVA @RLHecht Updated the content from VA311 to `us` and `our MyVA411 main information line at` as specified in your comments! 🙂

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA @kelsonic these all look OK to me. One question is should these be in aria labels?

**Comment by kelsonic** [comment]
image

This is the test that keeps failing, @department-of-veterans-affairs/vsa-caregiver-frontend is this related to my changes?

**Review by bradl3yC — APPROVED** [review]

**Pull request merged**
