### PR TITLE
Check in/40836/pre check in unavailable phone

### PR DESCRIPTION
**Pull request by brianseek**
## Description
Adds error message for expired pre-check for phone appointments.
This PR also adds a new test UUID for expired phone appointments. To test, set your local mock to have the feature set to true then use this UUID for pre-check-in: `08ba56a7-68b7-4b9f-b779-53ba609140ef`

## Original issue(s)
department-of-veterans-affairs/va.gov-team#40836

## Testing done
Updated unit test.

## Screenshots
Screen Shot 2022-06-10 at 4 31 36 PM

### CODE REVIEW

**Comment by brianseek** [comment]
I didn't feel like this needed to be wrapped in the feature flag since its checking on appointment type to display and the code doesn't rely on the `kind` key to be in the appointment object.

**Comment by brdunfield** [comment]
> I didn't feel like this needed to be wrapped in the feature flag since its checking on appointment type to display and the code doesn't rely on the `kind` key to be in the appointment object.
> 
> Let me know if you feel like any of this should be wrapped by the flag.

I do somewhat feel like this should be wrapped in the flag - unless we're 100% sure the flag will stop phone 'kind' property entries from appearing until it's turned on (I'm not fully sure of what will be coming from the VA backend stuff - will phone appointments be filtered out?). I could be misunderstanding how it's all going to come together though!

**Comment by brianseek** [comment]
> > I didn't feel like this needed to be wrapped in the feature flag since its checking on appointment type to display and the code doesn't rely on the `kind` key to be in the appointment object.
> > Let me know if you feel like any of this should be wrapped by the flag.
> 
> I do somewhat feel like this should be wrapped in the flag - unless we're 100% sure the flag will stop phone 'kind' property entries from appearing until it's turned on (I'm not fully sure of what will be coming from the VA backend stuff - will phone appointments be filtered out?). I could be misunderstanding how it's all going to come together though!

Makes sense to me, I'll wrap it in the flag. I just needed one person to say to do it to convince me!

**Review by it-harrison — APPROVED** [review]

**Review by brdunfield — APPROVED** [review]
LGTM! 🦑 
Tested with and without feature flag enabled, and everything works as expected.

**Pull request merged**
