### PR TITLE
Remove testActionLink prop from forms library

### LINKED ISSUE #1674: Forms Library: Incorrect text displaying on start button
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Original Slack convo: https://dsva.slack.com/archives/CBU0KDSB1/p1680805825168439

The start progress buttons on forms are displaying the incorrect text. It is displaying "Continue" instead of the start text passed into the component:

Screenshot 2023-04-06 at 2 25 45 PM

Screenshot 2023-04-06 at 1 53 37 PM

## What I expected to happen

I expect the start progress buttons to display the text passed into the button's text prop. It might also need the chevron " displayed too but I'm not sure what the form looked like before this update.

### Details

The update made to replace the `ProgressButton` React component with `va-button` in `forms/save-in-progress/FormStartControls.jsx` added the `continue` prop I think maybe to display the chevron character "»" but [that prop overrides the provided text ](https://design.va.gov/storybook/?path=/docs/components-va-button--continue)and automatically displays "continue" instead.

- https://github.com/department-of-veterans-affairs/vets-website/pull/23768

Screenshot 2023-04-06 at 2 03 02 PM

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1. Log in to staging as user [260](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv#L260) and navigate to [VA Form 10182 (Notice of Disagreement)](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/introduction)
   - vets.gov.user+258@gmail.com
   - 152SsNrLgPv5
2. Notice that the buttons on the page say "Continue >>" but it should say "Start the Board Appeal request"
3. Inspect the button and remove the `continue` prop and the expected text will appear.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [x] Other

I don't think this is blocking anything but it is probably affecting all forms that use the `src/platform/forms/save-in-progress/FormStartControls.jsx` file.

### PR DESCRIPTION
**Pull request by jamigibbs**
## Summary
This update removes the `testActionLink` prop that would allow teams to test the [action link](https://design.va.gov/storybook/?path=/docs/components-action-link--primary) to start a form instead of a button. 

The action link maturity rating is now "use:deploy" so [based on the discussion here](https://github.com/department-of-veterans-affairs/vets-website/pull/23875#issuecomment-1499640220), we are updating the forms library to use it instead of a button.

## Related issue(s)
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1674

## Testing done
Locally
E2E & Unit tests passing

### Before
Screenshot 2023-04-10 at 11 42 48 AM

### After

Screenshot 2023-04-10 at 11 44 23 AM

## What areas of the site does it impact?
- Forms Library
- Apps using the `<FormStartControls>` or `<SaveInProgressIntro>`

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature
- [ ]  [Accessibility foundational testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### CODE REVIEW

**Review by Mottie — APPROVED** [review]

**Review by jhonny218 — APPROVED** [review]

**Review by Dr-Pongo — APPROVED** [review]
LGTM! 🚀 

Thank you!

**Comment by jamigibbs** [comment]
A gentle poke to see if you could please add your review to this PR? We have a few teams waiting for this update:
- @department-of-veterans-affairs/my-education-benefits
- @department-of-veterans-affairs/1010-health-apps-frontend
- @department-of-veterans-affairs/platform-va-product-forms
- @department-of-veterans-affairs/vsa-authd-exp-frontend

**Review by longmd — APPROVED** [review]
LGTM for the HCA app 🚀

**Review by nathanielbuck — APPROVED** [review]

**Review by adamwhitlock1 — APPROVED** [review]
lgtm. Only thing this touched in `personalization` apps is a non-production app and looks fine regardless.

**Review by ndsprinkle — APPROVED** [review]

**Pull request merged**
