### PR TITLE
Remove home "/" breadcrumb accorss VAMC pages

### PR DESCRIPTION
**Pull request by brangi**
## Description
issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/10038

TODO: remove [build prod check](https://github.com/department-of-veterans-affairs/vets-website/blob/8bad1aebc6d83ebc555d7bf7ad2de2bd64298063/src/site/includes/breadcrumbs.drupal.liquid#L8) when fully tested - 
## Testing done
Review instance : http://12dc4c77f42f213b4c9048866fef935f.review.vetsgov-internal/pittsburgh-health-care/

## Acceptance criteria
- [x] Remove Home > across https://www.va.gov/pittsburgh-health-care/ for VAMC products only

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by brangi** [comment]
@ethanteague, @mpelzsherman , let me know if I missed any other. I'd appreciate you taking a second look

**Review by ethanteague — CHANGES_REQUESTED** [review]
There's only 7 files here, @brangi  - should be all the .drupal.liquid layouts in template directory, with the exceptions of:

- page.drupal.liquid
- office.drupal.liquid
- landing_page.drupal.liquid
- home.drupal.liquid

**Comment by brangi** [comment]
> There's only 7 files here, @brangi - should be all the .drupal.liquid layouts in template directory, with the exceptions of:
> 
> * page.drupal.liquid
> * office.drupal.liquid
> * landing_page.drupal.liquid
> * home.drupal.liquid

Most of them already have the option though:

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/health_care_region_health_services_page.drupal.liquid

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/health_care_region_locations_page.drupal.liquid

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/health_services_listing.drupal.liquid

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/locations_listing.drupal.liquid

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/news_stories_page.drupal.liquid

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/news_story.drupal.liquid

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/press_releases_listing.drupal.liquid

**Comment by ethanteague** [comment]
> > There's only 7 files here, @brangi - should be all the .drupal.liquid layouts in template directory, with the exceptions of:
> > 
> > * page.drupal.liquid
> > * office.drupal.liquid
> > * landing_page.drupal.liquid
> > * home.drupal.liquid
> 
> Most of them already have the option though:
> 
> https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/health_care_region_health_services_page.drupal.liquid
> 
> https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/health_care_region_locations_page.drupal.liquid
> 
> https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/health_services_listing.drupal.liquid
> 
> https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/locations_listing.drupal.liquid
> 
> https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/news_stories_page.drupal.liquid
> 
> https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/news_story.drupal.liquid
> 
> https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/press_releases_listing.drupal.liquid

Still missing some - there are 26 drupal files in that directory. The 7 above plus the 7 you changed in this pr plus the 4 exceptions I listed only gets us to 18, @brangi

**Comment by brangi** [comment]
> > > There's only 7 files here, @brangi - should be all the .drupal.liquid layouts in template directory, with the exceptions of:
> > > 
> > > * page.drupal.liquid
> > > * office.drupal.liquid
> > > * landing_page.drupal.liquid
> > > * home.drupal.liquid
> > 
> > 
> > Most of them already have the option though:
> > https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/health_care_region_health_services_page.drupal.liquid
> > https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/health_care_region_locations_page.drupal.liquid
> > https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/health_services_listing.drupal.liquid
> > https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/locations_listing.drupal.liquid
> > https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/news_stories_page.drupal.liquid
> > https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/news_story.drupal.liquid
> > https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/press_releases_listing.drupal.liquid
> 
> Still missing some - there are 26 drupal files in that directory. The 7 above plus the 7 you changed in this pr plus the 4 exceptions I listed only gets us to 18, @brangi

I didn't list all of them ^ and we could probably remove the templates but I think last commit will cover all

**Review by ethanteague — APPROVED** [review]

**Review by mpelzsherman — APPROVED** [review]

**Review by mpelzsherman — CHANGES_REQUESTED** [review]
We need to remove `buildtype == 'vagovprod'` from line 8 of src/site/includes/breadcrumbs.drupal.liquid, otherwise these changes will not take effect in production.

**Review by mpelzsherman — APPROVED** [review]
Approving to get the code into staging. Once testing is complete we will need another PR to remove the prod flag.

**Review by bkjohnson — APPROVED** [review]

**Pull request merged**
