### PR TITLE
Upgrade react dependency

### PR DESCRIPTION
**Pull request by jhonny218**
## Description
Major upgrade. No breaking changes but A LOT OF internal changes

## Original issue(s)
department-of-veterans-affairs/va.gov-team#33822

## Testing done
- Locally
- [Test Plan](https://docs.google.com/spreadsheets/d/1AwlYzftj2mBSDpLI0npeFm9TvGegiCB-88W8MMZGZH4/edit#gid=0)

## Acceptance criteria
- [] No knew errors presented in the test plan related to the upgrade

## Definition of done
- [ ] React 17 is upgraded and the test plan is accepted

### CODE REVIEW

**Comment by timwright12** [comment]
Is that it? Does this all work now?

**Comment by jhonnyoddball** [comment]
I'm doing some local testing now

**Comment by timwright12** [comment]
Test plan for release https://docs.google.com/spreadsheets/d/1AwlYzftj2mBSDpLI0npeFm9TvGegiCB-88W8MMZGZH4/edit#gid=0

**Comment by timwright12** [comment]
converted this back to a draft since we don't want it merged until the upgrade and test plan are complete

**Review by srsuddath — APPROVED** [review]
Thanks!

**Comment by alexandec** [comment]
The only thing I noticed is two skipped tests. Are they failing due to the react upgrade?

**Review by alexandec — APPROVED** [review]

**Comment by jhonnyoddball** [comment]
> The only thing I noticed is two skipped tests. Are they failing due to the react upgrade?

They were failing due to the upgrade but after talking to Kelson, these tests are no longer valid since he created a new mega menu. They already have a ticket for clean up where Public Websites will be removing all those tests. Therefore, he was ok with skipping the tests for now.

**Comment by alexandec** [comment]
Okay cool, as long as the failures don't point towards additional issues in other apps, I'm good with that

**Pull request merged**
