### PR TITLE
add statement about unified branding to playbook

### PR DESCRIPTION
**Pull request by emilyville**
@dannychapman and @ss0ss would love your thoughts on placement! 

this is from issue #714. If we put this on our site, we will be good on leaving out individual branding. The copy is from the Martin Taylor in Sec. Bob's office.

Also I made up the section title "Unified Branding" it's alright but def. open to other ideas. I put the section in platform since it's not about _our_ brand or style, but how we will incorporate other products brands.

screencapture-localhost-4000-playbook-platform-1447898351051

### CODE REVIEW

**Comment by ss0ss** [comment]
@emilyville - The copy needs some work. Give me a day to throw something back to you. @sjb912 - Feel free to chime in here.

**Comment by ss0ss** [comment]
@emilyville Feel free to move forward with the PR for now - but I will probably throw another PR your way soon to edit/fix the copy.

**Comment by koconnor719** [comment]
can you guys just send me the final text you want so i can send to Martin Taylor to approve?  i'm sure he'll be fine with it, but he needs to approve this branding language:)

**Comment by emilyville** [comment]
Added new language written by @sjb912 and signed off from VA office! Ready to go.

**Comment by dannychapman** [comment]
@emilyville Looks good. Feel free to merge.

**Comment by koconnor719** [comment]
here is the copy from Susan--that has been approved by Office of Sec:

The Department of Veterans Affairs (VA) announced in January, 2015, that
VA would transition its many websites to a single site -- Vets.gov -- with
the goal of creating a unified web experience for Veterans and their
families. The Vets.gov branding model will replace previously existing
branding of VA Web content and programs when they become part of Vets.gov.

**Pull request merged**
