### PR TITLE
Migrate va-number-input to va-text-input

### PR DESCRIPTION
**Pull request by harshilmoradia**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

## Summary

This PR migrates `va-number-input` to `va-text-input` and fixes tests.

## Related issue(s)

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2662

## Testing done
Yes (Manual testing)

### income-limits app
Screenshot 2024-07-17 at 10 46 31 AM
Screenshot 2024-07-17 at 11 39 44 AM

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by micahchiang — DISMISSED** [review]
Nice work, thanks Harshil!

**Review by eselkin — DISMISSED** [review]
LGTM

**Review by chriskim2311 — DISMISSED** [review]
LGTM

**Comment by ToddWebDev** [comment]
The [va-number](https://design.va.gov/components/form/number-input) uses an input type of 'text' under the hood, but the `<va-text-input inputmode="number" />` is using an input type of 'number' under the hood. I was under the impression that the va-number field was using a type of 'text' for accessibility reasons. Suffice to say this is all very confusing as a va-number-input is of input type 'string' and now a va-text-input can be an input type of 'number'. Is this new type of va-text-input support for numbers supposed to be a type of 'number'?

**Comment by harshil1793** [comment]
@Todd The  `va-text-input` will use an input type of **'number'** only if the `max` or `min` attributes are set; otherwise, it will default to an input type of **'text'**. This change ensures that the input behaves appropriately based on the presence of these attributes. I understand that this can be semantically confusing, but it allows for greater flexibility and functionality within the same component.

**Comment by ToddWebDev** [comment]
@harshil1793 Thank you for the clarification

**Review by ToddWebDev — DISMISSED** [review]

**Review by rhasselle-oddball — DISMISSED** [review]

**Comment by Dr-Pongo** [comment]
@harshil1793 Hey! I have a few questions/concerns, so is the `currency` prop going away on text input since we now have `input-prefix`? 

I've been testing with [this AddIncome](https://github.com/department-of-veterans-affairs/vets-website/pull/30854/files#diff-4d8b6e62b530e53f3a9eaa232fa8bb739321b89955d0dc1466fd892e64a66ec4R122) component and noticed that it is throwing an error when I enter a decimal value. It doesn't prevent me from continuing, but I tested it against main and I don't see the same error pop there so I'm guessing it's some kind of baked in functionality. `inputmode="decimal"` doesn't seem to help, and I tried changing `type="number"` with no luck either. Let me know what you think! Thank you! 

image

**Review by micahchiang — DISMISSED** [review]

**Review by Dr-Pongo — APPROVED** [review]
LGTM! 🚀

**Review by eselkin — APPROVED** [review]
LGTM. But I'd want @laflannery review also.

**Review by chriskim2311 — APPROVED** [review]
LGTM

**Comment by laflannery** [comment]
I reviewed this and approved [within slack](https://dsva.slack.com/archives/C52CL1PKQ/p1721321112586739?thread_ts=1721235427.815249&cid=C52CL1PKQ) (as I can't get to the dependents screen in the review instance). I also confirmed just now that now changes have occurred that would impact what I previously approved. Thanks for tagged me @eselkin!

**Review by micahchiang — APPROVED** [review]

**Review by ToddWebDev — APPROVED** [review]

**Review by rhasselle-oddball — APPROVED** [review]

**Pull request merged**
