### PR TITLE
Content wip discharge link on eligibility pages

### PR DESCRIPTION
**Pull request by DanielleSoCompany**

### CODE REVIEW

**Comment by DanielleSoCompany** [comment]
Hi @phiden. Wanted to ask if you could help me with 2 things associated with this PR. Just let me know if you have any questions. And just a heads up: We're not going to be ready to merge this PR until I can connect with Beth re: whether we need to run it by SMEs yet, so we don't want to merge yet. Thanks!

**1)** We've included an anchor link that will go to the discharge upgrade instructions page (https://www.vets.gov/discharge-upgrade-instructions/) and open a specific accordion. It's not a static page, so I don't want to go trying to edit it myself. Could you add the anchor link tag on the discharge upgrade app page? The tag is #other-options and the anchor link we'd like it to auto-open is **"Can I get VA benefits without a discharge upgrade?"**

**2)** On the user profile, we'd like to replace the current question/answer of **"Have a less than honorable discharge?"** with the following Q/A. Also, Natalie let us know that SMEs felt there needed to be more separation between the link above that Q/A (Apply for a Veteran ID Card) and the discharge upgrade copy because they feel it looks like the copy is referring specifically to VIC. So maybe a short line separating those, or perhaps we could put the Q/A about discharge upgrade in a little blue callout box? Would love your design thoughts there.

Here's the new copy for that:

**What should I do if I received an other than honorable, bad conduct, or dishonorable discharge?**

If you've received one of these discharge statuses, you may not be eligible for VA benefits. **But there are 2 ways you can try to qualify:**

[Find out how to apply for a discharge upgrade](/discharge-upgrade-instructions/).
[Learn about the VA Character of Discharge review process](/discharge-upgrade-instructions/#other-options).

**Comment by DanielleSoCompany** [comment]
Hi @bethpotts. Could you please review the new discharge upgrade language across the different eligibility pages? Also, 2 notes:

1. I changed "were discharged from the military under other than dishonorable conditions" to "didn't receive a dishonorable discharge" on these pages as well, per our conversation of how to lessen confusion as expressed in user testing. Think we need to get SME approval on that change? 

2. The addition of the discharge upgrade question does make a few of the blue boxes quite long. Let me know if you think we need to break things up on those pages a bit.

Thanks!

**Comment by DanielleSoCompany** [comment]
Hi @bshyong. @phiden recommended reaching out to you re: edits needed on the profile page and the discharge wizard page. Please see below for details. Is this something you can help with? Thank you in advance and please just let me know if you have any questions!

**1)** We've included an anchor link that will go to the discharge upgrade instructions page (https://www.vets.gov/discharge-upgrade-instructions/) and open a specific accordion. It's not a static page, so I don't want to go trying to edit it myself. Could you add the anchor link tag on the discharge upgrade app page? The tag is #other-options and the anchor link we'd like it to auto-open is **"Can I get VA benefits without a discharge upgrade?"**

**2)** On the user profile, we'd like to replace the current question/answer of **"Have a less than honorable discharge?"** with the following Q/A. Also, Natalie let us know that SMEs felt there needed to be more separation between the link above that Q/A (Apply for a Veteran ID Card) and the discharge upgrade copy because they feel it looks like the copy is referring specifically to VIC. So maybe a short line separating those, or perhaps we could put the Q/A about discharge upgrade in a little blue callout box? Would love your design thoughts there.

**Here's the new copy for that:**

**What should I do if I received an other than honorable, bad conduct, or dishonorable discharge?**

If you've received one of these discharge statuses, you may not be eligible for VA benefits. But there are 2 ways you can try to qualify:

[Find out how to apply for a discharge upgrade](/discharge-upgrade-instructions/).
[Learn about the VA Character of Discharge review process](/discharge-upgrade-instructions/#other-options.

**Comment by bshyong** [comment]
@saneshark is there anyone on Griffins that has the time to make these changes? If so, I’d like to walk them through how to make these changes so that we can share knowledge and make it is easier to make changes in the future.

**Comment by DanielleSoCompany** [comment]
@bshyong @saneshark 2 notes for the request above:

- There's been a minor tweak to the copy that should replace the current "less than dishonorable" discharge upgrade content on the profile page. Copy should now read:

**What should I do if I received an other than honorable, bad conduct, or dishonorable discharge?**

If you've received one of these discharge statuses, you may not be eligible for VA benefits. 
**There are 2 ways you can try to qualify:**

[Find out how to apply for a discharge upgrade].
[Learn about the VA Character of Discharge review process].

- Also, @NatalieEMoore  had asked me to take another look at the profile page content and make any additional recommendations for edits. I do see some things we should change. These are listed below:

1.  Some changes needed for links:

Change **Apply for health care** to **Apply for VA health care benefits**

Change **Apply for Education Benefits** to **Apply for VA education benefits**

Change **Refill your prescription** to **Refill your prescriptions**

Change **Message your health care team** to **Message your VA health care team**

Change **Check your claim and appeal status** to **Track your VA claims and appeals**

2. **Change:** **[Verify your identity](https://staging.vets.gov/verify/) to access more services you may be eligible for.**

**To:** **Want to access more services you may be eligible for?** 
 [Verify your identity](https://staging.vets.gov/verify/).

3. Change the note at the bottom of the page from: You have accepted the latest health tools terms and conditions for this site.

To: **Note:** You've accepted the latest terms and conditions for using this site's health tools.

Thank you!

**Comment by DanielleSoCompany** [comment]
@NatalieEMoore Beth has completed her edits to the static pages if you'd like to review. Thanks!

**Comment by DanielleSoCompany** [comment]
@phiden here's the PR I referenced in my note just a minute ago that we need to haved merged. This covers the static pages portion of this request. Thanks!

**Review by phiden — APPROVED** [review]

**Pull request merged**
