### PR TITLE
added yeoman test - do not merge

### PR DESCRIPTION
**Pull request by rianfowler**
I ran the [yeoman generator](https://github.com/department-of-veterans-affairs/generator-vets-website/pull/1/files) and this is what happened.

### CODE REVIEW

**Comment by rianfowler** [comment]
screen shot 2018-03-30 at 13 49 52
I got some linting errors but I might need to re-run `yarn install`

**Comment by rianfowler** [comment]
Looks like it worked!
screen shot 2018-03-30 at 13 52 24

**Comment by jbalboni** [comment]
@rianfowler Thanks! I added some more info to the prompts and some validation for the root url based on this.

**Comment by rianfowler** [comment]
I added a better image of the linting errors after running `yarn install`

**Pull request closed without merging**
