### PR TITLE
WIP/burial allowances static updates and EDU process page edits

### PR DESCRIPTION
**Pull request by peggygannon**
Updates to burial allowances static page

### CODE REVIEW

**Comment by peggygannon** [comment]
@bethpotts: this PR with updates to Burial Allowances static page is ready for your review.

**Review by bethpotts — COMMENTED** [review]
Your content changes look perfect, Peggy. We just need to wait for the global fix to spacing/bullets on master, then merge master into the branch.

**Comment by peggygannon** [comment]
@phiden Can you merge master into this branch: content/wip/burial-allowances-static-updates? 

Nick had to revert some changes in the master branch, and I need to make sure my branch reflects the reverted changes.  Thanks!

**Comment by phiden** [comment]
all set

**Comment by peggygannon** [comment]
@bethpotts This PR is ready for your review.

**Review by bethpotts — APPROVED** [review]
Content looks good, and thanks for fixing bullets!

**Comment by peggygannon** [comment]
@phiden Hi, Sophia, this PR is ready to be merged.

**Review by phiden — APPROVED** [review]

**Pull request merged**
