### PR TITLE
Content wip discharge upgrade instructions sme edits

### PR DESCRIPTION
**Pull request by DanielleSoCompany**

### CODE REVIEW

**Comment by DanielleSoCompany** [comment]
Hi @bethpotts and @NatalieEMoore , could you please review this PR? This is to address the SME edits from this ticket: https://app.zenhub.com/workspace/o/department-of-veterans-affairs/vets.gov-team/issues/9276. Thank you!

@bshyong Would you be able to take a screenshot of the Discharge Wizard introduction screen in staging and paste it here so that Beth and Natalie can review the revised content? Thank you!

**Review by NatalieEMoore — APPROVED** [review]

**Review by bethpotts — APPROVED** [review]
Made minor edits and approved!

**Comment by DanielleSoCompany** [comment]
Hi @phiden, could you please review this PR and push to production for tomorrow's build? And could you please also comment here when it's ready so that @NatalieEMoore can take a look at the discharge upgrade instruction page in staging just to make sure it's okay (we can't see the changes there in heroku) before it goes live? Thank you and let me know if you have any questions!

**Review by phiden — APPROVED** [review]

**Comment by phiden** [comment]
@DanielleSoCompany @NatalieEMoore approved & merged!

**Pull request merged**
