### PR TITLE
Facility locator design updates

### PR DESCRIPTION
**Pull request by bshyong**
- resolves https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2859
- resolves https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1879
- updates `react-tabs` to address deprecation warnings
- refactor to use camelcase inflection

### CODE REVIEW

**Review by U-DON — APPROVED** [review]
LGTM so far. Should this be merged yet? I noticed the commits were from a while back, so not sure if this is WIP. And also because it looks like there's a soft launch for this later.

I think you also intended to refactor requests to have the camel-case header. It doesn't have to be done in this PR, but the relevant issue is the one place where you made note of it.

**Comment by bshyong** [comment]
Good catch. Added the refactor in this PR. I'm not sure if we are clear to merge yet, though the data for the access to care does exist. We are also catching for cases where the data is not available, in which case we will not show the graphs.

@leannammiller do you know if this is free to merge into master/dev + staging + prod?

This PR adds some improvements and implements the data bars in this screenshot:

https://cloud.githubusercontent.com/assets/303289/26361678/89be37cc-3f90-11e7-9afc-7a44553fe9ed.png

**Comment by leannammiller** [comment]
Definitely not production but dev is fine @bshyong. @NatalieEMoore please confirm timeline for rolling out wait times.

**Comment by NatalieEMoore** [comment]
- Wait times and patient satisfaction data--live June 12th 
- Vet Centers live June 19th

**Comment by bshyong** [comment]
OK—so we cannot merge this to master yet; but wait times data and patient satisfaction redesign is done

**Review by U-DON — CHANGES_REQUESTED** [review]
Blocking to prevent accidental merging.

**Comment by bshyong** [comment]
Changed PR to merge to `kudos-launch`

**Comment by bshyong** [comment]
^ keeping branch around so we can make a new PR to merge into master when we are ready to launch

**Pull request merged**
