### PR TITLE
Content/wip/disability consistency issue

### PR DESCRIPTION
**Pull request by bethpotts**

### CODE REVIEW

**Comment by bethpotts** [comment]
@mnorthuis I want to run past you an update I'd to make to the top nav to match the shortened title for a Life Insurance page that I've just tweaked the title for. That was a mouthful. Here's the page, for reference: https://www.vets.gov/life-insurance/disabled-and-terminally-ill/

The title will change (Amy has approved already, to put the person--"policyholder"--first and the disability/diagnoses--"totally disabled or terminally ill"--second)
From: Claims for Disabled and Terminally Ill Policyholders
To: Benefits for Policyholders Who Are Totally Disabled or Terminally Ill

The left nav will change to: Totally Disabled or Terminally Ill
And I'd like the top nav to match. It currently says: Disabled & terminally ill policyholders

I want to make sure this all makes sense to you and to get your approval before I loop Sophia in to help me make the change.

**Comment by mnorthuis** [comment]
I'm good with this change.  Thank you!

**Comment by bethpotts** [comment]
@phiden I have two requests, please!! (if you'd be so kind as to help me...)
1) Could you make the corresponding change to the top nav (same as left nav, which I've already fixed in display_title) in Life Insurance, right side: 
Before: Disabled & terminally ill policyholders
Change to: Totally disabled or terminally ill

2) Wait for Peggy to review, then please merge after Peggy's approval. Thanks!!

**Review by peggygannon — APPROVED** [review]
LGTM.

**Comment by phiden** [comment]
@bethpotts pushed that change -- waiting for checks to pass and then will merge.

**Pull request merged**
