### PR TITLE
removed prod flags for 4227 and 4275

### PR DESCRIPTION
**Pull request by ksantiagoBAH**
## Description
As a developer, I need to remove the feature flag so that the Veteran Programs section updates are available in the production environment.

This issue implements functionality covered in the following stories: 
- story numbers 4227, 4275

## Original PR(s)
These PRs are the original code that is currently behind a prod flag that is being lifted by this PR. 
- PR 1  department-of-veterans-affairs/vets-website#11349
- PR 2 department-of-veterans-affairs/vets-website#11334

## Testing
Local Testing

## Assumptions
1. This work has been reviewed by EDU and signed off on as of 01/03/2020.
2. The work completed in https://github.com/department-of-veterans-affairs/va.gov-team/issues/4277 is available is to remain behind a production flag.

## Acceptance Criteria: 
- [x] The work completed in  https://github.com/department-of-veterans-affairs/va.gov-team/issues/4227 is available in production.
- [x] The work completed in https://github.com/department-of-veterans-affairs/va.gov-team/issues/4275 is available in production.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by delli-gatti-michael — APPROVED** [review]

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by bkjohnson — COMMENTED** [review]
What exactly was supposed to be behind a Prod flag?  When I look at what was removed I see that [this flag doesn't seem to do anything](https://github.com/department-of-veterans-affairs/vets-website/pull/11419/files#diff-220cd71a49609636ef05e8eac0da1809L44) - both of the JSX sections are identical.

**Comment by ksantiagomorgan6** [comment]
> What exactly was supposed to be behind a Prod flag? When I look at what was removed I see that [this flag doesn't seem to do anything](https://github.com/department-of-veterans-affairs/vets-website/pull/11419/files#diff-220cd71a49609636ef05e8eac0da1809L44) - both of the JSX sections are identical.

@bkjohnson The production flag is in CautionaryInformation.jsx which is covered in this story. department-of-veterans-affairs/va.gov-team#4277

**Review by bkjohnson — CHANGES_REQUESTED** [review]
> The section was conditional, now it is not

Are you sure about that?  [This is what I see](https://github.com/department-of-veterans-affairs/vets-website/blob/e31dd17adc669f6c8d74bb937bb6601d264188e4/src/applications/gi/components/vet-tec/VetTecInstitutionProfile.jsx#L44-L58):

```jsx
          {/* prod flag for BAH 4227. There are also flags in Programs.jsx and VetTecPrograms.jsx */}
          {environment.isProduction() && displayVeteranPrograms() ? (
            <AccordionItem button="Veteran programs">
              <VetTecVeteranPrograms
                institution={institution}
                onShowModal={showModal}
              />
            </AccordionItem>
          ) : (
            <AccordionItem button="Veteran programs">
              <VetTecVeteranPrograms
                institution={institution}
                onShowModal={showModal}
              />
            </AccordionItem>
          )}
```

The `<AccordionItem>` looks the exact same in both cases regardless of the condition.

Please add some unit tests describing/verifying what `<VetTecVeteranPrograms>` is supposed to show.

**Comment by shawkey-daniel** [comment]
> > The section was conditional, now it is not
> 
> Are you sure about that? [This is what I see](https://github.com/department-of-veterans-affairs/vets-website/blob/e31dd17adc669f6c8d74bb937bb6601d264188e4/src/applications/gi/components/vet-tec/VetTecInstitutionProfile.jsx#L44-L58):
> 
> ```js-jsx
>           {/* prod flag for BAH 4227. There are also flags in Programs.jsx and VetTecPrograms.jsx */}
>           {environment.isProduction() && displayVeteranPrograms() ? (
>             <AccordionItem button="Veteran programs">
>               <VetTecVeteranPrograms
>                 institution={institution}
>                 onShowModal={showModal}
>               />
>             </AccordionItem>
>           ) : (
>             <AccordionItem button="Veteran programs">
>               <VetTecVeteranPrograms
>                 institution={institution}
>                 onShowModal={showModal}
>               />
>             </AccordionItem>
>           )}
> ```
> 
> The `<AccordionItem>` looks the exact same in both cases regardless of the condition.
> 
> Please add some unit tests describing/verifying what `<VetTecVeteranPrograms>` is supposed to show.

Originally, the section would not display, if there were no values. Now the section will display with language to handle no values.

**Comment by bkjohnson** [comment]
> Now the section will display with language to handle no values

I'm glad to hear it!  Now I'd like to see some tests to prove it going forward. :slightly_smiling_face:

**Comment by ksantiagomorgan6** [comment]
> > Now the section will display with language to handle no values
> 
> I'm glad to hear it! Now I'd like to see some tests to prove it going forward. 🙂

Unit test have been added for the VetTecVeteranPrograms component

**Comment by bkjohnson** [comment]
It's a good start.  Now there is a test for `Student Veteran Group` availability and one for when no groups are available.  Please add coverage for `VetSuccess on Campus` being available.

Also I think the 0% coverage that codeclimate is showing isn't totally accurate - it may be due to there being no prior unit tests to go off of.  I made a change to your test and ran it locally and it failed as expected, so there is _some_ coverage now:

```diff
diff --git a/src/applications/gi/tests/components/VetTecVeteranPrograms.unit.spec.jsx b/src/applications/gi/tests/components/VetTecVeteranPrograms.unit.spec.jsx
index 2fb36756e..5d9200ab1 100644
--- a/src/applications/gi/tests/components/VetTecVeteranPrograms.unit.spec.jsx
+++ b/src/applications/gi/tests/components/VetTecVeteranPrograms.unit.spec.jsx
@@ -34,7 +34,7 @@ describe('<VetTecVeteranPrograms>', () => {
   it('should render correct data if student veteran group is available', () => {
     const wrapper = mount(<VetTecVeteranPrograms {...defaultProps} />);
     expect(wrapper.length).to.eq(1);
-    expect(wrapper.find('button').text()).to.eq('Student Veteran Group');
+    expect(wrapper.find('button').text()).to.eq('Hello');
     wrapper.unmount();
   });
```

image

**Comment by ksantiagomorgan6** [comment]
> It's a good start. Now there is a test for `Student Veteran Group` availability and one for when no groups are available. Please add coverage for `VetSuccess on Campus` being available.
> 
> Also I think the 0% coverage that codeclimate is showing isn't totally accurate - it may be due to there being no prior unit tests to go off of. I made a change to your test and ran it locally and it failed as expected, so there is _some_ coverage now:
> 
> ```diff
> diff --git a/src/applications/gi/tests/components/VetTecVeteranPrograms.unit.spec.jsx b/src/applications/gi/tests/components/VetTecVeteranPrograms.unit.spec.jsx
> index 2fb36756e..5d9200ab1 100644
> --- a/src/applications/gi/tests/components/VetTecVeteranPrograms.unit.spec.jsx
> +++ b/src/applications/gi/tests/components/VetTecVeteranPrograms.unit.spec.jsx
> @@ -34,7 +34,7 @@ describe('<VetTecVeteranPrograms>', () => {
>    it('should render correct data if student veteran group is available', () => {
>      const wrapper = mount(<VetTecVeteranPrograms {...defaultProps} />);
>      expect(wrapper.length).to.eq(1);
> -    expect(wrapper.find('button').text()).to.eq('Student Veteran Group');
> +    expect(wrapper.find('button').text()).to.eq('Hello');
>      wrapper.unmount();
>    });
> ```
> 
> image

Coverage has been added for Vet Success on Campus

**Review by bkjohnson — APPROVED** [review]

**Pull request merged**
