### PR TITLE
Update links

### PR DESCRIPTION
**Pull request by cvalarida**
## Description
Updates some links.

## Testing done
None. :grimacing:

I'm not sure how to get claims mocked locally, so wasn't able to test this yet.

I did verify that the updated `href`s point to the appropriate pages by manually navigating to their respective URLs.

## Screenshots
:disappointed: 

## Acceptance criteria
- [x] The links are updated to point to the right places

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by cvalarida** [comment]
@bethpotts @DanielleSoCompany Tagging you two on this one since you were on the originating ticket.

**Review by markgreenburg — APPROVED** [review]
LGTM. Links look fine to me.

**Review by bethpotts — APPROVED** [review]
Looks good!

**Comment by bethpotts** [comment]
@cvalarida No need for @DanielleSoCompany to give another content approval. You can move forward.

**Comment by cvalarida** [comment]
@bethpotts Thanks! :raised_hands:

**Pull request merged**
