### PR TITLE
Build task yellow for prefill pattern

### PR DESCRIPTION
**Pull request by adamwhitlock1**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

- Adds a formConfig for our 'task-yellow' for prefill authenticated pattern
- mocks responses for sip PUTs, updating mailing address success, and uses the request history that lives in the mock server memory to mimic the successful transaction for updating mailing address
- mocks address validation to provide a 100% confidence score, so that address updates can be mocked as being saved without any address validation additional step
- Updates form introduction page, and adjusts styles to match the figma designs for the yellow task
- Changed from moment to date-fns for date formatting
- Updated form title and subTitle to match figma designs
- TODO - add save successful alert to the mailing address info view page, similar to green task

## Related issue(s)

- https://github.com/department-of-veterans-affairs/tmf-auth-exp-design-patterns/issues/52

## Testing done

- tested locally, this is a prototype form and will not be getting promoted to prod usage at all

## Screenshots

No before screenshots as this is a new set of pages/formConfig

screencapture-localhost-3001-mock-form-ae-design-patterns-task-yellow-introduction-2024-08-14-20_40_25

screencapture-localhost-3001-mock-form-ae-design-patterns-task-yellow-veteran-information-personal-information-2024-08-14-20_40_42

screencapture-localhost-3001-mock-form-ae-design-patterns-task-yellow-veteran-information-confirm-mailing-address-2024-08-14-20_40_54

screencapture-localhost-3001-mock-form-ae-design-patterns-task-yellow-veteran-information-edit-mailing-address-2024-08-14-20_41_06

## What areas of the site does it impact?

Impact nothing on production, and the only code that is modified is for the authenticated patterns work

## Acceptance criteria

- [x] Yellow task pages built out
- [x] Yellow task accessed by the common task buttons

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by msbtterswrth — COMMENTED** [review]
@adamwhitlock1 once the merge conflicts are fixed should be all set.

**Comment by adamwhitlock1** [comment]
fixed merge conflicts, now waiting on ci/cd to do it's thing 🪄

**Comment by adamwhitlock1** [comment]
@bellepx0 this one is ready for you to review whenever you have a chance, thanks!

**Review by bellepx0 — APPROVED** [review]
Approved!

**Pull request merged**
