### PR TITLE
Home page update to lowercase two words for consistency

### PR DESCRIPTION
**Pull request by mollyblake**
Lower case health care

### CODE REVIEW

**Comment by bethpotts** [comment]
@emilyville Tagging you for awareness that this PR is in progress.

**Comment by bethpotts** [comment]
@rroueche Can you help us with the unsuccessful checks?

**Comment by rroueche** [comment]
@bethpotts we can ignore the two Jenkins checks as that's just in testing, the required checks have passed here - is this ready for me to review and merge to master?

**Comment by mollyblake** [comment]
@rroueche as long as @maryannbrody has had eyeballs on it since it's the home page!  THANKS so much

**Comment by maryannbrody** [comment]
looks good to me! @rroueche

**Review by rroueche — COMMENTED** [review]
Looks good

**Pull request merged**
