### PR TITLE
Updates to healthcare landing page.

### PR DESCRIPTION
**Pull request by webinista**
Closes department-of-veterans-affairs/vets-website#4113

- Changed modulo to equality operator in includes/main-navigation.html
    - tinyliquid does not support the modulo operator.
- Changed height of cards to accommodate new health landing page content.

### CODE REVIEW

**Comment by webinista** [comment]
Not sure who to assign this to for approval, so you all get to review or claim it!

screen shot 2016-11-28 at 3 35 15 pm

**Comment by ayaleloehr** [comment]
This should not be merged into `master` until we're ready to go live with Rx and SM

**Comment by gnakm** [comment]
Visually, LGTM!

**Comment by ayaleloehr** [comment]
@emilyville or @crwallace I believe this should go live on Monday.  And we also need to link the homepage to this page I believe. Should that go in this PR or separate?

**Comment by ayaleloehr** [comment]
LGTM. Removed do not merge label as this can get into master now.

**Pull request merged**
