### PR TITLE
Update vets-json-schema version

### PR DESCRIPTION
**Pull request by cehsu**
References https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3646

Zero default values are now required.
As this change involves a newer version of vets-json-schema, this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/5916), related to an earlier change made to vets-json-schema should be merged first.

screen shot 2017-06-29 at 6 07 26 pm

screen shot 2017-06-29 at 6 08 49 pm

### CODE REVIEW

**Comment by jbalboni** [comment]
@cehsu Should work after merging now

**Review by cvalarida — COMMENTED** [review]
The PR you mentioned has been merged. 🚀

**Review by cvalarida — APPROVED** [review]
...and I forgot to hit approve...

**Comment by jbalboni** [comment]
@cehsu Are the 0 and $ misaligned like that on your screen normally? That's something we should open an issue to fix if it's happening in a particular browser.

**Review by jbalboni — APPROVED** [review]

**Comment by cehsu** [comment]
@jbalboni wow, good catch, this is only a problem when I zoom out for the screenshot.

**Pull request merged**
