### PR TITLE
Add codeowner lines for known apps without explicit owners, assign to…

### LINKED ISSUE #66724: Recent updates to vets-website codeowners identified 14 apps...
Submitted By: jill.adams
 Topic: Something Else
Team: Frontend Support

Recent updates to vets-website codeowners identified 14 apps that do not have listed codeowners. Public Websites would like to add the static-pages paths at minimum, since we get auto-tagged for PR reviews under that path. Any objections to adding all of these with Platform FE as the main codeowner, til actual app owners are identified?   Original PR: https://github.com/department-of-veterans-affairs/vets-website/pull/25743

### PR DESCRIPTION
**Pull request by jilladams**
… Plat FE.

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary
Follow up to https://github.com/department-of-veterans-affairs/vets-website/pull/25743. 
Adds 14 apps that were identified as missing codeowners, and adds them to codeowners with Platform FE as team to review. These ideally would get owned by a product team, and reorganized into the file in other ways, so have added a heading comment to keep them identifiable.

Related Slack thread in #vfs-platform-support: https://dsva.slack.com/archives/CBU0KDSB1/p1696266612367689

closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/66724
Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15303

### CODE REVIEW

**Review by CBonade — APPROVED** [review]
LGTM as long as checks pass!

**Review by randimays — APPROVED** [review]
Thanks Jill!

**Comment by jilladams** [comment]
These Cypress tests failures are so annoying and driving me bonkers.

**Comment by jilladams** [comment]
@CBonade this change is only to .codeowners. I've refreshed branch 3x today, and still getting Cypress fails from various tests that can't possibly be due to my changes. Any chance you have the power to squash/merge it anyway?  Or any suggestions about what I should do here?

**Comment by randimays** [comment]
@CBonade @jilladams Tried a local rebase; running CI

**Comment by randimays** [comment]
@CBonade Still failing CI :(

**Comment by jilladams** [comment]
Gonna go ahead and make a new support thread.

**Pull request merged**
