### PR TITLE
Add cvt appointment kind to mock data

### PR DESCRIPTION
**Pull request by wullaski**
## Summary

- Adds a cvt appointment to mock data so we can see it locally in day of check in by using the all appointment types uuid: `bb48c558-7b35-44ec-8ab7-32b7d49364fc`

Most of the work was already done as part of this ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/72860

## Related issue(s)

- [department-of-veterans-affairs/va.gov-team#72870](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72870)

## Testing done

- Visual

## Screenshots

image
Screenshot 2024-04-18 at 1 28 58 PM

## What areas of the site does it impact?

Check-in/appointment-check-in

## Acceptance criteria

Displays the CVT appointment correctly

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by powellkerry — DISMISSED** [review]

**Review by brianseek — DISMISSED** [review]
this checks out with the Figma other than the known icon differences. One slight nitpick is that we don't need to use the backticks in the values since there are no template literals in there. But really I don't care about it enough for you to make another commit for it.

**Comment by benbrasso-agile6** [comment]
Re: icons, does this message coincide when we'll be making the switch to use the other icon set? 

https://dsva.slack.com/archives/C03R5SBELQM/p1710776364414359

**Comment by brianseek** [comment]
> Re: icons, does this message coincide when we'll be making the switch to use the other icon set?
> 
> https://dsva.slack.com/archives/C03R5SBELQM/p1710776364414359

Yes! @wullaski it is probably worth a little exploration to see if we can use the va-icon now. Especially since these are more points on this ticket than you actually needed

**Review by lee-delarm6 — APPROVED** [review]
Approved, but is it (in the appointment/index.js file, really `location_city` and not `location-city`?

**Comment by wullaski** [comment]
@lee-delarm6 yeah the v3 icons all have snake_case names now https://design.va.gov/foundation/icons

**Pull request merged**
