### PR TITLE
91823 remove burial v2 flipper take 2

### PR DESCRIPTION
**Pull request by balexandr**
Remove all FormV2 things for Burial

### CODE REVIEW

**Review by IGallupSoCo — APPROVED** [review]
LGTM - approved for merging despite unit test stability job failures in CI

**Review by dcloud — DISMISSED** [review]
I think my team was added as CODEOWNER over `src/platform/mhv/api/mocks/user/index.js`, which has some minor mock data changes.

Those particular changes look fine, I believe other people/teams will need to look at the rest of this PR

**Review by IGallupSoCo — DISMISSED** [review]
LGTM

**Comment by balexandr** [comment]
Closed in favor of take 3 https://github.com/department-of-veterans-affairs/vets-website/pull/33528

**Pull request closed without merging**
