### PR TITLE
[ZOOM]: Section 103 - Modal windows MUST be usable at 200% to 400% zoom fix

### PR DESCRIPTION
**Pull request by ksantiagoBAH**
## Description
Several of the modal windows are expanding out of the viewport at 200-250% zoom. I saw this on a few of the longer modals like Yellow Ribbon and the college housing. Screenshot of Yellow Ribbon attached below.

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9240

text button overlap bug 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/9262

## Testing done
local testing

## Screenshots
Screen Shot 2020-05-19 at 1 30 15 PM
Screen Shot 2020-05-19 at 1 29 51 PM
300%
Screen Shot 2020-05-20 at 11 59 03 AM

400%
Screen Shot 2020-05-20 at 11 59 49 AM

500%
Screen Shot 2020-05-20 at 11 51 07 AM

## Acceptance criteria
- [x] The modals do not break out of the viewport at any zoom between 200% and 400%
- [x] No other zoom levels break or change their layout

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by zurbergram — APPROVED** [review]

**Review by 1Copenut — CHANGES_REQUESTED** [review]
I tested this locally on MacOS using Safari, Firefox, and Chrome. Is there a way we could add right padding to the heading at higher sizes? I might be being too picky, but there were some overlaps in text I'd like to avoid if possible. cc @CrystabelReiter for awareness.

#### Firefox and Safari
Screen Shot 2020-05-19 at 1 09 04 PM

**Review by zurbergram — APPROVED** [review]

**Comment by ksantiagomorgan6** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/9262 this issue had a similar request as @1Copenut which has been added to the PR.

**Review by delli-gatti-michael — APPROVED** [review]

**Comment by ksantiagomorgan6** [comment]
> I tested this locally on MacOS using Safari, Firefox, and Chrome. Is there a way we could add right padding to the heading at higher sizes? I might be being too picky, but there were some overlaps in text I'd like to avoid if possible. cc @CrystabelReiter for awareness.
> 
> #### Firefox and Safari
> Screen Shot 2020-05-19 at 1 09 04 PM

fixed

**Review by 1Copenut — APPROVED** [review]
Please ping me when this is deployed to staging and I'll review it on the Windows platform as well.

**Pull request merged**
