### PR TITLE
MyVA - updates to (previously) Saved applications section

### PR DESCRIPTION
**Pull request by allisonlu**
## Summary
After a UX audit of the current MyVA, we decided to update:
- the title of "**Saved applications**" to "**Benefit application drafts**", and 
- empty state copy from "**You have no applications in progress.**" to "**You have no benefit application drafts to show.**" 

This PR also updates relevant unit and e2e tests.

## Related issue(s)
- Ticket: [https://github.com/department-of-veterans-affairs/va.gov-team/issues/52619](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52619)
- Epic: [https://github.com/department-of-veterans-affairs/va.gov-team/issues/41934](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41934)

## Testing done
- MyVA page still renders 
- All unit and e2e tests pass

### LOA3 user
| Before | After |
| --- | --- |
|app-loa3-before | app-loa3-after

## What areas of the site does it impact?
Just MyVA for LOA3 users only

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Documentation has been updated ([link to documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/applications-FE-documentation.md))
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [x]  I added a screenshot of the developed feature

### CODE REVIEW

**Comment by aagosto90** [comment]
@allisonlu This is a minor thing but can we keep the empty state text as it currently is for the LOA1 state? So it should still read "You have no applications in progress to show." The LOA1 experience is a little different from LOA3 and we've chosen to only make updates to the LOA3 experience as part of this audit work. Otherwise, this looks great. Thank you!!

**Review by adamwhitlock1 — APPROVED** [review]
Looks good!

**Comment by adamwhitlock1** [comment]
With the text being conditional on loa level, it did break some of the unit tests. The initial state looks be getting set to:

```
const initialState = {
        user: {
          profile: {
            savedForms: [],
            loa: {
              current: 1,
              highest: 3,
            },
          },
        },
      };
```

But the assertion is looking for the LOA3 text. Probably would be good to update this test to have current be loa3 and then maybe throw in another test to assert the conditional text for loa1

**Comment by allisonlu** [comment]
@ajakabcin Changes are now on staging! 

https://staging.va.gov/my-va/

Log on with any user to see update to title, and any LOA3 user with **no applications in progress** to see the empty state text.

**Pull request merged**
