### PR TITLE
Removes use of vaOnlineSchedulingBreadcrumbUrlUpdate feature flag within appointments breadcrumb component

### PR DESCRIPTION
**Pull request by ryanshaw**
## Summary

Removes the use of the `vaOnlineSchedulingBreadcrumbUrlUpdate` feature flag within appointments breadcrumb component ([VAOSBreadcrumbs](https://github.com/department-of-veterans-affairs/vets-website/blob/e5f78cc86fe5e67ad0067a4448089488f46fa833/src/applications/vaos/components/Breadcrumbs.jsx#L7))

## Related issue(s)

n/a

## Testing done

- Unit testing
- e2e testing

### Quality Assurance & Testing

- [ ] I updated unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Review by vbahinwillit — CHANGES_REQUESTED** [review]
There are still some references to 'vaOnlineSchedulingBreadcrumbUrlUpdate'.

**Comment by ryanshaw** [comment]
> There are still some references to 'vaOnlineSchedulingBreadcrumbUrlUpdate'.

@vbahinwillit This PR is only addressing an issue in the `AppUnavailable` component that was pulling in the the `VAOSBreadcrumbs` component. The issue was caused by the 'vaOnlineSchedulingBreadcrumbUrlUpdate' feature flag in the `VAOSBreadcrumbs` component.

The removal of the feature flag completely from all of the appointments code will be done in future PRs, as a single PR will be way too big to review effectively. 

Were you talking about throughout the entire codebase or just within the files in this PR?

**Comment by vbahinwillit** [comment]
> > There are still some references to 'vaOnlineSchedulingBreadcrumbUrlUpdate'.
> 
> @vbahinwillit This PR is only addressing an issue in the `AppUnavailable` component that was pulling in the the `VAOSBreadcrumbs` component. The issue was caused by the 'vaOnlineSchedulingBreadcrumbUrlUpdate' feature flag in the `VAOSBreadcrumbs` component.
> 
> The removal of the feature flag completely from all of the appointments code will be done in future PRs, as a single PR will be way too big to review effectively.
> 
> Were you talking about throughout the entire codebase or just within the files in this PR?

Ok.

**Review by vbahinwillit — APPROVED** [review]

**Review by IGallupSoCo — APPROVED** [review]
LGTM

**Comment by ryanshaw** [comment]
@simiadebowale Just wanted to double-check to see if there was an issue associated with this -- I can't currently locate one and want to link one up if it exists. Is there an issue?

**Comment by ryanshaw** [comment]
This actually resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/72649

**Pull request merged**
