### PR TITLE
18883: STEM: Update 1995 Workflow

### PR DESCRIPTION
**Pull request by elder-joseph**
## Description
As a Rogers STEM Scholarship applicant, I need to complete the application accurately so I can receive a timely response to the application.

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/18883

## Testing done
Local manual, unit, and end to end tests pass

## Screenshots
N/A

## Acceptance criteria
- [x] If the user answers "Yes" to the question "Are you applying for the Edith Nourse Rogers STEM Scholarship (Chapter 33)?" on the "Education Benefit" page they are ALWAYS directed to the "Are you currently on active duty or do you anticipate you will be going on active duty?" question in the "Military History" section.
- [x] If the user answers "No" to to the question "Are you applying for the Edith Nourse Rogers STEM Scholarship (Chapter 33)?" on the "Education Benefit" page then they are directed to through the current 22-1995 workflow.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by devin-mccurdy — APPROVED** [review]
LGTM!

**Review by zurbergram — APPROVED** [review]
LGTM

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by sonntag-adam — APPROVED** [review]

**Comment by elder-joseph** [comment]
@department-of-veterans-affairs/frontend-review-group Could I get a vets-websitevets-json-schema code review on this at your earliest convenience. Thank you!"

**Review by rianfowler — APPROVED** [review]

**Pull request merged**
