### PR TITLE
Selector fix for edu benefits tests on iOS

### PR DESCRIPTION
**Pull request by jbalboni**
Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4165

Minor change that should fix some of the edu tests (at least the 1990e).

### CODE REVIEW

**Review by aub — APPROVED** [review]
LGTM, good spotting.

**Review by cvalarida — APPROVED** [review]
Oi, these are the worst. Good catch!

**Review by cehsu — APPROVED** [review]
Another great bracket find!

**Comment by cehsu** [comment]
Should this branch be deleted @jbalboni ?

**Pull request merged**
