### PR TITLE
41813 file upload focus on error

### PR DESCRIPTION
**Pull request by jaredcunha**
## Original issue(s)
department-of-veterans-affairs/va.gov-team#41813

# Expected behavior
When the user does not provide a required field in `AddFilesForm`, the `focus` should be transferred from the submit button to the errant form field.

## Current behavior
Focus state remains on the button.

## Your fix
This PR fixes the issue in several
- First, the work correctly sends focus to the invalid fields
- When submitting, error messages for both the checkbox and the file input would appear. This brought up a second issue since… while focus was correctly sent to the invalid file input, the screen reader (Voice Over) was announcing the error on the checkbox, which was confusing. I addressed by displaying on error at a time so that when the focus is sent to the file input, the relevant error announcement is now read. 
- In the checkbox error message, there is a spatial reference. Generally we want to avoid spatial references, but this one needed to be fixed because the reference was incorrect. It would say "Please agree to the above," but the checkbox was actually below the error message.

### To evaluate locally
1. To use Claim Details, [follow these steps use mock data](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/engineering/CST_frontend_details.md#claim-detail-testing).
2. Go to the **Ask VA to Decide Page**, we used this path `http://localhost:3001/track-claims/your-claims/1196201/files`. 
3. Without selecting a file, click Submit Files for Review
4. There should be an error message on the file input, and the focus should be on the "Add Files" button
5. Select a file and make a selection from the drop down, , click Submit Files for Review again
6. There should be an error on the checkbox, and the checkbox should have focus.

## Screenshots
Screen Recording 2022-06-13 at 02 30 55 PM

## Acceptance criteria
- [x] Tests continue to pass
- [x] Invalid fields have an error message, receive focus, and are scrolled to 

## Definition of done
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Review by OptionSelect — APPROVED** [review]
LGTM! 🚀

**Review by alexandec — APPROVED** [review]

**Comment by jaredcunha** [comment]
Found one small bug in the animated screen cap at the top where the error state persists after form submission. Made a fix that addresses, which you can see the resolution in this screen cap.
Screen Recording 2022-06-16 at 01 40 57 PM

**Review by Mottie — APPROVED** [review]
When I left the "this claims only" checkbox unchecked and hit the submit button, the error showed up as expected, but the screenreader read through the entire label before reading out the error. I was hoping to get the error to read first. I don't remember if this is an issue with the component, so you may not have to deal with this in this PR, but we should bring it up with Josh when he gets back.

**Comment by jaredcunha** [comment]
Interesting… I feel like I might have noticed that before, but I can't remember if that was before or after I refactored the submit function a little. But I'm not getting that effect. In VoiceOver, it's reading the error first, then the label.

**Pull request merged**
