### PR TITLE
SSOe keepalive request 

### PR DESCRIPTION
**Pull request by asg5704**
## Description
**Issue**: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15939

This PR modifies the SSOe keepalive request in the FE.  The major impact it has is Chrome DevTools reports waiting for the body content, when we only need information in the response headers.  It also slightly modifies the `alive` variable to use a better type coercion.

* Note: Researched the use of the `HEAD` HTTP request method and concluded that it works across all browsers.

## Testing done
Local
Staging (via fetch requests)

## Screenshots
n/a

## Acceptance criteria
- [x] No response body is provided
- [x] keepAlive function keeps same functionality
- [x] `CAUTION: request is not finished yet` warning is removed

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by ericbuckley** [comment]
@AGarcia-Clarity appologies with the snippet I pasted in the issue, but we don't want to change the content-type or accept headers, as that will mean we need to issue a pre-flight request.  The change should just be changing the method.

Also if you don't mind could you port these keepalive tests from the following PR over here?  There's a good chance we will NOT merge PR 14806.

https://github.com/department-of-veterans-affairs/vets-website/pull/14806/files#diff-2a6e9c3c162f11d97ef909344b03aca858193122b1cee865b3712c36182f616eR342

**Comment by ericbuckley** [comment]
@AGarcia-Clarity could you revert the code changes from https://github.com/department-of-veterans-affairs/vets-website/pull/14920/commits/bd688d934a908254521208445cf6cbd9748a5234?  The tests are useful in this PR, however the actually business logic changes from 14806 will probably be abandoned.

**Comment by AGarcia-Clarity** [comment]
> @AGarcia-Clarity could you revert the code changes from [bd688d9](https://github.com/department-of-veterans-affairs/vets-website/commit/bd688d934a908254521208445cf6cbd9748a5234)? The tests are useful in this PR, however the actually business logic changes from 14806 will probably be abandoned.

Okay I'll delete them 👍

**Review by ericbuckley — APPROVED** [review]
LGTM!

**Review by U-DON — APPROVED** [review]

**Pull request merged**
