### PR TITLE
17767 profile style guide changes

### PR DESCRIPTION
**Pull request by tlei123**
## Description
[17767](/department-of-veterans-affairs/vets.gov-team/issues/17767) - Change Profile LOA3 content per Style Guide updates.  See [changes doc](/department-of-veterans-affairs/vets.gov-team/files/3040564/Profile-LOA3_Content.updates_Feb.2019.docx) for details.

## Testing done
Ran yarn test:unit:personalization and all passed.
No logic or functional code-changes.

## Acceptance criteria
- [ ] All content changes made per [changes doc](/department-of-veterans-affairs/vets.gov-team/files/3040564/Profile-LOA3_Content.updates_Feb.2019.docx).

## Definition of done
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by tlei123** [comment]
Sorry for the noisy commit-history!

All my own commits in this branch have messages starting with ticket# ("17767 - ...").

**Review by ncksllvn — APPROVED** [review]
LGTM

**Review by erikphansen — APPROVED** [review]

**Comment by ncksllvn** [comment]
@tlei123 I think you need to merge latest one more time to fix an unrelated error in master 🙂

**Comment by tlei123** [comment]
Just merged latest master; now watching those tests.

**Pull request merged**
