### PR TITLE
VACMS-12042: Update props to correct data type

### PR DESCRIPTION
**Pull request by chriskim2311**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary
Caught a mismatch in proptype for label-header-level. This PR fixes it

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-cms#12042

### CODE REVIEW

**Comment by chriskim2311** [comment]
For this PR I have discovered that the header tags created are capitalized, which seems to be causing issues with the styles being properly shown in the browser. I have contacted the design team about it or I can add the font weight manually to the radio headers for this implementation.

**Comment by chriskim2311** [comment]
DST has mediated their `<h2>` bug. This PR takes care of mismatch prop types only

**Comment by chriskim2311** [comment]
@randimays This actually has been mediated on Prod. The DST team has merged their changes to update the header to a lowercase '<h2>', Not sure how to pull that change into this instance? https://github.com/department-of-veterans-affairs/component-library/pull/784

**Review by randimays — APPROVED** [review]

**Comment by chriskim2311** [comment]
For context: I have added back the label for the VASelect component and not made it an h2. The axe test we run requires a select dropdown to have a label, I have styled it according to the other semantic h2/visual h4 elements however. Screenshot for reference 
How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs

**Comment by chriskim2311** [comment]
@laflannery For this ticket I have implemented the `<h2>` tags for the radio components. For the select components is it okay to only have the label for it and not an h2? We run an axe test on the wizard and it fails if we do not provide a label for the select component.

**Comment by laflannery** [comment]
@chriskim2311 Yes, you have to have a label for every form element, it doesn't have to be a heading. This is fine to be implemented in this manner for now as ultimately this is going to need to be redesigned as the wizard pattern has been deprecated by the Design System.

**Comment by chriskim2311** [comment]
Thank you Laura we will go with this implementation!

**Pull request merged**
