### PR TITLE
508 compliance

### PR DESCRIPTION
**Pull request by bshyong**
This PR resolves 508 compliance issues in #2633

### CODE REVIEW

**Comment by bshyong** [comment]
@crwallace Made a couple fixes that should drastically decrease the number of violations.

I also went through each issue on the spreadsheet and made a note on each row (see first tab):
[08_03_16_vetsdotgov_508_violation_bshyong.xlsx](https://github.com/department-of-veterans-affairs/vets-website/files/404569/08_03_16_vetsdotgov_508_violation_bshyong.xlsx)

Should I go to some of the other repos and make PRs for design changes there? ie. job search tool, resume tool, etc.

**Comment by crwallace** [comment]
Yes @bshyong! Feel free to make changes and open those PRs and assign them to @melwoodard for design approval.

**Comment by bshyong** [comment]
@crwallace this is ready for review—after the burn-the-world branch got merged, the previous changes got moved into `/old` so I went through the front-end again and made sure they were working post-merge

**Comment by bshyong** [comment]
@awong-dev do you know how I can get access to see why the auto deploys fail?

**Comment by ayaleloehr** [comment]
@bshyong you should have just gotten a Heroku invite, which will allow you to see why it fails. Please let me know if you did not.

**Comment by bshyong** [comment]
@crwallace Rebased, passing tests, and ready for merge.

**Comment by crwallace** [comment]
@maryannbrody -- Will you take a look at the commits for awareness?

**Comment by crwallace** [comment]
closes #2663

**Comment by crwallace** [comment]
LGTM!

**Pull request merged**
