### PR TITLE
content updates

### LINKED ISSUE #21817: COVID-19 vaccine page VA vaccine act passed: Translate new updates
##User story

As a Veteran, spouse, or caregiver seeking the latest info on the new VA vaccine act in Spanish or Tagalog, I need updated information.

## Issue Description
Translate updates made 3.20.21 on English page.

---
## Tasks
- [x] Prep translation docs (Danielle)
- [x] Send docs to Chad (Danielle)
- [x] Make updates on Spanish page (Selina)
- [x] Review and publish Spanish page (Randi)
- [x] Make updates on Tagalog page (Selina)
- [x] Review and publish Tagalog page (Randi)
- [x] Send live links to Mateo's team for review (Randi)
- [x] Incorporate any changes from Mateo's team (Randi, Selina)

## Acceptance Criteria
- [x] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

### PR DESCRIPTION
**Pull request by youngfreezyVA**
resolves: https://github.com/department-of-veterans-affairs/va.gov-team/issues/21817#issuecomment-805831244

### CODE REVIEW

**Review by timwright12 — APPROVED** [review]
Looks good, update appears to match the request!

**Review by RLHecht — COMMENTED** [review]
@youngfreezyVA Just make sure that the Note section is long underneath the new copy. I can't always tell with GH what's still in and what's been removed. These should match the setup of the English version. An intro sentence followed by two bullets and then the CTA button.

**Comment by youngfreezyVA** [comment]
> @youngfreezyVA Just make sure that the Note section is long underneath the new copy. I can't always tell with GH what's still in and what's been removed. These should match the setup of the English version. An intro sentence followed by two bullets and then the CTA button.

To confirm, the old bolded section in the body goes away correct? so for tag, that would be: 
`Paalala: Susubukan naming makipag-ugnayan sa bawat-isang kwalipikadong Beterano sa bawat pangkat ng panganib. Hindi ninyo kailangang mag-sign up para makapagpabakuna.`

also, fyi, here is the common content structure we are using for this widget, across languages:

```   expandedEligibilityContent: {
      veteran: {
        boldedNote: `Kung kayo ay isang Beterano na kasalukuyang tumatanggap ng pag-aaruga sa pamamagitan ng VA,`,
        body: ` tatanungin namin kayo kung ano ang inyong plano patungkol sa bakuna kapag nagparehistro kayo. Maaaring gamitin ng inyong lokal na pasilidad-pangkalusugan ng VA ang impormasyong ito, para matukoy kung kailan makikipag-ugnayan sa inyo kapag karapat-dapat na ang inyong pangkat ayon sa panganib.`,
      },
      nonVeteran: {
        boldedNote: `Kung kayo naman ay isang Beterano, asawa o tagapag-alaga na hindi tumatanggap ng pag-aaruga sa VA, `,
        body: ` magparehistro para malaman kung nais ninyong magpabakuna sa VA. Kung karapat-dapat, makikipag-ugnayan kami sa inyo kapag may bakuna na para sa inyo. Sa ngayon, hindi pa namin alam kung kailan ito.`,
      },
    },

**Comment by RLHecht** [comment]
@youngfreezyVA The layout should look like this (just with the Tagalog and the Spanish text)
Screen Shot 2021-03-24 at 11 51 34 AM

The only new content would be what's in the two bullets, which I see you put in. There should no longer be a section that starts with "**Paalala:**" or "**Nota:**" at the bottom before the CTA button.

Not sure if these directions just made it more confusing?

**Comment by youngfreezyVA** [comment]
> @youngfreezyVA The layout should look like this (just with the Tagalog and the Spanish text)
> Screen Shot 2021-03-24 at 11 51 34 AM
> 
> The only new content would be what's in the two bullets, which I see you put in. There should no longer be a section that starts with "**Paalala:**" or "**Nota:**" at the bottom before the CTA button.
> 
> Not sure if these directions just made it more confusing?

that made it crystal clear, ty @RLHecht

**Pull request merged**
