### PR TITLE
Release to production 20161103

### PR DESCRIPTION
**Pull request by jkassemi**

### CODE REVIEW

**Comment by jkassemi** [comment]
cc @akainic

**Comment by akainic** [comment]
Awesome, thanks @jkassemi! The change we need deployed is in there and looks good.

**Review by crwallace — APPROVED** [review]
LGTM!

**Comment by jkassemi** [comment]
looking into build failure

**Comment by jkassemi** [comment]
@crwallace - failure appears to be due to lack of guards around the latest accessibility tests for buildtypes where the content isn't available.

**Comment by jkassemi** [comment]
@akainic - can you set up guards for the new accessibility specs (something like https://github.com/department-of-veterans-affairs/vets-website/blob/master/test/disability-benefits/e2e/00.claims-list.e2e.spec.js#L1) so they don't run for builds where they're not enabled?

**Comment by akainic** [comment]
@jkassemi yep will take care of that now!

**Pull request closed without merging**
