### PR TITLE
Added title and h1 to page not found shared component

### PR DESCRIPTION
**Pull request by carlosfelix2**
## Summary
Added title and h1 to page not found shared component. Also made the h1 the focus of the page, so screen readers can read the page properly. Also added margins around the top text to match the bottom sections.

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/84588
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/85960

## Testing done
- Updated unit test
- Manual testing for screen reader
  - Turn on your screen reader and navigate to an invalid URL for an application using this page not found component (e.g. http://localhost:3001/my-health/sdfsdf). Verify that the heading is read by the screen reader.

## Screenshots
|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |   image     | localhost_3001_my-health_kj |
| Desktop |    image    |    image   |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

### CODE REVIEW

**Review by radavis — DISMISSED** [review]

**Review by randimays — COMMENTED** [review]
Code changes look good, but there needs to be more left and right margin on the `h1` on mobile; it's nearly touching the edge of the screen. We probably should follow the left/right spacing of the `Common Questions` header?

**Review by jzucadi — DISMISSED** [review]

**Comment by carlosfelix2** [comment]
@randimays Can you provide a screenshot of what you see? Here is what I see on mobile:
www va gov_my-health_sdfsdf


> Code changes look good, but there needs to be more left and right margin on the `h1` on mobile; it's nearly touching the edge of the screen. We probably should follow the left/right spacing of the `Common Questions` header?

**Comment by randimays** [comment]
@carlosfelix2 I was referring to the screenshots you posted ("after") in the PR description

Screenshot 2024-06-17 at 12 37 37 PM

**Comment by carlosfelix2** [comment]
@randimays Ah, thank you! I'll take a look at that.
> @carlosfelix2 I was referring to the screenshots you posted ("after") in the PR description

**Comment by carlosfelix2** [comment]
@randimays I like the idea of matching the bottom sections. I added the margin and it looks a lot better. Many thanks!

**Review by randimays — APPROVED** [review]
Nice, thanks @carlosfelix2!

**Review by radavis — APPROVED** [review]

**Comment by CBonade** [comment]
Platform review delayed pending failing e2e tests.

**Pull request merged**
