### PR TITLE
Ask VA - Progress bar

### PR DESCRIPTION
**Pull request by ediiotero**
## Summary

- Adding a custom form progress bar to the Ask VA form
- _(If bug, how to reproduce)_
- _(What is the solution, why is this the solution)
- The Ask VA team owns this component
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_

## Related issue(s)

- Ticket [821](https://app.zenhub.com/workspaces/ask-va-647a476551689d06655cc815/issues/gh/department-of-veterans-affairs/ask-va/821)

## Testing done

- Old progress bar was split up into chapters. The new one increases based on percentage.
- Go through the form to confirm.
- Manual testing and Unit tests added.

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Desktop |   
Screenshot 2024-07-11 at 12 36 12 PM
     |    
Screenshot 2024-07-11 at 12 35 28 PM
   |

## What areas of the site does it impact?

Only impacts the Ask VA form

### Quality Assurance & Testing

- [X] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [X] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [X] Screenshot of the developed feature is added
- [X] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [X] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [X] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Review by joehall-tw — DISMISSED** [review]
LGTM!

**Review by joehall-tw — DISMISSED** [review]
Not sure if new approval is required. Doing it again, just in case.

**Comment by IGallupSoCo** [comment]
Hey folks, the build workflows were being affected by a branch that was triggering stylelint.  The fix has been merged into main.

**Review by joehall-tw — APPROVED** [review]
Looks good.

**Review by IGallupSoCo — APPROVED** [review]
LGTM

**Pull request merged**
