### PR TITLE
Add SGLI Open Enrollment System instructions by service branch

### PR DESCRIPTION
**Pull request by jstanek**
Army, Navy, Air Force, and Marines must manage SGLI online through the Open Enrollment System. Coast Guard and National Oceanic and Atmospheric Administration must still print paper forms. This work specifies the different instructions for each scenario.

### CODE REVIEW

**Review by peggygannon — APPROVED** [review]
@jstanek Hi, Joe. I made just a few proofreading tweaks.

**Review by bethpotts — APPROVED** [review]
Looks good to go. I changed a subhead size and made some other minor formatting changes. Check out my commit.

**Comment by bethpotts** [comment]
@jstanek You can request a review and merge from Trevor.

**Review by 1Copenut — APPROVED** [review]
@bethpotts I pulled this branch locally and verified changes on my instance. LGTM, merging to master now.

**Comment by 1Copenut** [comment]
@jstanek This one is 💯 and has been merged for 6/28 Thursday afternoon build.

**Pull request merged**
