### PR TITLE
Vamc 14309 vet centers and va should show uniform google maps and sr singletext

### PR DESCRIPTION
**Pull request by eselkin**
## Summary

- Change text on all google maps links in Nearby VA and Nearby Vet Centers on locations pages to "Get Directions on Google Maps" with sr-only title/name of location (chose single template string because otherwise screen reader had an odd pause with two strings).
- Made VA locations have "noopener noreferrer" relationships and "_blank" target
- As a consequence of eslint rules, the `<a>` tag with the phone number for nearby Vet Centers would not save without replacing itself as a `<va-telephone>` component. I have updated the phone number to use that tag and correctly insert the phone number (the auto-correct did not insert the phone number)
- On Facilities team
- No flipper

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14309

## Testing done

- Not uniform text on links prior to change, no screen reader text saying where the directions were intending to take you.
- Go to any Vet Center or VAMC locations page, e.g.: 
    - http://236e9e7a1cff5b8715750aa9b5ca049b.review.vetsgov-internal/greater-los-angeles-health-care/locations/
    - http://236e9e7a1cff5b8715750aa9b5ca049b.review.vetsgov-internal/tallahassee-vet-center/locations/
- Tested links all had uniform text. Tested Mac VoiceOver with links.

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Desktop VAMC  |   Screenshot 2023-10-04 at 4 36 57 PM  |   Screenshot 2023-10-04 at 4 37 24 PM  |
| Desktop VetCenter |  Screenshot 2023-10-04 at 4 38 35 PM  | Screenshot 2023-10-05 at 10 18 32 AM  |

|         | Before | After |
| ------- | ------ | ----- |
| Mobile VAMC  |   Screenshot 2023-10-04 at 4 43 17 PM  |  Screenshot 2023-10-04 at 4 43 44 PM  |
| Mobile VetCenter |  Screenshot 2023-10-04 at 4 49 46 PM | Screenshot 2023-10-05 at 10 17 21 AM  |

## What areas of the site does it impact?

VAMC locations pages and Vet Center locations pages

## Acceptance criteria
- [x] The directions links should be programmatically unique and provide information as to the location the directions pertain using the sr-only pattern
- [x] All links should open in a new tab with target="_blank"
- [x] All directions links should also have noreferrer attribute
- [x] All directions links visually say "Get Directions on Google Maps" [opted for directions in lowercase as example in the issue and elsewhere on the site]
- [ ] Accessibility review

### Quality Assurance & Testing

- [x] No new testing.
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated (No documentation - self-documenting)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (N/A)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user (no affected logged-in routes)

## Requested Feedback

- [ ] Go to a [VAMC locations page](http://236e9e7a1cff5b8715750aa9b5ca049b.review.vetsgov-internal/greater-los-angeles-health-care/locations)
- [ ] Check Nearby VA locations have "Get directions with Google Maps" link titles and sr-only attributes
- [ ] Check links open in a new tab
- [ ] Go to [Vet Center locations page](http://236e9e7a1cff5b8715750aa9b5ca049b.review.vetsgov-internal/tallahassee-vet-center/locations/)
- [ ] Check Nearby Vet Center locations have "Get directions with Google Maps" link titles and sr-only attributes
- [ ] Check links open in a new tab

### CODE REVIEW

**Review by maxx1128 — APPROVED** [review]
LGTM and the code checks out 👍

**Comment by eselkin** [comment]
@laflannery Can you double check the sr-only attribute works as expected? I tested on Mac VoiceOver, but wanted to be sure.

**Review by chriskim2311 — APPROVED** [review]
LGTM

**Comment by laflannery** [comment]
@eselkin Just a couple edits:
- Vet center pages:
  - There is an `aria-label` attribute on the directions links that should be removed:
image

- Both Vet Center and VAMC pages:
  - Can you add a space after "Maps"? If you don't the link text will run into "to" as one word (This tactic is done on the other locations links if you need examples)
    - Without a space: 
image
    - With a space:
image

**Comment by eselkin** [comment]
@laflannery it's only forcibly adding a space in one spot. Should I add the forced space in other Google directions links as well? I imaging I should, so I'm doing it, but can revert.

**Review by laflannery — APPROVED** [review]

**Comment by laflannery** [comment]
Reviewed and approved, both Vet Center pages and VAMCs

**Pull request merged**
