### PR TITLE
WIP/VIC welcome page

### PR DESCRIPTION
**Pull request by DanielleSoCompany**

### CODE REVIEW

**Comment by peggygannon** [comment]
@DanielleSoCompany I made just a few copy edits. Otherwise LGTM.

**Review by peggygannon — APPROVED** [review]

**Comment by peggygannon** [comment]
@jbalboni Can you review the code for the green apply button? I want to be sure I have the correct coding in the file. Thank you!

**Review by jbalboni — APPROVED** [review]

**Comment by jbalboni** [comment]
@peggygannon @DanielleSoCompany I made two changes, one to make the broken link checker ignore the apply page and another to put this file in the ignore list, so we can merge it before we go live in production.

**Comment by peggygannon** [comment]
thanks, @jbalboni  This is ready to merge into the VIC 2.0 PR/application. Sorry I forgot to mention that too!

**Pull request merged**
