### PR TITLE
10916 changes education wizard question order

### PR DESCRIPTION
**Pull request by apisandipas**
## Description
Reorders the questions for the Education Wizard so users are asked:
"Has your sponsor transferred their benefits to you?" then "Is your sponsor deceased, 100% permanently disabled, MIA, or a POW?"

## Original issue(s)
department-of-veterans-affairs/va.gov-cms#10916

## Testing done
Local manually testing against proposed workflow in Mural document:
https://app.mural.co/t/vagov6717/m/vagov6717/1664998387811/4be58c5f39967b921ca8cba2bfc77511b867eb00?sender=u907f83e01e35bb04de6f8139

## Screenshots
Screenshot 2022-11-08 at 11 24 32 AM

## Acceptance criteria
- [x] The question about "transferred benefits to you" appears before "is sponsor deceased etc" question
- [x] "Apply now" button is no longer present under the Alert at the "dead end" (if they answer No to the final question)
- [ ] Requires design/product review
- [ ] Loop back to EDU stakeholders to confirm fix and set KPI tracking cadence

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by markkvba** [comment]
@apisandipas I think we'll need to run this by EDU to ensure they still want/expect this.

**Comment by apisandipas** [comment]
@jilladams As per the comment left above, we should run this by EDU to make sure they know it's coming down the line/ assure its still wanted.

**Comment by jilladams** [comment]
Following up with @wesrowe

**Comment by wesrowe** [comment]
I can confirm that there was much discussion with the EDU stakeholders and it is clear that they feel switching these questions is a valuable step. They intend to follow up with an effort to add some context _before_ these questions to prevent remaining confusion. Tammy Hurley is the stakeholder who communicated this.

**Comment by wesrowe** [comment]
Forgot to tage @markkvba @jilladams @apisandipas in my previous comment

**Comment by jilladams** [comment]
Thanks Wes! @apisandipas that's clearance to merge when other checks are passing / code is approved.

**Comment by markkvba** [comment]
PR discussed with EDU sponsor (Cinda) and was approved. Will be adding to our release board and moving forward with approval.

**Review by jtmst — APPROVED** [review]
Checked out on review instance. LG

**Review by GovNapoleon — APPROVED** [review]

**Review by it-harrison — APPROVED** [review]

**Review by eubiera — APPROVED** [review]

**Pull request merged**
