### PR TITLE
Bower all the things rebase

### PR DESCRIPTION
**Pull request by llimllib**
(This is a version of #603 rebase on current master. This PR is @benbalter's, not mine)

This pull request implements using [Bower](http://bower.io/), a static asset package manager, to manage the various vendored dependencies.

Specifically:
- Foundation
- Bourbon
- Neat
- wow
- Modernizr
- html5shiv
- jquery.tipsy
- classy

The advantage here, is that the various components can be semantically versioned (rather than haphazardly copied) and upgraded as simply as `bower update`. 

The output of the resulting site should be identical, with vendored files moving from `_sass/vendor` and `assets/js/vendor` to `assets/vendor`.

As you can see, many of the components have already been updated since they were originally copied.

### CODE REVIEW

**Comment by benbalter** [comment]
>  why did you change around the scss files? Does that have something to do with bower?

They should be 99% not-changed (but moved). Two changes:

1. Moved the files from `_sass` to `assets` so that bower'd assets could be served out as part of the generated site (which they wouldn't be if living in _sass), and made a symlink to keep the includes working.

2. There was a variables file, which seems to be part of Foundation, but customized, which I appended to the existing variables file.

> Unable to find a suitable version for modernizr, please choose one:

Which version of modernizer do you want to use? I suspect 3.x, but you can modify the /package.json file to drop it back to ~2.8, if you'd like as well.

**Comment by llimllib** [comment]
On serving this branch, I get three errors:

```
        ** ERROR: directory is already being watched! **

        Directory: /Users/llimllib/adhoc/vets-website/assets/vendor/foundation/scss/foundation

        is already begin watched through: /Users/llimllib/adhoc/vets-website/assets/vendor/foundation/scss/foundati
on

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
        ** ERROR: directory is already being watched! **

        Directory: /Users/llimllib/adhoc/vets-website/assets/vendor/bourbon/app/assets/stylesheets

        is already begin watched through: /Users/llimllib/adhoc/vets-website/assets/vendor/bourbon/app/assets/style
sheets

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
        ** ERROR: directory is already being watched! **

        Directory: /Users/llimllib/adhoc/vets-website/assets/vendor/neat/app/assets/stylesheets

        is already begin watched through: /Users/llimllib/adhoc/vets-website/assets/vendor/neat/app/assets/styleshe
ets

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
```

**Comment by llimllib** [comment]
(sorry for the super slow responses, VEC fell apart a bit and I had to jump in there)

**Comment by benbalter** [comment]
> On serving this branch, I get three errors:

That's a limitation/bug in listen, that I believe is safe to ignore (and only affects local development). It's because the _sass assets are symlinked to the assets/vendor directory.

**Comment by llimllib** [comment]
> > Unable to find a suitable version for modernizr, please choose one:
> Which version of modernizer do you want to use? I suspect 3.x, but you can modify the /package.json file to drop it back to ~2.8, if you'd like as well.

Heck if I know, I just think that `bower update` shouldn't be asking me that; if we ask every developer to make this choice then we're going to see a confusing error because two of them selected different options.

**Comment by llimllib** [comment]
After I `bower update`, I get a much different modernizr layout than the one that's checked into this PR, causing a large amount of deletions/untracked files in my repo. Should I commit the updated modernizr?

**Comment by llimllib** [comment]
ah! that's because you checked in 2.8.3 not 3.2 . I'm just going to remove the dependency from `bower.json` and let it come from `foundation`

**Comment by llimllib** [comment]
Should this PR change the `foundation.min.js` references to `assets/vendor/foundation` instead of `assets/js` and remove `assets/js/foundation.min.js`?

**Comment by llimllib** [comment]
I'm happy to do so if you think it should. Otherwise, LGTM; the concatenating of variables was what confused me.

**Comment by dannychapman** [comment]
Circling back on this. Any more feedback @benbalter or @llimllib? I'd love to get this one merged.

**Comment by llimllib** [comment]
still waiting on this Q: https://github.com/department-of-veterans-affairs/vets-website/pull/692#issuecomment-157840701 , I think those should be changed?

**Comment by benbalter** [comment]
> Should this PR change the foundation.min.js references to assets/vendor/foundation instead of assets/js and remove assets/js/foundation.min.js?

I believe so, yes. If there are references to elsewhere-vendored modules, that was an oversight on my part.

**Comment by awong-dev** [comment]
This PR is stale enough that I think we should just kill it. Any objections?

**Comment by dannychapman** [comment]
@awong-dev Actually, I'd really like to ship this if we can. Shouldn't be too hard to rebase... There's good stuff in here.

**Comment by awong-dev** [comment]
Ah...I see what it's trying to do. Okay.  Will leave around.

Also, @dannychapman: get off work email :)

**Comment by awong-dev** [comment]
going to try to revive this, and might also move us to webpack + npm instead.

**Comment by awong-dev** [comment]
Obsoleted by #1135. Closing.

**Pull request closed without merging**
