### PR TITLE
Updated field lengths for edu-benefits

### LINKED ISSUE #3163: USWDS change field length
Field lengths in some places could better match the data we're collecting:

Fields:

- SSN
- Zip
- Phone number
- Suffix
- Year

### PR DESCRIPTION
**Pull request by jbalboni**
Closes #3163.

This updates a few fields to be shorter on non-mobile screens:
- SSN
- Zip
- Phone numbers
- Suffix
- Year fields

I also updated the year fields to all be number inputs.
## screen shot 2016-09-28 at 10 16 26 am

screen shot 2016-09-28 at 10 16 57 am

### CODE REVIEW

**Comment by jbalboni** [comment]
@cweber Are there any other fields you were thinking of for this?

**Comment by cweber** [comment]
That looks like all of the right stuff to me.

**Comment by jbalboni** [comment]
@akainic Can you take a look when you have a chance?

**Comment by akainic** [comment]
From a code standpoint this looks totally fine. From a design standpoint I think some of the fields look a bit odd now. In particular SSN and phone numbers. I'm not sure if it's because I'm used to seeing the fields with a longer length, or if it's that the labels extend beyond the fields, or if it's just too narrow for the number of characters we need to fit in there. The smaller input length looks totally fine for Suffix and Year, just for SSN and Phone it seems slightly too small. Thoughts @cweber and @goldenmeanie?

**Comment by cweber** [comment]
I'll give it a closer look.

@jbalboni Do we have a standard set of field lengths to pick from? (tiny, small, medium...)

**Comment by jbalboni** [comment]
@cweber It looks like there's just tiny and medium. I ended up using medium everywhere because some of the fields looked weird (like Anne pointed out) even at the medium size.

**Comment by cweber** [comment]
It seems like medium is our best option out of the existing choices that are built into US WDS form field styling. So I think we should go with it.

That said, it might be worth one of us submitting an issue to US WDS to inquire about the limits. I'' curious how intentional it is.

**Pull request merged**
