### PR TITLE
Update prescriptions API url

### PR DESCRIPTION
**Pull request by alexose**
This updates the prescriptions API to look more like it does on production.  This will mean that it will work regardless of where it is deployed.

### CODE REVIEW

**Comment by alexose** [comment]
That said, this URL should live in a config file somewhere so that it's easy to change (e.g., if the API version increments to `v1`).

**Comment by U-DON** [comment]
LGTM. But I thought this change only affects local development? Does webpackDevServer run in deploy environments?

**Comment by U-DON** [comment]
Blah, never mind, I see you changed it in the action creators too.

**Comment by alexose** [comment]
:D  Thanks

**Pull request merged**
