### PR TITLE
add facilities.json file to repo so it deploys properly

### PR DESCRIPTION
**Pull request by ayaleloehr**

### CODE REVIEW

**Comment by ayaleloehr** [comment]
There was previously a process for updating facilities.json where it wasn't in the repo, but this will break when we go to a sync in S3 instead of just copying files over. Adding this file here is the simplest method for fixing this. 

One caveat though is that this file really needs to be gzipped when served, since it's so large. @jbalboni was talking about enabling that across vets-website, so @jbalboni do you want to add that change to this PR or create another PR and just merge them to master around the same time so this one doesn't go live first?

**Comment by ayaleloehr** [comment]
CORS issues should be fixed now with that last commit so that it pulls from the correct S3 bucket, instead of always wanting to use the production one.

**Comment by ayaleloehr** [comment]
Assigning to @jbalboni to get his thoughts on adding gzipping to files on deploy. If that is to be done elsewhere though, feel free to assign back to me or to anyone else for review (likely Courtney, Albert, or Ben, so just pick one).  :)

**Comment by awong-dev** [comment]
LGTM

**Comment by awong-dev** [comment]
gzip is a separate issue. Am going to merge this as it just fixes a timebomb.

**Comment by jbalboni** [comment]
@ayaleloehr Sorry, didn't see this until now. Gzipping should probably be done in the server (which looks like nginx?) config, wherever that lives, so it doesn't need to be handled during deploys.

**Comment by awong-dev** [comment]
@jbalboni Can you coordinate with Ken and/or James?  You're looking for the reverse proxy configs in the devops repo.

**Pull request merged**
