### PR TITLE
EDM-272/implement SOB print page flipper

### PR DESCRIPTION
**Pull request by jefftmarks**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

### :warning: TeamSites :warning:
Examples of a TeamSite: https://va.gov/health and https://benefits.va.gov/benefits/. This scenario is also referred to as the "injected" header and footer. You can reach out in the `#sitewide-public-websites` Slack channel for questions.

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

- _(Summarize the changes that have been made to the platform)_: There is currently a bug where print page for GI Bill Statement of Benefits will not load. This is do to a null error which is the result of a content-build classname update (https://github.com/department-of-veterans-affairs/content-build/pull/2254). The component is looking for DOM element with classname ".va-nav-breadcrumbs' which no longer exists. Author of PR Andrew Steele instructed us to change query selector to look for 'va-breadcrumbs'. Putting this fix behind feature flag because we cannot test locally and can only test in staging.
- _(If bug, how to reproduce)_: Log into the app in staging [here](https://staging.va.gov/education/check-post-9-11-gi-bill-benefits/) as user:
  - [vets.gov.user+12@gmail.com](mailto:vets.gov.user+12@gmail.com)
  - password: [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)
- _(What is the solution, why is this the solution)_: Conditionally render query selector for bread crumb element based on feature toggle
- _(Which team do you work for, does your team own the maintenance of this component?)_: Education Data Migration (EDM), yes
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_: As soon as this fix is implement and tested in staging, we will enable in production and then remove flipper toggle. Success criteria is that print page loads.

## Related issue(s)

- https://github.com/department-of-veterans-affairs/vets-website/pull/32588
- https://github.com/department-of-veterans-affairs/vets-api/pull/18934
- https://jira.devops.va.gov/browse/EDM-272
- 
## Testing done
Unit tests did not catch this bug. This is because in local environment vets-website does not draw from content-build and instead uses [dev-template](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/landing-pages/dev-template.ejs#L164) file. It looks like this file needs to be updated, which I will work separately with platform team to accomplish.

## What areas of the site does it impact?

Post-911 Statement of Benefits

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

As noted above, it looks like dev-template file needs to be updated to match changes implemented by the breadcrumbs.html update in content-build. Currently discussing this with author of that PR Andrew Steele

### CODE REVIEW

**Review by CBonade — CHANGES_REQUESTED** [review]
While I see that some of the linting warnings are about lines that have not been changed (like the <va-button> vs <button> one) but some of them are newly introduced (or seemingly newly introduced) by new code here. Can we try and resolve some of these prior to merge, or deem that they are not able to be resolved (or shouldn't), before we add more to the pile of warnings?

**Comment by jefftmarks** [comment]
> While I see that some of the linting warnings are about lines that have not been changed (like the vs one) but some of them are newly introduced (or seemingly newly introduced) by new code here. Can we try and resolve some of these prior to merge, or deem that they are not able to be resolved (or shouldn't), before we add more to the pile of warnings?

Hey @CBonade thanks for the review! Just made the linting changes and re-requested review. We can create a separate ticket to update the button element to a web component to chip away at this linting errors

**Review by CBonade — APPROVED** [review]

**Comment by CBonade** [comment]
This looks SO much better. Thank you!

**Review by binq — APPROVED** [review]
LGTM

**Pull request merged**
