### PR TITLE
Update cancel appointment and request confirmation pages

### PR DESCRIPTION
**Pull request by JunTaoLuo**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

- We noticed that our cancellation confirmation and review pages had outdated null state logic and this PR updates the logic in accordance with the latest design requirements.
- Appointments (VAOS) Team
- This feature is not behind a Flipper

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/90999

## Testing done

- Tested UI locally, see screenshots below
- Ensured unit tests pass

## Screenshots

| Type | Full content | Null state 1 | Null state 2 | Null state 3 |
| - | - | - | - | - |
| In person | image| image| image| image|
| Phone | image| image| image| image|
| CC Request | image| image|  |  |
| VA Request - Details | image| image| image|  |
| VA Request - Cancellation | image| image| image|  |

## What areas of the site does it impact?

Appointments (VAOS)

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
FYI the "Other details: none" on CC Request is a null state bug that I'll file another ticket for since it's out of scope of this PR. The bug affects both CC request and CC appointment.

**Review by jenniemc — CHANGES_REQUESTED** [review]
Nice job refactoring cancel page layout for in-person and phone cancel appointments. Locally confirmed the provider information displays in the cancel review page.

In the VA request, looking at Null state 1 screenshot, text information is missing under the Facility heading. 

In the CC request, based on the [updated canceled design for Preferred Community Care Provider](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=1183-199238&node-type=section&t=k0i7OmV47tu4kKMI-0), it should display [Provider name] and [address]. It doesn’t ask for [Treatment Speciality]. Maybe confirm this with the UI team?

**Comment by outerpress** [comment]
>  I agree that it looks odd this way so maybe we should use the same logic as confirmed appointments (i.e. the same content as phone appointment null state 2 and null state 3)?

That makes sense to me, as long as we can apply the same logic to both cards (details and cancelation). I'll get the feature reference updated.

**Comment by JunTaoLuo** [comment]
@jenniemc this is ready for another look!

**Review by jenniemc — APPROVED** [review]
LGTM!

**Pull request merged**
