### PR TITLE
Remove contact modal from profile

### PR DESCRIPTION
**Pull request by sanlouise**
## Description
Removed ""Changes your contact information..." modal component from the codebase (as it needed to be removed from the profile, the only place we were rendering it).

## Testing done
Unit tests still pass.

## Acceptance criteria
- [x] Remove ""Changes to your contact information..." modal from the profile

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by kelsonic — APPROVED** [review]
LGTM! 🎉

**Comment by kelsonic** [comment]
Random e2e test failed, rerunning Jenkins 🤞

**Review by erikphansen — APPROVED** [review]

**Comment by erikphansen** [comment]
I didn't even know there was a ticket for this work!

**Comment by kelsonic** [comment]
e2e test keeps failing: 

image

Seems unrelated and we should probably bring this up to #vfs-platform-support

**Review by ncksllvn — APPROVED** [review]
LGTM!

**Comment by kelsonic** [comment]
Yahoo! e2e tests passed! 😅

**Comment by sanlouise** [comment]
@mshea0606 

When you have a moment, could you validate and move this ticket? Thank you!

**Pull request merged**
