### PR TITLE
Find a Rep 2.0 internal qa changes

### PR DESCRIPTION
**Pull request by cosu419**
## Summary
Making refinements ahead of staging review. Adjusted styling, copy/casing, UI focus behaviors, heading structure, media queries, and unit tests.

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75902
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75889
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/76040
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75874
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75867
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75887
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75704
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75813
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/74720
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/74779

## Testing done

- Updated unit tests to reflect new copy and element structure.  

## Screenshots

image
image
image

## What areas of the site does it impact?

- Staging (app is not enabled in production)

### CODE REVIEW

**Review by rmessina1010 — COMMENTED** [review]
I could be missing something about the semantic hierarchy at play here. The title is now H3;  the subsequent  headings generated are H3 are they not subordinate to the title?

**Comment by cosu419** [comment]
> I could be missing something about the semantic hierarchy at play here. The title is now H3; the subsequent headings generated are H3 are they not subordinate to the title?

@rmessina1010 I was experimenting with using an explicit h3 in place of the modalTitle, because for some reason the font size of the modal text is being inflated - the computed size of the h3 modalTitle is 21.44px vs 20px, for example. Our team's designer caught this and I tentatively put in this change, but upon further discussion we decided not to override the core behavior. Change was reverted, thanks!

**Review by holdenhinkle — APPROVED** [review]
Looks good!

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Pull request merged**
