### PR TITLE
Add GIBS nav

### PR DESCRIPTION
**Pull request by raquelromano-gov**
Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3482
Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3272

Profile page for LOA1 user:
image

Profile page for LOA3 user:
image

### CODE REVIEW

**Review by annekainicUSDS — COMMENTED** [review]
This looks good, although it looks like from the ticket we're also supposed to be adding a link to the profile page. Should we be doing that here as well @rroueche?

Also let's wait to merge until the daily deploy goes out for the day so this doesn't accidentally get deployed to prod early.

**Comment by rroueche** [comment]
thanks @raquelromano-gov ! could you add it to the Account/Profile page as well? "Check Post-9/11 GI Bill benefits"

Rachael

**Comment by raquelromano-gov** [comment]
@rroueche added the profile page links

**Review by rroueche — APPROVED** [review]
LGTM!

**Pull request merged**
