### PR TITLE
16737 spot check

### PR DESCRIPTION
**Pull request by youngfreezyVA**
resolves #16737 based on this new comment: https://github.com/department-of-veterans-affairs/va.gov-team/issues/16737#issuecomment-739055927

### CODE REVIEW

**Comment by zacharymorel** [comment]
There's an issue with using the screen reader on this. 

After the vet clicks the button, the screen reader reads the entire javascript function.

**Comment by youngfreezyVA** [comment]
> There's an issue with using the screen reader on this.
> 
> After the vet clicks the button, the screen reader reads the entire javascript function.

could you elaborate a bit more? also, feel free to implement a fix as this was originally your ticket.

> There's an issue with using the screen reader on this.
> 
> After the vet clicks the button, the screen reader reads the entire javascript function.

looping in @1Copenut and @jenstrickland here. @zacharymorel could you elaborate? You may have additional insight as you were the original author of this code.

**Comment by zacharymorel** [comment]
Yeah, I was looking at the review instance, when the user clicks the Back To Top Button, the screen reader will read the javascript within the listener that is attached to it.

**Comment by jenstrickland** [comment]
Is there somewhere I could take a look? I just tried https://staging.va.gov/resources/signing-in-to-vagov/ with VoiceOver, and it read correctly for where it was directed — although I realize it's focused on `#content` and the change is going to `body`. Does it need to go to `body.merger` or could it just go to `body`? 

Which screen reader pairing is reading the JS function?

**Comment by zacharymorel** [comment]
> Is there somewhere I could take a look? I just tried https://staging.va.gov/resources/signing-in-to-vagov/ with VoiceOver, and it read correctly for where it was directed — although I realize it's focused on `#content` and the change is going to `body`. Does it need to go to `body.merger` or could it just go to `body`?
> 
> Which screen reader pairing is reading the JS function?

Do you have your SOCKS configured?

**Comment by jenstrickland** [comment]
I do have SOCKS access, and when I check with VoiceOver and Chrome it works as expected.

**Review by zacharymorel — APPROVED** [review]

**Review by U-DON — APPROVED** [review]

**Pull request merged**
