### PR TITLE
Update back link text on request details page

### PR DESCRIPTION
**Pull request by jenniemc**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

### :warning: TeamSites :warning:
Examples of a TeamSite: https://va.gov/health and https://benefits.va.gov/benefits/. This scenario is also referred to as the "injected" header and footer. You can reach out in the `#sitewide-public-websites` Slack channel for questions.

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

Change the back link text in request details page to "Back to pending appointments"

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#93129

## Testing done

unit test

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |     Screenshot 2024-10-23 at 10 40 59 AM  |  Screenshot 2024-10-23 at 1 32 28 PM   |

## What areas of the site does it impact?

request appointment details page back link text

## Acceptance criteria

- [ ] Change the back link text in request details page to "Back to pending appointments"

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### CODE REVIEW

**Review by JunTaoLuo — APPROVED** [review]
Hmmm the code says "Back to pending appointments" but the screenshot says "Back pending appointments" which is missing the word "to". Is that just an outdated screenshot? Otherwise the code looks good.

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Comment by jenniemc** [comment]
> Hmmm the code says "Back to pending appointments" but the screenshot says "Back pending appointments" which is missing the word "to". Is that just an outdated screenshot? Otherwise the code looks good.

Good catch @JunTaoLuo! That's what I get for being in a hurry. I've uploading a correct screenshot.

**Comment by JunTaoLuo** [comment]
Haha sounds good, feel free to merge!

**Pull request merged**
