### PR TITLE
[WIP] Health Care - obsolete

### PR DESCRIPTION
**Pull request by rroueche**

### CODE REVIEW

**Comment by melwoodard** [comment]
Content is poured, heroku issues preventing launch of staging link. Working w/ eng team to unblock. Next step: proofread.

**Comment by DanielleSoCompany** [comment]
Staging link handed off to SMEs on 5.18.17. Awaiting SME feedback.

**Comment by bethpotts** [comment]
Proofreading all Health Care pages this week (6/19-23)

**Comment by bethpotts** [comment]
Proofreading complete!

**Pull request closed without merging**
