### PR TITLE
Match :visited site-wide

### PR DESCRIPTION
**Pull request by phiden**
See issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3248

### CODE REVIEW

**Review by robertfairhead — APPROVED** [review]
This fixes side nav. 💯 

The original issue also indicated next/prev at the bottom should not change on :visited but this PR doesn't address that. 

screen shot 2017-08-09 at 3 02 23 pm

Assuming that'll be in another PR so 👍  on this

**Comment by phiden** [comment]
ah! forgot about next/prev. Will add them that to this PR and re-request. Thanks @robertfairhead!

**Comment by phiden** [comment]
@robertfairhead added the next/prev nav; would you review please when you have a minute?

**Comment by robertfairhead** [comment]
LGTM!

**Pull request merged**
