### PR TITLE
Add analytics to Action Links on static pages

### PR DESCRIPTION
**Pull request by bsmartin-ep**
## Description

For:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/23364

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by bsmartin-ep** [comment]
@jonwehausen - FYI I don't think the type (primary, secondary, reverse) is separate from the icon color.  Do we keep the icon color param nonetheless or does it just complicate things?

**Review by k80bowman — APPROVED** [review]

**Comment by jonwehausen** [comment]
> @jonwehausen - FYI I don't think the type (primary, secondary, reverse) is separate from the icon color. Do we keep the icon color param nonetheless or does it just complicate things?

@bsmartin-ep I threw that in there as a way to monitor this over time (if the colors ever were to change), but feel free to throw out if you don't see it as a value add

**Comment by bsmartin-ep** [comment]
> > @jonwehausen - FYI I don't think the type (primary, secondary, reverse) is separate from the icon color. Do we keep the icon color param nonetheless or does it just complicate things?
> 
> @bsmartin-ep I threw that in there as a way to monitor this over time (if the colors ever were to change), but feel free to throw out if you don't see it as a value add

Makes sense to me @jonwehausen.  Icon Color has been re-added.  Can you re-test?

**Review by jonwehausen — APPROVED** [review]
Code looks good, but please see testing [here ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23364#issuecomment-825087032)

**Review by ncksllvn — APPROVED** [review]

**Comment by bsmartin-ep** [comment]
@jonwehausen - 

I think I found the issues...

image

Please re-test.  Thanks!

**Comment by jonwehausen** [comment]
@bsmartin-ep We are good to squash & merge here...please see [updated test results](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23364#issuecomment-825656281)

**Pull request merged**
