### PR TITLE
Bold labels for claim status

### PR DESCRIPTION
**Pull request by austin-martinez**
Fixes https://github.com/department-of-veterans-affairs/sunsets-team/issues/263
screen shot 2016-12-09 at 12 35 42 pm

### CODE REVIEW

**Review by jbalboni — APPROVED** [review]
LGTM

**Comment by jbalboni** [comment]
@austin-martinez Actually, I wonder if the labels on the files tab should be bold, too?

**Comment by jbalboni** [comment]
Never mind, that's in a separate issue: [268](https://github.com/department-of-veterans-affairs/sunsets-team/issues/268)

**Review by molindoz — APPROVED** [review]
LGTM

**Pull request merged**
