### PR TITLE
phone appointment block

### PR DESCRIPTION
**Pull request by brianseek**
## Description
Adds an alternative component for when phone appointment feature is on. When we depreciate the feature, we can rename the alt component and remove the old one.

## Original issue(s)
department-of-veterans-affairs/va.gov-team#38266

## Testing done
Added unit tests for new alt component

### CODE REVIEW

**Comment by brianseek** [comment]
> For in-person - is adding the facility name in scope for this PR? Everything else looks good but I just noticed the wireframe also shows facility on in-person appointments. Screen Shot 2022-06-21 at 12 15 19 PM

Yes, I think you are correct. I'll look into that, it may be a different ticket but maybe not.

**Comment by loripusey** [comment]
Yes, Facility Name is specified in the original ticket.

**Comment by brianseek** [comment]
@brdunfield added facility name for in person appointments with tests.

**Review by alexandec — APPROVED** [review]

**Comment by brianseek** [comment]
> On the Introduction page (list of appointments before answering questions), phone appointments now show the blue box "your provider will call you" (Which is different from the blue box displayed on the confirmation page), while in-person appointments do not have any blue box. Is this intentional? I'm having difficulty understanding whether that was an AC of the ticket.

That is what I am seeing in the mocks, but maybe worth an after meeting today.

**Review by brdunfield — APPROVED** [review]
Looks good to me. Thanks for clarifying the scope! 🚀

**Pull request merged**
