### PR TITLE
Navigation menu adjustments and fixes.

### PR DESCRIPTION
**Pull request by ghost**
Related to department-of-veterans-affairs/vets.gov-team#1175

- Removed underline from .va-button-primary. Closes department-of-veterans-affairs/vets.gov-team#1220.
- Change color of active second-level button. Closes department-of-veterans-affairs/vets.gov-team#1230.
- Changed background color of back buttons. Closes department-of-veterans-affairs/vets.gov-team#1220
- Corrected color of vetnav-panel links. Closes department-of-veterans-affairs/vets.gov-team#1231
- Added border to work in progress message. Closes department-of-veterans-affairs/vets.gov-team#1229
- Changed size of icons for menu toggle buttons. closes department-of-veterans-affairs/vets.gov-team#1227
- Increased space between logo/close button and menu links.

    - closes department-of-veterans-affairs/vets.gov-team#1225
    - closes department-of-veterans-affairs/vets.gov-team#1223

- Fixed mitered corners for borders on links. closes department-of-veterans-affairs/vets.gov-team#1222

### CODE REVIEW

**Comment by jcmeloni-usds** [comment]
@tiffanybbrown-va Is this a running PR (I know you combined stuff -- yay!) or are you ready for review?

**Comment by tiffanybbrown-va** [comment]
In some weird rabbit hole of errors with this one. Trying to detangle.

**Comment by tiffanybbrown-va** [comment]
Now it's ready for a review.

**Review by melwoodard — CHANGES_REQUESTED** [review]
Visually looking pretty good, just a few small issues:

1. The WIP message in the mobile menu overflows offscreen instead of wrapping

discover__apply_for__track_and_manage_your_veteran_benefits_with_vets_gov__vets_gov

2. [This](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1225) appears to still be an issue - space below the logo + button is still much smaller than the space above.

3. Desktop "explore" dropdown: the gold border-left correctly appears on hover now, but after the first click to another category it now disappears from the selected category



4. Desktop dropdown link colors - the links in the left column of the "explore" dropdown are still the lighter blue

discover__apply_for__track_and_manage_your_veteran_benefits_with_vets_gov__vets_gov

**Comment by tiffanybbrown-va** [comment]
@melwoodard it's ready for re-review whenever you have time.

**Review by melwoodard — APPROVED** [review]

**Review by melwoodard — COMMENTED** [review]
LGTM!

**Comment by jcmeloni-usds** [comment]
make_it_so

**Pull request merged**
