### PR TITLE
Fix exit icon css

### PR DESCRIPTION
**Pull request by bshyong**
Resolves https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2989

Merging into the content template branch so that these can go in together

### CODE REVIEW

**Review by U-DON — COMMENTED** [review]
Code change LGTM.

Although, I wonder if the intention is for the icon be next to the link itself, which would require a change in the markup rather than CSS.

> screen shot 2017-06-08 at 3 26 20 pm

**Comment by bshyong** [comment]
@melwoodard can you clarify on the above comment? I can change the markup for these cases specifically

**Comment by melwoodard** [comment]
Ah, yes ideally it should be next to the link text instead of at the end of the block. If it has to be a markup change does that mean it needs to be applied manually to every instance of an external link?

**Comment by bshyong** [comment]
Fixed—this is done through css styles so no markup changes are needed

screen shot 2017-06-08 at 5 36 39 pm

**Comment by U-DON** [comment]
Yeah, it can work with just styles too. But probably have to add `h1`, `h2`, etc. to the rule to apply to everything that might be contained within an external link. And probably should apply only to the first header in case there are multiple in that section. Ultimately it's copying the same style of an external link to a header within a nav link list (in which case, might it be helpful to make it a mixin?).

**Comment by bshyong** [comment]
Yup, good suggestions. I'm not sure how much further to optimize in case things change, but will incorporate this feedback

**Review by U-DON — APPROVED** [review]

**Pull request merged**
