### PR TITLE
remove lazy load for footer and events

### PR DESCRIPTION
**Pull request by srsuddath**
## Description
Remove lazy load of two widgets to fix issues with feature flags

### CODE REVIEW

**Comment by it-harrison** [comment]
@srsuddath I'm not sure the issues re feature flags but if you want to change [this file](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/index.js) with respect to the async IIEF on the Footer component.

**Comment by srsuddath** [comment]
thanks so much @it-harrison I am trouble shooting and working on the footer as I go. We had an issue on some of the other va sites that are re-using our footer and hoping that this fixes it!

**Review by TSimmz — APPROVED** [review]

**Review by GovNapoleon — APPROVED** [review]

**Comment by srsuddath** [comment]
@it-harrison do you think I could get a review from you when you get a chance?

**Comment by it-harrison** [comment]
@srsuddath sure, I will take a look

**Review by it-harrison — APPROVED** [review]
lgtm

**Review by adamwhitlock1 — APPROVED** [review]
some minor comment / test naming suggestions, but not merge blocking, LGTM!

**Pull request merged**
