### PR TITLE
Content/wip/form name consistency

### PR DESCRIPTION
**Pull request by peggygannon**
Updating forms names for consistency across site

### CODE REVIEW

**Comment by peggygannon** [comment]
@bethpotts Form name consistency PR is ready for your review. 

One thing I noticed when updating the form style.. I have been using "a" or "an" before a form name. For example, 
You’ll need to fill out and send *an* Application for Dependency and Indemnity Compensation, Death Pension and Accrued Benefits by a Surviving Spouse or Child (VA Form 21-534). 

I noticed in the Burials section, were were using "the" before a form name. Do we have an established style decision on this?

**Review by bethpotts — APPROVED** [review]
Managing editor/proof approval! Content is good to go after Amy give us a thumbs up.

**Comment by peggygannon** [comment]
@amybehrens Hi, Amy, this PR is ready for your review. Thank you!

**Review by ghost — APPROVED** [review]

**Comment by peggygannon** [comment]
@phiden This PR is ready for your review. Once you give it a LGTM, then it's ready to merge! 

Thank you!

**Comment by peggygannon** [comment]
@phiden @robertfairhead Hi, there! I don't see these changes on the live site yet... Do you know if this PR successfully merged or are there still issues to resolve?

**Comment by robertfairhead** [comment]
there hasn't been a production deploy since they were merged. Should deploy with afternoon's update.

**Pull request merged**
