### PR TITLE
WIP: Upgrade USWDS to 1.3.0

### PR DESCRIPTION
**Pull request by cehsu**
Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1463

Errors encountered in upgrading USWDS:

-SASS can't easily be used when installing via npm + git (documented [here](https://github.com/18F/web-design-standards/issues/2032))

There are two options indicated in the above issue on this error. One is to include node modules in the sass path, the other is to install these as dependencies rather than dev dependencies.

```
[e_uswds-upgrade-version-ceh-QH4ZB256PMXBOICES3NH7NINIMNBPJHMI7GPNRRGHBLIYKQG6ZLQ] Running shell script
+ cd /application
+ npm --no-color run lint
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.1
npm info lifecycle vets-website@1.0.0~prelint: vets-website@1.0.0
npm info lifecycle vets-website@1.0.0~lint: vets-website@1.0.0

> vets-website@1.0.0 lint /application
> npm run lint:js && npm run lint:sass

npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.1
npm info lifecycle vets-website@1.0.0~prelint:js: vets-website@1.0.0
npm info lifecycle vets-website@1.0.0~lint:js: vets-website@1.0.0

> vets-website@1.0.0 lint:js /application
> eslint --quiet --ext .js --ext .jsx .
/application/config/webpack.config.js
  7:25  error  Unable to resolve path to module 'bourbon'       import/no-unresolved
  8:22  error  Unable to resolve path to module 'bourbon-neat'  import/no-unresolved

✖ 2 problems (2 errors, 0 warnings)


npm info lifecycle vets-website@1.0.0~lint:js: Failed to exec lint:js script
npm ERR! Linux 4.4.8-20.46.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint:js"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vets-website@1.0.0 lint:js: `eslint --quiet --ext .js --ext .jsx .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vets-website@1.0.0 lint:js script 'eslint --quiet --ext .js --ext .jsx .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vets-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint --quiet --ext .js --ext .jsx .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vets-website
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vets-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /application/npm-debug.log

npm info lifecycle vets-website@1.0.0~lint: Failed to exec lint script
npm ERR! Linux 4.4.8-20.46.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--no-color" "run" "lint"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vets-website@1.0.0 lint: `npm run lint:js && npm run lint:sass`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vets-website@1.0.0 lint script 'npm run lint:js && npm run lint:sass'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vets-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint:js && npm run lint:sass
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vets-website
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vets-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /application/npm-debug.log
script returned exit code 1
```

- Adding these as peer dependencies resolves the first error but then another occurs: 
```
[e_uswds-upgrade-version-ceh-QH4ZB256PMXBOICES3NH7NINIMNBPJHMI7GPNRRGHBLIYKQG6ZLQ] Running shell script
+ cd /application
+ npm --no-color run build -- --buildtype=development
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.1
npm info lifecycle vets-website@1.0.0~prebuild: vets-website@1.0.0

> vets-website@1.0.0 prebuild /application
> node script/prebuild.js

npm info lifecycle vets-website@1.0.0~build: vets-website@1.0.0

> vets-website@1.0.0 build /application
> node script/build.js "--buildtype=development"

(node:47) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

/application/script/build.js:655
  if (err) throw err;
           ^
Hash: 9d9f0f547b5356322b92
Version: webpack 2.4.1
Time: 120795ms
                       Asset       Size  Chunks                    Chunk Names
       user-profile.entry.js    1.47 MB      21  [emitted]  [big]  user-profile
           edu-5490.entry.js     575 kB       0  [emitted]  [big]  edu-5490
          edu-1990e.entry.js     449 kB       2  [emitted]  [big]  edu-1990e
           edu-5495.entry.js     439 kB       3  [emitted]  [big]  edu-5495
          edu-1990n.entry.js     429 kB       4  [emitted]  [big]  edu-1990n
           edu-1995.entry.js     431 kB       5  [emitted]  [big]  edu-1995
    claims-uploader.entry.js     665 kB       6  [emitted]  [big]  claims-uploader
       edu-benefits.entry.js    4.56 MB       7  [emitted]  [big]  edu-benefits
           pensions.entry.js    4.03 MB       8  [emitted]  [big]  pensions
                hca.entry.js    3.84 MB       9  [emitted]  [big]  hca
            burials.entry.js    3.76 MB      10  [emitted]  [big]  burials
           pre-need.entry.js    3.73 MB      11  [emitted]  [big]  pre-need
         facilities.entry.js    4.32 MB      12  [emitted]  [big]  facilities
          messaging.entry.js    3.21 MB      13  [emitted]  [big]  messaging
                 rx.entry.js     2.3 MB      14  [emitted]  [big]  rx
disability-benefits.entry.js    2.43 MB      15  [emitted]  [big]  disability-benefits
                 gi.entry.js    2.69 MB      16  [emitted]  [big]  gi
            letters.entry.js     1.9 MB      17  [emitted]  [big]  letters
     health-records.entry.js    1.99 MB      18  [emitted]  [big]  health-records
post-911-gib-status.entry.js    1.69 MB      19  [emitted]  [big]  post-911-gib-status
        health-beta.entry.js    1.43 MB      20  [emitted]  [big]  health-beta
           edu-1990.entry.js     562 kB       1  [emitted]  [big]  edu-1990
           no-react.entry.js    1.33 MB      22  [emitted]  [big]  no-react
               auth.entry.js     857 kB      23  [emitted]  [big]  auth
              style.entry.js    1.44 kB      24  [emitted]         style
                   vendor.js    3.52 MB      25  [emitted]  [big]  vendor
                 burials.css    37.7 kB      10  [emitted]         burials
     disability-benefits.css    23.8 kB      15  [emitted]         disability-benefits
            edu-benefits.css    40.5 kB       7  [emitted]         edu-benefits
              facilities.css    32.7 kB      12  [emitted]         facilities
                      gi.css    16.1 kB      16  [emitted]         gi
                     hca.css    37.9 kB       9  [emitted]         hca
          health-records.css    14.9 kB      18  [emitted]         health-records
               messaging.css    42.6 kB      13  [emitted]         messaging
                      rx.css    16.9 kB      14  [emitted]         rx
                no-react.css    17.4 kB      22  [emitted]         no-react
            user-profile.css    5.13 kB      21  [emitted]         user-profile
                    auth.css  349 bytes      23  [emitted]         auth
                 letters.css    33.1 kB      17  [emitted]         letters
                pensions.css    38.2 kB       8  [emitted]         pensions
     post-911-gib-status.css    2.77 kB      19  [emitted]         post-911-gib-status
             health-beta.css    20.6 kB      20  [emitted]         health-beta
                pre-need.css      38 kB      11  [emitted]         pre-need
chunk    {0} edu-5490.entry.js (edu-5490) 167 kB {7} [rendered]
chunk    {1} edu-1990.entry.js (edu-1990) 166 kB {7} [rendered]
chunk    {2} edu-1990e.entry.js (edu-1990e) 130 kB {7} [rendered]
chunk    {3} edu-5495.entry.js (edu-5495) 128 kB {7} [rendered]
chunk    {4} edu-1990n.entry.js (edu-1990n) 126 kB {7} [rendered]
chunk    {5} edu-1995.entry.js (edu-1995) 127 kB {7} [rendered]
chunk    {6} claims-uploader.entry.js (claims-uploader) 258 kB {15} [rendered]
chunk    {7} edu-benefits.entry.js, edu-benefits.css (edu-benefits) 1.5 MB {25} [initial] [rendered]
chunk    {8} pensions.entry.js, pensions.css (pensions) 1.28 MB {25} [initial] [rendered]
chunk    {9} hca.entry.js, hca.css (hca) 1.21 MB {25} [initial] [rendered]
chunk   {10} burials.entry.js, burials.css (burials) 1.2 MB {25} [initial] [rendered]
chunk   {11} pre-need.entry.js, pre-need.css (pre-need) 1.19 MB {25} [initial] [rendered]
chunk   {12} facilities.entry.js, facilities.css (facilities) 1.49 MB {25} [initial] [rendered]
chunk   {13} messaging.entry.js, messaging.css (messaging) 1.04 MB {25} [initial] [rendered]
chunk   {14} rx.entry.js, rx.css (rx) 771 kB {25} [initial] [rendered]
chunk   {15} disability-benefits.entry.js, disability-benefits.css (disability-benefits) 800 kB {25} [initial] [rendered]
chunk   {16} gi.entry.js, gi.css (gi) 891 kB {25} [initial] [rendered]
chunk   {17} letters.entry.js, letters.css (letters) 623 kB {25} [initial] [rendered]
chunk   {18} health-records.entry.js, health-records.css (health-records) 664 kB {25} [initial] [rendered]
chunk   {19} post-911-gib-status.entry.js, post-911-gib-status.css (post-911-gib-status) 550 kB {25} [initial] [rendered]
chunk   {20} health-beta.entry.js, health-beta.css (health-beta) 466 kB {25} [initial] [rendered]
chunk   {21} user-profile.entry.js, user-profile.css (user-profile) 486 kB {25} [initial] [rendered]
chunk   {22} no-react.entry.js, no-react.css (no-react) 432 kB {25} [initial] [rendered]
chunk   {23} auth.entry.js, auth.css (auth) 250 kB {25} [initial] [rendered]
chunk   {24} style.entry.js (style) 1.14 kB {25} [initial] [rendered]
chunk   {25} vendor.js (vendor) 1.24 MB [entry] [rendered]

ERROR in ./~/css-loader!./~/resolve-url-loader!./~/sass-loader?{"includePaths":[["/application/~/bourbon/app/assets/stylesheets"],["/application/~/bourbon-neat/app/assets/stylesheets"],"~/uswds/src/stylesheets&sourceMap"],"sourceMap":true}!./src/sass/style.scss
Module build failed: 
    @media screen and ($default-feature: nth($query, 1)) {
                                                 ^
      (min-width: 64.0625em) isn't a valid CSS value.
      in /application/node_modules/uswds/src/stylesheets/lib/grid/_media.scss (line 59, column 51)
 @ ./src/sass/style.scss 4:14-175

ERROR in ./src/sass/style.scss
Module build failed: ModuleBuildError: Module build failed: 
    @media screen and ($default-feature: nth($query, 1)) {
                                                 ^
      (min-width: 64.0625em) isn't a valid CSS value.
      in /application/node_modules/uswds/src/stylesheets/lib/grid/_media.scss (line 59, column 51)
    at runLoaders (/application/node_modules/webpack/lib/NormalModule.js:192:19)
    at /application/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /application/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/application/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.onRender (/application/node_modules/sass-loader/index.js:273:13)
    at Object.<anonymous> (/application/node_modules/async/dist/async.js:2262:31)
    at apply (/application/node_modules/async/dist/async.js:20:25)
    at Object.<anonymous> (/application/node_modules/async/dist/async.js:56:12)
    at Object.callback (/application/node_modules/async/dist/async.js:944:16)
    at options.error (/application/node_modules/node-sass/lib/index.js:294:32)

ERROR in /application/node_modules/extract-text-webpack-plugin/loader.js??ref--4-0!/application/node_modules/style-loader/index.js!/application/node_modules/css-loader/index.js!/application/node_modules/resolve-url-loader/index.js!/application/node_modules/sass-loader/index.js??ref--4-4!/application/src/sass/style.scss doesn't export content
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 3.16 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 25.6 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 27.8 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 28.1 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 35.7 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 30.8 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 18.6 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 5.63 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 2.04 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 22.9 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 28.4 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 3.12 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 28.2 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 17.2 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 16.1 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 45.4 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 308 bytes [entry] [rendered]
    
    ERROR in ./~/css-loader!./~/resolve-url-loader!./~/sass-loader?{"includePaths":[["/application/~/bourbon/app/assets/stylesheets"],["/application/~/bourbon-neat/app/assets/stylesheets"],"~/uswds/src/stylesheets&sourceMap"],"sourceMap":true}!./src/sass/style.scss
    Module build failed: 
        @media screen and ($default-feature: nth($query, 1)) {
                                                     ^
          (min-width: 64.0625em) isn't a valid CSS value.
          in /application/node_modules/uswds/src/stylesheets/lib/grid/_media.scss (line 59, column 51)
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 18.2 kB [entry] [rendered]

npm info lifecycle vets-website@1.0.0~build: Failed to exec build script
npm ERR! Linux 4.4.8-20.46.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--no-color" "run" "build" "--" "--buildtype=development"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vets-website@1.0.0 build: `node script/build.js "--buildtype=development"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vets-website@1.0.0 build script 'node script/build.js "--buildtype=development"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vets-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node script/build.js "--buildtype=development"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vets-website
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vets-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /application/npm-debug.log
script returned exit code 1
```

### CODE REVIEW

**Comment by cehsu** [comment]
Error:
```
ERROR in ./~/css-loader!./~/resolve-url-loader!./~/sass-loader?{"includePaths":[["/Users/clairehsu/Projects/vets-website/~/bourbon/app/assets/stylesheets"],["/Users/clairehsu/Projects/vets-website/~/bourbon-neat/app/assets/stylesheets"],"~/uswds/src/stylesheets&sourceMap"],"sourceMap":true}!./src/sass/style.scss
Module build failed: 
    @media screen and ($default-feature: nth($query, 1)) {
                                                 ^
      (min-width: 64.0625em) isn't a valid CSS value.
      in /Users/clairehsu/Projects/vets-website/node_modules/uswds/src/stylesheets/lib/grid/_media.scss (line 60, column 51)
 @ ./src/sass/style.scss 4:14-175

ERROR in ./src/sass/style.scss
Module build failed: ModuleBuildError: Module build failed: 
    @media screen and ($default-feature: nth($query, 1)) {
                                                 ^
      (min-width: 64.0625em) isn't a valid CSS value.
      in /Users/clairehsu/Projects/vets-website/node_modules/uswds/src/stylesheets/lib/grid/_media.scss (line 60, column 51)
    at runLoaders (/Users/clairehsu/Projects/vets-website/node_modules/webpack/lib/NormalModule.js:192:19)
    at /Users/clairehsu/Projects/vets-website/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/clairehsu/Projects/vets-website/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/clairehsu/Projects/vets-website/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.onRender [as callback] (/Users/clairehsu/Projects/vets-website/node_modules/sass-loader/index.js:273:13)
    at Object.<anonymous> (/Users/clairehsu/Projects/vets-website/node_modules/async/dist/async.js:2262:31)
    at apply (/Users/clairehsu/Projects/vets-website/node_modules/async/dist/async.js:20:25)
    at Object.<anonymous> (/Users/clairehsu/Projects/vets-website/node_modules/async/dist/async.js:56:12)
    at Object.callback (/Users/clairehsu/Projects/vets-website/node_modules/async/dist/async.js:944:16)
    at options.error (/Users/clairehsu/Projects/vets-website/node_modules/node-sass/lib/index.js:294:32)

ERROR in /Users/clairehsu/Projects/vets-website/node_modules/extract-text-webpack-plugin/loader.js??ref--4-0!/Users/clairehsu/Projects/vets-website/node_modules/style-loader/index.js!/Users/clairehsu/Projects/vets-website/node_modules/css-loader/index.js!/Users/clairehsu/Projects/vets-website/node_modules/resolve-url-loader/index.js!/Users/clairehsu/Projects/vets-website/node_modules/sass-loader/index.js??ref--4-4!/Users/clairehsu/Projects/vets-website/src/sass/style.scss doesn't export content
```
Searching the project and the node_modules only yields two files that contain the query's value:
node_modules/foundation-sites/css/foundation.css
node_modules/foundation-sites/css/foundation.min.css
Plan: explore whether replacement steps resolve the error.

**Comment by ncksllvn** [comment]
I think while we're doing the style overhaul, the issue [Migrate from Foundation to USWDS](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/549) would be a good one to take on at the same time. Or maybe a new issue combining both.

Based on my findings today, these frameworks are pretty tangled up both in the markup and the sass. What I'm finding to be a big problem is that USWDS uses the following responsive breakpoints: 

``` scss
$small-screen:  481px !default;
$medium-screen: 600px !default;
$large-screen:  1201px !default;
```

While Foundation uses these breakpoints: 

``` sass
$breakpoints: (
  small: 0px,
  medium: 640px,
  large: 1024px,
  xlarge: 1200px,
  xxlarge: 1440px,
);
```

Then finally we have our own breakpoints file (sass/base/_b-breakpoints.scss) where we define another:

``` scss
$medium-large-screen: 768px;
```

The `768px` value seems more traditional, but my preference is to migrate fully to USWDS and try to avoid defining any of our breakpoints going forward so that we can leverage that framework as much possible. The viewpoint conflicts are on display in this [issue](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4600#issuecomment-332944340). I'll probably make a temp fix to close that issue sooner rather than later.

Are you comfortable with working on this from the `uswds-upgrade-version-ceh` branch or should we start a new one off master?

**Comment by cehsu** [comment]
Thanks @ncksllvn, a new branch sounds like the right idea.

**Comment by jbalboni** [comment]
@cehsu Should we close this?

**Comment by ncksllvn** [comment]
Good idea @jbalboni !

**Pull request closed without merging**
