### PR TITLE
Content wip discharge crosslinks

### PR DESCRIPTION
**Pull request by DanielleSoCompany**

### CODE REVIEW

**Comment by ncksllvn** [comment]
User Profile page - 

image

**Review by ncksllvn — APPROVED** [review]
LGTM

**Comment by peggygannon** [comment]
@bethpotts Link that was showing up as external on HC has been fixed. I kept getting a spinner when I tried to check the relative link to discharge page, however.

**Comment by DanielleSoCompany** [comment]
@bshyong this is one of the PRs to merge

**Pull request merged**
