### PR TITLE
Add classes in/out for animating the drawer

### PR DESCRIPTION
**Pull request by ncksllvn**
On the static site on mobile (screenshot), the sidebar currently just appears and disappears without any effect. This PR adds a slide-in and slide-out effect from the right side.

Connects to department-of-veterans-affairs/vets.gov-team/issues/3191.

screen shot 2017-09-14 at 4 11 54 pm

### CODE REVIEW

**Review by U-DON — APPROVED** [review]
LGTM. There is a CSS-only solution if you're interested.

Instead of using `display`, use `visibility`. Also, if you don't want to keep track of the `$sidebar-width`, you can also use `transform: translateX(100%)` on `.va-sidebarnav > div` and `transform: translateX(0)` on `.va-sidebarnav--opened > div`.

Also have to keep `visibility: visible` on `.va-sidebarnav > div` for the close animation to work.

**Comment by ncksllvn** [comment]
@U-DON thanks! I'll check out that CSS-only solution. If I recall correctly, doesn't `visibility` still cause the element to take up space, therefore stopping the use form clicking other elements on the page? I tried that briefly. Good idea with the `transform` property!

**Comment by ncksllvn** [comment]
@U-DON Wow, I stand corrected with the `visibility` property! These were awesome suggestions. I had no idea the visibility property worked like that. Thanks man!

**Review by cehsu — APPROVED** [review]

**Comment by ncksllvn** [comment]
Thanks @cehsu!

**Pull request merged**
