### PR TITLE
54099 - Update details link text (Accessibility)

### PR DESCRIPTION
**Pull request by vbahinwillit**
## Summary
This PR modifies the appointment detail link aria text that is read out when VoiceOver is on.

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#54099

## Testing done
VoiceOver

## Screenshots
Uploading Screen Recording 2023-03-07 at 2.02.52 PM.mov…

## What areas of the site does it impact?
VAOS

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature
- [ ]  [Accessibility foundational testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by simiadebowale — APPROVED** [review]
LGTM

**Review by jenniemc — CHANGES_REQUESTED** [review]
When VO announce the details link for pending appointments, it is missing the announcement "request for...".  Also, there's no need to announce date and time based on the AC for pending appts. 

- [ ]  Requests details links are announced as Details for [canceled] request for a [type of care] [modality|community care] appointment

**Comment by simiadebowale** [comment]
> When VO announce the details link for pending appointments, it is missing the announcement "request for...". Also, there's no need to announce date and time based on the AC for pending appts.
> 
> * [ ]   Requests details links are announced as Details for [canceled] request for a [type of care] [modality|community care] appointment

good catch Jenny

**Comment by vbahinwillit** [comment]
> When VO announce the details link for pending appointments, it is missing the announcement "request for...". Also, there's no need to announce date and time based on the AC for pending appts.
> 
> * [ ]   Requests details links are announced as Details for [canceled] request for a [type of care] [modality|community care] appointment

Thanks Jenny. Just submitted changes and new video for your review.

**Review by jenniemc — CHANGES_REQUESTED** [review]
It's announcing correctly for pending appointments. But when announcing canceled booked appointments, it reads it as "canceled request for xxx". See image for VO announcement.
Screenshot 2023-03-07 at 6 50 46 PM

**Comment by vbahinwillit** [comment]
> 

VO images appears to match the acceptance criteria: "Details for [canceled] request for a [type of care] [modality|community care] appointment".

**Review by jenniemc — APPROVED** [review]
LGTM!

**Pull request merged**
