### PR TITLE
WIP/Content/meta tag descriptions

### PR DESCRIPTION
**Pull request by peggygannon**
Adding meta tag descriptions to the frontmatter YML for top 10 most-visited pages. 

Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4629

### CODE REVIEW

**Comment by peggygannon** [comment]
@bethpotts Here is the PR for adding meta tag descriptions for the most-visited pages for your review. 

The list of approved meta tags are in https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4629

**Comment by peggygannon** [comment]
@phiden @robertfairhead Hi! Here is the PR for adding meta tag descriptions for our top 10 most-visited pages. Beth is OOO today and Monday, so would you mind giving this PR a review before it's merged?
I added "description" meta tag line to each file's YML frontmatter. 

Thank you!

**Review by robertfairhead — APPROVED** [review]
LGTM. Checked the meta tags on heroku. Showed up properly for me.

screen shot 2017-09-08 at 10 45 10 am

**Comment by peggygannon** [comment]
thanks, @robertfairhead 

@phiden Any changes on your end? If not, then I think this is ready to merge.

**Comment by phiden** [comment]
If it's good with @robertfairhead it's good by me -- merging

**Pull request merged**
