### PR TITLE
Pension 82745 Datadog RUM monitoring

### PR DESCRIPTION
**Pull request by wayne-weibel**
## Summary

add datadog RUM monitoring to Pension application

## Related issue(s)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/82745
https://github.com/department-of-veterans-affairs/va.gov-team/issues/82710
https://github.com/department-of-veterans-affairs/vets-api/pull/16748

## Testing done

local testing to check monitoring is not invoked

## What areas of the site does it impact?

Pension

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Comment by TaiWilkin** [comment]
Some questions:
- In this [referenced file](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/appeals/shared/utils/useBrowserMonitoring.js), they start browser logging as well as RUM. Do we do that elsewhere already? If not, should we be initializing that here?
- Is the plan to keep the feature flag off on production until we've thoroughly reviewed elements for PII/PHI leaks?
- You say in the description that you tested locally to ensure monitoring wasn't invoked - what does it look like locally when monitoring is invoked? How can you tell? I'm not sure how to test this. 

Also, just as a reminder, I think you'll need to make sure the backend PR with the feature flag addition has reached production before you  merge this to main.

**Comment by wayne-weibel** [comment]
@TaiWilkin 
> Some questions:
> 
> * In this [referenced file](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/appeals/shared/utils/useBrowserMonitoring.js), they start browser logging as well as RUM. Do we do that elsewhere already? If not, should we be initializing that here?

Interesting.  The doc I was looking at should only RUM.  I will add that though

> * Is the plan to keep the feature flag off on production until we've thoroughly reviewed elements for PII/PHI leaks?

Yes exactly, we want to be EXTRA certain nothing is being logged that should not.

> * You say in the description that you tested locally to ensure monitoring wasn't invoked - what does it look like locally when monitoring is invoked? How can you tell? I'm not sure how to test this.

I placed some `console.log` in the file and a debugger breakpoint to be sure the conditional was not entered.

**Review by mjknight50 — DISMISSED** [review]
GTG

**Review by TaiWilkin — DISMISSED** [review]
Looks great!

**Review by harshilmoradia — DISMISSED** [review]

**Review by scottsdevelopment — CHANGES_REQUESTED** [review]

**Review by TaiWilkin — APPROVED** [review]
Nice refactor 👍

**Review by scottsdevelopment — APPROVED** [review]

**Review by harshilmoradia — APPROVED** [review]

**Pull request merged**
