### PR TITLE
VA-11358: Discharge wizard: transition to design system radios

### LINKED ISSUE #11358: React RadioButtons should transition to design system component by 12/21
## Description
https://dsva.slack.com/archives/C03R5SBELQM/p1666879267774979
> The VA Design System Team has deprecated the RadioButtons React component. We encourage all teams using the RadioButtons React component to upgrade to the [va-radio web component](https://design.va.gov/storybook/?path=/docs/components-va-radio--default). We have changed the ESLint warning to an ESLint error and have removed the documentation about the React RadioButtons component from Storybook.

The audit of PW-owned code was performed in the process of refining this ticket, so ACs center on swapping out the radio buttons on the one app we own that is impacted by the deprecation: 
* ~~Education how to apply page 10916~~ _VFEP team took care of it_
* 10 instances, all in the `/discharge-wizard` app. vsa-frontend is the only codeowner listed for this file
  * https://www.va.gov/discharge-upgrade-instructions/

## Additional info
FYI this wizard has a flipper related: `discharge_wizard_features`, "Iteration of new features for discharge wizard". I don't have context for what it's doing / how long it's been there, but it's worth keeping an eye on as you make this change, to confirm that we get expected behavior relative to flipper.

**Complexity to keep in mind and de-risk when possible**
The "guidance" screen has many conditionally-displayed components that combine in many ways depending on Veteran inputs. We've created a [Mural board](https://app.mural.co/invitation/mural/vagov6717/1670355600942?sender=u252e7152800e3981889d1910&key=789998a8-498d-419f-be6d-aef09cbf2e23) to help identify the flows and guidance permutations.

## Testing plan
The flow chart in the Mural above should be used to identify manual use cases that touch all known configurations at least once:
- All ~10 of the questions display correctly
- All possible responses to the ~10 questions are summarized accurately in the "Review your answers" panel at bottom
- Each results variation identified in the Mural can be triggered by some combination of responses
  - Alerts/Warnings
  - Form possibilities
  - Extra Info-alert text triggered by "having paperwork"

## Acceptance Criteria
- [x] Audit FE for RadioButtons React component
  - [x] vets-api
  - [x] content-build
- [x] Document which files include them _**and which are in our products**_
- [x] Write implementation ticket to migrate them to design system component, and send link to Wes/Jill for prioritization
- [x] RadioButtons component is not present in the discharge app
- [x] UX around the content itself (questions, order, advice yielded by app) does not change; links are consistent, sequence of questions is consistent
- [x] UX and Accessibility improvements made
  - [x] Eliminate extra padding to left of questions, so that questions are aligned with H1 at top of page (desktop and mobile)
  - [x] Questions that use non-radio inputs (eg Year of discharge) are changed from H4s to regular, non-bold text (consistent with radio-input questions)
  - [x] Heading "Review your answers" is an H2 (changed from H4)
- [x] Design system component is used instead
- [ ] All IDs for radiobuttons are unique. ([context](https://dsva.slack.com/archives/C52CL1PKQ/p1671661367323609?thread_ts=1671649127.116519&cid=C52CL1PKQ))

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by maxx1128**
## Summary

The Discharge Wizard page uses the old React component for radio answers. This changes them over to the design system's radio components while retaining the same functionality and updating a few styles for consistency and accessibility.

## Related issue(s)

- Closes department-of-veterans-affairs/va.gov-cms#11358

## Testing done

Clicked through the discharge wizard questions to confirm the same functionality and alignment carried over. Also confirmed that the labels no longer contain headers, for both radio and non-radio questions.

## Screenshots
_Note: This field is mandatory for component work and UI changes (non-component work should NOT have screenshots)._

| | Before | After |
| --- | --- | --- |
| Mobile | Screen Shot 2022-12-14 at 12 59 46 PMScreen Shot 2022-12-14 at 12 59 58 PM | Screen Shot 2022-12-14 at 12 56 28 PMScreen Shot 2022-12-14 at 12 56 34 PM |
| Desktop | Screen Shot 2022-12-14 at 1 00 25 PMScreen Shot 2022-12-14 at 1 00 17 PM | Screen Shot 2022-12-14 at 12 56 04 PMScreen Shot 2022-12-14 at 12 56 12 PM |

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [x]  No error nor warning in the console.
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x]  I added a screenshot of the developed feature

## Requested Feedback

Check for consistency, no broken functionality, and no remaining old radio components.

### CODE REVIEW

**Review by apisandipas — APPROVED** [review]
Looks good to me.

**Comment by jilladams** [comment]
@apisandipas since Max is out, could you clarify if your review was primarily code review, or if you also stepped through the front-end for functional testing to compare to the Mural etc?

**Review by it-harrison — APPROVED** [review]

**Comment by maxx1128** [comment]
Once the tests are passing then I think this should be good to merge.

**Comment by jilladams** [comment]
We want to be sure this is fully QA verified prior to merging. @wesrowe is owning that testing. Please wait to merge until he has signed off. Thanks!

**Review by wesrowe — APPROVED** [review]
I thoroughly funtionally tested the review instance alongside the app in Prod. Documented with screenshots. Details are all in the VA-owned Mural linked from the ticket this PR implements.

**Comment by wesrowe** [comment]
I just reviewed and approved the PR

**Comment by jilladams** [comment]
@maxx1128 some test failures on E2E / code climate tests, FYI. Doesn't look like they're blocking merge, but not sure why.

**Review by jilladams — DISMISSED** [review]
code is passing in `name` and `value` properties to the <va-radio-option> web component. That web component then assigns an `id` value by concatenating those two values. This combination is not unique from one question to the next, so a11y is flagging the repeated `id` values.

https://dsva.slack.com/archives/C52CL1PKQ/p1671661367323609?thread_ts=1671649127.116519&cid=C52CL1PKQ

**Comment by maxx1128** [comment]
The `name` and `value` issue has been resolved and the test suites are all passing, so this pull request is good to merge.

**Pull request merged**
