### PR TITLE
Removes live requests to keepalive endpoint in E2E testing

### LINKED ISSUE #41626: Investigate E2E EAuth issues
## Description
Look into the eAuth issue that is causing E2E Cypress tests to break.

Background information
- https://dsva.slack.com/archives/C02V265VCGH/p1652882476538359

## Tasks
- [x] Investigate what is causing E2E Cypress tests to break
- [x] Implement fixes to ensure .skip is not used in E2E Cypress tests

## Acceptance Criteria
- [x] In CI/CD, E2E Cypress tests pass as normal

### PR DESCRIPTION
**Pull request by asg5704**
## Description
This PR updates the `keepAlive` method in E2E testing to use a mock call to the `/keepalive` endpoint rather than using the real call to eAuth.  Additionally, it reverts some of the `.skip` in some Cypress tests to any dealing with Debts.

## Original issue(s)
Closes department-of-veterans-affairs/va.gov-team#41626

## Testing done
Local Cypress, unit tests

## Screenshots
n/a

## Acceptance criteria
- [x] Cypress testing for Debts consistently passes

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by jhonny218 — APPROVED** [review]
LGTM

**Review by ddzz — APPROVED** [review]

**Review by lzapson — APPROVED** [review]
LGTM

**Comment by AGarcia-Clarity** [comment]
@mdewey Can you review this PR please

**Review by Mottie — APPROVED** [review]

**Comment by AGarcia-Clarity** [comment]
@department-of-veterans-affairs/vsa-debt-frontend @department-of-veterans-affairs/vsa-ebenefits-frontend Can I get a PR please 🙏  thank you.

**Review by jerekshoe — APPROVED** [review]

**Review by mdewey — APPROVED** [review]
LGTM

**Pull request merged**
