### PR TITLE
update pdf url per SME: survivors-pension

### PR DESCRIPTION
**Pull request by bethpotts**
Request forwarded by Josh Q.

### CODE REVIEW

**Review by phiden — APPROVED** [review]
@bethpotts is this ready to merge once the tests pass?

**Comment by bethpotts** [comment]
@phiden No, please wait until Peggy has looked at it. Should I wait next time to add you as a reviewer until Peggy's pass is complete? Thanks for asking!

**Comment by phiden** [comment]
@bethpotts ok -- ping when it's ready and I'll merge!

**Review by peggygannon — APPROVED** [review]
LGTM!

**Pull request merged**
