### PR TITLE
Add service location support to health_care_local_health_service transformer

### PR DESCRIPTION
**Pull request by mpelzsherman**
https://github.com/department-of-veterans-affairs/va.gov-team/issues/14606

## Acceptance criteria
- [x] CMS export-based build matches graphql-based build for pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive

## Definition of done
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Comment by mpelzsherman** [comment]
As of today, this command produces 584 diffs:

opendiff build/localhost/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/index.html build/graphql-localhost/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/index.html

Some of these are inconsequential, e.g. the order of <meta> tags.

**Comment by mpelzsherman** [comment]
Omitting the debug data, adding more fields and using graphql ordering brings the diffs down to 138.

**Comment by mpelzsherman** [comment]
Fixed address field - down to 114 diffs. Still todo: phone numbers (make a common schema) and appointments.

**Comment by mpelzsherman** [comment]
Added phone numbers. Down to 70!

**Comment by mpelzsherman** [comment]
Down to only 35 diffs!

The remaining diffs appear to be due to actual differences in the source data. Need to investigate!

**Review by jhonny218 — APPROVED** [review]
LGTM

I run the `diff` and I saw no discrepancies

**Review by brangi — APPROVED** [review]
LGTM

**Review by ncksllvn — APPROVED** [review]

**Pull request merged**
