### PR TITLE
Pull latest script config from brand-consolidation branch

### PR DESCRIPTION
**Pull request by ncksllvn**
## Description
I'm doing some more work with the build script today and am getting things back in sync between master/brand-consolidation's script directories.

Related to the goals outline here - department-of-veterans-affairs/vets.gov-team/issues/12840

## Testing done
Tested the build

## Screenshots
N/A

## Acceptance criteria
- [x] Script in sync /brand-consolidation script (Did not include the `collections/brand-consolidation.json` file because that only matters to brand-consolidation and just clutters the diff at this point)

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by wyattwalter — APPROVED** [review]
Whoops, forgot to do that. Thanks!

**Comment by wyattwalter** [comment]
Looks like Jenkinsfile needs an update too.

**Comment by ncksllvn** [comment]
@wyattwalter  updated the Jenkinsfile - want to take another look and make sure I did it ok?

**Comment by wyattwalter** [comment]
Oh yeah, these are way out-of-sync. I'd say let's just remove the vagov-dev reference from it entirely for now and we can make a more concerted effort to get them in-sync as a separate thing. The PR was failing because devpreview was still set as a build type in master, which no longer existed as part of your build script updates.

**Pull request merged**
