### PR TITLE
Add entryName for all apps missing it

### PR DESCRIPTION
**Pull request by acrollet**
## Summary

- adds `entryName` parameter to all applications that don't have it

This should improve reporting in Datadog and eliminate `unknown` values for `source_app`. ([cf](https://vagov.ddog-gov.com/metric/explorer?fromUser=false&start=1717605042950&end=1717608642950&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGniqyABuiBpOGPIQAHQaCJ4aUM2NEE7aGJkA1n0mZm3AcCLVyHCDGgC08to4UBQABOl4WXAN8vLIeCKDIjhgIjzd9Zn4IggAFACUIDwAulSu7niYoeEfql8YGKleLPN4gNpYNA5UDyDBQhAIHJJHAwJyZb4aCCZRJoUQ7OSKco4XFQHF4pz0JjKE7uOHPfgQeyYLBOAlIgBGGG0llePD44PkuIQAGEpMIYCgRF80DwgA))
 
## Related issue(s)

- https://github.com/department-of-veterans-affairs/generator-vets-website/pull/410

### CODE REVIEW

**Review by CBonade — APPROVED** [review]

**Review by asg5704 — APPROVED** [review]
Good catch on the `login` app's entryName @acrollet. Thank you

**Comment by acrollet** [comment]
NB: the E2E stability test review failures seem to be caused by the number of apps being updated in this PR. Frontend CoP has approved over-riding branch protections to merge this: https://dsva.slack.com/archives/CBU0KDSB1/p1717616459169499

**Review by Mottie — APPROVED** [review]

**Review by brianseek — APPROVED** [review]
🎉

**Review by amponce — APPROVED** [review]
👍

**Review by szarrougtw — APPROVED** [review]

**Review by adamwhitlock1 — APPROVED** [review]
looks good for authd-exp team

**Review by gabezurita — APPROVED** [review]
ARF changes LGTM!

**Review by jsimonVA — APPROVED** [review]

**Pull request merged**
