### PR TITLE
Content/wip/add var to healthcare

### PR DESCRIPTION
**Pull request by DanielleSoCompany**
Suggested placements for VAR links.

### CODE REVIEW

**Comment by DanielleSoCompany** [comment]
@amybehrens @bethpotts Please see my suggested placement for the VAR link on the "Your Care Team" and "Where You'll Get Care" pages. I had 2 thoughts on where we could place the link on these pages: Either at the bottom of the first main chunk of content or as its own separate question. I've added both so you can review both options and let me know which you prefer. Thanks!

**Comment by bethpotts** [comment]
@amybehrens @DanielleSoCompany Thanks for the two options to review. I like it broken out as a separate question. It stands out more with its own subhead.

**Comment by amybehrens** [comment]
@DanielleSoCompany and @bethpotts I it as its own question too (which surprised me!). 

I'm wary of calling it an app because it's a web app (not something people need to download from the app store). I also think it's important to mention they need a DS Logon to use it so we don't set up an even more frustrating experience. 

Can we go with something like:
You can also use your DS Logon to request and schedule non-urgent visits online. (link the whole sentence)

**Comment by DanielleSoCompany** [comment]
@amybehrens yes, i like that! @bethpotts I'm updating now and will ping you when this is ready for proofing.

**Comment by DanielleSoCompany** [comment]
okay, @bethpotts this is ready for proofing! @amybehrens just an fyi that i added this additional text to define DS Logon: "Your DS Logon is the same logon used for eBenefits." In recent identity/logon research, we found that users didn't recognize what "DS Logon" was even though they had it for eBenefits. Thanks!

**Review by bethpotts — APPROVED** [review]
@DanielleSoCompany @amybehrens I've proofed this and it's ready to run past leadership.

**Comment by DanielleSoCompany** [comment]
Hi @robertfairhead. The VA Appointments Request (VAR) team has requested that we set up tracking for user clicks on the links to VAR from Vets.gov. Per the PR, there will be links to VAR from /health-care/about-va-health-care/your-care-team and from /health-care/about-va-health-care/where-you-get-care. Could you set this up? Thank you! And just let @amybehrens or I know if you have any questions about this.

**Comment by robertfairhead** [comment]
We track all clicks on links to non `vets.gov` domains so we would pick up any clicks on those links. Outbound click tracking like that isn't perfect so we may miss some because the internet isn't always perfect, but we can definitely give them a sense of it from the reporting.

**Comment by DanielleSoCompany** [comment]
okay, great - thank you @robertfairhead!

**Comment by DanielleSoCompany** [comment]
Update: This relates to Issue #4247 and is with Jeff Grandon for review.

**Comment by DanielleSoCompany** [comment]
@amybehrens Jeff has approved this PR so we're ready to publish!

**Review by ghost — APPROVED** [review]

**Comment by DanielleSoCompany** [comment]
@bethpotts can you take one more copy editing look at this before I ask Sophia to merge? Thank you!

**Comment by bethpotts** [comment]
@DanielleSoCompany I avoided repetition of "use" in one sentence by substituting "access"--take a look at what I did to make sure you agree. Content looks great! Approved.

**Comment by bethpotts** [comment]
@phiden Would you please review this PR and merge if all looks good? Thanks! We are not waiting on anyone else to review.

**Review by phiden — APPROVED** [review]

**Pull request merged**
