### PR TITLE
[WIP] 1995 ch 1 update

### PR DESCRIPTION
**Pull request by cvalarida**
References #4578

There are a few things listed in the comments of the above issue that haven't been done yet:
1. Adding OMB number and respondent burden at the bottom of the page
    1. Waiting for feedback from @goldenmeanie
2. @mollyblake's comment, items [4] and [5]
    1. [4] When I get feedback on what to do, I'll make it happen
    2. [5] Goes in #4543

Also, in talking with @jbalboni and @goldenmeanie, we decided to change the file number validation message to just `File number must be 8 digits` and not mention the C, but not reject it.

### CODE REVIEW

**Comment by jbalboni** [comment]
@cvalarida These changes look good to me. Looks like we're waiting on a couple answers from @goldenmeanie to make the remaining changes?

**Comment by goldenmeanie** [comment]
I think it makes sense to do the OMB thing as a separate ticket

**Comment by goldenmeanie** [comment]
[4] Which benefit do you want to transfer?

**Review by jbalboni — APPROVED** [review]
LGTM

**Pull request merged**
