### PR TITLE
[CST] Adding decision letter docType to GA metadata

### PR DESCRIPTION
**Pull request by jerekshoe**
## Summary
Adding the decision letter docType to the metadata associated with the custom GA event so that we can keep track of how many letters of each docType have been downloaded. We are about to add a new docType and the stakeholders involved want us to be able to provide metrics on how many of their letter type are being downloaded

## What areas of the site does it impact?
Claim Status Tool
*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by pmclaren19 — CHANGES_REQUESTED** [review]
@jerekshoe can you add any tests or screenshots showing that this is working as expected? I think these would be helpful to add for reviewers!

**Comment by jerekshoe** [comment]
> @jerekshoe can you add any tests or screenshots showing that this is working as expected? I think these would be helpful to add for reviewers!

There aren't any UI changes being made, this is just related to google analytics. As far as tests there isn't really much to test here, the recordEvent function is already tested elsewhere

**Comment by pmclaren19** [comment]
> > @jerekshoe can you add any tests or screenshots showing that this is working as expected? I think these would be helpful to add for reviewers!
> 
> There aren't any UI changes being made, this is just related to google analytics. As far as tests there isn't really much to test here, the recordEvent function is already tested elsewhere

Ah and you cant see/show the google analytics changes locally either?

**Comment by jerekshoe** [comment]
> > > @jerekshoe can you add any tests or screenshots showing that this is working as expected? I think these would be helpful to add for reviewers!
> > 
> > 
> > There aren't any UI changes being made, this is just related to google analytics. As far as tests there isn't really much to test here, the recordEvent function is already tested elsewhere
> 
> Ah and you cant see/show the google analytics changes locally either?

Yeah, unfortunately google analytics is disabled when running the site locally...

**Review by pmclaren19 — APPROVED** [review]
Approved! Wish there was a good way to test locally but changes look good and should resolve the issue.

**Pull request merged**
