### PR TITLE
Issue #3859 - Change address blocks from <dl> to <p> elements

### PR DESCRIPTION
**Pull request by phiden**

### CODE REVIEW

**Comment by ayaleloehr** [comment]
@phiden is this still being worked on?

**Comment by phiden** [comment]
@ayaleloehr the changes to `<p>` etc are complete -- not sure why Jenkins isn't building, and I can't seem to look at the details unless I'm on an intranet?

**Comment by ayaleloehr** [comment]
[Here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Work%20Practices/Engineering/Internal%20Tools.md) is the documentation for accessing the SOCKS proxy, which is what gets you access to Jenkins. Or feel free to ping someone who already has access if preferred, but having that set up might be useful!

**Comment by raquelromano-gov** [comment]
hey @phiden so sorry for the delay (OOO + discovery sprint + travel = unread gh notifications).
Is this demo'd in that jenkins review instance or did you build a new one? LMK if you have one running--no worries if not

**Comment by phiden** [comment]
no worries @raquelromano-gov. This is a different ticket than the one I was building a Jenkins instance for -- especially now that the tests are passing! The heroku instance here was enough for checking address blocks.

**Review by raquelromano-gov — APPROVED** [review]

**Pull request merged**
