### PR TITLE
Add Adobe update language to link to form

### PR DESCRIPTION
**Pull request by melwoodard**
Closes https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2732

### CODE REVIEW

**Comment by melwoodard** [comment]
Adobe update copy added on a separate line after the form link:

https://vetsgov-pr-5526.herokuapp.com/burials-and-memorials/burial-planning/

**Comment by J-Quag** [comment]
I kinda feel like its a huge block of text, but I dont really know if there is a way around that.

**Review by ghost — CHANGES_REQUESTED** [review]
Can you put it on the same line as the content before so it looks like:

Fill out the Application for Pre-Need Determination of Eligibility for Burial in a VA National Cemetery (VA Form 40-10007). Download VA Form 40-10007. (To save your information in this form, make sure you have the latest free version of Adobe Reader.)

*this isn't a great solution, but it's a good band aid until we can retire the PDF

**Review by ghost — APPROVED** [review]

**Comment by melwoodard** [comment]
I moved the text up to the same line, and added some bolding at the beginning of the two main steps to break up the content a bit. If this can be approved and merged in the next hour-ish, we can get it into today's production deployment.

@EmilyTav does this look good to you?

image

**Comment by amybehrens** [comment]
@EmilyTav if we haven't heard from you by 11am tomorrow, I'm going to assume @melwoodard is ok to get this deployed. Thanks everyone for the quick turnaround on this!

**Comment by melwoodard** [comment]
Hearing nothing, I'll merge this in the next hour. Last call...

**Comment by amybehrens** [comment]
@melwoodward please do!

**Pull request merged**
