### PR TITLE
Pension 76776 Dependent information deprecated field

### PR DESCRIPTION
**Pull request by wayne-weibel**
## Summary

update widgets to use uswds v3; chapter 4 dependent child info - place of birth, and no SSN checkbox

## Related issue(s)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/76776

## Testing done

view dependent child information page
enter information
data should save

## Screenshots

image

## What areas of the site does it impact?

Pension chapter 4 dependent child info

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Comment by Andrew565** [comment]
PR has failing required tests, opting not to review at this time. - Tier 2/FE COP

**Review by ToddWebDev — CHANGES_REQUESTED** [review]
These updates look good. While manually testing this I noticed that the form can geti into an invalid error state when the form should be valid. If you check the 'Doesn't have a Social Security number' checkbox and then uncheck it and enter a SSN, it will not let you continue, even though the form is valid. I think it's due to the 'VaCheckboxField'  schema including `enum: [true]`.
Screenshot 2024-03-01 at 11 23 22 AM

**Comment by wayne-weibel** [comment]
> These updates look good. While manually testing this I noticed that the form can geti into an invalid error state when the form should be valid. If you check the 'Doesn't have a Social Security number' checkbox and then uncheck it and enter a SSN, it will not let you continue, even though the form is valid. I think it's due to the 'VaCheckboxField' schema including `enum: [true]`

figures, that is what i get for following the example, and the 1 sequence i did not test lol

**Review by ToddWebDev — APPROVED** [review]
That was a tough one to catch but I'm glad we did instead of a Veteran.

**Pull request merged**
