### PR TITLE
VIC announcement subscription copy updates

### PR DESCRIPTION
**Pull request by jkassemi**

### CODE REVIEW

**Comment by jkassemi** [comment]
screen shot 2017-12-04 at 12 18 51 pm

screen shot 2017-12-04 at 12 19 01 pm

**Comment by bethpotts** [comment]
@jkassemi Two more tiny tweaks, then we should be good to go. It helps so much to see the text in the screenshots, as it will appear on the site. Thanks! So could you edit two sentences?:
1) We're sorry, but your application didn't go through. 
2) ...please enter your email address below.

**Comment by bethpotts** [comment]
After convo with James, here's where we landed:

We’re sorry. Our system is having trouble handling the many requests for Veteran ID cards, and can’t accept your application right now. We’re working to fix the problem as fast as we can.

**Comment by bethpotts** [comment]
@jkassemi I just noticed that the link to our privacy policy is embedded. Usually we link the whole line of text. If it's not too late, could you link the whole shebang?: [See our privacy policy.]

**Comment by jkassemi** [comment]
@bethpotts thanks! Just made the update. We're waiting on an update to how we pull the rate limit configuration to get this out.

**Review by bethpotts — APPROVED** [review]
Looks great!

**Pull request merged**
