### PR TITLE
Add "Download health records" into navigation

### PR DESCRIPTION
**Pull request by ncksllvn**
This adds the "Download health records" link into the following locations:

- Navigation -> Explore benefits -> Health care
- Health Care index page major links (3rd from bottom)
- Health Care sidebar (second from bottom, pages other than index page)

This also shortens the title of "Refill your prescriptions" to "Refill prescriptions" and "Send a message to your provider" to "Secure message health care team" in the sidebar.

Resolves department-of-veterans-affairs/vets.gov-team/issues/3529

### CODE REVIEW

**Comment by ncksllvn** [comment]
Questions:

- Is the order correct for the navigation?
- Sometimes the link for health records is called "Download health records" while other times it's called "Get your VA health records." Is this correct?

**Comment by bethpotts** [comment]
@ncksllvn In regards to your question: Sometimes the link for health records is called "Download health records" while other times it's called "Get your VA health records." Is this correct?

Please make it "Get your VA health records" in each case rather than "Download health records"

**Comment by ncksllvn** [comment]
@bethpotts PTAK when you get the chance

**Review by bethpotts — APPROVED** [review]
Content and placement of new links looks good. Approved!

**Comment by ncksllvn** [comment]
Thanks @bethpotts!

**Pull request merged**
