### PR TITLE
Content/wip/update accredited rep page

### PR DESCRIPTION
**Pull request by kellyskennedy**

### CODE REVIEW

**Comment by kellyskennedy** [comment]
This is ready for you to take a look, @bethpotts

**Comment by kellyskennedy** [comment]
Hi @peggygannon -- I've completed my changes to all the pages, and this is ready for you. Thanks!

**Review by peggygannon — COMMENTED** [review]
@kellyskennedy PR copy edit/review is complete. Please let me know if you have any questions about my changes. 
--I updated some of the link language to "Get Help Filing Your Claim" so it matches the actual page name
--also on the disability-benefits/apply/help/ page, I noticed some of the content changed under "What does it cost to use a VSO..." I want to check if we need to run those updates by a stakeholder or SME?

**Comment by kellyskennedy** [comment]
@peggygannon Can you review this, please? Thanks!

**Comment by kellyskennedy** [comment]
@peggygannon The SMEs probably should take a look at the new information about costs

**Comment by kellyskennedy** [comment]
I think this is waiting for your review, @bethpotts

**Comment by kellyskennedy** [comment]
This is ready for a copy edit/review, @peggygannon

**Comment by bethpotts** [comment]
@peggygannon To clarify, you don't have to copyedit the whole PR again, just this recent link edit. The last commit Kelly made. 

@kellyskennedy for awareness.

**Review by peggygannon — APPROVED** [review]
@kellyskennedy OK, link update looks good.

**Comment by kellyskennedy** [comment]
Thanks, @peggygannon On to you, @bethpotts

**Comment by kellyskennedy** [comment]
Okay, @bethpotts We should be straight. Closing the issue.

**Comment by bethpotts** [comment]
@phiden This is ready for your review and merge. Thanks!

**Review by bethpotts — APPROVED** [review]
Looks great, thanks Kelly!

**Review by phiden — APPROVED** [review]

**Pull request merged**
