### PR TITLE
Add `depends` usage to cookbook

### PR DESCRIPTION
**Pull request by cvalarida**
Looking at `src/js/common/utils/helpers.js` -> `isActivePage()`, I think I got those options for `depends` right, but correct me if I'm wrong.

Also, should we think about passing in the flattened data so we don't have to access `data.pageName.data.fieldName`?

### CODE REVIEW

**Review by jbalboni — APPROVED** [review]
LGTM. Once my flatten PR is merged, we won't need the page name and `data` in the depends objects.

**Comment by cvalarida** [comment]
@jbalboni Awesome. Sounds like a plan! Ping me when that's done and I'll fix it up here too.

**Comment by cvalarida** [comment]
Does that look right, @jbalboni?

**Comment by jbalboni** [comment]
@cvalarida Looks good to me!

**Pull request merged**
