### PR TITLE
add initial unit tests

### PR DESCRIPTION
**Pull request by mchelen-gov**
## Description

https://github.com/department-of-veterans-affairs/va.gov-team/issues/9213

## Acceptance criteria
- [x] unit tests pass

## Definition of done
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Comment by mchelen-gov** [comment]
Unit test results can be seen in CircleCI: https://app.circleci.com/pipelines/github/department-of-veterans-affairs/vets-website/6037/workflows/d13ecfb2-256e-4e69-a249-0ec764ba3aac/jobs/36961/parallel-runs/0/steps/0-106 (search for `coronavirus-screener`)

**Comment by stephenBarrs** [comment]
@mchelen-gov do we need unit tests for formState?

**Review by jhonny218 — APPROVED** [review]
LGTM

**Comment by mchelen-gov** [comment]
@stephenBarrs 
> @mchelen-gov do we need unit tests for formState?
We need unit tests for a looot of things, I just wanted to get it started. Also didn't want to go too far until we iron out any imminent refactors.

**Review by stephenBarrs — APPROVED** [review]

**Pull request merged**
