### PR TITLE
content updates

### PR DESCRIPTION
**Pull request by DanielleSoCompany**

### CODE REVIEW

**Comment by melwoodard** [comment]
@ncksllvn any chance you could add a wrapper around all of the text so it's all a consistent width? It looks like only the intro-text is subject to our standard max-width for content, everything else is too wide.

The cutoff should be about here:

try_our_new_beta_tools__vets_gov

**Comment by ncksllvn** [comment]
@melwoodard no problem! Will do that shortly

**Review by melwoodard — APPROVED** [review]
Looks great! Thanks @DanielleSoCompany @ncksllvn!

**Comment by ncksllvn** [comment]
@DanielleSoCompany I believe this branch was created off of a very old version of master branch so I recommend doing a `git pull`. I believe that's why the navigation and enroll button weren't loading.

**Pull request merged**
