### PR TITLE
Homeless alert box

### PR DESCRIPTION
**Pull request by kellyskennedy**

### CODE REVIEW

**Comment by kellyskennedy** [comment]
@peggygannon -- @phiden is fixing the  short-box weirdness, but these are ready for you to take a look. Thanks!

**Review by peggygannon — APPROVED** [review]
@kellyskennedy Looks good to me. thanks.

**Comment by kellyskennedy** [comment]
Okay, @bethpotts -- it's ready for you

**Review by phiden — APPROVED** [review]

**Comment by bethpotts** [comment]
@phiden Please merge after reviewing the code. Thanks!

**Pull request merged**
