### PR TITLE
Enable no-unused-vars ESLint rule

### PR DESCRIPTION
**Pull request by bkjohnson**
## Description

This PR re-enables `no-unused-vars` which was disabled in https://github.com/department-of-veterans-affairs/vets-website/pull/12760

We are tracking these disabled ESLint rules in https://github.com/department-of-veterans-affairs/va.gov-team/issues/11691

There are a lot of changed files, but I've grouped the apps by commit (in a _very loose_ alphabetical order by app). If you've viewed the changes in the commit for your app and they look good, then you can approve.

The following apps have 2 commits due to further changes after merging in master:

- debt-letters
- facility-locator
- vaos
- vre

## Testing done

Only linting.

## Screenshots

Turning the rule on before any of the fixes were made:

image

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by zurbergram — APPROVED** [review]

**Review by jbalboni — APPROVED** [review]

**Review by micahchiang — APPROVED** [review]

**Review by jhonny218 — APPROVED** [review]

**Review by Mottie — APPROVED** [review]

**Review by erikphansen — APPROVED** [review]
Geez, I can't believe how many unused vars made their way in since disabling that rule.

**Review by rianfowler — APPROVED** [review]

**Review by mpelzsherman — APPROVED** [review]

**Comment by mpelzsherman** [comment]
Thanks for doing this painstaking work, @bkjohnson !!

**Review by bradl3yC — APPROVED** [review]

**Review by ncksllvn — APPROVED** [review]

**Comment by bkjohnson** [comment]
@department-of-veterans-affairs/va-cto-health-products please review this as soon as you get the chance.

**Review by mchelen-gov — APPROVED** [review]
`src/applications/coronavirus-screener/` and `src/applications/covid-research-volunteer/` look good

**Pull request merged**
