### PR TITLE
Replace Cypress-TestRail custom-reporter

### PR DESCRIPTION
**Pull request by tlei123**
## Description
Replace current Cypress-TestRail custom-reporter cy-tr-reporter package with new [@tlei123/vagov-cy-tr-reporter](https://github.com/tlei123/vagov-cy-tr-reporter), which is much leaner and customized to fit our in-house Cypress/TestRail configurations and work-processes.

## Original issue
department-of-veterans-affairs/va.gov-team#48686

## Testing done
- Locally tested new reporter with existing integrated Cypress specs and [successfully posted results to TestRail](https://dsvavsp.testrail.io/index.php?/runs/overview/4). [see also screenshot below.]
- No code changes were made to any vets-website application.

## Screenshot
image

## Acceptance criteria
- Code-reviewer(s) approved changes.

## Definition of done
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by tlei123** [comment]
@pjhill [or whoever reviews this PR], feel free to test my new reporter against your local vets-website project:
- check-out my feature-branch shared-support-qa/vagov-cy-tr-reporter
- usage as exactly the same as before
- also, I have a [testing help-page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/shared-support/QA/vagov-cy-tr-reporter-draft-pr-local-testing.md) including a list of suggested Cypress specs to run.

**Comment by tlei123** [comment]
**Extra app-file included under Files-changed tab**: Looks like GitHub Actions caught some linting items in **src/applications/edu-benefits/0994/containers/IntroductionPage.jsx**.  I did NOT make any changes to that file.

**Review by it-harrison — APPROVED** [review]
looks good but I do have a question: should `cy-tr-reporter` be removed from `package.json` and should `"@tlei123/vagov-cy-tr-reporter": "^0.0.7"` be listed in `devDependencies`?

**Comment by pjhill** [comment]
> looks good but I do have a question: should `cy-tr-reporter` be removed from `package.json` and should `"@tlei123/vagov-cy-tr-reporter": "^0.0.7"` be listed in `devDependencies`?

Agreed, I would think that `cy-tr-reporter` could be removed and Tze's custom version added to `devDependencies`.

**Review by pjhill — APPROVED** [review]

**Comment by tlei123** [comment]
@it-harrison @pjhill , just pushed a installations-fix.  cy-tr-reporter removed, and @tlei123/vagov-cy-tr-reporter installed as devDependency.

Thx for catching that, Ian!  :)

**Pull request merged**
