### PR TITLE
Bah colmery 104

### PR DESCRIPTION
**Pull request by shawkey-daniel**
## Description
CT: 104 - Update School Profile Search Options for Yellow Ribbon Update#17903
As a Compare Tool user, I need the School Profile to display accurate search options for currently available benefits, so that I can make educated decisions on the use of my benefits based on accurate information.

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/17903

## Screenshots
image
image

## Acceptance criteria
- [x] If the answer to "What is your military status?" is "Active Duty" AND the answer to "Cumulative Post-9/11 active duty service" is "36+ months: 100% (includes BASIC)" then do not display the following content/questions:
    Will you be a Yellow Ribbon recipient?
    Degree Level (yellow ribbon answer is yes)
    Division or school (yellow ribbon answer is yes)
    Yellow Ribbon amount from school per year (yellow ribbon answer is yes)
    Alert displaying "Maximum amount per student:" and "Number of students" content.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by devin-mccurdy — APPROVED** [review]
LGTM!

**Review by sonntag-adam — APPROVED** [review]

**Comment by shawkey-daniel** [comment]
@department-of-veterans-affairs/backend-review-group Could I get a code review on this at your earliest convenience. Thank you!" as a comment to the pull request.

**Comment by shawkey-daniel** [comment]
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!" as a comment to the pull request.

**Comment by jbalboni** [comment]
@shawkey-daniel Can you remove the extra files that are in this PR? Looks like we just want the calculator file and unit test changes.

**Comment by shawkey-daniel** [comment]
@jbalboni removed unnecessary files. Build appears to be good.

**Review by jbalboni — APPROVED** [review]

**Pull request merged**
