### PR TITLE
update vet tec search results styling

### PR DESCRIPTION
**Pull request by hughes-dustin**
## Description
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19360

## Screenshots
Screen Shot 2019-07-25 at 11 33 35 AM

## Acceptance criteria
- [ ]  On the VET TEC Search Results Page the cards will have the following layout:
     - Row 1 - warnings (if any)
     - Row 2 - Provider + Preferred Indicator (Row 1 if no warnings)
     - Row 3 - City + You may be eligible for... (Row 2 if no warnings)
- [ ]  The styling of the provider name and city/state is as follows:
     - The provider name is styled as an h2 header for the card.
     - The City, State text is displayed as a "locality".
- [ ]  If there are no warnings, there will not be a blank row on the card.
- [ ]  If there is no preferred provider indicator the "You may be eligible for" section is not moved out of the City/State row.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by sonntag-adam — APPROVED** [review]

**Comment by hughes-dustin** [comment]
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!

**Review by cvalarida — COMMENTED** [review]
Looks fine as far as I can tell, but after poking around the GIBCT in staging right now, I don't know reproduce your results to compare old vs new.

How can I test what it looks like on staging right now to compare against this?

**Comment by hughes-dustin** [comment]
> Looks fine as far as I can tell, but after poking around the GIBCT in staging right now, I don't know reproduce your results to compare old vs new.
> 
> How can I test what it looks like on staging right now to compare against this?

In staging, we should have vet tec providers who are preferred providers .

If you want the "school closing" warning message to appear in staging, you will need to add a vet tec provider facility code entry into the school_closure.csv. Then upload that csv, generate preview and push to production. The facility code must match an existing vet-tec provider facility code in the WEAMS.csv. 

I can go ahead and do all this for you if you need me too.

**Comment by cvalarida** [comment]
:thinking: So part of my problem may be that I'm looking at the wrong tool. Is this GIBCT? My sidebar looks different. 
image

At any rate, I was trying to reproduce that warning bar (with any labels) and the preferred provider indicator to see how they looked before. I'd also like to test out how they change for mobile to make sure it all works like expected.

**Comment by hughes-dustin** [comment]
> 🤔 So part of my problem may be that I'm looking at the wrong tool. Is this GIBCT? My sidebar looks different.
> image
> 
> At any rate, I was trying to reproduce that warning bar (with any labels) and the preferred provider indicator to see how they looked before. I'd also like to test out how they change for mobile to make sure it all works like expected.

When you get to the landing page, you will want to select "VET TEC training providers only" under "Type of Institution". Search off of that, and you should get Vet Tec search results.

**Comment by hughes-dustin** [comment]
> 🤔 So part of my problem may be that I'm looking at the wrong tool. Is this GIBCT? My sidebar looks different.
> image
> 
> At any rate, I was trying to reproduce that warning bar (with any labels) and the preferred provider indicator to see how they looked before. I'd also like to test out how they change for mobile to make sure it all works like expected.

**Comment by cvalarida** [comment]
Ahhh, okay, that did it for me. Thank you!
image

**Review by cvalarida — APPROVED** [review]
Thanks for hopping on a call with me to run through the mobile styles. Looks great! :shipit:

**Pull request merged**
