### PR TITLE
Add VS Code workspace extension recommendations

### PR DESCRIPTION
**Pull request by mchelen-gov**
## Description
VS Code allows projects to recommend extensions: https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions

Note: the `.vscode` directory is still gitignored, only `extensions.json` is tracked because it is optional for user.

Update: split off shared `settings.json` issue to https://github.com/department-of-veterans-affairs/vets-website/issues/12845

## Testing done
Workspace recommendations appear in `@recommended` search

## Screenshots
Screenshot from 2020-05-15 09-56-54-cropped

## Acceptance criteria
- [x] Workspace recommendations appear in `@recommended` search

## Definition of done
- [ ] Documentation has been updated, if applicable
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by erikphansen** [comment]
@mchelen-gov I confirmed that this does work for me as well if I enter `@recommended` in the search bar.

**Comment by mchelen-gov** [comment]
@erikphansen fwiw if you open the `vets-website` dir with "File -> Open Folder -> vets-website" there is a little popup that will alert you to the suggested extensions. The user can then install those, or tell VS Code to suppress this suggestion.

**Comment by mchelen-gov** [comment]
@rianfowler i think you mentioned `eslint` and `prettier` extensions conflict, can you give any more detail on this or an example where this happens?

**Comment by rianfowler** [comment]
>@rianfowler i think you mentioned eslint and prettier extensions conflict, can you give any more detail on this or an example where this happens?

I don't- i vaguely remember someone having an issue and figuring they were redundant. I'm fine with recommending both if you think it's valuable.

**Comment by mchelen-gov** [comment]
> > @rianfowler i think you mentioned eslint and prettier extensions conflict, can you give any more detail on this or an example where this happens?
> 
> I don't- i vaguely remember someone having an issue and figuring they were redundant. I'm fine with recommending both if you think it's valuable.

@rianfowler i know they can be configured not to conflict, i can check if they are redundant though since prettier might be reading eslint config anyway

**Review by rianfowler — APPROVED** [review]

**Comment by mchelen-gov** [comment]
note: shared `settings.json` issue split off since its more complicated https://github.com/department-of-veterans-affairs/vets-website/issues/12845

**Comment by mchelen-gov** [comment]
confirmed that ESLint extension is reading Prettier config, so Prettier extension is unneeded :+1:

**Pull request merged**
