### PR TITLE
WIP: 5490 conditional benefit disclaimers

### PR DESCRIPTION
**Pull request by goldenmeanie**
Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1883

This PR is a WIP. 

Alex will work with Josh and Peggy to understand what needs to be added to these four benefit selection pages:

Spouse - DEA
Spouse - FRY
Child - DEA
Child - FRY

Layout changes and removing redundant or impossible instructions. I realize this will require more stakeholder conversation. But it's here for @raquelromano-gov reference.

### CODE REVIEW

**Comment by raquelromano-gov** [comment]
Thanks for making these changes--LGTM on the code. Adding screenshots here for reference--looks like we'll need to add a some whitespace before the final warning (after the effective date).

Other than that, sounds like the plan is to merge this and get stakeholders' eyeballs on it for any additional iterations, right?

If applicant is spouse of sponsor:

image

If applicant is child of sponsor:

image

**Comment by raquelromano-gov** [comment]
LMK whether you want to fix the whitespace issue in this PR or prefer to merge and fix later.

**Comment by goldenmeanie** [comment]
Yes to whitespace!

**Comment by J-Quag** [comment]
as a note, according to tom, there is no effective date for a spouse as they do not have to give up DIC.

**Comment by leannammiller** [comment]
@bethpotts @peggygannon - please work with @goldenmeanie to rewrite this content.

**Comment by leannammiller** [comment]
working thru this with stakeholders, @goldenmeanie will schedule meeting with Shay tomorrow AM.

**Comment by leannammiller** [comment]
@raquelromano-gov there is more work to be done from the content/product side before this is ready for you.

**Comment by goldenmeanie** [comment]
When spouse is chosen:
- hide benefitsRelinquishedInfo
- hide benefitsRelinquishedDate
- hide benefitsRelinquishedWarning

Four states of conditional warning (nested inside selection)
1. Spouse & DEA  
    > I understand that if I am also eligible for Fry Scholarship benefits then I am electing to receive DEA benefits in lieu of any Fry Scholarship benefits for which I am currently eligible including Fry Scholarship benefits based on the death of the qualifying individual entered for this application, as well as, Fry Scholarship benefits based on the death of any other individuals not identified on this application.
2. Spouse & Fry  
    > I understand that I am electing to receive Fry Scholarship benefits in lieu of any DEA benefits for which I am currently eligible including DEA benefits based on the death of the qualifying individual entered for this application, based on the death of any other individuals not identified on this application, based on a spouse who has a total disability permanent in nature resulting from a service-connected disability, or based on any other criteria as listed in 38 U.S.C. § 3501(a)(1).
3. Child & DEA  
    > I understand that if I am also eligible for Fry Scholarship benefits based on the death of the qualifying individual entered for this application then I am electing to receive DEA benefits in lieu of any Fry Scholarship benefits based on that death. Furthermore, I understand that even after this election I will continue to retain any current eligibility to Fry Scholarship benefits if the eligibility is based on the death of the qualifying individual entered for this application.
4. Child & Fry  
    > I understand that I am electing to receive Fry Scholarship benefits in lieu of any DEA benefits for which I am currently eligible based on the death of the qualifying individual entered for this application. Furthermore, I understand that even after this election I will continue to retain any current eligibility to DEA benefits if the eligibility is based on the death of the qualifying individual entered for this application, based on a parent who has a total disability permanent in nature resulting from a service-connected disability, or based on any other criteria as listed in 38 U.S.C. § 3501(a)(1).

**Comment by peggygannon** [comment]
Suggested edits: 
When spouse is chosen:
•	hide benefitsRelinquishedInfo
•	hide benefitsRelinquishedDate
•	hide benefitsRelinquishedWarning
Four states of conditional warning (nested inside selection)
1.	Spouse & DEA
I understand that I am choosing to receive DEA benefits instead of any Fry Scholarship benefits for which I am currently eligible. This includes Fry Scholarship benefits based on the death of the qualifying individual on this application, as well as, Fry Scholarship benefits based on the death of any other individuals not listed on this application.
2.	Spouse & Fry
I understand that I am choosing to receive Fry Scholarship benefits instead of any DEA benefits for which I am currently eligible. This includes DEA benefits based on the death of the qualifying individual on this application, based on the death of any other individuals not listed on this application, based on a spouse who has a permanent and total service-connected disability, or based on any other criteria as listed in 38 U.S.C. § 3501(a)(1).
3.	Child & DEA
I understand that I am choosing to receive DEA benefits instead of any Fry Scholarship benefits based on the death of the qualifying individual on this application. I understand that even after this choice I will continue to be eligible for Fry Scholarship benefits if the eligibility is based on the death of the qualifying individual on this application.
4.	Child & Fry
I understand that I am choosing to receive Fry Scholarship benefits instead of DEA benefits for which I am currently eligible based on the death of the qualifying individual on this application. I understand that even after this choice I will continue to be eligible for DEA benefits if the eligibility is based on the death of the qualifying individual on this application, based on a parent who has a permanent and total service-connected disability, or based on any other criteria as listed in 38 U.S.C. § 3501(a)(1).

**Comment by peggygannon** [comment]
@goldenmeanie @leannammiller @J-Quag  See my suggested edits above, including changing "electing" to "choosing".

**Comment by goldenmeanie** [comment]
I like choosing :)

Thanks for working these over @peggygannon !

**Comment by J-Quag** [comment]
I like the suggested edits @peggygannon

**Comment by goldenmeanie** [comment]
1. Child Path:  
    - Vertical space between benefit selection section and DIC section should be increased.
    - Add a subhead "Dependency and Indemnity Compensation" at the top of the DIC section.
2. Spouse Path:  
    - Bullet the conditions (example below)
    - In the Fry Scholarship option, link to the statute in the warning copy

DEA warning:
> I understand that I am choosing to receive DEA benefits instead of any Fry Scholarship benefits for which I am currently eligible. This includes Fry Scholarship benefits based on:
> - The death of the qualifying individual on this application
> - Fry Scholarship benefits based on the death of **any other individuals not listed on this application**.

Fry warning:
> I understand that I am choosing to receive Fry Scholarship benefits instead of any DEA benefits for which I am currently eligible. This includes DEA benefits based on:
> - The death of the qualifying individual on this application
> - The death of any other individuals not listed on this application
> - A spouse who has a permanent and total service-connected disability
> - Any other criteria as listed in [38 U.S.C. § 3501(a)(1)](#).

**Comment by raquelromano-gov** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/5203 was branched off this and merged

**Pull request closed without merging**
