### PR TITLE
533 remove proof of veteran status feature toggle

### PR DESCRIPTION
**Pull request by AdamKing0126**
## Summary

I'm Adam King, I work on the VA-IIR team, and we are the current owners of this component.  This PR is to remove a feature toggle check on `profile_show_proof_of_veteran_status`.

Previously this exact PR was deployed to staging, and @stevelong00 discovered that the Veteran Service card did not display at all.  It's my theory that this was a mistake, the code does indeed work as expected.  See, "Testing Done"

## Related issue(s)

Original Issue: [533](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/533)
New Issue: [683](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/683)

## Testing done

After getting the mock api running correctly and being able to test the code locally, I'm now of the belief that Steve's initial PR to remove the flag (which was later reverted) did in fact work.  I paired with @nicksayre  on this yesterday, and he concurs.

Initially I thought that the removal of the feature toggle check was acting as a sort of "speed brake" and allowing the request to get the veteran's service history
- I implemented a React hook to trigger a page re-render when that api request completed
- I mocked out that endpoint and allowed the call to take a long time
- The entire page's loading was withheld until that request completed
This disproves my hypothesis: all the network requests must complete before the browser attempts to load the page

Taking a different tact, I loaded the staging site up and logged in as Steve's test user, and modified the running JavaScript code
- placed a debugger before the check for the feature toggle
- edited the running code to eliminate the check
- resumed execution of the code
- the Veteran's Status Card displayed as expected

I cannot explain how Steve's previous experience demonstrated something different.  It's possible he was looking at the wrong browser window, I'm not sure.  The problem is that there's a short window where the code on Staging is testable before it is deployed into production.  This introduces a significant amount of urgency.  What I'm going to do is get approval from Nick and the codeowners and then I will wait until after the production deploy happens.  That'll give us the longest time in which to confirm that everything's working as expected in staging.

## What areas of the site does it impact?

https://staging.va.gov/profile/military-information

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Review by nicksayre — DISMISSED** [review]
I agree that this solution appears correct despite the previous reversion. LGTM!

**Comment by adamwhitlock1** [comment]
Curious what did the hook like like that you made to mess with the loading logic?

**Comment by AdamKing0126** [comment]
> Curious what did the hook like like that you made to mess with the loading logic?

It was something like this (warning, syntax errors)
```
const MilitaryInformation = ({ militaryInformation, veteranStatus }) => {
  let showVeteranStatusCard, setShowVeteranStatusCard = useState(true); 
  useEffect(() => {
    document.title = `Military Information | Veterans Affairs`;
    setShowVeteranStatusCard(Boolean(militaryInformation?.serviceHistory?.serviceHistory));
  }, []);
```

And then lower down in the code, 
```
      {showVeteranSrtatusCard && (
        <div className="vads-u-margin-y--4">
          <ProofOfVeteranStatus />
        </div>
      )}
```

**Comment by adamwhitlock1** [comment]
This LGTM as far as the changes go.

There are some issues in the e2e tests in that they actually don't test anything and pass without asserting anything on the rendered UI. Wasn't anything you did, I just happened to notice them when I ran your branch locally, but they should definitely be fixed up. 

I can create an issue for that though and fix those.

**Review by adamwhitlock1 — DISMISSED** [review]

**Comment by adamwhitlock1** [comment]
@AdamKing0126 I actually whipped up a hotfix branch real quick here:
https://github.com/department-of-veterans-affairs/vets-website/tree/Profile/aw/hotfix/e2e-tests-for-vet-status

If you want to merge my branch into your branch then we could just roll with that, or I can open a PR on my own.

**Comment by AdamKing0126** [comment]
> @AdamKing0126 I actually whipped up a hotfix branch real quick here: https://github.com/department-of-veterans-affairs/vets-website/tree/Profile/aw/hotfix/e2e-tests-for-vet-status
> 
> If you want to merge my branch into your branch then we could just roll with that, or I can open a PR on my own.

Cool, should be good now.  Mind re-approving?  Something I did triggered a dismissal

**Review by nicksayre — APPROVED** [review]

**Review by adamwhitlock1 — APPROVED** [review]

**Review by harshilmoradia — APPROVED** [review]

**Pull request merged**
