### PR TITLE
Updated callback param names in updateSchema

### PR DESCRIPTION
**Pull request by cvalarida**
Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1519

Matches the naming convention

### CODE REVIEW

**Review by raquelromano-gov — APPROVED** [review]

**Comment by cvalarida** [comment]
@raquelromano-gov I just noticed the naming convention was weird in `updateSchemaFromUiSchema`, so I changed it in there as well. Could you give it another quick look?

**Comment by raquelromano-gov** [comment]
Sorry, just saw that you had updated this! Reviewing now.

**Comment by raquelromano-gov** [comment]
Thanks for fixing this--these names were making my head spin when I was writing that function to update the ui based on data (which I later threw away) to keep straight the various data objects we're passing around between `reducers/index.js`, `helpers.js` and the form config files:

It sounds like we have 3 things:
1.  `pageData`: structured object with all data from a specific page, not the whole form
2.  `formData`: flattened (?) object with all data from all pages
3.  `form`: structured object with all data from all pages

Can we rename (2) and (3)?  E.g., `formData` -> `flattenedData` and `form` -> `formData` (open to suggestions).

**Comment by cvalarida** [comment]
`flattenedData` sounds good, but `formData` is misleading, methinks. If I saw that, I would think it would be structured either like `flattenedData` (the current `formData`), or just the data separated by page name like
```js
{
  pageName: {
    field1: 'value',
    field2: 'value'
  }
}
```
when it's really set up with `schema` and `uiSchema` as well as `data`.
```js
{
  pageName: {
    schema: { ... },
    uiSchema: { ... },
    data: {
      field1: 'value',
      field2: 'value'
    }
  }
}
```

**Comment by raquelromano-gov** [comment]
Oh right...we use `formConfig` in a bunch of places. Can we use that here instead of plain old `form`?

**Comment by cvalarida** [comment]
Ah, good ole `formConfig`. Sounds great! I'll get right on it. :+1:

**Comment by cvalarida** [comment]
Actually...I think that might be misleading as well because the config doesn't have `data`. Hmm.

**Comment by raquelromano-gov** [comment]
Tragic.
OK, well this is certainly an improvement so go for it.

**Review by raquelromano-gov — APPROVED** [review]

**Comment by cvalarida** [comment]
If we come up with something better, we can definitely revisit this.

**Pull request merged**
