### PR TITLE
Remove fake data from History List

### PR DESCRIPTION
**Pull request by alexose**
This PR does three things:
- Move the `loadData()` action into Main.jsx.  This way, it will load regardless if you're looking at Active or History.
- Replaces the fake data from faker with actual data from the API.
- Removes faker from package.json

### CODE REVIEW

**Comment by alexose** [comment]
`loadData` is probably going to need more logic around which prescriptions list we want to start with on page load (also sort, pagination, etc.)  I'm going to defer this to the PR where we replace `reactable` with something else...

**Comment by U-DON** [comment]
LGTM.

**Comment by U-DON** [comment]
I think the Active view is supposed to load `/prescriptions/active` and History is supposed to load just `/prescriptions`. So the two containers will eventually each call their own `loadData` (probably will be separate functions just to make it more obvious which is which).

**Comment by U-DON** [comment]
Note that removal of faker breaks ContactCard, but I've already replaced it with data from the API in #2883.

**Comment by alexose** [comment]
Ah, I thought I'd grepped through for faker references.  Evidently I failed at that.

**Pull request merged**
