### PR TITLE
VACMS 18537 - Facility Locator a -> va-link or open in a new tab when needed

### PR DESCRIPTION
**Pull request by eselkin**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

## Summary

- Changes links in facility-locator to va-link where possible, otherwise adding (opens in a new tab) to links that open in a new tab
- Sitewide team

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18537

## Testing done

- Updated unit tests
- Manually tested pages and results for CCP/Urgent Care/Emergency/VA and non-VA/VBA/Vet Center details pages and direct VA page links

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

<details>
<summary>Before and after: Link in alert/Operation Status (similar for NCA but cannot find one to link to)</summary>

| before | after |
| ------ | ----- |
| Screenshot 2024-08-22 at 12 19 44 PM | Screenshot 2024-08-22 at 12 19 06 PM |
</details>

<details>
<summary>Before and after: website and directions links in details page</summary>

| before | after |
| ------ | ----- |
| Screenshot 2024-08-22 at 12 21 20 PM|Screenshot 2024-08-22 at 12 20 48 PM |
</details>

<details>
<summary>Before and after: result list with link to VA page (not to a detail page)</summary>

| before | after |
| ------ | ----- |
| Screenshot 2024-08-22 at 12 23 07 PM |Screenshot 2024-08-22 at 12 22 47 PM |
</details>

<details>
<summary>Before and after: result list with link to a detail page (Doesn't visibly change, but h5 styling class was removed because it was ignored)</summary>

| before | after |
| ------ | ----- |
| Screenshot 2024-08-22 at 12 42 30 PM | Screenshot 2024-08-22 at 12 41 40 PM |
</details>

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by SnowboardTechie — DISMISSED** [review]

**Review by chriskim2311 — APPROVED** [review]
LGTM! Tested in RI and code changes look good

**Comment by eselkin** [comment]
@laflannery I added you to test the Get directions links [here](http://64257ddcdd7042f8be750f7dd4cfd299.review.vetsgov-internal/find-locations/?address=Portland%2C%20OR&bounds%5B%5D%5B%5D=-75.4059945&bounds%5B%5D%5B%5D=39.3127492&bounds%5B%5D%5B%5D=-72.6059945&bounds%5B%5D%5B%5D=42.112749199999996&context=Portland%2C%20Oregon%2C%20United%20States&facilityType=benefits&latitude=45.52068&longitude=-122.6789&page=1&radius=38&serviceType&bounds%5B%5D=-124.0789&bounds%5B%5D=44.12068&bounds%5B%5D=-121.2789&bounds%5B%5D=46.92068)
and
[here](http://64257ddcdd7042f8be750f7dd4cfd299.review.vetsgov-internal/find-locations/facility/vba_348a)

**Comment by laflannery** [comment]
@eselkin Most of this looked good but the last one in the QA list - result list with link to a detail page - Shouldn't these be updated to use the `<va-link>` component? They aren't in your screenshot nor are they in the PR. Is there a reason they wouldn't be able to?

**Review by laflannery — APPROVED** [review]
LGTM

**Pull request merged**
