### PR TITLE
CT Sandbox - Mobile compare drawer updates

### PR DESCRIPTION
**Pull request by devin-mccurdy**
## Description
Update compare drawer mobile styling

## Original issue(s)
department-of-veterans-affairs/va.gov-team#27557

## Testing done
Tested locally and QA reviewed

## Screenshots
image

image

## Acceptance criteria
- [x] The width of the compare drawer matches the width of the institution cards.
- [x] The elements in the compare drawer are stacked vertically in the following order:
  - "You can compare 2 to 3 institutions" content
  - Placeholder indicator / institution names
  - Compare button
- [x] The height of the placeholder indicator is 40h px.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by sonntag-adam — APPROVED** [review]

**Review by zacharymorel — APPROVED** [review]
Approved for Discharge Wizard change

**Comment by dmccurdybah** [comment]
I am not sure how the wrong-perenthesis (`'`) was updated on these files!

**Comment by zacharymorel** [comment]
> I am not sure how the wrong-perenthesis (`'`) was updated on these files!

I believe it's a eslint rule.

**Pull request merged**
