### PR TITLE
added basic logic

### PR DESCRIPTION
**Pull request by mdewey**
## Description
My Team had a spacing issue with the buttons on the review page. This will add a configuration to let the buttons be sized based on the `formConfig`.  

## Testing done
{none yet, but will do}
- [ ] Units tests

## Screenshots
Before 
Screen Shot 2020-10-22 at 2 36 11 PM

After
Screen Shot 2020-10-22 at 2 38 56 PM

## Acceptance criteria
- [x] The button sizes are configurable per formConfig
- [x] If missing then the default is 5. 

## Definition of done
- [ ] Documentation has been updated
- [ ] Unit tests are passing in CI

### CODE REVIEW

**Review by bkjohnson — COMMENTED** [review]
Could we achieve the same thing by having the columns in the default submit state use one of the flexbox utilities?

https://design.va.gov/utilities/flexbox

**Comment by mdewey** [comment]
@bkjohnson I think flexbox would totally help here. I will play with it today to see what it do.

**Comment by mdewey** [comment]
@bkjohnson  I switch to flexbox is worked perfectly. Thanks for the tip. What tests should I add for this since this now a CSS change?

**Comment by bkjohnson** [comment]
:thinking: I'm not sure what the best way to test this is. It seems appropriate for visual regression testing which we unfortunately don't have, so I'll do some thinking/asking and get back to you.

**Comment by bkjohnson** [comment]
Can you post screenshots of the new flexbox layout?

**Comment by mdewey** [comment]
Sure thing @bkjohnson 

Screen Shot 2020-10-29 at 3 24 28 PM

**Comment by bkjohnson** [comment]
Thank you! We will be discussing this today, so hopefully it will get out of limbo soon.

**Review by bkjohnson — APPROVED** [review]
:+1:

**Pull request merged**
