### PR TITLE
Updates per ticket 3606

### PR DESCRIPTION
**Pull request by DanielleSoCompany**

### CODE REVIEW

**Comment by DanielleSoCompany** [comment]
@bethpotts - @kellyskennedy and I just made our recommended revisions here, and we're ready for your review. Thanks!

**Review by bethpotts — APPROVED** [review]
I made two tweaks. Take a look to make sure you agree. Then request a merge!

**Comment by bethpotts** [comment]
@DanielleSoCompany This one's approved. You can request a merge.

**Comment by jkassemi** [comment]
What's the status on this? Can this PR be closed, or should these changes go into effect?

**Comment by DanielleSoCompany** [comment]
@jkassemi Looks like I must not have requested the merge somehow...since this is such an old PR, will it cause issues to merge now? If yes, the changes were very minor and I could just open a new branch and add them again. Just let me know what's best. Thanks!

**Comment by DanielleSoCompany** [comment]
Okay, great. I've closed this PR. Should I also delete the branch?

**Pull request closed without merging**
