### PR TITLE
Increase graphql pages limit from 2000 to 5000

### PR DESCRIPTION
**Pull request by mpelzsherman**
## Description
Fix for https://github.com/department-of-veterans-affairs/va.gov-team/issues/18242

## Testing done
Ran build locally, confirmed that the missing pages appear in the build.

### CODE REVIEW

**Review by swirtSJW — CHANGES_REQUESTED** [review]
Title says 5000 but only changed it to 3000

**Review by swirtSJW — APPROVED** [review]
Tests out ok as a load on the CMS

**Review by theodur — APPROVED** [review]
:shipit:

**Comment by swirtSJW** [comment]
I am not sure why e2e tests are failing.   But they failures seem to be unrelated
image

**Comment by swirtSJW** [comment]
This is blocking a time sensitive VAMC rollout.   Can we get this prioritized for merge or determine what needs to be done to get that test passing?

**Pull request merged**
