### PR TITLE
Integrate Higher Level Review form-tester spec with Cypress TestRail Reporter/Helper

### PR DESCRIPTION
**Pull request by tlei123**
## Description
Integrate Higher Level Review form-tester spec with cy-tr-reporter (custom Cypress reporter) & cypress-testrail-helper (custom utility script).

## Original issue(s)
n/a

## Testing done
- No impact on any app-functionalities.  Just a string-manipulation method in Form-Tester code to conditionally append a TestRail Case ID to the test-description string.
- Ran updated & unchanged specs, and the two already-integrated specs successfully pushed results to TestRail:
  - Updated [HLR form-tester spec results](https://dsvavsp.testrail.io/index.php?/runs/view/2595)
  - Unchanged, previously-integrated [HLR wizard spec results](https://dsvavsp.testrail.io/index.php?/runs/view/2596) [regression-testing for updated cypress-testrail config]
  - Unchanged, unintegrated [HCA form-tester spec](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/hca/tests/hca.cypress.spec.js) also ran fine [regression-testing for updated form-tester]

## Acceptance criteria
- [ ] Reviewer(s) approved changes.

## Definition of done
- [x] Documentation has been updated, if applicable
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by tlei123** [comment]
@pjhill @ddzz , YES, I cracked the Form-Tester TestRail-integration nut!  :D

To test this, just checkout this feature-branch and:

1. Start **vets-website** app.  [Stop vets-api if that's running.]
2. Start **cypress-testrail-helper** in a separate Termainl at vets-website root:
    ```node
    cd <vets-website-root>
    yarn cy:my-testrail-helper
    ```
3. When prompted for spec filename, input `hlr`.
4. Re-run the **helper** for unchanged spec `hlr-wizard`, as regression-test for updated cypress-testrail.json config.
5. Run unchanged **hca form-tester spec** the regular way [not integrated w/ TestRail], as regression-test for updated form-tester:
    ```node
    yarn cy:run --spec "**/hca/**/hca.cypress.spec.js"
    ```

For further details, see my updated [updated Helper README](https://github.com/department-of-veterans-affairs/vets-website/blob/vsa-qa/form-tester-cypress-testrail/script/cypress-testrail-helper/README.md) in this feature-branch &mdash; there's a new footnote for form-tester integration at the bottom.

Thanks much!

cc @Mottie

**Review by Mottie — APPROVED** [review]
Thanks Tze!

**Review by zacharymorel — APPROVED** [review]

**Review by oseasmoran73 — APPROVED** [review]

**Review by cohnjesse — APPROVED** [review]
LGTM

**Review by timwright12 — APPROVED** [review]

**Comment by tlei123** [comment]
Closing this PR -- need to re-integrate after recent/new UI-changes.

**Pull request closed without merging**
