### PR TITLE
Updates for employment landing page

### LINKED ISSUE #3608: DOL page

### PR DESCRIPTION
**Pull request by crwallace**
New updates to employment landing page:

screencapture-localhost-3001-employment-1478022421490

Code Review - @bshyong 
Layout Review - @staceylanger 

closes #3608

### CODE REVIEW

**Comment by maryannbrody** [comment]
@crwallace, @bshyong - a note for when this goes to prod: we will also need to remove the link to the "Veterans Employment Center" in the footer. Can we include that in the PR?

Thanks!

**Review by bshyong — APPROVED** [review]
LGTM

**Comment by bshyong** [comment]
Link removed @maryannbrody @crwallace This is ready for merge

**Comment by maryannbrody** [comment]
@bshyong @crwallace -- One small content change -- under the "Hire a Veteran" card, can we change the subhead to: 

> Post jobs and learn about hiring qualified Veterans. 

Next Steps:

- Other than that, this is *approved* by all parties, and we can push to production Nov 9 or 10 (exact date TBD as we are depending on DoL to redirect veterans.gov to vets.gov first).

**Comment by crwallace** [comment]
Content updates are done and we are ready to roll on the 9th @maryannbrody and @staceylanger.

**Pull request merged**
