### PR TITLE
Pre-need form text updates

### PR DESCRIPTION
**Pull request by jbalboni**
Also connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5905

screenshot-2017-11-15 apply online for pre-need determination of eligibility in a va national cemetary 3
-------
screenshot-2017-11-15 apply online for pre-need determination of eligibility in a va national cemetary 2
-------
screenshot-2017-11-15 apply online for pre-need determination of eligibility in a va national cemetary 1
------
screenshot-2017-11-17 apply online for pre-need determination of eligibility in a va national cemetary

### CODE REVIEW

**Review by cehsu — APPROVED** [review]
LGTM.

**Comment by peggygannon** [comment]
@jbalboni A few additional tweaks are needed: 
--Under Apply
Update copy to:
Complete this pre-need eligibility determination form.
After submitting the form, you’ll get a confirmation message. You can print this for your records.

--Under VA Review
change 30 days to 90 days, so it should read:    We usually process claims within 90 days.


--Will this form be SIP-enabled? If so, should we replace the current save message with: 
You can save this form in progress, and come back later to finish filling it out.
[Sign in to your account.]

**Review by peggygannon — CHANGES_REQUESTED** [review]
@jbalboni A few additional tweaks are needed:
--Under Apply
Update copy to:
Complete this pre-need eligibility determination form.
After submitting the form, you’ll get a confirmation message. You can print this for your records.

--Under VA Review
change 30 days to 90 days, so it should read: We usually process claims within 90 days.

--Will this form be SIP-enabled? If so, should we replace the current save message with:
You can save this form in progress, and come back later to finish filling it out.
[Sign in to your account.]

**Comment by jbalboni** [comment]
@peggygannon Updated.

I think the form will be SiP enabled, but not initially. So I think it's ok to leave it for now. When we turn it on, most of that messaging is automatically enabled.

**Review by peggygannon — APPROVED** [review]
@jbalboni LGTM!

**Pull request merged**
