### PR TITLE
Hotfix/lazyload

### LINKED ISSUE #25115: Lazyloading bug causing Webpack to break on external teamsites
## What happened?
Lazy-loading React modules has broken the SessionTimeoutModal and SignInModal for external teamsites (https://benefits.va.gov/benefits).  External teamsites are about 200+ sites that are currently negatively effected by the the code changes.

## Specs:
- Device: all
- Browser: all

## Steps to Reproduce
- URL: https://benefits.va.gov/benefits
Open the Developer Tools to view the console errors

## Desired behavior
There should be no Webpack errors in the console and the SignInModal & SessionTimeoutModal work as prior to lazy-loading.

## Acceptance Criteria
- [x] No Webpack errors linked to lazy-loading exist in external teamsites.
- [x] SignInModal & SessionTimeoutModal function as before prior to lazy-loading.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

### PR DESCRIPTION
**Pull request by asg5704**
## Description
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/25115

- Removes `React.lazy` on Identity related modules
- Updates Main.jsx spec files

## Testing done
Visual, unit tests

## Screenshots
n/a

## Acceptance criteria
- [x] `React.lazy` is removed from Identity related modules
- [x] Unit tests are updated to reflect non-lazyloading

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by timwright12 — APPROVED** [review]
Thanks!

**Comment by joeniquette** [comment]
@timwright12 Can you provide supporting documents for the issues you raised for this removal? As well as a list of sites that were having an issue? I believe we are better served by at least trying to work with the impacted teams rather than just rolling back improvements to the site.

**Review by joeniquette — CHANGES_REQUESTED** [review]
Need supporting docs first.

**Comment by timwright12** [comment]
@joeniquette Sure what are you looking for? Can we do that after merge, this is currently affecting the teamsites

http://benefits.va.gov/
https://www.cem.va.gov/
https://www.oprm.va.gov/
http://www.diversity.va.gov/
http://www.va.gov/visn5

**Comment by joeniquette** [comment]
> @joeniquette Sure what are you looking for? Can we do that after merge, this is currently affecting the teamsites and we need to get it through before the 2pm ET deploy
> 
> http://benefits.va.gov/
> https://www.cem.va.gov/
> https://www.oprm.va.gov/
> http://www.diversity.va.gov/
> http://www.va.gov/visn5
> 
> This is the current documentation we have https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/architecture/teamsite
> 
> Unfortunately we don't have any flexibility with teamsite engineering as it isn't handled within our ecosystem

I hear you Tim, I would like to at least be able to communicate with the team that this is impacting to get them to commit to updating their code. Is there an exact link from your list that I can see how lazy loading is causing an issue?

**Comment by timwright12** [comment]
@joeniquette you can see it at any of the URLs listed. My go to is https://benefits.va.gov/benefits/ -- you'll not that the search and login are missing and console errors are pointing to the path of the lazyloaded file

**Review by joeniquette — APPROVED** [review]
We have the documentation for the issues. Still need a contact on the appropriate engineering team. @timwright12 please let me know who this is so we can have a conversation with them. 

CC: @christine-dillman @CoryTrimmUSDS

**Comment by timwright12** [comment]
We have an open request with teamsites engineers to have a chat, but it's not something they can fix. It's a much more systemic problem that we're working through, it's just going to take a while, but we'll need to get this fixed up in the meantime.

**Review by kelsonic — APPROVED** [review]

**Pull request merged**
