### PR TITLE
[VET TEC] - Remove production flags from applicant information page

### PR DESCRIPTION
**Pull request by devin-mccurdy**
## Description
Updated applicant information page should be accessible on prod

## Testing done
Tested locally

## Screenshots
image

## Acceptance criteria
- [x] Updated applicant information page is accessible in prod
- [x] 0994 is accessible to all logged in LOA1 users

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by zurbergram — APPROVED** [review]
LGTM

**Review by sonntag-adam — APPROVED** [review]

**Comment by dmccurdybah** [comment]
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!

**Comment by jbalboni** [comment]
@dmccurdybah How are you envisioning this working with currently in progress forms? It's hard to tell exactly if these are brand new fields that might trip up someone trying to submit a form they've already started.

**Comment by dmccurdybah** [comment]
> @dmccurdybah How are you envisioning this working with currently in progress forms? It's hard to tell exactly if these are brand new fields that might trip up someone trying to submit a form they've already started.

These are all existing fields in the schema, and were already returned by the prefill.  This will resolve an issue in production where users without the required fields weren't able to enter them manually.

**Comment by dmccurdybah** [comment]
@jbalboni These are all existing fields in the schema, and were already returned by the prefill.  This will resolve an issue in production where users without the required fields weren't able to enter them manually.

**Review by jbalboni — APPROVED** [review]

**Pull request merged**
