### PR TITLE
Update Applicant information labels to match new standards

### PR DESCRIPTION
**Pull request by zurbergram**
## Description
https://design.va.gov/patterns/form-labels has been updated with new labels 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/13965 is for updating the 1995 form, since these labels come from platform code this PR is to update the labels for all forms using Applicant information

## Screenshots
Screen Shot 2020-10-02 at 12 52 09 PM

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by peggygannon — APPROVED** [review]
@cvalarida Looks good.

**Review by cvalarida — APPROVED** [review]
Thanks for double-checking, @peggygannon :raised_hands:

**Comment by bkjohnson** [comment]
I believe this needed to be updated in another file as well, since it is used by app code:

https://github.com/department-of-veterans-affairs/vets-website/blob/3254011659b49fc9d45ea56198e3830e53a54e0b/src/platform/forms-system/src/js/definitions/fullName.js#L3

https://github.com/department-of-veterans-affairs/vets-website/blob/3254011659b49fc9d45ea56198e3830e53a54e0b/src/applications/ask-a-question/config/pages/contactInformationPage.js#L2

**Comment by zurbergram** [comment]
> I believe this needed to be updated in another file as well, since it is used by app code:
> 
> https://github.com/department-of-veterans-affairs/vets-website/blob/3254011659b49fc9d45ea56198e3830e53a54e0b/src/platform/forms-system/src/js/definitions/fullName.js#L3
> 
> https://github.com/department-of-veterans-affairs/vets-website/blob/3254011659b49fc9d45ea56198e3830e53a54e0b/src/applications/ask-a-question/config/pages/contactInformationPage.js#L2

@bkjohnson 
Those files appeared to only be used by `ask-a-question` which is codeowned by [department-of-veterans-affairs/orchid](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/CODEOWNERS#L71)

**Pull request merged**
