### PR TITLE
Fix flaky mobile facility locator Cypress test

### PR DESCRIPTION
**Pull request by ddzz**
## Description
This PR fixes a couple of race conditions in a flaky Cypress test.

## Testing done
- The test was run 30 times locally without any failures.

## Acceptance criteria
- [ ] Tests pass locally and on CI.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by holdenhinkle** [comment]
I ran the test 30 times locally (I wrapped that `it` call in a `for` loop) and got the following error 4 times (see the screenshot):

```
cy.type() failed because it requires a DOM element.

The subject received was:

  > Object{3}

The previous command that ran was:

  > cy.should()
```

Image 1:
image

Image 2:
image

**Comment by ddzz** [comment]
@holdenhinkle thanks for reviewing and testing! I didn't see any failures when I ran the test locally 30 times in headless mode. I'll try to recreate it.

**Comment by holdenhinkle** [comment]
> @holdenhinkle thanks for reviewing and testing! I didn't see any failures when I ran the test locally 30 times in headless mode. I'll try to recreate it.

Ah. I didn't try in headless mode. Trying now...

**Comment by holdenhinkle** [comment]
It passed all 30 times. LGTM. Thanks for your help on this!

image

**Review by holdenhinkle — APPROVED** [review]

**Review by 1Copenut — APPROVED** [review]
👍 LGTM. I reviewed the comments and have high confidence after both of you ran the test 30 times locally in headless mode.

**Comment by timwright12** [comment]
@ddzz came in this morning and saw this PR had been stuck on "unit tests" for 13hrs, so I restarted it in Jenkins. Can you keep an eye on it? I'm not sure why this update would cause that, but I don't see it happening in other PRs at this time.

**Comment by ddzz** [comment]
> @ddzz came in this morning and saw this PR had been stuck on "unit tests" for 13hrs, so I restarted it in Jenkins. Can you keep an eye on it? I'm not sure why this update would cause that, but I don't see it happening in other PRs at this time.
> 
> Update: unit tests appear to be passing fine in Circle, so we might just need to keep restarting until it passes in Jenkins

@timwright12 thanks for restarting it. I've had a couple of Jenkins failures on this branch, so I'll keep an eye on this until it passes.

**Review by timwright12 — APPROVED** [review]

**Review by kelsonic — APPROVED** [review]
LGTM 🎉

**Review by brangi — APPROVED** [review]

**Review by LanceGundersen — APPROVED** [review]
Passed here :shipit: 🚀

**Pull request merged**
