### PR TITLE
49913 - Revert pending requests filtering back to using the Created Date

### PR DESCRIPTION
**Pull request by ryanshaw**
This reverts this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/22626) 

## Description

https://github.com/department-of-veterans-affairs/va.gov-team/issues/49913
## Original issue(s)
[department-of-veterans-affairs/va.gov-team#49913](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49913)

## Testing done
- e2e testing
- unit testing

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by simiadebowale — APPROVED** [review]
LGTM!

**Comment by jenniemc** [comment]
@ryanshaw , using Jacob Reid as test user, I'm getting Bad Gateway in the review instance when submitting a VA request for mental health at Springfield OH.

```
    {
        "title": "Bad Gateway",
        "detail": "Received an an invalid response from the upstream server",
        "code": "VAOS_502",
        "source": {
            "vamfUrl": "https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/vaos/v1/patients/1013120805V887530/appointments",
            "vamfBody": "{\"id\":\"02bfc629-6744-4f19-8888-0917e9ac03dc\",\"code\":500,\"errorCode\":7004,\"traceId\":\"80d5cc4b90ca934fa63800c21ee2d253\",\"message\":\"failed to create appointment\",\"detail\":\"Could not create appointment through Vista Scheduling Provider\",\"meta\":{\"upstreamErrorSource\":\"mobile-appointment-service\",\"upstreamErrorId\":\"fc5f46fe-a193-4c71-911c-59a039aaf028\"}}",
            "vamfStatus": 500
        },
        "status": "502"
    }
```

**Review by vbahinwillit — APPROVED** [review]
LGTM!

**Comment by ryanshaw** [comment]
@jenniemc I have confirmed the error on staging too, using the same test user:

```
{
    "id": "d25363d5-5138-4257-b080-cfc96ca76065",
    "code": 500,
    "errorCode": 7004,
    "traceId": "510c144b02ce2f67d72d15533f389130",
    "message": "failed to create appointment",
    "detail": "Could not create appointment through Vista Scheduling Provider",
    "meta": {
        "upstreamErrorSource": "mobile-appointment-service",
        "upstreamErrorId": "c9481723-8b2f-444c-bcec-57912c7a2464"
    }
}
```

**Review by jenniemc — APPROVED** [review]
LGTM too!

**Comment by jenniemc** [comment]
> @jenniemc I have confirmed the error on staging too, using the same test user:
> 
> ```
> {
>     "id": "d25363d5-5138-4257-b080-cfc96ca76065",
>     "code": 500,
>     "errorCode": 7004,
>     "traceId": "510c144b02ce2f67d72d15533f389130",
>     "message": "failed to create appointment",
>     "detail": "Could not create appointment through Vista Scheduling Provider",
>     "meta": {
>         "upstreamErrorSource": "mobile-appointment-service",
>         "upstreamErrorId": "c9481723-8b2f-444c-bcec-57912c7a2464"
>     }
> }
> ```

Looks like the POST error is a BE issue and is being addressed on  https://issues.mobilehealth.va.gov/browse/VAOSR-4861

**Pull request merged**
