### PR TITLE
Hca fix package json

### PR DESCRIPTION
**Pull request by joesoftware**
Anne, I followed Albert's instructions on slack to add the dev dependency:

```
npm install -D nodemon
npm shrinkwrap
```

The first command updated `package.json` as expected, but the second left `nodemon` out of the `npm-shrinkwrap.json` file, so I followed with the command `npm shrinkwrap --dev`.

I'm not sure we actually wanted the dev dependencies in the shrink-wrap file, but I'll leave as is until Albert can weigh in later.

### CODE REVIEW

**Comment by akainic** [comment]
@joesoftware Looks like the build is failing. Not sure I'm the best person to review this PR. If you don't mind I'm going to reassign to @awong-dev.

**Comment by awong-dev** [comment]
Ugh...it looks like we hit a npm shrinkwrap bug.

@joesoftware I undid your `npm shrinkwrap --dev` just to keep this change more focused. I don't actually know if we want to include dev dependencies or not...open to thoughts, but let's do in another PR.

**Comment by awong-dev** [comment]
LGTM (even though I made the last commit).

Merging so people's setups are fixed.

**Comment by joesoftware** [comment]
I second the LGTM (even though it's already there) :+1:

**Pull request merged**
