### PR TITLE
New disability followup validations

### PR DESCRIPTION
**Pull request by cvalarida**
## Description
Adds length validations to the fields as outlined in https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16274

## Testing done
Unit tests written

## Screenshots
image

@peggygannon What should the error messages say? They're currently all like this (but with the proper number in there per field).

## Acceptance criteria
- [x] The fields trigger a validation error if there are too many characters entered

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by peggygannon — CHANGES_REQUESTED** [review]
Hi, @cvalarida. The character limit info should follow this pattern: 
Please briefly describe the injury or event while you were under VA care that caused your disability.
(350 characters maximum) (*Required)

Validation error = This field should be less than 350 characters

**Review by bshyong — APPROVED** [review]
LGTM

**Comment by cvalarida** [comment]
@peggygannon Updated content:
image

**Comment by peggygannon** [comment]
Hi, @cvalarida We need to add the character limit to the end of the question (see below in bold), so users know there is a limit. No need to add it in bold.. I made it bold so it's easier to see:

Please briefly describe the injury or event while you were under VA care that caused your disability.
(**350 characters maximum**) (*Required)

**Comment by cvalarida** [comment]
Ahh, gotcha. Okay. :+1:

**Comment by peggygannon** [comment]
@cvalarida Yes, I see. How about if do something like this when there are multiple parens... , removing the first instance. Like the below: 
 
Please briefly describe the injury or exposure that caused your condition. For example, I operated loud machinery while in the service, and this caused me to lose my hearing.
(400 characters maximum) (*Required)

Please tell us when this happened. If you’re having trouble remembering the exact date you can provide a year. (25 characters maximum)

**Review by markgreenburg — APPROVED** [review]
LGTM

**Review by peggygannon — APPROVED** [review]
@cvalarida Thanks. Updates look good.

**Pull request merged**
