### PR TITLE
Change appointment details where and tests

### PR DESCRIPTION
**Pull request by wullaski**
## Summary

- Changes the where area of the appointment details
- Updates unit tests
- Updates cypress tests

## Related issue(s)

- [department-of-veterans-affairs/va.gov-team#80942](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80942)

## Testing done

- Visual
- cypress
- unit

## Screenshots
**Day of -> in person**
check-in-in-person-2
**Pre Check in**
pre-check-in-cvt
pre-check-in-in-person
pre-check-in-phone
pre-check-in-vvc

## What areas of the site does it impact?

Day of -> details
Pre Check in -> details

## Acceptance criteria

- [ ] displays the correct information based on modality
- [ ] tests pass

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by benbrasso-agile6** [comment]
@wullaski there was a decision yesterday to NOT include the WHAT label and value when it's empty. <br><br>


Screenshot 2024-04-24 at 10 02 13 AM

**Comment by benbrasso-agile6** [comment]
Also, I think we want a small amount of spacing between the facility info and clinic info. Should be 16 px between the two. E.g., 16 px after Loma Landa (or if/when there's an address and directions link).

**Review by powellkerry — DISMISSED** [review]

**Comment by benbrasso-agile6** [comment]
> @wullaski there was a decision yesterday to NOT include the WHAT label and value when it's empty. This rule is specific to the appt detail page. NOT the appt list page.

> @benbrasso-agile6 We aren't currently using the value that populates the What label it's just static as VA appointment so it will always be there.

@loripusey we should separate this work out into its own ticket, since it's not related to this ticket, but it is a change that was decided yesterday for UAE

**Comment by benbrasso-agile6** [comment]
@wullaski good, but no paragraph break after the facility name (LOMA LINDA VA CLINIC). Then, you're good.

**Comment by loripusey** [comment]
@loripusey need ticket for this:
On details page:
if no Provider value don't display label 
Remove the "What" data & labels (i.e. don't display either)

**Comment by wullaski** [comment]
@benbrasso-agile6 Alright spacing should be fixed.

**Review by brianseek — APPROVED** [review]
🚀

**Comment by wullaski** [comment]
@benbrasso-agile6 I changed the way the spacing was added to different elements now it works with or without the facility address.
Screenshot 2024-04-25 at 10 09 12 AM
Screenshot 2024-04-25 at 10 09 35 AM

**Comment by benbrasso-agile6** [comment]
LGTM

**Comment by benbrasso-agile6** [comment]
Oh, are we moving to the other directions icon? Or, that's still the ongoing conversation that you and Brian were having yesterday?

**Pull request merged**
