### PR TITLE
Added link in caution flag specific to Ashford University.

### PR DESCRIPTION
**Pull request by U-DON**
Resolves department-of-veterans-affairs/gi-bill-comparison-tool#477.

> screen shot 2017-11-24 at 4 30 26 pm

The message before the link will have to be updated separately in GIDS. The Iowa link removed from the modal pertains to Ashford as well, and the relevant section is directly below the content that the "more information" link leads to.

### CODE REVIEW

**Comment by U-DON** [comment]
CC: @melwoodard

**Comment by melwoodard** [comment]
@U-DON can you make sure there's a period after the word "benefits" and before the more info link?

**Review by bshyong — APPROVED** [review]
LGTM besides Mel's comment on adding a period to the end of the `cautionFlagReason` content

**Comment by U-DON** [comment]
@melwoodard: The period has to come from the copy that's set in GIDS. Note that [in Ashford's profile on prod](https://www.vets.gov/gi-bill-comparison-tool/profile/21007103), there is a period, but we aren't setting that ourselves. That's just the data entered in GIDS.

**Comment by melwoodard** [comment]
Ah, that's right. Sounds good then!

**Comment by SPriceVA** [comment]
When will this go live?

**Comment by SPriceVA** [comment]
Also we would like to keep this language 'VA has notified Ashford that benefit payments may be suspended as early as January 8, 2018, unless corrective actions are taken'

**Pull request merged**
