### PR TITLE
Consolidate unit test runners

### PR DESCRIPTION
**Pull request by mchelen-gov**
## Description
deprecates `./script/run-coverage.sh` in favor of newer `./script/run-unit-test.js`

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by mchelen-gov** [comment]
it looks like jenkins is changing to `/application` dir before running coverage, and perhaps the report needs to be output to that dir?

**Comment by jbalboni** [comment]
@mchelen-gov The `--coverage` param is not getting passed to `run-unit-test.js` with the change you made. It would need to be `npm run test:unit -- --coverage`. The `--` tells npm to pass through the args after that point (or something like that).

**Comment by mchelen-gov** [comment]
> @mchelen-gov The `--coverage` param is not getting passed to `run-unit-test.js` with the change you made. It would need to be `npm run test:unit -- --coverage`. The `--` tells npm to pass through the args after that point (or something like that).

fixed, thanks!

**Review by cvalarida — APPROVED** [review]
No red flags here. :+1: :shipit:

**Pull request merged**
