### PR TITLE
Bugfix/sa 44503 contact preference page text message selection error

### PR DESCRIPTION
**Pull request by FernandoBoza**
## Summary

Updated MEB form > contact preference UI to include an alert to pop up on top of the last question with a button to redirect back to mobile phone section of the form/

## Testing done
- [x] Done

## Screenshots
image

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria
- [ ]  No error nor warning in the console.
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expect
- [x]  I added a screenshot of the developed feature

### CODE REVIEW

**Review by nathanielbuck — APPROVED** [review]
Looks great!

**Review by nathanielbuck — CHANGES_REQUESTED** [review]
I spoke a little too soon. The form interaction (error checking, logic, navigation, etc.) looks great, but the review page shows the radio buttons for the contact preferences. I think the `receiveTextMessages` field needs a `ui:reviewField`.
image

**Comment by FernandoBoza** [comment]
> I spoke a little too soon. The form interaction (error checking, logic, navigation, etc.) looks great, but the review page shows the radio buttons for the contact preferences. I think the `receiveTextMessages` field needs a `ui:reviewField`. 

Nice catch!

**Review by nathanielbuck — APPROVED** [review]

**Comment by nathanielbuck** [comment]
Okay, I just pushed a little change with a review field for `receiveTextMessages`. Check it out.

https://github.com/department-of-veterans-affairs/vets-website/pull/23130/files#diff-ae941bda5497c5205cde4a82206577e73f779606665de320d6ed5e4689fb77d1

**Pull request merged**
