### PR TITLE
content/wip/breadcrumb-updates

### PR DESCRIPTION
**Pull request by rroueche**
1. Remove Claims Process page: https://github.com/department-of-veterans-affairs/vets.gov-content/issues/239
- [x] move Claims Process child pages to appropriate new parent folders: apply, eligibility, and after-you-apply
- [x] delete Claims Process page
- [x] update links to those child pages throughout site to new URLs
- [x] submit ticket to redirect old URLs to new ones

2. Fix the apply path for Disability URLs: https://github.com/department-of-veterans-affairs/vets-website/issues/5197
- [x] rename parent folder apply (instead of apply-for-benefits)
- [x] update links to those apply-for-benefits child pages throughout site to new URLs
- [x] submit ticket to redirect old URLs to new ones

3. Update logic for right side bar: https://github.com/department-of-veterans-affairs/vets.gov-content/issues/187

### CODE REVIEW

**Comment by rroueche** [comment]
@bethpotts and @amybehrens these updates are complete, I've done a checkthrough to make sure everything looks OK in staging, could you take a pass as well before I merge these updates in?

https://vetsgov-pr-5238.herokuapp.com/

**Comment by bethpotts** [comment]
@rroueche @amybehrens Looks good to me!

**Review by ghost — APPROVED** [review]
I can't get herokuapp to load on either of the laptops today, so let's go with is being correct--I trust @rroueche and @bethpotts

**Comment by rroueche** [comment]
ok! @jkassemi is ok w/you for me to merge this PR today (I know you were doing some testing of it in dev so just checking)? And then @CyberKoz would you and your team be good to enact the redirects (https://github.com/department-of-veterans-affairs/devops/pull/1627) today or tomorrow?

**Comment by CyberKoz** [comment]
@rroueche we have the redirects alll tee'd up and ready to go.

**Comment by rroueche** [comment]
Alright great, thanks @CyberKoz ! @jkassemi I'm going to go ahead and merge this to master now then (this note is a heads up :) )

**Pull request merged**
