### PR TITLE
Detail page template.

### PR DESCRIPTION
**Pull request by ghost**
Closes department-of-veterans-affairs/vets.gov-team#2151

- Adds previous-next page navigation. Closes department-of-veterans-affairs/vets.gov-team#2153
- Re-ordering order of partials to fix USWDS grid/responsive queries bug.
- Adds side bar navigation, desktop view. Part of department-of-veterans-affairs/vets.gov-team#2151

### CODE REVIEW

**Comment by tiffanybbrown-va** [comment]
Action shot of the [sidebar navigation](https://vetsgov-pr-5401.herokuapp.com/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/). 

That page also features the next / previous navigation. I still need to add the responsive, slide-in-from-the-left navigation.

**Comment by tiffanybbrown-va** [comment]
Not sure why the branch builds are failing here, but at this point, @melwoodard I think it's ready for a design review. I know the border colors are off, so please tell me what you'd like those to be instead.

**Comment by melwoodard** [comment]
Thanks @tiffanybbrown-va! I'm going to do a more thorough review tomorrow, but a few quick things on the sidebar for now:

1. You can make the divider color `$color-gray-lighter`
2. On desktop, can you give 16px right margin/padding to the sidebar to give it a little more breathing room from the main column?
3. Responsive behavior looks a little funky currently - the sidebar jumps above the main column once my viewport is <1200px (maybe has to do with using `usa-grid` classes?). Ideally the sidebar would remain on the left down to the 768px break;  under that would convert to the mobile slide-out style.

**Comment by melwoodard** [comment]
Also adding @amybehrens and @suzchap for review.

**Comment by tiffanybbrown-va** [comment]
IDK why there's no USWDS breakpoint between 600 and 1201, but here we are. For some reason between 600px and 1200px, the `.usa-width-one-fourth` class has a width of 47%, and `.usa-width-three-fourths` has a width of 100%. I can't tell off-hand whether this is an easy fix or what the cause is.

Some of the responsive behavior is probably due to competing breakpoints.

**Comment by suzchap** [comment]
LGTM (and yay!)

**Comment by tiffanybbrown-va** [comment]
IDK what happened here, but on my local version, the navigation no longer works. Trying to trouble shoot now.

**Review by melwoodard — CHANGES_REQUESTED** [review]
Ok, here's a more detailed review:

1. Previous/next navigation looks great! One change - let's have the gray hover highlight just on the link text instead of the entire div.
2. Desktop sidebar looks great other than the changes noted earlier
3. Mobile sidebar needs a couple tweaks:
   - Reduce margin above the "more in this section" button by 2rem, and below it by 
   - Give the slide out menu white background a 1px `$color-gray-light` left border
   - Give the 'x' button in the slide out menu a larger target area - ideally 44x44px 
4. Can you explain how the process will work for the content team when setting up side nav + pagination for a particular set of pages?

Also -- if it turns out the grid fix isn't simple, I'd be inclined to split off the side nav work as a separate effort so it doesn't hold up the rest.

**Comment by tiffanybbrown-va** [comment]
I think the menu break point is part of a larger issue. Now tracking it in department-of-veterans-affairs/vets.gov-team#2475

**Review by melwoodard — CHANGES_REQUESTED** [review]
Thanks @tiffanybbrown-va, got a few more for you:

Previous/next hover background - sorry, I meant the background should show up just for the blue underlined text:

asbestos__vets_gov

Mobile sidebar needs a couple tweaks:
- Reduce margin above the "more in this section" button by 2rem, and below it by 1rem
- Give the slide out menu white background a 1px $color-gray-light left border

**Review by melwoodard — APPROVED** [review]
Updates look great, thanks! I'm good with this once the existing pages are reverted back to the old templates.

**Comment by rroueche** [comment]
@tiffanybbrown-va agree w/mel - looks good once pages are reverted back to old templates. also, could you provide a summary of what needs to be included (in YAML, md, html) on the page to enable these various things to display?

**Pull request merged**
