### PR TITLE
Fix broken link from Dec link check

### PR DESCRIPTION
**Pull request by peggygannon**
Fix broken link discovered in December dead link check.

### CODE REVIEW

**Comment by peggygannon** [comment]
@bethpotts PR for monthly dead link check.

**Comment by bethpotts** [comment]
@amybehrens and @lalexanderson-dsva Every month Peggy checks for broken links on our site and fixes the ones that are "not found" or a 404 or any other error. This community care link on the Schedule a VA Appointment page popped up in her check this month. She has fixed it so it redirects here (let us know if there's some other page you'd prefer, otherwise we'll proceed): https://www.ruralhealth.va.gov/vets/communitycare.asp 

On the live site, the current broken link off the Scheduling page is this: https://www.va.gov/COMMUNITYCARE/veterans.asp

**Comment by amybehrens** [comment]
https://www.va.gov/COMMUNITYCARE/index.asp

That link still works on other places on our site--maybe just an issue with scheduling? 
@bethpotts @lalexanderson-dsva

**Comment by peggygannon** [comment]
@bethpotts @amybehrens the Community Care link has been updated with this address: https://www.va.gov/COMMUNITYCARE/index.asp

**Review by bethpotts — APPROVED** [review]
Thanks, Peggy, looks great!

**Comment by peggygannon** [comment]
@phiden Ready for your review and merge! thank you!

**Review by phiden — APPROVED** [review]

**Pull request merged**
