### PR TITLE
Updating API URL references in test files

### PR DESCRIPTION
**Pull request by madebydna**
## Description
I was experimenting with changing the `*api.va.gov` references in test files to the new API url `*platform-api.va.gov`. It turns out that most references can be updated without breaking any unit or integration tests. That's because in most cases, the references are part of canned API responses and not used in any test assertions.

I tried parameterizing the API URL where possible, i.e. using the `API_URL` constant set as an environment variable. This will ensure that unit specs that actually check for the value of that variable should pass before and after the change. 

Certain references to `sandbox-api.va.gov` and `platform-api.va.gov` actually need to remain as they are, since they point to Lighthouse API endpoints and, as such, will not change. All of those instances are part of the `health-care-questionnaire` app that is currently not used in production. 

Please let me know if you think this could be merged in preparation for the move to the new API URLs.

## Original issue(s)
[department-of-veterans-affairs/va.gov-team#45514](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45514)

## Testing done
Unit and integration tests pass

### CODE REVIEW

**Review by vbahinwillit — COMMENTED** [review]
LGTM for VAOS changes.

**Review by acrollet — APPROVED** [review]

**Review by adamwhitlock1 — APPROVED** [review]
lgtm for personalization app changes

**Review by justin-trieu — APPROVED** [review]

**Review by simiadebowale — APPROVED** [review]
LGTM!

**Review by theodur — APPROVED** [review]

**Review by k80bowman — APPROVED** [review]

**Review by ryanshaw — APPROVED** [review]
VAOS changes look good.

**Review by maxx1128 — APPROVED** [review]

**Review by lzapson — APPROVED** [review]

**Review by Mottie — APPROVED** [review]

**Review by micahchiang — APPROVED** [review]

**Comment by madebydna** [comment]
@department-of-veterans-affairs/afs-code-reviewers, @department-of-veterans-affairs/vsa-public-websites-frontend, and @department-of-veterans-affairs/vsa-debt-frontend teams: Please review this PR that updates some test file references from `*api.va.gov` to `*platform-api.va.gov`. I need three more reviews, one from each team. Thank you so much!

**Review by allisonlu — APPROVED** [review]

**Review by ScottyRJames — APPROVED** [review]

**Review by FernandoBoza — APPROVED** [review]

**Pull request merged**
