### PR TITLE
Updates Content for addDisabilitiesRevised Page

### PR DESCRIPTION
**Pull request by tyler-spangler6**
## Summary

This updates the content and instructions for the addDisabilities page.  The new content has been through Veteran testing and provides more instructions for Veterans as the use the new combobox component to add conditions for disability compensation. Additionally, this updates the messages for validation of Veteran inputs. This content is behind the feature flag `disability_526_improved_autosuggestions_add_disabilities_page`.  

## Related issue(s)

- [#468](https://app.zenhub.com/workspaces/contention-classification-640a24db5dcd08457cebbc79/issues/gh/department-of-veterans-affairs/vagov-claim-classification/468)

## Testing done

- Unit tests are included in `addDisabilitiesRevised.unit.spec.jsx.

## Screenshots
_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

These changes are implemented in the 526EZ form in the addDisabilitiesRevised page. 

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by mchae-nava — DISMISSED** [review]
Code pass LGTM

**Review by tjheffner — DISMISSED** [review]

**Comment by lukey-luke** [comment]
Text content looks good to me.

I left a comment on [#468](https://github.com/department-of-veterans-affairs/vagov-claim-classification/issues/468) for some style differences from the spec I saw in the mobile view.

**Review by lukey-luke — DISMISSED** [review]

**Review by tjheffner — APPROVED** [review]

**Review by lukey-luke — APPROVED** [review]
Thanks for updating the label string. LGTM

**Review by lukey-luke — APPROVED** [review]
Thanks for updating the combobox title. LGTM.

**Review by harshilmoradia — APPROVED** [review]

**Pull request merged**
