### PR TITLE
Adding third link to Set up accredited rep

### PR DESCRIPTION
**Pull request by kellyskennedy**

### CODE REVIEW

**Comment by kellyskennedy** [comment]
@peggygannon This is ready for you, but heads up: I couldn't see the deployment cuz Vets.gov is down. Thanks!

**Review by peggygannon — APPROVED** [review]
@kellyskennedy Copy edit is complete. Just made one adjustment to the form name. Thx.

**Comment by kellyskennedy** [comment]
@bethpotts this is ready for you

**Comment by bethpotts** [comment]
@peggygannon Please proof my edits!

@kellyskennedy For awareness. Take a look at the way I tweaked the language/set-up and see if you agree.

**Comment by peggygannon** [comment]
@bethpotts Ok, looks good. I removed instances of "form" I think this can be merged.

**Review by bethpotts — APPROVED** [review]

**Comment by kellyskennedy** [comment]
@phiden Could you merge this please? Thanks!

**Pull request merged**
