### PR TITLE
Resolves #2713; explicitly define layouts in all pages

### LINKED ISSUE #2713: Remove default layout
Having a default layout in metalsmith makes it impossible to push out a bare HTML page. It's also less explicit.  Better to just make us write in the layout for each page explicitly.

### PR DESCRIPTION
**Pull request by bshyong**
Addresses #2713 

cc @awong-dev. This is ready for review and merge.

### CODE REVIEW

**Comment by awong-dev** [comment]
Branch looks sane!  Did you manage to diff the generated outputs to verify nothing really changed?

With this, I would expect the diff to be pretty much whitespace only.

**Comment by bshyong** [comment]
I'll diff today—FWIW I manually clicked through the affected pages and didn't see any visual regressions

**Comment by bshyong** [comment]
@awong-dev diffed and looks like only whitespace changes
`diff --brief -r build build_old`

**Comment by bshyong** [comment]
Am I free to merge this @awong-dev?

**Comment by awong-dev** [comment]
Lgtm

Yes! Sorry. I'm not at a computer to do the merge. Feel free to push it in
though. Thanks for doing the diff!

**Pull request merged**
