### PR TITLE
[FE] 10-10CG - Facility page: Create connection from search input to MapBox API Client

### PR DESCRIPTION
**Pull request by JoshingYou1**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- _Adds API calls for both MapBox and Lighthouse Facilities for the 1010CG form_

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/57860

## Testing done

- Added unit tests for both actions

## What areas of the site does it impact?

The 1010CG form

## Acceptance criteria
- Work with PM to obtain access token for MapBox connection
- Create MapBox client and set up all necessary actions
- Test connection to ensure proper coordinates are being returned
- Ensure all work is implemented behind feature flag and not being ran in production

### Quality Assurance & Testing

- [X] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [X] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [X] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [X] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [X] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Comment by JoshingYou1** [comment]
@longmd , I'm not very familiar with the Sentry stuff. Is that something I should incorporate into these actions for error logging purposes?

**Review by mkerns1 — APPROVED** [review]
LGTM!

**Review by longmd — APPROVED** [review]

**Comment by longmd** [comment]
@JoshingYou1 , I don't think it would hurt to add in the Sentry logging. Just maybe copy what I did in the `VaMedicalCenter` widget and you'll be good to go.

**Comment by JoshingYou1** [comment]
> @JoshingYou1 , I don't think it would hurt to add in the Sentry logging. Just maybe copy what I did in the `VaMedicalCenter` widget and you'll be good to go.

Okay, I'll add it in there. Thanks Matt!

**Pull request merged**
