### PR TITLE
HCA text updates from SiP walkthrough

### PR DESCRIPTION
**Pull request by jbalboni**
Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3594

screen shot 2017-07-26 at 4 34 29 pm
screen shot 2017-07-26 at 4 33 48 pm
screen shot 2017-07-26 at 4 33 24 pm
screen shot 2017-07-26 at 4 33 14 pm

### CODE REVIEW

**Review by cehsu — APPROVED** [review]
Looks good to me.

**Review by cvalarida — CHANGES_REQUESTED** [review]
There are just a few things left from that ticket:

- [ ] Bolding the Note: in the blue box on `household-information/financial-disclosure:`
- [ ] Capitalizing 'Prisoner of War' on the financial disclosure page (found in `src/js/hca/helpers.jsx`)
- [ ] Lower case 'Net Income' in the `veteranNetIncome` label
- [ ] Sentence case 'Net income from farm, ranch, property, or business' in the child's `netIncome` (found in `src/js/hca/definitions/child.js`)

**Comment by jbalboni** [comment]
@cvalarida Updated.

**Review by cvalarida — APPROVED** [review]
Awesome!

**Pull request merged**
