### PR TITLE
Check in/bug/33923/flaky tests

### PR DESCRIPTION
**Pull request by mdewey**
## Description
- Fixed some flaky tests that were testing useEffect functionality, if this is still an issue, I will delete these unit tests and ensure they are being covered by cypress tests

## Original issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/33923

### CODE REVIEW

**Review by timwright12 — APPROVED** [review]

**Review by dcgoodwin2112 — APPROVED** [review]
LGTM! All tests ran locally multiple times without any flake.

**Review by acrollet — COMMENTED** [review]
Do we have the choma ID from a failing run, and if so does it pass with that?

**Comment by mdewey** [comment]
@acrollet  Yes, I used the exact CHOMA_SEED and all the tests passed

**Comment by mdewey** [comment]
Screen Shot 2021-12-14 at 2 31 44 PM

**Pull request merged**
