### PR TITLE
Creating a prebuild script and adding command.

### PR DESCRIPTION
**Pull request by robbiethegeek-usds**
When starting to look at the build.js seems like it could be broken into some more semantic pieces, and figured I would start to tease apart. This is just a pull all the stuff that happens before the build starts into a prebuild script and create a new npm run script for prebuild that will be run automatically on npm run build.

### CODE REVIEW

**Comment by robbiethegeek-usds** [comment]
When starting to look at the build.js seems like it could be broken into some more semantic pieces, and figured I would start to tease apart.  This is just a pull all the stuff that happens before the build starts into a prebuild script and create a new npm run script for prebuild that will be run automatically on npm run build.

**Review by cvalarida — COMMENTED** [review]
Looks good, but how is the prebuild script run automatically when the build script is?

**Comment by robbiethegeek-usds** [comment]
@cvalarida it is a magical feature of npm scripts :) if there is a pre or a post it will be run before and/or after

**Comment by cvalarida** [comment]
Good to know! Thanks, @robbiethegeek-usds!

**Review by cvalarida — APPROVED** [review]

**Review by jbalboni — APPROVED** [review]

**Review by jkassemi — APPROVED** [review]

**Comment by robertfairhead** [comment]
@robbiethegeek-usds did you check on if this will impact the heroku builds? it uses a lightly different build path than the normal site builds

**Comment by robbiethegeek-usds** [comment]
@jkassemi can you confirm that the heroku build for this PR was successful and make sure nothing there needs to change?

**Comment by jkassemi** [comment]
@robbiethegeek-usds @robertfairhead not seeing any issues with the Heroku build! 🚂

**Pull request merged**
