### PR TITLE
remove prod flag per story 5639

### PR DESCRIPTION
**Pull request by shawkey-daniel**
## Description
As a developer, I need to remove the production / feature flag for the SCO contact details so that the information is available in production.

## Testing done
local testing

## Screenshots
image

## Acceptance criteria
- [X] 1. The work completed in #5362 is delivered to the production environment.

## Definition of done
- [X] Events are logged appropriately
- [X] Documentation has been updated, if applicable
- [X] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by shawkey-daniel** [comment]
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5639

**Comment by shawkey-daniel** [comment]
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5639

**Comment by shawkey-daniel** [comment]
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5639

**Review by devin-mccurdy — APPROVED** [review]
LGTM

**Review by devin-mccurdy — APPROVED** [review]
LGTM

**Review by delli-gatti-michael — APPROVED** [review]
Passes QA Testing

**Review by jhonny218 — APPROVED** [review]
LGTM

**Pull request merged**
