### PR TITLE
Renaming _health-care to _healthcare, updating URL config.

### LINKED ISSUE #2442: Healthcare urls need to be updated
In `health-care/index.html` the urls are still pointing to `health-care` instead of `healthcare`.

### PR DESCRIPTION
**Pull request by webinista**
- Closes #2442
- Related to #2435

### CODE REVIEW

**Comment by webinista** [comment]
@akainic @emilyville Assigning to both of you. I think this is all that's necessary.

**Comment by akainic** [comment]
This is great, thanks @webinista! Looks like there are still some links that need to be updated?

**Comment by webinista** [comment]
@akainic There's a JavaScript build/testing issue at play that I do not know enough to debug.

**Comment by akainic** [comment]
@webinista I think it's because there are still references to `health-care` in some of the test files. Example: In `spec/javascripts/healthcare/components/IntroductionSection.spec/jsx`, a file is being imported and the path is still using `health-care`.

**Comment by akainic** [comment]
LGTM!

**Comment by akainic** [comment]
Actually looks like there are a few more references to `health-care

**Comment by webinista** [comment]
I did one last search and replace for `health-care` and changed them to `healthcare`. Nothing broke, so I guess we can merge :-)

**Comment by akainic** [comment]
LGTM! Thanks @webinista!

**Pull request merged**
