### PR TITLE
Update employment-support.md

### PR DESCRIPTION
**Pull request by mollyblake**
replaced dummy links with:
/employment/job-seekers/search_jobs
/employment/commitments

### CODE REVIEW

**Comment by rcarthur** [comment]
We could use a little help with this one - failing 2 checks.  Thank you!!!

**Comment by awong-dev** [comment]
totally! This one points to an error in your change. If you click through the "Details" link next to the red, you will see the test log. It looks daunting at first, but it's actually not that hard to read. The key is to scroll to the bottom and work backwards until you see lines in red. Here it's line on line 299 or 288 depending on which link you click. The error message should tell you which files have an issue.

In this case, you are creating links to something non-existent...

**Comment by awong-dev** [comment]
Feel free to reassign to me or start up a chat on #vetsdotgov slack tomorrow if this doesn't make sense.

**Comment by emilyville** [comment]
I think this has been done / undone a few times because these links aren't working. Are you sure these are the right locations?

*  internally linking to /employment/commitments, which does not exist (line 158)
*  internally linking to /employment/job-seekers/search_jobs, which does not exist (line 158)

**Comment by ayaleloehr** [comment]
Those links do not exist _in this repo_, but they will exist and are coming from the VEC repo. For example, you can go to https://staging.vets.gov/employment/commitments and see it's there. 

Not sure how to handle the link checking from this repo to that one though, as Travis doesn't know about the other repo when running tests.  My question I guess would be that we already have links in other places (such as [here](https://github.com/department-of-veterans-affairs/vets-website/blob/def059147e1735d453ea5d5ef2ec24aef2bb2964/index.html#L40)) to the GI Bill Comparison Tool, which isn't in this repo; why does Travis not fail on those as well?

**Comment by ayaleloehr** [comment]
More diligence shows it's because of this line: https://github.com/department-of-veterans-affairs/vets-website/blob/0fa1d59fff92c10fea6a5b677a625b870300636c/Rakefile#L154

**Comment by ayaleloehr** [comment]
@emilyville If you review and merge [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/1513) first, then rerun these tests, I think this should pass.

**Comment by emilyville** [comment]
YAAAAAAAAYYY!!!!

**Comment by mollyblake** [comment]
So I actually did it correctly? MIC DROP

**Pull request merged**
