### PR TITLE
Update links from accesstocare.va.gov/sign-in-help to help desk + 711

### PR DESCRIPTION
**Pull request by kelsonic**
## Description
**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/19893

This PR implements the following:

```jsx
call our MyVA411 main information line for help at
<a href="tel:18006932411" aria-label="8 0 0. 6 9 3. 2 4 1 1.">
  800-698-2411
</a>
(TTY: <Telephone contact={CONTACTS['711']} pattern={PATTERNS['911']} />).
```

into these areas:

| Before | After |
| --- | --- |
| If you still can’t sign in, please use our online form to submit a request for help | If you still can't sign in, call our MyVA411 main information line for help at 800-698-2411, select 0 (TTY: 711). |
| We’re having trouble signing you in to VA.gov right now because we found more than one DoD ID number for you. To fix this issue, please submit a request to get help signing in. | We’re having trouble signing you in to VA.gov right now because we found more than one DoD ID number for you. To fix this issue, call our MyVA411 main information line at 800-698-2411, select 0 (TTY: 711) |
| We’re having trouble signing you in right now because your My HealtheVet account number doesn’t match the account number on your VA.gov account. To fix this issue, please submit a request to get help signing in. | We’re having trouble signing you in right now because your My HealtheVet account number doesn’t match the account number on your VA.gov account. To fix this issue, call our MyVA411 main information line at 800-698-2411, select 0 (TTY: 711) |
| If you’ve taken the steps above and still can’t sign in, please use our online form to submit a request for help. | If you've taken the steps above and still can't sign in, please call our MyVA411 main information line at 800-698-2411, select 0 (TTY: 711) |
| To find out if this is about an account with the Department of Defense: You can submit a request to get help signing in | To find out if this is about an account with the Department of Defense: Call our MyVA411 main information line at 800-698-2411, select 0 (TTY: 711) |

## Acceptance criteria
- [x] Update accesstocare.va.gov/sign-in-help links to help desk + 711 numbers

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by AGarcia-Clarity** [comment]
@kelsonic Are we no longer tracking the analytics when a user tries to get help?

**Review by asg5704 — APPROVED** [review]
LGTM.  Just curious if there are any plans to add the analytics back?

**Comment by kelsonic** [comment]
Good question, asking [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19893#issuecomment-834453494) 🙂

**Review by oseasmoran73 — APPROVED** [review]

**Review by RLHecht — COMMENTED** [review]
@kelsonic For the change on line 67 can you take out the colon and make it a comma and lowercase "call" after it. So it reads: To find out if this is about an account with the Department of Defense, call our MyVA411 main information line for help at..." Thank you!

**Comment by kelsonic** [comment]
@RLHecht thanks! Updated! 🙂

**Review by RLHecht — APPROVED** [review]

**Pull request merged**
