### PR TITLE
content/wip/piano keys apply.md

### PR DESCRIPTION
**Pull request by bethpotts**

### CODE REVIEW

**Comment by bethpotts** [comment]
@amybehrens @rroueche Ready for your approval! The purpose of this PR was to take a careful look at (and edit as needed) piano key language and placement on the Eligibility, Application Process, and After You Apply pages that we launched last week. I have proofread Danielle's excellent work and clicked each piano key to make sure they go to the right place. Thumbs up from me... your turn!

**Comment by rroueche** [comment]
@bethpotts and @DanielleSoCompany thanks for the great work! I'm checking now.

**Review by rroueche — APPROVED** [review]

**Comment by rroueche** [comment]
@amybehrens once you review and approve, I'll merge!

**Review by ghost — APPROVED** [review]

**Comment by amybehrens** [comment]
All set, nice work!

Amy Behrens
U.S. Digital Service<https://www.usds.gov/>
 [cid:image001.png@01D2A3D8.7DE72750]

**Comment by rroueche** [comment]
alright! all set, merged in, should go live either today or tmrw.

**Pull request merged**
