### PR TITLE
Combining .va-h-ruled, highlight rulesets. closes #4175

### LINKED ISSUE #3660: Unify ruled heading styles
We currently have `.va-h-ruled` and now/soon`.rx-heading`. They're styled a bit differently, but aren't so radically different that they can't be combined. 

Example of `.va-h-ruled`
screen shot 2016-11-01 at 12 44 36 pm

Example of `rx-heading`:

screen shot 2016-11-01 at 12 45 23 pm

This is also affected by #2347.

### LINKED ISSUE #4175: Header clean up
@melwoodard did an awesome job auditing headers all across our tools. We need to clean up the headers for Rx detail and glossary pages.

### Detail page
1. Aligned with top of Prescription name
2. Contact should be `h4` with border bottom.
screen shot 2016-11-30 at 7 00 02 pm

claims for reference:
63974bb2-b6db-11e6-87a6-2d4cef6e12d7-1

@mel is the primary blue the color we are going with across vets.gov for border bottom?

3. Order History should be `h2`

### Glossary page
1. Glossary should be `h1`
2. Status headers `h2` with `border-bottom`
3. Definition headers `h3`

glossary page

### PR DESCRIPTION
**Pull request by webinista**
- Also added TODO comments to facility-locator.scss.
-Also closes #3660

### CODE REVIEW

**Comment by crwallace** [comment]
@webinista -- Why are we adding TODOs instead of just holding until its time for the change?

**Comment by webinista** [comment]
I added TODOs as notes for things that should be fixed at some point, mostly to make finding-and-fixing easier. Some of these TODOs are already tracked as tasks. Most are not, or they're interrelated to something that _is_ tracked as a task. Most TODOs are, unrelated to pending design changes.

They're SCSS comments, so they're not adding weight to the final output.

**Comment by crwallace** [comment]
@webinista -- I get the purpose of TODOs I just wonder if they are better served in github issues since we don't scrape the code and create issues out of them. We could connect the issues as dependencies to finish some work before other work.

**Comment by webinista** [comment]
Seems just as weird to me to create a GitHub issue for a small, not-at-all urgent improvement.

That said: what's the action here: would you like me to remove the TODO, create a GitHub issue or both?

**Comment by crwallace** [comment]
Maybe it would be helpful for tracking if we had github issues associated with the TODOs. @jcmeloni any thoughts on this?

**Comment by jcmeloni** [comment]
My thoughts:
- I don't tend to like todos floating around code for more than a couple weeks, but todos are super helpful as pointers 
- If there's no trend/precedent for constantly scanning for todos in code, def stick them in issues
- If the todos are of a small size, and you could do all todos in a day or day and a half give or take, i'd just throw all of them in one issue and bust them out -- that's for retroactive to-do'ing in bulk
- Ongoing todos, like stuff you come across while working on other things and are all "we totally should fix that", I'd slap a todo in the code, make a single issue for it, add the "debt" label, and make sure that you talk about it in sprint planning like "I make a bunch of todos last sprint and i think we should knock 'em out" and we'll get them in the mix so they don't just go back into the abyss.

"Julie, any thoughts on this" lol :)

**Comment by webinista** [comment]
Thanks for this guidance, @jcmeloni. 

The worst problems flagged by TODOs in our SCSS are [already GitHub issues](department-of-veterans-affairs/vets.gov-team/issues/656). 

If it's not yet a GitHub issue, it's because:

1. It's thoroughly blocked by one that's already tracked.
2. It would not cause spillover effects if it was never resolved.

Some additional context: I added almost all of the current TODOs in our SCSS back when I was the person maintaining most of it. My intention at the time was to revisit those less significant TODOs once the blocking issues were resolved. 

The work that I was doing and trying to prioritize (refactoring our selectors, implementing a CSS naming convention, creating a pattern library) was mistimed. I moved to Kudos before getting a chance to fix the worst of our SCSS problems. Those GitHub issues and related TODO management fell by the wayside.

That said point 2 applies to _this particular_ TODO, which is why I didn't bother to create a GitHub issue. I'll happily create one. Would you also like me to update the TODO in some way before merging this PR?

**Comment by jcmeloni** [comment]
@webinista Totally understand the history.  You've done a great job trying desperately to manage the debt, and that work is very clear to me!

**Comment by jkassemi** [comment]
Updated with latest from master to trigger new build with latest Jenkins configuration as part of https://github.com/department-of-veterans-affairs/devops/issues/1352.

I expect this branch to also have issues with the logs in the Blue Ocean UI (https://github.com/department-of-veterans-affairs/devops/issues/1360).

**Comment by jcmeloni-usds** [comment]
@webinista Any reason not to merge at this point?

**Comment by webinista** [comment]
@jcmeloni Not as far as I'm concerned.

**Comment by jcmeloni-usds** [comment]
@webinista Cool. I'm pressing the button.

**Pull request merged**
