### PR TITLE
Adding new piano keys pattern. closes #1445

### LINKED ISSUE #1445: Piano Key Redesign
We want to prototype a redesign of the piano keys for large screens. 
The idea is that we don't want the grey go to across the page and the hover features will remain the same. Length will be same as the 75 characters body copy.  

revised gi bill page

https://www.vets.gov/education/gi-bill/

### PR DESCRIPTION
**Pull request by webinista**
- Adds a va-pianokeys partial and va-navigation--piano component
- Moving color-green-darkest to _variables.scss.
- Cleaning up the piano markup

modified:   _education/gi-bill.md
modified:   _sass/_va.scss
new file:   _sass/components/_va-pianokeys.scss
modified:   _sass/core/_variables.scss

### CODE REVIEW

**Comment by webinista** [comment]
The left border does not expand in this iteration of piano keys. Because the max-line length is shorter, some lines now wrap. Having the border's width expand causes the wrapping point to change for longer lines of text.

**Comment by emilyville** [comment]
I think the alignment is supposed to be to the left? @gnakm @webinista Looks good on mobile, though!

screencapture-127-0-0-1-4000-education-gi-bill-1458782235134


shaggydogreut_468x497

**Comment by gnakm** [comment]
Looks great and ditto on the left alignment!

**Comment by emilyville** [comment]
lgtm! sending over to @gnakm to handle whether we want to merge or show to friends first.

**Comment by gnakm** [comment]
We received feedback from vet.gov team and will not be moving forward with this prototype. Piano Keys will most likely become links.

**Pull request closed without merging**
